### PR TITLE
Automatically Fully Download Files through HTTPFS if no length header is provided

### LINKED ISSUE #3731: Seeming network error when downloading a large file and converting it to parquet.
This fails pretty consistently for me almost always at different places in the stream.  I have no problem with the same file over 'wget'. I'm building a script that loads the imdb data set and converts it to parquet files. Makes for a nice example.
```
  install "httpfs";
  load "httpfs";
  copy (
    SELECT *
      REPLACE (
        str_split(primaryProfession,',') as primaryProfession,
        str_split(knownForTitles,',') as knownForTitles,
        case WHEN regexp_matches(deathYear,'[0-9]+') THEN CAST(deathYear as integer) END as deathYear,
        case WHEN regexp_matches(birthYear,'[0-9]+') THEN CAST(birthYear as integer) END as birthYear
      )
    FROM read_csv_auto('https://datasets.imdbws.com/name.basics.tsv.gz', delim='\t', quote='',header=True)
  ) to 'name_basics.parquet' (FORMAT 'parquet', CODEC 'ZSTD')
  ```

image

### LINKED ISSUE #5924: CSV Auto-Detection fails when loading file over HTTP, but succeeds locally
### What happens?

Trying [this article](https://csvbase.com/blog/2) in DuckDB I noticed our CSV auto-detection fails when loading the example file over HTTPS.

### To Reproduce

```sql
select * from read_csv_auto('https://csvbase.com/meripaterson/stock-exchanges');
-- Error: Invalid Input Error: Error in file "https://csvbase.com/meripaterson/stock-exchanges": CSV options could not be auto-detected. Consider setting parser options manually.
```

It also fails when using the fallback `.csv` url:

```sql
select * from read_csv_auto('https://csvbase.com/meripaterson/stock-exchanges.csv');
-- Error: Invalid Input Error: Error in file "https://csvbase.com/meripaterson/stock-exchanges.csv": CSV options could not be auto-detected. Consider setting parser options manually.
```

It succeeds when downloading the file:

```sql
-- wget https://csvbase.com/meripaterson/stock-exchanges.csv
D select * from read_csv_auto('stock-exchanges.csv') limit 5;
┌────────────────┬───────────────┬──────────────────────────┬───────────────────────────────────────┬─────────┬──────────────┐
│ csvbase_row_id │   Continent   │         Country          │                 Name                  │   MIC   │ Last changed │
│     int64      │    varchar    │         varchar          │                varchar                │ varchar │     date     │
├────────────────┼───────────────┼──────────────────────────┼───────────────────────────────────────┼─────────┼──────────────┤
│              1 │ Africa        │ Lesotho                  │ HYBSE                                 │ NULL    │ 2019-03-25   │
│              2 │ Asia          │ Kazakhstan               │ Astana International Financial Centre │ AIXK    │ 2018-11-18   │
│              3 │ Africa        │ South Africa             │ ZAR X                                 │ ZARX    │ 2018-11-18   │
│              4 │ South America │ Argentina                │ Bolsas y Mercados Argentinos          │ NULL    │ 2018-04-02   │
│              5 │ North America │ United States of America │ Delaware Board of Trade               │ NULL    │ 2018-04-02   │
└────────────────┴───────────────┴──────────────────────────┴───────────────────────────────────────┴─────────┴──────────────┘

```

### OS:

MacOS

### DuckDB Version:

Latest master

### DuckDB Client:

CLI

### Full Name:

Mark

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### LINKED ISSUE #6388: httpfs Error: Catalog Error: Table with name https://www... does not exist!
### What happens?

SELECT from http url that return a csv failed on windows (not try on linux)

SELECT count(*) from 'https://www.data.gouv.fr/fr/datasets/r/6d186965-f41b-41f3-9b23-88241cc6890c';
Error: Catalog Error: Table with name https://www.data.gouv.fr/fr/datasets/r/6d186965-f41b-41f3-9b23-88241cc6890c does not exist!
Did you mean "pragma_database_list"?
LINE 1: SELECT count(*) from 'https://www.data.gouv.fr/fr/datasets/r...

### To Reproduce

Launch Duckdb.exe cli on cmd or powershell

```SQL
install 'httpfs';
load 'httpfs';
SELECT count(*) from 'https://www.data.gouv.fr/fr/datasets/r/6d186965-f41b-41f3-9b23-88241cc6890c';
```

The url should be stable a be tested as is

### OS:

Windows 10

### DuckDB Version:

0.7.0

### DuckDB Client:

Windows CLI

### Full Name:

Romain Ferraton

### Affiliation:

Architecture & Performance

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by pdet**
The length header is optional, and it seems that servers that produce files upon request tend not to send it to us.
Not having a length header makes it impossible to use Get Range requests. In these cases, we default to fully downloading the file upfront.

I guess the main disadvantages of that is not being able to parallelize the requests and materializing the file in memory (Although we could probably have a buffer managed array there).

I've added a new parameter, `get_request_file_size`, that defaults to 100Mb. If the file is bigger than this we force the user to increase the value, and throw an error suggesting that (if they have control of the server) they should emit the length header. This might be a bit controversial, and we might want to have a lower value as default, but a warning message seems important since, in cases where the header could be provided, this can bring unnecessary performance bottlenecks. 

Fix: #6388 
Fix: #5924
Fix: #3731

### CODE REVIEW

File: extension/httpfs/httpfs.cpp [hunk 1]
```diff
@@ -317,9 +386,9 @@ void HTTPFileSystem::Read(FileHandle &handle, void *buffer, int64_t nr_bytes, id
 	auto &hfh = (HTTPFileHandle &)handle;
 	idx_t to_read = nr_bytes;
 	idx_t buffer_offset = 0;
-	if (location + nr_bytes > hfh.length) {
-		throw IOException("out of file");
-	}
+	//	if (location + nr_bytes > hfh.length) {
```
Comment (samansmink) [inline extension/httpfs/httpfs.cpp:389]: i think this can be deleted?

File: third_party/httplib/httplib.hpp [hunk 2]
```diff
@@ -3293,7 +3299,10 @@ inline bool read_content_with_length(Stream &strm, uint64_t len,
 	uint64_t r = 0;
 	while (r < len) {
 		auto read_len = static_cast<size_t>(len - r);
-		auto n = strm.read(buf, (std::min)(read_len, CPPHTTPLIB_RECV_BUFSIZ));
+		auto n = (uint64_t) strm.read(buf, (std::min)(read_len, CPPHTTPLIB_RECV_BUFSIZ));
```
Comment (samansmink) [inline third_party/httplib/httplib.hpp:3302]: I feel like we would prefer to have this code not as a modification to the inlined library and ideally handle this only from the content receiver callback

Also, is this even necessary? aren't you already handling this in the content receiver already?

File: test/sql/copy/csv/test_csv_httpfs.test [hunk 3]
```diff
@@ -0,0 +1,93 @@
+# name: test/sql/copy/csv/test_csv_httpfs.test
+# description: This test triggers the http prefetch mechanism.
+# group: [csv]
+
+require httpfs
+
+query IIIIII rowsort
+SELECT * from read_csv_auto('https://www.data.gouv.fr/fr/datasets/r/6d186965-f41b-41f3-9b23-88241cc6890c');
```
Comment (samansmink) [inline test/sql/copy/csv/test_csv_httpfs.test:8]: These tests will likely break silently at some point either by the files being gone, or the servers supporting range requests.

Ideally we would have a set of test servers with different endpoints one of which does not support range requests. I think that can come in another PR though

**Review by samansmink — COMMENTED** [review]
Very cool! not getting a content-length / not supporting the range header seems to be quite common

I added a few small comments

File: third_party/httplib/httplib.hpp (hunk 2 above)
Comment (pdet) [reply third_party/httplib/httplib.hpp:3302]: Yes, I was also not super happy changing the third-party lib.
The nice thing is this can be an early-out in certain situations. Since the to-be-read batch can already be over our limit.

The content receiver still has to process stuff, potentially wasting more work.

File: test/sql/copy/csv/test_csv_httpfs.test (hunk 3 above)
Comment (pdet) [reply test/sql/copy/csv/test_csv_httpfs.test:8]: That is very much true, it can also break from API changes, I'll add a comment on the header of the test,

File: extension/httpfs/httpfs.cpp (hunk 1 above)
Comment (pdet) [reply extension/httpfs/httpfs.cpp:389]: 🙈

File: third_party/httplib/httplib.hpp (hunk 2 above)
Comment (samansmink) [reply third_party/httplib/httplib.hpp:3302]: Ah that's a fair point. I would however still argue that the added code complexity from writing our code in an inlined lib is not worth saving reading the bytes. I mean this should be an edge case that a user will only run when his `get_request_file_size` is too low, right?

Comment (pdet) [reply third_party/httplib/httplib.hpp:3302]: By default, the `get_request_file_size = 100mb' maybe we should make it smaller and remove it from the third-party lib?
@Mytherin, any opinions here?

Comment (Mytherin) [reply third_party/httplib/httplib.hpp:3302]: I agree that editing the httplib is likely not worth the hassle. Perhaps we should just always download the entire file and remove the file size parameter entirely? I also wonder how this PR relates to #6467 - does that solve some of the cases solved by this PR as well?

Comment (pdet) [reply third_party/httplib/httplib.hpp:3302]: I've ran the same tests here with the #6467 PR, it seems that the range-requests can't cover the missing content-length header.

I've removed the file size requirement entirely.

**Comment by Mytherin** [comment]
@samansmink could you have another look at this one?

File: extension/httpfs/httpfs.cpp [hunk 4]
```diff
@@ -327,47 +383,66 @@ void HTTPFileSystem::Read(FileHandle &handle, void *buffer, int64_t nr_bytes, id
...
-
-			hfh.buffer_idx += buffer_read_len;
-			hfh.buffer_available -= buffer_read_len;
-			hfh.file_offset += buffer_read_len;
-		}
-
-		if (to_read > 0 && hfh.buffer_available == 0) {
-			auto new_buffer_available = MinValue<idx_t>(hfh.READ_BUFFER_LEN, hfh.length - hfh.file_offset);
+	if (!hfh.range_read) {
+		GetRequest(hfh, hfh.path, {});
```
Comment (samansmink) [inline extension/httpfs/httpfs.cpp:387]: I'm pretty sure this does a Get request for every `HTTPFileSystem::Read(FileHandle &handle, void *buffer, int64_t nr_bytes, idx_t location)`, a function that is not just internally used in the `HTTPFileSystem::Read(FileHandle &handle, void *buffer, int64_t nr_bytes)`, but part of the Filesystem API. 

As discussed with @pdet already: we need some test to ensure we make the correct amount of request (1 get request for the whole file) This can be done with a regex test on the explain analyze output of a query, since that prints the number of requests that have been made. To force the single file download for a parquet file, we probably want to add either a `force_full_file_download` or add this to the `pragma enable_verification` somehow.

File: extension/httpfs/httpfs.cpp [hunk 5]
```diff
@@ -496,16 +571,20 @@ void HTTPFileHandle::Initialize(FileOpener *opener) {
...
-
-	try {
-		length = std::stoll(res->headers["Content-Length"]);
-	} catch (std::invalid_argument &e) {
-		throw IOException("Invalid Content-Length header received: %s", res->headers["Content-Length"]);
-	} catch (std::out_of_range &e) {
-		throw IOException("Invalid Content-Length header received: %s", res->headers["Content-Length"]);
+	if (length == 0) {
+		// Try to fully download the file first
+		range_read = false;
```
Comment (samansmink) [inline extension/httpfs/httpfs.cpp:587]: I think we might want to do the download here, that way we have the size available after the OpenFile as you would expect from the filesystem api?

**Review by samansmink — COMMENTED** [review]
@pdet @Mytherin As i'm writing down these comments, I just realized the parquet reader opens a file handle per thread. This means a full file download per thread I think.

The whole reason a cache per filehandle was okay with the range requests, is because we weren't reading the same ranges anyway. Now with the whole file this no longer works. (well it does but very slowly)

I think we do really want to only be downloading these files once, so the solution would be to move the buffer to some shared object in the `ClientData` similar to the HttpStats which will need to contain some synchronization code to allow opening multiple filehandles backed by the same cached data.

File: extension/httpfs/httpfs.cpp (hunk 4 above)
Comment (pdet) [reply extension/httpfs/httpfs.cpp:387]: I think I'm extending the `pragma enable_verification` to run every query with the full download statement (besides using the range queries).

File: extension/httpfs/httpfs.cpp (hunk 5 above)
Comment (pdet) [reply extension/httpfs/httpfs.cpp:587]: Alright-o

File: extension/httpfs/httpfs.cpp (hunk 4 above)
Comment (pdet) [reply extension/httpfs/httpfs.cpp:387]: nvm the pragma beauty doesn't work here, going for an option

**Comment by pdet** [comment]
@samansmink, great catch on the last review, I just fixed that and added a test! Let me know if you can spot sth else :-)

**Review by samansmink — COMMENTED** [review]
looks good! added two more small comments

**Comment by samansmink** [comment]
@pdet @Mytherin looks good to me! thanks for all the work here!

**Comment by pdet** [comment]
> @pdet @Mytherin looks good to me! thanks for all the work here!

thank you for the very detailed review! :-)
