### PR TITLE
[Python] Fix `__exit__` signature

### LINKED ISSUE #7816: Cursor context manager __exit__ type signature implies it swallows exceptions
### What happens?

The cursor context manager `__exit__` type signature is:

```python
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> bool: ...
```

By returning a bool, this implies the context manager can swallow exceptions (see the [`object.__exit__` docs](https://docs.python.org/3/reference/datamodel.html#object.__exit__)). 

This causes type checkers like pyright to assume assigned values within the context block may be unbound.

I've tested throwing an exception in the context block, and it doesn't appear that the context manager swallows exceptions. So could the return type be changed to `None` instead, which would be more accurate and avoid the type error below? 

### To Reproduce

```
import duckdb


def fetch(duck_conn: duckdb.DuckDBPyConnection) -> list:
    with duck_conn.cursor() as cur:
        #raise Exception("boom!")
        cur.execute("SELECT * from FOOBAR")
        results = cur.fetchall()

    return results
```

pyright/vscode:

```
10:12 - error: "results" is possibly unbound
```    

### OS:

darwin

### DuckDB Version:

0.8.0

### DuckDB Client:

python

### Full Name:

Oliver Mannion

### Affiliation:

Xero

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #7816 

As explained in the issue, returning `None` allows the type checkers to not have any uncertainty about the method swallowing exceptions or not.

### CODE REVIEW

**Review by Mause — APPROVED** [review]

File: tools/pythonpkg/src/pyconnection.cpp [hunk 1]
```diff
@@ -1585,13 +1585,14 @@ shared_ptr<DuckDBPyConnection> DuckDBPyConnection::Enter() {
...
 }
 
-bool DuckDBPyConnection::Exit(DuckDBPyConnection &self, const py::object &exc_type, const py::object &exc,
+void DuckDBPyConnection::Exit(DuckDBPyConnection &self, const py::object &exc_type, const py::object &exc,
                               const py::object &traceback) {
 	self.Close();
 	if (exc_type.ptr() != Py_None) {
-		return false;
+		// Propagate the exception if any occurred
+		PyErr_SetObject(exc_type.ptr(), exc.ptr());
```
Comment (Tishj) [inline tools/pythonpkg/src/pyconnection.cpp:1593]: @Mause do you think this is okay?
I realized now we might lose the traceback here, would it suffice to just only change the type annotation while the function itself actually returns a bool?
