### PR TITLE
Fix #7356

### LINKED ISSUE #7356: DuckDB INTERNAL Error: Assertion triggered in file "src/storage/table/row_group.cpp" on line 86: c < columns.size()
### What happens?

The DuckDB binary (`/usr/local/bin/duckdb`) throws `INTERNAL Error: Assertion triggered in file "src/storage/table/row_group.cpp" on line 86: c < columns.size()`.

### To Reproduce

```sql
CREATE INDEX id ON t1(td);
INSERT INTO t1(tr) VALUES (2);
SELECT * FROM (SELECT *, ROW_NUMBER() OVER (ORDER BY td) AS row_num FROM t1 WHERE td < 5) AS temp WHERE row_num = 1;
```

### OS:

Ubuntu 20.04 64bit

### DuckDB Version:

v0.7.2-dev2867 aa20f17

### DuckDB Client:

Binary (/usr/local/bin/duckdb)

### Full Name:

Jingzhou Fu

### Affiliation:

Wingtecher Lab of Tsinghua University

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #7356 

We were using logical indices as physical indices, because of generated columns this can cause problems.
Maybe this conversion needs to be moved up still (?)

### CODE REVIEW

File: src/function/table/table_scan.cpp [hunk 1]
```diff
@@ -233,8 +233,17 @@ static void IndexScanFunction(ClientContext &context, TableFunctionInput &data_p
 	auto &transaction = DuckTransaction::Get(context, bind_data.table.catalog);
 	auto &local_storage = LocalStorage::Get(transaction);
 
+	vector<column_t> physical_ids;
```
Comment (Mytherin) [inline src/function/table/table_scan.cpp:236]: Can we move this to `IndexScanInitGlobal` to avoid doing it for every invocation of `IndexScanFunction`? With this change we perhaps don't need to store `column_ids` at all in `IndexScanGlobalState`?

Comment (Tishj) [reply src/function/table/table_scan.cpp]: Done, I've also changed some places from column_t to storage_t, it's just semantics but I prefer making it somewhat more obvious these are working with (and expecting) physical indices

**Comment by Tishj** [comment]
I believe the regressions are unrelated, I'm going to pre-emptively merge with https://github.com/duckdb/duckdb/pull/7509 to see if that's the case

**Comment by Tishj** [comment]
@Mytherin these are unrelated, they fail on the (now removed) append100kintegers tests
should I push an empty commit to rerun the CI?

**Comment by Mytherin** [comment]
No need, thanks
