### PR TITLE
Remove LogicalTypeId::JSON and implement read_json_objects

### LINKED ISSUE #5960: json_contains only checks value from second parameter
### What happens?

My second argument to json_contains has the same value as the first parameter, but a different key. I would expect this to return false, since the entire json in the second parameter is not present in the first.

### To Reproduce

```sql
select json_contains(json('{"key":"value"}'),json('{"blah":"value"}')) as my_json_contains;
```
| my_json_contains |
|------------------|
| true             |

### OS:

Windows

### DuckDB Version:

0.6.1 and 0.6.2-dev1283

### DuckDB Client:

CLI

### Full Name:

Alex Monahan

### Affiliation:

Intel and DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by lnkuiper**
This PR removes `LogicalTypeId::JSON`, and moves the logical type to the JSON extension, just like other custom types like `INET`. This requires a bump in the storage version, as `LogicalTypeId::JSON` is in our storage version test.

This also means that for some data formats we will now return `LogicalTypeId::VARCHAR` instead, but casting to `JSON` is free, and possible only if the JSON extension is installed.

Besides that, this PR also implements `read_json_objects` and `read_ndjson_objects`. These were implemented using a macro for the CSV reader before, but are now implemented and are much faster. The `read_ndjson_objects` function now reads newline-delimited JSON data, and is able to do so in parallel. The `read_json_objects` function can read any type of JSON data, even non-newline-delimited, but does so single-threadedly. We should be able to detect whether the JSON is newline-delimited or not automatically, but I will do that in a future PR.

I've generated the `lineitem` table at SF1 as a newline-delimited JSON file, which is around 2GB. I ran this query:
```sql
create temporary table test as select * from read_ndjson_objects('lineitem.json');
```

Here are the timings:

| Implementation | Timing [s] |
| :- | :- |
| Old | 3.795 |
| `read_json_objects` (new) | 4.371 |
| `read_ndjson_objects` (new) | **0.730** |

I'm happy to receive any feedback on this. This was my first `TableFunction` implementation, so I am sure there are some things that I missed.

### CODE REVIEW

File: extension/json/include/json_common.hpp [hunk 1]
```diff
@@ -152,6 +172,10 @@ struct JSONCommon {
 	static inline DocPointer<yyjson_doc> ReadDocumentUnsafe(const string_t &input) {
 		return DocPointer<yyjson_doc>(yyjson_read(input.GetDataUnsafe(), input.GetSize(), READ_FLAG));
```
Comment (Mause) [inline extension/json/include/json_common.hpp:173]: Whilst we're doing this work, it would be great if we could expose the error from yyjson when it falls to parse? Makes debugging much easier

**Review by Mause — CHANGES_REQUESTED** [review]

File: extension/json/json_functions/json_transform.cpp [hunk 2]
```diff
@@ -58,15 +58,15 @@ static unique_ptr<FunctionData> JSONTransformBind(ClientContext &context, Scalar
 		throw InvalidInputException("JSON structure must be a constant!");
 	} else {
 		auto structure_val = ExpressionExecutor::EvaluateScalar(context, *arguments[1]);
-		if (!structure_val.DefaultTryCastAs(LogicalType::JSON)) {
+		if (!structure_val.DefaultTryCastAs(JSONCommon::JSONType())) {
```
Comment (Mytherin) [inline extension/json/json_functions/json_transform.cpp:61]: `DefaultTryCastAs` should never work with extension types, no? Should this not be turned into `TryCastAs`?

File: test/sql/json/read_ndjson.test [hunk 3]
```diff
@@ -14,10 +29,70 @@ SELECT * FROM read_json_objects('data/json/example.ndjson')
...
+SELECT * FROM read_json_objects('data/json/example_rn.ndjson')
+----
+{"id":1,"name":"O Brother, Where Art Thou?"}
+{"id":2,"name":"Home for the Holidays"}
+{"id":3,"name":"The Firm"}
+{"id":4,"name":"Broadcast News"}
+{"id":5,"name":"Raising Arizona"}
+
+query I
+SELECT * FROM read_ndjson_objects('data/json/example_rn.ndjson')
```
Comment (Mytherin) [inline test/sql/json/read_ndjson.test:70]: Could we add tests where we:

* Read json from a gzip compressed file (`example_rn.ndjson.gz`)
* Read json over a network connection using HTTPFS (you can host files [here](https://github.com/duckdb/duckdb-data/releases/tag/v1.0) for that purpose)
* Read json from stdin in the shell (see `tools/shell/shell-test.py:894` where we read CSVs from `/dev/stdin`)

Malformed tests, including checking that the expected error is thrown (using the new `statement error` syntax):

* Read an empty file
* Unterminated quotes
* Duplicate JSON key
* Multiple JSON objects on one line
* What if we try to read a CSV file using the JSON functions?
* What if we try to read a Parquet file using the JSON functions?

Finally, perhaps out of scope for this PR, but for testing it is extremely useful to also have a writer because you can do round-trip verification and generate large datasets without having to check them in. This is used quite extensively in the CSV and Parquet readers/writers. For example, you could write the TPC-H database as JSON files, then read them back in and verify that the query results are still correct.

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Great results. Some comments from my side:

File: test/sql/json/read_ndjson.test (hunk 3 above)
Comment (lnkuiper) [reply test/sql/json/read_ndjson.test:70]: I've implemented pretty much all of this, and it required parsing the JSON before ingesting it (which is technically not required for NDJSON), so this is a slight performance hit.

Much less than I expected, though, it now takes ~1.21s instead of ~0.73 seconds :) And we can now throw descriptive errors.

Comment (lnkuiper) [reply test/sql/json/read_ndjson.test:70]: Also, we should be able to create a `COPY ... (FORMAT JSON)` really easily - all the components are already there:
```sql
copy (select to_json(lineitem) from lineitem) to '__TEST_DIR__/lineitem.json' (format csv, quote '')
```

Maybe we can do some kind of rewrite when `(FORMAT JSON)` is specified?

**Comment by wonb168** [comment]
but this can only read json file?
how to read a json str, I use python requests get the json str.

and read_json_objects the result is wrong:
```
df=con.execute("select * from read_json_objects('d:/download/json.json')").df()
print(df)
json
0  [{"col 1":"a","col 2":"b"},{"col 1":"c","col 2...
```
pandas read_json got:
```
col 1 col 2
0     a     b
1     c     d
```
thanks!

**Comment by lnkuiper** [comment]
@wonb168 This PR implements `read_json_objects`, which we already had before but was implemented as a macro that used the CSV reader.

These improvements speed up the ingestion of JSON and should prepare us for a future PR where we automatically detect the JSON schema and convert it to tabular data. Until then, we don't have this, and you can use `json_transform` to supply the schema yourself.

**Comment by lnkuiper** [comment]
Had to remove the `YYJSON_READ_INSITU` flag sadly, although the performance diff is not a big deal. Following the discussion at [ibireme/yyjson#100](https://github.com/ibireme/yyjson/issues/100) I did a big refactor to the JSON extension, and we now use a custom allocator everywhere.

The benchmark I used earlier is now actually < 1s on my laptop! Big thanks to the author of yyjson.

**Comment by lnkuiper** [comment]
The allocation improvements seem to bring a 20-30% performance benefit to other functions such as `json_extract` as well.

File: extension/json/include/buffered_json_reader.hpp [hunk 4]
```diff
@@ -0,0 +1,123 @@
...
+#include "duckdb/common/enums/file_compression_type.hpp"
+#include "duckdb/common/mutex.hpp"
+#include "json_common.hpp"
+
+namespace duckdb {
+
+struct FileHandle;
+
+enum class JSONFormat : uint8_t {
+	//! Auto-detect during the bind (TODO)
```
Comment (Mytherin) [inline extension/json/include/buffered_json_reader.hpp:21]: This is done right?

File: extension/json/include/json_scan.hpp [hunk 5]
```diff
@@ -0,0 +1,194 @@
...
+
+#include "buffered_json_reader.hpp"
+#include "duckdb/common/mutex.hpp"
+#include "duckdb/function/table_function.hpp"
+
+namespace duckdb {
+
+struct JSONScanLocalState;
+
+struct JSONScanData : public TableFunctionData {
```
Comment (Mytherin) [inline extension/json/include/json_scan.hpp:19]: Does this all need to be in the header, or could it be moved to the `.cpp` file?

File: extension/json/json-extension.cpp [hunk 6]
```diff
@@ -18,31 +21,45 @@ static DefaultMacro json_macros[] = {
...
     {nullptr, nullptr, {nullptr}, nullptr}};
 
-static DefaultMacro table_macros[] = {
-    {DEFAULT_SCHEMA,
-     "read_json_objects",
-     {"json_file", nullptr},
-     "SELECT * FROM read_csv(json_file, columns={'json': 'JSON'}, delim=NULL, header=0, quote=NULL, escape=NULL)"},
-    {DEFAULT_SCHEMA, "read_ndjson_objects", {"json_file", nullptr}, "SELECT * FROM read_json_objects(json_file)"},
-    {nullptr, nullptr, {nullptr}, nullptr}};
+static DefaultMacro table_macros[] = {{nullptr, nullptr, {nullptr}, nullptr}};
```
Comment (Mytherin) [inline extension/json/json-extension.cpp:24]: Perhaps this could be removed entirely?

File: src/storage/storage_info.cpp [hunk 7]
```diff
@@ -2,7 +2,7 @@
 
 namespace duckdb {
 
-const uint64_t VERSION_NUMBER = 41;
+const uint64_t VERSION_NUMBER = 42;
```
Comment (Mytherin) [inline src/storage/storage_info.cpp:5]: Is the storage version increase necessary?

File: test/sql/json/read_json_objects.test [hunk 8]
```diff
@@ -0,0 +1,224 @@
...
+
+query I
+select * from read_ndjson_objects('data/json/empty.ndjson')
+---
+
+# invalid json stuff
+statement error
+select * from read_json_objects('data/json/unterminated_quotes.ndjson')
+----
+Invalid Input Error: Malformed JSON at byte 25 of input
```
Comment (Mytherin) [inline test/sql/json/read_json_objects.test:170]: Future work: print the line number, and perhaps also the context around the reported byte

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Looks great - very impressive improvements! Some minor comments below:

File: extension/json/include/json_scan.hpp (hunk 5 above)
Comment (lnkuiper) [reply extension/json/include/json_scan.hpp:19]: The idea for this is that we have a shared `json_scan.hpp` file for all the future JSON table functions. In this case, I've re-implemented `read_(nd)json_objects`, which uses these common functionality from `json_scan.hpp`. In the future, we'll add more JSON table functions, which need a lot of the same functionality too. So I figured it was best to add it to the `.hpp` file.

File: test/sql/json/read_json_objects.test (hunk 8 above)
Comment (lnkuiper) [reply test/sql/json/read_json_objects.test:170]: I hope I can get something working similar to what Pedro did for the CSV reader

File: extension/json/json_scan.cpp [hunk 9]
```diff
@@ -0,0 +1,497 @@
...
+	}
+
+	// Skip over any remaining whitespace for the next scan
+	SkipWhitespace(buffer_ptr, buffer_offset, buffer_size);
+
+	return count;
+}
+
+static inline const char *NextNewline(const char *ptr, idx_t size) {
+	return (const char *)memchr(ptr, '\n', size);
```
Comment (Mytherin) [inline extension/json/json_scan.cpp:173]: We might also want to add tests with Windows delimited files (`\r\n`) in the future

File: extension/json/json_scan.cpp [hunk 10]
```diff
@@ -0,0 +1,497 @@
...
+		objects[count] = ParseLine((char *)line_start, line_size, lines[count], ignore_errors);
+
+		buffer_offset += line_size;
+		SkipWhitespace(buffer_ptr, buffer_offset, buffer_size);
+	}
+}
+
+idx_t JSONScanLocalState::GetBatchIndex() const {
+	// Is this enough? Needs to be lower than PipelineBuildState::BATCH_INCREMENT = 10000000000000
+	return current_reader->file_index * 1000000 + current_buffer_handle->buffer_index;
```
Comment (Mytherin) [inline extension/json/json_scan.cpp:494]: Do we need to do the `1000000 * file_index` trick? Can't we know how many batch indexes are in each file while we are reading?

For example, if we have a 100MB file, and read 1MB buffers, we know there are 100 batch indexes in that file.

File: extension/json/json_scan.cpp [hunk 11]
```diff
@@ -0,0 +1,497 @@
...
+		const auto &c = *ptr;
+		if (c == '\n') {
+			break;
+		}
+	}
+	return ptr;
+}
+
+static inline void TrimWhitespace(JSONLine &line) {
+	while (line.size != 0 && std::isspace(line[0])) {
```
Comment (Mytherin) [inline extension/json/json_scan.cpp:187]: Can we use `StringUtil::CharacterIsSpace` here? `std::isspace`is [locale sensitive](https://en.cppreference.com/w/cpp/string/byte/isspace) which is evil.

**Review by Mytherin — COMMENTED** [review]
Some more minor comments:

File: extension/json/json_scan.cpp (hunk 9 above)
Comment (lnkuiper) [reply extension/json/json_scan.cpp:173]: I have already added a test for this in `read_json_objects.test`, where we read the `example_rn.ndjson` file.

File: extension/json/json_scan.cpp (hunk 10 above)
Comment (lnkuiper) [reply extension/json/json_scan.cpp:494]: What about compression? If the original 100MB file is 10MB compressed, we will still read 100 batch indexes, but then we have to _estimate_ the compression ratio to estimate how many indexes there are in the file.

File: extension/json/json_scan.cpp [hunk 12]
```diff
@@ -0,0 +1,497 @@
...
+	}
+}
+
+unique_ptr<GlobalTableFunctionState> JSONScanGlobalState::Init(ClientContext &context, TableFunctionInitInput &input) {
+	auto &bind_data = (JSONScanData &)*input.bind_data;
+	return make_unique<JSONScanGlobalState>(context, bind_data);
+}
+
+idx_t JSONScanGlobalState::MaxThreads() const {
+	return system_threads;
```
[the remark this answers is not in the document]
Comment (lnkuiper) [reply extension/json/json_scan.cpp:109]: I copied this from the CSV reader. Do we need to open the file to get the file size? I didn't see any other way.

The parquet reader opens only the first file and then estimates the total number of row groups for all files by multiplying the number of row groups in the first file by the number of files. Would this be OK here? This would be slightly problematic if we read a small file (which would be read using 1 thread) first and then a large file (which would require all threads), as we would underestimate the thread count by a lot.

File: src/storage/storage_info.cpp (hunk 7 above)
Comment (Mytherin) [reply src/storage/storage_info.cpp:5]: We can regenerate the database without bumping the storage version, no?

File: extension/json/include/json_scan.hpp (hunk 5 above)
Comment (Mytherin) [reply extension/json/include/json_scan.hpp:19]: Fair enough

File: extension/json/json_scan.cpp (hunk 12 above)
[the remark this answers is not in the document]
Comment (Mytherin) [reply extension/json/json_scan.cpp:109]: That is true - perhaps it is indeed better to always launch `n` tasks as it is unlikely to hurt much.

File: extension/json/json_scan.cpp (hunk 9 above)
Comment (Mytherin) [reply extension/json/json_scan.cpp:173]: Great - missed that one. Thanks!

File: extension/json/json_scan.cpp (hunk 10 above)
Comment (Mytherin) [reply extension/json/json_scan.cpp:494]: That's fair - in the CSV reader we dynamically assign batch indexes instead to avoid having to do this. Perhaps the same is possible for the JSON reader.

File: src/storage/storage_info.cpp (hunk 7 above)
Comment (lnkuiper) [reply src/storage/storage_info.cpp:5]: Sure, but users that have JSON in their db will crash upon opening it when they update.

Comment (Mytherin) [reply src/storage/storage_info.cpp:5]: Hm, that also means that it is no longer possible to store JSON - at least until we fix #4578, right?

File: extension/json/json_scan.cpp (hunk 10 above)
Comment (lnkuiper) [reply extension/json/json_scan.cpp]: I thought this was tricky, but I've implemented dynamic batch indices properly now

File: src/storage/storage_info.cpp (hunk 7 above)
Comment (lnkuiper) [reply src/storage/storage_info.cpp:5]: I've added a test for this and it seems to work properly

**Comment by lnkuiper** [comment]
Thanks for the feedback! I think I've implemented all of it. I was able to reproduce the 32-bit issue in a Docker container, and I've managed to fix it there, so I hope CI is happy now too. Fingers crossed 🤞

**Comment by lnkuiper** [comment]
I've also fixed #5960 in this PR

**Comment by lnkuiper** [comment]
@Mytherin I think this is good to go!

**Comment by Mytherin** [comment]
Thanks! Great work!
