### PR TITLE
[Python] Fix fatal exception caused by empty Pandas Categorical objects.

### LINKED ISSUE #12364: DuckDB throws InternalError when creating a table from an empty DataFrame with a categoric column
### What happens?

I received an inscrutable internal error from DuckDb under certain conditions in my app;
```
con.execute("CREATE TABLE test AS SELECT * FROM empty_categoric_df")
duckdb.duckdb.InternalException: INTERNAL Error: Information loss on integer cast: value -1 outside of target range [0, 255]
```

Upon digging, and paring back details of my use case I found that the cause was when creating a table from an empty pandas DataFrame which included a categoric column.

I understand this may be a bit of an invalid edge case, but a more intelligible error message would have made it easier to debug.

### To Reproduce

Reproduction script:

```
import pandas as pd
import duckdb

con = duckdb.connect()

data = {'category': pd.Categorical(['A', 'B', 'C'])}
populated_categoric_df = pd.DataFrame(data)

con.execute("CREATE TABLE test AS SELECT * FROM populated_categoric_df")

empty_categoric_df = pd.DataFrame({'category': pd.Series(dtype='category')})

print(empty_categoric_df)
print(empty_categoric_df.dtypes)
print(empty_categoric_df['category'].cat.categories)
print(empty_categoric_df['category'].cat.codes)

con.execute("CREATE TABLE test AS SELECT * FROM empty_categoric_df")
```

The former case works, of course, the latter throws the error.

Output from the above reproduction script:
```
Empty DataFrame
Columns: [category]
Index: []
category    category
dtype: object
Index([], dtype='object')
Series([], dtype: int8)
Traceback (most recent call last):
  File <redacted>, line 18, in <module>
    con.execute("CREATE TABLE test AS SELECT * FROM empty_categoric_df")
duckdb.duckdb.InternalException: INTERNAL Error: Information loss on integer cast: value -1 outside of target range [0, 255]
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
For more information, see https://duckdb.org/docs/dev/internal_errors
```

### OS:

linux/amd64

### DuckDB Version:

1.0.0

### DuckDB Client:

Python

### Full Name:

Simon Grant

### Affiliation:

n/a

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #12364 

This was caused by us accepting input that would create an ENUM of size 0, which was not expected by the rest of the system. We held an implicit assertion that the size would be over 0.

I've added the assertion and we throw a proper exception when this is attempted.

### CODE REVIEW

File: tools/pythonpkg/src/pandas/bind.cpp [hunk 1]
```diff
@@ -68,6 +68,9 @@ static LogicalType BindColumn(PandasBindColumn &column_p, PandasColumnBindData &
 			bind_data.numpy_type.type = NumpyNullableType::CATEGORY;
 			vector<string> enum_entries = py::cast<vector<string>>(categories);
 			idx_t size = enum_entries.size();
+			if (enum_entries.empty()) {
+				throw InvalidInputException("Could not create an ENUM from an empty Categorical");
```
Comment (Mytherin) [inline tools/pythonpkg/src/pandas/bind.cpp:72]: Perhaps we can fallback to `LogicalType::VARCHAR` here instead so we can query the dataframe?

Comment (Tishj) [reply tools/pythonpkg/src/pandas/bind.cpp:72]: Maybe, but I don't really see when anyone would use this, creating a column out of an empty Categorical means it can't hold any values, the set of available options is empty

Comment (Tishj) [reply tools/pythonpkg/src/pandas/bind.cpp:72]:
```py
data = ['cat', 'dog', 'cat', 'bird', 'dog', 'cat']
categorical_column = pd.Categorical(data, categories=[])
df = pd.DataFrame({'category': categorical_column})
print(df)
```
```
  category
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
5      NaN
```

Comment (Mytherin) [reply tools/pythonpkg/src/pandas/bind.cpp:72]: I don't think anyone uses this intentionally - but at least one user seems to have encountered this error. Users might not explicitly make a pandas DataFrame without categories, but with no data the categories list might end up empty, causing a strange error on the DuckDB side when reading. If possible since Pandas accepts this, I think we should accept it as well.

Comment (Mytherin) [reply tools/pythonpkg/src/pandas/bind.cpp:72]: e.g. something like this seems plausible:

```py
import pandas as pd
import numpy as np

def create_categorical(data):
	categorical_column = pd.Categorical(data, categories=np.unique(data))
	df = pd.DataFrame({'category': categorical_column})
	return df

print(create_categorical([]))
-- Empty DataFrame
-- Columns: [category]
-- Index: []
```

**Comment by Tishj** [comment]
@Mytherin this failure seems interesting <https://github.com/duckdb/duckdb/actions/runs/9363993037/job/25775994277?pr=12370>

I added an assertion earlier on so we can catch it before it causes us to create a `(idx_t)-1` value inside `Value::MaximumValue(type)`

**Comment by Mytherin** [comment]
I wonder if we should just allow zero-length enums? I can't really think of anything that would break - they just need to be `NULL` for every value since there is no valid value, but that is not really different from the other constraints on enums (i.e. enum values always need to be `< dict_size` anyway).

**Comment by Mytherin** [comment]
Thanks!
