### PR TITLE
Track exact ART size and many ART improvements

### LINKED ISSUE #4967: Index sizes do not appear to be accounted for in pragma database_size
### What happens?

According to [this comment](https://github.com/duckdb/duckdb/issues/1546#issuecomment-1263525113) indexes should be managed by the buffer manager and thus contribute to the memory size listed when running `pragma database_size`. However, in some experiments with the CLI this doesn't appear to be the case.

I'm not sure if this is an actual bug or if I'm interpreting things incorrectly.

### To Reproduce

Below are some screenshots illustrating what I'm seeing. I was running duckdb built from commit 91a9fc49a5. So while not the absolute latest & greatest, it's pretty close.

The data being used is 100k rows of an integer and 10 varchars. It's contrived data, here's the first few rows
```csv
id,A0,A1,A2,A3,A4,A5,A6,A7,A8,A9,
0,"ccccccccccccccc00","ccccccccccccccc01","ccccccccccccccc02","ccccccccccccccc03","ccccccccccccccc04","ccccccccccccccc05","ccccccccccccccc06","ccccccccccccccc07","ccccccccccccccc08","ccccccccccccccc09",
1,"ccccccccccccccc10","ccccccccccccccc11","ccccccccccccccc12","ccccccccccccccc13","ccccccccccccccc14","ccccccccccccccc15","ccccccccccccccc16","ccccccccccccccc17","ccccccccccccccc18","ccccccccccccccc19",
2,"ccccccccccccccc20","ccccccccccccccc21","ccccccccccccccc22","ccccccccccccccc23","ccccccccccccccc24","ccccccccccccccc25","ccccccccccccccc26","ccccccccccccccc27","ccccccccccccccc28","ccccccccccccccc29",
```

In the first set of screenshots I've created a table with a primary key on the ID which will also create an index on that column. They show a discrepancy between what DuckDB is reporting versus what the OS is reporting.

image
image

(The 0.4.0 and 0.5.1 instances of duckdb are running with the same table created from the same data set.)

The next set of screenshots show the same table loaded with the same data, except now the `id` column is not a primary key.

image
image

While I don't have a screenshot for it, if I manually create an index, `create index id_idx on t(id);` the OS-reported memory usage goes back up to about 41.0MB.

### OS:

MacOS

### DuckDB Version:

0.5.1

### DuckDB Client:

CLI

### Full Name:

Michael Albers

### Affiliation:

Mode

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by taniabogatsch**
This PR adds logic to track the exact in-memory size of any existing ART index and many minor improvements. 

We update the current memory in the buffer manager after each operation on a chunk or after constructing an index via `CREATE INDEX ...`. Not all indexes propagate their in-memory size, i.e., transient indexes during ART creation or in the local state of a transaction do not propagate their in-memory size. To achieve this, the index contains a `track_memory` flag that identifies whether changes to the index's size should be propagated to the buffer manager. This closes #4967.

I also added a few micro-benchmarks to help spot significant index performance regressions in the future.

Other minor changes include the following (I know this PR got a bit too big - sooorry 😅):
- various comments and updated exception messages
- more assertions, especially in merge code
- removed some `static_cast` because I think we typically use regular casts in our code
- refactored `ART::VerifyExistence` by adding more precise exception messages and code paths
- recursively checking for side effects during `CREATE INDEX` plan creation
- refactored (de)serialization of leaf to match the cases for other node types
- node more magic numbers in the `cpp`-files of the different nodes
- handling of constraint checking when merging the thread-local ARTs into the global ART

### CODE REVIEW

File: src/execution/index/art/art.cpp [hunk 1]
```diff
@@ -404,58 +412,68 @@ bool ART::Insert(Node *&node, Key &key, idx_t depth, row_t row_id) {
...
-		Node4::InsertChild(new_node, key_byte, node);
+		this->memory_size += new_node->MemorySize(*this, false);
+
+		auto key_byte = node->prefix.Reduce(*this, new_prefix_length);
+		Node4::InsertChild(*this, new_node, key_byte, node);
+
 		Node *leaf_node = Leaf::New(key, depth + new_prefix_length + 1, row_id);
-		Node4::InsertChild(new_node, key[depth + new_prefix_length], leaf_node);
+		Node4::InsertChild(*this, new_node, key[depth + new_prefix_length], leaf_node);
+		this->memory_size += leaf_node->MemorySize(*this, false);
```
Comment (Tishj) [inline src/execution/index/art/art.cpp:446]: I'm noticing a pattern of `InsertChild` + `this->memory_size += ...` is there any way we can combine these maybe?

File: src/execution/index/art/art.cpp [hunk 2]
```diff
@@ -811,52 +845,61 @@ void ART::VerifyExistence(DataChunk &chunk, VerifyExistenceType verify_type, str
 		if (keys[i].Empty()) {
 			continue;
 		}
+
 		Node *node_ptr = Lookup(tree, keys[i], 0);
-		bool throw_exception =
-		    verify_type == VerifyExistenceType::APPEND_FK ? node_ptr == nullptr : node_ptr != nullptr;
-		if (!throw_exception) {
+
+		// APPEND_FK, i.e., the key must exist in the PK/UNIQUE table
```
Comment (Tishj) [inline src/execution/index/art/art.cpp:851]: Is there any chance you could move the adjustments made here to another PR?
I have had to alter this code quite a bit as part of UPSERT so we're bound to get a bunch of merge conflicts there

File: src/execution/index/art/node.cpp [hunk 3]
```diff
@@ -408,36 +465,48 @@ bool ResolvePrefixesAndMerge(MergeInfo &info, idx_t depth, ParentsOfNodes &paren
...
 	// insert l_node, break up prefix of l_node
-	auto key_byte = l_node->prefix.Reduce(mismatch_pos);
-	Node4::InsertChild(new_node, key_byte, l_node);
+	auto key_byte = l_node->prefix.Reduce(*info.root_l_art, mismatch_pos);
+	Node4::InsertChild(*info.root_l_art, new_node, key_byte, l_node);
 
 	// insert r_node, break up prefix of r_node
-	key_byte = r_node->prefix.Reduce(mismatch_pos);
-	Node4::InsertChild(new_node, key_byte, r_node);
+	key_byte = r_node->prefix.Reduce(*info.root_r_art, mismatch_pos);
```
Comment (Tishj) [inline src/execution/index/art/node.cpp:503]: This pattern also continues quite a few times, maybe move to a function?

File: src/execution/index/art/node256.cpp [hunk 4]
```diff
@@ -48,7 +57,8 @@ idx_t Node256::GetNextPos(idx_t pos) {
 }
 
 idx_t Node256::GetNextPosAndByte(idx_t pos, uint8_t &byte) {
-	for (pos == DConstants::INVALID_INDEX ? pos = 0 : pos++; pos < 256; pos++) {
+	pos == DConstants::INVALID_INDEX ? pos = 0 : pos++;
```
Comment (Tishj) [inline src/execution/index/art/node256.cpp:60]: nit:
I read this wrong before thinking you were assigning to `pos`, so the `pos++` looked weird to me
But then I saw that you don't assign to pos, they are just separate expressions

Can we use this instead as it's easier to understand for my smooth brain?
```suggestion
pos = (DConstants::INVALID_INDEX) ? 0 : pos + 1;
```

File: src/include/duckdb/execution/index/art/node48.hpp [hunk 5]
```diff
@@ -35,11 +40,13 @@ class Node48 : public Node {
...
+	bool ChildIsInMemory(idx_t pos) override;
 
 	//! Insert a new child node at key_byte into the Node48
-	static void InsertChild(Node *&node, uint8_t key_byte, Node *new_child);
+	static void InsertChild(ART &art, Node *&node, uint8_t key_byte, Node *new_child);
 	//! Erase the child at pos and (if necessary) shrink to Node16
-	static void EraseChild(Node *&node, int pos, ART &art);
+	static void EraseChild(ART &art, Node *&node, idx_t pos);
 	//! Returns the size (maximum capacity) of the Node48
 	static idx_t GetSize();
```
Comment (Tishj) [inline src/include/duckdb/execution/index/art/node48.hpp:51]: These can be static constexpr I believe?

File: src/execution/index/art/node256.cpp [hunk 6]
```diff
@@ -65,28 +75,48 @@ void Node256::ReplaceChildPointer(idx_t pos, Node *node) {
...
+		art.memory_size -= child->MemorySize(art, true);
+	}
+
+	// erase the child and decrease the count
 	n->children[pos].Reset();
 	n->count--;
-	if (node->count <= 36) {
+
+	// shrink node to Node48
+	if (node->count <= Node48::GetSize() - 11) {
```
Comment (Tishj) [inline src/execution/index/art/node256.cpp:104]:
```suggestion
if (node->count <= Node48::GetSize() - 12) {
```
(48 - 11 = 37)

File: src/include/duckdb/execution/index/art/art.hpp [hunk 7]
```diff
@@ -52,14 +52,14 @@ class ART : public Index {
...
+	    AttachedDatabase &db, bool track_memory, idx_t block_id = DConstants::INVALID_INDEX,
 	    idx_t block_offset = DConstants::INVALID_INDEX);
 	~ART() override;
 
 	//! Root of the tree
 	Node *tree;
-	//! Attached database
-	AttachedDatabase &db;
+	//	//! Attached database
+	//	AttachedDatabase &db;
```
Comment (Tishj) [inline src/include/duckdb/execution/index/art/art.hpp:62]: Is this supposed to be commented out?

**Review by Tishj — COMMENTED** [review]
Some places we can maybe further reduce duplication but otherwise LGTM! 👍 
I feel a little out of my depth reviewing this, and as a result I might have been grasping at straws to find stuff I could have an opinion on :joy: take the importance of these comments with a grain of salt

File: src/execution/index/art/node4.cpp [hunk 8]
```diff
@@ -86,45 +97,69 @@ void Node4::InsertChild(Node *&node, uint8_t key_byte, Node *new_child) {
...
+	// this is a one way node, compress
 	if (n->count == 1) {
+
+		// get only child and concatenate prefixes
 		auto child_ref = n->GetChild(art, 0);
 		// concatenate prefixes
-		child_ref->prefix.Concatenate(n->key[0], node->prefix);
+		child_ref->prefix.Concatenate(art, n->key[0], node->prefix);
+		// free this node
 		n->children[0] = nullptr;
```
Comment (Tishj) [inline src/execution/index/art/node4.cpp:159]: Don't we get a reference to this child, that we use in `node = child_ref` later
Does this not cause a heap-use-after-free?

File: src/execution/index/art/art.cpp [hunk 9]
```diff
@@ -358,8 +360,14 @@ bool ART::Insert(IndexLock &lock, DataChunk &input, Vector &row_ids) {
 			row_t row_id = row_identifiers[i];
 			Erase(tree, keys[i], 0, row_id);
```
[the remark this answers is not in the document]
Comment (taniabogatsch) [reply src/execution/index/art/art.cpp:361]: We can keep this in mind, but I would not include it in this PR. Also, if we move to use the merge code for constraint checking before insertions, we no longer need to clean up anyways. I will move this to the ART improvements issue.

File: src/execution/index/art/art.cpp (hunk 2 above)
Comment (taniabogatsch) [reply src/execution/index/art/art.cpp:851]: I'd like to keep them in for now, but you can just overwrite them when merging, no?

Comment (Tishj) [reply src/execution/index/art/art.cpp:852]: Yea fair enough, on second inspection they look pretty minor, I think I just read VerifyExistence and got PTSD, because like 2/3rds of the time spent on UPSERT was spent untangling this code

**Comment by Mytherin** [comment]
Thanks - the PR LGTM. Perhaps it would be a good idea to implement a `Verify` method on the ART that verifies that the memory usage of all the nodes added together is equivalent to what is stored in the `ART::memory_usage` variable? This could be done by e.g. adding a recursive `GetUsedMemory` function to the ART nodes that is called in this verify method. 

In my experience it is easy for these types of variables that get incrementally updated to get out-of-sync because of bugs which might lead to hard-to-debug issues.

File: src/execution/operator/schema/physical_create_index.cpp [hunk 10]
```diff
@@ -111,11 +109,14 @@ SinkFinalizeType PhysicalCreateIndex::Finalize(Pipeline &pipeline, Event &event,
 	// here, we just set the resulting global index as the newly created index of the table
 
 	auto &state = (CreateIndexGlobalSinkState &)gstate_p;
-
 	if (!table.storage->IsRoot()) {
 		throw TransactionException("Transaction conflict: cannot add an index to a table that has been altered!");
 	}
 
+	if (state.global_index->track_memory) {
+		state.global_index->buffer_manager.IncreaseUsedMemory(state.global_index->memory_size);
```
Comment (Mytherin) [inline src/execution/operator/schema/physical_create_index.cpp:117]: The `IncreaseUsedMemory` seems to only be called in the `PhysicalCreateIndex` - this is not the code path that is taken for primary key indexes, and memory will also not be tracked/increased for newly inserted data. Perhaps this should be moved to the `Index::Insert` and `Index::Remove` calls instead, or also added to other locations where the index memory usage increases?

Comment (taniabogatsch) [reply src/execution/operator/schema/physical_create_index.cpp:117]: To increase the ART size in the buffer manager, I added code to `ART::Insert` (`art.cpp`) and the `physical_create_index.cpp` . Basically directly after every time we change the ART, so for each chunk of inserted keys or each new ART. This should also work for primary keys and newly inserted data, no? I added code to decrease the memory usage to the destructor `ART::~ART()` and `ART::Delete` (`art.cpp`). If I remember correctly, these are all the places where I propagated changes to the buffermanager.

But yes, maybe these places are not intuitive enough? Or there is a better solution? I intended to change the memory usage chunk-wise directly after a permanent change to the ART.

Comment (Mytherin) [reply src/execution/operator/schema/physical_create_index.cpp:117]: Ah yes, you are correct - I missed the usage in `ART::Insert`

**Review by Mytherin — COMMENTED** [review]
Some more minor comments - could you merge with master and resolve the conflicts with the upsert PR?

**Comment by Mytherin** [comment]
Thanks!
