### PR TITLE
[C-API] Data chunk invalid left-shift

### LINKED ISSUE #4499: PRAGMA table_info returns invalid dflt_value using data chunks API
### What happens?

Executing `PRAGMA table_info(foo)` returns an invalid value for the `dflt_value` col using the data chunks API. I can't reproduce this with the CLI.

The issue is based on an issue I received for the DuckDB Go driver [here](https://github.com/marcboeker/go-duckdb/issues/39).

Do you have any idea why this happens?

### To Reproduce

Schema:

`CREATE TABLE foo (id integer)`

Running `PRAGMA table_info(foo)` should return 1 row with 6 cols. All columns are reported correctly but except for the `dflt_value` column. 

I'm going this way (simplified) to fetch the data in the go-duckdb client driver:

1. `chunk = duckdb_result_get_chunk(res, 0)` with res as the result of `PRAGMA table_info(foo)` and 0 for the first chunk.
2. `vector = duckdb_data_chunk_get_vector(chunk, 4)` with 4 as the column index for the `dflt_value` column.
3. `validity = duckdb_vector_get_validity(vector)`
4. Check `duckdb_validity_row_is_valid(validity, 0)` for the first row that always fails with a non null return value.

This is the output for `PRAGMA table_info(foo)`:

```
Row: 0, Col: 0, Name: cid, Value: 0
Row: 0, Col: 1, Name: name, Value: id
Row: 0, Col: 2, Name: type, Value: INTEGER
Row: 0, Col: 3, Name: notnull, Value: false
0x1257bf980 <--- Result from duckdb_vector_get_validity(vector)
Error: row is invalid
```

But querying for `PRAGMA database_size` works totally fine:

```
Row: 0, Col: 0, Name: database_size, Value: 0 bytes
Row: 0, Col: 1, Name: block_size, Value: 262144
Row: 0, Col: 2, Name: total_blocks, Value: 0
Row: 0, Col: 3, Name: used_blocks, Value: 0
Row: 0, Col: 4, Name: free_blocks, Value: 0
Row: 0, Col: 5, Name: wal_size, Value: 563 bytes
Row: 0, Col: 6, Name: memory_usage, Value: 0 bytes
Row: 0, Col: 7, Name: memory_limit, Value: 27.4GB
```

So I went to `src/function/table/system/pragma_table_info.cpp` and changed `output.SetValue(4, index, def_value);` to `output.SetValue(4, index, Value(column.Name()));` just to return some other value and whoops the verification for validity doesn't complain anymore, except I'm now returning the column's name instead of its default value.

```
Row: 0, Col: 0, Name: cid, Value: 0
Row: 0, Col: 1, Name: name, Value: id
Row: 0, Col: 2, Name: type, Value: INTEGER
Row: 0, Col: 3, Name: notnull, Value: false
Row: 0, Col: 4, Name: dflt_value, Value: id <--- Now the column's name "id" is returned
Row: 0, Col: 5, Name: pk, Value: false
```

### OS:

macOS

### DuckDB Version:

0.4.0

### DuckDB Client:

go-duckdb

### Full Name:

Marc Boeker

### Affiliation:

Private

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #4499 

It's a simple oversight, the type of `1` defaults to `int32_t`, causing a shift with any value larger than/equal to 32 produces an incorrect result.

### CODE REVIEW

**Comment by hannes** [comment]
As suggested in the issue, can you please double check whether there are other problematic instances of this shift in the codebase?

**Comment by Tishj** [comment]
> As suggested in the issue, can you please double check whether there are other problematic instances of this shift in the codebase?

Yes will do :thumbsup:

**Comment by hannes** [comment]
Thanks can you also double check what happened to your ICU? There's a giant diff there.

**Comment by Tishj** [comment]
Yea it's caused by format-master, I'll redo the changes with formatting I guess

I somehow broke Julia, it cant find `duckdb_pending_prepared` anymore

**Comment by hannes** [comment]
Thanks, but I would probably say let's not do this fix in the third_party stuff. @Mytherin do you agree?

**Comment by Mytherin** [comment]
Agreed let’s skip the ICU fixes, it’s likely the code is never even run

File: extension/icu/third_party/icu/common/ustrtrns.cpp [hunk 1]
```diff
@@ -608,7 +608,7 @@ u_strFromUTF8Lenient(UChar *dest,
                 if((t1 = pSrc[1]) != 0 && (t2 = pSrc[2]) != 0 && (t3 = pSrc[3]) != 0) {
                     pSrc += 4;
                     /* 0x3c82080 = (0xf0 << 18) + (0x80 << 12) + (0x80 << 6) + 0x80 */
-                    ch = (ch << 18) + (t1 << 12) + (t2 << 6) + t3 - 0x3c82080;
+                    ch = (ch << 18) + ((UChar32)t1 << 12) + (t2 << 6) + t3 - 0x3c82080;
```
Comment (Tishj) [inline extension/icu/third_party/icu/common/ustrtrns.cpp:611]: `uint8_t t1, t2, t3; /* trail bytes */`

`t1 << 12` is causing undefined behavior because there aren't 12 bits in the value, so it has to be cast

File: third_party/fmt/include/fmt/format-inl.h [hunk 2]
```diff
@@ -405,7 +405,7 @@ class fp {
     assign(d);
     constexpr int min_normal_e = std::numeric_limits<float>::min_exponent -
                                  std::numeric_limits<double>::digits;
-    significand_type half_ulp = 1 << (std::numeric_limits<double>::digits -
+    significand_type half_ulp = (uint64_t)1 << (std::numeric_limits<double>::digits -
```
Comment (Tishj) [inline third_party/fmt/include/fmt/format-inl.h:408]: `std::numeric_limits<double>::digits == 53` which causes undefined behavior if applied to a `int32_t`
So this has to be cast

Comment (Tishj) [reply third_party/fmt/include/fmt/format-inl.h:408]: Ah, it's (53 - 24 - 1) which is equal to 28, so this cast is not needed 😅

File: extension/icu/third_party/icu/common/ustrtrns.cpp (hunk 1 above)
Comment (Tishj) [reply extension/icu/third_party/icu/common/ustrtrns.cpp:611]: Apparantly this doesn't matter
`No arithmetic operation takes uint8_t so both of your operands will always be promoted.`

So this explicit cast is not necessary, it happens implicitly
