### PR TITLE
ISSUE-22061: Fix JSON shell output: emit BOOLEAN as true/false, not strings

### LINKED ISSUE #22061: Boolean in JSON output is casted as string
### What happens?

Boolean value in `json` output mode is casted as string, leading `"false"` value to treated as `true` in followup `jq` operations.

That issue had a dramatic effect in data pipeline.

```
$ duckdb-1.4.4 --json -s 'SELECT 1 AS id, true AS flag UNION SELECT 2 AS id, false AS flag' | jq 'map(select(.flag))'
[
  {
    "id": 1,
    "flag": true
  }
]

$ duckdb-1.5.2 --json -s 'SELECT 1 AS id, true AS flag UNION SELECT 2 AS id, false AS flag' | jq 'map(select(.flag))'
[
  {
    "id": 2,
    "flag": "false"
  },
  {
    "id": 1,
    "flag": "true"
  }
]
```

### To Reproduce

```
duckdb --json -s 'SELECT true AS pos, false AS neg'
```

```
duckdb --json -s 'SELECT 1 AS id, true AS flag UNION SELECT 2 AS id, false AS flag' | jq 'map(select(.flag))'
```

### OS:

MacOS

### DuckDB Version:

1.5.0, 1.5.1, 1.5.2

### DuckDB Client:

CLI

### Hardware:

arm64

### Full Name:

Nikolai Zujev

### Affiliation:

Deloitte

### Did you include all relevant configuration (e.g., CPU architecture, Linux distribution) to reproduce the issue?

- [x] Yes, I have

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### PR DESCRIPTION
**Pull request by herbenderbler**
Fixes https://github.com/duckdb/duckdb/issues/22061

## Problem

In `--json` / `.mode json` (and JSON Lines), `BOOLEAN` columns were serialized as JSON **strings** (`"true"` and `"false"`) instead of JSON **booleans** (`true` and `false`).

`ModeJsonRenderer` casts most columns to `VARCHAR` for printing. Boolean values become the strings `true` / `false`. The renderer then treated every non-numeric type as needing JSON string quoting, so those values were wrapped again as `"true"` / `"false"`. That breaks consumers such as `jq` (e.g. `select(.flag)` treats any non-empty string as truthy, so `"false"` is incorrectly kept).

## Solution

In `ModeJsonRenderer::RequiresQuotes`, treat `LogicalTypeId::BOOLEAN` like unquoted JSON literals: do not pass the rendered value through `EscapeJSONString`, so the output matches JSON boolean syntax.

## Changes

- `tools/shell/shell_renderer.cpp` — boolean branch in `RequiresQuotes` with a short comment explaining the VARCHAR cast + JSON literal behavior.
- `tools/shell/tests/test_shell_rendering.py` — `test_mode_json_boolean` to assert `true` / `false` appear as JSON booleans in `.mode json` output.
- `tools/shell/tests/test_rendering_mode_regression.py` — update `all_types` expected output for `json` and `jsonlines` so the `bool` field is `true` / `false`, not quoted strings.

## Testing

- `make format-fix` was run on the touched files.
- Shell tests: run the new test (and any shell regression tests you rely on) with your built CLI, for example:
  - `pytest tools/shell/tests/test_shell_rendering.py::test_mode_json_boolean --shell-binary <path/to/duckdb>`
- Per [CONTRIBUTING.md](CONTRIBUTING.md), ensure CI passes on your fork before marking the PR ready for review.

### Manual verification (official releases vs this branch)

Using **`duckdb_cli-osx-arm64.zip`** from GitHub releases for **v1.4.4** (pre-1.5) and **v1.5.2**, compared with a **`build/release/duckdb`** from this branch:

1. **`duckdb --json -s 'SELECT true AS pos, false AS neg'`**
   - **v1.4.4:** `[{"pos":true,"neg":false}]` (JSON booleans).
   - **v1.5.2:** `[{"pos":"true","neg":"false"}]` (regression: string values).
   - **This branch:** `[{"pos":true,"neg":false}]` (matches v1.4.4).

2. **`duckdb --json -s 'SELECT 1 AS id, true AS flag UNION SELECT 2 AS id, false AS flag' | jq 'map(select(.flag))'`**
   - **v1.4.4:** Only the row with `id: 1` and boolean `flag: true` (expected).
   - **v1.5.2:** Both rows: `"false"` is a non-empty JSON string, so `jq`’s `select(.flag)` incorrectly keeps `id: 2` as well.
   - **This branch:** Same result as v1.4.4 (only `id: 1`).

### CODE REVIEW

File: benchmark/imdb_plan_cost/init/load.sql [hunk 1]
```diff
@@ -1,3 +1,7 @@
+-- Same extensions as benchmark/imdb (require httpfs; require parquet): load once before remote Parquet reads.
+LOAD httpfs;
```
Comment (Mytherin) [inline benchmark/imdb_plan_cost/init/load.sql]: Can we remove this?

**Review by Mytherin — COMMENTED** [review]
Thanks - LGTM, one comment

File: benchmark/imdb_plan_cost/init/load.sql (hunk 1 above)
Comment (herbenderbler) [reply benchmark/imdb_plan_cost/init/load.sql]: No problem!

**Comment by Mytherin** [comment]
Actually can we retarget this to `v1.5-variegata` so this can be fixed in the next patch release?

**Comment by herbenderbler** [comment]
> Actually can we retarget this to `v1.5-variegata` so this can be fixed in the next patch release?

I _think_ I did that correctly.  Let me know if there's anything else I can do to help this merge.

**Comment by Mytherin** [comment]
Seems to be failing CI now - can you have another look

**Comment by Mytherin** [comment]
Can we revert the CI changes?

**Comment by Mytherin** [comment]
Thanks!
