### PR TITLE
Correctly handle query parameters in JDBC

### LINKED ISSUE #4136: JDBC client incorrectly handles Unicode characters in prepared statement parameters
#### What happens?
When a Unicode character is used as a prepared statement parameter, the query results contain incorrect bytes for the character. Maybe related to https://github.com/duckdb/duckdb/issues/3956?

#### To Reproduce
Reproduction case can be found at https://github.com/michaeljohnalbers/duckdb-issue-reproduction/releases/tag/unicode-chars-prepared-stmt-params

#### Environment (please complete the following information):
 - OS: Ubuntu Linux
 - DuckDB Version: 0.4.0
 - DuckDB Client: JDBC

#### Identity Disclosure:
 - Full Name: Michael Albers
 - Affiliation: Mode Analytics

If the above is not given and is not obvious from your GitHub profile page, we might close your issue without further review. Please refer to the [reasoning behind this rule](https://berthub.eu/articles/posts/anonymous-help/) if you have questions.

#### Before Submitting

- [X] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [X] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

### PR DESCRIPTION
**Pull request by michaeljohnalbers**
* Closes duckdb/duckdb/issues/4136

### CODE REVIEW

File: tools/jdbc/src/jni/duckdb_java.cpp [hunk 1]
```diff
@@ -187,6 +191,12 @@ static string byte_array_to_string(JNIEnv *env, jbyteArray ba_j) {
 	return ret;
 }
 
+static string jstring_to_string(JNIEnv *env, jstring string_j) {
+	jobject charset = env->CallStaticObjectMethod(J_Charset, J_Charset_forName, env->NewStringUTF("UTF-8"));
```
Comment (Jens-H) [inline tools/jdbc/src/jni/duckdb_java.cpp:195]: This charset jobject is basically a constant, isn't it? If so, I might be moved up into the JNI_OnLoad function to avoid the JNI->Java calls every time. What do you think?

**Comment by jonathanswenson** [comment]
I'm no authority here, but I recently did a change to support emoji and other characters in the JDBC string appender following a slightly different pattern -- extracting the byte array in the java layer and passing the byte array through to the JNI layer. 
https://github.com/duckdb/duckdb/pull/3957/files#diff-dffcfa5e28dff3d9f9c132c04d89fd344169d379256244bc324e1be8ccf2f4f9R62

I modeled this after how things were being done else where in the JDBC driver: 
https://github.com/duckdb/duckdb/blob/2c623978d700443665d519282ee52891e4573a3d/tools/jdbc/src/main/java/org/duckdb/DuckDBAppender.java#L15

That being said, this looks like it works too. 

Seems like one of these patterns should likely be applied across the entire JDBC driver implementation to ensure the full UTF-8 character set is supported everywhere.

**Comment by Jens-H** [comment]
I think this solution is straightforward and ideally already applied on the Java side (like with the appender call). Here it is not possible, but the same approach should work, too.

Luckily I found only one other call to GetStringUTFChars and this one does not see emojis.

File: tools/jdbc/src/jni/duckdb_java.cpp (hunk 1 above)
Comment (michaeljohnalbers) [reply tools/jdbc/src/jni/duckdb_java.cpp]: Fixed.

**Comment by Mytherin** [comment]
Thanks, LGTM
