### PR TITLE
Fixes #2240: Support in-place updates of varchar

### LINKED ISSUE #2240: Exception thrown when inserting and updating a text column in the same row in a transaction
**What does happen?**
If you insert and update a row in the same transaction, it will fail for columns of type 'text' with the error 
"Unsupported type for in-place update", thrown here: 

https://github.com/duckdb/duckdb/blob/33299a4f8583c648a7473e61757fe61f86b5ddbe/src/storage/local_storage.cpp#L274-L300

**What should happen?**
The row should be updated.

**To Reproduce**

```
BEGIN TRANSACTION;
CREATE TABLE test (id INTEGER, name TEXT);
INSERT INTO test VALUES (1, 'Bob');
UPDATE test SET name = 'Alice' Where id = 1;
```

Note that this succeeds if you COMMIT before the UPDATE statement.

**Environment (please complete the following information):**
 - OS: Linux/Ubuntu 20.04
 - DuckDB Version: 0.2.7

Command line and JDBC.

**Before submitting**
- [X] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [ ] Not tried against master, but an inspection of [local_storage.cpp](https://github.com/duckdb/duckdb/blob/33299a4f8583c648a7473e61757fe61f86b5ddbe/src/storage/local_storage.cpp#L298) suggests that this case remains unimplemented for all types except INT8, INT16, INT32, INT64, FLOAT, and DOUBLE.

### PR DESCRIPTION
**Pull request by akbertram**
This adds support for updating a column of type VARCHAR in-place during a transaction.

### CODE REVIEW

File: src/storage/local_storage.cpp [hunk 1]
```diff
@@ -294,8 +294,11 @@ static void UpdateChunk(Vector &data, Vector &updates, Vector &row_ids, idx_t co
 	case PhysicalType::DOUBLE:
 		TemplatedUpdateLoop<double>(data, updates, row_ids, count, base_index);
 		break;
+	case PhysicalType::VARCHAR:
+		TemplatedUpdateLoop<string_t>(data, updates, row_ids, count, base_index);
+		break;
 	default:
-		throw Exception("Unsupported type for in-place update");
+		throw Exception("Unsupported type for in-place update: " + TypeIdToString(data.GetType().InternalType()));
```
Comment (hannesmuehleisen) [inline src/storage/local_storage.cpp:301]: This could just be `data.GetType().ToString()` no?

Comment (akbertram) [reply src/storage/local_storage.cpp:301]: I wasn't quite sure what the difference between `GetType()` and `GetType().InternalType()` is. Since the switch is based on the internal type I thought this might be more useful debugging information, as I initially expected the internal type of my `TEXT` column to `STRING`, but it was actually `VARCHAR`. 

Of course happy to change if I've misunderstood or if `GetType().ToString()` is more useful in this context!

**Comment by Mytherin** [comment]
Thanks for the PR, looks good!
