### PR TITLE
Fix `try_cast` from NaN `double` to `decimal`

### LINKED ISSUE #17310: Casting issue from float64 to decimal
### What happens?

we get the following error with 1.3.0 pre-release when reading numbers from a json through parquet. With 1.2.2 it works fine.

```
Invalid Input Error:
Type DOUBLE with value nan can't be cast because the value is out of range for the destination type INT64
```

### To Reproduce

test.json

```
{"IDENT":"K-00400868","X_STORAGE":0.04851963844167154}
```

cli:
```
duckdb ":memory:" "copy (select * from test.json) to test_2.parquet"
duckdb ":memory:" "select ident, x_storage::decimal(18, 2) from 'test_2.parquet'"
```

DuckDB 1.2.2 works fine:
```
┌────────────┬──────────────────────────────────┐
│   IDENT    │ CAST(x_storage AS DECIMAL(18,2)) │
│  varchar   │          decimal(18,2)           │
├────────────┼──────────────────────────────────┤
│ K-00400868 │               0.05               │
└────────────┴──────────────────────────────────┘
```

### OS:

Ubuntu 22.04

### DuckDB Version:

1.3.3 Pre-Release

### DuckDB Client:

CLI + Python

### Hardware:

_No response_

### Full Name:

Daniel Gut

### Affiliation:

Aveniq

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [x] Yes, I have

### PR DESCRIPTION
**Pull request by lnkuiper**
Fixes #17310

This should return `NULL`, not throw an error.

### CODE REVIEW

File: src/common/operator/cast_operators.cpp [hunk 1]
```diff
@@ -2311,7 +2311,7 @@ bool DoubleToDecimalCast(SRC input, DST &result, CastParameters &parameters, uin
 	double value = input * NumericHelper::DOUBLE_POWERS_OF_TEN[scale];
 	double roundedValue = round(value);
 	if (roundedValue <= -NumericHelper::DOUBLE_POWERS_OF_TEN[width] ||
-	    roundedValue >= NumericHelper::DOUBLE_POWERS_OF_TEN[width]) {
+	    roundedValue >= NumericHelper::DOUBLE_POWERS_OF_TEN[width] || isnan(roundedValue) || isinf(roundedValue)) {
```
Comment (Mytherin) [inline src/common/operator/cast_operators.cpp:2314]: Using `Value::IsFinite` should fix the include errors :)
