### PR TITLE
Use ISNULL in conjunction or filters

### LINKED ISSUE #15479: INTERNAL Error: ConstantFilter constant cannot be NULL - use IsNullFilter instead
### What happens?

The below test case triggered an internal error in DuckDB.

### To Reproduce

```sql
CREATE TABLE  t0(c1 INT);
SELECT * FROM t0 WHERE ((t0.c1 IS DISTINCT FROM NULL) OR (NOT NULL));
```

### OS:

Ubuntu 22.04

### DuckDB Version:

v1.1.4-dev3741 ab8c909857

### DuckDB Client:

CLI

### Hardware:

_No response_

### Full Name:

Suyang Zhong

### Affiliation:

NUS

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by Tmonster**
Fixes https://github.com/duckdblabs/duckdb-internal/issues/3838
Fixes https://github.com/duckdb/duckdb/issues/15479

When adding support for OR filters in table filter scans, we forgot to check for NULL in the conjunction OR.

### CODE REVIEW

File: src/optimizer/filter_combiner.cpp [hunk 1]
```diff
@@ -705,8 +705,27 @@ TableFilterSet FilterCombiner::GenerateTableScanFilters(const vector<ColumnIndex
...
 					auto comparison_type =
 					    invert ? FlipComparisonExpression(comp.GetExpressionType()) : comp.GetExpressionType();
-					auto const_filter = make_uniq<ConstantFilter>(comparison_type, const_val->value);
-					conj_filter->child_filters.push_back(std::move(const_filter));
+					if (const_val->value.IsNull()) {
+						switch (comparison_type) {
+						case ExpressionType::COMPARE_EQUAL:
+						case ExpressionType::COMPARE_DISTINCT_FROM: {
+							auto null_filter = make_uniq<IsNullFilter>();
+							conj_filter->child_filters.push_back(std::move(null_filter));
```
Comment (Mytherin) [inline src/optimizer/filter_combiner.cpp:713]: `x = NULL` always returns `NULL` (i.e. false) -  so this should be only `DISTINCT FROM`

File: src/optimizer/filter_combiner.cpp [hunk 2]
```diff
@@ -705,8 +705,27 @@ TableFilterSet FilterCombiner::GenerateTableScanFilters(const vector<ColumnIndex
...
+							break;
+						}
+						case ExpressionType::COMPARE_NOTEQUAL:
+						case ExpressionType::COMPARE_NOT_DISTINCT_FROM: {
+							auto null_filter = make_uniq<IsNotNullFilter>();
+							conj_filter->child_filters.push_back(std::move(null_filter));
```
Comment (Mytherin) [inline src/optimizer/filter_combiner.cpp:719]: Same here, this should be only `NOT DISTINCT FROM`

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! LGTM - minor comment:

File: src/optimizer/filter_combiner.cpp (hunk 1 above)
Comment (Tmonster) [reply src/optimizer/filter_combiner.cpp:713]: Should this mean that the table scan should just be replaced with an empty result? Since `= NULL` evaluates to NULL and as a where condition this means no rows are returned. Although for nested types NULL comparisons get tricky, but we don't support NULL pushdown into nested types yet

Comment (Mytherin) [reply src/optimizer/filter_combiner.cpp:713]: Yes, that's also a possible optimization, it is indeed always false

Comment (Tmonster) [reply src/optimizer/filter_combiner.cpp:712]: Turns out Postgres/sqlite both evaluate `WHERE NULL or TRUE` to TRUE, so `(a = NULL OR TRUE)` should not be replaced with an empty result.

Comment (Mytherin) [reply src/optimizer/filter_combiner.cpp:712]: Yes, that's SQL standard boolean logic (similarly `FALSE AND NULL` also returns `FALSE`).

**Comment by Mytherin** [comment]
Thanks!
