### PR TITLE
Fix #3756: fix issue when running blockwise NL join on dictionary vectors of structs

### LINKED ISSUE #3756: Incorrect Aggregate Calculation
The data in this test can be found by cloning 

```
git clone git@github.com:lloydtabb/imdb_malloy.git
make
```

It seems there is a bug in DISTINCTing.  Not sure exactly where.

```
SELECT
    group_set,
    COUNT(DISTINCT concat(movies_queries.tconst, '|', IFNULL(movies_queries.ratings.numVotes,0)::varchar) )  as all_movie_votes,
    case when group_set = 0 THEN
      COUNT(DISTINCT concat(movies_queries.tconst, '|', IFNULL(movies_queries.ratings.numVotes,0)::varchar) )
    END as movie_votes0,
    case when group_set = 1 THEN
      COUNT(DISTINCT concat(movies_queries.tconst, '|', IFNULL(movies_queries.ratings.numVotes,0)::varchar) )
    END as movie_votes1

  FROM 'titles.parquet' as movies_queries
  LEFT JOIN 'principals.parquet' AS principals_0
    ON movies_queries.tconst=principals_0.tconst
  -- comment out the line below to make the bug go away
  LEFT JOIN 'names.parquet' AS people_0 ON principals_0.nconst=people_0.nconst
  CROSS JOIN (SELECT UNNEST(GENERATE_SERIES(0,1,1)) as group_set  ) as group_set
  WHERE (movies_queries.ratings.numVotes>30000)
     -- comment the line below to make the bug go away.
     AND ((group_set NOT IN (1) OR (group_set IN (1) AND principals_0.category='director')))
  GROUP BY 1
  ```

The proper result is 6094 distinct movies.  There should be nothing a join can do to change the calculation of a count distinct, yet it does.  The where clause  should only effect calulations in group_set= 1, yet it effects calculations in group_set=0

Changing either of the lines below the comment will produce an accurate calculation.

image

### PR DESCRIPTION
**Pull request by Mytherin**
Fixes #3756 

The problem was caused by an incorrect index being used in the `ConstantVector::Reference` method when used with a struct type. This method was called in the `Blockwise NL join`, which is the join type that is used when there are no straightforward comparison join expressions available, and a complex join expressions has to be used (e.g. an `OR` clause or other complex expressions).

### CODE REVIEW

File: src/common/types/vector.cpp [hunk 1]
```diff
@@ -1179,7 +1178,7 @@ void ConstantVector::Reference(Vector &vector, Vector &source, idx_t position, i
 		auto &source_entries = StructVector::GetEntries(source);
 		auto &target_entries = StructVector::GetEntries(vector);
 		for (idx_t i = 0; i < source_entries.size(); i++) {
-			ConstantVector::Reference(*target_entries[i], *source_entries[i], position, count);
+			ConstantVector::Reference(*target_entries[i], *source_entries[i], struct_index, count);
```
Comment (hawkfish) [inline src/common/types/vector.cpp:1181]: Shouldn't this be looked up by entry instead of globally? What if the components have been sliced differently?

**Review by hawkfish — APPROVED** [review]
