### PR TITLE
Fix #2986: correctly copy old data over when calling repalloc in parser

### LINKED ISSUE #2986: Long string with double apostrophe becomes empty string
#### What happens?
A long string with an apostrophe becomes an empty string.

#### To Reproduce
```sql
CREATE TABLE j2 (id INT, json VARCHAR, src VARCHAR);
INSERT INTO j2(id,json,src)
    VALUES(3,'[
    {
        "id": "0001",
        "type": "donut",
        "name": "Cake",
        "ppu": 0.55,
        "batters":
            {
                "batter":
                    [
                        { "id": "1001", "type": "Regular" },
                        { "id": "1002", "type": "Chocolate" },
                        { "id": "1003", "type": "Blueberry" },
                        { "id": "1004", "type": "Devil''s Food" }
                    ]
            },
        "topping":
            [
                { "id": "5001", "type": "None" },
                { "id": "5002", "type": "Glazed" },
                { "id": "5005", "type": "Sugar" },
                { "id": "5007", "type": "Powdered Sugar" },
                { "id": "5006", "type": "Chocolate with Sprinkles" },
                { "id": "5003", "type": "Chocolate" },
                { "id": "5004", "type": "Maple" }
            ]
    },
    {
        "id": "0002",
        "type": "donut",
        "name": "Raised",
        "ppu": 0.55,
        "batters":
            {
                "batter":
                    [
                        { "id": "1001", "type": "Regular" }
                    ]
            },
        "topping":
            [
                { "id": "5001", "type": "None" },
                { "id": "5002", "type": "Glazed" },
                { "id": "5005", "type": "Sugar" },
                { "id": "5003", "type": "Chocolate" },
                { "id": "5004", "type": "Maple" }
            ]
    },
    {
        "id": "0003",
        "type": "donut",
        "name": "Old Fashioned",
        "ppu": 0.55,
        "batters":
            {
                "batter":
                    [
                        { "id": "1001", "type": "Regular" },
                        { "id": "1002", "type": "Chocolate" }
                    ]
            },
        "topping":
            [
                { "id": "5001", "type": "None" },
                { "id": "5002", "type": "Glazed" },
                { "id": "5003", "type": "Chocolate" },
                { "id": "5004", "type": "Maple" }
            ]
    }
    ]','https://adobe.github.io/Spry/samples/data_region/JSONDataSetSample.html');
SELECT json = '' FROM j2;
-- true
```
We would expect the query to return `false`.

The bug does not occur when I remove the `''` from `"Devil''s Food"`.
The bug also does not appear when the string is much shorter, e.g.:
```sql
CREATE TABLE j2 (id INT, json VARCHAR, src VARCHAR);
INSERT INTO j2(id,json,src)
    VALUES(3,'[
    {
        "id": "0001",
        "type": "donut",
        "name": "Cake",
        "ppu": 0.55,
        "batters":
            {
                "batter":
                    [
                        { "id": "1001", "type": "Regular" },
                        { "id": "1002", "type": "Chocolate" },
                        { "id": "1003", "type": "Blueberry" },
                        { "id": "1004", "type": "Devil''s Food" }
                    ]
            },
        "topping":
            [
                { "id": "5001", "type": "None" },
                { "id": "5002", "type": "Glazed" },
                { "id": "5005", "type": "Sugar" },
                { "id": "5007", "type": "Powdered Sugar" },
                { "id": "5006", "type": "Chocolate with Sprinkles" },
                { "id": "5003", "type": "Chocolate" },
                { "id": "5004", "type": "Maple" }
            ]
    }
    ]','https://adobe.github.io/Spry/samples/data_region/JSONDataSetSample.html');
SELECT json = '' FROM j2;
-- false
```

The string is stored correctly. I ran the same query in Postgres to see if it has something to do with the parser, but there it worked fine.

#### Environment (please complete the following information):
 - OS: macOS
 - DuckDB Version: master
 - DuckDB Client: CLI

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

### PR DESCRIPTION
**Pull request by Mytherin**
Fixes #2986

### CODE REVIEW

File: third_party/libpg_query/pg_functions.cpp [hunk 1]
```diff
@@ -55,12 +55,17 @@ static void allocate_new(parser_state *state, size_t n) {
 
 void *palloc(size_t n) {
 	// we need to align our pointers for the sanitizer
-	auto aligned_n = ((n + 7) / 8) * 8;
+	auto allocate_n = n + sizeof(size_t);
+	auto aligned_n = ((allocate_n + 7) / 8) * 8;
```
Comment (hawkfish) [inline third_party/libpg_query/pg_functions.cpp:59]: Don't we have a utility function for this somewhere? Align<T> or something?

**Review by hawkfish — APPROVED** [review]

File: third_party/libpg_query/pg_functions.cpp (hunk 1 above)
Comment (Mytherin) [reply third_party/libpg_query/pg_functions.cpp:59]: Yes, but since this is in the libpg_query library in the third_party folder we prefer not to link it back to the main DuckDB sources.

Comment (hawkfish) [reply third_party/libpg_query/pg_functions.cpp:59]: That's what I figured, but thought I should ask.
