### PR TITLE
Produce an empty list result for enum_range(NULL::enum_type)

### LINKED ISSUE #13473: Enum type with no members
### What happens?

I'm not sure if an Enum type with no members is permitted by design or it is a bug but calling `enum_range` on such type causes an internal error.

image

### To Reproduce

```sql
CREATE TYPE mood AS ENUM ();

SELECT enum_range(NULL::mood) AS my_enum_range;
```
Results in: 
> INTERNAL Error: Value::LIST without providing a child-type requires a non-empty list of values. Use Value::LIST(child_type, list) instead.

### OS:

Windows 11 x64

### DuckDB Version:

v1.0.1-dev4228

### DuckDB Client:

CLI

### Full Name:

Giorgi Dalakishvili

### Affiliation:

Space International

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by pdet**
Fix: #13473

### CODE REVIEW

File: src/core_functions/scalar/enum/enum_functions.cpp [hunk 1]
```diff
@@ -28,7 +28,12 @@ static void EnumRangeFunction(DataChunk &input, ExpressionState &state, Vector &
 	for (idx_t i = 0; i < enum_size; i++) {
 		enum_values.emplace_back(enum_vector.GetValue(i));
 	}
-	auto val = Value::LIST(enum_values);
+	Value val;
+	if (!enum_values.empty()) {
+		val = Value::LIST(enum_values);
```
Comment (Mytherin) [inline src/core_functions/scalar/enum/enum_functions.cpp:33]: Perhaps we can use `Value::LIST(LogicalType::VARCHAR, enum_values)` instead of using `Value::EMPTYLIST?

File: src/core_functions/scalar/enum/enum_functions.cpp [hunk 2]
```diff
@@ -28,7 +28,12 @@ static void EnumRangeFunction(DataChunk &input, ExpressionState &state, Vector &
...
+	} else {
+		val = Value::EMPTYLIST(types[0]);
```
Comment (Mytherin) [inline src/core_functions/scalar/enum/enum_functions.cpp:35]: `types[0]` is the enum type - the function definition states we should return a varchar list (although Postgres returns an array of the enum type instead of a varchar list, not sure if we want to do anything with that).

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Looks good - some minor comments:

**Comment by Mytherin** [comment]
Thanks!
