### PR TITLE
Fix invalid memory access when CSV columns less than expected

### LINKED ISSUE #4379: AddressSanitizer:DEADLYSIGNAL
Issue found by csv_multi_param_fuzzer on git commit hash [310d0](https://github.com/duckdb/duckdb/commit/310d07d36d08217b5f2150efca6a6b2a12659191) using seed 0.
### To Reproduce
```sql
.sh wget https://github.com/duckdb/duckdb-fuzzer/raw/refs/heads/main/reproduction_inputs/csv/20260403_b0c39a.csv
from read_csv('20260403_b0c39a.csv', columns={ 'date': 'DATE', 'datetime': 'TIMESTAMPTZ', 'time': 'TIME', 'timestamp': 'TIMESTAMP', 'time_tz': 'TIMETZ' }, store_rejects=true);
```

### Error Message
```
AddressSanitizer:DEADLYSIGNAL
```

### Stack Trace
```
=================================================================
==11128==ERROR: AddressSanitizer: SEGV on unknown address (pc  bp  sp  T0)
==11128==The signal is caused by a READ memory access.
==11128==Hint: this fault was caused by a dereference of a high value address (see register values below).  Disassemble the provided pc to learn which register was used.
    #0  in duckdb::Time::TryConvertInternal(char const*, unsigned long, unsigned long&, duckdb::dtime_t&, bool, duckdb::optional_ptr<int, true>) (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #1  in duckdb::Time::TryConvertTimeTZ(char const*, unsigned long, unsigned long&, duckdb::dtime_tz_t&, bool&, bool, duckdb::optional_ptr<int, true>) (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #2  in bool duckdb::TryCast::Operation<duckdb::string_t, duckdb::dtime_tz_t>(duckdb::string_t, duckdb::dtime_tz_t&, bool) (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #3  in bool duckdb::TryCastErrorMessage::Operation<duckdb::string_t, duckdb::dtime_tz_t>(duckdb::string_t, duckdb::dtime_tz_t&, duckdb::CastParameters&) (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #4  in duckdb::dtime_tz_t duckdb::VectorTryCastErrorOperator<duckdb::TryCastErrorMessage>::Operation<duckdb::string_t, duckdb::dtime_tz_t>(duckdb::string_t, duckdb::ValidityMask&, unsigned long, void*) (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #5  in duckdb::dtime_tz_t duckdb::GenericUnaryWrapper::Operation<duckdb::VectorTryCastErrorOperator<duckdb::TryCastErrorMessage>, duckdb::string_t, duckdb::dtime_tz_t>(duckdb::string_t, duckdb::ValidityMask&, unsigned long, void*) (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #6  in void duckdb::UnaryExecutor::ExecuteFlat<duckdb::string_t, duckdb::dtime_tz_t, duckdb::GenericUnaryWrapper, duckdb::VectorTryCastErrorOperator<duckdb::TryCastErrorMessage> >(duckdb::string_t const*, duckdb::dtime_tz_t*, unsigned long, duckdb::ValidityMask&, duckdb::ValidityMask&, void*, bool) (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #7  in void duckdb::UnaryExecutor::ExecuteStandard<duckdb::string_t, duckdb::dtime_tz_t, duckdb::GenericUnaryWrapper, duckdb::VectorTryCastErrorOperator<duckdb::TryCastErrorMessage> >(duckdb::Vector&, duckdb::Vector&, unsigned long, void*, bool, duckdb::FunctionErrors) (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #8  in void duckdb::UnaryExecutor::GenericExecute<duckdb::string_t, duckdb::dtime_tz_t, duckdb::VectorTryCastErrorOperator<duckdb::TryCastErrorMessage> >(duckdb::Vector&, duckdb::Vector&, unsigned long, void*, bool) (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #9  in bool duckdb::VectorCastHelpers::TemplatedTryCastLoop<duckdb::string_t, duckdb::dtime_tz_t, duckdb::VectorTryCastErrorOperator<duckdb::TryCastErrorMessage> >(duckdb::Vector&, duckdb::Vector&, unsigned long, duckdb::CastParameters&) (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #10  in bool duckdb::VectorCastHelpers::TryCastErrorLoop<duckdb::string_t, duckdb::dtime_tz_t, duckdb::TryCastErrorMessage>(duckdb::Vector&, duckdb::Vector&, unsigned long, duckdb::CastParameters&) (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #11  in duckdb::VectorOperations::TryCast(duckdb::CastFunctionSet&, duckdb::GetCastFunctionInput&, duckdb::Vector&, duckdb::Vector&, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool, bool) (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #12  in duckdb::VectorOperations::TryCast(duckdb::ClientContext&, duckdb::Vector&, duckdb::Vector&, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool, bool) (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #13  in duckdb::StringValueScanner::Flush(duckdb::DataChunk&) (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #14  in duckdb::CSVFileScan::Scan(duckdb::ClientContext&, duckdb::GlobalTableFunctionState&, duckdb::LocalTableFunctionState&, duckdb::DataChunk&) (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #15  in duckdb::MultiFileFunction<duckdb::CSVMultiFileInfo>::MultiFileScan(duckdb::ClientContext&, duckdb::TableFunctionInput&, duckdb::DataChunk&) (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #16  in duckdb::PhysicalTableScan::GetDataInternal(duckdb::ExecutionContext&, duckdb::DataChunk&, duckdb::OperatorSourceInput&) const (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #17  in duckdb::PhysicalOperator::GetData(duckdb::ExecutionContext&, duckdb::DataChunk&, duckdb::OperatorSourceInput&) const (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #18  in duckdb::PipelineExecutor::GetData(duckdb::DataChunk&, duckdb::OperatorSourceInput&) (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #19  in duckdb::PipelineExecutor::FetchFromSource(duckdb::DataChunk&) (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #20  in duckdb::PipelineExecutor::Execute(unsigned long) (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #21  in duckdb::PipelineTask::ExecuteTask(duckdb::TaskExecutionMode) (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #22  in duckdb::ExecutorTask::Execute(duckdb::TaskExecutionMode) (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #23  in duckdb::Executor::ExecuteTask(bool) (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #24  in duckdb::ClientContext::ExecuteTaskInternal(duckdb::ClientContextLock&, duckdb::BaseQueryResult&, bool) (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #25  in duckdb::PendingQueryResult::ExecuteTaskInternal(duckdb::ClientContextLock&) (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #26  in duckdb::PendingQueryResult::ExecuteInternal(duckdb::ClientContextLock&) (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #27  in duckdb::PendingQueryResult::Execute() (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #28  in duckdb::ClientContext::Query(duckdb::unique_ptr<duckdb::SQLStatement, std::default_delete<duckdb::SQLStatement>, true>, duckdb::QueryParameters) (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #29  in duckdb::Connection::SendQuery(duckdb::unique_ptr<duckdb::SQLStatement, std::default_delete<duckdb::SQLStatement>, true>, duckdb::QueryParameters) (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #30  in duckdb_shell::ShellState::ExecuteStatement(duckdb::unique_ptr<duckdb::SQLStatement, std::default_delete<duckdb::SQLStatement>, true>) (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #31  in duckdb_shell::ShellState::ExecuteSQL(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #32  in duckdb_shell::ShellState::RunOneSqlLine(duckdb_shell::InputMode, char*) (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #33  in duckdb_shell::ShellState::ProcessInput(duckdb_shell::InputMode) (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #34  in RunShell(int, char const**) (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #35  in main (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)
    #36   (    #37  in __libc_start_main (    #38  in _start (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/home/runner/work/duckdb-fuzzer-ci/duckdb-fuzzer-ci/duckdb/build/debug/duckdb) (BuildId: 5ff5b202c382619d2de9ec1c2d216e65d819fc77) in duckdb::Time::TryConvertInternal(char const*, unsigned long, unsigned long&, duckdb::dtime_t&, bool, duckdb::optional_ptr<int, true>)
==11128==ABORTING
```

### PR DESCRIPTION
**Pull request by dentiny**
Closes https://github.com/duckdb/duckdb-fuzzer/issues/4379

`StringValueResult` allocate a large chunk of uninitialized memory for chunk data at [constructor](https://github.com/duckdb/duckdb/blob/af66da7d6cb98a933e6f08390ba3661a15a54818/src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp#L105-L110).

The CSV row which suffers invalid memory has 5 columns, but only 4 values in the culprit row, leaving the last 5-th untouched -- value uninitialized memory but validity bit true (default).

On `Flush`, `TryCast` consider the row to be valid and attempts to cast the whole row but access invalid memory.
The fix proposed in this PR is to mark the un-encountered values as invalid, so the whole row will be skipped to parse and [be in the result](https://github.com/duckdb/duckdb/blob/af66da7d6cb98a933e6f08390ba3661a15a54818/src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp#L1174-L1176).

I have ran CI on my fork: https://github.com/dentiny/duckdb/pull/78

### CODE REVIEW

File: src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp [hunk 1]
```diff
@@ -834,7 +834,23 @@ bool StringValueResult::AddRowInternal() {
...
+	// Keep the current parse progress, `HandleErrors` reset states.
+	const auto chunk_col_id_before = chunk_col_id;
 	if (current_errors.HandleErrors(*this)) {
+		// There're two cases here:
+		// - ignore errors = true, with last row being removed
+		// - store rejects = true, with last row index being added to borked rows
+		// Invalid all columns that are not populated for this row, when the row still exists.
+		if (borked_rows.find(static_cast<idx_t>(number_of_rows)) != borked_rows.end()) {
+			for (idx_t cur_col_idx = chunk_col_id_before; cur_col_idx < validity_mask.size(); ++cur_col_idx) {
+				validity_mask[cur_col_idx]->SetInvalid(static_cast<idx_t>(number_of_rows));
```
Comment (Mytherin) [inline src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp:843]: Maybe we can just set the validity to `NULL` in the `if (!state_machine.options.null_padding)` branch above?

I think we can also remove some of the added comments. These comments are very verbose w.r.t. this one specific issue.

**Comment by Mytherin** [comment]
Thanks for the fix! Left a comment - could you also retarget to `v1.5-variegata`?

File: src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp (hunk 1 above)
Comment (dentiny) [reply src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp:843]: For the regression test I added (which suffers invalid memory access), the `null_padding` option is true so it won't enter the if-branch.
https://github.com/dentiny/duckdb/blob/1f54bf7445f7cb0507ff840eff0decf69f243e34/test/sql/copy/csv/afl/test_fuzz_4379.test#L23

I cleaned up the verbose comments a bit.

**Comment by dentiny** [comment]
> could you also retarget to v1.5-variegata?

Sure, done!
