### PR TITLE
R: Arrow timestamps in seconds, milliseconds and nanoseconds

### LINKED ISSUE #2734: duckdb_prepare_R: Unknown column type for prepare: TIMESTAMP (NS)
#### What happens?

`arrow::to_duckdb()` fails to handle TIMESTAMP data in NS format in parquet files which duckdb created.  

#### To Reproduce

- I export data from duckdb to parquet; works as expected.
- I read the parquet with `arrow::open_dataset` from R, works as expected
- I try `arrow::to_duckb()` and get the error on any timestamp-type column

```
  duckdb_prepare_R: Unknown column type for prepare: TIMESTAMP (NS)
```

(Guessing this is a just a datatype that still needs to be implemented on the parquet reader, at least for the R client?  lemme know if a copy-paste example of R would help)

#### Environment (please complete the following information):
 - OS: Linux
 - DuckDB Version: current
 - DuckDB Client: R

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

### PR DESCRIPTION
**Pull request by james-atkins**
Fixes duckdb#2734

Currently only Arrow timestamps in microseconds are supported by the R
package - for other units, an error is raised. Add support for
timestamps in seconds, milliseconds and nanoseconds.

All units are converted to R's POSIXct format. As there may be a
precision loss when nanoseconds are converted, a one-time warning is
shown.

### CODE REVIEW

File: tools/rpkg/src/statement.cpp [hunk 1]
```diff
@@ -268,20 +274,67 @@ static void transform(Vector &src_vec, SEXP &dest, idx_t dest_offset, idx_t n) {
 	case LogicalTypeId::INTEGER:
 		VectorToR<int32_t, uint32_t>(src_vec, n, INTEGER_POINTER(dest), dest_offset, NA_INTEGER);
 		break;
+	case LogicalTypeId::TIMESTAMP_SEC: {
+		auto src_data = FlatVector::GetData<int64_t>(src_vec);
```
Comment (Mytherin) [inline tools/rpkg/src/statement.cpp:278]: This code seems to be duplicated four times, could we extract this into a templated function?

For example, see how this is done [in the Python wrapper](https://github.com/duckdb/duckdb/blob/b48ff00354c88ea9ce4c9554adfa10689146cdd2/tools/pythonpkg/src/array_wrapper.cpp#L664).

**Comment by Mytherin** [comment]
Thanks for the PR! Looks good. One comment:

File: tools/rpkg/src/statement.cpp [hunk 2]
```diff
@@ -268,20 +274,67 @@ static void transform(Vector &src_vec, SEXP &dest, idx_t dest_offset, idx_t n) {
...
+		for (size_t row_idx = 0; row_idx < n; row_idx++) {
+			dest_ptr[row_idx] =
+			    !mask.RowIsValid(row_idx) ? NA_REAL : (double)src_data[row_idx] / Interval::NANOS_PER_SEC;
+		}
+
+		// some dresssup for R
+		SET_CLASS(dest, RStrings::get().POSIXct_POSIXt_str);
+		Rf_setAttrib(dest, RStrings::get().tzone_sym, RStrings::get().UTC_str);
+
+		static bool precision_warning = false;
```
Comment (Mytherin) [inline tools/rpkg/src/statement.cpp:331]: This isn't thread safe, right? Does it matter or is this code guaranteed to only be called once because of the R interpreter? @hannesmuehleisen thoughts on this?

Comment (Mytherin) [reply tools/rpkg/src/statement.cpp:331]: Could use [`std::call_once`](https://en.cppreference.com/w/cpp/thread/call_once) for this.

**Comment by james-atkins** [comment]
Thanks for the comments. Will tidy up the duplicated code and look at call_once.

Looking at the Python wrapper, it seems that I should handle TIMESTAMP_TZ too? And then presumably set the "correct" timezone in the returned R type. Any pointers as to what the correct timezone is for a TIMESTAMP_TZ vs a TIMESTAMP, and how do I get it?

**Comment by Alex-Monahan** [comment]
I'm not sure where the current timezone is stored on the C++ side, but here is a way to get it using SQL in case that is helpful as a starting point!
[Timestamp docs](https://duckdb.org/docs/sql/data_types/timestamp)

```sql
SELECT * FROM duckdb_settings() WHERE name = 'TimeZone';
-- Americas/Los_Angeles
```

**Review by Mytherin — APPROVED** [review]
Thanks for the updates! This looks good. Ready for merge after feature freeze ends.
