### PR TITLE
Issue #19499: HashedSort Sorting Memory

### LINKED ISSUE #9880: Out of Memory Error: Failed to allocate block of 13230080 bytes
### What happens?

I am performing the following query with a window function and `QUALIFY` clause on a GCP `n2-highmem-64` instance (64 CPU, 500GB RAM, with plenty of free swap just in case).

```sql
-- perform query
CREATE TABLE tbl_out AS
SELECT
	A, B, C,
	row_number() OVER (PARTITION BY A, B ORDER BY C DESC) AS D
FROM tbl_in
QUALIFY row_number() OVER (PARTITION BY A, B ORDER BY C DESC) <= 5
ORDER BY A, B, D ASC;
```

DuckDB is configured as such:

```sql
-- only use 16 threads and 200G RAM, set a temporary directory
SET threads TO 16;
SET memory_limit = '200GB';
SET temp_directory='<some path>';
```

This issue is likely similar to https://github.com/duckdb/duckdb/issues/8135: the issue happens randomly, and there's 300GB of free RAM available.

As advised by @hawkfish [here](https://github.com/duckdb/duckdb/issues/8135#issuecomment-1684399615), I reduced the thread count which helped for previous queries, but not this one. I set memory to less than 50% of the available RAM. I set up a temporary directory.

This query works on my OSX M1 Max, 64GB RAM, 10 CPUs.

### To Reproduce

I cannot share the original data as it is private, but I generated synthetic data that keeps the original cardinality and reproduce the error.

On a GCP instance `n2-highmem-64`,

```bash
$ curl -O https://storage.googleapis.com/capp-dev/duckdb/tbl_in.parquet
$ duckdb oom
```

then

```sql
SET threads TO 16;
SET memory_limit = '200GB';
SET temp_directory='tmp';

CREATE TABLE tbl_in AS SELECT * FROM 'tbl_in.parquet';

CREATE TABLE tbl_out AS
SELECT
	A, B, C,
	row_number() OVER (PARTITION BY A, B ORDER BY C DESC) AS D
FROM tbl_in
QUALIFY row_number() OVER (PARTITION BY A, B ORDER BY C DESC) <= 5
ORDER BY A, B, D ASC;
```

You should likely see the following error:

```
Out of Memory Error: Failed to allocate block of XXXX bytes
```

although you have plenty of free RAM

### OS:

Linux instance-2 5.10.0-26-cloud-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64 GNU/Linux

### DuckDB Version:

0.9.2

### DuckDB Client:

Go

### Full Name:

Gawen Arab

### Affiliation:

airbuds.fm

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by hawkfish**
* First pass at sorting tasks.
* Fix race condition around Combine.
* Rename really slow window test.
* Fix tidy issues.

fixes: duckdb/duckdb#19499
fixes: duckdb/duckdb#9880
fixes: duckdblabs/duckdb-internal#6370
fixes: duckdblabs/duckdb-internal#856

### CODE REVIEW

File: src/common/sort/hashed_sort.cpp [hunk 1]
```diff
@@ -17,6 +17,12 @@ class HashedSortGroup {
 
 	HashedSortGroup(ClientContext &client, optional_ptr<Sort> sort, idx_t group_idx);
 
+	bool Scan(TupleDataCollection &payload, TupleDataLocalScanState &local_scan, DataChunk &chunk) {
+		//	Despite the name, TupleDataParallelScanState is not thread safe...
```
Comment (lnkuiper) [inline src/common/sort/hashed_sort.cpp:21]: Not sure why this wouldn't be thread-safe, pretty much the first thing that happens in the parallel scan code is grabbing a lock. However, this isn't well tested, as this newly added scan is now the only usage of parallel tuple data scanning in the entire code base.

I'd expect this to work when scanning with `UNPIN_AFTER_DONE` (which is the default being used here), but not with `DESTROY_AFTER_DONE` (which was used before - now removed).

I think what should happen is that each `TupleDataCollection` should be scanned independently. After the `Sink` phase, each thread has a `PartitionedTupleData`, so we should be able to do fine-grained scheduling of small tasks (one per thread per partition), single-threaded scans on each `TupleDataCollection` that can be sunk into the `Sort`. This then also allows using `DESTROY_AFTER_DONE`.

I've checkout out this branch and ran #19499, and this now finishes the query! However, it is ~30% slower than 1.3.2, as it spills more data. I think this is due to data not being freed up quickly.

**Review by lnkuiper — COMMENTED** [review]
Thanks for the PR! It looks good, I just have one comment that should be addressed, but this can also be done in a follow-up PR.

**Comment by d-justen** [comment]
Just FYI, #9880 should also be fixed by the `TopNWindowEliminationRule`, which replaces the window function with an `ArgMinMaxN` aggregate.
