### PR TITLE
[Python RelAPI] Throw an error if trying to use a invalid argument in read_csv

### LINKED ISSUE #12338: Issue with Python duckdb.read_csv not working with 0.10.2+
### What happens?

Reading from a StringIO buffer works in 0.10.1, but not in 0.10.2 or 0.10.3.

### To Reproduce

download the csv files from:

* https://www.dropbox.com/scl/fi/3xpwlfgfc0seoe4lw3vwk/cad_fi_cp1252.csv?rlkey=2wanizbvs6nr7tzrgwvquj6mf&dl=1
* https://www.dropbox.com/scl/fi/anbvm5n9gpp0dgxfanipp/cad_fi_utf8.csv?rlkey=mxdqw3disqn12lqb4d88j6woo&dl=1

and run the following script:

from io import StringIO

import duckdb

def load_csv(filename, encoding, newline="\r\n"):
    with open(filename, "rb") as fp:
        content = fp.read().decode(encoding)
        _buffer = StringIO(content.replace(newline, "\n"), newline="\n")
        return duckdb.read_csv(
            _buffer,
            normalize_names=True,
            sample_size=-1,
        )

cad_fi_utf8 = load_csv("cad_fi_utf8.csv", "utf-8")
cad_fi_cp1252 = load_csv("cad_fi_cp1252.csv", "cp1252")

assert (
    duckdb.sql("SELECT count(*) FROM cad_fi_utf8").fetchone()
    == duckdb.sql("SELECT count(*) FROM cad_fi_cp1252").fetchone()
), "Different number of rows"

### OS:

Windows 11

### DuckDB Version:

0.10.3

### DuckDB Client:

0.10.3

### Full Name:

Leo Horta

### Affiliation:

Sparta Fundos de Investimento

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by pdet**
It also gives suggestions for valid arguments.

Fix: https://github.com/duckdb/duckdb/issues/12338
where the user would use a slightly wrong argument name, and that would be silently ignored.

### CODE REVIEW

File: tools/pythonpkg/src/pyconnection.cpp [hunk 1]
```diff
@@ -896,7 +896,64 @@ static py::object GetValueOrNone(py::kwargs &kwargs, const string &key) {
...
+			std::ostringstream error;
+			error << "The methods read_csv and read_csv_auto do not have the \"" << parameter << "\" argument." << '\n';
+			error << "Possible arguments as suggestions: " << '\n';
+			vector<string> parameters(valid_parameters.begin(), valid_parameters.end());
+			auto suggestions = StringUtil::TopNJaroWinkler(parameters, parameter, 3);
+			for (auto &suggestion : suggestions) {
+				error << "* " << suggestion << '\n';
+			}
+			throw InvalidInputException(error.str());
+			throw InvalidInputException("read_csv and read_csv_auto does not have the %s option.");
```
Comment (Mytherin) [inline tools/pythonpkg/src/pyconnection.cpp:949]: This second exception is likely left here by accident

File: tools/pythonpkg/src/pyconnection.cpp [hunk 2]
```diff
@@ -896,7 +896,64 @@ static py::object GetValueOrNone(py::kwargs &kwargs, const string &key) {
 	return py::none();
 }
 
+void AcceptableCSVOptions(const py::kwargs &kwargs) {
+	// List of strings to match against
+	const unordered_set<string> valid_parameters = {"header",
```
Comment (Mytherin) [inline tools/pythonpkg/src/pyconnection.cpp:901]: Having this list of parameters effectively duplicated seems error-prone when we will (inevitably) add more parameters.

Could we perhaps rewrite the `ReadCSV` function below to iterate over the `kwargs`, e.g. something like:

```cpp
for(auto &arg : kwargs) {
   auto &arg_name = arg.first;
   if (arg_name == "header") {
        ...
   } else if (arg_name == "compression") {
        ...
   } else {
        throw Exception("Unrecognized parameter X");
   }
}
```

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Looks good - some comments:

**Comment by Mytherin** [comment]
Thanks!
