### PR TITLE
Label mark joins with convert to semi

### LINKED ISSUE #11042: INTERNAL Error: Failed to bind column reference "xx" [21.0] (bindings: [0.0 0.1 1.0])
### What happens?

 INTERNAL Error: Failed to bind column reference "parentExists" [21.0] (bindings: [0.0 0.1 1.0])

### To Reproduce

```sql
CREATE OR REPLACE TABLE BaseData AS (
    SELECT
      '10' AS my_key,
      '20' AS parent_key,
      '30' AS payload
)
;

WITH
Example AS (
    SELECT
        c.my_key,
        (c.parent_key IN (SELECT my_key FROM BaseData)) AS parentExists,
        p.my_key IS NOT NULL AS parentExists2,
    FROM BaseData AS c
    LEFT JOIN BaseData AS p ON c.parent_key = p.my_key
)
SELECT *
FROM Example
WHERE parentExists -- fails
-- WHERE parentExists2 -- works
;
```

### OS:

macOS 14.3.1

### DuckDB Version:

0.10.0

### DuckDB Client:

Python

### Full Name:

Rob Jackson

### Affiliation:

Exaforce

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by Tmonster**
Continuation of https://github.com/duckdb/duckdb/pull/12828/files
closes https://github.com/duckdb/duckdb/issues/11042

The discussion on PR 12828, led to making a new optimizer to prevent mark to semi join conversions.  Although the chance is very small, I was worried people could turn off the NO_MARK_TO_SEMI_OPTIMIZER but not the filter pushdown optimizer. This would mean the bug could persist if another optimizer was added to fix this. 

Now in optimizer.cpp, once the filter pushdown object is created, `filter_pushdown.CheckMarkToSemi(*plan, top_bindings);` is called. This is only needs to be called at the root of the plan, keeping the code clean and avoiding extra tree traversals.

### CODE REVIEW

File: src/optimizer/filter_pushdown.cpp [hunk 1]
```diff
@@ -1,15 +1,68 @@
...
+		auto plan_bindings = op.GetColumnBindings();
+		auto &proj = op.Cast<LogicalProjection>();
+		auto proj_bindings = proj.GetColumnBindings();
+		unordered_set<idx_t> new_table_bindings;
+		for (auto &binding : proj_bindings) {
+			auto col_index = binding.column_index;
+			auto &expr = proj.expressions.at(col_index);
+			vector<ColumnBinding> bindings_to_keep;
+			ExpressionIterator::EnumerateExpression(expr, [&](Expression &child) {
+				if (expr->expression_class == ExpressionClass::BOUND_COLUMN_REF) {
```
Comment (lnkuiper) [inline src/optimizer/filter_pushdown.cpp:44]: How does this work if the top-level expression is not a column ref, but it refers to one or more column refs?

For example:
```
SELECT col0 AND col1 FROM (...);
```
The mark join colref boolean can be used in the remainder of the plan like so

**Review by lnkuiper — COMMENTED** [review]
Thanks for the PR! I have one comment:

File: src/optimizer/filter_pushdown.cpp (hunk 1 above)
Comment (Tmonster) [reply src/optimizer/filter_pushdown.cpp:44]: EnumerateExpression should also enumerate into the children, so the mark join colref should still be picked up here

Comment (lnkuiper) [reply src/optimizer/filter_pushdown.cpp:44]: Ah, I see. I was worried that referring to columns multiple times would mess things up in queries like this:
```sql
SELECT col0, col0 AND col1 FROM (...);
```
but they are deduplicated by the `unordered_set`, so that should be fine

**Review by lnkuiper — APPROVED** [review]
This is good to go from my side

File: src/optimizer/filter_pushdown.cpp (hunk 1 above)
Comment (Mytherin) [reply src/optimizer/filter_pushdown.cpp:44]: Can we perhaps in a follow-up PR rename `EnumerateExpression` to `EnumerateAllExpressions`? The difference between `EnumerateExpression` and `EnumerateChildren` is otherwise easy to miss when reading.

**Comment by Mytherin** [comment]
Thanks!
