### PR TITLE
Make sure that empty and only white space headers have same treatment

### LINKED ISSUE #12977: CSV parsing gives different name format for empty vs. whitespace header
### What happens?

When parsing a CSV, a header row with an empty column will turn into `column{i}`
For instance, `a,b,c,,e` becomes `a,b,c,column3,e` 

But if the header row has a column that is just whitespace, that empty column will turn into `C{i}`
For instance, `a,b,c,  ,e` becomes `a,b,c,C3,e`

These names should probably be consistent.

Note: I'm using duckdb-wasm, but I don't believe this is a WASM specific problem. If that is the case this can be moved to that repo.

### To Reproduce

1. Create two CSVs (or just change the header in one csv) with the above differences in the first row.
2. Load both into DuckDB. I'm using the WASM bindings but I believe it still happens with other CSV parsing methods.
3. Observe the difference in column names

### OS:

macOS 

### DuckDB Version:

1.0.0

### DuckDB Client:

WASM (version 1.28.1-dev106.0)

### Full Name:

Robert Lesser

### Affiliation:

Nomic AI

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [ ] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [ ] Yes, I have

### PR DESCRIPTION
**Pull request by pdet**
Fix: #12977

### CODE REVIEW

File: src/execution/operator/csv_scanner/sniffer/header_detection.cpp [hunk 1]
```diff
@@ -149,6 +148,24 @@ bool CSVSniffer::DetectHeaderWithSetColumn(ClientContext &context, vector<Header
...
+	if (col_name.empty() || is_null) {
+		return true;
+	}
+	if (normalize) {
+		// normalize has special logic to trim white spaces and generate names
+		return false;
+	}
+	// check if it's all white spaces
+	for (auto &c : col_name) {
+		if (c != ' ') {
```
Comment (Mytherin) [inline src/execution/operator/csv_scanner/sniffer/header_detection.cpp:161]: Can we use `StringUtil::CharacterIsSpace` here so that we also capture other types of spaces (e.g. tabs)?

**Review by Mytherin — COMMENTED** [review]
Thanks! LGTM - one minor comment

**Comment by Mytherin** [comment]
Thanks!
