### PR TITLE
fix statistics propagation for anti-joins on empty tables

### LINKED ISSUE #17417: A wrong anti-join result when joining with an empty table
### What happens?

Dear DuckDB developers,
I meet unexpected result of two equivalent anti-join queries, and I will appreciate it if you can review it.

Additionally, if t2 is not a empty table, this bug can not be triggered.

```sql
CREATE TABLE t0(c0 INT);
CREATE TABLE t2(c0 INT);
INSERT INTO t0(c0) VALUES (5);

SELECT * FROM t0 WHERE NOT EXISTS (select 1 FROM t2 WHERE ((t2.c0)>=(t0.c0)));
-- 5

SELECT * FROM t0 ANTI JOIN t2 ON ((t2.c0)>=(t0.c0));
-- empty
-- wrong result, should be 5

-- Query Plan of Q2 is almost nothing.
┌─────────────────────────────┐
│┌───────────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐
│        EMPTY_RESULT       │
└───────────────────────────┘


```

### To Reproduce

```sql
CREATE TABLE t0(c0 INT);
CREATE TABLE t2(c0 INT);
INSERT INTO t0(c0) VALUES (5);

SELECT * FROM t0 WHERE NOT EXISTS (select 1 FROM t2 WHERE ((t2.c0)>=(t0.c0)));
-- 5

SELECT * FROM t0 ANTI JOIN t2 ON ((t2.c0)>=(t0.c0));
-- empty
-- wrong result, should be 5

Query Plan of Q2 is almost nothing.
┌─────────────────────────────┐
│┌───────────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐
│        EMPTY_RESULT       │
└───────────────────────────┘


```

### OS:

MacOS

### DuckDB Version:

v1.3.0-dev3259 e0e4cc2cc8

### DuckDB Client:

CLI

### Hardware:

_No response_

### Full Name:

TheoristCoder

### Affiliation:

NUS

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [x] Yes, I have

### PR DESCRIPTION
**Pull request by bradynwalsh**
Closes #17417 

This issue appears to actually be a regression of issue #9308 (with the existing test for that issue not picking up the regression as the optimizer no longer makes an explicit ANTI-JOIN for the WHERE NOT EXISTS query).

While the fix in #9654 could be re-applied (and if this PR is deemed not suitable, should be) to remove the pruning optimization altogether for ANTI-JOINS with always true filters, this PR aims to keep the optimization and handle the case where the join is on an empty result set.

In particular, this PR adds a helper function to BaseStatistics to determine whether the stats match an empty result set (using the min/max set by CreateEmpty) and correctly returns the LHS of the ANTI-JOIN if the RHS is empty (and keeps the current behaviour of returning an empty result otherwise)

While this function is only currently used for NumericStats, I've also implemented it for the other BaseStatistics implementations, to avoid this being regressed again in future if statistics propagation (and in particular, filter pruning) occur for non-numeric types.

### CODE REVIEW

File: src/optimizer/statistics/operator/propagate_join.cpp [hunk 1]
```diff
@@ -119,7 +119,17 @@ void StatisticsPropagator::PropagateStatistics(LogicalComparisonJoin &join, uniq
 					}
 					case JoinType::ANTI:
 					case JoinType::RIGHT_ANTI: {
-						ReplaceWithEmptyResult(node_ptr);
+						// If filter always true and RHS (LHS in RIGHT_ANTI) not empty, return empty result
+						// If RHS (LHS in RIGHT_ANTI) is empty, return LHS (RHS in RIGHT_ANTI)
+						//
+						// A node is only considered empty if the stats for it are from BaseStatistics::CreateEmpty
+						if (join.join_type == JoinType::ANTI && stats_right->IsEmpty()) {
```
Comment (Damon07) [inline src/optimizer/statistics/operator/propagate_join.cpp:126]: It seems PropagateComparison produces an incorrect pruning result for empty table statistics. Perhaps the fix should be within PropagateComparison itself.

Comment (Tmonster) [reply src/optimizer/statistics/operator/propagate_join.cpp:126]: I agree with @Damon07, Looking into the propagate comparison code, it seems like the `has_min` and `has_max` attributes of `NumericStats` are incorrectly getting set to True for `rstats` (the empty right table)

I don't think adding an `IsEmpty` is necessary here

**Comment by coracuity** [comment]
also chiming in with enthusiasm for this being merged, and thanks to the dev who fixed it!!

**Review by Tmonster — APPROVED** [review]
Looks good to me. I think you can change the base branch to v1.3-Ossivalis so that this gets merged into the next bug fix release

**Comment by bradynwalsh** [comment]
Thanks for the review, changed the base branch to v1.3-Ossivalis!

**Comment by krlmlr** [comment]
@Mytherin: Is this likely to make it into 1.3.2? I want to run revdepchecks for the R package, and this (and #17530, but not ready for review) seem to be the only affected open PRs.

**Comment by Mytherin** [comment]
Thanks!
