### PR TITLE
Fix incorrect results with NOT EXISTS and IS DISTINCT FROM operator (#19680)

### LINKED ISSUE #19680: Unexpected Execution Result
### What happens?

Dear DuckDB Developers,
I have encountered an unexpected execution result and have prepared a reproducible case, which I’ve included below. I would greatly appreciate it if you could take a moment to review it.
```sql
CREATE  TABLE  t0(c2 INT);

INSERT INTO t0(c2) VALUES (NULL);
INSERT INTO t0(c2) VALUES (1);


SELECT t0.c2 FROM t0 WHERE NOT EXISTS (SELECT 1 FROM (SELECT t0.c2 AS col0 FROM t0) AS subQuery WHERE ((t0.c2)IS DISTINCT FROM(subQuery.col0)));
-- Wrong Execution Result: 
-- NULL
-- 1

-- Expected Result: Empty result
```

### To Reproduce

```sql
CREATE  TABLE  t0(c2 INT);

INSERT INTO t0(c2) VALUES (NULL);
INSERT INTO t0(c2) VALUES (1);


SELECT t0.c2 FROM t0 WHERE NOT EXISTS (SELECT 1 FROM (SELECT t0.c2 AS col0 FROM t0) AS subQuery WHERE ((t0.c2)IS DISTINCT FROM(subQuery.col0)));
-- Wrong Execution Result: 
-- NULL
-- 1

-- Expected Result: Empty result
```

### OS:

MacOS

### DuckDB Version:

DuckDB v1.5.0-dev2154 (Development Version, 963000678a)

### DuckDB Client:

CLI

### Hardware:

_No response_

### Full Name:

TheoristCoder

### Affiliation:

Personal Project(Will disclose after paper review)

### Did you include all relevant configuration (e.g., CPU architecture, Linux distribution) to reproduce the issue?

- [x] Yes, I have

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant data sets for reproducing the issue?

Yes

### PR DESCRIPTION
**Pull request by henry8128**
Fixes #19680

This fixes a bug where queries using `NOT EXISTS` with `IS DISTINCT FROM` returned incorrect results due to improper handling of NULL semantics in the optimizer.

The issue was that the optimizer's deliminator incorrectly treated `DISTINCT FROM` variants the same as regular equality/inequality comparisons, which have different NULL handling:
  - `IS DISTINCT FROM`: NULL-aware (NULL IS DISTINCT FROM NULL = FALSE)
  - != or =: NULL-unaware (NULL != NULL = NULL, filters out NULLs)

### Incorrect Query Plan

```
┌───────────────────────────┐
│         PROJECTION        │
│    ────────────────────   │
│             c2            │
│                           │
│          ~0 rows          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         PROJECTION        │
│    ────────────────────   │
│             #5            │
│__internal_decompress_integ│
│     ral_integer(#3, 1)    │
│             #1            │
│                           │
│          ~0 rows          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│      NESTED_LOOP_JOIN     │
│    ────────────────────   │
│      Join Type: ANTI      │
│    Conditions: c2 != c2   ├──────────────┐
│                           │              │
│          ~0 rows          │              │
└─────────────┬─────────────┘              │
┌─────────────┴─────────────┐┌─────────────┴─────────────┐
│         PROJECTION        ││         PROJECTION        │
│    ────────────────────   ││    ────────────────────   │
│            NULL           ││            NULL           │
│             #2            ││             #2            │
│            NULL           ││            NULL           │
│             #1            ││             #1            │
│            NULL           ││            NULL           │
│             #0            ││             #0            │
│            NULL           ││            NULL           │
│                           ││                           │
│          ~2 rows          ││           ~1 row          │
└─────────────┬─────────────┘└─────────────┬─────────────┘
┌─────────────┴─────────────┐┌─────────────┴─────────────┐
│         PROJECTION        ││         PROJECTION        │
│    ────────────────────   ││    ────────────────────   │
│             #0            ││             #0            │
│__internal_compress_integra││__internal_compress_integra│
│     l_utinyint(#1, 1)     ││     l_utinyint(#1, 1)     │
│             #2            ││             #2            │
│                           ││                           │
│          ~2 rows          ││           ~1 row          │
└─────────────┬─────────────┘└─────────────┬─────────────┘
┌─────────────┴─────────────┐┌─────────────┴─────────────┐
│         PROJECTION        ││         PROJECTION        │
│    ────────────────────   ││    ────────────────────   │
│            NULL           ││            NULL           │
│             #0            ││             #0            │
│            NULL           ││            NULL           │
│                           ││                           │
│          ~2 rows          ││           ~1 row          │
└─────────────┬─────────────┘└─────────────┬─────────────┘
┌─────────────┴─────────────┐┌─────────────┴─────────────┐
│         SEQ_SCAN          ││           FILTER          │
│    ────────────────────   ││    ────────────────────   │
│         Table: t0         ││     (col0 IS NOT NULL)    │
│   Type: Sequential Scan   ││                           │
│      Projections: c2      ││                           │
│                           ││                           │
│          ~2 rows          ││           ~1 row          │
└───────────────────────────┘└─────────────┬─────────────┘
                             ┌─────────────┴─────────────┐
                             │         SEQ_SCAN          │
                             │    ────────────────────   │
                             │         Table: t0         │
                             │   Type: Sequential Scan   │
                             │      Projections: c2      │
                             │                           │
                             │          ~2 rows          │
                             └───────────────────────────┘
```

  The buggy plan shows two critical issues:
```
  ┌─────────────┴─────────────┐
  │      NESTED_LOOP_JOIN     │
  │      Join Type: ANTI      │
  │    Conditions: c2 != c2   │  ← ❌ Wrong(the join conditions should be c2 IS DISTINCT FROM c2)
  │          ~0 rows          │
  └─────────────┬─────────────┘
                │
                └─────────────┐
                             ┌┴─────────────┐
                             │   FILTER     │
                             │ (col0 IS NOT │  ← ❌ Wrong(the filter should be removed)
                             │    NULL)     │
                             └──────────────┘
```

### Solution

This PR adds proper support for DISTINCT FROM operators throughout the optimization pipeline:

1. Preserve DISTINCT FROM semantics in join conversion.(src/optimizer/deliminator.cpp)
```
// NOTE: We should NOT convert DISTINCT FROM to != in general
// Only convert if the ORIGINAL join had != or = (not DISTINCT FROM variants)
if (delim_join.join_type != JoinType::MARK &&
    original_join_comparison != ExpressionType::COMPARE_DISTINCT_FROM &&
    original_join_comparison != ExpressionType::COMPARE_NOT_DISTINCT_FROM) {
    // Safe to convert
}
```
2. Skip NULL filters for DISTINCT FROM variants.(src/optimizer/deliminator.cpp)
```
// Only add IS NOT NULL filter for regular equality/inequality comparisons
// Do NOT add for DISTINCT FROM variants, as they handle NULL correctly
if (cond.comparison != ExpressionType::COMPARE_NOT_DISTINCT_FROM &&
    cond.comparison != ExpressionType::COMPARE_DISTINCT_FROM) {
    // Add IS NOT NULL filter
}
```
3. Added negation support for COMPARE_DISTINCT_FROM and COMPARE_NOT_DISTINCT_FROM
    in expression type handling.(src/common/enums/expression_type.cpp)
4. Updated parser to properly negate IS DISTINCT FROM expressions when wrapped with NOT. (src/parser/transform/expression/transform_bool_expr.cpp)
5. Added regression test in test/sql/subquery/exists/test_correlated_exists_with_derived_table.test

### CODE REVIEW

File: src/optimizer/deliminator.cpp [hunk 1]
```diff
@@ -352,7 +356,13 @@ bool Deliminator::RemoveInequalityJoinWithDelimGet(LogicalComparisonJoin &delim_
 				// join condition was a not equal and filtered out all NULLS.
 				// DELIM JOIN need to do that for not DELIM_GET side. Easiest way is to change the
 				// comparison expression type. See duckdb/duckdb#16803
-				if (delim_join.join_type != JoinType::MARK) {
+				// NOTE: We should NOT convert DISTINCT FROM to != in general, as they have different NULL semantics
```
Comment (Tmonster) [inline src/optimizer/deliminator.cpp]: nit: While this is true, I don't think these comments provide much value here, as there is a specific case where we do want to change it. See https://github.com/duckdb/duckdb/pull/16910 which has almost the same query, expect the original join is a `!=` and not a `compare distinct from`

File: src/optimizer/deliminator.cpp [hunk 2]
```diff
@@ -352,7 +356,13 @@ bool Deliminator::RemoveInequalityJoinWithDelimGet(LogicalComparisonJoin &delim_
...
+				// - DISTINCT FROM: NULL IS DISTINCT FROM NULL = FALSE (NULL-aware)
+				// - !=: NULL != NULL = NULL (filters out NULL)
+				// Only convert if the ORIGINAL join had != or = (not DISTINCT FROM variants)
```
Comment (Tmonster) [inline src/optimizer/deliminator.cpp:359]: 🙏 nice, this is a case I missed.

**Review by Tmonster — APPROVED** [review]
Thanks for the PR! Was a tricky one to understand, but I finally understood it. 
Just one small nit on the comments, otherwise LGTM.

File: src/optimizer/deliminator.cpp (hunk 1 above)
Comment (henry8128) [reply src/optimizer/deliminator.cpp]: good point!

**Comment by henry8128** [comment]
@Tmonster Thanks a lot for your review. I have updated the PR as you suggested. 

Best, Henry

**Review by Tmonster — APPROVED** [review]
LGTM. Thank you again!
