### PR TITLE
Map bug combo of const & non-const lists

### LINKED ISSUE #6259: `json_extract` exploding when inside `map`
### What happens?

When reading from JSON (file or column of `json` type), if you do a select with a map, and the map key or value is populated using `json_extract_string`, the `map` fails with `Error: Invalid Input Error: Error in MAP creation: key list has a different size from value list (1 keys, 2 values)`

### To Reproduce

`example.json`

```json
{"name":"donald", "is_duck": true}
{"name":"cole", "is_duck": false, "extra": "hello, cole"}
```

Open DuckDB

```sql
select map(['name'], [json_extract_string(json, '$.name')]) from read_ndjson_objects('./example.json');
-- Error: Invalid Input Error: Error in MAP creation: key list has a different size from value list (1 keys, 2 values)
```

### OS:

macOS x64

### DuckDB Version:

0.7.0

### DuckDB Client:

cli

### Full Name:

Cole MacKenzie

### Affiliation:

Cloudflare

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by LindsayWray**
Addresses issue #6259

This issue exposed an error when map is created with both a constant and a columnar list and required some refactoring of the map function to accommodate this. 

Plus a fix when both lists contain an equal total amount of keys and values, but are actually not aligned on each row.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR! @Tishj could you perhaps have a look at it?

File: src/function/scalar/map/map.cpp [hunk 1]
```diff
@@ -66,46 +66,91 @@ void MapConversionVerify(Vector &vector, idx_t count) {
...
 	auto value_count = ListVector::GetListSize(args.data[1]);
-	if (key_count != value_count) {
-		throw InvalidInputException(
-		    "Error in MAP creation: key list has a different size from value list (%lld keys, %lld values)", key_count,
-		    value_count);
+	auto key_data = ListVector::GetData(args.data[0]);
+	auto value_data = ListVector::GetData(args.data[1]);
+	auto src_data = key_data;
+
+	if (keys_are_const && !values_are_const) {
```
Comment (Tishj) [inline src/function/scalar/map/map.cpp:111]: I think we can combine this `if` body and the `else if` body in one function.
It only really needs `args.data[0]` and `args.data[1]`

You can probably leave the `src_data = ..` out of this function though

File: src/function/scalar/map/map.cpp [hunk 2]
```diff
@@ -66,46 +66,91 @@ void MapConversionVerify(Vector &vector, idx_t count) {
...
 
+	ListVector::SetListSize(result, MaxValue(key_count, value_count));
+
+	result_data = ListVector::GetData(result);
 	for (idx_t i = 0; i < args.size(); i++) {
-		list_data[i] = args_data[i];
+		result_data[i] = src_data[i];
+	}
+
+	if (!(keys_are_const && !values_are_const)) {
```
Comment (Tishj) [inline src/function/scalar/map/map.cpp:147]: Could you add additional comments explaining this section?
And possibly make the condition easier to read? I have to admit I don't know what this condition logically is

File: src/function/scalar/map/map.cpp [hunk 3]
```diff
@@ -66,46 +66,91 @@ void MapConversionVerify(Vector &vector, idx_t count) {
...
 
-static void MapFunction(DataChunk &args, ExpressionState &state, Vector &result) {
-	D_ASSERT(result.GetType().id() == LogicalTypeId::MAP);
-
-	//! Otherwise if its not a constant vector, this breaks the optimizer
-	result.SetVectorType(VectorType::CONSTANT_VECTOR);
-	for (idx_t i = 0; i < args.ColumnCount(); i++) {
-		if (args.data[i].GetVectorType() != VectorType::CONSTANT_VECTOR) {
-			result.SetVectorType(VectorType::FLAT_VECTOR);
+static void ExpandVector(const Vector &source, Vector &target, idx_t expansion_factor) {
```
Comment (Tishj) [inline src/function/scalar/map/map.cpp:69]: Nit: can we add a comment somewhere showcasing what it does?
for example:
```
// source: [1,2,3], expansion_factor: 4
// target (result): [1,2,3,1,2,3,1,2,3,1,2,3]
```

**Review by Tishj — COMMENTED** [review]
Looks good to me, just had a few comments about some minor things :)

File: src/function/scalar/map/map.cpp (hunk 1 above)
Comment (LindsayWray) [reply src/function/scalar/map/map.cpp:111]: I’ve also tried this to do this, because they seem very similar but there are more differences than just args.data[x], namely the size of the vector to allocate,  key_count / value_count vs  value_count / key_count and key_vector.Reference vs value_vector.Reference.

Comment (Tishj) [reply src/function/scalar/map/map.cpp:114]: Sorry, I was pretty sure it could be done, and I kind of went "challenge accepted", I hope you don't mind
```c++
static void AlignVectorToReference(const Vector &original, const Vector &reference, idx_t tuple_count, Vector &result) {
	auto original_length = ListVector::GetListSize(original);
	auto new_length = ListVector::GetListSize(reference);

	Vector expanded_const(ListType::GetChildType(original.GetType()), new_length);

	auto expansion_factor = new_length / original_length;
	if (expansion_factor != tuple_count) {
		throw InvalidInputException("Error in MAP creation: key list and value list do not align. i.e. different "
									"size or incompatible structure");
	}
	ExpandVector(original, expanded_const, expansion_factor);
	result.Reference(expanded_const);
}
```
```c++
	if (keys_are_const && !values_are_const) {
		AlignVectorToReference(args.data[0], args.data[1], args.size(), key_vector);
		src_data = value_data;
	} else if (values_are_const && !keys_are_const) {
		AlignVectorToReference(args.data[1], args.data[0], args.size(), value_vector);
```

Comment (LindsayWray) [reply src/function/scalar/map/map.cpp:129]: Damn, that looks good! I've implemented it!

**Comment by Mytherin** [comment]
Thanks for the fixes! It looks like there is still an issue in one of the tests - could you have a look?

```
Wrong result in query! (test/sql/types/list/const_struct_null_bug.test_slow:9)!
================================================================================
SELECT hits_0.access.page."pageTitle" as "pageTitle",
COUNT(DISTINCT CONCAT(ga_sessions."__distinct_key", 'x', hits_0.__row_id)) as "hits_count",
COUNT(DISTINCT CASE WHEN product_0.access."productQuantity">0 THEN CONCAT(ga_sessions."__distinct_key", 'x', hits_0."__row_id") END) as "sold_count"
FROM (SELECT GEN_RANDOM_UUID() as __distinct_key, * FROM 'data/parquet-testing/issue_6013.parquet' as x) as ga_sessions,
(SELECT GEN_RANDOM_UUID() as __row_id, x.access FROM (SELECT UNNEST(ga_sessions.hits)) as x(access)) as hits_0,
(SELECT GEN_RANDOM_UUID() as __row_id, x.access FROM (SELECT UNNEST(hits_0.access.product)) as x(access)) as product_GROUP BY 1 LIMIT 2;
================================================================================
Mismatch on row 2, column Android | Shop by Brand | Google Merchandise Store <> Men's Outerwear | Apparel | Google Merchandise Store
================================================================================
Expected result:
================================================================================
Electronics | Google Merchandise Store	15	Men's Outerwear | Apparel | Google Merchandise Store	6	================================================================================
Actual result:
================================================================================
Electronics | Google Merchandise Store	15	Android | Shop by Brand | Google Merchandise Store	2	[1511/2625] (57%): test/sql/types/list/const_struct_null_bug.test_slow          
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
unittest is a Catch v2.13.7 host application.
Run with -? for options


```

**Comment by LindsayWray** [comment]
> Thanks for the fixes! It looks like there is still an issue in one of the tests - could you have a look?
> 
> ```
> Wrong result in query! (test/sql/types/list/const_struct_null_bug.test_slow:9)!
> ================================================================================
> SELECT hits_0.access.page."pageTitle" as "pageTitle",
> COUNT(DISTINCT CONCAT(ga_sessions."__distinct_key", 'x', hits_0.__row_id)) as "hits_count",
> COUNT(DISTINCT CASE WHEN product_0.access."productQuantity">0 THEN CONCAT(ga_sessions."__distinct_key", 'x', hits_0."__row_id") END) as "sold_count"
> FROM (SELECT GEN_RANDOM_UUID() as __distinct_key, * FROM 'data/parquet-testing/issue_6013.parquet' as x) as ga_sessions,
> (SELECT GEN_RANDOM_UUID() as __row_id, x.access FROM (SELECT UNNEST(ga_sessions.hits)) as x(access)) as hits_0,
> (SELECT GEN_RANDOM_UUID() as __row_id, x.access FROM (SELECT UNNEST(hits_0.access.product)) as x(access)) as product_GROUP BY 1 LIMIT 2;
> ================================================================================
> Mismatch on row 2, column Android | Shop by Brand | Google Merchandise Store <> Men's Outerwear | Apparel | Google Merchandise Store
> ================================================================================
> Expected result:
> ================================================================================
> Electronics | Google Merchandise Store	15	Men's Outerwear | Apparel | Google Merchandise Store	6	================================================================================
> Actual result:
> ================================================================================
> Electronics | Google Merchandise Store	15	Android | Shop by Brand | Google Merchandise Store	2	[1511/2625] (57%): test/sql/types/list/const_struct_null_bug.test_slow          
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> unittest is a Catch v2.13.7 host application.
> Run with -? for options
> ```

Would you mind triggering this ci test again? I can't reproduce it, it didn't fail before the last refactor commit and it seems strange to me that this test would pass through mapfunction

**Comment by Mytherin** [comment]
I think you are right - it seems to be a problem in the test itself. It looks like the test has a `GROUP BY LIMIT` but no `ORDER BY` so the result is underspecified, causing this to randomly fail. I have restarted the CI.
