### PR TITLE
[Nested] Fix incorrect type casting in list_reduce lambda expressions

### LINKED ISSUE #17008: Internal error with new list_reduce
### What happens?

```sql
select 
    list_reduce([0], (x, y) -> x > 3, 3.1)
```
```
INTERNAL Error: Vector::Reference used on vector of different type

Stack Trace:

[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb9Exception6ToJSONENS_13ExceptionTypeERKSs+0x53) [0x7f6c462593f3]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb9ExceptionC1ENS_13ExceptionTypeERKSs+0x16) [0x7f6c46259426]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb17InternalExceptionC1ERKSs+0x11) [0x7f6c4625bab1]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(+0x943333) [0x7f6c453f2333]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb18ExpressionExecutor7ExecuteERKNS_10ExpressionEPNS_15ExpressionStateEPKNS_15SelectionVectorEmRNS_6VectorE+0x1ff) [0x7f6c4645425f]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb18ExpressionExecutor7ExecuteERKNS_25BoundComparisonExpressionEPNS_15ExpressionStateEPKNS_15SelectionVectorEmRNS_6VectorE+0x9a) [0x7f6c464757ea]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb18ExpressionExecutor7ExecuteERKNS_10ExpressionEPNS_15ExpressionStateEPKNS_15SelectionVectorEmRNS_6VectorE+0x10f) [0x7f6c4645416f]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb18ExpressionExecutor7ExecuteERKNS_19BoundCastExpressionEPNS_15ExpressionStateEPKNS_15SelectionVectorEmRNS_6VectorE+0x76) [0x7f6c46475646]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb18ExpressionExecutor7ExecuteERKNS_10ExpressionEPNS_15ExpressionStateEPKNS_15SelectionVectorEmRNS_6VectorE+0xe7) [0x7f6c46454147]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb18ExpressionExecutor7ExecuteEPNS_9DataChunkERS1_+0x6d) [0x7f6c4645e02d]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb15LambdaFunctions18ListReduceFunctionERNS_9DataChunkERNS_15ExpressionStateERNS_6VectorE+0xf7c) [0x7f6c45ebf19c]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb18ExpressionExecutor7ExecuteERKNS_10ExpressionEPNS_15ExpressionStateEPKNS_15SelectionVectorEmRNS_6VectorE+0x187) [0x7f6c464541e7]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb18ExpressionExecutor14EvaluateScalarERNS_13ClientContextERKNS_10ExpressionEb+0x65) [0x7f6c46458ce5]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb18ExpressionExecutor17TryEvaluateScalarERNS_13ClientContextERKNS_10ExpressionERNS_5ValueE+0x1d) [0x7f6c46458f1d]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb19ConstantFoldingRule5ApplyERNS_15LogicalOperatorERNS_6vectorISt17reference_wrapperINS_10ExpressionEELb1EEERbb+0x66) [0x7f6c46c5d7a6]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb18ExpressionRewriter10ApplyRulesERNS_15LogicalOperatorERKNS_6vectorISt17reference_wrapperINS_4RuleEELb1EEENS_10unique_ptrINS_10ExpressionESt14default_deleteISB_ELb1EEERbb+0x188) [0x7f6c46c00f88]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb18ExpressionRewriter15VisitExpressionEPNS_10unique_ptrINS_10ExpressionESt14default_deleteIS2_ELb1EEE+0x5a) [0x7f6c46c011aa]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb22LogicalOperatorVisitor20EnumerateExpressionsERNS_15LogicalOperatorERKSt8functionIFvPNS_10unique_ptrINS_10ExpressionESt14default_deleteIS5_ELb1EEEEE+0x98) [0x7f6c46d149b8]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb22LogicalOperatorVisitor24VisitOperatorExpressionsERNS_15LogicalOperatorE+0x3d) [0x7f6c46d14d9d]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb18ExpressionRewriter13VisitOperatorERNS_15LogicalOperatorE+0x82) [0x7f6c46c03952]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb22LogicalOperatorVisitor21VisitOperatorChildrenERNS_15LogicalOperatorE+0x72) [0x7f6c46d22bd2]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb18ExpressionRewriter13VisitOperatorERNS_15LogicalOperatorE+0x19) [0x7f6c46c038e9]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb9Optimizer12RunOptimizerENS_13OptimizerTypeERKSt8functionIFvvEE+0x5b) [0x7f6c46c0007b]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb9Optimizer20RunBuiltInOptimizersEv+0x83) [0x7f6c46c00133]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb9Optimizer8OptimizeENS_10unique_ptrINS_15LogicalOperatorESt14default_deleteIS2_ELb1EEE+0xe9) [0x7f6c46c00b39]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb13ClientContext31CreatePreparedStatementInternalERNS_17ClientContextLockERKSsNS_10unique_ptrINS_12SQLStatementESt14default_deleteIS6_ELb1EEENS_12optional_ptrISt13unordered_mapISsNS_18BoundParameterDataENS_33CaseInsensitiveStringHashFunctionENS_29CaseInsensitiveStringEqualityESaISt4pairIS3_SC_EEELb1EEE+0x6d4) [0x7f6c46b08a54]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb13ClientContext23CreatePreparedStatementERNS_17ClientContextLockERKSsNS_10unique_ptrINS_12SQLStatementESt14default_deleteIS6_ELb1EEENS_12optional_ptrISt13unordered_mapISsNS_18BoundParameterDataENS_33CaseInsensitiveStringHashFunctionENS_29CaseInsensitiveStringEqualityESaISt4pairIS3_SC_EEELb1EEENS_21PreparedStatementModeE+0x2dd) [0x7f6c46b094fd]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb13ClientContext24PendingStatementInternalERNS_17ClientContextLockERKSsNS_10unique_ptrINS_12SQLStatementESt14default_deleteIS6_ELb1EEERKNS_22PendingQueryParametersE+0x96) [0x7f6c46b15886]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb13ClientContext35PendingStatementOrPreparedStatementERNS_17ClientContextLockERKSsNS_10unique_ptrINS_12SQLStatementESt14default_deleteIS6_ELb1EEERNS_10shared_ptrINS_21PreparedStatementDataELb1EEERKNS_22PendingQueryParametersE+0xd7) [0x7f6c46b1c8d7]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb13ClientContext43PendingStatementOrPreparedStatementInternalERNS_17ClientContextLockERKSsNS_10unique_ptrINS_12SQLStatementESt14default_deleteIS6_ELb1EEERNS_10shared_ptrINS_21PreparedStatementDataELb1EEERKNS_22PendingQueryParametersE+0x10b) [0x7f6c46b1d9ab]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb13ClientContext20PendingQueryInternalERNS_17ClientContextLockENS_10unique_ptrINS_12SQLStatementESt14default_deleteIS4_ELb1EEERKNS_22PendingQueryParametersEb+0x96) [0x7f6c46b1cb26]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb13ClientContext20PendingQueryInternalERNS_17ClientContextLockERKNS_10shared_ptrINS_8RelationELb1EEEb+0x153) [0x7f6c46b22063]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb13ClientContext12PendingQueryERKNS_10shared_ptrINS_8RelationELb1EEEb+0x44) [0x7f6c46b22274]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(+0x25b89f6) [0x7f6c470679f6]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb16DuckDBPyRelation15ExecuteInternalEb+0x15) [0x7f6c47067ad5]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb16DuckDBPyRelation16ToStringInternalERKNS_17BoxRendererConfigEb+0x20a) [0x7f6c4706aa7a]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(_ZN6duckdb16DuckDBPyRelation8ToStringEv+0x181) [0x7f6c4706ad81]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(+0x25db784) [0x7f6c4708a784]
[/home/soeren/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/jlab/lib/python3.12/site-packages/duckdb/duckdb.cpython-312-x86_64-linux-gnu.so)(+0x24fbf03) [0x7f6c46faaf03]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)() [0x60ec9d]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)(_PyObject_MakeTpCall+0x181) [0x6599c1]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)() [0x65a3aa]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)() [0x583088]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)() [0x5f20fa]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)() [0x730f88]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)() [0x5b7970]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)(_PyEval_EvalFrameDefault+0xcff) [0x5a94bf]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)(_PyFunction_Vectorcall+0x25e) [0x658afe]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)(_PyObject_FastCallDictTstate+0x59) [0x65ca99]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)(_PyObject_Call_Prepend+0x5a) [0x65cbea]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)() [0x73100d]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)(_PyObject_MakeTpCall+0x181) [0x6599c1]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)(_PyEval_EvalFrameDefault+0x720) [0x5a8ee0]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)(_PyFunction_Vectorcall+0x25e) [0x658afe]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)(_PyObject_FastCallDictTstate+0x59) [0x65ca99]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)(_PyObject_Call_Prepend+0x5a) [0x65cbea]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)() [0x73100d]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)(_PyObject_MakeTpCall+0x181) [0x6599c1]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)(PyObject_CallOneArg+0x88) [0x65c988]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)(_PyEval_EvalFrameDefault+0x7316) [0x5afad6]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)(PyEval_EvalCode+0x99) [0x70ffd9]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)() [0x7128ee]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)(_PyEval_EvalFrameDefault+0x3962) [0x5ac122]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)() [0x74ce61]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)() [0x74d03b]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)(_PyEval_EvalFrameDefault+0x3fa2) [0x5ac762]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)() [0x65a368]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)(_PyObject_Call+0xdf) [0x65968f]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)(_PyEval_EvalFrameDefault+0x5822) [0x5adfe2]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)() [0x74ce61]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)(PyIter_Send+0x28) [0x52a236]
[/usr/lib/python3.12/lib-dynload/_asyncio.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/usr/lib/python3.12/lib-dynload/_asyncio.cpython-312-x86_64-linux-gnu.so)(+0x7070) [0x7f6c75e07070]
[/usr/lib/python3.12/lib-dynload/_asyncio.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/usr/lib/python3.12/lib-dynload/_asyncio.cpython-312-x86_64-linux-gnu.so)(+0x77f4) [0x7f6c75e077f4]
[/usr/lib/python3.12/lib-dynload/_asyncio.cpython-312-x86_64-linux-gnu.so](http://localhost:8888/usr/lib/python3.12/lib-dynload/_asyncio.cpython-312-x86_64-linux-gnu.so)(+0x7936) [0x7f6c75e07936]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)() [0x60edf4]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)() [0x69f385]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)() [0x4ab22e]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)() [0x60ed4d]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)(_PyObject_Call+0x58) [0x659608]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)(_PyEval_EvalFrameDefault+0x5822) [0x5adfe2]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)(PyEval_EvalCode+0x99) [0x70ffd9]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)() [0x7128ee]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)() [0x60ed4d]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)(PyObject_Vectorcall+0x36) [0x65c9e6]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)(_PyEval_EvalFrameDefault+0x720) [0x5a8ee0]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)(_PyFunction_Vectorcall+0x25e) [0x658afe]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)(_PyObject_Call+0x58) [0x659608]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)() [0x6dce80]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)(Py_RunMain+0x3a1) [0x6de081]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)(Py_BytesMain+0x2d) [0x6de23d]
[/lib/x86_64-linux-gnu/libc.so.6](http://localhost:8888/lib/x86_64-linux-gnu/libc.so.6)(__libc_start_main+0xf3) [0x7f6c77530083]
[/home/soeren/jlab/bin/python3](http://localhost:8888/jlab/bin/python3)(_start+0x2e) [0x6875ae]

This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
For more information, see https://duckdb.org/docs/dev/internal_errors
```

### To Reproduce

.

### OS:

Linux

### DuckDB Version:

'1.3.0-dev1976'

### DuckDB Client:

Python

### Hardware:

AMD64

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [x] Yes, I have

### PR DESCRIPTION
**Pull request by maiadegraaf**
Fixes: https://github.com/duckdb/duckdb/issues/17008

This PR fixes an issue with type casting in lambda expressions used in the `list_reduce` function. 

For example, in the following query:
```sql
select list_reduce([0], (x, y) -> x > 3, 3.1)
```

The lambda expression was incorrectly bound as:
```sql
CAST((x > CAST(3 AS INTEGER)) AS DECIMAL(11,1))
```

Now proper type casting is implemented to match the max logical type of both the list child type and the initial value type:
```sql
CAST((x > CAST(3 AS DECIMAL(11,1))) AS DECIMAL(11,1))
```

### Test Cases
Added tests to verify the correct casting behaviour

### CODE REVIEW

File: extension/core_functions/lambda_functions.cpp [hunk 1]
```diff
@@ -244,28 +244,35 @@ unique_ptr<FunctionData> ListLambdaBindData::Deserialize(Deserializer &deseriali
...
-		return list_child_type;
-	case 1:
-		return LogicalType::BIGINT;
-	default:
-		throw BinderException("This lambda function only supports up to two lambda parameters!");
+LogicalType LambdaFunctions::DetermineListChildType(const vector<LogicalType> &function_child_types) {
+	// the first child is always the list
+	constexpr idx_t list_idx = 0;
+
+	LogicalType list_child_type = function_child_types[list_idx];
```
Comment (taniabogatsch) [inline extension/core_functions/lambda_functions.cpp:251]: `auto list_type = function_child_types[list_idx];`

File: extension/core_functions/lambda_functions.cpp [hunk 2]
```diff
@@ -244,28 +244,35 @@ unique_ptr<FunctionData> ListLambdaBindData::Deserialize(Deserializer &deseriali
...
+	if (list_child_type.id() != LogicalTypeId::SQLNULL &&
+	    list_child_type.id() != LogicalTypeId::UNKNOWN) {
+		if (list_child_type.id() == LogicalTypeId::ARRAY) {
+			list_child_type = ArrayType::GetChildType(list_child_type);
+		} else {
+			list_child_type = ListType::GetChildType(list_child_type);
```
Comment (taniabogatsch) [inline extension/core_functions/lambda_functions.cpp:257]: Just `return ArrayType::...` ... and `return ListType::...`.

File: extension/core_functions/lambda_functions.cpp [hunk 3]
```diff
@@ -244,28 +244,35 @@ unique_ptr<FunctionData> ListLambdaBindData::Deserialize(Deserializer &deseriali
...
-	switch (parameter_idx) {
-	case 0:
-		return list_child_type;
-	case 1:
-		return LogicalType::BIGINT;
-	default:
-		throw BinderException("This lambda function only supports up to two lambda parameters!");
+LogicalType LambdaFunctions::DetermineListChildType(const vector<LogicalType> &function_child_types) {
+	// the first child is always the list
+	constexpr idx_t list_idx = 0;
```
Comment (taniabogatsch) [inline extension/core_functions/lambda_functions.cpp:249]: Maybe for reusability we could pass this as a parameter?

File: extension/core_functions/lambda_functions.cpp [hunk 4]
```diff
@@ -244,28 +244,35 @@ unique_ptr<FunctionData> ListLambdaBindData::Deserialize(Deserializer &deseriali
...
+
+LogicalType LambdaFunctions::BindBinaryLambda(const idx_t parameter_idx, ClientContext &context,
+                                              const vector<LogicalType> &function_child_types) {
+	auto list_child_type = DetermineListChildType(function_child_types);
+
 	switch (parameter_idx) {
 	case 0:
 		return list_child_type;
 	case 1:
 		return list_child_type;
```
Comment (taniabogatsch) [inline extension/core_functions/lambda_functions.cpp:273]: Maybe it's the diff, but binary lambdas need to continue returning `case 1: return LogicalType::BIGINT;`.

File: extension/core_functions/lambda_functions.cpp (hunk 2 above)
Comment (taniabogatsch) [inline extension/core_functions/lambda_functions.cpp:257]: Maybe we can make this more explicit?
```
if (array) ...
else if (list) ...
else InternalException...
```

File: extension/core_functions/scalar/list/list_filter.cpp [hunk 5]
```diff
@@ -30,8 +30,9 @@ static unique_ptr<FunctionData> ListFilterBind(ClientContext &context, ScalarFun
 	return LambdaFunctions::ListLambdaBind(context, bound_function, arguments, has_index);
 }
 
-static LogicalType ListFilterBindLambda(const idx_t parameter_idx, const LogicalType &list_child_type) {
-	return LambdaFunctions::BindBinaryLambda(parameter_idx, list_child_type);
+static LogicalType ListFilterBindLambda(const idx_t parameter_idx, ClientContext &context,
```
Comment (taniabogatsch) [inline extension/core_functions/scalar/list/list_filter.cpp:33]: Nit: let's pass the client context as the first argument. Maybe context, types, parameter index?

File: extension/core_functions/scalar/list/list_reduce.cpp [hunk 6]
```diff
@@ -263,8 +262,46 @@ static unique_ptr<FunctionData> ListReduceBind(ClientContext &context, ScalarFun
 	                                     has_initial);
 }
 
-static LogicalType ListReduceBindLambda(const idx_t parameter_idx, const LogicalType &list_child_type) {
-	return LambdaFunctions::BindTernaryLambda(parameter_idx, list_child_type);
+
+LogicalType LambdaFunctions::BindReduce(const idx_t parameter_idx, ClientContext &context,
```
Comment (taniabogatsch) [inline extension/core_functions/scalar/list/list_reduce.cpp:266]: Maybe we can change the name here - its a bit confusing since we also have `ListReduceBind`.

File: extension/core_functions/scalar/list/list_reduce.cpp [hunk 7]
```diff
@@ -263,8 +262,46 @@ static unique_ptr<FunctionData> ListReduceBind(ClientContext &context, ScalarFun
...
+                                        const vector<LogicalType> &function_child_types) {
+	auto list_child_type = DetermineListChildType(function_child_types);
+
+	// if there is an initial value, find the max logical type
+	if (function_child_types.size() == 3) {
```
Comment (taniabogatsch) [inline extension/core_functions/scalar/list/list_reduce.cpp:271]: What happens here if the `list_child_type` is `SQLNULL` or `UNKNOWN`?

File: src/include/duckdb/function/lambda_functions.hpp [hunk 8]
```diff
@@ -53,10 +53,16 @@ struct ListLambdaBindData final : public FunctionData {
...
 	//! Returns the parameter type for binary lambdas
-	static LogicalType BindBinaryLambda(const idx_t parameter_idx, const LogicalType &list_child_type);
-	//! Returns the parameter type for ternary lambdas
-	static LogicalType BindTernaryLambda(const idx_t parameter_idx, const LogicalType &list_child_type);
+	static LogicalType BindBinaryLambda(const idx_t parameter_idx, ClientContext &context,
+	                                    const vector<LogicalType> &function_child_types);
+
+	//! Returns the parameter type for ListReduce
+	static LogicalType BindReduce(const idx_t parameter_idx, ClientContext &context,
+	                              const vector<LogicalType> &function_child_types);
```
Comment (taniabogatsch) [inline src/include/duckdb/function/lambda_functions.hpp:65]: Let's fully move this out of `lambda_functions.hpp` into reduce.

**Review by taniabogatsch — CHANGES_REQUESTED** [review]
Hi @maiadegraaf - thanks! I left a few comments, mostly nits around code structure and some names. :))

File: extension/core_functions/scalar/list/list_reduce.cpp (hunk 7 above)
Comment (maiadegraaf) [reply extension/core_functions/scalar/list/list_reduce.cpp:271]: It is handled by `LogicalType::TryGetMaxLogicalType`, or is passed as a `SQLNULL` or `UNKNOWN` to the function which handles it there.

**Review by taniabogatsch — COMMENTED** [review]
Left a few more comments. :)

**Comment by Mytherin** [comment]
Thanks for the PR! LGTM - should we retarget this to `v1.3` or keep this targeted towards `main`?

**Comment by maiadegraaf** [comment]
I think retargeting to `v1.3` is best. I've rebased the branch, so it should be gtg now!

**Comment by Mytherin** [comment]
Thanks!
