### PR TITLE
Pandas timezone

### LINKED ISSUE #4267: duckdb to/from pandas does not preserve timezone awareness
### What happens?

duckdb preserves timezone-awareness during to/from arrow conversion, but the same information is lost when converting to/from pandas.

### To Reproduce

```python
# Create pandas DataFrame with timezone-aware timestamp column and corresponding arrow table:
import duckdb
import pandas as pd
import pyarrow as pa

df = pd.DataFrame(
    {"timestamp": [pd.Timestamp("2022-01-01", tz="America/New_York")]}
)
arrow_table = pa.Table.from_pandas(df)

con = duckdb.connect()

# duckdb to/from arrow preserves timezone awareness:
con.execute("DESCRIBE (SELECT * FROM arrow_table)").fetchall()
# Output:
# [('timestamp', 'TIMESTAMP WITH TIME ZONE', 'YES', None, None, None)]
con.execute("SELECT * from arrow_table").fetch_arrow_table()
# Output:
# pyarrow.Table
# timestamp: timestamp[us, tz=UTC]
# ----
# timestamp: [[2022-01-01 05:00:00.000000]]

# duckdb to/from pandas drops timezone awareness:
con.execute("DESCRIBE (SELECT * FROM df)").fetchall()
# Output:
# [('timestamp', 'TIMESTAMP', 'YES', None, None, None)]
con.execute("SELECT * from arrow_table").df().dtypes
# Output:
# timestamp    datetime64[ns]
# dtype: object
```

### OS:

OSX

### DuckDB Version:

0.4.1.dev1115 (and 0.4.0)

### DuckDB Client:

Python

### Full Name:

Erin Ovechkin

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by pdet**
Support to timezone types on Pandas.

Note that similarly to Arrow, the timezones are stored in DuckDB in UTC, and will follow the mask value set in the database.

Fix: #4267

### CODE REVIEW

File: tools/pythonpkg/src/pandas_type.cpp [hunk 1]
```diff
@@ -6,64 +6,69 @@
...
 		return PandasType::OBJECT;
-	} else if (col_type == "string") {
+	} else if (col_type_str == "string") {
 		return PandasType::PANDA_STRING;
-	} else if (col_type == "timedelta64[ns]") {
+	} else if (col_type_str == "timedelta64[ns]") {
 		return PandasType::PANDA_INTERVAL;
-	} else if (StringUtil::StartsWith(col_type, "datetime64[ns") || col_type == "<M8[ns]") {
+	} else if (StringUtil::StartsWith(col_type_str, "datetime64[ns") || col_type_str == "<M8[ns]") {
+		if (hasattr(col_type, "tz")) {
```
Comment (Mause) [inline tools/pythonpkg/src/pandas_type.cpp:64]: Weird question, but do we want to check the field contains anything? Or only that it exists?

**Review by Mause — CHANGES_REQUESTED** [review]
Feel free to let me know if I'm nitpicking too much 😁 need to calibrate myself for the duckdb work, vs my day job

File: tools/pythonpkg/src/pandas_type.cpp (hunk 1 above)
Comment (pdet) [reply tools/pythonpkg/src/pandas_type.cpp:64]: That's a good question, 

I was not able to generate an empty timezone, ```tz_convert``` would throw me an error.

Can you generate an empty timezone somehow? If yes, then the question is what does that mean in the Pandas context? Is it equivalent to UTC, or not?

Comment (Mause) [reply tools/pythonpkg/src/pandas_type.cpp:64]: From the pandas docs:
> A tz of None will convert to UTC and remove the timezone information.
answers that question 😅

**Comment by pdet** [comment]
@Mause feel free to nitpick, I've mostly wroten python code for config/experiment scripts, so your comments are very welcome.

File: tools/pythonpkg/src/pandas_type.cpp (hunk 1 above)
Comment (pdet) [reply tools/pythonpkg/src/pandas_type.cpp:64]: Yeah I saw that, but with the ```None``` value the attribute doesn't exist. So I guess we are fine with this :-D.

File: tools/pythonpkg/src/include/duckdb_python/pandas_type.hpp [hunk 2]
```diff
@@ -67,9 +67,11 @@ enum class PandasType : uint8_t {
 	PANDA_DATETIME = 101,       //! datetime64[ns, UTC]
 	PANDA_PERIOD = 102,         //! datetime64[ns, UTC]
 	PANDA_INTERVAL = 103,       //! datetime64[ns, UTC]
+	PANDA_DATETIME_TZ = 104,    //! datetime64[ns, TZ]
```
[the remark this answers is not in the document]
Comment (Tishj) [reply tools/pythonpkg/src/include/duckdb_python/pandas_type.hpp:70]: These are the `num`'s of the dtypes used by Pandas when extending the NumpyDtype.
At some point I planned to use these instead of the conversions to string, to find out which dtype we're dealing with.

But that turned out to not be possible, so I should have removed the explicit values for the dtypes, as they are now unused.

[the remark this answers is not in the document]
Comment (Mause) [reply tools/pythonpkg/src/include/duckdb_python/pandas_type.hpp:70]: @Tishj oh, I meant where in the pandas codebase - I couldn't find any reference to these "major numbers"

**Comment by pdet** [comment]
@Tishj I did a lot of refactoring regarding the ```PandasTypes```  could you please check if these still make sense and work as they were supposed to work?

File: tools/pythonpkg/tests/fast/pandas/test_pandas_timestamp.py [hunk 3]
```diff
@@ -0,0 +1,22 @@
...
+    assert df.equals(duck_df)
+
+def test_pandas_tz_utc():
+    run_pandas_with_tz('UTC')
+
+def test_pandas_tz_utc():
+    run_pandas_with_tz('CET')
+
+def test_pandas_tz_utc():
+    run_pandas_with_tz('Asia/Kathmandu')
```
Comment (Mause) [inline tools/pythonpkg/tests/fast/pandas/test_pandas_timestamp.py:22]:
```suggestion
import duckdb
import pandas as pd
from pytest import mark

@mark.parametrize('timezone', ['UTC', 'CET', 'Asia/Kathmandu'])
def run_pandas_with_tz(timezone):
    con = duckdb.connect()
    con.execute("SET TimeZone = '"+timezone+"'")
    df = pd.DataFrame({"timestamp": [pd.Timestamp("2022-01-01 10:15", tz=timezone)]})
    duck_df = con.from_df(df).df()
    print (df['timestamp'].dtype)
    print(duck_df['timestamp'].dtype)
    print (df)
    print(duck_df)
    assert df.equals(duck_df)
```

**Review by Mause — CHANGES_REQUESTED** [review]

**Comment by Tishj** [comment]
LGTM!

Definitely much cleaner, only things I can think of is that the numpy dtypes were the full list of dtypes that numpy uses, so they might show up as edge cases later.
But we weren't converting to them anyways, so it's better to remove them than to leave them uncovered.

Apart from that the removal of ColumnIsMasked had me scratching my head, but it looks like the "mask" attribute check I added obsoleted the other checks, which I didn't catch at the time 😅

File: tools/pythonpkg/tests/fast/pandas/test_pandas_timestamp.py (hunk 3 above)
Comment (Tishj) [reply tools/pythonpkg/tests/fast/pandas/test_pandas_timestamp.py:22]: Ah yes I have seen that syntax, been meaning to introduce it into a test.
It essentially runs this test 3 times right, with the 3 different arguments to timezone?

**Comment by Mytherin** [comment]
Thanks!
