### PR TITLE
Make the Binder respect the `max_expression_depth` setting

### LINKED ISSUE #8171: [Python] Stack overflow in nested relation scan
### What happens?

```py
import pandas as pd
import duckdb

df = pd.DataFrame({'a': [42]})

con = duckdb.connect()
rel = con.sql('select * from df')
for _ in range(2):
	rel = con.sql('select a from rel')
```

The first iteration is fine, the second one appears to stack-overflow

### OS:

MacOS

### DuckDB Version:

master

### DuckDB Client:

Python

### Full Name:

Thijs Bruineman

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #8171

By introducing a depth limit in the Binder, we catch recursion errors like this earlier, so we can throw an exception instead of crash due to a stack overflow.

Note: this is only really necessary because of the Relation API.
The parser already uses this depth limit, so this restriction will be hit there first and thus we'll never hit this restriction in the binder.
But the Relation API kind of circumvents the parser so we need to check for the depth limit in the binder to catch issues like this.

### CODE REVIEW

File: src/planner/binder.cpp [hunk 1]
```diff
@@ -21,7 +21,20 @@
 
 namespace duckdb {
 
+idx_t Binder::GetBinderDepth(idx_t depth) {
```
Comment (Mytherin) [inline src/planner/binder.cpp:24]: On the topic of stack overflows - perhaps this can be a `while` instead of a recursive function call to prevent expanding the stack more? There are a number of other functions that work in a similar way (recursively call the parent binder) that should likely be reworked in this manner.

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Looks good - one comment:

File: src/planner/binder.cpp (hunk 1 above)
Comment (Mytherin) [reply src/planner/binder.cpp:24]: Other functions like `GenerateTableIndex`, `GetActiveBinders`, `AddUsingBindingSet`, `GetBindingMode`, `AddTableName`, `GetTableNames` only need the root binder, so we can add a function `GetRootBinder()` that returns the top-most parent using a `while` loop that can be used by these functions

Comment (Tishj) [reply src/planner/binder.cpp]: Yes good idea, done 👍

**Comment by Mytherin** [comment]
Thanks! Looks great
