### PR TITLE
Issue #15054: Windowed Aggregate Macros

### LINKED ISSUE #15054: Should macros be allowed as custom aggregate window functions?
### What happens?

See https://github.com/duckdb/duckdb-web/issues/3294

### To Reproduce

```sql
CREATE OR REPLACE MACRO my_agg(x) AS SUM(CASE WHEN x THEN 1 END);
select my_agg(range) from range(2)
```
works and returns `1` but 
```sql
select my_agg(range) OVER () from range(2)
```
throws 
```
Catalog Error: my_agg is not an aggregate function
```

### OS:

Linux

### DuckDB Version:

1.1.0

### DuckDB Client:

Python

### Hardware:

i5, AMD64

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by hawkfish**
Implement expansion of macros that look like windowed aggregates. They still have to result in a top-level aggregate function.

fixes: duckdb/duckdb#15054
fixes: duckdblabs/duckdb-internal#3600

### CODE REVIEW

File: src/planner/binder/expression/bind_window_expression.cpp [hunk 1]
```diff
@@ -142,9 +142,22 @@ static LogicalType BindRangeExpression(ClientContext &context, const string &nam
 }
 
 BindResult BaseSelectBinder::BindWindow(WindowExpression &window, idx_t depth) {
+	QueryErrorContext error_context(window.query_location);
+	//	Check for macros pretending to be aggregates
+	if (window.type == ExpressionType::WINDOW_AGGREGATE) {
+		auto func = GetCatalogEntry(CatalogType::SCALAR_FUNCTION_ENTRY, window.catalog, window.schema,
```
Comment (Mytherin) [inline src/planner/binder/expression/bind_window_expression.cpp:148]: Could we re-use the function we found in the catalog below, to avoid having to do two catalog look-ups in the common case?

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! LGTM - one minor comment

File: src/planner/binder/expression/bind_window_expression.cpp (hunk 1 above)
Comment (hawkfish) [reply src/planner/binder/expression/bind_window_expression.cpp:148]: We seem to do multiple lookups elsewhere in the binder for similar reasons?

**Comment by hawkfish** [comment]
@Mytherin this looks like a CI infrastructure failure - can we restart it?

**Comment by Mytherin** [comment]
Thanks!
