### PR TITLE
Fix issue 8230

### LINKED ISSUE #8230: Memory corruption in httpfs
### What happens?

When running a query that uses views that reference parquet files over httpfs (e.g., `create view forex as select * from 'http://localhost:8080/forex.parquet';`), duckdb occasionally corrupts memory (use-after-free?)

```
duckdb(60001,0x16b177000) malloc: Heap corruption detected, free list is damaged at 0x60000391d0d0
*** Incorrect guard value: 0
duckdb(60001,0x16b177000) malloc: *** set a breakpoint in malloc_error_break to debug
```

This does not seem to happen when running the same queries against local files. I think this is a regression since 0.8.1, but I'm not sure

### To Reproduce

I have a query against four parquet files that semi-reliably (once every thousand runs or so) reproduces this issue. The parquet files (and, to a lesser extent, the query) are not something I'm excited about posting on the internet, but are available if you email me (Mark and Hannes, potentially among others, know how to reach out!)

A rough approximation of the repro:
``` sh
cd dir/with/parquet/files/and/query
# in shell 1
npx http-server
# in shell 2
for i in {1..1000}; do /var/folders/c4/8t155n9x6_9d3_g4f2ym7x240000gn/T/duckdb.0KWzgTfL/build/release/duckdb -unsigned -cmd "load '/var/folders/c4/8t155n9x6_9d3_g4f2ym7x240000gn/T/duckdb.0KWzgTfL/build/release/extension/httpfs/httpfs.duckdb_extension'" -line < preflight.sql; done
duckdb(65574,0x16b5bf000) malloc: Heap corruption detected, free list is damaged at 0x600003751b30
*** Incorrect guard value: 105553131277736
duckdb(65574,0x16b5bf000) malloc: *** set a breakpoint in malloc_error_break to debug
duckdb(65984,0x16b0ef000) malloc: Heap corruption detected, free list is damaged at 0x600003cb42e0
*** Incorrect guard value: 105553147415120
duckdb(65984,0x16b0ef000) malloc: *** set a breakpoint in malloc_error_break to debug
```

### OS:

OSX

### DuckDB Version:

v0.8.2-dev1559 fa204ca892

### DuckDB Client:

shell

### Full Name:

Carl Jackson

### Affiliation:

Watershed

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by samansmink**
fixes https://github.com/duckdb/duckdb/issues/8230. 

The problem was that the unordered map was accessed in a non-thread safe way without holding a lock.
Resolved the issue by refactoring the way the cached_files map is accessed. Confirmed that this fixed the issue by using the bug reproduction from https://github.com/duckdb/duckdb/issues/8230.

### CODE REVIEW

File: src/include/duckdb/common/http_state.hpp [hunk 1]
```diff
@@ -36,7 +38,7 @@ class HTTPState {
 	//! Mutex to lock when getting the cached file(Parallel Only)
 	mutex cached_files_mutex;
 	//! In case of fully downloading the file, the cached files of this query
-	unordered_map<string, CachedFile> cached_files;
+	unordered_map<string, shared_ptr<CachedFile>> cached_files;
```
Comment (Mytherin) [inline src/include/duckdb/common/http_state.hpp:41]: Perhaps we can clean up the code by moving the members to be private (`cached_files` for the `HTTPState`, and `capacity`/ `data`/`finished` for `CachedFile`) and moving accesses to them to GETers that obtain the lock correctly? As it stands it is still easy to accidentally cause a race condition by forgetting to grab the lock (and this might happen elsewhere in the code)

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Looks great. One comment:

File: src/include/duckdb/common/http_state.hpp (hunk 1 above)
Comment (samansmink) [reply src/include/duckdb/common/http_state.hpp:95]: Good point, did a little refactor to make it safer

**Comment by Mytherin** [comment]
Thanks! LGTM
