### PR TITLE
Fix issue #20187: Fix PIVOT aggregate  mismatch for ranges >=21

### LINKED ISSUE #20187: Internal error in PIVOT
### What happens?

```sql
PIVOT (FROM range(21)) 
ON range 
USING 
    sum(range),
    sum(range) 
```
```
INTERNAL Error: Pivot aggregate count mismatch (expected 2, found 1)
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
For more information, see https://duckdb.org/docs/stable/dev/internal_errors
```

Error disappears for any range of size <21.

Previously reported with different example at https://github.com/duckdb/duckdb/issues/9325. The persistence of the broken database state there has since been fixed but the original error hasn't.

### To Reproduce

.

### OS:

Ubuntu

### DuckDB Version:

'1.5.0.dev103'

### DuckDB Client:

Python

### Hardware:

AMD64

### Full Name:

Soeren Wolfers

### Affiliation:

G-Reserach

### Did you include all relevant configuration (e.g., CPU architecture, Linux distribution) to reproduce the issue?

- [x] Yes, I have

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### PR DESCRIPTION
**Pull request by gemy26**
Fixes #20187

## Description
- This PR fixes the internal error "Pivot aggregate count mismatch" that occurs when using PIVOT with duplicate aggregates on ranges >= 21.
- Currently, the binder was not correctly duplicating aggregate expressions for repeated aggregates in the USING clause. 

## Changes
- Modified `BindBoundPivot()` in `src/planner/binder/tableref/bind_pivot.cpp`
- Added logic to detect and handle duplicate aggregate.
- Expanded the deduplicated aggregates to match the user's expected column count.

## Testing
Added  test cases in `test/sql/pivot/test_pivot_duplicate_aggregates.test` to test Mixed duplicate and unique aggregates and different range sizes.

### CODE REVIEW

File: src/planner/binder/tableref/bind_pivot.cpp [hunk 1]
```diff
@@ -425,9 +425,34 @@ BoundStatement Binder::BindBoundPivot(PivotRef &ref) {
 
 	auto &aggregates = result.bound_pivot.aggregates;
 	ExtractPivotAggregates(result.child, aggregates);
-	if (aggregates.size() != ref.bound_aggregate_names.size()) {
-		throw InternalException("Pivot aggregate count mismatch (expected %llu, found %llu)",
-		                        ref.bound_aggregate_names.size(), aggregates.size());
+
+	if (aggregates.size() < ref.bound_aggregate_names.size()) {
```
Comment (lnkuiper) [inline src/planner/binder/tableref/bind_pivot.cpp:429]: The original check of `size != size` was safer than the current check. Could you change the control flow here so that we have the same safety as before, e.g.:
```C++
	if (aggregates.size() < ref.bound_aggregate_names.size()) {
		// try to make these vectors the same size (your changes)
	}

	// if they still aren't the same size throw
	if (aggregates.size() != ref.bound_aggregate_names.size()) {
		throw InternalException("Pivot aggregate count mismatch (expected %llu, found %llu)",
		                        ref.bound_aggregate_names.size(), aggregates.size());
	}
```

**Review by lnkuiper — CHANGES_REQUESTED** [review]
Thanks for the PR! This looks great, I just have one request:

File: src/planner/binder/tableref/bind_pivot.cpp (hunk 1 above)
Comment (gemy26) [reply src/planner/binder/tableref/bind_pivot.cpp:429]: Thanks for review, I've updated the code.

File: PIVOT
Comment (EslamAhmed171) [inline PIVOT:1]: Unnecessary binary file?

Comment (lnkuiper) [reply PIVOT:1]: Good catch, this shouldn't be here

**Review by lnkuiper — APPROVED** [review]
Thanks for the changes! LGTM now
