### PR TITLE
Properly resizing DuckDB batches that reference arrow batches

### LINKED ISSUE #3258: Crash when pulling datasets between Arrow and DuckDB
#### What happens?
Since #3173 merged, we are seeing crashes + data corruption in our roundtrip tests between Arrow and DuckDB with datasets (including filter + mutates). The behavior of these is very similar to what we saw in #2912 (though those were resolved with that PR).

#### To Reproduce
We saw this error in our nightlies (where we test against DuckDB HEAD@default branch](https://github.com/ursacomputing/crossbow/runs/5596172598?check_suite_focus=true). There we're seeing invalid data being returned.

I've also reproduced this locally both with release Arrow and our current HEAD@default branch locally with the following, which variably segfaults, or returns data that does not match:

```
library(arrow)
library(dplyr)

example_data <- tibble::tibble(
  int = c(1:3, NA_integer_, 5:10),
  dbl = c(1:8, NA, 10) + .1,
  dbl2 = rep(5, 10),
  lgl = sample(c(TRUE, FALSE, NA), 10, replace = TRUE),
  false = logical(10),
  chr = letters[c(1:5, NA, 7:10)],
  fct = factor(letters[c(1:4, NA, NA, 7:10)])
)

tf <- tempfile()
new_ds <- rbind(
  cbind(example_data, part = 1),
  cbind(example_data, part = 2),
  cbind(mutate(example_data, dbl = dbl * 3, dbl2 = dbl2 * 3), part = 3),
  cbind(mutate(example_data, dbl = dbl * 4, dbl2 = dbl2 * 4), part = 4)
)
write_dataset(new_ds, tf, partitioning = "part")

ds <- open_dataset(tf)

duck <- ds %>%
    to_duckdb() %>%
    select(-fct) %>%
    mutate(dbl_plus = dbl + 1) %>%
    to_arrow() %>%
    filter(int > 5 & part > 1) %>%
    collect() %>%
    arrange(part, int) %>%
    as.data.frame()

arrow <- ds %>%
    select(-fct) %>%
    filter(int > 5 & part > 1) %>%
    mutate(dbl_plus = dbl + 1) %>%
    collect() %>%
    arrange(part, int)

all.equal(duck, arrow)
```

Steps to reproduce the behavior. Bonus points if those are only SQL queries.

#### Environment (please complete the following information):
 - OS: macOS + Ubuntu
 - DuckDB Version: HEAD@default branch
 - DuckDB Client: R

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

### PR DESCRIPTION
**Pull request by pdet**
Fix: #3258 

Basically when we were appending batches to arrow originated batches, we would resize the original arrow array (which we ofc can't).

@jonkeane I think we should add any duckdb tests that exist on the Arrow testing to duckdb as well, I think this is just one file right now, or are there others?
I've basically copied it to: tools/rpkg/tests/testthat/test_arrow.R

It seems that two tests (the ones commented out) are breaking in the current build and on the latest release, is that expected?

### CODE REVIEW

**Comment by jonkeane** [comment]
For `example_data` you'll either need to copy this file or the block that creates it: https://github.com/apache/arrow/blob/778b1772fd20766e52b2bdccbd37668726f67e0c/r/tests/testthat/helper-data.R#L18-L26

**Comment by pdet** [comment]
example_data is already there.

I basically get


── Failure (???): to_duckdb ────────────────────────────────────────────────────
... %>% arrange(mean_int) not identical to tibble::tibble(...).
Attributes: < Component “row.names”: Numeric: lengths (2, 3) differ >
Component “lgl”: Lengths (2, 3) differ (comparison on first 2 components)
Component “lgl”: 'is.NA' value mismatch: 1 in current 0 in target
Component “mean_int”: Numeric: lengths (2, 3) differ
Component “mean_dbl”: Numeric: lengths (2, 3) differ

── Failure (???): to_duckdb ────────────────────────────────────────────────────
... %>% arrange(mean_int) not identical to tibble::tibble(...).
Attributes: < Component “row.names”: Numeric: lengths (2, 3) differ >
Component “lgl”: Lengths (2, 3) differ (comparison on first 2 components)
Component “lgl”: 'is.NA' value mismatch: 1 in current 0 in target
Component “mean_int”: Numeric: lengths (2, 3) differ
Component “mean_dbl”: Numeric: lengths (2, 3) differ

── Error (???): to_arrow roundtrip, with dataset (without wrapping ─────────────────────
Error in `to_arrow(., as_arrow_query = FALSE)`: unused argument (as_arrow_query = FALSE)

**Comment by jonkeane** [comment]
Ah, you'll need to install the newest Arrow to use that file directly. Our release version doesn't have everything that's tested there (specifically the `as_arrow_query` argument). The easiest way is probably https://arrow.apache.org/docs/r/articles/install.html#install-the-nightly-build

```
Sys.setenv(NOT_CRAN = TRUE)
install.packages("arrow", repos = "https://arrow-r-nightly.s3.amazonaws.com")
```

File: tools/rpkg/tests/testthat/test_arrow.R [hunk 1]
```diff
@@ -0,0 +1,295 @@
...
+# Unless required by applicable law or agreed to in writing,
+# software distributed under the License is distributed on an
+# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
+# KIND, either express or implied.  See the License for the
+# specific language governing permissions and limitations
+# under the License.
+
+library(arrow, warn.conflicts = FALSE)
+library(dplyr, warn.conflicts = FALSE)
+library(duckdb)
```
Comment (rsund) [inline tools/rpkg/tests/testthat/test_arrow.R:20]: Are you sure that you want to load all these package namespaces? I would avoid that if possible. Why quotes in some and no quotes on other? Is there really need for `library(duckdb)` within duckdb?

File: tools/rpkg/tests/testthat/test_arrow.R [hunk 2]
```diff
@@ -0,0 +1,295 @@
...
+library("testthat")
+library("DBI")
+skip_on_cran()
+skip_on_os("windows")
+skip_if_not_installed("arrow", "5.0.0")
+# Skip if parquet is not a capability as an indicator that Arrow is fully installed.
+skip_if_not(arrow::arrow_with_parquet(), message = "The installed Arrow is not fully featured, skipping Arrow integration tests")
+skip_if_not_installed("dbplyr")
+
+example_data <- tibble::tibble(
```
Comment (rsund) [inline tools/rpkg/tests/testthat/test_arrow.R:30]: `tibble` is probably not even a suggested package in DuckDB. Certainly it comes with `dplyr` and others, but maybe that complicates testing? Is there some particular reason to use tibble instead of data.frame here?

File: tools/rpkg/tests/testthat/test_arrow.R [hunk 3]
```diff
@@ -0,0 +1,295 @@
...
+  expect_error(
+    to_arrow(ds_rt),
+    "to_arrow\\(\\) currently only supports Arrow tables, Arrow datasets,"
+  )
+})
+
+test_that("to_arrow roundtrip, with dataset", {
+  # these will continue to error until 0.3.2 is released
+  # https://github.com/duckdb/duckdb/pull/2957
+  skip_if_not_installed("duckdb", minimum_version = "0.3.2")
```
Comment (rsund) [inline tools/rpkg/tests/testthat/test_arrow.R:141]: Probably not relevant in tests within `duckdb`?

File: tools/rpkg/tests/testthat/test_arrow.R [hunk 4]
```diff
@@ -0,0 +1,295 @@
...
+
+#   expect_r6_class(out, "RecordBatchReader")
+# })
+
+# The next set of tests use an already-extant connection to test features of
+# persistence and querying against the table without using the `tbl` itself, so
+# we need to create a connection separate from the ephemeral one that is made
+# with arrow_duck_connection()
+con <- dbConnect(duckdb::duckdb())
+dbExecute(con, "PRAGMA threads=2")
```
Comment (rsund) [inline tools/rpkg/tests/testthat/test_arrow.R:201]: These appear to be outside `test_that()`-function. Maybe that's not the best approach? Connection is not explicitly closed here and most likely `on.exit()` will not be triggered here as it is not inside of a function and results in garbage collected connections?

**Comment by pdet** [comment]
Hey @rsund, thanks for your comments.

These tests are not originated from DuckDB but rather from Arrow.

Hence I'm more inclined to add tibble as a test dependency than manually tweaking tests. Mainly for two reasons. 1) Guaranteed identical tests with Arrow (Voltron is a gold member; hence we must guarantee that their test cases do not break). 2) It is easier to integrate whatever new tests they add if we have the same test dependencies.

In any case, I'm wondering if either @Mytherin or @hannes have an opinion about this.

**Comment by rsund** [comment]
Yes, I understand and certainly it is best to keep test as similar (or even equivalent) if possible!

Maybe you could just change the call to `dplyr::tibble()` as it seems to be exported from that namespace too? Then maybe put `skip_if_not_installed("dplyr")` in the beginning.

Or one way could be to deal with tibble-dependency with the function `pkg_method` included in duckdb R-codes (see examples from the backend-dbplyr__duckdb_connection.R), but probably CI will still fail if all used packages are not installed during the setup

Anyhow,  adding tibble as suggested package in the DESCRIPTION file is not hard dependency, so that certainly is one way to proceed.

Maybe it would in any case be a good idea to suggest potential changes/corrections to arrow-tests? E.g. putting library-calls before skip-functions seems a bit strange (will fail before skip?) and running tests outside of test_that probably are not working as expected.

**Comment by pdet** [comment]
> Yes, I understand and certainly it is best to keep tests as similar (or even identical) if possible!
> 
> Maybe you could just change the call `tibble::tibble()` to `dplyr::tibble()` as it seems to be exported from that namespace too? Then maybe put `skip_if_not_installed("dplyr")` in the beginning.
> 
> EDIT: Or maybe just change `tibble::tibble()` to `data.frame()`?
> 
> Or one way could be to deal with tibble-dependency with the function `pkg_method` included in duckdb R-codes (see examples from the `backend-dbplyr__duckdb_connection.R`), but probably CI will still fail if all used packages are not installed during the setup.
> 
> Anyhow, adding `tibble` as suggested package in the DESCRIPTION file is not a hard dependency, so that certainly is one way to proceed.
> 
> Maybe it would in any case be a good idea to suggest potential changes/corrections to the original arrow-tests as those seem to require more dependencies than duckdb even without actual/obvious need for that and may have some "typos" there? E.g. putting library-calls before skip-functions seems a bit strange (will fail before skip?) and code outside of `test_that` opening a connection and setting `on.exit()` to close it is probably not working as expected. And maybe they could change `tibble` to `data.frame` as it is almost the same thing, `tibble` just adds some flavor to printing of it, but in almost all cases those should work equivalently in normal data-analysis tasks?

Maybe @jonkeane would be interested in taking these suggestions on the Arrow test side :)

**Comment by jonkeane** [comment]
We're very happy to take a PR (or even just a Jira) for cleaning up our tests there.


>  putting library-calls before skip-functions seems a bit strange (will fail before skip?) and 

We [have a sequence of skips with one test between them](https://github.com/apache/arrow/blob/ddb663b1724034f64cc53d62bd2d5a4e8fa42954/r/tests/testthat/test-duckdb.R#L18-L33) to test a failure mode. It's a bit weird, but works. There are other ways this might work, happy to have a PR that does this in a cleaner way 

> code outside of test_that opening a connection and setting on.exit() to close it is probably not working as expected. 

Would love to know more (or have an issue or PR) on this!

> And maybe they could change tibble to data.frame as it is almost the same thing, tibble just adds some flavor to printing of it, but in almost all cases those should work equivalently in normal data-analysis tasks?

The `tibble/dplyr::tibble` issue for us is less of one: we suggest both. So not sure we need or want to move that around in Arrow, but for here that's totally fine!

**Comment by rsund** [comment]
Chance from `tibble::tibble()` to `dplyr::tibble()` seems to be enough to avoid the dependency WARNING in R checks. Other corrections would be more or less cosmetic.

> We [have a sequence of skips with one test between them](https://github.com/apache/arrow/blob/ddb663b1724034f64cc53d62bd2d5a4e8fa42954/r/tests/testthat/test-duckdb.R#L18-L33) to test a failure mode. It's a bit weird, but works. There are other ways this might work, happy to have a PR that does this in a cleaner way

As long as it works it is probably better to keep as it is.
 
> > code outside of test_that opening a connection and setting on.exit() to close it is probably not working as expected.
> Would love to know more (or have an issue or PR) on this!

`on.exit()` should be used only inside of functions, because it won't trigger otherwise. Therefore the connection is not closed properly. Overwriting the next connection to same object, however, releases the connection to gc and works that way without leaks, but gives (local) warnings in tests. I think that manual release of connection after it is no more needed would be a better option here (i.e. moving close to proper place and removing of `on.exit` would be enough). In principle, it may still leave the connection open if there is an error or test failure, but that should happen only when something is going in unexpected way, i.e. it is not a problem if test is successful.

> > And maybe they could change tibble to data.frame as it is almost the same thing, tibble just adds some flavor to printing of it, but in almost all cases those should work equivalently in normal data-analysis tasks?
> The `tibble/dplyr::tibble` issue for us is less of one: we suggest both. So not sure we need or want to move that around in Arrow, but for here that's totally fine!

It seems that the tests would work with base R `data.frame`s, so that would make it easiest to move tests also to other environments (`tibble` has also a class of `data.frame`, i.e. almost everything should work in a same way - there are some differences in how types are converted and how printing works, so that may require some minor tweaking in some cases). But as `dplyr::tibble` can be used insead of `tibble::tibble` that solves the dependency issue here, I think that there is no urgent needs to have a "pure" `data.frame`.

One additional thing could be to minimize the use of `library()` calls and use ::-notation if possible. In the worst case the loading of whole namespaces may mask some functions and break some later tests. But again, if everything works that should be OK.
