### PR TITLE
Fix issue copying a TABLE that references a SEQUENCE

### LINKED ISSUE #14639: Sequences in COPY FROM <database>TO <otherDB> causes Dependency Error
### What happens?

> ./duckdb original.db
v1.1.2 f680b7d08f
Enter ".help" for usage hints.
D create sequence seq start 1;
D create table tbl (id int default nextval('seq'));
D attach 'backup.db';
D copy from database original to backup;
Dependency Error: Error adding dependency for object "tbl" - dependency "seq" is in catalog "original", which does not match the catalog "backup".
Cross catalog dependencies are not supported.

### To Reproduce

```bash
./duckdb original.db
```
```sql
create sequence seq start 1;
create table tbl (id int default nextval('seq'));
attach 'backup.db';
copy from database original to backup;
```
```console
Dependency Error: Error adding dependency for object "tbl" - dependency "seq" is in catalog "original", which does not match the catalog "backup".
Cross catalog dependencies are not supported.
```
### OS:

Windows 10

### DuckDB Version:

1.1.2

### DuckDB Client:

CLI

### Hardware:

_No response_

### Full Name:

johndapps

### Affiliation:

4LP

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #14639

Using `nextval('seq')` was finding the original sequence entry in both the `from` and `to` database.
We are now inserting the catalog+schema of the table in the search path when binding the `nextval`, so it finds the right sequence (the one that was just created)

- `dependency` was removed from ScalarFunction, in favor of `bind_with_binder`, this receives a Binder instead of a ClientContext, we can use the binder to propagate the dependency information directly.
- `bind_extended` can be given instead of `bind` to receive a `ScalarFunctionBindInput` instead of a `ClientContext &`, this should be used if the function has to look up catalog entries (such as `currval` and `nextval`)

### CODE REVIEW

File: src/function/scalar/sequence/nextval.cpp [hunk 1]
```diff
@@ -143,7 +154,8 @@ ScalarFunction NextvalFun::GetFunction() {
 
 ScalarFunction CurrvalFun::GetFunction() {
 	ScalarFunction curr_val("currval", {LogicalType::VARCHAR}, LogicalType::BIGINT,
-	                        NextValFunction<CurrentSequenceValueOperator>, NextValBind, NextValDependency);
+	                        NextValFunction<CurrentSequenceValueOperator>, nullptr, NextValDependency);
```
Comment (Mytherin) [inline src/function/scalar/sequence/nextval.cpp:157]: Looks like the dependency function is still here - can we fully remove it?

**Review by Mytherin — COMMENTED** [review]
Thanks - looks good - one comment

**Comment by Mytherin** [comment]
Maybe we can call it `bind_extended` and pass it a `ScalarFunctionBindInput` structure so that we can extend it further in the future?

**Comment by Mytherin** [comment]
Thanks!
