### PR TITLE
Missing error messages

### LINKED ISSUE #3043: Lateral join issue?
#### What happens?
Hello Duckies! While fuzzing lateral joins in MonetDB, ie got some crashes there :) I see LATERAL join queries are not working how they should be despite being accepted by the parser. I guess this happens because DuckDB is using PostgreSQL parser.

Here's an example:
`CREATE TABLE rt0 (c0 INT);`
`INSERT INTO rt0 VALUES (1), (2), (3), (NULL);`
`SELECT rt0.c0 FROM rt0 JOIN LATERAL (select rt0.c0 from (select 1) y(y)) AS x(x) ON TRUE;`

It should output the rows 1,2,3,NULL

This query gives the error: Error: Binder Error: Referenced table "rt0" not found!
However because it's a lateral join, rt0.c0 can be seen in the joined query.

Either LATERAL should be disabled, or could be implemented. I guess it shouldn't be difficult. Sadly at the moment I don't have time to make a pull request :(

#### To Reproduce
Check the example in the description.

#### Environment (please complete the following information):
 - OS: Linux
 - DuckDB Version: compiled from tip of master branch.
 - DuckDB Client: Shell

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

### PR DESCRIPTION
**Pull request by PedroTadim**
Hi Duckies! I just leave here some missing error messages for alter statements and lateral joins. It should fix #3043

### CODE REVIEW

File: src/include/duckdb/parser/parsed_data/create_sequence_info.hpp [hunk 1]
```diff
@@ -13,6 +13,16 @@
 
 namespace duckdb {
 
+class SequenceInfo {
+public:
```
Comment (Mytherin) [inline src/include/duckdb/parser/parsed_data/create_sequence_info.hpp:17]: We try to avoid bitmasks unless necessary, could we turn this into an `enum class` instead and move this to the `transform_alter_sequence` file (which is the only place where this is used)?

File: src/parser/transform/statement/transform_alter_sequence.cpp [hunk 2]
```diff
@@ -17,12 +18,18 @@ unique_ptr<AlterStatement> Transformer::TransformAlterSequence(duckdb_libpgquery
 		throw InternalException("Expected an argument for ALTER SEQUENCE.");
 	}
 
+	uint32_t used = 0;
```
Comment (Mytherin) [inline src/parser/transform/statement/transform_alter_sequence.cpp:21]: Can we turn this into an `unordered_set<SequenceInfo>` instead?

File: test/sql/catalog/sequence/test_sequence.test [hunk 3]
```diff
@@ -489,3 +489,7 @@ select nextval(1 + 1);
 
 statement error
 select currval(true);
+
+# max value specified more than once
+statement error
+CREATE SEQUENCE wrongseq NO MAXVALUE MAXVALUE 2;
```
Comment (Mytherin) [inline test/sql/catalog/sequence/test_sequence.test:495]: Can we add tests for all of the (potentially) duplicated sequence elements?

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Looks good. Some comments:

File: src/parser/transform/statement/transform_alter_sequence.cpp (hunk 2 above)
Comment (PedroTadim) [reply src/parser/transform/statement/transform_alter_sequence.cpp]: Done

File: test/sql/catalog/sequence/test_sequence.test (hunk 3 above)
Comment (PedroTadim) [reply test/sql/catalog/sequence/test_sequence.test:495]: Added them

**Comment by Mytherin** [comment]
Thanks!
