### PR TITLE
[Fix][ADBC] Implement required ADBCConnectionGetObjects schema

### LINKED ISSUE #11330: ADBC driver ConnectionGetObjects method does not return the standard schema
### What happens?

ADBC standardizes schemas for a number of the methods it exposes, including `ConnectionGetObjects`. The current `ConnectionGetObjects` implementation returns arrow records with a slightly different schema, with the effect that applications relying on the standard schema may break after calling the method.

The structure is defined in a comment in [adbc.h](https://github.com/apache/arrow-adbc/blob/ff866d9e2a696accbff3de3157eff70b3509fa79/adbc.h#L1468) and there is a [C++ helper](https://github.com/apache/arrow-adbc/blob/ff866d9e2a696accbff3de3157eff70b3509fa79/c/driver/common/utils.c#L442) specifying the schema as well.

The main issue is that DuckDB returns `db_schema_name`, `db_schema_tables` at the top-level, but they should actually be nested within a struct below `catalog_name` and `catalog_db_schemas`. There are also fields missing from the schema much more deeply nested such as xdbc and constraint info, but those fields can be reasonably set to null if they cannot be determined.

I have confirmed in the current HEAD of the source code that the described behavior is still the case.

### To Reproduce

```python
import adbc_driver_duckdb
with adbc_driver_duckdb.dbapi.connect() as conn:
    objects = conn.adbc_get_objects(depth="all").read_all()
print(objects.schema)

db_schema_name: string
db_schema_tables: list<l: struct<table_name: string, table_columns: list<l: struct<column_name: string, ordinal_position: int32, remarks: string>>>>
  child 0, l: struct<table_name: string, table_columns: list<l: struct<column_name: string, ordinal_position: int32, remarks: string>>>
      child 0, table_name: string
      child 1, table_columns: list<l: struct<column_name: string, ordinal_position: int32, remarks: string>>
          child 0, l: struct<column_name: string, ordinal_position: int32, remarks: string>
              child 0, column_name: string
              child 1, ordinal_position: int32
              child 2, remarks: string
```

compare to...

```python
import adbc_driver_sqlite
with adbc_driver_sqlite.dbapi.connect() as conn:
    objects = conn.adbc_get_objects(depth="all").read_all()
print(objects.schema)

catalog_name: string
catalog_db_schemas: list<item: struct<db_schema_name: string, db_schema_tables: list<item: struct<table_name: string not null, table_type: string not null, table_columns: list<item: struct<column_name: string not null, ordinal_position: int32, remarks: string, xdbc_data_type: int16, xdbc_type_name: string, xdbc_column_size: int32, xdbc_decimal_digits: int16, xdbc_num_prec_radix: int16, xdbc_nullable: int16, xdbc_column_def: string, xdbc_sql_data_type: int16, xdbc_datetime_sub: int16, xdbc_char_octet_length: int32, xdbc_is_nullable: string, xdbc_scope_catalog: string, xdbc_scope_schema: string, xdbc_scope_table: string, xdbc_is_autoincrement: bool, xdbc_is_generatedcolumn: bool>>, table_constraints: list<item: struct<constraint_name: string, constraint_type: string not null, constraint_column_names: list<item: string> not null, constraint_column_usage: list<item: struct<fk_catalog: string, fk_db_schema: string, fk_table: string not null, fk_column_name: string not null>>>>>>>>
  child 0, item: struct<db_schema_name: string, db_schema_tables: list<item: struct<table_name: string not null, table_type: string not null, table_columns: list<item: struct<column_name: string not null, ordinal_position: int32, remarks: string, xdbc_data_type: int16, xdbc_type_name: string, xdbc_column_size: int32, xdbc_decimal_digits: int16, xdbc_num_prec_radix: int16, xdbc_nullable: int16, xdbc_column_def: string, xdbc_sql_data_type: int16, xdbc_datetime_sub: int16, xdbc_char_octet_length: int32, xdbc_is_nullable: string, xdbc_scope_catalog: string, xdbc_scope_schema: string, xdbc_scope_table: string, xdbc_is_autoincrement: bool, xdbc_is_generatedcolumn: bool>>, table_constraints: list<item: struct<constraint_name: string, constraint_type: string not null, constraint_column_names: list<item: string> not null, constraint_column_usage: list<item: struct<fk_catalog: string, fk_db_schema: string, fk_table: string not null, fk_column_name: string not null>>>>>>>
      child 0, db_schema_name: string
      child 1, db_schema_tables: list<item: struct<table_name: string not null, table_type: string not null, table_columns: list<item: struct<column_name: string not null, ordinal_position: int32, remarks: string, xdbc_data_type: int16, xdbc_type_name: string, xdbc_column_size: int32, xdbc_decimal_digits: int16, xdbc_num_prec_radix: int16, xdbc_nullable: int16, xdbc_column_def: string, xdbc_sql_data_type: int16, xdbc_datetime_sub: int16, xdbc_char_octet_length: int32, xdbc_is_nullable: string, xdbc_scope_catalog: string, xdbc_scope_schema: string, xdbc_scope_table: string, xdbc_is_autoincrement: bool, xdbc_is_generatedcolumn: bool>>, table_constraints: list<item: struct<constraint_name: string, constraint_type: string not null, constraint_column_names: list<item: string> not null, constraint_column_usage: list<item: struct<fk_catalog: string, fk_db_schema: string, fk_table: string not null, fk_column_name: string not null>>>>>>
          child 0, item: struct<table_name: string not null, table_type: string not null, table_columns: list<item: struct<column_name: string not null, ordinal_position: int32, remarks: string, xdbc_data_type: int16, xdbc_type_name: string, xdbc_column_size: int32, xdbc_decimal_digits: int16, xdbc_num_prec_radix: int16, xdbc_nullable: int16, xdbc_column_def: string, xdbc_sql_data_type: int16, xdbc_datetime_sub: int16, xdbc_char_octet_length: int32, xdbc_is_nullable: string, xdbc_scope_catalog: string, xdbc_scope_schema: string, xdbc_scope_table: string, xdbc_is_autoincrement: bool, xdbc_is_generatedcolumn: bool>>, table_constraints: list<item: struct<constraint_name: string, constraint_type: string not null, constraint_column_names: list<item: string> not null, constraint_column_usage: list<item: struct<fk_catalog: string, fk_db_schema: string, fk_table: string not null, fk_column_name: string not null>>>>>
              child 0, table_name: string not null
              child 1, table_type: string not null
              child 2, table_columns: list<item: struct<column_name: string not null, ordinal_position: int32, remarks: string, xdbc_data_type: int16, xdbc_type_name: string, xdbc_column_size: int32, xdbc_decimal_digits: int16, xdbc_num_prec_radix: int16, xdbc_nullable: int16, xdbc_column_def: string, xdbc_sql_data_type: int16, xdbc_datetime_sub: int16, xdbc_char_octet_length: int32, xdbc_is_nullable: string, xdbc_scope_catalog: string, xdbc_scope_schema: string, xdbc_scope_table: string, xdbc_is_autoincrement: bool, xdbc_is_generatedcolumn: bool>>
                  child 0, item: struct<column_name: string not null, ordinal_position: int32, remarks: string, xdbc_data_type: int16, xdbc_type_name: string, xdbc_column_size: int32, xdbc_decimal_digits: int16, xdbc_num_prec_radix: int16, xdbc_nullable: int16, xdbc_column_def: string, xdbc_sql_data_type: int16, xdbc_datetime_sub: int16, xdbc_char_octet_length: int32, xdbc_is_nullable: string, xdbc_scope_catalog: string, xdbc_scope_schema: string, xdbc_scope_table: string, xdbc_is_autoincrement: bool, xdbc_is_generatedcolumn: bool>
                      child 0, column_name: string not null
                      child 1, ordinal_position: int32
                      child 2, remarks: string
                      child 3, xdbc_data_type: int16
                      child 4, xdbc_type_name: string
                      child 5, xdbc_column_size: int32
                      child 6, xdbc_decimal_digits: int16
                      child 7, xdbc_num_prec_radix: int16
                      child 8, xdbc_nullable: int16
                      child 9, xdbc_column_def: string
                      child 10, xdbc_sql_data_type: int16
                      child 11, xdbc_datetime_sub: int16
                      child 12, xdbc_char_octet_length: int32
                      child 13, xdbc_is_nullable: string
                      child 14, xdbc_scope_catalog: string
                      child 15, xdbc_scope_schema: string
                      child 16, xdbc_scope_table: string
                      child 17, xdbc_is_autoincrement: bool
                      child 18, xdbc_is_generatedcolumn: bool
              child 3, table_constraints: list<item: struct<constraint_name: string, constraint_type: string not null, constraint_column_names: list<item: string> not null, constraint_column_usage: list<item: struct<fk_catalog: string, fk_db_schema: string, fk_table: string not null, fk_column_name: string not null>>>>
                  child 0, item: struct<constraint_name: string, constraint_type: string not null, constraint_column_names: list<item: string> not null, constraint_column_usage: list<item: struct<fk_catalog: string, fk_db_schema: string, fk_table: string not null, fk_column_name: string not null>>>
                      child 0, constraint_name: string
                      child 1, constraint_type: string not null
                      child 2, constraint_column_names: list<item: string> not null
                          child 0, item: string
                      child 3, constraint_column_usage: list<item: struct<fk_catalog: string, fk_db_schema: string, fk_table: string not null, fk_column_name: string not null>>
                          child 0, item: struct<fk_catalog: string, fk_db_schema: string, fk_table: string not null, fk_column_name: string not null>
                              child 0, fk_catalog: string
                              child 1, fk_db_schema: string
                              child 2, fk_table: string not null
                              child 3, fk_column_name: string not null
```

### OS:

MacOS x64

### DuckDB Version:

0.10.0

### DuckDB Client:

Python and Go

### Full Name:

Joel Lubinitsky

### Affiliation:

Backdeck, inc

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by joellubi**
Fixes: #11330

Previously, the output of ADBCConnectionGetObjects did not output results in the [schema expected](https://github.com/apache/arrow-adbc/blob/ff866d9e2a696accbff3de3157eff70b3509fa79/adbc.h#L1468) by ADBC.

This fix ensures that the proper schema is used for GetObjects at all search depths and with any filter patterns.

Additionally:
- `depth='catalog'` is now implemented
- `table_type` is now included in results but still not valid for filtering (not implemented in upstream api)
- Table constraints are now included in the results (see limitations)

Limitations:
- The official GetObjects result schema specifies certain fields to be `not null`. The nullability is technically part of the schema, so it must be specified to have an exact schema match. In practice this would likely require defining the schema explicitly rather than deriving it from the query result to get it exact. That may be a better approach but at least for this implementation the response should be compatible with what most consumers would be expecting.
- Table constraints `names` and `types` are added to the response, but the current `information_schema` tables only contain `column` information for certain constraint types. For consistency across all constraint types, I've left the constraint-column fields as NULL.

### CODE REVIEW

File: src/common/adbc/adbc.cpp [hunk 1]
```diff
@@ -960,57 +960,312 @@ AdbcStatusCode StatementSetOption(struct AdbcStatement *statement, const char *k
...
-		return ADBC_STATUS_NOT_IMPLEMENTED;
+		// Return metadata on catalogs.
+		query = duckdb::StringUtil::Format(R"(
+				WITH filtered_schemata AS (
+					SELECT
+						catalog_name,
+						schema_name,
+					FROM
+						information_schema.schemata
+					WHERE catalog_name NOT IN ('system', 'temp') AND schema_name NOT IN ('information_schema', 'pg_catalog')
```
Comment (pdet) [inline src/common/adbc/adbc.cpp:984]: Are these a restriction in the ADBC spec?

**Review by pdet — COMMENTED** [review]
Thanks for the implementation and the fixes, I think it looks really good!

One thing I'm wondering is if it makes sense for us to change our python tests to compare with `adbc_driver_sqlite` results instead of hand-crafted answers.

I think this can be interesting because the results can be somewhat error-prone and the `adbc_driver_sqlite` is more up-to-date with latest ADBC developments, so it can also break the test if the ADBC definition changes in the future

File: src/common/adbc/adbc.cpp (hunk 1 above)
Comment (joellubi) [reply src/common/adbc/adbc.cpp:984]: It's not specified in the spec, but neither the sqlite nor postgres drivers currently include system tables. This is a good point, because I think clarity about this is currently missing from the spec. I'm going ask on the arrow mailing list about this.

**Comment by joellubi** [comment]
> Thanks for the implementation and the fixes, I think it looks really good!
> 
> One thing I'm wondering is if it makes sense for us to change our python tests to compare with `adbc_driver_sqlite` results instead of hand-crafted answers.
> 
> I think this can be interesting because the results can be somewhat error-prone and the `adbc_driver_sqlite` is more up-to-date with latest ADBC developments, so it can also break the test if the ADBC definition changes in the future

Thanks @pdet!

I had a similar thought to compare to an authoritative source. I think it would be valuable to compare schemas, such as:
```python
assert duck_conn.adbc_get_objects(depth="all").read_all().schema == sqlite_conn.adbc_get_objects(depth="all").read_all().schema
```

Is this what you had in mind? In that case it might make sense to have adbc export the reference schemas themselves, which would avoid the need to bring an entire driver along with it.

The C++ drivers in the arrow-adbc repo currently use [this helper](https://github.com/apache/arrow-adbc/blob/49ea4ad008ca593b20ca3729c1bab656a5b1e1cc/c/driver/common/utils.c#L442) to keep schemas consistent. Is this something you think you would be able to use? The python library doesn't currently export the reference schemas, but perhaps we can add that to aid with testing.

**Comment by pdet** [comment]
> > Thanks for the implementation and the fixes, I think it looks really good!
> > One thing I'm wondering is if it makes sense for us to change our python tests to compare with `adbc_driver_sqlite` results instead of hand-crafted answers.
> > I think this can be interesting because the results can be somewhat error-prone and the `adbc_driver_sqlite` is more up-to-date with latest ADBC developments, so it can also break the test if the ADBC definition changes in the future
> 
> Thanks @pdet!
> 
> I had a similar thought to compare to an authoritative source. I think it would be valuable to compare schemas, such as:
> 
> ```python
> assert duck_conn.adbc_get_objects(depth="all").read_all().schema == sqlite_conn.adbc_get_objects(depth="all").read_all().schema
> ```
> 
> Is this what you had in mind? In that case it might make sense to have adbc export the reference schemas themselves, which would avoid the need to bring an entire driver along with it.
> 
> The C++ drivers in the arrow-adbc repo currently use [this helper](https://github.com/apache/arrow-adbc/blob/49ea4ad008ca593b20ca3729c1bab656a5b1e1cc/c/driver/common/utils.c#L442) to keep schemas consistent. Is this something you think you would be able to use? The python library doesn't currently export the reference schemas, but perhaps we can add that to aid with testing.

I think that incorporating the driver shouldn't be problematic for the Python tests. We've added test dependencies for lesser reasons, and it might actually prove to be beneficial in checking other ADBC functionality. The advantage of doing this in the Python layer is that it will automatically fetch the latest driver, causing the test to fail if it becomes non-compliant. Conversely, if we inline the helper function, we might have to manually update it in the future.
I think that bringing the driver should not be that problematic for the python tests, we have added test dependencies for less and might actually prove to be worth it on checking other ADBC functionality. I think the nicest thing of doing it in the Python layer is that it will automatically get the latest driver and the test will fail if it goes out of conformity. While if we inline the helper function we might even have to manually update it in the future.

**Comment by pdet** [comment]
> > Thanks for the implementation and the fixes, I think it looks really good!
> > One thing I'm wondering is if it makes sense for us to change our python tests to compare with `adbc_driver_sqlite` results instead of hand-crafted answers.
> > I think this can be interesting because the results can be somewhat error-prone and the `adbc_driver_sqlite` is more up-to-date with latest ADBC developments, so it can also break the test if the ADBC definition changes in the future
> 
> Thanks @pdet!
> 
> I had a similar thought to compare to an authoritative source. I think it would be valuable to compare schemas, such as:
> 
> ```python
> assert duck_conn.adbc_get_objects(depth="all").read_all().schema == sqlite_conn.adbc_get_objects(depth="all").read_all().schema
> ```
> 
> Is this what you had in mind? In that case it might make sense to have adbc export the reference schemas themselves, which would avoid the need to bring an entire driver along with it.
> 
> The C++ drivers in the arrow-adbc repo currently use [this helper](https://github.com/apache/arrow-adbc/blob/49ea4ad008ca593b20ca3729c1bab656a5b1e1cc/c/driver/common/utils.c#L442) to keep schemas consistent. Is this something you think you would be able to use? The python library doesn't currently export the reference schemas, but perhaps we can add that to aid with testing.

I think that adding the driver shouldn't be problematic for the Python tests. We've added test dependencies for lesser reasons, and it might actually prove to be useful in checking other ADBC functions. 
The advantage of doing this in the Python layer is that it will automatically fetch the latest driver, causing the test to fail if it becomes non-compliant. However, if we inline the helper function, we might have to manually update it in the future.

I think that matching the schema is a great idea. Ideally we could even create catalog/tables/what-not and match the actual values, but maybe there are smaller incompatibilities with SQLite and DuckDB that would make this too hacky or even impossible.

**Comment by joellubi** [comment]
> I think that matching the schema is a great idea. Ideally we could even create catalog/tables/what-not and match the actual values, but maybe there are smaller incompatibilities with SQLite and DuckDB that would make this too hacky or even impossible.

I'm happy to give this a try. The only thing is that a naive schema matching test would fail in the current implementation. The main reason is that certain fields in the reference schema are annotated `not null` but by default duckdb arrow fields are all nullable. One way around this is to implement a `schema_approximate_equals` helper for testing that is insensitive to nullability. The other is to pass an explicit schema when constructing the arrow stream, but this will require a bigger refactor. What do you think?

I think either could be done as a follow-up as well.

**Comment by pdet** [comment]
> * In practice this would likely require defining the schema explicitly rather than deriving it from the query result to get it exact. That may be a better approach but at least for this implementation the response should be compatible with what most consumers would be expecting.

That makes sense, I think it can be a separate PR where we adress the: 

> The official GetObjects result schema specifies certain fields to be not null. The nullability is technically part of the schema, so it must be specified to have an exact schema match. In practice this would likely require defining the schema explicitly rather than deriving it from the query result to get it exact. That may be a better approach but at least for this implementation the response should be compatible with what most consumers would be expecting.

And then we add the exact match.

**Review by pdet — APPROVED** [review]

File: src/common/adbc/adbc.cpp (hunk 1 above)
Comment (joellubi) [reply src/common/adbc/adbc.cpp:980]: Thanks for the approval @pdet. The only part that remains is this catalog/schema filter. I've confirmed that the spec does not require system tables to be excluded. I can remove the filter and update the tests.

**Comment by Mytherin** [comment]
Thanks!
