### PR TITLE
Not using Random Device in DuckDB Core

### LINKED ISSUE #14: [JDBC] DuckDB JDBC driver SIGSEGV the JVM since 0.9.0
### What happens?

Since version 0.9.0, using the DuckDB JDBC driver in a Java application makes the application crash with a SIGSEGV.
The Java version is 17.0.5 (tested also on 17.0.8.1).

There is first a Java exception

```
java.sql.SQLException: random_device could not be read
	at org.duckdb.DuckDBNative.duckdb_jdbc_startup(Native Method)
	at org.duckdb.DuckDBConnection.newConnection(DuckDBConnection.java:48)
	at org.duckdb.DuckDBDriver.connect(DuckDBDriver.java:38)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:190)
	at io.kestra.plugin.jdbc.JdbcConnectionInterface.connection(JdbcConnectionInterface.java:63)
	at io.kestra.plugin.jdbc.AbstractJdbcQuery.run(AbstractJdbcQuery.java:77)
	at io.kestra.plugin.jdbc.duckdb.Query.run(Query.java:148)
	at io.kestra.plugin.jdbc.duckdb.Query.run(Query.java:31)
	at io.kestra.core.runners.Worker$WorkerThread.run(Worker.java:674) 	
```

Then a JVM crash

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f523603fd60, pid=37746, tid=39346
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.5+8 (17.0.5+8) (build 17.0.5+8)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (17.0.5+8, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  0x00007f523603fd60
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to <redacted>)
#
# An error report file with more information is saved as:
# <redacted>
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

It works well with 0.8.0.

### To Reproduce

Here is the SQL query:

```
      INSTALL httpfs;
      SELECT Title, max("Days In Top 10") 
      from (SELECT * FROM read_parquet('s3://duckdb-md-dataset-121/netflix_daily_top_10.parquet'))
      where Type='Movie'
      GROUP BY Title
      ORDER BY max("Days In Top 10") desc
      limit 5;
```

The code uses the standard Java JDBC API (Connection & Statement), but it is not easily extracted as it runs via [Kestra DuckDB plugin](https://github.com/kestra-io/plugin-jdbc/tree/master/plugin-jdbc-duckdb).

### OS:

Ubuntu 23.04

### DuckDB Version:

0.9.0

### DuckDB Client:

Java JDBC

### Full Name:

Loïc Mathieu

### Affiliation:

Kestra

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### LINKED ISSUE #8708: "ImportError: random_device could not be read" after importing tensorflow
### What happens?

In a linux x86_64 machine in a python3.10 venv that contains `tensorflow==2.13.0` and `duckdb==0.8.1`, running this python code:
```python
import tensorflow
import duckdb
```
either hangs indefinitely or crashes with 
```
ImportError: random_device could not be read
```

This happens with tensorflow 2.12 and tensorflow 2.13, but not tensorflow 2.11 or 2.11.1.
It also happens with both duckdb 0.7.1 and duckdb 0.8.1.

It doesn't happen if I run
```python
import duckdb
import tensorflow
```
or
```python
import duckdb
```
or
```python
import tensorflow
```
.

### To Reproduce

On a x86_64 linux machine:
```sh
python3.10 -m venv ./venv
source ./venv/bin/activate
pip install tensorflow==2.13.0 duckdb==0.8.1
python -c 'import tensorflow; print("done importing tensorflow"); import duckdb'
```
produces the output:
```
2023-08-29 02:03:04.910055: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-08-29 02:03:04.916150: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-29 02:03:04.955909: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-29 02:03:04.956466: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-29 02:03:07.224135: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
done importing tensorflow
[hangs forever]
```

### OS:

Linux

### DuckDB Version:

0.8.1

### DuckDB Client:

Python

### Full Name:

Sidharth Kapur

### Affiliation:

OpenLabs USA

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by pdet**
Random Device has different interfaces and libc++ and in libstdc++, this can cause symbol collisions with other libraries.
This PR removes the usage of random device and checks the symbols are not exported in CI.
It is most likely necessary to also amend extensions that might use and export this symbol.

Fix: https://github.com/duckdb/duckdb-java/issues/14
Fix: https://github.com/duckdb/duckdb/issues/8708

### CODE REVIEW

File: src/common/random_engine.cpp [hunk 1]
```diff
@@ -14,7 +19,13 @@ struct RandomState {
 
 RandomEngine::RandomEngine(int64_t seed) : random_state(make_uniq<RandomState>()) {
 	if (seed < 0) {
+#ifdef __linux__
+		idx_t random_seed;
+		syscall(SYS_getrandom, &random_seed, sizeof(random_seed), 0);
```
Comment (Mytherin) [inline src/common/random_engine.cpp:24]: Can we check the return value here?

**Review by Mytherin — COMMENTED** [review]
Thanks! Looks good - one more minor comment

File: src/common/random_engine.cpp (hunk 1 above)
Comment (Mytherin) [reply src/common/random_engine.cpp:24]: Trying to recover sounds good

**Comment by Mytherin** [comment]
Thanks!
