### PR TITLE
Fix INSERT OR REPLACE updates on non-unique indexed columns

### LINKED ISSUE #20952: Insert or replace succeeds but doesn't update non-PK indexed columns
### What happens?

Calling `insert or replace` on a table that includes indexes on non-primary key columns executes successfully but doesn't update the other indexed columns.

### To Reproduce

Minimal replication:
```
CREATE TABLE t (id VARCHAR PRIMARY KEY, state VARCHAR NOT NULL, name VARCHAR NOT NULL);
INSERT OR REPLACE INTO t VALUES ('a', 'first', 'jeremy');
CREATE INDEX idx_state ON t(state);
INSERT OR REPLACE INTO t VALUES ('a', 'second','tim');
select * from t;
```
I would expect the select to return "a, second, tim" but get "a,first,tim".

### OS:

Ubuntu 24.04.3 LTS x86_64

### DuckDB Version:

1.4.4

### DuckDB Client:

python, cli

### Hardware:

_No response_

### Full Name:

Jeremy Keillor

### Affiliation:

CIBO Technologies

### Did you include all relevant configuration (e.g., CPU architecture, Linux distribution) to reproduce the issue?

- [x] Yes, I have

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant data sets for reproducing the issue?

Yes

### PR DESCRIPTION
**Pull request by feichai0017**
## Summary

Fix `INSERT OR REPLACE` conflict-update behavior for tables that have non-unique indexes.

- Change `CreateSetInfoForReplace` to exclude only conflict-key columns from UNIQUE/PRIMARY KEY indexes.
- Allow `INSERT OR REPLACE` to update non-unique indexed columns (fixes the behavior reported in #20952).
- Keep conflict-key columns out of the generated `SET` list to avoid unnecessary delete+insert rewrites.
- Add a regression test for #20952.
- Update the existing ART constraint test to match the new `INSERT OR REPLACE` semantics for non-unique indexed columns.

## Testing

- `make allunit`

Fixes #20952

### CODE REVIEW

File: src/planner/binder/statement/bind_insert.cpp [hunk 1]
```diff
@@ -174,34 +174,36 @@ void DoUpdateSetQualify(unique_ptr<ParsedExpression> &expr, const string &table_
...
 			}
-			columns.push_back(name);
+			columns.push_back(column.Name());
 		}
 	} else {
 		// a list of columns was explicitly supplied, only update those
 		for (auto &name : insert.columns) {
 			auto &column = column_list.GetColumn(name);
-			if (indexed_columns.count(column.Oid())) {
+			if (conflict_columns.count(column.Oid())) {
```
Comment (artjomPlaunov) [inline src/planner/binder/statement/bind_insert.cpp:206]: can we have a test that exercises the else branch here, i.e. I think there may have also been a bug here that you fixed with this, but it's not in the test case. I think something like  INSERT OR REPLACE INTO t (id, state) VALUES ('a', 'second'); perhaps? (confirm that it actually hits this code path though).

File: src/planner/binder/statement/bind_insert.cpp [hunk 2]
```diff
@@ -174,34 +174,36 @@ void DoUpdateSetQualify(unique_ptr<ParsedExpression> &expr, const string &table_
...
-                                                  TableStorageInfo &storage_info) {
+                                                  const TableStorageInfo &storage_info) {
 	auto set_info = make_uniq<UpdateSetInfo>();
 
 	auto &columns = set_info->columns;
-	// Figure out which columns are indexed on
-
-	unordered_set<column_t> indexed_columns;
+	// REPLACE is rewritten to UPDATE and should not try to write conflict-key columns.
+	// Updating those columns triggers unnecessary delete+insert rewrites and can perturb row ordering.
```
Comment (artjomPlaunov) [inline src/planner/binder/statement/bind_insert.cpp]: I'm not entirely sure about the row ordering claim here, can you explain to me?

File: test/sql/upsert/insert_or_replace/issue_20952_non_pk_index_column.test
Comment (artjomPlaunov) [inline test/sql/upsert/insert_or_replace/issue_20952_non_pk_index_column.test:1]: I'm wondering if there may be issues with column IDs here, namely what if we had a generated column in the mix. Can you add a test case that adds a generated column, so that the index logical and physical offsets are not aligned, then tests the original behavior again?

i.e. a similar insert of replace scenario, but with the table like: 

```sql
CREATE TABLE t3 (
    gen AS (1),
    id VARCHAR PRIMARY KEY,
    state VARCHAR NOT NULL,
    name VARCHAR NOT NULL
);
```

**Comment by artjomPlaunov** [comment]
@feichai0017 Thank you for the PR! :-) Can we rebase this to 1.5 since it's a bugfix? 

It mostly looks good to me, mainly I just want to see a little more testing. Also I'm not sure if there might be underlying issues with the physical/logical column offsets, but as I commented in the review, it would be a follow up PR.

File: test/sql/upsert/insert_or_replace/issue_20952_non_pk_index_column.test
Comment (artjomPlaunov) [reply test/sql/upsert/insert_or_replace/issue_20952_non_pk_index_column.test:1]: actually, even if this is an issue, we should keep the PR scoped as is, so disregard (it would be a follow up PR if you're interested in picking it up).

**Review by artjomPlaunov — CHANGES_REQUESTED** [review]

File: test/sql/upsert/insert_or_replace/issue_20952_non_pk_index_column.test
Comment (artjomPlaunov) [inline test/sql/upsert/insert_or_replace/issue_20952_non_pk_index_column.test:1]: one more test to add: let's have a composite key index as the non-unique index for the insert or replace

```sql
  CREATE TABLE t (id INT PRIMARY KEY, a INT, b INT);                                                                                    
  CREATE INDEX idx_ab ON t(a, b); 
```

**Review by artjomPlaunov — CHANGES_REQUESTED** [review]

**Comment by feichai0017** [comment]
Thanks for the review, I added both requested test scenarios.

1) Else-branch coverage in CreateSetInfoForReplace:
   I added `INSERT OR REPLACE INTO t(id, state) VALUES ('a', 'fourth')` and verified only `state` changes while `name` remains unchanged. This exercises the explicit-column-list path (`insert.columns` non-empty).

2) Composite non-unique index coverage:
   I added a table with `CREATE INDEX idx_ab ON t_comp(a, b)` and tested REPLACE updates with both full-row and explicit-column-list inserts, including an assertion that the old composite key no longer matches.

I also updated the nearby comment in bind_insert.cpp to remove the row-ordering wording and make it precise: conflict-key columns are used for conflict matching and should not be included in the SET list.

**Review by artjomPlaunov — APPROVED** [review]

**Comment by artjomPlaunov** [comment]
Thanks! LGTM

**Comment by Mytherin** [comment]
Thanks!
