### PR TITLE
[Encryption] Adding random IV and tag for canary encryption

### LINKED ISSUE #20162: Store and verify tag for canary encryption
### What happens?

An encrypted canary is stored in the database header of an encrypted file, to check whether the _correct_ key is used to decrypt a database. Currently, we use AES-GCM with a constant IV to en- and decrypt, without storing and checking the tag. This is not NIST-compliant.

### To Reproduce

n/a

### OS:

MacOS

### DuckDB Version:

1.4.2

### DuckDB Client:

CLI

### Hardware:

n/a

### Full Name:

Lotte Felius

### Affiliation:

DuckDB Labs

### Did you include all relevant configuration (e.g., CPU architecture, Linux distribution) to reproduce the issue?

- [x] Yes, I have

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### PR DESCRIPTION
**Pull request by ccfelius**
This PR makes sure to use a randomized IV/nonce and tag for the encrypted canary, which is necessary to meet the NIST requirements. To strengthen the security a bit, in newer encrypted files the canary is always en/decrypted with AES GCM.

I used an extra byte of the encryption metadata, which now indicates the DuckDB encryption version. Reading older versions of encrypted database files remains possible. Writing older (v0) encrypted files is also still possible, but it requires explicitly setting the older version with `debug_encryption_version 'v0'`, such that:

`ATTACH 'encrypted.duckdb' AS encrypted_v0 (ENCRYPTION_KEY 'asdf', debug_encryption_version 'v0');` 

Note that changing the IV/nonce to 12-bytes will be addressed in a follow-up PR since this requires some more refactoring for backwards compatibility, and for the OpenSSL API (the GCM cipher requires a 12-byte input IV and for CTR this is 16: 12 bytes + the 4-byte counter which we need to initialize ourselves). However, changing back the default IV size is not strictly necessary for meeting the NIST requirements.

Fixes https://github.com/duckdb/duckdb/issues/20162 and https://github.com/duckdblabs/duckdb-internal/issues/6891

### CODE REVIEW

**Comment by carlopi** [comment]
Question: would not make sense to move from `debug_encryption_version 'v0'` to piggy back on the storage_version, AND changing default to v1.5.0 for encrypted databases?

That way the default case is that files are properly written, if user opts differently, files compatible with older duckdb are produced, but default is v1.5.0+ compatible only.

**Comment by ccfelius** [comment]
> Question: would not make sense to move from `debug_encryption_version 'v0'` to piggy back on the storage_version, AND changing default to v1.5.0 for encrypted databases?
> 
> That way the default case is that files are properly written, if user opts differently, files compatible with older duckdb are produced, but default is v1.5.0+ compatible only.

Maybe I do not understand it correctly; but the default is 1.5.0 now. Only if you explicitly use `debug_encryption_version 'v0'` an older encryption version file will be written, mainly for debugging purposes and my initial thought was that it's a bit more flexible this way since you don't have to force an older storage version if you want to write an older version. But yeah, in general writing older encryption versions should be avoided.

 Either way, I'm also fine with your approach since it's more robust.

**Comment by carlopi** [comment]
Oh, now I see, that this can be done already as per the PR.
I guess a version of my comment then is "does the extra option needs to be exposed to users at all?" (say in the docs), and now at a more proper read I think the answer is that it's not necessary, like:

```sql
---- these are all equivalent
ATTACH 'my_db1.db' (ENCRYPTION_KEY 'key1', STORAGE_VERSION 'v1.4.0');
ATTACH 'my_db1.db' (ENCRYPTION_KEY 'key1', debug_encryption_version 'v0');

---- these are also all equivalent
ATTACH 'my_db2.db' (ENCRYPTION_KEY 'key2');   ---- default behaviour
ATTACH 'my_db2.db' (ENCRYPTION_KEY 'key2', debug_encryption_version 'v1');
ATTACH 'my_db2.db' (ENCRYPTION_KEY 'key2', STORAGE_VERSION 'v1.5.0');
```
given `debug_encryption_version` and `STORAGE_VERSION` go hand in hand. This was not obvious to me at first look, but that's on me.

**Comment by ccfelius** [comment]
> ```sql
> ---- these are all equivalent
> ATTACH 'my_db1.db' (ENCRYPTION_KEY 'key1', STORAGE_VERSION 'v1.4.0');
> ATTACH 'my_db1.db' (ENCRYPTION_KEY 'key1', debug_encryption_version 'v0');
> ```

This is not entirely correct. The idea was that `ATTACH 'my_db1.db' (ENCRYPTION_KEY 'key1', debug_encryption_version 'v0');` does not force storage version 1.4.0; it can be any that supports encryption, but I also do not set it explicitly to 1.5.0 indeed.

File: src/storage/storage_manager.cpp [hunk 1]
```diff
@@ -62,20 +61,42 @@ void StorageOptions::Initialize(const unordered_map<string, Value> &options) {
...
+		if (!storage_version.IsValid() ||
+		    storage_version.GetIndex() < SerializationCompatibility::FromString("v1.4.0").serialization_version) {
+			if (!storage_version_user_provided.empty()) {
+				throw InvalidInputException("Explicit provided STORAGE_VERSION (\"%s\") and ENCRYPTION_KEY (storage >= "
+				                            "v1.4.0) are not compatible",
+				                            storage_version_user_provided);
+			}
+		}
+		// explicit storage version input
+		if ((!storage_version_user_provided.empty() &&
```
Comment (carlopi) [inline src/storage/storage_manager.cpp]: I still think the following block is not completely correct, there are a few more cases to consider, like I would set storage_version after checking it's not already higher than necessary (currently it will just override v1.5.0, whatever it is to start with).

Note that this might not be wrong now, but it will become in a few months.

File: src/storage/storage_manager.cpp [hunk 2]
```diff
@@ -24,54 +24,63 @@ namespace duckdb {
...
+		// storage version set, but v1.4.0 =< storage < v1.5.0
+		if (storage_version.GetIndex() < SerializationCompatibility::FromString("v1.5.0").serialization_version) {
 			if (!storage_version_user_provided.empty()) {
-				throw InvalidInputException("Explicit provided STORAGE_VERSION (\"%s\") is not compatible with "
-				                            "'debug_encryption_version=v1' (storage >= "
-				                            "v1.5.0)",
-				                            storage_version_user_provided);
+				if (encryption_version == target_encryption_version) {
+					// encryption version is explicitly given, but not compatible with < v1.5.0
+					if (!storage_version_user_provided.empty()) {
```
Comment (carlopi) [inline src/storage/storage_manager.cpp]: Way nicer!!

I think one of line 52 and 55 are redundant.

**Comment by lnkuiper** [comment]
This looks great! Since you've requested a review, maybe @samansmink can have one last look?

**Review by samansmink — APPROVED** [review]

**Comment by lnkuiper** [comment]
Thanks!
