### PR TITLE
Fix #19575: Fix illegal utf8 character

### LINKED ISSUE #19575: [1.4.1] Interesting error with like expression on some character. (Invalid unicode)
### What happens?

Insert some utf8 character into database, then select it with like.

"绿色"   chinese, means "Green".

C:\Softwares\duckdb-1.4.1\cli\v1.4.1\windows-amd64>duckdb
DuckDB v1.4.1 (Andium) b390a7c376
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D create or replace table aaa(name varchar);
D insert into aaa values('绿色');
D select * from aaa;
┌─────────┐
│  name   │
│ varchar │
├─────────┤
│ 绿色    │
└─────────┘
D select * from aaa where name like '绿%';
Invalid Input Error:
Invalid unicode (byte sequence mismatch) detected in value construction

### To Reproduce

```
create or replace table aaa(name varchar);
insert into aaa values('绿色');
select * from aaa;
select * from aaa where name like '绿%';
```

### OS:

Windows, Linux (both aarch64 and x86_64)

### DuckDB Version:

1.4.1

### DuckDB Client:

CLI

### Hardware:

_No response_

### Full Name:

RobotSlacker

### Affiliation:

RobotSlacker

### Did you include all relevant configuration (e.g., CPU architecture, Linux distribution) to reproduce the issue?

- [x] Yes, I have

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### PR DESCRIPTION
**Pull request by flashmouse**
This PR is a simple fix for #19575. If we still want to create a ``COMPARE_LESSTHAN`` filter, we need to handle the ``prefix_string`` at the character encoding level, not the byte level.

### CODE REVIEW

File: src/optimizer/filter_combiner.cpp [hunk 1]
```diff
@@ -397,10 +398,12 @@ FilterPushdownResult FilterCombiner::TryPushdownPrefixFilter(TableFilterSet &tab
...
-	prefix_string[prefix_string.size() - 1]++;
-	auto upper_bound = make_uniq<ConstantFilter>(ExpressionType::COMPARE_LESSTHAN, Value(prefix_string));
 	table_filters.PushFilter(column_index, std::move(lower_bound));
-	table_filters.PushFilter(column_index, std::move(upper_bound));
+	prefix_string[prefix_string.size() - 1]++;
+	if (Utf8Proc::Analyze(prefix_string.c_str(), prefix_string.size()) != UnicodeType::INVALID) {
+		auto upper_bound = make_uniq<ConstantFilter>(ExpressionType::COMPARE_LESSTHAN, Value(prefix_string));
+		table_filters.PushFilter(column_index, std::move(upper_bound));
+	}
 	return FilterPushdownResult::PUSHED_DOWN_FULLY;
```
Comment (samansmink) [inline src/optimizer/filter_combiner.cpp]: this feels off, returning `FilterPushdownResult::PUSHED_DOWN_FULLY` when the table filter is not pushed

File: src/optimizer/filter_combiner.cpp [hunk 2]
```diff
@@ -397,10 +398,12 @@ FilterPushdownResult FilterCombiner::TryPushdownPrefixFilter(TableFilterSet &tab
 	auto &column_index = column_ids[column_ref.binding.column_index];
 	//! Replace prefix with a set of comparisons
 	auto lower_bound = make_uniq<ConstantFilter>(ExpressionType::COMPARE_GREATERTHANOREQUALTO, Value(prefix_string));
-	prefix_string[prefix_string.size() - 1]++;
-	auto upper_bound = make_uniq<ConstantFilter>(ExpressionType::COMPARE_LESSTHAN, Value(prefix_string));
 	table_filters.PushFilter(column_index, std::move(lower_bound));
-	table_filters.PushFilter(column_index, std::move(upper_bound));
+	prefix_string[prefix_string.size() - 1]++;
```
Comment (Mytherin) [inline src/optimizer/filter_combiner.cpp]: Instead of just incrementing the last byte (which might result in invalid UTF8) - could we find the next UTF8 codepoint?

This would look something like this:

```cpp
// find the start of the last codepoint
idx_t last_codepoint_start;
for(last_codepoint_start = prefix_string.size(); last_codepoint_start > 0; last_codepoint_start--) {
    if (IsCharacter(prefix_string[last_codepoint_start - 1])) {
        break;
    }
}
D_ASSERT(last_codepoint_start > 0);
last_codepoint_start--;
int codepoint_size;
auto codepoint = Utf8Proc ::UTF8ToCodepoint(prefix_string.c_str() + last_codepoint_start, codepoint_size);
auto next_codepoint = codepoint + 1;
if (next_codepoint >= 0xD800 && next_codepoint <= 0xDFFF) {
    // next codepoint falls within surrogate range increment to next valid character
    next_codepoint = 0xE000;
}
char next_codepoint_text[4];
int next_codepoint_size;
if (!Utf8Proc::CodepointToUtf8(codepoint + 1, next_codepoint_size, next_codepoint_text)) {
        // invalid codepoint
		return FilterPushdownResult::NO_PUSHDOWN;
}
string upper_bound = prefix_string.substr(0, last_codepoint_start) + string(next_codepoint_text, next_codepoint_size);
```

Comment (Mytherin) [reply src/optimizer/filter_combiner.cpp]: In UTF8 a higher codepoint is always lexicographically higher than a lower codepoint, we can verify this using DuckDB itself, e.g.:

```sql
select codepoint, try(chr(codepoint::INTEGER)) unicode
from range(0, '0x10FFFF'::BIGINT + 1) t(codepoint)
where unicode is not null
qualify codepoint < lag(codepoint) over (order by unicode);
```

Comment (Mytherin) [reply src/optimizer/filter_combiner.cpp]: We can trigger the "invalid codepoint" codepath in a test using a prefix filter on `chr('0x10FFFF')` which is the highest unicode codepoint possible, and the surrogate range codepath using a filter on `chr('0xD7FF')`

**Review by Mytherin — COMMENTED** [review]
Thanks for the fix! Left a comment on how to improve this fix. Can we also target this towards `v1.4-andium`?

File: src/optimizer/filter_combiner.cpp [hunk 3]
```diff
@@ -282,6 +284,32 @@ static bool SupportedFilterComparison(ExpressionType expression_type) {
 	}
 }
 
+bool FilterCombiner::FindNextLegalUTF8(string &prefix_string) {
+	// find the start of the last codepoint
+	idx_t last_codepoint_start;
+	for (last_codepoint_start = prefix_string.size() - 1; last_codepoint_start >= 0; last_codepoint_start--) {
```
Comment (Mytherin) [inline src/optimizer/filter_combiner.cpp]: `last_codepoint_start >= 0` is always true because `last_codepoint_start` is an `idx_t` - this will instead underflow (and loop infinitely) if this does not find a character. Could you modify this to the following loop for safety purposes - otherwise we might get infinite loops if invalid UTF8 somehow enters the system:

```cpp
idx_t last_codepoint_start;
for(last_codepoint_start = prefix_string.size(); last_codepoint_start > 0; last_codepoint_start--) {
    if (IsCharacter(prefix_string[last_codepoint_start - 1])) {
        break;
    }
}
if (last_codepoint_start == 0) {
    throw InvalidInputException("Invalid UTF8 found in string \"%s\"", prefix_string);
}
last_codepoint_start--;
```

**Review by Mytherin — COMMENTED** [review]
Thanks for the changes! Looks good - one comment

File: src/optimizer/filter_combiner.cpp (hunk 3 above)
Comment (flashmouse) [reply src/optimizer/filter_combiner.cpp]: Thanks for reply! I missed that ``last_codepoint_start`` is unsigned. 

And I have another one question: 
I want to keep find the legal utf8 codepoint until we find the first one or all bytes in ``prefix_string`` are processed, do you think it's correct and useful?

Comment (Mytherin) [reply src/optimizer/filter_combiner.cpp]: I guess that would be possible yeah - although I think the last codepoint is very rarely used

**Comment by Mytherin** [comment]
Thanks!
