### PR TITLE
Fuzzer fixes

### LINKED ISSUE #460: ABORT THROWN BY INTERNAL EXCEPTION: Calling StringValue::Get on a NULL value
Issue found by DuckFuzz on git commit hash [6b06e](https://github.com/duckdb/duckdb/commit/6b06ebe56191031e57ed890f3bd3624a21c6870e) using seed 1069239220.
### To Reproduce
```sql
call dbgen(sf=0.1);
SELECT lead(c9, c18) OVER (ORDER BY 2399 DESC NULLS FIRST ROWS BETWEEN c2 PRECEDING AND #10 FOLLOWING) FROM (SELECT c4 FROM json_execute_serialized_sql(NULL) AS t5(c1, c2, c3, c4)) AS t6 , (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (VALUES (3579, 426, main.list_value(), 5272, CAST('290309-12-22 (BC) 00:00:00' AS TIMESTAMP_S), '356f1b18-7a3d-417e-97eb-710eae92f600', NULL, 634), (CAST('290309-12-22 (BC) 00:00:00' AS TIMESTAMP), NULL, 1138, NULL, NULL, 8922, 1726, 5539), (main.list_value(42.0, CAST('nan' AS DOUBLE), 1e1000, -1e1000, NULL, -42.0), 'enum_69999', 'dcf24776-2f79-4878-a175-8daabf453cd0', '9d4c7f67-bdcb-46c5-bd44-1d04be3b94ab', NULL, 9021, 1124, 6294)) AS valueslist) AS valueslist) AS valueslist) AS valueslist) AS valueslist) AS valueslist) AS valueslist) AS valueslist) FULL JOIN lineitem AS t23(c7, c8, c9, c10, c11, c12, c13, c14, c15, c16, c17, c18, c19, c20, c21, c22) ON (c8)

```

### Error Message
```
ABORT THROWN BY INTERNAL EXCEPTION: Calling StringValue::Get on a NULL value
```

### LINKED ISSUE #1138: ABORT THROWN BY INTERNAL EXCEPTION: Failed to bind column reference "timestamp" [7.3] (bindings: [1.0 1.1 7.1 7.2])
Issue found by SQLSmith on git commit hash [72080](https://github.com/duckdb/duckdb/commit/7208022cac983300712db555f39265eed04a655d) using seed 1051638785.
### To Reproduce
```sql
create table all_types as select * exclude(small_enum, medium_enum, large_enum) from test_all_types() limit 0;
SELECT count_star() OVER (PARTITION BY ref_1.hugeint, ref_1."timestamp" ORDER BY subq_0.c0) AS c0 FROM (SELECT ref_0."int" AS c0, ref_0.timestamp_s AS c1 FROM main.all_types AS ref_0 WHERE ref_0."varchar") AS subq_0 INNER JOIN main.all_types AS ref_1 ON ((subq_0.c1 = ref_1.timestamp_s)) WHERE (ref_1."time" IS NOT NULL)

```

### Error Message
```
ABORT THROWN BY INTERNAL EXCEPTION: Failed to bind column reference "timestamp" [7.3] (bindings: [1.0 1.1 7.1 7.2])
```

### LINKED ISSUE #1142: ABORT THROWN BY INTERNAL EXCEPTION: Failed to bind column reference "varchar" [31.1] (bindings: [1.0 16.0 22.0 22.1 28.1 30.2 25.1 64.0 63.0 62.0 74.2])
Issue found by SQLSmith on git commit hash [72080](https://github.com/duckdb/duckdb/commit/7208022cac983300712db555f39265eed04a655d) using seed 430532173.
### To Reproduce
```sql
create table all_types as select * exclude(small_enum, medium_enum, large_enum) from test_all_types() limit 0;
SELECT arg_min(CAST(ref_19."varchar" AS VARCHAR), CAST(ref_3."varchar" AS VARCHAR)) OVER (PARTITION BY ref_23."bit" ORDER BY ref_6.ubigint) FROM (SELECT (SELECT "time" FROM main.all_types LIMIT 1 OFFSET 4) AS c1 FROM main.all_types AS ref_0 WHERE ref_0."varchar") AS subq_0 INNER JOIN (SELECT ref_1."varchar" AS c5 FROM main.all_types AS ref_1 LEFT JOIN main.all_types AS ref_2 ON ((ref_1."varchar" !~~* ref_2."varchar")) WHERE (ref_2."varchar" ~~* ref_2."varchar")) AS subq_1 INNER JOIN main.all_types AS ref_3 ON ((subq_1.c5 ~~ ref_3."varchar")) ON ((ref_3."varchar" ~~ subq_1.c5)) INNER JOIN main.all_types AS ref_4 RIGHT JOIN main.all_types AS ref_5 RIGHT JOIN main.all_types AS ref_6 ON ((ref_6."varchar" ^@ ref_6."varchar")) ON ((ref_6.timestamp_ms IS NOT NULL)) INNER JOIN main.all_types AS ref_7 INNER JOIN main.all_types AS ref_8 ON ((ref_7.dec_4_1 = ref_8.dec_4_1)) LEFT JOIN main.all_types AS ref_9 RIGHT JOIN main.all_types AS ref_10 ON ((ref_9.timestamp_array = ref_10.timestamp_array)) ON ((ref_10."varchar" ^@ ref_8."varchar")) INNER JOIN main.all_types AS ref_11 RIGHT JOIN main.all_types AS ref_12 ON ((ref_11."float" = ref_12."float")) LEFT JOIN main.all_types AS ref_13 ON ((ref_11."varchar" ~~~ ref_12."varchar")) ON ((CAST(NULL AS VARCHAR) ~~~ ref_7."varchar")) ON (((((ref_8."varchar" !~~ ref_8."varchar") AND (ref_6."varchar" ~~~ ref_12."varchar")) OR (ref_9."varchar" ~~ CAST(NULL AS VARCHAR))) AND (ref_6."varchar" ^@ ref_8."varchar") AND (ref_11.hugeint IS NOT NULL))) RIGHT JOIN (SELECT (SELECT bool FROM main.all_types LIMIT 1 OFFSET 6) AS c4) AS subq_2 ON ((ref_9."varchar" !~~ ref_8."varchar")) ON ((ref_3."int" = ref_10."int")) INNER JOIN (SELECT 41 AS c0 FROM main.all_types AS ref_15 RIGHT JOIN main.all_types AS ref_16 ON ((ref_15."varchar" = ref_16."varchar"))) AS subq_3 INNER JOIN (SELECT ref_17.timestamp_s AS c5 FROM main.all_types AS ref_17) AS subq_4 ON ((subq_3.c0 IS NULL)) INNER JOIN main.all_types AS ref_18 LEFT JOIN main.all_types AS ref_19 INNER JOIN main.all_types AS ref_20 INNER JOIN main.all_types AS ref_21 ON (((SELECT "varchar" FROM main.all_types LIMIT 1 OFFSET 4) ~~~ ref_21."varchar")) ON ((ref_21."timestamp" IS NULL)) ON ((ref_19."varchar" ~~~ ref_20."varchar")) RIGHT JOIN main.all_types AS ref_22 LEFT JOIN main.all_types AS ref_23 ON (1) ON (0) ON ((0 OR (ref_20."varchar" !~~* ref_19."varchar") OR ((EXISTS(SELECT (SELECT tinyint FROM main.all_types LIMIT 1 OFFSET 1) AS c0 FROM main.all_types AS ref_24 WHERE (ref_23."bigint" IS NOT NULL) LIMIT 110) OR (ref_23.timestamp_array IS NULL)) AND (ref_21."varchar" ^@ ref_21."varchar")))) ON ((ref_9."varchar" ~~* chr(CAST(ref_18."int" AS INTEGER)))) WHERE (ref_12."varchar" ^@ ref_20."varchar")

```

### Error Message
```
ABORT THROWN BY INTERNAL EXCEPTION: Failed to bind column reference "varchar" [31.1] (bindings: [1.0 16.0 22.0 22.1 28.1 30.2 25.1 64.0 63.0 62.0 74.2])
```

### LINKED ISSUE #1169: ABORT THROWN BY INTERNAL EXCEPTION: Failed to bind column reference "varchar" [3.1] (bindings: [1.0 2.2 2.3 0.0])
Issue found by SQLSmith on git commit hash [312b9](https://github.com/duckdb/duckdb/commit/312b9954507386305544a42c4f43c2bd410a64cb) using seed 496764688.
### To Reproduce
```sql
create table all_types as select * exclude(small_enum, medium_enum, large_enum) from test_all_types() limit 0;
SELECT NULL FROM (SELECT ref_0."int" AS c3 FROM main.all_types AS ref_0 RIGHT JOIN main.all_types AS ref_1 INNER JOIN main.all_types AS ref_2 ON ((ref_1."int" = ref_2."int")) INNER JOIN main.all_types AS ref_3 ON ((ref_2.tinyint = ref_3.tinyint)) ON ((ref_2."varchar" ~~* ref_3."varchar")) WHERE (ref_2."smallint" IS NOT NULL)) AS subq_0

```

### Error Message
```
ABORT THROWN BY INTERNAL EXCEPTION: Failed to bind column reference "varchar" [3.1] (bindings: [1.0 2.2 2.3 0.0])
```

### PR DESCRIPTION
**Pull request by Tmonster**
fixes https://github.com/duckdb/duckdb-fuzzer/issues/1138
fixes https://github.com/duckdb/duckdb-fuzzer/issues/1142
fixes https://github.com/duckdb/duckdb-fuzzer/issues/460
fixes https://github.com/duckdb/duckdb-fuzzer/issues/1169

and potentially many more?

This is an issue with the column_lifetime analyzer. Previously, the column lifetime analyzer would not visit the operator expressions of logical comparison joins or filters before extracting unused columns. 

So any expression only present in the filter or join condition (but no where else in the plan) ends up in the unused_bindings binding_set. When the lifetime analyzer recurses into the children, the expression in the filter/join_condition is added to the `referenced_columns`. When the right_projection_map is generated, expressions in the join condition aren't included. This leads to missing column bindings. Then when we replace the operator with a logical empty result and copy the bindings over, we end up missing some bindings and therefore the binding error.

I think there are a number of fuzzer issues suffering from the same issue.

### CODE REVIEW

File: src/optimizer/column_lifetime_analyzer.cpp [hunk 1]
```diff
@@ -72,13 +74,17 @@ void ColumnLifetimeAnalyzer::VisitOperator(LogicalOperator &op) {
...
 		}
-		// now, for each of the columns of the RHS, check which columns need to be projected
+		// visit current operator expressions so they are added to the referenced_columns
+		LogicalOperatorVisitor::VisitOperatorExpressions(op);
+
 		column_binding_set_t unused_bindings;
+		auto old_op_bindings = op.GetColumnBindings();
 		ExtractUnusedColumnBindings(op.children[1]->GetColumnBindings(), unused_bindings);
 
 		// now recurse into the filter and its children
```
Comment (Mytherin) [inline src/optimizer/column_lifetime_analyzer.cpp:90]: `StandardVisitOperator` also calls `LogicalOperatorVisitor::VisitOperatorExpressions` - perhaps this should then be replaced with only `LogicalOperatorVisitor::VisitOperatorChildren`?

File: src/optimizer/column_lifetime_analyzer.cpp [hunk 2]
```diff
@@ -118,6 +124,8 @@ void ColumnLifetimeAnalyzer::VisitOperator(LogicalOperator &op) {
 		if (everything_referenced) {
 			break;
 		}
+		// first visit operator expressions to populate referenced columns
+		LogicalOperatorVisitor::VisitOperatorExpressions(op);
 		// filter, figure out which columns are not needed after the filter
 		column_binding_set_t unused_bindings;
 		ExtractUnusedColumnBindings(op.children[0]->GetColumnBindings(), unused_bindings);
```
Comment (Mytherin) [inline src/optimizer/column_lifetime_analyzer.cpp:131]: Same here - if we are explicitly calling `LogicalOperatorVisitor::VisitOperatorExpressions` we shouldn't need to call `StandardVisitOperator`

**Review by Mytherin — COMMENTED** [review]
Thanks for the fix! LGTM - one minor comment:

**Comment by Mytherin** [comment]
Thanks!
