### PR TITLE
Relax list_reduce Signature Restrictions

### LINKED ISSUE #17009: Unnecessarily restrictive signature of `list_reduce(..., initial)`
### What happens?

The new `list_reduce(..., initial)` has the signature

```
list_reduce(seq: T[], fun: (T, T) -> T, initial: T)
``` 
instead of the "correct" signature  
```
list_reduce(seq: T[], fun: (S, T) -> S, initial: S)
```
which means it can't do anything that couldn't already be done with 

```
list_reduce([initial] + seq, fun)
```
(the latter even has the advantage that you don't need to guess whether `fun` or `initial` come first).

In particular, the most simple fold, the identity on lists, isn't possible with the new `initial` argument:

```sql
select list_reduce([1], (x, y) -> x || [y], [])
``` 
```
Binder Error: Cannot concatenate types INTEGER and INTEGER[] - an explicit cast is required
```

and the unnecessarily inserted casts to enforce an all-Ts-signature produce "obviously wrong" results:

```sql
select
    y1: list_reduce([0], (x, y) -> if(len(x::VARCHAR) - 1, true, false), false), -- should be `true`, is `0`
    y2: list_reduce([2], (x, y) -> ['3.1', '1.4'][y], 1) -- should be `1.4` is `1`
```
```
┌───────┬───────┐
│  y1   │  y2   │
│ int32 │ int32 │
├───────┼───────┤
│     0 │     1 │
└───────┴───────┘
```

Given that the new `list_reduce(..., initial)` is logically just a rewrite of `list_reduce([initial] + ...)` it is not surprising that the latter produces the same results. That's just another reason that the `initial` version _shouldn't_ just be a rewrite though: In the rewritten form you can at least understand what's going on because `[initial] + seq` must obviously be assigned _some_ type and it is excusable that the type inference for that choice doesn't consider the lambda function. With an explicit `initial` argument, on the other hand, one would intuitively expect that the types of `initial` and `seq` need not be in any relation and thus be surprised from resulting errors (or, worse, wrong results). In fact, I believe  

```sql
list_reduce(<SeqExpr>, <LambdaArgAndValueExpr>, <InitExpr>)
```
should have the same type as the "super type" for `<InitExpr>` and 
```
<LambdaValueExpr>(<SeqExpr>[0], <InitExpr>)
```

If implementing that isn't as easy as I imagine, I'd argue that one should simply take the type of `<InitExpr>` as given, and throw if `<LambdaValueExpr>(<SeqExpr>[0], <InitExpr>)` isn't implicit-castable to that.

In short, I think the danger of users getting wrong results without noticing (or spending time figuring out what's happening when they do notice) currently outweights the benefit of the 2 characters saved from the new synax in cases where the two-argument function was already sufficient.

Finally, I assume that the unnecessary casts play part in the internal error reported at https://github.com/duckdb/duckdb/issues/17008

### To Reproduce

.

### OS:

Linux

### DuckDB Version:

'1.3.0-dev1976'

### DuckDB Client:

Python

### Hardware:

.

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [x] Yes, I have

### PR DESCRIPTION
**Pull request by d-justen**
fixes https://github.com/duckdblabs/duckdb-internal/issues/6806
fixes https://github.com/duckdblabs/duckdb-internal/issues/4592
fixes https://github.com/duckdb/duckdb/issues/17009

This PR relaxes the `list_reduce` type constraints in the sense that the accumulator type is derived from the explicit initial value instead of the list child type.

The function signature now is `list_reduce(seq: T[], fun: (S', T) -> S', initial: S)`. If `initial` has a different type than the return type of the lambda function, their common super type is used as accumulator and lambda result type. As this is a cyclical dependency, we now have to bind the lambda function twice for list result. Once with an accumulator with the type of `initial` to compute the lambda's return type, and then again with `initial` and the return type's common super type, which gives us the lambda function with the final signature.

### CODE REVIEW

**Comment by soerenwolfers** [comment]
Thanks for working on this. Is the special casing for numerical types really necessary? DuckDB already suffers from having at least 4 different sets of casting rules (see https://github.com/duckdb/duckdb/issues/15168#issuecomment-3679288602) and it sounds like this would introduce the next set?

**Review by lnkuiper — COMMENTED** [review]
Thanks for the PR! Looks good - this should now follow the general implicit casting rules. I have the same question as above, however. Why should this only work for numerics?

**Comment by d-justen** [comment]
So the idea was to do upcasting for convenience, e.g., so that we can prevent overflows. But if you think that the confusion this causes weighs higher than the convenience it brings, I can also just remove that.

**Comment by lnkuiper** [comment]
The upcasting-only logic should be handled in `LogicalType::TryGetMaxLogicalType` already, so I think this check can be removed :)

**Comment by d-justen** [comment]
I have changed the implicit casting now to apply for all data types. One thing that I noticed and that might be a little weird though.

```sql
SELECT list_reduce([0], lambda acc, x: if(len(acc::VARCHAR) - 1, true, false), false);
-- returns 0, not true
```

So what happens here is that the accumulator is an integer (as the common super type of bool and integer), which is casted VARCHAR '0'. With implicit casting only for numeric types, the VARCHAR cast would result in 'false' because of the boolean accumulator, and thus, this would have returned true. Do you think this way of casting makes more sense anyway?

**Comment by lnkuiper** [comment]
Hmm, I'm not sure if that makes sense. How are we getting bool x integer here? The return type of the `if` should be bool, and the initial value is also bool. The varchar cast should be just an intermediate type - not affect the accumulator type.

EDIT: also:
```sql
select range + true from range(10);
Binder Error:
No function matches the given name and argument types '+(BIGINT, BOOLEAN)'. You might need to add explicit type casts.
```

This errors on not being able to unify integer/bool, I feel like that makes sense

**Comment by soerenwolfers** [comment]
> Hmm, I'm not sure if that makes sense. How are we getting bool x integer here? The return type of the `if` should be bool, and the initial value is also bool. The varchar cast should be just an intermediate type - not affect the accumulator type.

@d-justen accidentally included the list element type in the the `GetMaxLogicalType`, when it should only include the initial type and the lambda output type. 


> 
> EDIT: also:
> 
> ```sql
> select range + true from range(10);
> Binder Error:
> No function matches the given name and argument types '+(BIGINT, BOOLEAN)'. You might need to add explicit type casts.
> ```
> 
> This errors on not being able to unify integer/bool, I feel like that makes sense

Thats one of the differences between two of the three different versions of implicit casting that are currently extant in DuckDB. See https://github.com/duckdb/duckdb/issues/15168#issuecomment-3679288602 (what you first suggested is type (III) there, what you now want is 
type (I).

**Comment by d-justen** [comment]
> @d-justen accidentally included the list element type in the the `GetMaxLogicalType`, when it should only include the initial type and the lambda output type.

Yes, I have realized that I thought about the type deduction in a wrong way. I think the tricky part here is the cyclic dependency that the lambda `acc` parameter type depends on the common super type of the lambda result type and `initial` but the lambda result type depends on `acc` as well. So I think to support more than type equality for the lambda return type/`acc` and `initial`, we would have to bind the lambda function twice. Once with the `initial` type as `acc`, and then with the actual `acc` type.

File: extension/core_functions/scalar/list/list_reduce.cpp [hunk 1]
```diff
@@ -191,26 +224,20 @@ unique_ptr<FunctionData> ListReduceBind(ClientContext &context, ScalarFunction &
...
+		auto &bound_lambda_expr = arguments[1]->Cast<BoundLambdaExpression>();
+		auto &lambda_return_type = bound_lambda_expr.lambda_expr->return_type;
+		accumulator_type = ResolveReduceAccumulatorType(context, initial_value_type, lambda_return_type);
+		arguments[2] = BoundCastExpression::AddCastToType(context, std::move(arguments[2]), accumulator_type);
+	} else {
+		auto &bound_lambda_expr = arguments[1]->Cast<BoundLambdaExpression>();
+		auto list_child_type = LambdaFunctions::DetermineListChildType(arguments[0]->return_type);
+		auto &lambda_return_type = bound_lambda_expr.lambda_expr->return_type;
+		if (!LogicalType::TryGetMaxLogicalType(context, list_child_type, lambda_return_type, accumulator_type)) {
+			throw BinderException("No common super type between list element and lambda return type");
```
Comment (lnkuiper) [inline extension/core_functions/scalar/list/list_reduce.cpp]: Could you improve this error by printing the types of the list element and lambda return?

File: extension/core_functions/scalar/list/list_reduce.cpp [hunk 2]
```diff
@@ -221,42 +248,23 @@ unique_ptr<FunctionData> ListReduceBind(ClientContext &context, ScalarFunction &
 	auto has_index = bound_lambda_expr.parameter_count == 3;
 
 	auto cast_lambda_expr =
-	    BoundCastExpression::AddCastToType(context, std::move(bound_lambda_expr.lambda_expr), list_child_type);
+	    BoundCastExpression::AddCastToType(context, std::move(bound_lambda_expr.lambda_expr), accumulator_type);
 	if (!cast_lambda_expr) {
-		throw BinderException("Could not cast lambda expression to list child type");
+		throw BinderException("Could not cast lambda expression to accumulator type");
```
Comment (lnkuiper) [inline extension/core_functions/scalar/list/list_reduce.cpp]: Could you also add both types to this error message?

**Review by lnkuiper — CHANGES_REQUESTED** [review]
Thanks for the changes! I just have two small requests, then this is ready to go

**Review by lnkuiper — APPROVED** [review]
Thanks!
