### PR TITLE
comparison of nested types returns true or false always (even with nulls)

### LINKED ISSUE #13924: Unexpected result when comparing `STRUCT` with `INET`
### What happens?

Consider the following test case generated by my fuzzer. There should be an issue in either the second query or the third, since the second query return `NULL`, and thus the third query should return an empty table. However, one row is fetched.

I built duckdb with `CORE_EXTENSIONS='inet' GEN=ninja make`. It could also be triggered by nightly build of duckdb-java.

### To Reproduce

```sql

CREATE TABLE  t1(c0 INT, c1 INET);
INSERT INTO t1(c0, c1) VALUES (1, '192.168.1.1');

SELECT * FROM t1; -- 1 192.168.1.1
SELECT ((NULL, t1.c0, NULL)<>(t1.c1)) FROM t1; -- NULL
SELECT * FROM t1 WHERE ((NULL, t1.c0, NULL)<>(t1.c1));
-- Expected: empty
-- Actual: 1 192.168.1.1

-- original test case found by TLP
SELECT * FROM t1 WHERE ((NULL, t1.c0, NULL)<>(t1.c1)) UNION ALL SELECT * FROM t1 WHERE (NOT ((NULL, t1.c0, NULL)<>(t1.c1))) UNION ALL SELECT * FROM t1 WHERE ((((NULL, t1.c0, NULL)<>(t1.c1))) IS NULL);
-- 2 rows (unexpected)
```

### OS:

Ubuntu 22.04

### DuckDB Version:

v1.1.1-dev116 a2c119f76d

### DuckDB Client:

CLI

### Hardware:

_No response_

### Full Name:

Suyang Zhong

### Affiliation:

NUS

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by Tmonster**
fixes https://github.com/duckdblabs/duckdb-internal/issues/3063
fixes https://github.com/duckdb/duckdb/issues/13924

Postgres teats nulls in nested types as equal and orderable (see examples below). In duckdb v1.1.0 we did the same for comparisons in `where` conditions. In select conditions, however, we would return `NULL` if there was a NULL somewhere in the nested object. This would lead to inconsistent results, i.e 

```
select a<>b from VALUES ((NULL, 1, NULL), (5, 6, 7)) t(a, b);
```
would return `NULL`

while 
```
select 1 from VALUES ((NULL, 1, NULL), (5, 6, 7)) t(a, b) where a<>b;
```
would return `1` even though the where condition evaluates to `NULL`

The fix I came up with is to copy the validity mask from `ComparesNotNull(leftv, rightv, result_validity, count)` in the `NestedComparisonExecutor`. This validity mask stores `NULL` results if a value in a nested type column is `NULL`. In these cases `NULL` is correct since `NULL` compared with anything is `NULL`

After the `ComparisonSelector` is called, we set all rows to valid if they were valid after the `ComparesNotNull` call. Normally the `ComparisonSelector` sets rows to `NULL` if a value in the nested types is `NULL`, which is what we want to prevent. Setting the rows back to valid ensures that if two non-null nested values are compared, there is always a non-null boolean result

Postgres behavior
```
create type foo as (a integer, b integer);
create type buzz as (c integer, d integer);
create table t3 (a foo);
create table t4 (b buzz);
insert into t3 values (row(1, NULL), row(NULL, NULL), row(2, 2));
insert into t3 values (row(4, NULL), row(NULL, NULL), row(2, 2));
select (a).a, (b).a from t3, t4;
select a, b, a=b from t3, t4 where a = b;
 --   a    |    b    | ?column?
-- ---------+---------+----------
 -- (10,10) | (10,10) | t
 -- (,)     | (,)     | t
```

### CODE REVIEW

File: src/common/vector_operations/comparison_operators.cpp [hunk 1]
```diff
@@ -182,6 +182,10 @@ static void NestedComparisonExecutor(Vector &left, Vector &right, Vector &result
 	if (!leftv.validity.AllValid() || !rightv.validity.AllValid()) {
 		ComparesNotNull(leftv, rightv, result_validity, count);
 	}
+	ValidityMask copy;
+	copy.SetAllValid(count);
+	copy.Copy(result_validity, count);
```
Comment (taniabogatsch) [inline src/common/vector_operations/comparison_operators.cpp:187]: Do we need `SetAllValid`, if we are immediately copying `result_validity` into it?
```cpp
	inline void Copy(const TemplatedValidityMask &other, idx_t count) {
		target_count = count;
		if (other.AllValid()) {
			validity_data = nullptr;
			validity_mask = nullptr;
		} else {
			validity_data = make_buffer<ValidityBuffer>(other.validity_mask, count);
			validity_mask = validity_data->owned_data.get();
		}
	}
```

File: src/common/vector_operations/comparison_operators.cpp [hunk 2]
```diff
@@ -190,12 +194,19 @@ static void NestedComparisonExecutor(Vector &left, Vector &right, Vector &result
 	for (idx_t i = 0; i < match_count; ++i) {
 		const auto idx = true_sel.get_index(i);
 		result_data[idx] = true;
+		// if the row was valid during the null check, set it to valid here as well
+		if (copy.RowIsValid(idx)) {
+			result_validity.SetValid(idx);
+		}
```
Comment (taniabogatsch) [inline src/common/vector_operations/comparison_operators.cpp:200]: Just a clarification question: `copy` contains the `result_validity` before `ComparisonSelector::Select`, which possibly overwriters some fields to invalid. Thus, can we reset them back to valid?

Nit: Maybe this will be clearer if we rename `copy` to something like `original_mask`?

**Review by taniabogatsch — COMMENTED** [review]
Nice! I left two comments.

File: src/common/vector_operations/comparison_operators.cpp (hunk 2 above)
Comment (taniabogatsch) [reply src/common/vector_operations/comparison_operators.cpp:200]: EDIT: I just saw your updated PR description. Makes sense to me. 👍 Should we rename `copy` to `original_mask` or `null_comparison_result`, or something similar?

File: test/sql/types/struct/unnamed_struct_comparison.test [hunk 3]
```diff
@@ -64,4 +64,35 @@ select 1 from VALUES ((NULL, 1, NULL), (5, 6, 7), (NULL, 2), (4, 5)) t(a, b, c,
 query II
 select a<>b, c<>d from VALUES ((NULL, 1, NULL), (5, 6, 7), (NULL, 2), (4, 5)) t(a, b, c, d) where a<>b and c<>d;
 ----
-true	true
\ No newline at end of file
+true	true
+
+# original issue from author
+
+require inet
```
Comment (hawkfish) [inline test/sql/types/struct/unnamed_struct_comparison.test:71]: Can we put this in a separate file? That way any tests that get added later will run even if `inet` is not available.

File: src/common/vector_operations/comparison_operators.cpp [hunk 4]
```diff
@@ -182,9 +182,9 @@ static void NestedComparisonExecutor(Vector &left, Vector &right, Vector &result
 	if (!leftv.validity.AllValid() || !rightv.validity.AllValid()) {
 		ComparesNotNull(leftv, rightv, result_validity, count);
 	}
-	ValidityMask copy;
-	copy.SetAllValid(count);
-	copy.Copy(result_validity, count);
+	ValidityMask original_mask;
```
Comment (hawkfish) [inline src/common/vector_operations/comparison_operators.cpp:185]: This reads to me like all that changed was renaming `copy` to `original_mask`... what am I missing?

File: test/sql/types/list/list_null_members.test [hunk 5]
```diff
@@ -30,55 +30,55 @@ SELECT lhs.i, rhs.i,
...
-[NULL, 2]	[NULL, 2]	NULL	NULL	NULL	NULL	NULL	NULL	True	False
-[NULL, 2]	[NULL, NULL]	NULL	NULL	NULL	NULL	NULL	NULL	False	True
-[NULL, NULL]	NULL	NULL	NULL	NULL	NULL	NULL	NULL	False	True
-[NULL, NULL]	[1]	NULL	NULL	NULL	NULL	NULL	NULL	False	True
-[NULL, NULL]	[1, 2]	NULL	NULL	NULL	NULL	NULL	NULL	False	True
-[NULL, NULL]	[1, NULL]	NULL	NULL	NULL	NULL	NULL	NULL	False	True
-[NULL, NULL]	[NULL]	NULL	NULL	NULL	NULL	NULL	NULL	False	True
-[NULL, NULL]	[NULL, 2]	NULL	NULL	NULL	NULL	NULL	NULL	False	True
-[NULL, NULL]	[NULL, NULL]	NULL	NULL	NULL	NULL	NULL	NULL	True	False
+NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	true	false
```
Comment (hawkfish) [inline test/sql/types/list/list_null_members.test:33]: Not a big thing, but can we restore the Title case for True/False to make the diff clearer?

**Review by taniabogatsch — APPROVED** [review]

**Review by hawkfish — APPROVED** [review]

**Comment by hannes** [comment]
Thanks!
