### PR TITLE
[Python] Add `Expression` class

### LINKED ISSUE #8359: Prepared statement causing "Out of Range Error"
### What happens?

When executing a prepared statement using the Python API leads to a "Out of Range Error" when the following conditions are met:
- The expression contains only literals
- The precision of the result is larger than the precision of the inputs.

### To Reproduce

```python
import duckdb
con = duckdb.connect(":default:")
con.execute("SELECT ? + ?", [100, 100]).fetchall()
```

```
---------------------------------------------------------------------------
OutOfRangeException                       Traceback (most recent call last)
      1 import duckdb
      2 con = duckdb.connect(":default:")
----> 3 con.execute("SELECT ? + ?", [100, 100]).fetchall()

OutOfRangeException: Out of Range Error: Overflow in addition of INT8 (100 + 100)!
```

However, running the prepared statement via CLI works fine:
```sql
PREPARE S1 AS SELECT ? + ?;
EXECUTE S1(100, 100);
┌───────────┐
│ ($1 + $2) │
╞═══════════╡
│       200 │
└───────────┘
```

### OS:

MacOS aarch64

### DuckDB Version:

0.8.1

### DuckDB Client:

Python

### Full Name:

Nicolas Camenisch

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Tishj**
This PR does not directly enable new functionality.
But it does allow users to build up expressions programmatically.

For example, given this relation:
```py
rel = duckdb.sql("""
	select
		1 as a,
		2 as b,
		3 as c,
		3 as d
""")
```

These are equivalent:
(using project)
```py
rel2 = rel.project('a >= b, b >= a, c >= d')
```

(using expressions + `select`)
```py
col1 = ColumnExpression('a')
col2 = ColumnExpression('b')
col3 = ColumnExpression('c')
col4 = ColumnExpression('d')

# Greater than or equal
expr1 = col1 >= col2
expr2 = col2 >= col1
expr3 = col3 >= col4
rel2 = rel.select(expr1, expr2, expr3)
```

### Expression creation

- ##### ConstantExpression(val: pyduckdb.Value)
  Create an expression containing a single value.
- ##### ColumnExpression(name: str)
  Create an expression that references a column.
- ##### FunctionExpression(function: str, *cols: Expression)
  Create an expression that represents a (scalar) function call
- ##### CaseExpression(condition: Expression, value: Expression)
  Create an expression that represents `CASE WHEN <condition> THEN <value> END` 
- ##### StarExpression(exclude: Optional[List[str]])
  Create a `*` expression, with an optional EXCLUDE list

### Expression methods

- ##### `alias(name: str)`
  Set the alias for the expression
- ##### `when(condition: Expression, value: Expression)`
  Add another `WHEN <condition> THEN <value>` option to an existing CaseExpression
- ##### `otherwise(value: Expression)`
  Add/replace the `ELSE <value>` on an existing CaseExpression
- ##### `cast(type: DuckDBPyType)`
  Add a cast to the provided type on top of the existing expression

### Future work:

Adding a method that creates Expressions from SQL might be a nice addition, so you can generate expressions and then alter the expressions programmatically.

Using the `core_functions` json files, it might be possible to generate static methods for every function, producing an Expression using the FunctionExpression static method.

### Fixes

Edit (Gabor): fixes #8359

### CODE REVIEW

**Comment by hannes** [comment]
Maybe @Tmonster can have a look since he implemented expressions in R

File: tools/pythonpkg/src/pyexpression.cpp [hunk 1]
```diff
@@ -0,0 +1,345 @@
...
+	return make_shared<DuckDBPyExpression>(std::move(expr));
+}
+
+shared_ptr<DuckDBPyExpression> DuckDBPyExpression::When(const DuckDBPyExpression &condition,
+                                                        const DuckDBPyExpression &value) {
+	AssertCaseExpression();
+	auto expr_p = expression->Copy();
+	auto expr = unique_ptr_cast<ParsedExpression, duckdb::CaseExpression>(std::move(expr_p));
+
+	return InternalWhen(std::move(expr), condition, value);
```
Comment (Tmonster) [inline tools/pythonpkg/src/pyexpression.cpp:76]: why are we returning an internal when here?

File: tools/pythonpkg/src/pyexpression/initialize.cpp [hunk 2]
```diff
@@ -0,0 +1,246 @@
...
+	m.def("StarExpression", &DuckDBPyExpression::StarExpression, py::kw_only(), py::arg("exclude") = py::list(), docs);
+	m.def(
+	    "StarExpression", []() { return DuckDBPyExpression::StarExpression(); }, docs);
+
+	// Function Expression
+	docs = "";
+	m.def("FunctionExpression", &DuckDBPyExpression::FunctionExpression, py::arg("function_name"), docs);
+}
+
+static void InitializeDunderMethods(py::class_<DuckDBPyExpression, shared_ptr<DuckDBPyExpression>> &m) {
```
Comment (Tmonster) [inline tools/pythonpkg/src/pyexpression/initialize.cpp:35]: DunderMethods?

File: tools/pythonpkg/src/pyexpression/initialize.cpp [hunk 3]
```diff
@@ -0,0 +1,246 @@
...
+		TODO: add docs
+	)";
+	m.def("__truediv__", &DuckDBPyExpression::Division, docs);
+	m.def("__rtruediv__", &DuckDBPyExpression::Division, docs);
+
+	docs = R"(
+		TODO: add docs
+	)";
+	m.def("__floordiv__", &DuckDBPyExpression::FloorDivision, docs);
+	m.def("__rfloordiv__", &DuckDBPyExpression::FloorDivision, docs);
```
Comment (Tmonster) [inline tools/pythonpkg/src/pyexpression/initialize.cpp:84]: what's the difference between `__floordiv__` and `__rfloordiv__`?

File: tools/pythonpkg/tests/fast/test_expression.py [hunk 4]
```diff
@@ -0,0 +1,557 @@
...
+        rel = con.sql(
+            """
+			select
+				1 as a,
+				2 as b,
+				3 as c,
+		"""
+        )
+
+        col1 = ColumnExpression('a')
```
Comment (Tmonster) [inline tools/pythonpkg/tests/fast/test_expression.py:370]: Any tests where this Column expression doesn't exist?

**Review by Tmonster — COMMENTED** [review]
Looks good! Had a couple of minor coments

File: tools/pythonpkg/src/include/duckdb_python/expression/pyexpression.hpp [hunk 5]
```diff
@@ -0,0 +1,125 @@
...
+	string Type() const;
+
+	string ToString() const;
+	void Print() const;
+	shared_ptr<DuckDBPyExpression> Add(const DuckDBPyExpression &other);
+	shared_ptr<DuckDBPyExpression> Negate();
+	shared_ptr<DuckDBPyExpression> Subtract(const DuckDBPyExpression &other);
+	shared_ptr<DuckDBPyExpression> Multiply(const DuckDBPyExpression &other);
+	shared_ptr<DuckDBPyExpression> Division(const DuckDBPyExpression &other);
+	shared_ptr<DuckDBPyExpression> FloorDivision(const DuckDBPyExpression &other);
```
[the remark this answers is not in the document]
Comment (Tishj) [reply tools/pythonpkg/src/include/duckdb_python/expression/pyexpression.hpp:47]: Do we have an operator for ceil division?

I just implemented what I needed for the pyspark API implementation.
Also yea I think `ceil` would just be `floor + 1`

File: tools/pythonpkg/src/include/duckdb_python/expression/pyexpression.hpp [hunk 6]
```diff
@@ -0,0 +1,125 @@
...
+	shared_ptr<DuckDBPyExpression> GreaterThanOrEqual(const DuckDBPyExpression &other);
+	shared_ptr<DuckDBPyExpression> LessThan(const DuckDBPyExpression &other);
+	shared_ptr<DuckDBPyExpression> LessThanOrEqual(const DuckDBPyExpression &other);
+
+	shared_ptr<DuckDBPyExpression> SetAlias(const string &alias) const;
+	shared_ptr<DuckDBPyExpression> When(const DuckDBPyExpression &condition, const DuckDBPyExpression &value);
+	shared_ptr<DuckDBPyExpression> Else(const DuckDBPyExpression &value);
+	shared_ptr<DuckDBPyExpression> Cast(const DuckDBPyType &type) const;
+
+	// AND, OR and NOT
```
[the remark this answers is not in the document]
Comment (Tishj) [reply tools/pythonpkg/src/include/duckdb_python/expression/pyexpression.hpp:65]: I just implemented what I needed, happy to add to it later but I didn't want to bloat this PR too much.

File: tools/pythonpkg/src/include/duckdb_python/expression/pyexpression.hpp [hunk 7]
```diff
@@ -0,0 +1,125 @@
...
+	static shared_ptr<DuckDBPyExpression> StarExpression(const py::list &exclude = py::none());
+	static shared_ptr<DuckDBPyExpression> ColumnExpression(const string &function_name);
+	static shared_ptr<DuckDBPyExpression> ConstantExpression(const py::object &value);
+	static shared_ptr<DuckDBPyExpression> CaseExpression(const DuckDBPyExpression &condition,
+	                                                     const DuckDBPyExpression &value);
+	static shared_ptr<DuckDBPyExpression> FunctionExpression(const string &function_name, const py::args &args);
+
+public:
+	// Internal functions (not exposed to Python)
+	static shared_ptr<DuckDBPyExpression> InternalFunctionExpression(const string &function_name,
```
[the remark this answers is not in the document]
Comment (Tishj) [reply tools/pythonpkg/src/include/duckdb_python/expression/pyexpression.hpp:100]: internal as in, "private" helper functions for methods, but all the methods are static so I can't get away with actually making it private

File: tools/pythonpkg/src/pyexpression.cpp (hunk 1 above)
Comment (Tishj) [reply tools/pythonpkg/src/pyexpression.cpp:76]: Just a helper method call, to reduce code duplication

File: tools/pythonpkg/src/pyexpression/initialize.cpp (hunk 2 above)
Comment (Tishj) [reply tools/pythonpkg/src/pyexpression/initialize.cpp:35]: dunder = "double underscore", python is full with `__name__` methods and they're commonly referred to as dunder methods

File: tools/pythonpkg/tests/fast/test_expression.py (hunk 4 above)
Comment (Tishj) [reply tools/pythonpkg/tests/fast/test_expression.py:370]: in `test_column_expression`
```py
        column = ColumnExpression('d')
        with pytest.raises(duckdb.BinderException, match='Referenced column "d" not found'):
            rel2 = rel.select(column)
```

File: tools/pythonpkg/src/pyexpression/initialize.cpp (hunk 3 above)
Comment (Tishj) [reply tools/pythonpkg/src/pyexpression/initialize.cpp:84]: In our case it doesn't matter because the only variant we accept is where `other` is also a class instance, so the `__rfloordiv__` variant likely doesn't even get used

File: tools/pythonpkg/src/pyexpression.cpp [hunk 8]
```diff
@@ -0,0 +1,345 @@
...
+	py_expr->null_order = OrderByNullType::NULLS_LAST;
+	return py_expr;
+}
+
+// Unary operators
+
+shared_ptr<DuckDBPyExpression> DuckDBPyExpression::Negate() {
+	vector<unique_ptr<ParsedExpression>> children;
+	children.push_back(GetExpression().Copy());
+	return DuckDBPyExpression::InternalFunctionExpression("-", std::move(children), true);
```
Comment (Tmonster) [inline tools/pythonpkg/src/pyexpression.cpp:215]: can we have an assert that there is only one child here? Also, why the `"-"` character for negate? Isn't `"!"` more common?

File: tools/pythonpkg/src/pyexpression.cpp [hunk 9]
```diff
@@ -0,0 +1,345 @@
...
+	auto expr = unique_ptr_cast<ParsedExpression, duckdb::CaseExpression>(std::move(expr_p));
+
+	expr->else_expr = value.GetExpression().Copy();
+	return make_shared<DuckDBPyExpression>(std::move(expr));
+}
+
+// Binary operators
+
+shared_ptr<DuckDBPyExpression> DuckDBPyExpression::Add(const DuckDBPyExpression &other) {
+	return DuckDBPyExpression::BinaryOperator("+", *this, other);
```
Comment (Tmonster) [inline tools/pythonpkg/src/pyexpression.cpp:91]: Maybe we can have enums for the string function_name argument? Or no?

**Review by Tmonster — COMMENTED** [review]
So this PR is to add the expression class to the python API right? In the end this python api is supposed to mirror the spark api.  You then build the relations in python land but they execute in DuckDB. Can we add a test where the column expressions reference columns in tables in the duckdb catalog? And then we create expressions in python that are then executed in duckdb? Something like this?
```
    def test_modulus_expression(self):
        con = duckdb.connect()
        insert = con.sql("""create table tb1 as select range as a, range as b from range(10)""")
        rel = con.sql(
            """
            select
                  a, b from tbl1
        """
        )
        col1 = ColumnExpression('a')
        col2 = ColumnExpression('b')
        expr = col1 % col2
        rel2 = rel.select(expr)
        res = rel2.fetchall()
        assert res == [(1,),(1,), ...]
```

And is there a way to check the explain output? That way maybe we can grep for the module or something in the duckdb plan

File: tools/pythonpkg/src/pyexpression.cpp (hunk 8 above)
Comment (Tishj) [reply tools/pythonpkg/src/pyexpression.cpp:215]: `!` would create a boolean, this just inverses the number I think?

**Comment by Tishj** [comment]
> So this PR is to add the expression class to the python API right? In the end this python api is supposed to mirror the spark api. You then build the relations in python land but they execute in DuckDB. Can we add a test where the column expressions reference columns in tables in the duckdb catalog? And then we create expressions in python that are then executed in duckdb? Something like this?
> 
> ```
>     def test_modulus_expression(self):
>         con = duckdb.connect()
>         insert = con.sql("""create table tb1 as select range as a, range as b from range(10)""")
>         rel = con.sql(
>             """
>             select
>                   a, b from tbl1
>         """
>         )
>         col1 = ColumnExpression('a')
>         col2 = ColumnExpression('b')
>         expr = col1 % col2
>         rel2 = rel.select(expr)
>         res = rel2.fetchall()
>         assert res == [(1,),(1,), ...]
> ```
> 
> And is there a way to check the explain output? That way maybe we can grep for the module or something in the duckdb plan

Sure I'll add this test, though I don't really know what you mean by:
> That way maybe we can grep for the module or something in the duckdb plan

What we currently do in the python API is accept strings, in things like `DuckDBPyRelation.project`, what we do internally is parse these into ParsedExpressions:
```c++
auto expressions = Parser::ParseExpressionList(select_list, context.GetContext()->GetParserOptions());
```

What this PR adds is the ability to move this creation of ParsedExpressions out of the internals, and then we allow the option to pass in these already created expressions instead of a stringified version.

After the call to `Relation::Project` this change will have no impact, apart from maybe binding issues if the expressions aren't properly constructed.

Maybe a good verification of this would be to add a method that accepts a string, which calls `Parser::ParseExpressionList` and returns a list of DuckDBPyExpressions, then verify that these produce the same results

Also:
> In the end this python api is supposed to mirror the spark api

This is not necessarily the goal, if the spark API does something stupid, we don't have to follow them, I just didn't think this was a stupid idea and it makes the implementation of the spark API much easier to have similar constructs as them.
For example it would have been hell to implement `when` and `otherwise` if we just had strings to work with

File: tools/pythonpkg/src/pyexpression.cpp (hunk 9 above)
Comment (Tishj) [reply tools/pythonpkg/src/pyexpression.cpp:91]: Then we'd have to parse it back to string when we create a FunctionExpression, so I'm not sure if that would be a good idea

File: src/include/duckdb/main/relation.hpp [hunk 10]
```diff
@@ -81,9 +84,12 @@ class Relation : public std::enable_shared_from_this<Relation> {
 	DUCKDB_API shared_ptr<Relation> Project(const string &select_list, const vector<string> &aliases);
 	DUCKDB_API shared_ptr<Relation> Project(const vector<string> &expressions);
 	DUCKDB_API shared_ptr<Relation> Project(const vector<string> &expressions, const vector<string> &aliases);
+	DUCKDB_API shared_ptr<Relation> Select(vector<unique_ptr<ParsedExpression>> expressions,
```
Comment (Tishj) [inline src/include/duckdb/main/relation.hpp:87]: Might be better if it's just called Project as well, since it does the same thing, the parameters are just different

File: src/main/relation.cpp [hunk 11]
```diff
@@ -47,6 +47,10 @@ shared_ptr<Relation> Relation::Project(const vector<string> &expressions) {
 	return Project(expressions, aliases);
 }
 
+shared_ptr<Relation> Relation::Select(vector<unique_ptr<ParsedExpression>> expressions, const vector<string> &aliases) {
```
Comment (Tishj) [inline src/main/relation.cpp:50]: This too

File: tools/pythonpkg/tests/fast/test_expression.py [hunk 12]
```diff
@@ -0,0 +1,572 @@
...
+        col2 = ColumnExpression('b')
+        expr = FunctionExpression('struct_pack', col1, col2).alias('struct')
+
+        rel = rel.select(expr)
+        res = rel.fetchall()
+        assert res == [({'a': 1, 'b': 2},)]
+
+    def test_function_expression(self):
```
Comment (Tishj) [inline tools/pythonpkg/tests/fast/test_expression.py:351]: Add tests with some existing functions

Comment (Tishj) [reply tools/pythonpkg/tests/fast/test_expression.py:351]: Also add some tests with aggregates, fine if they throw an error, we're not aiming to support these yet

File: tools/pythonpkg/tests/fast/test_expression.py [hunk 13]
```diff
@@ -0,0 +1,572 @@
...
+                2 as b,
+                3 as c
+        """
+        )
+        column = ColumnExpression('a')
+        rel2 = rel.select(column)
+        res = rel2.fetchall()
+        assert res == [(1,)]
+
+        column = ColumnExpression('d')
```
Comment (Tishj) [inline tools/pythonpkg/tests/fast/test_expression.py:63]: Add a test where we explain the logical plan to verify the presence of the expressions we created

Also check behavior on a table/view/temporary table, replacement scan etc for extra coverage

**Comment by Tishj** [comment]
I'm merging `select` and `project`, running into a slight issue related to `DuckDBPyConnection.project`
Previously the signature was:
`project(df: str, expr: str, connection: DuckDBPyConnection = None)`
Since `DuckDBPyRelation.project` now takes `*args` (and the method uses the relation's project method) I've had to change the signature to:
`project(*expr, kw_only(), df: str, connection: DuckDBPyConnection = None)`

Previous call:
```py
rel = duckdb.project(test_df, 'i')
```

New way to call:
```py
rel = duckdb.project('i', df=test_df)
```

**Comment by Tishj** [comment]
I really can't see how the CI failures here are related to the changes made here, so I'm going to say they are unrelated
