### PR TITLE
Bugfixes

### LINKED ISSUE #3821: Setting default_collation=NOCASE modifies values of GROUP BY queries
#### What happens?
Changing the default collation to "NOCASE" unexpectedly lowercases all values when a query includes a "GROUP BY" clause.

Mytherin suggested in Discord this was not intentional and asked me to file a bug.

#### To Reproduce

```sql
PRAGMA default_collation=NOCASE
CREATE TABLE t AS (SELECT 'hello' AS x UNION ALL SELECT 'WORLD' AS x);
SELECT x FROM t GROUP BY 1;
```

```text
┌─────────┐
│    x    │
│ varchar │
├─────────┤
│ world   │
│ hello   │
└─────────┘
```
Result: all values are lowercased.
Expected: casing of values returned is unchanged.

I ran into this because I want to use case-insensitive string sorting. default_collation=NOCASE would do what I want, but can't be used since it modifies values (seemingly only when a query includes a GROUP BY).

For now, I'm using `ORDER BY lower($column)` as a workaround, but that's undesirable as it needs to be included with every ORDER BY query vs just setting a global PRAGMA.

#### Environment (please complete the following information):
 - OS: OS X or browser Wasm
 - DuckDB Version: @duckdb/duckdb-wasm 1.14.4
 - DuckDB Client: duckdb-wasm

### LINKED ISSUE #8287: Internal Exception when dropping system catalog function as if it were a Macro
### What happens?

When trying to drop macro `sum` (without creating it), an internal exception is thrown.

### To Reproduce

```
$ duckdb
-- Loading resources from /Users/laurens/.duckdbrc
v0.8.1-dev1402 aada97ec5f
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D drop macro sum;
ABORT THROWN BY INTERNAL EXCEPTION: Database "system" not found
^C[1]    53269 abort (core dumped)  duckdb
```

### OS:

MacOS

### DuckDB Version:

Master

### DuckDB Client:

CLI

### Full Name:

Laurens Kuiper

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by lnkuiper**
Fixes #3821 by pushing a `first` aggregate when a column that appears in `GROUP BY` is implicitly collated by a default collation set with `PRAGMA`.

Fixes #8287 by checking whether the catalog entry is flagged `internal` when trying to drop it.

### CODE REVIEW

File: src/planner/binder/query_node/bind_select_node.cpp [hunk 1]
```diff
@@ -380,6 +383,20 @@ unique_ptr<BoundQueryNode> Binder::BindSelectNode(SelectNode &statement, unique_
 			auto bound_expr = group_binder.Bind(group_expressions[i], &group_type);
 			D_ASSERT(bound_expr->return_type.id() != LogicalTypeId::INVALID);
 
+			if (group_type.id() == LogicalTypeId::VARCHAR && !DBConfig::GetConfig(context).options.collation.empty()) {
+				// TODO If there is a collation on a group x, we should group by the collated expr,
+				//  but also push a first(x) aggregate)
+				info.implicit_collate[i] = result->aggregates.size();
```
Comment (Mytherin) [inline src/planner/binder/query_node/bind_select_node.cpp:389]: Rather than trying to figure out if a collation is present here - it would be better to check this earlier on when the collation is actually pushed into the group by (see `bind_select_node.cpp:384` where `ExpressionBinder::PushCollation` is called).

Currently this doesn't work with explicit collations on columns, e.g.:

```sql
SELECT x COLLATE NOCASE FROM t GROUP BY 1;
```

Or when the collation is part of the schema:

```sql
CREATE TABLE t(x VARCHAR COLLATE NOCASE);
INSERT INTO t VALUES ('WoRlD'), ('WORLD');
FROM t GROUP BY x;
┌─────────┐
│    x    │
│ varchar │
├─────────┤
│ world   │
└─────────┘
```

File: test/issues/general/test_3821.test [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+WORLD
+hello
+
+statement ok
+PRAGMA default_collation=NOCASE;
+
+query I rowsort
+SELECT x FROM t GROUP BY 1;
+----
+WORLD
```
Comment (Mytherin) [inline test/issues/general/test_3821.test:23]: Can we add a second `WoRlD` to the test table to ensure the collation is still doing the collation?

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Looks great. Some comments:

**Comment by lnkuiper** [comment]
Thanks for the feedback! That query indeed did not work yet; It should be fixed now.

**Review by Mytherin — APPROVED** [review]
Thanks for the fixes! LGTM

**Comment by lnkuiper** [comment]
I think this is ready to go!

File: test/issues/general/test_3821.test [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+SELECT x FROM t_schema GROUP BY x;
+----
+WORLD
+hello
+
+statement ok
+PRAGMA default_collation=NOCASE;
+
+query I rowsort
+SELECT x FROM t GROUP BY 1;
```
Comment (Mytherin) [inline test/issues/general/test_3821.test:41]: Can we also add a test where we don't explicitly have the `GROUP BY` in the select list, e.g.:

```sql
SELECT COUNT(*) FROM t GROUP BY x COLLATE NOCASE;
```

(I'm assuming this will work currently but perhaps good to test)

**Review by Mytherin — COMMENTED** [review]
Thanks for the fixes! Some more comments:

File: src/planner/binder/query_node/bind_select_node.cpp [hunk 4]
```diff
@@ -380,10 +384,31 @@ unique_ptr<BoundQueryNode> Binder::BindSelectNode(SelectNode &statement, unique_
...
+			                                                     StringType::GetCollation(group_type), true);
+			if (!contains_subquery && !collated_expr->Equals(bound_expr_ref)) {
+				// if there is a collation on a group x, we should group by the collated expr,
+				// but also push a first(x) aggregate in case x is selected (uncollated)
+				info.collated_groups[i] = result->aggregates.size();
+
+				auto first_fun = FirstFun::GetFunction(LogicalType::VARCHAR);
+				vector<unique_ptr<Expression>> first_children;
+				// FIXME: would be better to just refer to this expression, but for now we copy
+				first_children.push_back(bound_expr_ref.Copy());
```
[the remark this answers is not in the document]
Comment (lnkuiper) [reply src/planner/binder/query_node/bind_select_node.cpp:405]: I have been trying something for a while now, but I'm starting to think that I don't understand what you mean.

This is what I tried:
```c++
			// push a potential collation, if necessary
			string collation = StringType::GetCollation(group_type);
			auto collated_expr = ExpressionBinder::PushCollation(context, std::move(bound_expr), collation, true);
			if (!collation.empty()) {
				// if a collation is added on a group x, we should group by the collated expr,
				// but also push a first(x) aggregate in case x is selected (uncollated)
				vector<unique_ptr<ParsedExpression>> first_children;
				if (group_binder.unbound_expression->GetExpressionClass() == ExpressionClass::COLLATE) {
					auto &collate_expr = group_binder.unbound_expression->Cast<CollateExpression>();
					first_children.push_back(collate_expr.child->Copy());
				} else {
					first_children.push_back(group_binder.unbound_expression->Copy());
				}
				auto first = make_uniq_base<ParsedExpression, FunctionExpression>("first", std::move(first_children));
				result->aggregates.push_back(group_binder.Bind(first));
				info.collated_groups[i] = result->aggregates.size() - 1;
			}
```
But the binder doesn't seem to like this.

[the remark this answers is not in the document]
Comment (Mytherin) [reply src/planner/binder/query_node/bind_select_node.cpp:405]: Hm yes, that is what I meant. Let's just keep the original implementation if that's not working.
