### PR TITLE
Make our default `threads` setting Cgroup-aware on Linux

### LINKED ISSUE #6519: The default number of threads is wrong within a distributed environment
### What happens?

When using duckdb from a Docker container in a Kubernetes cluster, the default number of threads used is the number of physical cores of the cluster, instead of the number of accessible cores. This results in oversubscribing issues, where there are far too many threads spawned compared to the number of cores to be used.

This is probably due to duckdb using shell commands like `nproc` to access the number of cores. Such commands are not cgroup aware and therefore yield incorrect results.

On the other hand, libraries like joblib inspect cgroup to give an accurate number of accessible cores. See [this section of joblib](https://github.com/joblib/loky/blob/master/loky/backend/context.py#L125).

cc @ogrisel that spotted the bug

### To Reproduce

Run duckdb in a Kubernetes pod and see the number of spawned threads with `htop`.
```python
import duckdb
con = duckdb.connect("duckdb.db")
# any sql query
```

Also run `nproc` in the shell (this will also give the number observed threads)

Then, install joblib:
```shell
pip install joblib
python -c "import joblib; print(joblib.cpu_count())"
```
This will give the number of accessible cores.
Alternatively, directly query cgroup attributes like joblib:
```shell
expr $(cat /sys/fs/cgroup/cpu/cpu.cfs_quota_us) / $(cat /sys/fs/cgroup/cpu/cpu.cfs_period_us)
```

### OS:

Ubuntu 20.04.4 LTS

### DuckDB Version:

0.7.0

### DuckDB Client:

Python 3.10

### Full Name:

Vincent Maladiere

### Affiliation:

Inria • scikit-learn

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #6519

### CODE REVIEW

**Comment by Tishj** [comment]
Linux:
```c++
/home/runner/work/duckdb/duckdb/src/main/config.cpp:255:31: error: format ‘%lld’ expects argument of type ‘long long int*’, but argument 3 has type ‘int64_t*’ {aka ‘long int*’} [-Werror=format=]
  255 |   if (sscanf(byte_buffer, "%lld", &period) != 1) {
      |                            ~~~^   ~~~~~~~
      |                               |   |
      |                               |   int64_t* {aka long int*}
      |                               long long int*
      |                            %ld
```
Mac:
```c++
/Users/thijs/DuckDBLabs/duckdb/src/main/config.cpp:255:34: warning: format specifies type 'long *' but the argument has type 'int64_t *' (aka 'long long *') [-Wformat]
                if (sscanf(byte_buffer, "%ld", &period) != 1) {
                                         ~~~   ^~~~~~~
                                         %lld
```
Gotta love platform inconsistencies

**Comment by Mytherin** [comment]
Perhaps we can avoid using `sscanf` entirely?

**Comment by Tishj** [comment]
> Perhaps we can avoid using `sscanf` entirely?

What do you suggest we use instead, something from `std::` or something native to our codebase?

File: src/main/config.cpp [hunk 1]
```diff
@@ -214,9 +214,73 @@ void DBConfig::SetDefaultMaxMemory() {
...
+		byte_buffer[read_bytes] = '\0';
+		if (sscanf(byte_buffer, "%ld", &period) != 1) {
+			return physical_cores;
+		}
+	} else {
+		// No cgroup quota
+		return physical_cores;
+	}
+	if (quota > 0 && period > 0) {
+		return std::ceil(quota / period);
```
Comment (Mytherin) [inline src/main/config.cpp:264]: `quota` and `period` are both integers so this will be floored, no?

This should probably be: `idx_t(std::ceil(double(quota) / double(period)))`

**Comment by Mytherin** [comment]
> > Perhaps we can avoid using `sscanf` entirely?
> 
> What do you suggest we use instead, something from `std::` or something native to our codebase?

These files only contain integer values, right? We should be able to use `StringUtil::StringSplit` and `TryCast::Operation<string_t, uint64_t>`.

Perhaps we want to add a wrapper to StringUtil for the integer cast, e.g. we could have a `StringUtil::StringToNumber` that calls `TryCast::Operation<string_t, uint64_t>`  internally.

**Comment by Tishj** [comment]
Sooo I'm not particularly a fan, but this works on all platforms:
```c++
		if (std::sscanf(byte_buffer, "%" SCNd64 " %" SCNd64 "", &quota, &period) != 2) {
			return physical_cores;
		}
```
