### PR TITLE
Fix index resolution when querying table with index via view

### LINKED ISSUE #17290: Querying a table with an index via a view does not resolve the index
### What happens?

I have a table `traces`, which has an index on `trace_id`. Querying the table directly, the index is used as expected.

Querying the table via a view, which is created like `CREATE VIEW v AS SELECT * FROM traces;` does not use the index in 1.2.x or preview - but it did use the index in 1.1.3.

### To Reproduce

Use the sample eth traces parquet file:

```shell
wget https://public-data.spiceai.org/large_eth_traces.parquet
```

Then run the following commands in the duckdb-cli:

```sql
-- Data setup
CREATE TABLE traces AS
    SELECT * FROM read_parquet('large_eth_traces.parquet');

CREATE VIEW traces_view AS
    SELECT * FROM traces;

-- Test without indexes
.timer on
.mode trash
SELECT * FROM traces WHERE trace_id = 'call_0x22ba49176f15ec5524434d87c47fc9dbff6ef8f584889ab4f0fa830d76a678d4_7_3_2_0_0_0_0_0';
SELECT * FROM traces_view WHERE trace_id = 'call_0x22ba49176f15ec5524434d87c47fc9dbff6ef8f584889ab4f0fa830d76a678d4_7_3_2_0_0_0_0_0';
.timer off
.mode duckbox

-- Test with indexes
CREATE INDEX idx_traces ON traces(trace_id);
.timer on
.mode trash
SELECT * FROM traces WHERE trace_id = 'call_0x22ba49176f15ec5524434d87c47fc9dbff6ef8f584889ab4f0fa830d76a678d4_7_3_2_0_0_0_0_0';
SELECT * FROM traces_view WHERE trace_id = 'call_0x22ba49176f15ec5524434d87c47fc9dbff6ef8f584889ab4f0fa830d76a678d4_7_3_2_0_0_0_0_0';
```

I tested on DuckDB 1.1.3, 1.2.2 and Preview with the following results:

```console
# 1.2.2

100% ▕████████████████████████████████████████████████████████████▏ 
Run Time (s): real 0.035 user 0.565377 sys 0.013131
Run Time (s): real 0.033 user 0.546203 sys 0.005153
100% ▕████████████████████████████████████████████████████████████▏ 
Run Time (s): real 0.002 user 0.005919 sys 0.001608
Run Time (s): real 0.034 user 0.557535 sys 0.004811

# Preview

100% ▕████████████████████████████████████████████████████████████▏ 
Run Time (s): real 0.024 user 0.415963 sys 0.006251
Run Time (s): real 0.025 user 0.439129 sys 0.000790
100% ▕████████████████████████████████████████████████████████████▏ 
Run Time (s): real 0.002 user 0.007081 sys 0.000000
Run Time (s): real 0.024 user 0.422764 sys 0.004029

# 1.1.3

100% ▕████████████████████████████████████████████████████████████▏ 
Run Time (s): real 0.032 user 0.519765 sys 0.012689
Run Time (s): real 0.032 user 0.530937 sys 0.001702
100% ▕████████████████████████████████████████████████████████████▏ 
Run Time (s): real 0.002 user 0.001749 sys 0.000988
Run Time (s): real 0.001 user 0.001185 sys 0.000008
```

We can see that the view is the same speed as the indexed table in 1.1.3, but not in 1.2.2 or preview.

### OS:

Linux pop-os 6.9.3-76060903-generic

### DuckDB Version:

1.2.2

### DuckDB Client:

Native CLI

### Hardware:

_No response_

### Full Name:

William Croxson

### Affiliation:

Spice.AI

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [x] Yes, I have

### PR DESCRIPTION
**Pull request by mach-kernel**
Index scans would fail to match as in #17290 if the position of the column used in the filter did not match that of the `index_expr`: the ART `filter_match` assertion fails:

https://github.com/duckdb/duckdb/blob/0b83e5d2f68bc02dfefde74b846bd039f078affa/src/execution/index/art/art.cpp#L160-L161

It appears to work in the direct table query case (as shown in the issue) because a projection puts the indexed column first (so the binding matches). 

I am unsure if this is the correct approach/place to make the change, however rebinding the column ref to its correct position relative to the input projection appears to fix the issue. Included is a test that fails on v1.3.2.

Fixes #17290

### CODE REVIEW

File: src/function/table/table_scan.cpp [hunk 1]
```diff
@@ -484,6 +487,42 @@ vector<unique_ptr<Expression>> ExtractFilterExpressions(const ColumnDefinition &
...
+				UpdateIndexExprColumnBindings(child, input_column_ids, indexed_columns);
+			}
+			break;
+		}
+		// TODO: never end up here, TableScanInitGlobal called without filters in input
+		// case ExpressionClass::BOUND_CAST: {
+		// 	auto &cast_expr = expr->Cast<BoundCastExpression>();
+		// 	UpdateIndexExprColumnBindings(cast_expr.child, input_column_ids, indexed_columns);
+		// 	break;
+		// }
```
Comment (kczimm) [inline src/function/table/table_scan.cpp]: Why can't we ever end up here?

File: test/sql/index/art/issues/test_art_issue_view_col_binding_17290.test
Comment (taniabogatsch) [inline test/sql/index/art/issues/test_art_issue_view_col_binding_17290.test:1]: - In addition to `EXPLAIN ANALYZE`, can we also verify the result is actually the expected result?
- There are still some commented-out parts at the bottom
- Maybe we can shorten the file name a bit: `test_art_view_col_binding` and put the issue number in the description/comment

File: src/function/table/table_scan.cpp [hunk 2]
```diff
@@ -484,6 +488,42 @@ vector<unique_ptr<Expression>> ExtractFilterExpressions(const ColumnDefinition &
 	return expressions;
 }
 
+// Recursively updates column bindings in an index expression to match the current input projection,
+// even if they are the child of a function or cast
+void UpdateIndexExprColumnBindings(unique_ptr<Expression> &expr, const vector<column_t> &input_column_ids,
```
Comment (taniabogatsch) [inline src/function/table/table_scan.cpp]: Instead of passing `indexed_columns`, let's just pass `indexed_columns[0]` directly (`const column_t indexed_column`). That way it'll be more clear (later) that the function does not support updating a vector of index columns.

File: src/function/table/table_scan.cpp [hunk 3]
```diff
@@ -484,6 +488,42 @@ vector<unique_ptr<Expression>> ExtractFilterExpressions(const ColumnDefinition &
...
+	switch (expr->GetExpressionClass()) {
+		case ExpressionClass::BOUND_COLUMN_REF: {
+			auto &bound_column_ref_expr = expr->Cast<BoundColumnRefExpression>();
+
+			for (idx_t i=0; i < input_column_ids.size(); ++i) {
+				if (input_column_ids[i] == indexed_columns[0]) {
+					bound_column_ref_expr.binding.column_index = i;
+					break;
+				}
+			}
```
Comment (taniabogatsch) [inline src/function/table/table_scan.cpp]: I am not sure if the logic here is correct, mainly because we don't tie the `bound_column_ref_expr` to the indexed column. Like, we now always replace the `binding.column_index` with the index column, even if the original `bound_column_ref_expr` has nothing to do with the indexed column.

I am wondering if it should look more like this:
```cpp
		case ExpressionClass::BOUND_COLUMN_REF: {
			auto &bound_column_ref_expr = expr->Cast<BoundColumnRefExpression>();
			if (bound_column_ref_expr.binding.column_index == indexed_columns[0]) {
				for (idx_t i = 0; i < input_column_ids.size(); ++i) {
					if (input_column_ids[i] == indexed_columns[0]) {
						bound_column_ref_expr.binding.column_index = i;
						return;
					}
				}
			}
```

And if that's the correct logic, then we might as well move the for-loop outside of the recursion and only pass in the `replace_index`. So the updated function signature would look like:

```cpp
void UpdateIndexExprColumnBindings(unique_ptr<Expression> &expr, const column_t updated_column, const column_t index_column)
```

File: src/function/table/table_scan.cpp [hunk 4]
```diff
@@ -484,6 +488,42 @@ vector<unique_ptr<Expression>> ExtractFilterExpressions(const ColumnDefinition &
 	return expressions;
 }
 
+// Recursively updates column bindings in an index expression to match the current input projection,
+// even if they are the child of a function or cast
+void UpdateIndexExprColumnBindings(unique_ptr<Expression> &expr, const vector<column_t> &input_column_ids,
+						  		   const vector<column_t> &indexed_columns) {
+	if (!expr) { return; }
+
+	switch (expr->GetExpressionClass()) {
```
Comment (taniabogatsch) [inline src/function/table/table_scan.cpp]: You don't need to write your own switch-case here: we have `ExpressionIterator::EnumerateChildren` for that :)

**Review by taniabogatsch — CHANGES_REQUESTED** [review]
Hi @mach-kernel, thanks for looking into this! I left some comments :)

**Comment by mach-kernel** [comment]
Thanks for your review @taniabogatsch! I'm away for a few days but will get to this ASAP when I return!

File: src/function/table/table_scan.cpp (hunk 3 above)
Comment (mach-kernel) [reply src/function/table/table_scan.cpp]: The code was very terse with `ExpressionIterator` so I opted to do everything in `TryScanIndex`. Added the extra check as shown.

File: test/sql/index/art/issues/test_art_issue_view_col_binding_17290.test
Comment (mach-kernel) [reply test/sql/index/art/issues/test_art_issue_view_col_binding_17290.test:1]: I removed the test for:

```sql
create index test_cast_x on test(cast(x as integer))
```

I think fixing that is probably another PR, the explain output is really wacky (fixing it probably outside the scope of this PR):
https://gist.github.com/mach-kernel/62eee0f74c265c5094aa4a01dd5a73a4

File: src/function/table/table_scan.cpp (hunk 1 above)
Comment (mach-kernel) [reply src/function/table/table_scan.cpp]: The filters don't get bound in the input, I think that the cast trips up the optimizer

**Comment by mach-kernel** [comment]
Hi @taniabogatsch! Let me know if there are any other changes to be made 😸

File: src/function/table/table_scan.cpp [hunk 5]
```diff
@@ -500,6 +504,34 @@ bool TryScanIndex(ART &art, const ColumnList &column_list, TableFunctionInitInpu
...
+			updated_index_column = i;
+			found_index_column_in_input = true;
+			break;
+		}
+	}
+
+	// If found, update the bound column ref within index_expr
+	if (found_index_column_in_input) {
+		ExpressionIterator::EnumerateExpression(index_expr, [&](Expression &expr) {
+			if (expr.GetExpressionClass() != ExpressionClass::BOUND_COLUMN_REF)
```
Comment (taniabogatsch) [inline src/function/table/table_scan.cpp]: Small nit but let's put that line in brackets (our convention).

**Review by taniabogatsch — APPROVED** [review]
Small nit, but with or without fixing that, I think this PR is ready to go in :)

File: src/function/table/table_scan.cpp (hunk 5 above)
Comment (mach-kernel) [reply src/function/table/table_scan.cpp]: Sorted!

**Comment by Mytherin** [comment]
Thanks!
