### PR TITLE
Fix #4703

### LINKED ISSUE #4703: Internal error when drop column with generated column presented.
### What happens?

Internal error when drop column with generated column presented.
```sql
create table t(i int, j as (2), k int);
alter table t drop column k;
```

### To Reproduce

```sql
create table t(i int, j as (2), k int);
alter table t drop column k;
Error: INTERNAL Error: Assertion triggered in file "/data/zippond/git/duckdb_clean/src/storage/data_table.cpp" on line 147: removed_column < column_definitions.size()
```

### OS:

linuxamd64

### DuckDB Version:

v0.5.1-dev126 3591cd172

### DuckDB Client:

CLI

### Full Name:

Dong Zhi-peng

### Affiliation:

XJTU

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by taofengliu**
Fix #4703

It seems that generated columns are not inserted into DataTable and we use wrong index to delete common columns from DataTable.
I think I can't fix this issue just by inserting generated columns into DataTable because duckdb only support virtual generated columns now.So I skip the generated columns when passing argument 'removed_column' to DataTable.

I also add a test for this issue.

### CODE REVIEW

File: src/catalog/catalog_entry/table_catalog_entry.cpp [hunk 1]
```diff
@@ -441,7 +441,16 @@ unique_ptr<CatalogEntry> TableCatalogEntry::RemoveColumn(ClientContext &context,
 		return make_unique<TableCatalogEntry>(catalog, schema, (BoundCreateTableInfo *)bound_create_info.get(),
 		                                      storage);
 	}
-	auto new_storage = make_shared<DataTable>(context, *storage, removed_index);
+
+	// We need to skip generated columns because they are not in 'storage'
+	column_t storage_index = removed_index;
```
Comment (Mytherin) [inline src/catalog/catalog_entry/table_catalog_entry.cpp:446]: The columns store their `StorageOid`, so this could be replaced with `columns[removed_index].StorageOid()`

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Looks good.

It is intentional for virtual generated columns not to have entries in the DataTable. As they are generated, they are not stored on disk, so it would not make sense for them to have entries/occupy space in the physical table.

One minor comment, otherwise LGTM:

File: src/catalog/catalog_entry/table_catalog_entry.cpp (hunk 1 above)
Comment (taofengliu) [reply src/catalog/catalog_entry/table_catalog_entry.cpp:446]: Yes, you are right.

**Comment by Mytherin** [comment]
Thanks! LGTM
