### PR TITLE
Fix #6856: correctly check cast cost of child element of list during function binding

### LINKED ISSUE #6856: flatten() segfaults when called on bad input
### What happens?

Calling `flatten` on a list of literals, as opposed to a list of lists, results in a segfault instead of a user readable error.
Have not tried this on trunk. This is trivially reproducible for v0.7.1 b00b93f0b1 and master.

### To Reproduce

Just try to `select flatten([1,2]);`. Here's a copy and paste from my duckdb session:

```
D select flatten([[1,2]]);
┌─────────────────────────────────────────────────┐
│ flatten(main.list_value(main.list_value(1, 2))) │
│                     int32[]                     │
├─────────────────────────────────────────────────┤
│ [1, 2]                                          │
└─────────────────────────────────────────────────┘
D select flatten([1, 2]);
zsh: segmentation fault  duckdb
```

### OS:

MacOS,  M1, arm64

### DuckDB Version:

v0.7.1 b00b93f0b1, 0.7.2-dev1034 

### DuckDB Client:

CLI

### Full Name:

Dmitriy Ryaboy

### Affiliation:

Ginkgo Bioworks

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Mytherin**
Fixes #6856

### CODE REVIEW

File: src/function/cast_rules.cpp [hunk 1]
```diff
@@ -207,6 +207,15 @@ int64_t CastRules::ImplicitCast(const LogicalType &from, const LogicalType &to)
...
+	if (from.id() == LogicalTypeId::LIST && to.id() == LogicalTypeId::LIST) {
+		// Lists can be cast if their child types can be cast
+		auto child_cost = ImplicitCast(ListType::GetChildType(from), ListType::GetChildType(to));
+		if (child_cost >= 100) {
+			// subtract one from the cost because we prefer LIST[X] -> LIST[VARCHAR] over LIST[X] -> VARCHAR
+			child_cost--;
+		}
+		return child_cost;
+	}
 	if (from.id() == to.id()) {
```
Comment (Tishj) [inline src/function/cast_rules.cpp:219]: I spotted something weird here a couple weeks ago, since this takes care of `id == id`, then the if statement you removed was dead code. But below that, there is another similar case like this for UNION - which is also dead code right?

Comment (Mytherin) [reply src/function/cast_rules.cpp:219]: Yes it is. I tried to move it up but it did not work (as dead code often doesn't!) so I left it there for now. It should indeed be removed or reworked.
