### PR TITLE
Column Data Collection, Arrow Result conversion rework, Cross Product performance fixes & more

### LINKED ISSUE #3621: DuckDB 0.3.4 fetch_arrow_table() is over 20x slower vs 0.3.2
#### What happens?

fetch_arrow_table() appears to be significantly slower in 0.3.4 vs 0.3.2 (124 seconds vs 5.55 seconds)

#### To Reproduce
Steps to reproduce the behavior. Bonus points if those are only SQL queries.

!aws s3 cp s3://ursa-labs-taxi-data/2015/06/data.parquet /tmp

# using pyarrow==7 and duckdb 0.3.2

[ins] In [1]: import duckdb
[ins] In [2]: c = duckdb.connect()
[ins] In [5]: duckdb.__version__
Out[5]: '0.3.2'

[ins] In [6]: %time r = c.execute("select * from parquet_scan('/tmp/data.parquet')")
CPU times: user 17.7 ms, sys: 4.39 ms, total: 22.1 ms
Wall time: 26.4 ms

[ins] In [7]: %time t = r.fetch_arrow_table()
CPU times: user 5.55 s

------
# using pyarrow==7 and duckdb 0.3.4
# pyarrow==8 is also slow

[ins] In [1]: import duckdb
[nav] In [2]: c = duckdb.connect()

[ins] In [3]: duckdb.__version__
Out[3]: '0.3.4'

[ins] In [4]: %time r = c.execute("select * from parquet_scan('/tmp/data.parquet')")
CPU times: user 5.36 ms, sys: 7.14 ms, total: 12.5 ms
Wall time: 12 ms

[ins] In [5]: %time t = r.fetch_arrow_table()
CPU times: user 1min 46s, sys: 20 s, total: 2min 6s
Wall time: 2min 4s

#### Environment (please complete the following information):
 - OS: Ubuntu 20.04
 - DuckDB Version: 0.3.4
 - DuckDB Client: Python

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
'0.3.5-dev359'

[ins] In [5]: %time t = r.fetch_arrow_table()
CPU times: user 1min 29s, sys: 12.5 s, total: 1min 41s
Wall time: 1min 40s

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

Yes.  Created separate conda and docker environments.

### LINKED ISSUE #4147: Adding a where clause slows down a query by 10x.
Test file can be found here  https://github.com/lloydtabb/malloy_examples/blob/main/names/data/usa_names.parquet

The query below runs in about 20 seconds (on my machine).  Comment out the where clause and the query runs in 2 seconds.  I'm wondering if this can be optimized or if you have suggestions for rewriting the expression.  This is a pretty common Malloy use case.

```
  SELECT
    group_set,
    names_table."state" as "state__0",
    CASE WHEN group_set=0 THEN
      SUM(names_table."number")
      END as "population__0",
    CASE WHEN group_set=1 THEN
      names_table."name"
      END as "name__1",
    CASE WHEN group_set=1 THEN
      SUM(names_table."number")
      END as "population__1"
  FROM 'usa_names.parquet' as names_table
  CROSS JOIN (SELECT UNNEST(GENERATE_SERIES(0,1,1)) as group_set  ) as group_set
  WHERE (group_set NOT IN (1) OR (group_set IN (1) AND names_table."gender"='M'))
  GROUP BY 1,2,4
  LIMIT 5
  ```

vs

```
  SELECT
    group_set,
    names_table."state" as "state__0",
    CASE WHEN group_set=0 THEN
      SUM(names_table."number")
      END as "population__0",
    CASE WHEN group_set=1 THEN
      names_table."name"
      END as "name__1",
    CASE WHEN group_set=1 THEN
      SUM(names_table."number")
      END as "population__1"
  FROM 'usa_names.parquet' as names_table
  CROSS JOIN (SELECT UNNEST(GENERATE_SERIES(0,1,1)) as group_set  ) as group_set
  -- WHERE (group_set NOT IN (1) OR (group_set IN (1) AND names_table."gender"='M'))
  GROUP BY 1,2,4
  LIMIT 5
  ```

### LINKED ISSUE #4326: null UUID column converted to empty string in arrow table
### What happens?

When retrieving the arrow table from a relation with a null UUID, it's stored as an empty string.

### To Reproduce

```
con = duckdb.connect()
con.execute("""
    CREATE TABLE example(
        name varchar NOT NULL,
        uuid uuid,
        v varchar
    )        
""")
con.execute("""
    INSERT INTO example VALUES 
        ('a', '083739e9-9ef9-45db-a3ce-28fa85f1e0cc', 'hello'),
        ('b', null, null),
""")
arrow_df = con.execute("""SELECT * FROM example""").arrow()
print(arrow_df)
```

Which outputs:
```
name: [["a","b"]]
uuid: [["083739e9-9ef9-45db-a3ce-28fa85f1e0cc",""]]
v: [["hello",null]]
```

It should output:
```
name: [["a","b"]]
uuid: [["083739e9-9ef9-45db-a3ce-28fa85f1e0cc",null]]
v: [["hello",null]]
```

With pyarrow 9.0.0

### OS:

Archlinux - 5.18.14-arch1-1

### DuckDB Version:

0.4.0 and 0.4.1.dev1326

### DuckDB Client:

Python

### Full Name:

Christopher Meier

### Affiliation:

HEIG-VD

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Mytherin**
Yak shaving galore in this PR :) apologies for that.

This PR introduces the ColumnDataCollection (CDC). This is a new class fulfills the same purpose as the ChunkCollection - namely it serves to materialize query intermediates in columnar fashion. It is intended to fully replace the ChunkCollection, and has two distinct advantages over the ChunkCollection:

* The CDC is buffer managed, and allows for off-loading blocks from disk. Only the necessary blocks are kept pinned.
* The CDC supports zero-cost merging of multiple CDCs, which allows for parallel construction of CDCs. Separate threads can construct their own CDC in parallel, and create the final result by merging them.

Currently almost all instances of the ChunkCollection are replaced with the CDC - with a few notable exceptions. Those are the Window operator (pending @hawkfish reworks) and the LocalStorage (pending my own rework of that).

## Usage
The CDC is in many ways a drop-in replacement for the ChunkCollection. For example, you can iterate over the chunks in a CDC in a similar manner to the ChunkCollection:

```cpp
for(auto &chunk : cdc.Chunks()) {
	chunk.Print();
}
```

This works using iterators now, unlike the `ChunkCollection` that gave you direct access to the underlying `vector<DataChunk>`. Note that it is not entirely a drop-in replacement - there are certain operations that are not supported. In particular, support for the `GetValue` and `SetValue` methods are not added. 

As a replacement for this, we can iterate over the rows in the CDC:

```cpp
for(auto &row : cdc.Rows()) {
    auto col_idx = 0;
	row.GetValue(col_idx).Print();
}
```

Or we can materialize all rows in the CDC:

```cpp
auto rows = cdc.GetRows();
auto col_idx = 0;
auto row_idx = 0;
rows.GetValue(col_idx, row_idx).Print();
```

This is slow and should not be used in general - but the methods are added in order to support `GetValue` on the `MaterializedQueryResult` as it existed before.

## Internal workings
Internally the Column Data Collection consists of a set of `ColumnDataCollectionSegment` classes, which hold the actual data of the CDC. When exclusively appending and scanning only a single `ColumnDataCollectionSegment` will be created. The main reason this layer of indirection exists is to allow for zero-cost merges of multiple CDCs - by moving all of the segments of one CDC to another.

The segment stores data divided into chunks:

```cpp
struct ChunkMetaData {
	//! The set of vectors of the chunk
	vector<VectorDataIndex> vector_data;
	//! The block ids referenced by the chunk
	unordered_set<uint32_t> block_ids;
	//! The number of entries in the chunk
	uint16_t count;
};
```

The chunks contain vectors, one vector for each of the columns stored by the CDC. In addition the chunks know which blocks are referenced by all of the underlying vectors. This makes it easy to pin the blocks required to read an individual chunk.

The vector stores the location of the vector's data within the blocks, together with references to `child` and `next` vectors. `child` vectors are used to store nested types (lists and structs). `next` vectors are used to store large vectors - in the case of lists that exceed the vector size in terms of entries.

```cpp
struct VectorMetaData {
	//! Where the vector data lives
	uint32_t block_id;
	uint32_t offset;
	//! The number of entries present in this vector
	uint16_t count;

	//! Child data of this vector (used only for lists and structs)
	//! Note: child indices are stored with one layer of indirection
	//! The child_index here refers to the `child_indices` array in the ColumnDataCollectionSegment
	//! The entry in the child_indices array then refers to the actual `VectorMetaData` index
	//! In case of structs, the child_index refers to the FIRST child in the `child_indices` array
	//! Subsequent children are stored consecutively, i.e.
	//! first child: segment.child_indices[child_index + 0]
	//! nth child  : segment.child_indices[child_index + (n - 1)]
	VectorChildIndex child_index;
	//! Next vector entry (in case there is more data - used only in case of children of lists)
	VectorDataIndex next_data;
};
```

During appending, memory is allocated for the vectors through the `ColumnDataAllocator`. This class hands out data within blocks as new memory is requested, and allocates new blocks if the current pool of memory is exhausted. The `ColumnDataAllocator` can also be moved from one CDC to another. This is powerful - as it allows construction of multiple CDCs without requiring each CDC to take up one block of space. This is used in the `PhysicalBatchCollector` to materialize data into separate CDCs for each batch while avoiding the potential worst case where each row would take up `256KB`, in case only one row per batch would make it through.

A future extension here might be to allow CDCs to *share* column data allocators, potentially across threads using e.g. atomics (CC @hawkfish). This could be very powerful for data partitioning as it would allow batch allocation & buffer management while avoiding the "blow-up" that occurs in memory usage when partitioning in parallel. For example, if we were to create 1024 partitions with 32 threads, if each thread would require one block per partition we would be looking at 8GB of minimum memory usage. Instead, if we could share allocators, the minimum memory usage is reduced to only 256MB. 

### Cross Product & Blockwise NL Join Rework

The cross product works internally by taking two chunks (one from each side), and iterating over one of the two chunks by creating constant vectors from each of its' rows, while fully outputting the other chunk. This is efficient and allows the cross product to (a) execute without copying any data, and (b) emit constant vectors, allowing for fast execution. The blockwise NL join works in a similar manner, but executes its condition on this chunk immediately.

While this is efficient, there is one problem with this approach, which is if we pick the wrong side to iterate over. If we have one chunk of size 1024 and one chunk of size 1, choosing the right side means doing one iteration, while choosing the wrong side means doing 1024 iterations. Previously, we would always choose the left side, while the optimizer would try to place the smallest side on the right. If the optimizer got it wrong - however - performance would take a nosedive.

In this PR we change the cross product to instead dynamically iterate over the smallest chunk, fixing several performance issues. We also refactor the blockwise NL join to directly use the cross product code, which cleans up the operator and fixes the same issue there.

This fixes #4147 and #2511

### Arrow Data Conversion Rework

Converting DuckDB results to Arrow vectors would previously do (mostly) zero-copy conversion of DuckDB DataChunks. While this sounds good - it actually caused several problems and inefficiencies. The zero-copy could only be done on chunks obtained from a `MaterializedQueryResult` - requiring a full materialization of the result into a ChunkCollection. Chunks obtained from the `StreamQueryResult` would become invalid after the next chunk was fetched, which would then lead to invalid memory being present in the Arrow vectors.

Furthermore, the zero-copy would only really work when requesting batches of `<1024` rows, whereas by default Arrow works with far larger batches (100K-1M rows). As such, this approach in practice resulted in at least two full copies of the dataset being made. Once during the materialization of the result, and once during the materialization into the larger batch.

In this PR we rework the Arrow result construction to incrementally construct Arrow vectors from DataChunks instead using the new `ArrowAppender` class. As part of this rework, we also clean up and move all of the arrow code into a dedicated folder.

The `ArrowAppender` class results in significantly faster result set conversion, as it avoids the several instances of full-result set materialization.

There was also an issue where the Arrow result set conversion was constructing very large DataChunks using `Append`, which was doing a `Resize` in a non-quadratic fashion. This lead to non-linear behavior and very slow construction of arrow results with large batch sizes (#3621). This is fixed by this PR as well. Below is a benchmark of loading lineitem from SF1 into an arrow table and Pandas DataFrame before and after this PR:

| System | Arrow | Pandas |
|--------|-------|--------|
| Old    | 22.1s | 1.49s  |
| New    | 0.54s | 1.49s  |

We also add a regression test to ensure the conversion speed does not degrade in the future.

Fixes #3621

### R altrep strings

The R altrep string representation relied on the random access provided by the ChunkCollection enforcing each chunk having 1024 entries. For now, we have moved this to materialize the strings into an array that can be randomly accessed. We should come up with something better for this in the future - or at least do the conversion/materialization in parallel which is now possible thanks to the CDC.

### Code Refactors

* Add `ClientProperties` to result (which contains the timezone), so query results are independent of the context
* Left/Right Outer Join Code Cleanup into shared OuterJoinMarker class
* C Result conversion clean-up

### CODE REVIEW

File: tools/rpkg/tests/testthat/test_arrow.R [hunk 1]
```diff
@@ -201,7 +200,7 @@ test_that("to_arrow roundtrip, with dataset", {
 # we need to create a connection separate from the ephemeral one that is made
 # with arrow_duck_connection()
 con <- dbConnect(duckdb::duckdb())
-dbExecute(con, "PRAGMA threads=2")
+dbExecute(con, "PRAGMA threads=1")
```
Comment (pdet) [inline tools/rpkg/tests/testthat/test_arrow.R:203]: Why this changed?

File: third_party/jaro_winkler/details/intrinsics.hpp [hunk 2]
```diff
@@ -95,10 +95,10 @@ static inline int tzcnt(uint64_t x)
 #    endif
 
 #else /*  gcc / clang */
-static inline int tzcnt(uint32_t x)
-{
-    return __builtin_ctz(x);
-}
+//static inline int tzcnt(uint32_t x)
```
Comment (pdet) [inline third_party/jaro_winkler/details/intrinsics.hpp:98]: Should this be commented out? 
If yes, why not remove it?

File: src/common/arrow/arrow_appender.cpp [hunk 3]
```diff
@@ -0,0 +1,729 @@
...
+static void InitializeFunctionPointers(ArrowAppendData &append_data) {
+	append_data.initialize = OP::Initialize;
+	append_data.append_vector = OP::Append;
+	append_data.finalize = OP::Finalize;
+}
+
+static void InitializeFunctionPointers(ArrowAppendData &append_data, const LogicalType &type) {
+	// handle special logical types
+	switch (type.id()) {
+	case LogicalTypeId::MAP:
```
Comment (pdet) [inline src/common/arrow/arrow_appender.cpp:558]: Should we have a switch case only on the logical types?

File: src/common/arrow/arrow_wrapper.cpp [hunk 4]
```diff
@@ -145,7 +148,7 @@ int ResultArrowArrayStreamWrapper::MyStreamGetNext(struct ArrowArrayStream *stre
 			agg_chunk_result->Append(*new_chunk, true);
 		}
 	}
-	agg_chunk_result->ToArrowArray(out);
```
Comment (pdet) [inline src/common/arrow/arrow_wrapper.cpp:148]: Use your own code and not the old code :-)

File: third_party/jaro_winkler/details/intrinsics.hpp (hunk 2 above)
Comment (Mytherin) [reply third_party/jaro_winkler/details/intrinsics.hpp:98]: Yes, this breaks the MacOS CI build. I would rather not remove it since it is in a third party library.
