### PR TITLE
Issue #10224: FIRST ORDER BY 

### LINKED ISSUE #10224: GROUP BY with last(x ORDER BY y) runs OOM; GROUP BY with argmax(x, y) doesn't
### What happens?

Two equivalent and extremely trivial queries; one fail's drastically, one is blazing fast.

### To Reproduce

```
import pandas as pd
import numpy as np
import duckdb
n = 70_000_000
df = pd.DataFrame({
    'time': np.random.choice(pd.date_range('2019-01-01 00:00:00', '2020-01-01 00:00:00', 25_000), n),
    'value': np.random.sample(n),
    'id': np.random.choice(range(300), n)
})
```

then
```
duckdb.query("""
SELECT time::DATE, id, argmax(value, time)
FROM df
GROUP BY ALL
""").df()
```
finishes in 0.7s but
```
duckdb.query("""
SELECT time::DATE, id, last(value ORDER BY time ASC)
FROM df
GROUP BY ALL
""").df()
```
runs OOM after ~2min.

I would have expected duckdb optimizes away the `ORDER BY` in a last. I would have definitely not expected it run OOM. By the way, the OOM can be avoided by pre-sorting the dataframe by the `time` column. Even on a fully presorted dataframe, `argmax` is 3x faster than `last(ORDER BY)` which I imagine shouldn't be possible if `last(ORDER BY)` was handled correctly.

Yet another way of skinning the cat runs OOMs as well, but I don't have as good a reason as for `last` why it definitely shouldn't (and it requires slightly higher `n` to fail, or more columns to be added to DISTINCT):
```
duckdb.query("""
SELECT 
DISTINCT ON (time::DATE, id)
*
FROM df
ORDER by time DESC
""").df()
```

### OS:

Linux-5.15.0-76-generic-x86_64-with-glibc2.35

### DuckDB Version:

0.9.3-dev1996

### DuckDB Client:

Python

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by hawkfish**
Improve performance of `FIRST` and related aggregates when used with `ORDER BY` clauses.

The problem was that the sorted aggregate wrapper assumes that the aggregate is holistic, but these aggregates only need to keep around a single value and the associated sort key. The proposed solution here is:

* Create a new `AggregateOrderDependent::COMPARE_DEPENDENT` enum to tag such functions;
* Create a new `CombineAggregateFunction` wrapper for them that only keeps single values and sort keys
* Use `LAST` internally to hold the single value and `BLOB`s to hold the keys.
* Invert the ordering for `FIRST` and friends so that the "last" value can be passed to `LAST`
* Create a new `SortKeyFun` that produces the `BLOB` keys as a single column.
* Add a benchmark to demonstrate the performance improvements

The current implementation of `SortKeyFun` is restricted to fixed-width radix keys, but @Mytherin has a PR in review that is completely general. Once that lands, the one in this PR can be replaced and the check removed.

The benchmark results on an 8 core 8GB MacBook Pro:

| Branch | Time | Memory |
| :--- | ---: | ---: |
| first-argmax | 3.5s | 4GB |
| main | 15.5s | 13G |

fixes: #10224

### CODE REVIEW

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Great results.

I do wonder if it would be simpler to add new functions `arg_min_nulls`/`arg_max_nulls` that mimic the `NULL` behavior of `FIRST/LAST` so we can do a straight rewrite into them? 

Unless you can see a use case for `COMPARE_DEPENDENT` beyond the first/last rewrite?

**Comment by hawkfish** [comment]
> I do wonder if it would be simpler to add new functions `arg_min_nulls`/`arg_max_nulls` that mimic the `NULL` behavior of `FIRST/LAST` so we can do a straight rewrite into them?
> 
> Unless you can see a use case for `COMPARE_DEPENDENT` beyond the first/last rewrite?

I was actually leaning the other way because I think `FIRST` has better internals. And you can already rewrite `ARG_MAX(v, k)` as `LAST(v ORDER BY k) FILTER (k IS NOT NULL)` (although I think the `NULL` handling is more efficient in the inner loop).

The whole `COMPARE_DEPENDENT` thing bugged me a bit too and it did seem like a rewrite would be more logical than hacking the binder, but if we are going to add multiple `NULL` functionality, I think `FIRST` is the place to do it because it already has templating for it.

**Comment by hawkfish** [comment]
The other reason to hack the binder was that I'm not clear on how to serialise my `SortKeyFun` bc the binding doesn't fit the current APIs.

As for the whole `NULL` value thing, I was wondering if we could just add another modifier to function arguments `IGNORE/ALLOW NULLS`?

**Comment by Mytherin** [comment]
> The other reason to hack the binder was that I'm not clear on how to serialise my `SortKeyFun` bc the binding doesn't fit the current APIs.
> 
> As for the whole `NULL` value thing, I was wondering if we could just add another modifier to function arguments `IGNORE/ALLOW NULLS`?

Yes I think that makes sense, maybe another system already implements that? Functions would need to explicitly support it though because otherwise they might read uninitialized data accidentally.

**Comment by hawkfish** [comment]
New approach:

- Add NULL handling to `arg_xxx`
- Rewrite ordered `first` and friends to use them

Performance benchmark:

image

File: src/optimizer/rule/ordered_aggregate_optimizer.cpp [hunk 1]
```diff
@@ -24,6 +30,90 @@ unique_ptr<Expression> OrderedAggregateOptimizer::Apply(LogicalOperator &op, vec
...
+	string arg_xxx_name;
+	if (aggr_name == "last") {
+		arg_xxx_name = "arg_max_null";
+	} else if (aggr_name == "first" || aggr_name == "arbitrary") {
+		arg_xxx_name = "arg_min_null";
+	} else if (aggr_name == "any_value") {
+		arg_xxx_name = "arg_min";
+	}
+
+	if (!arg_xxx_name.empty()) {
```
Comment (Mytherin) [inline src/optimizer/rule/ordered_aggregate_optimizer.cpp:73]: nit: early-out here

File: src/core_functions/aggregate/distributive/functions.json [hunk 2]
```diff
@@ -9,19 +9,35 @@
...
         "type": "aggregate_function_set",
         "aliases": ["argmin", "min_by"]
     },
+    {
+        "name": "arg_min_null",
+        "parameters": "arg,val",
+        "description": "Finds the row with the minimum val. Calculates the arg expression at that row.",
+        "example": "arg_min_null(A,B)",
+        "type": "aggregate_function_set",
+        "aliases": ["argminnull", "min_null_by"]
```
Comment (Mytherin) [inline src/core_functions/aggregate/distributive/functions.json:23]: I wonder if we actually want to expose this to users and document it or if we want to keep it hidden and used only as optimization. The advantage to that is that we don't need to test corner cases that can be introduced by users but can't be introduced by us, e.g. we would only need to implement `BLOB/BIGINT` sorting keys and wouldn't need to support `NULL` there if we were the ones to generate it exclusively.

I would say at least we shouldn't add these aliases. They exist for `arg_min/arg_max` for compatibility with other systems.

File: src/optimizer/rule/ordered_aggregate_optimizer.cpp [hunk 3]
```diff
@@ -24,6 +30,90 @@ unique_ptr<Expression> OrderedAggregateOptimizer::Apply(LogicalOperator &op, vec
...
+		auto sort_key = binder.BindScalarFunction(DEFAULT_SCHEMA, "create_sort_key", std::move(sort_children), error);
+		if (!sort_key) {
+			throw BinderException(error);
+		}
+
+		auto &children = aggr.children;
+		children.emplace_back(std::move(sort_key));
+
+		//  Look up the arg_xxx_name function in the catalog
+		QueryErrorContext error_context(nullptr, 0);
```
Comment (Mytherin) [inline src/optimizer/rule/ordered_aggregate_optimizer.cpp]: This can just be `QueryErrorContext error_context` - no need to provide arguments here

File: test/sql/aggregate/aggregates/test_arg_min_max_null.test [hunk 4]
```diff
@@ -0,0 +1,163 @@
...
+select argmaxnull(1,1)
+----
+1
+
+statement error
+select argmaxnull(*)
+----
+
+query I
+select argmaxnull(i,i) from range (100) tbl(i);
```
Comment (Mytherin) [inline test/sql/aggregate/aggregates/test_arg_min_max_null.test:59]: I think it would be useful to test `FIRST(x ORDER BY y)` and `LAST(x ORDER BY y)` in the tests since that is how they will be used in practice (and it should test both the aggregate and the rewrite at the same time).

File: src/optimizer/rule/ordered_aggregate_optimizer.cpp [hunk 5]
```diff
@@ -24,6 +30,90 @@ unique_ptr<Expression> OrderedAggregateOptimizer::Apply(LogicalOperator &op, vec
...
+		// for each ORDER BY - check if it is actually necessary
+		// expressions that are in the groups do not need to be ORDERED BY
+		// `ORDER BY` on a group has no effect, because for each aggregate, the group is unique
+		// similarly, we only need to ORDER BY each aggregate once
+		expression_set_t seen_expressions;
+		auto &groups = op.Cast<LogicalAggregate>().groups;
+		for (auto &target : groups) {
+			seen_expressions.insert(*target);
+		}
+		vector<BoundOrderByNode> new_order_nodes;
```
Comment (Mytherin) [inline src/optimizer/rule/ordered_aggregate_optimizer.cpp:45]: Could we add some tests that trigger/stress-test this optimization?

File: src/optimizer/rule/ordered_aggregate_optimizer.cpp [hunk 6]
```diff
@@ -24,6 +30,90 @@ unique_ptr<Expression> OrderedAggregateOptimizer::Apply(LogicalOperator &op, vec
...
+		FunctionBinder binder(context);
+		vector<unique_ptr<Expression>> sort_children;
+		for (auto &order : aggr.order_bys->orders) {
+			sort_children.emplace_back(std::move(order.expression));
+
+			string modifier;
+			modifier += (order.type == OrderType::ASCENDING) ? "ASC" : "DESC";
+			modifier += " NULLS";
+			modifier += (order.null_order == OrderByNullType::NULLS_FIRST) ? " FIRST" : " LAST";
+			sort_children.emplace_back(make_uniq<BoundConstantExpression>(Value(modifier)));
```
Comment (Mytherin) [inline src/optimizer/rule/ordered_aggregate_optimizer.cpp:83]: Could we add some tests with ordered aggregates that test all of these cases, and verify that the `NULL` ordering works correctly in all edge cases?

File: src/optimizer/rule/ordered_aggregate_optimizer.cpp [hunk 7]
```diff
@@ -24,6 +30,90 @@ unique_ptr<Expression> OrderedAggregateOptimizer::Apply(LogicalOperator &op, vec
 		changes_made = true;
 		return nullptr;
 	}
+
+	auto &context = rewriter.context;
+	if (context.config.enable_optimizer) {
```
Comment (Mytherin) [inline src/optimizer/rule/ordered_aggregate_optimizer.cpp:35]: I think this condition is not necessary since the `OrderedAggregateOptimizer` is already an optimizer which shouldn't run when optimizations are disabled - IIRC we had this in the code before because we were doing optimizations in the binding phase

**Review by Mytherin — COMMENTED** [review]
Thanks for the updates! Looks great, and even better results. The code looks a lot simpler now as well. Some comments:

File: src/core_functions/aggregate/distributive/arg_min_max.cpp [hunk 8]
```diff
@@ -32,9 +32,15 @@ struct ArgMinMaxStateBase {
 	}
 
 	bool is_initialized;
+	bool arg_null;
 };
 
 // Out-of-line specialisations
+template <>
+void ArgMinMaxStateBase::CreateValue(string_t &value) {
+	new (&value) string_t(uint32_t(0));
```
[the remark this answers is not in the document]
Comment (hawkfish) [reply src/core_functions/aggregate/distributive/arg_min_max.cpp:41]: Sure! I only did this because assignment is more complex. (Also, I once helped a project get rid of huge amounts of code back in the day by converting their C++ object pager to use placement new, but I understand it can seem tasteless at times!)

File: src/core_functions/aggregate/distributive/arg_min_max.cpp [hunk 9]
```diff
@@ -267,16 +290,15 @@ AggregateFunction GetVectorArgMinMaxFunctionBy(const LogicalType &by_type, const
 	}
 }
 
+static const vector<LogicalType> arg_max_by_types = {
```
[the remark this answers is not in the document]
Comment (hawkfish) [reply src/core_functions/aggregate/distributive/arg_min_max.cpp:293]: Good point - I nearly did that but it seemed like overkill.

File: src/optimizer/rule/ordered_aggregate_optimizer.cpp (hunk 1 above)
Comment (hawkfish) [reply src/optimizer/rule/ordered_aggregate_optimizer.cpp:73]: Can do - I just write this way in case there are future operations because it reduces the complexity of diffs.

File: src/core_functions/aggregate/distributive/functions.json (hunk 2 above)
Comment (hawkfish) [reply src/core_functions/aggregate/distributive/functions.json:23]: I'll remove the aliases, but I can see users wanting them (plus it would make binding them more annoying).

File: test/sql/aggregate/aggregates/test_arg_min_max_null.test (hunk 4 above)
Comment (hawkfish) [reply test/sql/aggregate/aggregates/test_arg_min_max_null.test:59]: We actually have a lot of tests that do this (I kept tripping over them...) `test/sql/aggregate/aggregates/test_first_last_any_ordered.test` comes to mind.

File: src/optimizer/rule/ordered_aggregate_optimizer.cpp (hunk 5 above)
Comment (hawkfish) [reply src/optimizer/rule/ordered_aggregate_optimizer.cpp:45]: We already do - I added it because of some failures!

File: src/optimizer/rule/ordered_aggregate_optimizer.cpp (hunk 7 above)
Comment (Mytherin) [reply src/optimizer/rule/ordered_aggregate_optimizer.cpp:35]: Oh, hm, is this optimization now happening twice (also in `src/function/aggregate/sorted_aggregate_function.cpp`)?

I would say it should happen preferably only in the optimizer indeed as it is an optimization - and the binding only does the actual binding of the function.

Comment (hawkfish) [reply src/optimizer/rule/ordered_aggregate_optimizer.cpp]: Turn out there is code that uses this without going through the optimiser (`test/sql/aggregate/distinct/issue8505.test`).

**Comment by hawkfish** [comment]
Two final comments:

- It looks like we can't add "invisible" aggregate functions because the serialisation code complains.
- The `Vector`s in the `ARG_XXX` state were allocated with. capacity of 2048 when they only need 1 row, which should significantly improve memory usage per state.

**Comment by Mytherin** [comment]
Thanks!
