### PR TITLE
Safeguard uses of ColumnDefinition::DefaultValue

### LINKED ISSUE #9745: Error: INTERNAL Error: Calling DefaultValue() on a generated column
### What happens?

I clone the package and build the latest release. When executing `pragma_table_info` on a table with generated columns through the DuckDB CLI, an error is returned, ` Error: INTERNAL Error: Calling DefaultValue() on a generated column`.

I've noticed that a similar bug that has been fixed in https://github.com/duckdb/duckdb/issues/8833.
Since we can properly return the stringified generated expression.
A suggested Fix may be removing the IF branch in the following code.
```c++
// in src/parser/column_definition.cpp
// Remove the IF branch
const unique_ptr<ParsedExpression> &ColumnDefinition::DefaultValue() const {
	if (Generated()) {
		throw InternalException("Calling DefaultValue() on a generated column");
	}
	return expression;
}
```

### To Reproduce

```SQL
create table t1 (c1 int, c2 int generated always as (c1 + 1));
SELECT * FROM pragma_table_info(t1); -- Error: INTERNAL Error: Calling DefaultValue() on a generated column
```

### OS:

Ubuntu 22.04LTS x86

### DuckDB Version:

v0.9.3-dev668 802c71dafc

### DuckDB Client:

CLI

### Full Name:

Jiansen Song

### Affiliation:

Institute of Software Chinese Academy of Sciences

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #9745 

Added `HasDefaultValue` and changed `DefaultValue` to return a reference.
DefaultValue will now assert that HasDefaultValue is true, and HasDefaultValue will return false if the column is a GENERATED column.

### CODE REVIEW

File: src/parser/column_definition.cpp [hunk 1]
```diff
@@ -25,11 +25,16 @@ ColumnDefinition ColumnDefinition::Copy() const {
 	return copy;
 }
 
-const unique_ptr<ParsedExpression> &ColumnDefinition::DefaultValue() const {
+const ParsedExpression &ColumnDefinition::DefaultValue() const {
+	D_ASSERT(HasDefaultValue());
+	return *expression;
```
Comment (Mytherin) [inline src/parser/column_definition.cpp:30]: Can we keep the old `InternalException` here if `HasDefaultValue` is value?
