### PR TITLE
[Dev] Fix issue related to unpacked columns and the NOT operator

### LINKED ISSUE #15290: DuckDB triggers Assertion Failure: children.size() == 1
### What happens?

The latest version of the DuckDB (latest main: v1.1.4-dev3139 07780a0d22) triggers Assertion Failure when running the following SQL statement: 

```sql
CREATE TABLE v00 (c01 INT, c02 STRING); -- Both columns are required. 
PIVOT any_name : ( v00 AS ta5200 NATURAL JOIN v00 AS ta10801 ) ON CASE 'string' WHEN 'string' % c01 THEN NOT * COLUMNS ( * RENAME ( XMLPARSE AS any_name ) ) ->> 'string' END;
```

This error is only reproducible when compiling DuckDB with assertions turned on, e.g., compiled with `make relassert`. The code seems to work properly with released builds and non-assert builds. Just a faulty assertion?

The stack trace for the assertion failure (v1.1.4-dev3139 07780a0d22) is: 

```
#0  duckdb::InternalException::InternalException (this=0x60d0000074f0, Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
msg=) at /home/duckdb/duckdb/src/common/exception.cpp:333
#1  0x000000000202e0ea in duckdb::InternalException::InternalException<char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > (this=0x60d0000074f0, msg=..., params=<incomplete type>, params=<incomplete type>, params=<incomplete type>, 
    params=<incomplete type>) at ../../src/include/duckdb/common/exception.hpp:313
#2  0x0000000001de7c50 in duckdb::DuckDBAssertInternal (condition=<optimized out>, condition_name=<optimized out>, file=<optimized out>, 
    linenr=<optimized out>) at /home/duckdb/duckdb/src/common/assert.cpp:13
#3  0x00000000059f15b6 in duckdb::ExpressionBinder::ResolveNotType (this=0x7fff041ccc50, op=..., children=...)
    at /home/duckdb/duckdb/src/planner/binder/expression/bind_operator_expression.cpp:16
#4  0x00000000059f5806 in duckdb::ExpressionBinder::ResolveOperatorType (this=<optimized out>, op=..., children=...)
    at /home/duckdb/duckdb/src/planner/binder/expression/bind_operator_expression.cpp:77
#5  0x00000000059df531 in duckdb::ExpressionBinder::BindExpression (this=0x7fff041ccc50, op=..., depth=<optimized out>)
    at /home/duckdb/duckdb/src/planner/binder/expression/bind_operator_expression.cpp:183
#6  0x0000000005f8efd8 in duckdb::ExpressionBinder::BindExpression (this=0x7fff041ccc50, expr=..., depth=<optimized out>, root_expression=<optimized out>)
    at /home/duckdb/duckdb/src/planner/expression_binder.cpp:94
#7  0x0000000005e4d929 in duckdb::WhereBinder::BindExpression (this=0x7fff041ccc50, expr_ptr=..., depth=<optimized out>, root_expression=<optimized out>)
    at /home/duckdb/duckdb/src/planner/expression_binder/where_binder.cpp:38
#8  0x0000000005f94308 in duckdb::ExpressionBinder::Bind (this=0x7fff041ccc50, expr=..., depth=<optimized out>, root_expression=<optimized out>)
    at /home/duckdb/duckdb/src/planner/expression_binder.cpp:365
#9  0x0000000005f95f5f in duckdb::ExpressionBinder::BindChild (this=0x7fff041ccc50, expr=..., depth=<optimized out>, error=...)
    at /home/duckdb/duckdb/src/planner/expression_binder.cpp:223
#10 0x00000000059c3967 in duckdb::ExpressionBinder::BindFunction (this=0x7fff041ccc50, function=..., func=..., depth=<optimized out>)
    at /home/duckdb/duckdb/src/planner/binder/expression/bind_function_expression.cpp:110
#11 0x00000000059c11fb in duckdb::ExpressionBinder::BindExpression (this=0x7fff041ccc50, function=..., depth=<optimized out>, expr_ptr=...)
    at /home/duckdb/duckdb/src/planner/binder/expression/bind_function_expression.cpp:93
#12 0x0000000005f90847 in duckdb::ExpressionBinder::BindExpression (this=0x7fff041ccc50, expr=..., depth=<optimized out>, root_expression=<optimized out>)
    at /home/duckdb/duckdb/src/planner/expression_binder.cpp:89
#13 0x0000000005e4d929 in duckdb::WhereBinder::BindExpression (this=0x7fff041ccc50, expr_ptr=..., depth=<optimized out>, root_expression=<optimized out>)
    at /home/duckdb/duckdb/src/planner/expression_binder/where_binder.cpp:38
#14 0x0000000005f94308 in duckdb::ExpressionBinder::Bind (this=0x7fff041ccc50, expr=..., depth=<optimized out>, root_expression=<optimized out>)
    at /home/duckdb/duckdb/src/planner/expression_binder.cpp:365
#15 0x0000000005f95f5f in duckdb::ExpressionBinder::BindChild (this=0x7fff041ccc50, expr=..., depth=<optimized out>, error=...)
    at /home/duckdb/duckdb/src/planner/expression_binder.cpp:223
#16 0x0000000005990d00 in duckdb::ExpressionBinder::BindExpression (this=0x7fff041ccc50, expr=..., depth=<optimized out>)
    at /home/duckdb/duckdb/src/planner/binder/expression/bind_case_expression.cpp:14
#17 0x0000000005f8e6d3 in duckdb::ExpressionBinder::BindExpression (this=0x7fff041ccc50, expr=..., depth=<optimized out>, root_expression=<optimized out>)
    at /home/duckdb/duckdb/src/planner/expression_binder.cpp:67
#18 0x0000000005e4d929 in duckdb::WhereBinder::BindExpression (this=0x7fff041ccc50, expr_ptr=..., depth=<optimized out>, root_expression=<optimized out>)
    at /home/duckdb/duckdb/src/planner/expression_binder/where_binder.cpp:38
#19 0x0000000005f94308 in duckdb::ExpressionBinder::Bind (this=0x7fff041ccc50, expr=..., depth=<optimized out>, root_expression=<optimized out>)
    at /home/duckdb/duckdb/src/planner/expression_binder.cpp:365
#20 0x0000000005f95f5f in duckdb::ExpressionBinder::BindChild (this=0x7fff041ccc50, expr=..., depth=<optimized out>, error=...)
    at /home/duckdb/duckdb/src/planner/expression_binder.cpp:223
#21 0x00000000059dba66 in duckdb::ExpressionBinder::BindExpression (this=0x7fff041ccc50, op=..., depth=<optimized out>)
    at /home/duckdb/duckdb/src/planner/binder/expression/bind_operator_expression.cpp:96
#22 0x0000000005f8efd8 in duckdb::ExpressionBinder::BindExpression (this=0x7fff041ccc50, expr=..., depth=<optimized out>, root_expression=<optimized out>)
    at /home/duckdb/duckdb/src/planner/expression_binder.cpp:94
#23 0x0000000005e4d929 in duckdb::WhereBinder::BindExpression (this=0x7fff041ccc50, expr_ptr=..., depth=<optimized out>, root_expression=<optimized out>)
    at /home/duckdb/duckdb/src/planner/expression_binder/where_binder.cpp:38
#24 0x0000000005f94308 in duckdb::ExpressionBinder::Bind (this=0x7fff041ccc50, expr=..., depth=<optimized out>, root_expression=<optimized out>)
    at /home/duckdb/duckdb/src/planner/expression_binder.cpp:365
#25 0x0000000005f9ab7e in duckdb::ExpressionBinder::Bind (this=<optimized out>, expr=..., result_type=..., root_expression=<optimized out>)
    at /home/duckdb/duckdb/src/planner/expression_binder.cpp:317
#26 0x000000000ad369cd in duckdb::Binder::BindSelectNode (this=0x61900000a580, statement=..., from_table=...)
    at /home/duckdb/duckdb/src/planner/binder/query_node/bind_select_node.cpp:456
#27 0x000000000ad32f35 in duckdb::Binder::BindNode (this=<optimized out>, statement=...)
    at /home/duckdb/duckdb/src/planner/binder/query_node/bind_select_node.cpp:373
#28 0x0000000005fc0f1d in duckdb::Binder::BindNode (this=0x61900000a580, node=...) at /home/duckdb/duckdb/src/planner/binder.cpp:328
#29 0x0000000005fc2483 in duckdb::Binder::Bind (this=0x61900000a580, node=...) at /home/duckdb/duckdb/src/planner/binder.cpp:365
#30 0x0000000005ac79f8 in duckdb::Binder::Bind (this=0x61900000a580, stmt=...) at /home/duckdb/duckdb/src/planner/binder/statement/bind_select.cpp:11
#31 0x0000000005fb5d0a in duckdb::Binder::Bind (this=<optimized out>, statement=...) at /home/duckdb/duckdb/src/planner/binder.cpp:150
#32 0x0000000005b1f60a in duckdb::Binder::Bind (this=0x61900000a580, stmt=...) at /home/duckdb/duckdb/src/planner/binder/statement/bind_create.cpp:737
#33 0x0000000005fb7867 in duckdb::Binder::Bind (this=<optimized out>, statement=...) at /home/duckdb/duckdb/src/planner/binder.cpp:162
#34 0x000000000600a2cc in duckdb::Planner::CreatePlan (this=0x7fff041d03b0, statement=...) at /home/duckdb/duckdb/src/planner/planner.cpp:43
#35 0x0000000006013453 in duckdb::Planner::CreatePlan (this=0x60d0000074f0, statement=...) at /home/duckdb/duckdb/src/planner/planner.cpp:142
#36 0x00000000033b510c in duckdb::ClientContext::CreatePreparedStatementInternal (this=0x616000074790, lock=..., query=..., statement=..., values=...)
    at /home/duckdb/duckdb/src/main/client_context.cpp:340
#37 0x00000000033bb6d4 in duckdb::ClientContext::CreatePreparedStatement (this=0x616000074790, lock=..., query=..., statement=..., values=..., 
    mode=<optimized out>) at /home/duckdb/duckdb/src/main/client_context.cpp:426
#38 0x00000000033dd73a in duckdb::ClientContext::PendingStatementInternal (this=0x616000074790, lock=..., query=..., statement=..., parameters=...)
    at /home/duckdb/duckdb/src/main/client_context.cpp:745
#39 0x00000000033ea364 in duckdb::ClientContext::PendingStatementOrPreparedStatement (this=0x616000074790, lock=..., query=..., statement=..., 
    prepared=..., parameters=...) at /home/duckdb/duckdb/src/main/client_context.cpp:863
#40 0x00000000033d8e48 in duckdb::ClientContext::PendingStatementOrPreparedStatementInternal (this=0x616000074790, lock=..., query=..., statement=..., 
    prepared=..., parameters=...) at /home/duckdb/duckdb/src/main/client_context.cpp:837
#41 0x00000000033e0b9b in duckdb::ClientContext::PendingQueryInternal (this=0x616000074790, lock=..., statement=..., parameters=..., verify=<optimized out>)
    at /home/duckdb/duckdb/src/main/client_context.cpp:1054
#42 0x00000000033f6c5e in duckdb::ClientContext::PendingQuery (this=0x616000074790, statement=..., values=..., allow_stream_result=<optimized out>)
    at /home/duckdb/duckdb/src/main/client_context.cpp:1041
#43 0x00000000033ee170 in duckdb::ClientContext::PendingQuery (this=0x616000074790, statement=..., allow_stream_result=<optimized out>)
    at /home/duckdb/duckdb/src/main/client_context.cpp:1001
#44 0x00000000033ed1d4 in duckdb::ClientContext::Query (this=0x7fff041c84e0, statement=..., allow_stream_result=<optimized out>)
    at /home/duckdb/duckdb/src/main/client_context.cpp:914
#45 0x000000000343c45d in duckdb::Connection::Query (this=<optimized out>, statement=...) at /home/duckdb/duckdb/src/main/connection.cpp:130
#46 0x000000000070493f in duckdb_shell_sqlite3_prepare_v2 (db=0x60f000000a90, zSql=<optimized out>, nByte=<optimized out>, ppStmt=<optimized out>, 
    pzTail=<optimized out>) at ../../tools/sqlite3_api_wrapper/sqlite3_api_wrapper.cpp:201
#47 0x000000000066d9e6 in duckdb_shell::ShellState::ExecuteSQL (this=0x7fff041d2cc0, 
    zSql=0x6120000a4ec0 "PIVOT any_name : ( v00 AS ta5200 NATURAL JOIN v00 AS ta10801 ) ON CASE 'string' WHEN 'string' % c01 THEN NOT * COLUMNS ( * RENAME ( XMLPARSE AS any_name ) ) ->> 'string' END;", pzErrMsg=<optimized out>) at ../../tools/shell/shell.cpp:3524
#48 0x0000000000698f43 in duckdb_shell::ShellState::RunOneSqlLine (this=<optimized out>, zSql=<optimized out>) at ../../tools/shell/shell.cpp:8706
#49 0x000000000068e530 in duckdb_shell::ShellState::ProcessInput (this=0x7fff041d2cc0) at ../../tools/shell/shell.cpp:8936
#50 0x000000000069f1ad in main (argc=<optimized out>, argv=<optimized out>) at ../../tools/shell/shell.cpp:10152
```

### To Reproduce

1. Clone the DuckDB Git from the official repo.
2. Checkout to the latest main (v1.1.4-dev3139 07780a0d22).
3. Compile the DuckDB binary by using `make relassert`. The assertion must be turned on. 
4. Run the compiled DuckDB and input the following SQL:

```sql
CREATE TABLE v00 (c01 INT, c02 STRING); -- Both columns are required. 
PIVOT any_name : ( v00 AS ta5200 NATURAL JOIN v00 AS ta10801 ) ON CASE 'string' WHEN 'string' % c01 THEN NOT * COLUMNS ( * RENAME ( XMLPARSE AS any_name ) ) ->> 'string' END;
```

### OS:

Ubuntu 24.04 LTS

### DuckDB Version:

v1.1.4-dev3139 07780a0d22

### DuckDB Client:

cli

### Hardware:

_No response_

### Full Name:

Yu Liang

### Affiliation:

The Pennsylvania State Univeristy

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #15290 

NOT only expected a single expression, because in the grammar it only takes a single expression
Because of `*COLUMNS(...)` this can expand to multiple expressions

The internal exception has been turned into a binder exception, disallowing the use of *COLUMNS here (if it resolves to more than a single expression)

### CODE REVIEW

File: src/planner/binder/expression/bind_operator_expression.cpp [hunk 1]
```diff
@@ -13,7 +13,11 @@ namespace duckdb {
 
 LogicalType ExpressionBinder::ResolveNotType(OperatorExpression &op, vector<unique_ptr<Expression>> &children) {
 	// NOT expression, cast child to BOOLEAN
-	D_ASSERT(children.size() == 1);
+	if (children.size() != 1) {
```
Comment (Mytherin) [inline src/planner/binder/expression/bind_operator_expression.cpp:16]: I think this is the wrong place to fix the error - NOT operators should not be generated with multiple expressions. I think we should be throwing this error when expanding the `*COLUMNS(*)` expression instead

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Looks good - one comment

File: src/planner/binder/expression/bind_unpacked_star_expression.cpp [hunk 2]
```diff
@@ -50,6 +50,10 @@ static void ReplaceInFunction(unique_ptr<ParsedExpression> &expr, expression_lis
 static void ReplaceInOperator(unique_ptr<ParsedExpression> &expr, expression_list_t &star_list) {
 	auto &operator_expr = expr->Cast<OperatorExpression>();
 
+	if (operator_expr.type == ExpressionType::OPERATOR_NOT) {
```
Comment (Mytherin) [inline src/planner/binder/expression/bind_unpacked_star_expression.cpp:53]: We should probably also check `OPERATOR_IS_NULL/OPERATOR_IS_NOT_NULL` here

Comment (Mytherin) [reply src/planner/binder/expression/bind_unpacked_star_expression.cpp:53]: Or maybe this should just be an opt-in instead? i.e. only make this work for `IN/NOT_IN`

**Comment by Mytherin** [comment]
Thanks!
