### PR TITLE
Write struct fields as optionally quoted in EXPORT DATABASE

### LINKED ISSUE #6410: Export Database strips quotes from struct fields
### What happens?

A struct column containing quoted fields will be exported (to `schema.sql`) without the quotes. This will cause imports to fail if the previously quoted field is a duckdb keyword, or is otherwise not a valid field name when unquoted.

### To Reproduce

```sql
v0.7.1-dev284 6b7362d2ca
...
D create table a (s STRUCT("end" VARCHAR));
D export database 'backup';
D import database 'backup';
Error: Parser Error: syntax error at or near "end"
LINE 4: CREATE TABLE a(s STRUCT(end VARCHAR));
```

### OS:

MacOS Arm

### DuckDB Version:

v0.7.1-dev284

### DuckDB Client:

sql

### Full Name:

Alexander Vandenberg-Rodes

### Affiliation:

Obsidian Security

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #6410 

I have also added optionally quoting for the type part of the struct field, because I figured we could potentially have a user-defined type there.
But when testing I discovered we don't support exporting user-defined types yet, so I had to comment this test out.
Figured it was worth it to keep the quoting in there though, in case we do add exporting of user-defined types in the future.

### CODE REVIEW

File: src/common/types.cpp [hunk 1]
```diff
@@ -424,7 +424,8 @@ string LogicalType::ToString() const {
 		auto &child_types = StructType::GetChildTypes(*this);
 		string ret = "STRUCT(";
 		for (size_t i = 0; i < child_types.size(); i++) {
-			ret += child_types[i].first + " " + child_types[i].second.ToString();
+			ret += KeywordHelper::WriteOptionallyQuoted(child_types[i].first) + " " +
```
Comment (Mytherin) [inline src/common/types.cpp:427]: This should only add quotes to the struct field name, not the actual type, otherwise you get these issues:

```
STRUCT(a "STRUCT(b ""STRUCT(a """"INTEGER"""", b """"VARCHAR"""")"")")	
```

**Comment by Mytherin** [comment]
Thanks!
