### PR TITLE
1-based indexing for lists and strings

### LINKED ISSUE #2575: 0- vs. 1-based indexing
#### What happens?
Arrays use a different index-base (0-based) than Postgres (1-based):

#### To Reproduce
DuckDB:
```sql
D select arr[1] as el from (select array[1,2,3] as arr) sub;
┌────┐
│ el │
├────┤
│ 2  │
└────┘
```

Postgres:
```sql
postgres=# select arr[1] as el from (select array[1,2,3] as arr) sub;
 el 
----
  1
(1 row)
```

We checked what other systems do:

* HyPer/Umbra: 1-based
* BigTable: 0-based
* MySQL: there are not arrays per se, the JSON extractor (`$[...]`) is [0-based](https://dev.mysql.com/doc/refman/5.7/en/json.html)
#### Environment (please complete the following information):
 - OS: n/a
 - DuckDB Version: 0.3.1
 - DuckDB Client: n/a

cc @lnkuiper

### PR DESCRIPTION
**Pull request by taniabogatsch**
This PR changes the indexing from 0-based to 1-based as required by the SQL standard. This effects the the following functions:
- `list_slice`
- `list_extract`, also for strings

Close #2575. Please note that this change might break your queries, if you've been using `list_slice` or `list_extract`.

### CODE REVIEW

File: src/function/scalar/list/list_extract.cpp [hunk 1]
```diff
@@ -39,6 +39,14 @@ void ListExtractTemplate(idx_t count, VectorData &list_data, VectorData &offsets
 		if (list_data.validity.RowIsValid(list_index) && offsets_data.validity.RowIsValid(offsets_index)) {
 			auto list_entry = ((list_entry_t *)list_data.data)[list_index];
 			auto offsets_entry = ((int64_t *)offsets_data.data)[offsets_index];
+
+			// 1-based indexing
+			if (offsets_entry == 0) {
+				result_mask.SetInvalid(i);
+				continue;
+			}
+			offsets_entry = (offsets_entry > 0) ? offsets_entry - 1 : offsets_entry;
```
Comment (Mytherin) [inline src/function/scalar/list/list_extract.cpp:48]: This condition will never be met because of the `if` before it, no?

File: src/function/scalar/list/list_extract.cpp [hunk 2]
```diff
@@ -39,6 +39,14 @@ void ListExtractTemplate(idx_t count, VectorData &list_data, VectorData &offsets
 		if (list_data.validity.RowIsValid(list_index) && offsets_data.validity.RowIsValid(offsets_index)) {
 			auto list_entry = ((list_entry_t *)list_data.data)[list_index];
 			auto offsets_entry = ((int64_t *)offsets_data.data)[offsets_index];
+
+			// 1-based indexing
+			if (offsets_entry == 0) {
```
Comment (Mytherin) [inline src/function/scalar/list/list_extract.cpp:44]: Could we add some tests with indexes/offsets of 0?

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Looks great. Minor comments:

File: src/function/scalar/list/list_extract.cpp (hunk 1 above)
Comment (taniabogatsch) [reply src/function/scalar/list/list_extract.cpp:48]: Doesn't the `if` only cover `offsets_entry == 0`? So `offsets_entry` can still be either `> 0` or `< 0` I think?

File: src/function/scalar/list/list_extract.cpp (hunk 2 above)
Comment (taniabogatsch) [reply src/function/scalar/list/list_extract.cpp:44]: Done, but maybe I missed some more tricky cases...

**Comment by Mytherin** [comment]
Thanks!
