### PR TITLE
[Python] Fix issue with lists containing dictionaries of different sizes

### LINKED ISSUE #11062: Python client crashes when querying lists of differing length structs:  "INTERNAL error: Attempted to access index N with vector of size N"
### What happens?

When querying a DataFrame column that contains structs within lists, differing length structs cause the client to error. This doesn't appear to happen when using read_csv_auto or when querying the data directly, but only occurs when querying a DataFrame.

I don't necessarily expect the client to handle this because trying to run a query like:

```
select        [{
            'key1': 'val1',
        }]
        union all
select        [{
            'key2': 'val2',
            'key3': 'val3',
        }]
```

Errors in a way I'd expect: `Exception: Mismatch Type Error: Type STRUCT(key2 VARCHAR, key3 VARCHAR) does not match with STRUCT(key1 VARCHAR). Cannot cast STRUCTs of different size`. But I would expect that the Python client shows a similar error and doesn't crash the database.

### To Reproduce

Minimal repro:

```
import pandas as pd
import duckdb
df = pd.DataFrame(
    data={
        "col": [
            [
                {
                    "key": "value",
                }
            ],
            [
                {
                    "key": "value",
                    "key1": "value",
                }
            ],
        ]
    }
)


query_str = "select * from df"
with duckdb.connect(database=':memory:') as conn:
    duckdb_df = conn.execute(query_str).df()
```

Outputs:
`duckdb.duckdb.InternalException: INTERNAL Error: Attempted to access index 1 within vector of size 1`

### OS:

MacOS, Linux

### DuckDB Version:

0.8.1, 0.9.2, 10.0.0, duckdb-0.10.1.dev969

### DuckDB Client:

Python

### Full Name:

Kevin Dunn

### Affiliation:

hex Technologies

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #11062

We don't support combining structs of different sizes, but don't throw an exception inside of ForceMaxLogicalType.
So this silently selected one of the two structs as the type to use.

This hit an assertion inside of `TransformDictionaryToStruct` because it is assumed that all structs are of the same type here.

Instead we now traverse the type structure to find out if the structs are of different sizes and properly communicate this downwards.
Resulting in failing to hydrate the `object` into a DuckDBType, and using VARCHAR instead.

### CODE REVIEW

File: tools/pythonpkg/src/pandas/analyzer.cpp [hunk 1]
```diff
@@ -111,38 +117,135 @@ static LogicalType ConvertStructToMap(LogicalType &map_value_type) {
...
+	if (left.IsNested() && right.id() == LogicalTypeId::SQLNULL) {
+		return true;
+	}
+
+	switch (left.id()) {
+	case LogicalTypeId::LIST: {
+		if (right.id() != left.id()) {
+			// Not both sides are LIST, not compatible
+			// FIXME: maybe compatible with ARRAY type??
+			return false;
```
Comment (Mytherin) [inline tools/pythonpkg/src/pandas/analyzer.cpp:138]: Can we add tests that trigger some of these different (new) behaviors?

Comment (Tishj) [reply tools/pythonpkg/src/pandas/analyzer.cpp:138]: I'm not really sure what to add tests for, I believe there is no new behavior here, just a bug in the handling of structs in nested types.

Previously everything was handled with `left = LogicalType::ForceMaxLogicalType`, but that has different rules concerning structs.

```
[
    {'key1': 42}
],
[
    {'key1': 42, 'key2': 42}
]
```

individually these become `STRUCT(key1 integer)[]` and `STRUCT(key1 integer, key2 integer)[]`
When we use ForceMaxLogicalType this just returns whatever is `left` because the types are not considered compatible.

In UpgradeType we turn cases like this into a `MAP(VARCHAR, INTEGER)`

```
[
    {'key1': 42},
    {'key1': 42, 'key2': 42}
]
```

The change that this PR makes is that when combining the previous example, this same behavior now applies

Comment (Tishj) [reply tools/pythonpkg/src/pandas/analyzer.cpp:138]: This PR is only as big as it is because all the other nested types can no longer be handled by `ForceMaxLogicalType` because they *could* contain a STRUCT

Comment (Mytherin) [reply tools/pythonpkg/src/pandas/analyzer.cpp:138]: More tests with nested types with structs in it please

File: tools/pythonpkg/tests/fast/pandas/test_df_object_resolution.py [hunk 2]
```diff
@@ -329,6 +363,67 @@ def test_map_fallback_nullkey_coverage(self, pandas, duckdb_cursor):
         ):
             converted_col = duckdb_cursor.sql("select * from x").df()
 
+    @pytest.mark.parametrize('pandas', [NumpyPandas(), ArrowPandas()])
+    def test_structs_in_nested_types(self, pandas, duckdb_cursor):
```
Comment (Tishj) [inline tools/pythonpkg/tests/fast/pandas/test_df_object_resolution.py:367]: @Mytherin I added this test, it contains some behavior tests for incompatible struct schemas inside nested types

**Comment by Mytherin** [comment]
Thanks!
