### PR TITLE
Nested/Outer lambda parameters in rhs of inner lambda expressions

### LINKED ISSUE #5795: Nested lambdas fail to bind variables correctly
### What happens?

With nested lambdas (*e.g.*, when using two nested `list_apply`), any variable binding performed by the outer lambda appears to be "overwritten" by the variable binding performed by the inner lambda.

### To Reproduce

Buggy behaviour:

~~~
                                      unexpectedly carries y's binding (y "overwrites" x)
                                                      ↓
SELECT list_apply([1,2], x -> list_apply([3,4], y -> (x,y))) AS bug;  
┌──────────────────────────────────────────────────────────────────────────────┐
│                                     bug                                      │
│                       struct(x integer, y integer)[][]                       │
├──────────────────────────────────────────────────────────────────────────────┤
│ [[{'x': 3, 'y': 3}, {'x': 4, 'y': 4}], [{'x': 3, 'y': 3}, {'x': 4, 'y': 4}]] │
└──────────────────────────────────────────────────────────────────────────────┘
~~~

The expected result reads:

~~~
┌──────────────────────────────────────────────────────────────────────────────┐
│                                   expected                                   │
│                       struct(x integer, y integer)[][]                       │
├──────────────────────────────────────────────────────────────────────────────┤
│ [[{'x': 1, 'y': 3}, {'x': 1, 'y': 4}], [{'x': 2, 'y': 3}, {'x': 2, 'y': 4}]] │
└──────────────────────────────────────────────────────────────────────────────┘
~~~

### OS:

macOS 12.5, aarch64

### DuckDB Version:

v0.6.1 919cad22e8

### DuckDB Client:

DuckDB CLI

### Full Name:

Torsten Grust

### Affiliation:

U Tübingen, Germany

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by taniabogatsch**
This PR fixes #5795. It is now possible to use outer lambda parameters in the rhs of inner lambda expressions like so.
```sql
select list_transform([1,2], x -> list_transform([3,4], y -> x + y));
----
[[4, 5], [5, 6]]
```

To enable this, we add a lambda index to the `ColumnBinding` so that we can later (when capturing the lambda parameters) refer to the correct lambda parameter. We also change the binding of the lambda functions to always pass all existing outer lambda parameters to inner functions in reverse order. With this change, we can pass the current list child vector (the current lambda parameter) to the next expression executor call during execution, making the outer lambda parameters accessible in the inner lambdas.

### CODE REVIEW

File: src/planner/binder/expression/bind_function_expression.cpp [hunk 1]
```diff
@@ -165,12 +165,28 @@ BindResult ExpressionBinder::BindLambdaFunction(FunctionExpression &function, Sc
...
+	D_ASSERT(bound_function_expr.children.size() == 2);
+
+	// remove the lambda expression from the children
 	auto lambda = move(bound_function_expr.children.back());
 	bound_function_expr.children.pop_back();
 	auto &bound_lambda = (BoundLambdaExpression &)*lambda;
 
+	// push back (in reverse order) any nested lambda parameters so that we can later use them in the lambda expression
+	// (rhs)
+	if (lambda_bindings) {
```
Comment (Tishj) [inline src/planner/binder/expression/bind_function_expression.cpp:178]:
```suggestion
	if (lambda_bindings) {
		idx_t reference_idx = 0;
		for (idx_t i = lambda_bindings->size(); i > 0; i--) {
			auto idx = i - 1;
			auto& binding = (*lambda_bindings)[idx];
			D_ASSERT(binding.names.size() == 1);
			D_ASSERT(binding.types.size() == 1);
			bound_function_expr.function.arguments.push_back(binding.types[0]);
			auto bound_lambda_param = make_unique<BoundReferenceExpression>(
				binding.names[0],
				binding.types[0],
				reference_idx++);
			bound_function_expr.children.push_back(move(bound_lambda_param));
		}
	}
```

File: src/include/duckdb/planner/column_binding.hpp [hunk 2]
```diff
@@ -16,14 +16,18 @@ namespace duckdb {
 struct ColumnBinding {
 	idx_t table_index;
 	idx_t column_index;
+	idx_t lambda_index;
```
Comment (Mytherin) [inline src/include/duckdb/planner/column_binding.hpp:19]: Modifying the `ColumnBinding` seems rather invasive - as this is used in many different places in the code. Perhaps a cleaner solution would be to create a new expression type for lambda parameters - e.g. a `BoundLambdaRefExpression` - and use that instead of the `BoundColumnRefExpression`.

**Review by lnkuiper — CHANGES_REQUESTED** [review]
Great work!

I agree with Mark's point about BoundLambdaReferenceExpression. I would also like to see a test where we verify that the original lists are not being overwritten:
```sql
create table lists as select [range, range + 1] l from range(3);
select l, [[(x + y, x, y, l) for y in [42, 43] for x in l] from lists;
```

File: src/include/duckdb/planner/column_binding.hpp (hunk 2 above)
Comment (taniabogatsch) [reply src/include/duckdb/planner/column_binding.hpp:19]: Ah yes, that sounds much cleaner. 👍

**Comment by Mytherin** [comment]
Thanks!
