### PR TITLE
Current fix for Issue #5266 Returning error with rowid

### LINKED ISSUE #5266: Fuzzer 8. Returning clause with rowid internal error

### PR DESCRIPTION
**Pull request by Tmonster**
PR to fix https://github.com/duckdb/duckdb/issues/5266. 

Fully supporting rowid in the returning clause is a bit too difficult since inserted data may still be in the transactional log and not yet in storage, so instead we will just throw a binder error.

Also some styling cleanup in this PR.

### CODE REVIEW

File: src/planner/expression_binder/returning_binder.cpp [hunk 1]
```diff
@@ -9,6 +9,11 @@ ReturningBinder::ReturningBinder(Binder &binder, ClientContext &context) : Expre
 
 BindResult ReturningBinder::BindExpression(unique_ptr<ParsedExpression> *expr_ptr, idx_t depth, bool root_expression) {
 	auto &expr = **expr_ptr;
+	if (expr.GetName() == "rowid") {
```
Comment (Mytherin) [inline src/planner/expression_binder/returning_binder.cpp:12]: Can this be moved into the binding of the `ColumnRefExpression`? Using the name of a column is rather error-prone, as names might contain aliases which can cause a false positive here.

Alternatively we might want to use `AddGenericBinding` instead of `AddBaseTable` in `BindReturning` so the rowid column is never exposed to begin with.

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Looks good. One comment:

File: src/planner/expression_binder/returning_binder.cpp (hunk 1 above)
Comment (Mytherin) [reply src/planner/expression_binder/returning_binder.cpp:12]: Yes, that looks good. Aliases are misused somewhat also for named parameters - e.g. perhaps you could add a test with the following function `select struct_pack(row_id := 42);`?

The explicit rowid exception is likely not necessary in `ReturningBinder::BindColumnRef` because of the switch to `AddGenericBinding`, but the more explicit/clear error message is nice.

Comment (Tmonster) [reply src/planner/expression_binder/returning_binder.cpp:12]: Right, I forgot to mention that `AddGenericBinding` throws an error as well, but it's the same error that was thrown before 
```
Binder Error: Referenced column "rowid" not found in FROM clause!
Candidate bindings: "t0.c0"
```
I felt like a user would appreciate a message that rowid isn't supported.

**Review by lnkuiper — APPROVED** [review]

**Comment by Mytherin** [comment]
Thanks for the fixes - the code looks good to me, could you just fix up the CI?

**Comment by Mytherin** [comment]
Thanks!
