### PR TITLE
Fix #12225: revert OVERWRITE_OR_IGNORE to previous behavior, move new behavior to OVERWRITE flag

### LINKED ISSUE #12225: Hive partitioned append/write 0.10.3
### What happens?

Before version 0.10.3, you could enforce partitioned append to a Hive partitioned table by specifying the FILENAME_PATTERN 
property and setting OVERWRITE_OR_IGNORE to true. 
However, since the recent changes (as documented in this GitHub pull request https://github.com/duckdb/duckdb/pull/11787),
 the behavior has been modified. Now I am experiencing breaking changes in my applications.  Is there any alternative approach for partitioned append? The code below  illustrates the problem.

### To Reproduce

```sql
create or replace temp view t_val_v  as 
select *
from ( 
    values 
    ('p_1', 'key_1', 'val_1'),
    ('p_2', 'key_1', 'val_1'),
    ('p_3', 'key_1', 'val_1')
) as t_val(p_key, key, val);
copy (
    select *
    from  t_val_v
) to '/home/da/output_tmp/t_val' (
format parquet,
PARTITION_BY (p_key),
FILENAME_PATTERN "pv1_{i}",
OVERWRITE_OR_IGNORE false
);
copy (
    select *
    from  t_val_v
) to '/home/da/output_tmp/t_val' (
format parquet,
PARTITION_BY (p_key),
FILENAME_PATTERN "pv2_{i}",
OVERWRITE_OR_IGNORE false
);
```

output before. changes (version 0.10.2):

```bash
before 0.10.3 
~/output_tmp/t_val/p_key=p_1$ ls -la
total 16
drwxr-xr-x 2 da da 4096 May 24 10:46 .
drwxr-xr-x 5 da da 4096 May 24 10:44 ..
-rw-r--r-- 1 da da  367 May 24 11:49 pv1_0.parquet
-rw-r--r-- 1 da da  367 May 24 11:49 pv2_0.parquet
```
output with version 0.10.3 (removes all old files)

```bash
~/output_tmp/t_val/p_key=p_1$ ls -la
total 12
drwxr-xr-x 2 da da 4096 May 24 11:51 .
drwxr-xr-x 5 da da 4096 May 24 10:44 ..
-rw-r--r-- 1 da da  367 May 24 11:51 pv2_0.parquet
```

### OS:

windows, ubuntu

### DuckDB Version:

0.10.3

### DuckDB Client:

python

### Full Name:

Daniar Achakeev

### Affiliation:

HMS Analytical Software GmbH

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by Mytherin**
Fixes #12225

This PR reverts `OVERWRITE_OR_IGNORE` to the previous behavior where files are overwritten if they exist, or ignored (left alone) if they do not. The new behavior introduced in https://github.com/duckdb/duckdb/pull/11787 is instead moved to a new flag (`OVERWRITE`). The new flag is more explicit in what it does, and is also explicitly disabled for remote file systems (e.g. S3) where we don't support removing files yet.

### CODE REVIEW

File: src/planner/operator/logical_copy_to_file.cpp [hunk 1]
```diff
@@ -39,7 +39,7 @@ unique_ptr<LogicalOperator> LogicalCopyToFile::Deserialize(Deserializer &deseria
 	auto file_path = deserializer.ReadProperty<string>(200, "file_path");
 	auto use_tmp_file = deserializer.ReadProperty<bool>(201, "use_tmp_file");
 	auto filename_pattern = deserializer.ReadProperty<FilenamePattern>(202, "filename_pattern");
-	auto overwrite_or_ignore = deserializer.ReadProperty<bool>(203, "overwrite_or_ignore");
```
Comment (Tishj) [inline src/planner/operator/logical_copy_to_file.cpp:42]: Don't we need some way to map `true` to `CopyOverwriteMode::COPY_OVERWRITE_OR_IGNORE` for backwards compatibility?
Or is that not as important for LogicalCopyToFile?

Comment (Mytherin) [reply src/planner/operator/logical_copy_to_file.cpp:42]: Booleans are serialized as single bytes - where 0 is false and 1 is true. The new enum is also serialized as a single byte (`CopyOverwriteMode  : uint8_t`), where `0` is `COPY_ERROR_ON_CONFLICT` and 1 is `COPY_OVERWRITE `. So this should be work correctly already.

**Comment by anna-parker** [comment]
Commenting for myself and others, this bug was first shipped with v0.10.3 (that's what Github told me was the first tag that included the commit that introduced the bug per OP)

This fix was then included in v1.0.0.

So it's only v0.10.3 that is affected by this bug.
