### PR TITLE
[C-API] Decimal casting to other type fixes

### LINKED ISSUE #4506: Invalid float-point literal handling in statements like 'SELECT -0.5;'
### What happens?

Hi!

I've spotted something that seems to be a HUGE bug in number handling. 

### To Reproduce

Try the following code:

```c++
duckdb_database db;
duckdb_connection con;

assert(duckdb_open(nullptr, &db) == DuckDBSuccess);
assert(duckdb_connect(db, &con) == DuckDBSuccess);

duckdb_result result;
assert(duckdb_query(con, "SELECT -0.5;", &result) == DuckDBSuccess);

auto type = duckdb_column_type(&result, 0);
auto ff = duckdb_value_double(&result, 0, 0); // 1.8446744073709552E+19
auto str = duckdb_value_varchar(&result, 0, 0); // "18446744073709551611"
```

If we execute a simple query `SELECT -0.5;` the value is treated as a DECIMAL. If I try getting this value as a double, I get a very strange value of 1.8446744073709552E+19. If I try getting this value as a VARCHAR, I get "18446744073709551611". 

If I try to explicitly specify the value type (i.e. `SELECT -0.5::DOUBLE;`), I get the correct value for all of the calls. If I try `SELECT 0.5;` query, I get just `5` for a double and `"5"` for a VARCHAR.

### OS:

macOS

### DuckDB Version:

v0.4.0, da9ee49

### DuckDB Client:

C++

### Full Name:

Ivan Drozdov

### Affiliation:

SMTU

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #4506 

In the C-API Decimals are not being treated as the correct internal type, and the `width` and `scale` of the decimal is not taken into account at all.

Bridges/adapters are built+tested for the following cast operations:

## Cast from DECIMAL

- [x] DECIMAL -> DOUBLE
- [x] DECIMAL -> FLOAT
- [x] DECIMAL -> VARCHAR
- [x] DECIMAL -> HUGEINT
- [x] DECIMAL -> BIGINT
- [x] DECIMAL -> UBIGINT
- [x] DECIMAL -> INTEGER
- [x] DECIMAL -> UINTEGER
- [x] DECIMAL -> SMALLINT
- [x] DECIMAL -> USMALLINT
- [x] DECIMAL -> TINYINT
- [x] DECIMAL -> UTINYINT

## Cast to DECIMAL

- [x] DOUBLE -> DECIMAL
- [x] FLOAT -> DECIMAL
- [x] VARCHAR -> DECIMAL
- [x] HUGEINT -> DECIMAL
- [x] BIGINT -> DECIMAL
- [x] UBIGINT -> DECIMAL
- [x] INTEGER -> DECIMAL
- [x] UINTEGER -> DECIMAL
- [x] SMALLINT -> DECIMAL
- [x] USMALLINT -> DECIMAL
- [x] TINYINT -> DECIMAL
- [x] UTINYINT -> DECIMAL

## Still missing

DECIMAL -> DECIMAL

### CODE REVIEW

**Comment by lokax** [comment]
It seems that `deprecated_duckdb_translate_column()` always writes DECIMAL into an array of hugeint. Maybe there is no need to distinguish the internal type? This is just my opinion, not necessarily correct.

**Comment by Tishj** [comment]
> It seems that `deprecated_duckdb_translate_column()` always writes DECIMAL into an array of hugeint. Maybe there is no need to distinguish the internal type? This is just my opinion, not necessarily correct.

Ah I see, you're right, I missed that.

It also makes sense, because if you want to do anything with this result as a user in C, it's better to have it in a standard format.

**Comment by Tishj** [comment]
Looking at `result-c.cpp:224` and CDecimalConverter<T> it seems like it should not be necessary to fetch them as their internal types (int16_t, int32_t, etc..) but from what I tested it does?

**Comment by Tishj** [comment]
There's something weird going on in prepared statements with DECIMAL
The created plan for binding `634.3453::DECIMAL(7,4)` into the prepared statement: `SELECT CAST($1 AS BIGINT)` in `client_context.cpp:305` is:
```
(lldb) p planner.plan->Print()
┌───────────────────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│   CAST(0.0634 AS BIGINT)  │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│         DUMMY_SCAN        │
└───────────────────────────┘    
```

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR!

So, the C-API internal result set structure has been marked as deprecated for a while (hence the `__deprecated_` tag on all these structures that are being used here, and functions like `CanUseDeprecatedFetch`). The plan has been to switch entirely to a C++ based result set structure, which would allow us to use the standard C++ APIs. The reason the internal result set structure has been kept around is that direct access to that result set structure was provided as part of the API in the past.

I'm not such a big fan of re-architecting the code or adding more functionality around the deprecated result set structure. I would instead prefer to see all the code for that removed, and reimplemented over the C++ result. That should address this issue, and likely many more issues that will arise from essentially re-implementing data element conversions. It would also allow all functions to be used interleaved, instead of having a "deprecated result" and a "non-deprecated result".

**Comment by Tishj** [comment]
Ah that makes sense, but since we have things like `duckdb_decimal` which we expose to the user on the C side, we'll still need most of these changes, no?

Most of this code is just using the existing C++ operators but wrapping them to cast to the `duckdb_decimal` struct

**Comment by Mytherin** [comment]
I don't think we want to add `duckdb_value_decimal_as_properties` and I think having `duckdb_value_decimal` return 0 if the value is not a decimal seems fine to me. The reason `duckdb_value_decimal` exists is to allow for lossless fetching of decimal values - which only applies when the column type is decimal. I don't think it makes much sense to support using this in conjunction with columns of any other type, especially since the code to handle that seems to be quite involved.

File: test/api/capi/test_capi.cpp [hunk 1]
```diff
@@ -263,6 +275,42 @@ TEST_CASE("Test different types of C API", "[capi]") {
...
+	REQUIRE(result->Fetch<int16_t>(0, 0) == 1);
+	REQUIRE(result->Fetch<uint16_t>(0, 0) == 1);
+	REQUIRE(result->Fetch<int32_t>(0, 0) == 1);
+	REQUIRE(result->Fetch<uint32_t>(0, 0) == 1);
+	REQUIRE(result->Fetch<int64_t>(0, 0) == 1);
+	REQUIRE(result->Fetch<uint64_t>(0, 0) == 1);
+	require_hugeint_eq(result->Fetch<duckdb_hugeint>(0, 0), 1, 0);
+	REQUIRE(result->Fetch<float>(0, 0) == 1.2f);
+	REQUIRE(result->Fetch<double>(0, 0) == 1.2);
+	REQUIRE(result->Fetch<string>(0, 0) == "1.2");
```
Comment (Mytherin) [inline test/api/capi/test_capi.cpp:290]: Can we test all five decimal values here instead of only the first value?

File: test/api/capi/test_capi.cpp [hunk 2]
```diff
@@ -423,3 +471,23 @@ TEST_CASE("Issue #2058: Cleanup after execution of invalid SQL statement causes
...
+
+	REQUIRE(duckdb_open(NULL, &db) != DuckDBError);
+	REQUIRE(duckdb_connect(db, &con) != DuckDBError);
+
+	REQUIRE(duckdb_query(con, "SELECT -0.5;", &result) == DuckDBSuccess);
+
+	REQUIRE(duckdb_column_type(&result, 0) == DUCKDB_TYPE_DECIMAL);
+	REQUIRE(duckdb_value_double(&result, 0, 0) == (double)-0.5);
+	auto str = duckdb_value_varchar(&result, 0, 0);
+	REQUIRE(!strcmp(str, "-0.5"));
```
Comment (Mytherin) [inline test/api/capi/test_capi.cpp:488]: Perhaps just use `std::string` here, this looks a bit funky

**Review by Mytherin — COMMENTED** [review]
Thanks for the fixes! Two more minor comments then this is good to go.

**Comment by Mytherin** [comment]
Thanks!
