### PR TITLE
fix(jdbc): arrow error handling

### LINKED ISSUE #7600: JVM segfault when importing Arrow data with `month_day_nano_interval` field
### What happens?

When using the Arrow import functionality of the JDBC driver and querying data with an interval field with the "month day nano" resolution, the entire JVM crashes with the error

```
libc++abi: terminating due to uncaught exception of type duckdb::InvalidInputException: Invalid Input Error: arrow_scan: released schema passed
```

### To Reproduce

[Here is a minimal repro](https://github.com/dylanscott/duckdb_repro) as a git repo, which you can run with Gradle (`./gradlew run` from the root of the repo). But it's pretty simple. We construct an Arrow dataset with the `MONTH_DAY_NANO` interval type, and a single row:

```java
  private static VectorSchemaRoot createIntervalTable() {
    Field interval = new Field("interval",
        FieldType.notNullable(new ArrowType.Interval(IntervalUnit.MONTH_DAY_NANO)),
        /* children */ null);
    Schema schema = new Schema(asList(interval));
    VectorSchemaRoot root = VectorSchemaRoot.create(schema, ALLOCATOR);
    IntervalMonthDayNanoVector vector = (IntervalMonthDayNanoVector) root.getVector(0);
    root.setRowCount(1);
    vector.allocateNew(1);
    vector.set(0, 0, 0, 0);
    return root;
  }
```

Then we query (I am eliding a not very interesting function to convert the `VectorSchemaRoot` into a reader that duckdb can consume):

```java
  public static void main(String[] args) throws IOException, SQLException {
    try (VectorSchemaRoot table = createIntervalTable();
         ArrowReader reader = toReader(table);
         ArrowArrayStream stream = ArrowArrayStream.allocateNew(ALLOCATOR)) {
      Data.exportArrayStream(ALLOCATOR, reader, stream);
      try (DuckDBConnection conn = (DuckDBConnection) DriverManager.getConnection("jdbc:duckdb:")) {
        conn.registerArrowStream("bad", stream);
        try (PreparedStatement stmt = conn.prepareStatement("select count(*) from bad");
             ResultSet rs = stmt.executeQuery()) {
          while (rs.next()) {
            System.out.println(rs.getInt(1));
          }
        }
      }
    }
  }
```

If you change the type of the field to either of the other interval types (`YEAR_MONTH`, `DAY_TIME`) there is no issue.

### OS:

macOS, Linux

### DuckDB Version:

0.8, 0.7.1

### DuckDB Client:

JDBC

### Full Name:

Dylan Scott

### Affiliation:

Hex Technologies

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Mause**
Fixes https://github.com/duckdb/duckdb/issues/7600

Not sure if this is worth including in the bugfix release?

### CODE REVIEW

File: tools/jdbc/src/jni/duckdb_java.cpp [hunk 1]
```diff
@@ -1095,11 +1100,15 @@ class JavaArrowTabularStreamFactory {
...
+		auto stream_ptr = factory->stream_ptr;
+		if (!stream_ptr->release) {
 			throw InvalidInputException("This stream has been released");
 		}
-		factory->stream_ptr->get_schema(factory->stream_ptr, &schema.arrow_schema);
-		return;
+		stream_ptr->get_schema(stream_ptr, &schema.arrow_schema);
+		auto error = stream_ptr->get_last_error(stream_ptr);
+		if (error != nullptr) {
+			throw InvalidInputException(error);
```
Comment (Mause) [inline tools/jdbc/src/jni/duckdb_java.cpp:1110]: Not sure about this error choice

**Comment by Mytherin** [comment]
Thanks for the PR! LGTM. I think this is worth including.
