### PR TITLE
[Casting] Varchar -> Decimal cast fix

### LINKED ISSUE #4489: Issue with decimal scale
### What happens?

Decimal scale incorrectly affects integer side of number.

### To Reproduce

Seems decimal scale is incorrectly affecting the integer part of a decimal:

```
duckdb> select '1.23456789e+8'::DECIMAL(38,0);
┌────────────────────────────────────────┐
│ CAST('1.23456789e+8' AS DECIMAL(38,0)) │
╞════════════════════════════════════════╡
│                              100000000 │
└────────────────────────────────────────┘
Elapsed: 1 ms

duckdb> select '1.23456789e+8'::DECIMAL(38,2);
┌────────────────────────────────────────┐
│ CAST('1.23456789e+8' AS DECIMAL(38,2)) │
╞════════════════════════════════════════╡
│                           123000000.00 │
└────────────────────────────────────────┘
Elapsed: 1 ms

duckdb> select '1.23456789e+8'::DECIMAL(38,4);
┌────────────────────────────────────────┐
│ CAST('1.23456789e+8' AS DECIMAL(38,4)) │
╞════════════════════════════════════════╡
│                         123450000.0000 │
└────────────────────────────────────────┘
Elapsed: 1 ms

duckdb> select '1.23456789e+8'::DECIMAL(38,6);
┌────────────────────────────────────────┐
│ CAST('1.23456789e+8' AS DECIMAL(38,6)) │
╞════════════════════════════════════════╡
│                       123456700.000000 │
└────────────────────────────────────────┘
Elapsed: 1 ms

duckdb> select '1.23456789e+8'::DECIMAL(38,8);
┌────────────────────────────────────────┐
│ CAST('1.23456789e+8' AS DECIMAL(38,8)) │
╞════════════════════════════════════════╡
│                     123456789.00000000 │
└────────────────────────────────────────┘
Elapsed: 1 ms

duckdb> select '1.23456789e+8'::DECIMAL(38,10);
┌─────────────────────────────────────────┐
│ CAST('1.23456789e+8' AS DECIMAL(38,10)) │
╞═════════════════════════════════════════╡
│                    123456789.0000000000 │
└────────────────────
```

Or in python:

```
>>> duckdb.connect().execute("select '1.23456789e+8'::DECIMAL(38,0)").fetchone()
(Decimal('100000000'),)
```

OS:
Mac OS 12.1

DuckDB Version:
0.4.1.dev2142

### Full Name

David L

### Affiliation

None

### OS:

Mac OS 12.1

### DuckDB Version:

0.4.1.dev2142

### DuckDB Client:

Python: (duckdb.cpython-39-darwin.so)

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #4489 

What was happening is that the Scale was used to determine how many decimals we need to preserve
This caused a bug when exponents got involved, because **positive** exponents need up to `exponent` amount of decimals to create an accurate result.

## One last problem
I've fixed every test except for one; `test/issues/monetdb/test_round_bug.test`
This test now causes this error to be thrown:
`Out of Range Error: Overflow in HUGEINT multiplication!`

This happens inside `DecimalCastData::HandleDecimal` in `cast_operators.cpp`
The reason is quite clear, there are too many decimals to fit in a hugeint. This previously passed because only up to `scale` decimals were actually computed into the result.
Since the exponent is only found after all decimals have been encountered, there is no way to safely protect against this.

Since this is quite a performance sensitive part of the code, the solution obviously isn't try-catch

### Possible solutions
Since we're dealing with generics solution one would be, to create a TryMultiply function that's specialized for every type that can be encountered in there (int32_t, int64_t, hugeint_t, etc..) so we can return false from HandleDecimal.
Or possibly not even return false, but just don't record that decimal, the chance we'll need it for the actual result is very slim.

The other solution would be to just mark this test as `statement error`

### Update

I've fixed it so now the problematic test also passes!
```c++
		//! If we expect an exponent, we need to preserve the decimals
		//! But we don't want to overflow, so we prevent overflowing the result with this check
		if (state.digit_count + state.decimal_count >= DecimalWidth<decltype(state.result)>::max) {
			return true;
		}
```
This was the key to fixing the issue :D

The last thing that's failing is ODBC, but I'm not sure if it's a bug or a fix?
image
(left is old, right is new)

## Closing words

TruncateExcessiveDecimals is the main thing that this PR adds, it is never used if ALLOW_EXPONENT is false
What it does is remove extra decimals that are not needed.
These decimals had to be allowed because the exponent is not known until the very end, and in the case of **positive** exponents, these decimals might be needed.

If the exponent is positive, then any decimals after `state.scale + exponent` are removed and rounding is applied to the result.
If the exponent is not present or was negative, then any decimals after `state.scale` are removed, rounding is **not** applied in this case.

For negative exponents a new change is that rounding is now applied to the result after applying the exponent.

### CODE REVIEW

**Comment by Tishj** [comment]
The query the ODBC runs that now fails is essentially:
```sql
query I
SELECT '1234.567890'::numeric AS numeric_col
----
1234.568
```
(the produced output is below it)

The non-varchar version produces different output
```
query I
SELECT 1234.567890::numeric AS numeric_col
----
1234.567
```

So it's probably something I need to fix

File: src/common/operator/cast_operators.cpp [hunk 1]
```diff
@@ -1542,7 +1546,27 @@ struct DecimalCastOperation {
...
+				state.excessive_decimals = decimal_excess - exponent;
+				exponent = 0;
+			} else {
+				exponent -= decimal_excess;
+			}
+			D_ASSERT(exponent >= 0);
+		} else if (exponent < 0 && decimal_excess) {
+			//! Negative exponents dont require any extra digits
+			state.excessive_decimals = -exponent + decimal_excess;
+			exponent = 0;
```
Comment (Tishj) [inline src/common/operator/cast_operators.cpp:1565]: This somehow looks wrong?
As soon as we have *any* excess decimals, the negative exponent is completely ignored?

File: src/common/operator/cast_operators.cpp [hunk 2]
```diff
@@ -1579,11 +1608,45 @@ struct DecimalCastOperation {
...
+	}
+
+	template <class T, bool NEGATIVE>
 	static bool Finalize(T &state) {
-		// if we have not gotten exactly "scale" decimals, we need to multiply the result
-		// e.g. if we have a string "1.0" that is cast to a DECIMAL(9,3), the value needs to be 1000
-		// but we have only gotten the value "10" so far, so we multiply by 1000
+		if (state.excessive_decimals) {
+			//! Encountered an exponent
+			if (!TruncateExcessiveDecimals<T, NEGATIVE>(state)) {
```
Comment (Tishj) [inline src/common/operator/cast_operators.cpp:1637]: if the 'else if' case is checked before this, then the two TruncateExcessiveDecimals calls can be unified

File: src/common/operator/cast_operators.cpp [hunk 3]
```diff
@@ -1552,7 +1576,7 @@ struct DecimalCastOperation {
 			}
 			return true;
 		} else {
-			// positive exponent: append 0's
+			//  positive exponent: append 0's
```
Comment (Tishj) [inline src/common/operator/cast_operators.cpp:1579]: nitpick: fix this indentation 😅

**Review by Tishj — COMMENTED** [review]
Notes to self:

**Comment by Tishj** [comment]
Found another discrepancy between casting from VARCHAR->DECIMAL and DECIMAL->DECIMAL
```sql
query I
select '+1234.56789e-1'::DECIMAL(38,5)
----
123.45678

query I
select +1234.56789e-1::DECIMAL(38,5)
----
123.45679
```

File: src/common/operator/cast_operators.cpp (hunk 1 above)
Comment (Tishj) [reply src/common/operator/cast_operators.cpp]: This is not wrong, because TruncateExcessiveDecimals is almost identical to the logic that happens to negative exponents, adding it to 'excessive_decimals' makes the negative exponent logic obsolete in this case.

In the new (hopefully last) update TruncateExcessiveDecimals in this case is performed as if no exponent was encountered, and the exponent is carried out after the Finalize step.

File: test/sql/types/decimal/test_decimal_from_string.test [hunk 4]
```diff
@@ -4,6 +4,26 @@
 #statement ok
 #pragma enable_verification
 
+query I
+select '+1e-1'::DECIMAL(38,3)
```
Comment (hannes) [inline test/sql/types/decimal/test_decimal_from_string.test:8]: Maybe we should have a bit more tests there, e.g. with exponents other than -1?

Comment (Tishj) [reply test/sql/types/decimal/test_decimal_from_string.test:8]: Ah those are just duplicates of the cases I was last debugging that I forgot to take out.

If you look below there is a monstrosity of 4 nested foreach loops that make up 1400 assertions comparing many variations of pos/neg number, pos/neg exponent, a range of different exponent values and a range of scales

**Comment by Tishj** [comment]
Just saw a comment that feels relevant to this pr
```c++
// while integer division is slow, hugeint division is MEGA slow
```
This PR adds more division to the common case, because of the extra decimals that are accepted and now need to be truncated

**Comment by hannes** [comment]
correctness > performance

**Comment by panda-34** [comment]
Here's a problem:

D `select '9.9999999999999999e+27'::DECIMAL(33,11);`
Error: Conversion Error: Could not convert string "9.9999999999999999e+27" to DECIMAL(33,11)

The error is correct.

Here I only add an insignificant zero at the end
D `select '9.99999999999999990e+27'::DECIMAL(33,11);`
Error: Out of Range Error: Overflow in HUGEINT multiplication!

This is an exception which screws up Value::TryCastAs function which throws instead of returning false.

Even more interesting:
D `select '9.999999999999e+25'::DECIMAL(37,12);`
Error: Conversion Error: Could not convert string "9.999999999999e+25" to DECIMAL(37,12)

The error is correct.

Add another '9' at the end and suddenly:
D `select '9.9999999999999e+25'::DECIMAL(37,12);`
```
┌───────────────────────────────────────────────┐
│ CAST('9.9999999999999e+25' AS DECIMAL(37,12)) │
├───────────────────────────────────────────────┤
│ 99999999999999000000000000.000000000000       │
└───────────────────────────────────────────────┘

```
The result is actually DECIMAL(38,12), there's 26 digits in the integer part.
