### PR TITLE
Fix #7263

### LINKED ISSUE #7263: INTERNAL Error: Invalid unicode (byte sequence mismatch) detected in segment statistics update
### What happens?

```text
Appender10MRows	1	2.634649
Appender10MRows	2	2.635860
Appender10MRows	3	2.641729
Appender10MRows	4	2.636160
Appender10MRows	5	2.630352
Appender10MRowsPrimaryKey	1	8.375196
Appender10MRowsPrimaryKey	2	terminate called after throwing an instance of 'duckdb::InternalException'
  what():  INTERNAL Error: Invalid unicode (byte sequence mismatch) detected in segment statistics update
```

### To Reproduce

Normal Performance Test, called by
```shell
build/release/benchmark/benchmark_runner
```

### OS:

Linux archlinux 6.2.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 20 Apr 2023 16:11:55 +0000 x86_64 GNU/Linux

### DuckDB Version:

Latest Git

### DuckDB Client:

Shell

### Full Name:

Andreas Reichel

### Affiliation:

manticore-projects Co. Ltd.

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by carlopi**
Two minor non-connected fixes, one related to using potentially uninitialised field in benchmark runner (depends on compiler flags AND not deterministic), one related to string_t ending up being inlined when 0 length (here unsure what the problem could be, or if it makes sense to merge, being it's only can happen in degenerated cases during debug).

I believe this fixes #7263.

### CODE REVIEW

File: src/include/duckdb/common/types/string_type.hpp [hunk 1]
```diff
@@ -65,7 +65,12 @@ struct string_t {
 	}
 
 	bool IsInlined() const {
+#ifndef DUCKDB_DEBUG_NO_INLINE
```
Comment (Mytherin) [inline src/include/duckdb/common/types/string_type.hpp:68]: Is this change necessary as part of this PR? I believe there is a reason zero-length strings are inlined even with the debug setting.

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Comments below

**Comment by Mytherin** [comment]
Thanks!
