### PR TITLE
Resolve the conflict between the CTE name and the referring table name.

### LINKED ISSUE #5673: Referring to an object inside a CTE with the same name mistakenly thinks you're being recursive
### What happens?

```sql
with

orders as (

    select * from analytics.orders

),
```

this will complain to me that i need to use `with recursive`, even though one of these is a database object and the other is a CTE, and it should probably be able to sort out which is which. i could understand if it was purely 'orders' in both places but that's not the case.

### To Reproduce

Try something like the below in a query, substituting orders for anything available, just make sure the CTE name and the db object have the same name.

```sql
with

orders as (

    select * from analytics.orders

),
```

### OS:

Intel macOS 13

### DuckDB Version:

0.6.1

### DuckDB Client:

SQL via duckdbt adapter

### Full Name:

Gwen Windflower

### Affiliation:

dbt Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by douenergy**
Fix https://github.com/duckdb/duckdb/issues/5673 and https://github.com/duckdb/duckdb/issues/4987

Provide a clear error message and guide for the case of CTE name and table name shadowing.

❌
```sql
with
orders as (
    select * from stg_orders
    where ordered_at >= (select max(ordered_at) from orders)
),
some_more_logic as (
    select *
    from orders
)
select * from some_more_logic;
```
Error: Binder Error: Circular reference to CTE "orders", There are two possible solutions.
1. use WITH RECURSIVE to use recursive CTEs.
2. If you want to use the TABLE name "orders" the same as the CTE name, please explicitly add "SCHEMA" before table name. You can try "main.orders" (main is the duckdb default schema)

✅
```sql
with
orders as (
    select * from stg_orders
    where ordered_at >= (select max(ordered_at) from main.orders) # add schema here 
),
some_more_logic as (
    select *
    from orders
)
select * from some_more_logic;
``` 
So user can explicitly add "SCHEMA"  to the CTE tableref. 

We can pass the schema_name +  table_name to FindCTE, as @aarashy says in (https://github.com/duckdb/duckdb/issues/4987 ) "CTE names are never allowed to be qualified" (Postgres also not allow qualified CTE name). 

If a tableref is qualified, we can confirm that it should not be a CTE name.

### CODE REVIEW

File: src/planner/binder/tableref/bind_basetableref.cpp [hunk 1]
```diff
@@ -21,15 +21,19 @@ unique_ptr<BoundTableRef> Binder::Bind(BaseTableRef &ref) {
 	QueryErrorContext error_context(root_statement, ref.query_location);
 	// CTEs and views are also referred to using BaseTableRefs, hence need to distinguish here
 	// check if the table name refers to a CTE
-	auto found_cte = FindCTE(ref.table_name, ref.table_name == alias);
+	auto found_cte = FindCTE(ref.table_name + ref.schema_name, ref.table_name == alias);
```
Comment (Mytherin) [inline src/planner/binder/tableref/bind_basetableref.cpp:24]: Maybe `FindCTE` should just not be run if the table reference is qualified (i.e. if `ref.schema_name` is not empty)? Adding the schema name to the end might cause weird situations where `schema.table` is equivalent to `tableschema`.

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! LGTM.

One comment:

**Comment by douenergy** [comment]
Code coverage test pass on my fork !
https://github.com/douenergy/duckdb/actions/runs/5599354959

@Mytherin Please take a look.

**Comment by Mytherin** [comment]
Thanks!
