### PR TITLE
Make error message more explicit for when trying to parse SQL types.

### LINKED ISSUE #13293: read_csv: Confusing / inconsistent error message when passing 'MAP' entry in auto_type_candidates parameter
### What happens?

When using the `auto_type_candidates` option to `read_csv` and passing in an entry `'MAP'` we get a confusing error message that also points to the wrong line - at least from the perspective of the user (I think the line number refers to a sql statement ran internally inside the csv reader, not to the context of the statement submitted by the user.)

I know that `auto_type_candidates` does not accept just any data type name, but I think passing in an unqualified 'LIST' is functionally similar and that does result in a sensible error message.

### To Reproduce

```sql
WITH
  cte1 AS (
    SELECT 1
  ),
  cte2 AS (
    SELECT *
    FROM read_csv('all_types_test.csv', auto_type_candidates=['MAP'])
  )
SELECT * 
FROM cte2;
```
[all_types_test.csv](https://github.com/user-attachments/files/16479247/all_types_test.csv)

results in this error:

```
Parser Error: syntax error at or near ")"
LINE 4: )
```
This is just not correct. We can take lines 1..4 and do a select on ct1 and it executes so whatever is the matter, it cannot be a Parser Error on line 4.

As you can see, 

Passing in the - also unsupported - 'LIST' datatype returns a more sensible message:

`Parser Error: LIST is not valid as a stand-alone type`

### OS:

windows 11 enterprise

### DuckDB Version:

v1.0.1-dev3762 566eb853c8

### DuckDB Client:

CLI

### Full Name:

Roland Bouman

### Affiliation:

EPAM Systems BV Netherlands

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by pdet**
Example:
```sql
SELECT * FROM read_csv_auto ('__TEST_DIR__/csv_file.csv', auto_type_candidates=['MAP']);
```

Previous Error Message:
```
Parser Error: syntax error at or near ")"
LINE 1: SELECT * FROM read_csv_auto ('duckdb_unittest_tempdir/3960/csv_fil...
```

New Error Message:
```
Invalid Input Error: Value "MAP" can not be converted to a DuckDB Type.
Possible examples as suggestions: 
* MAP(INTEGER, VARCHAR)
* SMALLINT
* USMALLINT
* TIMESTAMPTZ	
* DECIMAL(prec, scale)
```

Fix: #13293

### CODE REVIEW

File: src/storage/write_ahead_log.cpp [hunk 1]
```diff
@@ -280,8 +280,9 @@ void WriteAheadLog::WriteCreateIndex(const IndexCatalogEntry &entry) {
 
 	// now serialize the index data to the persistent storage and write the index metadata
 	auto &duck_index_entry = entry.Cast<DuckIndexEntry>();
+	auto &table_idx_list = duck_index_entry.GetDataTableInfo().GetIndexes();
+	lock_guard<mutex> lock(table_idx_list.indexes_lock);
 	auto &indexes = duck_index_entry.GetDataTableInfo().GetIndexes().Indexes();
```
Comment (Mytherin) [inline src/storage/write_ahead_log.cpp:285]: Can this be rewritten to use `indexes.Scan` instead of exposing the `indexes_lock` internal?

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! LGTM - one comment

**Comment by Mytherin** [comment]
Looks like there's some CI failures in extensions due to an interface change (adding `const` to a function) - could you have a look?

**Comment by Mytherin** [comment]
Thanks!
