### PR TITLE
[Python] Support replacement scan on `connection.table(<name>)` method

### LINKED ISSUE #9134: [Python] replacement scans do not work inside the `table` method
### What happens?

When calling `duck.table` and providing it with a table identifier of a variable in scope that should be queryable via a replacement scan (eg a Pandas or Polars dataframe), the DuckDB Python client instead responds with:

    CatalogException: Catalog Error: Table 'df' does not exist!

I discovered this by trying to adopt a common R pattern with `dplyr`/`dbplyr`, where you start your query with a relation formed from a table, and then build on top of it. The Python Relational API equivalent is:

    duckdb.table("my_table").more().methods()

Which is much cleaner that what you currently need to do when your table identifier is a dataframe:

    duckdb.sql("FROM my_table").more().methods()

### To Reproduce

```
df = duckdb.values([1,2,3]).df()

duckdb.table("df")
```

### OS:

Ubuntu 23.04

### DuckDB Version:

0.9.0

### DuckDB Client:

Python

### Full Name:

Ned Letcher

### Affiliation:

Thoughtworks

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #9134

If the table lookup fails, we fall back to creating a `"select * from name"` query and creating a relation out of that, which utilizes the replacement scan functionality.

Added tests for using `table` for various replacement scan candidates.

### CODE REVIEW

File: tools/pythonpkg/src/pyconnection.cpp [hunk 1]
```diff
@@ -969,7 +969,13 @@ unique_ptr<DuckDBPyRelation> DuckDBPyConnection::Table(const string &tname) {
 	if (qualified_name.schema.empty()) {
 		qualified_name.schema = DEFAULT_SCHEMA;
 	}
-	return make_uniq<DuckDBPyRelation>(connection->Table(qualified_name.schema, qualified_name.name));
+	try {
+		return make_uniq<DuckDBPyRelation>(connection->Table(qualified_name.schema, qualified_name.name));
+	} catch (const CatalogException &e) {
+		// CatalogException will be of the type '... is not a table'
+		// Not a table in the database, make a query relation that can perform replacement scans
+		return RunQuery(StringUtil::Format("from %s", tname), tname);
```
Comment (Mytherin) [inline tools/pythonpkg/src/pyconnection.cpp:977]: This should use `KeywordHelper::WriteOptionallyQuoted`, otherwise this will fail on relations that contain e.g. spaces, are keywords, etc. Perhaps you could add a test with a dataframe called e.g. "select":

```py
select = pd.DataFrame.from_dict(..)
duckdb.table('select')
```

Comment (Mytherin) [reply tools/pythonpkg/src/pyconnection.cpp:977]: Another option is to construct the `SelectStatement` programmatically instead of forwarding this to the parser, but this is more work

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! LGTM - one comment:

**Comment by Tishj** [comment]
@Mytherin The failed test is vcpkg related, could you re-run it?

**Comment by Mytherin** [comment]
Thanks!
