### PR TITLE
Make DISTINCT ON respect the ORDER BY clause similar to Postgres + several ordered aggregate improvements

### LINKED ISSUE #2041: SELECT DISTINCT ON does not return the right rows
DuckDB 0.2.7 on Windows 10

Based on [https://stackoverflow.com/a/46567397](https://stackoverflow.com/a/46567397)

The DISTINCT ON clause should be executed after the ORDER BY clause.

Sorry, I'm having trouble properly formatting the SQL from the StackOverflow page.

### LINKED ISSUE #6061: Filter pushdown and pullup doesn't work correctly with DISTINCT operator
### What happens?

A query with distinct gives incorrect results due to filter pushdown.

### To Reproduce

The following two queries gives a result which I think incorrect.

```
D create table t1 (i int, j int);
D insert into t1 values (1, 10), (1, 3), (2, 1), (2, 3);
D select distinct on (i) i, j from t1 order by i, j desc;
┌───────┬───────┐
│   i   │   j   │
│ int32 │ int32 │
├───────┼───────┤
│     1 │    10 │
│     2 │     1 │
└───────┴───────┘
D select * from (select distinct on (i) i, j from t1 order by i, j desc) A where j < 10;
┌───────┬───────┐
│   i   │   j   │
│ int32 │ int32 │
├───────┼───────┤
│     1 │     3 │
│     2 │     1 │
└───────┴───────┘
```
From the plan, we can see the filter `j < 10` is pushed down under DISTINCT.

```
D explain select * from (select distinct on (i) i, j from t1 order by i, j desc) A where j < 10;

┌─────────────────────────────┐
│┌───────────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐
│          ORDER_BY         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          ORDERS:          │
│CAST((t1.i - 1) AS UTINYINT│
│           ) ASC           │
│CAST((t1.j - 1) AS UTINYINT│
│           ) DESC          │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             #0            │
│             #1            │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│       HASH_GROUP_BY       │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             #0            │
│         first(#1)         │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│            t1.i           │
│             #1            │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│          SEQ_SCAN         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             t1            │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             i             │
│             j             │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│ Filters: j<10 AND j IS NOT│
│            NULL           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 0           │
└───────────────────────────┘                             

```
Without query optimization, we can get a more intuitive answer.
```
D PRAGMA disable_optimizer;
┌─────────┐
│ Success │
│ boolean │
├─────────┤
│ 0 rows  │
└─────────┘
D select * from (select distinct on (i) i, j from t1 order by i, j desc) A where j < 10;
┌───────┬───────┐
│   i   │   j   │
│ int32 │ int32 │
├───────┼───────┤
│     2 │     1 │
└───────┴───────┘

```
This is because of the filter pushdown, but I found that the filter pullup is done through DISTINCT as well.

Also, the second row for this query seems incorrect:

```
D select distinct on (i) i, j from t1 order by i, j desc;
┌───────┬───────┐
│   i   │   j   │
│ int32 │ int32 │
├───────┼───────┤
│     1 │    10 │
│     2 │     1 │
└───────┴───────┘
```
I think the correct result is (2, 3) because there's `order by`.

### OS:

Linux

### DuckDB Version:

latest from sources

### DuckDB Client:

Shell and C/C++ API

### Full Name:

Kisung Kim

### Affiliation:

Oracle - This is done only by personal interest on DuckDB.

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### LINKED ISSUE #6524: SELECT DISTINCT ON does not respect ORDER BY
### What happens?

When running a `SELECT DISTINCT ON ... ORDER BY ...` query, I expect DuckDB to return the first row—as defined by the query's `ORDER BY` clause—for each unique DISTINCT ON. Instead, DuckDB picks a random row.

[Postgres docs](https://www.postgresql.org/docs/current/sql-select.html#SQL-DISTINCT) for the behavior I expect.

### To Reproduce

Extracted from a production use case:

```
CREATE TABLE fuzzy_data AS (SELECT * FROM VALUES (1, 2, 'a'), (1, null, 'b'), (2, null, 'c'), (null, 4, 'd') t(a, b, foo));

SELECT DISTINCT ON (t.a)
"__join1"."a" IS NULL as j1a,
"__join1"."b" IS NULL as j1b,
"__join2"."a" IS NULL as j2a,
"__join2"."b" IS NULL as j2b,
FROM VALUES (1) t(a)
LEFT JOIN "fuzzy_data" AS "__join1" ON ("__join1"."a" IS NOT DISTINCT FROM 1 OR "__join1"."a" IS NULL) AND ("__join1"."b" IS NOT DISTINCT FROM 2 OR "__join1"."b" IS NULL)
LEFT JOIN "fuzzy_data" AS "__join2" ON ("__join2"."a" IS NOT DISTINCT FROM 1 OR "__join2"."a" IS NULL) AND ("__join2"."b" IS NOT DISTINCT FROM 3 OR "__join2"."b" IS NULL)
ORDER BY t.a, "__join1"."a" IS NULL, "__join1"."b" IS NULL, "__join2"."a" IS NULL, "__join2"."b" IS NULL;
```

Here's the result of running a few variants of that query in a duckdb 0.7.1 shell:
1. The query above
2. The query minus the `DISTINCT ON (t.a)` part
3. `EXPLAIN` of that query

```
┌─────────┬─────────┬─────────┬─────────┐
│   j1a   │   j1b   │   j2a   │   j2b   │
│ boolean │ boolean │ boolean │ boolean │
├─────────┼─────────┼─────────┼─────────┤
│ false   │ true    │ false   │ true    │
└─────────┴─────────┴─────────┴─────────┘
┌─────────┬─────────┬─────────┬─────────┐
│   j1a   │   j1b   │   j2a   │   j2b   │
│ boolean │ boolean │ boolean │ boolean │
├─────────┼─────────┼─────────┼─────────┤
│ false   │ false   │ false   │ true    │
│ false   │ true    │ false   │ true    │
└─────────┴─────────┴─────────┴─────────┘

┌─────────────────────────────┐
│┌───────────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐
│          ORDER_BY         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          ORDERS:          │
│           #5 ASC          │
│  (__join1.a IS NULL) ASC  │
│  (__join1.b IS NULL) ASC  │
│  (__join2.a IS NULL) ASC  │
│  (__join2.b IS NULL) ASC  │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             #1            │
│             #2            │
│             #3            │
│             #4            │
│             #0            │
│             #5            │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│       HASH_GROUP_BY       │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             #0            │
│         first(#1)         │
│         first(#2)         │
│         first(#3)         │
│         first(#4)         │
│         first(#5)         │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             #4            │
│             #0            │
│             #1            │
│             #2            │
│             #3            │
│             #5            │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│            j1a            │
│            j1b            │
│            j2a            │
│            j2b            │
│             a             │
│             a             │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│     BLOCKWISE_NL_JOIN     │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│            LEFT           ├───────────────────────────────────────────┐
│            true           │                                           │
└─────────────┬─────────────┘                                           │
┌─────────────┴─────────────┐                             ┌─────────────┴─────────────┐
│     BLOCKWISE_NL_JOIN     │                             │           FILTER          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │                             │   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│            LEFT           │                             │ (((a IS NULL) OR (a IS NOT│
│            true           │                             │  DISTINCT FROM 1)) AND ((b│
│                           ├──────────────┐              │    IS NULL) OR (b IS NOT  │
│                           │              │              │     DISTINCT FROM 3)))    │
│                           │              │              │   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│                           │              │              │           EC: 0           │
└─────────────┬─────────────┘              │              └─────────────┬─────────────┘
┌─────────────┴─────────────┐┌─────────────┴─────────────┐┌─────────────┴─────────────┐
│      COLUMN_DATA_SCAN     ││           FILTER          ││          SEQ_SCAN         │
│                           ││   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   ││   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│                           ││ (((a IS NULL) OR (a IS NOT││         fuzzy_data        │
│                           ││  DISTINCT FROM 1)) AND ((b││   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│                           ││    IS NULL) OR (b IS NOT  ││             a             │
│                           ││     DISTINCT FROM 2)))    ││             b             │
│                           ││   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   ││   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│                           ││           EC: 0           ││           EC: 0           │
└───────────────────────────┘└─────────────┬─────────────┘└───────────────────────────┘
                             ┌─────────────┴─────────────┐
                             │          SEQ_SCAN         │
                             │   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
                             │         fuzzy_data        │
                             │   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
                             │             a             │
                             │             b             │
                             │   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
                             │           EC: 0           │
                             └───────────────────────────┘
```

From the query plan it's pretty clear the `ORDER_BY` block is on the wrong side of the `HASH_GROUP_BY` block

### OS:

OSX, M1

### DuckDB Version:

0.7.1

### DuckDB Client:

shell

### Full Name:

Carl Jackson

### Affiliation:

Watershed

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Mytherin**
Fixes #2041, fixes #6061 , fixes #6524

This PR reworks the DISTINCT ON operator so that it orders values not named in the ON list. It does this by pushing the `ORDER BY` clause for any elements not in the target list into the `FIRST` aggregates that are pushed as part of the `DISTINCT ON`. 

For example, a query like this:

```sql
SELECT DISTINCT ON (i) i, j FROM integers ORDER BY i, j DESC;
```

Is now translated into this:

```sql
SELECT i, FIRST(j ORDER BY j DESC) FROM integers GROUP BY i ORDER BY i, j DESC;
```

This makes our `DISTINCT ON` operator match what [Postgres' DISTINCT ON does](https://www.postgresql.org/docs/current/sql-select.html#SQL-DISTINCT).

#### Ordered Aggregates

This PR also includes a number of improvements to ordered aggregates.

* Ordered aggregates are bound during **physical planning** instead of during binding. As a result, the `ORDER BY` information is kept in the optimizer phase, and optimizers and other nodes have insight into the order modifiers of an aggregate.
* We introduce an `AggregateOrderDependent` property that determines for aggregate functions whether or not their input order matches. If an `ORDER BY` clause is used for an aggregate on which this has no effect (e.g. `min`, `max` or `median`) the `ORDER BY` clause is removed.
* We add code that removes redundant/unnecessary entries from the `ORDER BY` lists of aggregates - namely (1) we remove duplicate entries, and (2) we remove any columns that are part of the `GROUP BY` list from the `ORDER BY`. The second can be done because, **within a group**, the entries that are part of the `GROUP BY` are always constant, hence ordering by them does not change the result at all.

### CODE REVIEW

File: src/function/aggregate/distributive/bool.cpp [hunk 1]
```diff
@@ -95,13 +95,15 @@ AggregateFunction BoolOrFun::GetFunction() {
 	auto fun = AggregateFunction::UnaryAggregate<BoolState, bool, bool, BoolOrFunFunction>(
 	    LogicalType(LogicalTypeId::BOOLEAN), LogicalType::BOOLEAN);
 	fun.name = "bool_or";
+	fun.order_dependent = AggregateOrderDependent::NOT_ORDER_DEPENDENT;
```
Comment (hawkfish) [inline src/function/aggregate/distributive/bool.cpp:98]: Is it worth making this the default?

File: src/include/duckdb/function/aggregate_function.hpp [hunk 2]
```diff
@@ -92,7 +93,7 @@ class AggregateFunction : public BaseScalarFunction {
 	                         LogicalType(LogicalTypeId::INVALID), null_handling),
 	      state_size(state_size), initialize(initialize), update(update), combine(combine), finalize(finalize),
 	      simple_update(simple_update), window(window), bind(bind), destructor(destructor), statistics(statistics),
-	      serialize(serialize), deserialize(deserialize) {
+	      serialize(serialize), deserialize(deserialize), order_dependent(AggregateOrderDependent::ORDER_DEPENDENT) {
```
Comment (hawkfish) [inline src/include/duckdb/function/aggregate_function.hpp:96]: Being order dependent is very unusual - I think it makes developing other aggregates simpler to make that the default.

File: src/planner/binder/query_node/plan_query_node.cpp [hunk 3]
```diff
@@ -20,6 +21,17 @@ unique_ptr<LogicalOperator> Binder::VisitQueryNode(BoundQueryNode &node, unique_
 		}
 		case ResultModifierType::ORDER_MODIFIER: {
 			auto &bound = (BoundOrderModifier &)*mod;
+			unique_ptr<BoundOrderModifier> order_by;
```
Comment (hawkfish) [inline src/planner/binder/query_node/plan_query_node.cpp:24]: Nit - this can move next to the loop?

File: src/planner/operator/logical_distinct.cpp [hunk 4]
```diff
@@ -15,6 +15,9 @@ string LogicalDistinct::ParamsToString() const {
 }
 void LogicalDistinct::Serialize(FieldWriter &writer) const {
 	writer.WriteSerializableList(distinct_targets);
+	if (order_by) {
+		throw NotImplementedException("Serializing ORDER BY not yet supported");
```
Comment (hawkfish) [inline src/planner/operator/logical_distinct.cpp:19]: One thing I noticed looking at serializing sorted aggregates is that we are not set up to handle aggregate wrappers. But we may be able to deal with that now?

File: test/optimizer/ordered_aggregate.test [hunk 5]
```diff
@@ -0,0 +1,84 @@
...
+
+query I nosort order_by_none
+EXPLAIN SELECT grp, FIRST(i ORDER BY grp) FROM integers GROUP BY grp ORDER BY grp
+----
+
+query I nosort order_by_none
+EXPLAIN SELECT grp, FIRST(i ORDER BY grp, grp DESC, grp DESC NULLS FIRST) FROM integers GROUP BY grp ORDER BY grp
+----
+
+# ORDER BY is removed from aggregates for which it has no effect
```
Comment (hawkfish) [inline test/optimizer/ordered_aggregate.test:53]: I'm wondering if these sorts of tests should be part of the tests for the aggregate. Not that it hurts to have an example or two here.

File: test/optimizer/ordered_aggregate.test [hunk 6]
```diff
@@ -0,0 +1,84 @@
...
+query I nosort order_by_median
+EXPLAIN SELECT MEDIAN(i ORDER BY i) FROM integers
+----
+
+query I nosort order_by_sum
+EXPLAIN SELECT SUM(i) FROM integers
+----
+
+query I nosort order_by_sum
+EXPLAIN SELECT SUM(i ORDER BY i) FROM integers
```
Comment (hawkfish) [inline test/optimizer/ordered_aggregate.test:83]: One of the interesting things about the old implementation was that if you had some numerical instability with say `SUM(float)`, you could make it deterministic by adding an `ORDER BY`. Not sure that is especially important, but thought I should mention it.  Basically, if someone wants to force ordering, I don't think it is a bad thing to let them.

**Review by hawkfish — COMMENTED** [review]
Looks great - and simple. My only concern is around whether we want to still allow all aggregates to be ordered if the user requests it. I think that would simplify the code and make new aggregate development a bit easier.

File: src/include/duckdb/function/aggregate_function.hpp (hunk 2 above)
Comment (Mytherin) [reply src/include/duckdb/function/aggregate_function.hpp:96]: I thought about that as well, I opted for not doing so for two reasons:

* There are many aggregates that are "surprisingly" order dependent, like the floating point sum that you mentioned, or anything with floating point instabilities. In that case we might still want to allow users to add an `ORDER BY` clause. 
* It is quite tough to automatically test whether or not an aggregate is order dependent - so it is not easy to notify the developer that they have set this property incorrectly. I imagine this will lead to subtle bugs when writing new aggregates. This is essentially opting to perform the ORDER BY unless the developer is certain the aggregate is not order dependent.

File: test/optimizer/ordered_aggregate.test (hunk 6 above)
Comment (Mytherin) [reply test/optimizer/ordered_aggregate.test:83]: I thought about that as well - I only made the integer `SUM` order independent. The floating point sum is still marked as order dependent. I will add a test case for that.
