### PR TITLE
Issue #2965: CTE parameter binding

### LINKED ISSUE #2965: Prepared statement not working with multiple CTEs
#### What happens?

When trying to run a query w/ prepared statement and a CTE, I get an error regardless of how many parameters I pass.

#### To Reproduce

When trying to run this query (or one like it):
```sql
with temp_first as (
    select * from "user" 
    where "name" = ?
), temp_second as (
    select * from "user" 
    where "name" = ?
)

select * from temp_first
```

If I try to execute it like so:
```py
con.execute(query_string, ["val1", "val2"])
```

I get this error, which is incorrect since there should be two arguments to insert:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-90de98a041e9> in <module>
      4 
      5 # pass computed args to data service
----> 6 query_result = hex_data_service.query_dataframe(**_hex_args)
      7 query_result.head(10)
      8 

~/workspace/hex-inc/hex/data-service-python/hex_data_service/sql_cell.py in query_dataframe(templatized_sql_string, **kwargs)
    209     try:
    210         print(query_string)
--> 211         con.execute(query_string, ["val1", "val2"])
    212     except RuntimeError as err:
    213         matcher = re.compile(

RuntimeError: Binder Error: Parameter/argument count mismatch for prepared statement. Expected 1, got 2
```

If I instead only pass 1 like so:
```py
con.execute(query_string, ["val1"])
```

I get the an error which looks correct:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-90de98a041e9> in <module>
      4 
      5 # pass computed args to data service
----> 6 query_result = hex_data_service.query_dataframe(**_hex_args)
      7 query_result.head(10)
      8 

~/workspace/hex-inc/hex/data-service-python/hex_data_service/sql_cell.py in query_dataframe(templatized_sql_string, **kwargs)
    209     try:
    210         print(query_string)
--> 211         con.execute(query_string, ["val1"])
    212     except RuntimeError as err:
    213         matcher = re.compile(

RuntimeError: Prepared statement needs 2 parameters, 1 given
```

#### Environment (please complete the following information):
 - OS: macOS
 - DuckDB Version: unsure, how do I check?
 - DuckDB Client: 0.3.1 (this is the python package version)

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
I tried using `0.3.2.dev1173`

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

### PR DESCRIPTION
**Pull request by hawkfish**
Bind unused CTEs to make sure all parameters get bound.

### CODE REVIEW

**Comment by hannesmuehleisen** [comment]
Implementation looks good to me, there is a failing test still tho: `test/sql/fts/test_indexing.test_slow`

**Comment by hawkfish** [comment]
> Implementation looks good to me, there is a failing test still tho: `test/sql/fts/test_indexing.test_slow`

Ugh it passes on my Mac. Can someone with a Linux box take a look? (NB: It requires the FTS extension.)

File: src/main/prepared_statement_data.cpp [hunk 1]
```diff
@@ -13,23 +13,25 @@ PreparedStatementData::~PreparedStatementData() {
 
 void PreparedStatementData::Bind(vector<Value> values) {
 	// set parameters
-	if (values.size() != value_map.size()) {
+	const auto required = unbound_statement ? unbound_statement->n_param : 0;
```
Comment (Mytherin) [inline src/main/prepared_statement_data.cpp:16]: Perhaps this should be an internal exception if there is no unbound_statement?

File: src/planner/planner.cpp [hunk 2]
```diff
@@ -103,7 +103,9 @@ void Planner::PlanExecute(unique_ptr<SQLStatement> statement) {
 	vector<Value> bind_values;
 	for (idx_t i = 0; i < stmt.values.size(); i++) {
 		ConstantBinder cbinder(*binder, context, "EXECUTE statement");
-		cbinder.target_type = prepared->GetType(i + 1);
+		if (prepared->value_map.count(i + 1)) {
```
Comment (Mytherin) [inline src/planner/planner.cpp:106]: Should we do a check here? It seems like this should be caught earlier on in the process, as this seems to indicate a mismatch in number of prepared statement parameters, no?

**Review by Mytherin — COMMENTED** [review]
Thanks for the updates! Looks great. Some comments:

File: src/main/prepared_statement_data.cpp (hunk 1 above)
Comment (hawkfish) [reply src/main/prepared_statement_data.cpp:16]: It came up at some point, which is why I added the check.

File: src/planner/planner.cpp (hunk 2 above)
Comment (hawkfish) [reply src/planner/planner.cpp:106]: Actually this is the case we are fixing!  The problem is not that there are the wrong number of parameters, but that not all of them are used.  The validation happens in the `Bind` call just below.

File: src/main/prepared_statement_data.cpp (hunk 1 above)
Comment (hawkfish) [reply src/main/prepared_statement_data.cpp:16]: I don't think it is an error, just a pass. Although it does remind me a bit of #3029.

**Review by Mytherin — APPROVED** [review]
