### PR TITLE
Fix schema resolution for unqualified FOREIGN KEY references

### LINKED ISSUE #20530: Insertion into table with schema can fail with "Table with name <table> does not exist!" where <table> is not mentioned in the failing command!
### What happens?

Set a schema, make a table with a foreign key, try to add a row with a foreign key.

The insertion fails with an apparent error in the create table, which succeeded. Although really the create does not have an error.

This error can be avoided by replacing `SET schema=freddy;` with `SET schema=jane.freddy;` in the reproduction code below, but if that is the problem it should have failed on that line.

### To Reproduce

```
duckdb jane.db
```
```
v1.1.3 19864453f7
Enter ".help" for usage hints.
```
```
CREATE SCHEMA freddy;
SET schema=freddy;
CREATE TABLE freddy.zippy(id INTEGER, PRIMARY KEY(id));
CREATE TABLE freddy.george(id INTEGER, zippy_id INTEGER, PRIMARY KEY(id), FOREIGN KEY(zippy_id) REFERENCES zippy(id));
INSERT INTO zippy (id) VALUES(1);
INSERT INTO george (id, zippy_id) VALUES(1, 1);
```
```console
Catalog Error: Table with name zippy does not exist!
Did you mean "jane.freddy.zippy"?
```

Note that the error does not say that `george` does not exist, but the foreign key target `zippy`, which is not mentioned in the failing line.

### OS:

Ubuntu 24.04.2

### DuckDB Version:

v1.1.3 19864453f7

### DuckDB Client:

duckdb CLI

### Hardware:

_No response_

### Full Name:

Tim Band

### Affiliation:

University College London

### Did you include all relevant configuration (e.g., CPU architecture, Linux distribution) to reproduce the issue?

- [x] Yes, I have

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant data sets for reproducing the issue?

Yes

### PR DESCRIPTION
**Pull request by yijiangt**
### Summary

This PR fixes an issue where unqualified FOREIGN KEY references created in a non-default schema could lose the current schema context during binding.

Previously, constraints such as:

```sql
FOREIGN KEY (zippy_id) REFERENCES zippy(id)
```

when created with a non-default schema set as the current schema (e.g. via `SET schema`), could later fail at runtime with `table not found` errors on `INSERT`.

This change defers schema resolution to the bind phase and resolves the referenced table using the session's current schema/search path, consistent with SQL name resolution semantics.

### Tests

Added a regression test `test/sql/constraints/foreignkey/fk_20530.test` covering unqualified foreign key references in a non-default schema.

### Related Issue

Fixes #20530

### CODE REVIEW

**Comment by artjomPlaunov** [comment]
@yijiangt thanks for the PR! I think it's in the right direction although I will leave some comments.

Just some more context for anyone else who reviews this: I did some investigation and what happens here: 

```sql
statement ok
CREATE SCHEMA freddy;

statement ok
SET schema=freddy;

statement ok
CREATE TABLE freddy.zippy(id INTEGER, PRIMARY KEY(id));

statement ok
CREATE TABLE freddy.george(id INTEGER, zippy_id INTEGER, PRIMARY KEY(id), FOREIGN KEY(zippy_id) REFERENCES zippy(id));

statement ok
INSERT INTO freddy.zippy (id) VALUES(1);

statement ok
INSERT INTO freddy.george (id, zippy_id) VALUES(1, 1);
```

is that on the final insert the FK verify append constraint code path has a set catalog (memory) in this case, but an invalid schema since it wasn't set when the FK constraint was being bound. This goes down a valid catalog + invalid schema search path for the schema, which fails to match against ("", freddy) in that path. I think the fix is to just set the schema on ForeignKeyInfo during binding during the CREATE TABLE so that we hit the search logic for set catalog + set schema, instead of the search logic for set catalog + invalid schema, which fails.

File: src/include/duckdb/parser/constraint.hpp [hunk 1]
```diff
@@ -37,6 +37,8 @@ enum class ForeignKeyType : uint8_t {
 struct ForeignKeyInfo {
 	ForeignKeyType type;
 	string schema;
+	bool schema_specified = false;
```
Comment (artjomPlaunov) [inline src/include/duckdb/parser/constraint.hpp]: Why do we need schema_specified?

File: test/sql/constraints/foreignkey/fk_20530.test
Comment (artjomPlaunov) [inline test/sql/constraints/foreignkey/fk_20530.test:1]: Can you add to the test to check that printing still works for default schemas? i.e. I think now it should be 

```sql
SELECT constraint_text FROM duckdb_constraints() WHERE table_name='george' AND constraint_type='FOREIGN KEY';
----
FOREIGN KEY (zippy_id) REFERENCES freddy.zippy(id)
```
but we can also check that we didn't break ToString behavior when the default schema of main is set.

File: src/parser/constraints/foreign_key_constraint.cpp
Comment (artjomPlaunov) [inline src/parser/constraints/foreign_key_constraint.cpp:1]: Can we just check info.schema != DEFAULT_SCHEMA instead? (instead of schema specified)

File: src/planner/binder/statement/bind_create_table.cpp [hunk 2]
```diff
@@ -556,12 +556,18 @@ static void BindCreateTableConstraints(CreateTableInfo &create_info, CatalogEntr
...
+		auto schema_name = fk.info.schema_specified ? fk.info.schema : INVALID_SCHEMA;
+		auto table_entry = entry_retriever.GetEntry(INVALID_CATALOG, schema_name, table_lookup);
 		if (table_entry->type == CatalogType::VIEW_ENTRY) {
 			throw BinderException("cannot reference a VIEW with a FOREIGN KEY");
 		}
 
 		auto &pk_table_entry_ptr = table_entry->Cast<TableCatalogEntry>();
+		
+		fk.info.schema = pk_table_entry_ptr.schema.name;
+		fk.info.table = pk_table_entry_ptr.name;
```
Comment (artjomPlaunov) [inline src/planner/binder/statement/bind_create_table.cpp]: Do we need to set the table? If so, is there a test we can add that checks for this?

File: src/include/duckdb/parser/constraint.hpp (hunk 1 above)
Comment (yijiangt) [reply src/include/duckdb/parser/constraint.hpp]: Removed schema_specified.

File: test/sql/constraints/foreignkey/fk_20530.test
Comment (yijiangt) [reply test/sql/constraints/foreignkey/fk_20530.test:1]: Added a test covering both cases:
- non-default schema prints schema.table
- default main schema prints just table

File: src/parser/constraints/foreign_key_constraint.cpp
Comment (yijiangt) [reply src/parser/constraints/foreign_key_constraint.cpp:1]: Yes. Printing now checks info.schema != DEFAULT_SCHEMA, based on the resolved schema.

File: src/planner/binder/statement/bind_create_table.cpp (hunk 2 above)
Comment (yijiangt) [reply src/planner/binder/statement/bind_create_table.cpp]: No. The table name is already preserved from parsing. Re-set it during binding has no effect, and I couldn’t find a test case where it changes behavior. Already removed the line.

**Comment by artjomPlaunov** [comment]
Looks good to me, thanks! :-)  Although we will need an extra reviewer here to confirm this is the right approach. In the meantime, have you been able to run local CI on your fork?

**Review by artjomPlaunov — APPROVED** [review]

**Review by taniabogatsch — APPROVED** [review]

**Comment by taniabogatsch** [comment]
Looks good from my side if CI passes - let's run the workflows (@lnkuiper).

**Comment by artjomPlaunov** [comment]
@yijiangt some relevant stuff from contributing docs here -- format-fix, merging with main regularly, running the CI on your fork first, draft state, etc., then when it's ready again we can re-run the CI here :-)

**Comment by yijiangt** [comment]
@artjomPlaunov Thanks for the pointer! I’ve run the formatter, rebased on the latest main, and verified the full release test suite locally. The branch is now up to date and ready for CI re-run :-)

**Comment by artjomPlaunov** [comment]
@yijiangt you should run CI on your local fork first (GH actions is free for public forks of open source projects), formatter run doesn't look right.

**Comment by yijiangt** [comment]
@artjomPlaunov I have already run the CI on my local fork and verified all tests pass locally (including make format-fix). The PR is ready for review and the official CI run

**Comment by artjomPlaunov** [comment]
@yijiangt there shouldn't be changes in all the irrelevant files (those were already formatted whenever they were pushed)

**Comment by artjomPlaunov** [comment]
@yijiangt perhaps you ran a different version of the formatter?

**Comment by artjomPlaunov** [comment]
https://github.com/duckdb/duckdb/blob/main/CONTRIBUTING.md#formatting

**Comment by lnkuiper** [comment]
Thanks for the PR! Once the formatting changes that aren't relevant to the fix are undone this is ready to go :)

**Comment by yijiangt** [comment]
Done!

**Comment by artjomPlaunov** [comment]
Thanks! @lnkuiper we can run the CI now 

P.S. @yijiangt first PR always requires explicit approval to run the CI here, but keep in mind the workflow for running local CI first to catch any issues before running the main CI here, I will also update the contributing docs to make that clearer. You can open "draft" pull requests in the future that will allow you to push to the PR/run CI locally first :-)

**Comment by artjomPlaunov** [comment]
Hi @yijiangt we actually have to rebase this to the 1.5-variegata branch since this is a bugfix, sorry. Hopefully you will at least get used to all the workflows in case you want to contribute more! :-) (we have a 1.5 release coming up so we are trying to target bug fixes to that branch right now)

**Comment by taniabogatsch** [comment]
Just adding a bit to Artjom's last comment: we can also merge here, but in that case the changes won't be in the upcoming `v1.5.0` release. So your call, but like Artjom said, we'd prefer the fix to be in ASAP! :D

**Comment by yijiangt** [comment]
Done! I've rebased the changes onto v1.5-variegata and updated the PR base branch. Thanks.

**Comment by artjomPlaunov** [comment]
Great, thank you!

**Comment by artjomPlaunov** [comment]
@lnkuiper this is rebased to 1.5 now, ready for CI
