### PR TITLE
Tuning ART indexes for duplicate values

### LINKED ISSUE #7565: Loading data into table with multiple foreign keys doesn't complete
### What happens?

I am recreating TPCDS SF1 in a database with primary and foreign key declarations. When loading the inventory table with multiple foreign keys, the CLI progress bar gets to 97% and never completes. It appears to still be processing after several hours.

### To Reproduce

In the DuckDB CLI:
```
.open sf1gen
CALL dsdgen(sf=1);
EXPORT DATABASE 'sf1data';
.open sf1fk
CREATE TABLE date_dim ( d_date_sk Integer Not Null PRIMARY KEY, d_date_id String Not Null, d_date Date Not Null, d_month_seq Integer, d_week_seq Integer, d_quarter_seq Integer, d_year Integer, d_dow Integer, d_moy Integer, d_dom Integer, d_qoy Integer, d_fy_year Integer, d_fy_quarter_seq Integer, d_fy_week_seq Integer, d_day_name String, d_quarter_name String, d_holiday String, d_weekend String, d_following_holiday String, d_first_dom Integer, d_last_dom Integer, d_same_day_ly Integer, d_same_day_lq Integer, d_current_day String, d_current_week String, d_current_month String, d_current_quarter String, d_current_year String ) ;
CREATE TABLE warehouse ( w_warehouse_sk Integer Not Null PRIMARY KEY, w_warehouse_id String Not Null, w_warehouse_name String, w_warehouse_sq_ft Integer, w_street_number String, w_street_name String, w_street_type String, w_suite_number String, w_city String, w_county String, w_state String, w_zip String, w_country String, w_gmt_offset Decimal(5,2) ) ;
CREATE TABLE item ( i_item_sk Integer Not Null PRIMARY KEY, i_item_id String Not Null, i_rec_start_date Date, i_rec_end_date Date, i_item_desc String, i_current_price Decimal(7,2), i_wholesale_cost Decimal(7,2), i_brand_id Integer, i_brand String, i_class_id Integer, i_class String, i_category_id Integer, i_category String, i_manufact_id Integer, i_manufact String, i_size String, i_formulation String, i_color String, i_units String, i_container String, i_manager_id Integer, i_product_name String ) ;
CREATE TABLE inventory ( inv_date_sk Integer Not Null REFERENCES date_dim (d_date_sk), inv_item_sk Integer Not Null REFERENCES item (i_item_sk), inv_warehouse_sk Integer Not Null REFERENCES warehouse (w_warehouse_sk), inv_quantity_on_hand Integer ) ;
COPY date_dim FROM 'sf1data\date_dim.csv' (FORMAT 'csv', header 0, delimiter ',', quote '"');
COPY item FROM 'sf1data\item.csv' (FORMAT 'csv', header 0, delimiter ',', quote '"');
COPY warehouse FROM 'sf1data\warehouse.csv' (FORMAT 'csv', header 0, delimiter ',', quote '"');
COPY inventory FROM 'sf1data\inventory.csv' (FORMAT 'csv', header 0, delimiter ',', quote '"');
```

### OS:

Windows 11

### DuckDB Version:

0.8.0

### DuckDB Client:

CLI

### Full Name:

Dan Cory

### Affiliation:

self

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### LINKED ISSUE #11227: Read imdb csv hangs on
### What happens?

This is similar to #10749 but with primary key and foreign key constraints on Debian 12.
When I was loading the `title` table from a csv file, duckdb hung on with 96%.

### To Reproduce

```bash
# download csv files
wget http://homepages.cwi.nl/~boncz/job/imdb.tgz
tar -zxvf imdb.tgz
```

Related schema: `imdb_schema.sql`:
```sql
CREATE TABLE kind_type (
    id integer NOT NULL PRIMARY KEY,
    kind character varying(15) NOT NULL
);

CREATE TABLE title (
    id integer NOT NULL PRIMARY KEY,
    title text NOT NULL,
    imdb_index character varying(12),
    kind_id integer NOT NULL REFERENCES kind_type(id),
    production_year integer,
    imdb_id integer,
    phonetic_code character varying(5),
    episode_of_id integer,
    season_nr integer,
    episode_nr integer,
    series_years character varying(49),
    md5sum character varying(32)
);
```

My script to run:
```bash
#!/bin/bash

rm -f ./imdb.db

# create schema
echo "create imdb schema"
echo -ne ".read imdb_schema.sql" | duckdb ./imdb.db

# load imdb
for table in kind_type title
do
  echo "duckdb load table from ${table}.tbl"
  command="copy ${table} from '${table}.csv' (quote '\"', escape '\\');"
  echo $command
  echo -ne "${command}" | duckdb ./imdb.db
done
```

### OS:

Debian 12

### DuckDB Version:

0.10.0-4a89d97

### DuckDB Client:

CLI

### Full Name:

Pei Mu

### Affiliation:

University of Edinburgh

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by taniabogatsch**
# Tuning ART indexes for duplicate values

This PR contains many changes to significantly improve ART insertion and deletion performance in the presence of duplicate values, which is typically the case for foreign keys.

## Benchmarks

Benchmark:  `benchmark/micro/index/insert/insert_pk_fk.benchmark`.
Source: https://github.com/duckdb/duckdb/issues/7565.

|      | main | PR |
| ----------- | ----------- | ----------- |
| `CALL dsdgen(sf=0.01)`      | 1.1075s       | 0.0685s       |
| `CALL dsdgen(sf=0.1)`   | `TIMEOUT`        | 0.3146s        |
| `CALL dsdgen(sf=0.5)`   | `TIMEOUT`        | 2.2242s        |

## Solution

The main change in this PR is to move away from dedicated `LEAF` nodes storing a linked list of row IDs in the presence of duplicate keys. 

We can inline the row ID directly into its `Node` pointer for unique row IDs. The `Node` pointer of a `Node` usually points to the children at `byte`. If there are no children, i.e., if we reach a leaf, we can store the row ID instead.

This optimization is impossible for duplicate values, where each key has multiple matching row IDs. Before this PR, we used the `LEAF` node type to store these row IDs. However, this means we need to append the row ID to the front or back of the list for any insertion.

- Current leaf option: Appends to the back. Slow insertions and deletions. Straightforward implementation. When introducing the ART, DuckDB did not support foreign keys. Thus, fast insertion and deletion for duplicate values were not relevant. With this solution, we go to the tail and append the row ID. We find the row ID's location for deletions and then replace it with the last row ID in the list.
- Band-aid: Appends to the front. Fast insertions. Slow deletions. Slightly more code complexity.

**Both approaches are undesirable and can cause `O(n^2)` insertion and deletion performance. Thus, we fully refactored the `LEAF` node type, making it redundant for newer storage versions.**

### Nested leaves

Row IDs are of a fixed eight-byte size and always **unique**. They do not differ from `BIGINT` ART keys. Thus, instead of using a different representation for leaves, we can recurse into a nested leaf, again an ART. To do so, we flip a bit in the `Node` pointer previously pointing to the first `LEAF` node. We call this flipped bit a `Gate`. Now, this pointer points to the first node of the nested ART. As we now store row IDs in nested ARTs, we achieve `O(key_len + row_id_len)` insertion and deletion performance for duplicates. We never nest more than one level, as row IDs are unique.

Necessary changes:
- Transform row IDs into ART keys.
- Implement `Gate` logic.
- Refactor many algorithms to work with `Gate` nodes. This refactoring is relevant, especially for prefixes and functions such as `Concatenate`, `Traverse`, and `Split`.
- Refactor scan algorithms. We now scan nested leaves using the same logic as inlined row IDs.
- Refactor the `Construct` (merge) algorithm to recurse into nested leaves.
- Add logic to expand an `INLINED_LEAF` into a nested leaf.
- Add logic to shrink a nested leaf into an `INLINED_LEAF`.
- Implement transformations between nested leaves and old `LEAF` lists.

## Storage size regression

With all these changes in place, we noticed significant performance improvements. However, we also detected a substantial regression in ART storage sizes in the presence of duplicates. While the ART uses vertical compression with prefixes and horizontal compression with the different node types, it is not storage-optimized. The node contains an empty ` Node` pointer for any empty byte in a node, i.e., a byte with no child. In a nested ART, storing two row IDs results takes up the same amount of memory as storing four row IDs differing at the same byte position. If the ART is sparse, this regression is more stark for the `Node48` and the `Node256`.

#### Affected tests

- `test/sql/index/art/vacuum/test_art_vacuum_strings.test_slow`
- `test/sql/index/art/memory/test_art_varchar.test_slow`
- `test/sql/index/art/memory/test_art_non_linear.test_slow`

### Mitigation

We implemented two major mitigation strategies. However, this PR still introduces a slight regression in storage size for indexes with duplicate values.

#### Leaf nodes

We can reconstruct the row ID when traversing the nested ART with slight modifications to the current algorithms. Thus, storing a child pointer or inlining the row ID is unnecessary if the row IDs differ at their last byte position (`sizeof(row_t) - 1`). Therefore, we introduce four new (aligned) node types: `PREFIX_INLINED`, `NODE_7_LEAF`, `NODE_15_LEAF`, and `NODE_256_LEAF`.

#### Adaptive prefix sizes

Currently, each prefix has a fixed size of 15 bytes. To further reduce the memory footprint of the ARTs, especially leaves, we added adaptive prefix sizes. Each ART still has a fixed prefix size, which can differ between ARTs.

We calculate the prefix length for primary keys or unique indexes according to the `key_length`. For ARTs containing nested keys, the minimum of `key_length` and `ROW_ID_PREFIX_COUNT = sizeof(row_t) - 1`. This minimum is required for the `PREFIX_INLINED` node, as we need to guarantee that we can inline `sizeof(row_t) - 1`.

### Limitations

The change for adaptive prefix sizes only takes effect slowly. The first time we serialize an ART to storage, we currently still transform the ART storage to a `1.0.0'—compatible format, i.e., we expanded the prefixes to contain 15 bytes.

## Storage compatibility

The `IndexStorageInfo` now contains an additional property: `case_insensitive_map_t<Value> options;`. Any index, i.e., extension indexes, can write options for this map. On default, the map is empty to ensure compatibility. This change causes the patch to the `vss` extension.

We write a new option for ART indexes: `"v1_0_0_storage": bool`. We write this option if we are **NOT** defaulting to the (older) v.1.0.0. storage. I.e., we only write if `!v1_0_0_storage`.

We use the following check in the WAL and when checkpointing to determine whether to write the older storage format.
```cpp
auto db_options = database.GetDatabase().config.options;
auto v1_0_0_storage = db_options.serialization_compatibility.serialization_version < 3;
```

We then pass the options to the ART serialization code and possibly perform transformations. We only transform in-memory nodes, as any other Nodes and their children already have the target storage format.

We transform each prefix if the ART uses a prefix count that is not DEPRECATED_PREFIX_COUNT.
If we are serializing it to older storage, we transform each nested leaf to the old leaf representation.
We have yet to transform anything when deserializing, as we deserialize the ART lazily. If we encounter a deprecated leaf, we transform it into a nested leaf. We do not change the prefix size to avoid excessive transformations during execution. _Not changing the prefix size during deserialization means only indexes that were never serialized to older storage formats will contain the newer, possibly more memory-efficient, prefix sizes._

## Other notable changes

- In many places, instead of using memory safe types like `optional_ptr`, we now use the unsafe types.
- Removed the `LogicalType` parameter from most `ARTKey` functions. Other small changes to `ARTKeys`.
- The nodes to use significantly more templating. Notably, nodes now implement `Iterator` functions.

### Fixed-size allocator

The `FixedSizeAllocator` now exposes these additional functions:
```cpp
template <class T> 
T *GetInMemoryPtr(const IndexPointer ptr);
data_ptr_t GetInMemoryPtr(const IndexPointer ptr);
idx_t GetSegmentSize() const;
idx_t GetSegmentCount() const;
void RemoveEmptyBuffers();
bool IsEmpty();
```

## Related Issues

- Fixes https://github.com/duckdb/duckdb/issues/7565.
- Fixes https://github.com/duckdblabs/duckdb-internal/issues/841.
- Fixes https://github.com/duckdb/duckdb/issues/11227.

### CODE REVIEW

**Comment by taniabogatsch** [comment]
https://github.com/taniabogatsch/duckdb/pull/4/commits/bf560b1e35ace7a60ef0dfeade3280a67144c071 passed all tests here: https://github.com/taniabogatsch/duckdb/pull/4. However, I pushed some changes afterwards. So possibly some minor hiccups. They should not interfere with the reviewing. 😄

File: src/include/duckdb/execution/index/art/node4.hpp [hunk 1]
```diff
@@ -14,50 +14,136 @@
 
 namespace duckdb {
 
-//! Node4 holds up to four Node children sorted by their key byte
+//! Node4 holds up to four children sorted by their key byte.
 class Node4 {
+	friend class Node16;
+
+public:
+	static constexpr NType NODE_4 = NType::NODE_4;
```
Comment (Mytherin) [inline src/include/duckdb/execution/index/art/node4.hpp:22]: Since the `Node4/Node16` and `Node7Leaf/Node15Leaf` share almost all of their functionality - maybe it would be cleaner to have a shared base class for these that they inherit from, e.g. something like:

```cpp
template<int CAPACITY, NodeType node_type>
class BaseNode {
...
};

class Node4 : public BaseNode<4, NodeType::NODE_4> {
   // ..
};

class Node16 : public BaseNode<16, NodeType::NODE_16> {
   // ..
};
```

File: src/include/duckdb/execution/index/fixed_size_allocator.hpp [hunk 2]
```diff
@@ -42,25 +42,57 @@ class FixedSizeAllocator {
...
 	}
 
+	//! Returns a pointer of type T to a segment, or nullptr, if the buffer is not in memory.
+	template <class T>
+	inline T *GetInMemoryPtr(const IndexPointer ptr) {
+		return (T *)GetInMemoryPtr(ptr);
+	}
+
+	//! Returns the data_ptr_t to a segment, or nullptr, if the buffer is not in memory.
+	inline data_ptr_t GetInMemoryPtr(const IndexPointer ptr) {
```
Comment (Mytherin) [inline src/include/duckdb/execution/index/fixed_size_allocator.hpp:69]: Maybe `GetIfLoaded` is a more descriptive name?

File: src/include/duckdb/execution/index/art/node.hpp [hunk 3]
```diff
@@ -27,107 +24,162 @@ enum class NType : uint8_t {
...
-	//! Get the child for the respective byte in the node
-	optional_ptr<Node> GetChildMutable(ART &art, const uint8_t byte) const;
-	//! Get the first child (immutable) that is greater or equal to the specific byte
-	optional_ptr<const Node> GetNextChild(ART &art, uint8_t &byte) const;
-	//! Get the first child that is greater or equal to the specific byte
-	optional_ptr<Node> GetNextChildMutable(ART &art, uint8_t &byte) const;
-
-	//! Returns the string representation of the node, or only traverses and verifies the node and its subtree
+	//! Get the immutable child at byte.
+	const Node *GetChild(ART &art, const uint8_t byte) const;
```
Comment (Mytherin) [inline src/include/duckdb/execution/index/art/node.hpp:78]: Can we turn these into `unsafe_optional_ptr` instead of a raw pointer?

File: src/include/duckdb/execution/index/art/iterator.hpp [hunk 4]
```diff
@@ -23,60 +23,74 @@ struct IteratorEntry {
...
+	ART &art;
+	//! Stack of nodes from the root to the currently active node.
 	stack<IteratorEntry> nodes;
-	//! Last visited leaf node
+	//! Last visited leaf node.
 	Node last_leaf = Node();
+	//! Holds the row ID of nested leaves.
+	uint8_t row_id[ROW_ID_SIZE];
+	//! True, if we passed a gate.
+	bool in_gate = false;
```
Comment (Mytherin) [inline src/include/duckdb/execution/index/art/iterator.hpp:85]: Maybe we can turn this into an enum?

File: test/sql/storage/shutdown_create_index.test [hunk 5]
```diff
@@ -2,7 +2,6 @@
 # description: CREATE INDEX statement after shutdown
 # group: [storage]
 
-# load the DB from disk
```
Comment (Mytherin) [inline test/sql/storage/shutdown_create_index.test:5]: Could we add a test that interleaves `NULL` values in the index in order to create higher row ids to stress test the handling of differently sized row ids?

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Looks great - some comments:

**Comment by carlopi** [comment]
I tried turning the default to `latest`, as I would assume would eventually become the default, and running CI shows a few failures connected to assertions like:
```
[1201/3938]: test/sql/index/art/storage/test_art_reclaim_storage.test_slow () (Time: 1.3179 seconds)
FAILURE IN RUNNING TEST
--------------------
[0/1] (0%): test/sql/index/art/storage/test_art_reclaim_storage.test_slow       
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
unittest is a Catch v2.13.7 host application.
Run with -? for options

-------------------------------------------------------------------------------
test/sql/index/art/storage/test_art_reclaim_storage.test_slow
-------------------------------------------------------------------------------
/__w/duckdb/duckdb/test/sqlite/test_sqllogictest.cpp:210
...............................................................................

/__w/duckdb/duckdb/test/sqlite/test_sqllogictest.cpp:210: FAILED:
  {Unknown expression after the reported line}
due to a fatal error condition:
  SIGABRT - Abort (abnormal termination) signal

===============================================================================
test cases:  1 |  0 passed | 1 failed
assertions: 51 | 50 passed | 1 failed


--------------------
STDERR
--------------------

terminate called after throwing an instance of 'duckdb::InternalException'
  what():  {"exception_type":"INTERNAL","exception_message":"Invalid node type for GetAllocatorIdx."}
```
(CI run: https://github.com/carlopi/duckdb/actions/runs/10326218614/job/28589335662#step:8:1259, on this diff: https://github.com/carlopi/duckdb/commit/f0723f3c26423c3b95f19dda3f669b94f9416e69)

I would think that:
1. adding a easier way to change default at compile time could come handy (I'd say an independent define via CMake and possibly exposed also to Makefile)
2. adding a CI run that uses `latest` as default, probably based on Linux Release but run as part of nighly
3. fixing whatever pops up

I think 1 is handy to have in any case, since I can see this pattern used again over time, 2 if done as part of nightly is lightweight and allow to test 1.

**Comment by taniabogatsch** [comment]
@carlopi, I'll add a nightly run with your changes in a flag similar to `DUCKDB_ALTERNATIVE_VERIFY`.
```cpp
SerializationCompatibility SerializationCompatibility::Default() {
 #ifdef DUCKDB_ALTERNATIVE_VERIFY
 	auto res = FromString("latest");
 	res.manually_set = false;
 	return res;
 #else
 	auto res = FromString("v0.10.2");
 	res.manually_set = false;
 	return res;
 #endif
 }
```

**Comment by taniabogatsch** [comment]
Updated benchmark times. Everything got a bit faster after fixing everything in the CI. 😄 

|      | main | PR |
| ----------- | ----------- | ----------- |
| `CALL dsdgen(sf=0.01)`      | 1.1075s       | 0.0641s       |
| `CALL dsdgen(sf=0.1)`   | `TIMEOUT`        | 0.2816s        |
| `CALL dsdgen(sf=0.5)`   | `TIMEOUT`        | 2.0628s        |

**Comment by taniabogatsch** [comment]
```
[247/3959] (6%): Test TPCH arrow roundtrip                                      
/home/runner/work/duckdb/duckdb/src/include/duckdb/common/arrow/appender/varchar_data.hpp:20:9: runtime error: null pointer passed as argument 1, which is declared to never be null
[248/3959] (6%): Test Parquet Files round-trip 
```
There are no indexes in these tests. Thus, they are unrelated.

**Comment by Mytherin** [comment]
Agreed, we can pick up the nightly tests next week.

**Comment by Mytherin** [comment]
Thanks!
