### PR TITLE
fix binder: handle errors with over in where inside subquery

### LINKED ISSUE #20263: serialization Error with scalar function + OVER clause in subquery
### What happens?

Using a scalar function with an OVER clause inside a subquery WHERE condition causes DuckDB to fail during query plan serialization with the following error:
```
Serialization Error:
Cannot copy bound expression
```

Instead of producing a clear binder or parser error (e.g. rejecting invalid window function usage), DuckDB fail during plan serialization.
DuckDB should reject the query during parsing or binding with an error such as:
Binder Error: OVER clause used with non-window function
or Window functions are not allowed in WHERE clause

### To Reproduce

```
CREATE TABLE v0 ( v1 INTEGER ) ; 
SELECT ( SELECT to_centuries ( v1 ) FROM v0 WHERE fmod ( fmod ( v1 , 3.100000 ) , 3.100000 ) OVER( ORDER BY v1 ) = 70000 ) AS century_result ;
```
## duckdb client output:
Serialization Error:
Cannot copy bound expression

### OS:

Ubuntu 22.04.1 LTS x86_64

### DuckDB Version:

DuckDB v1.4.1-dev211 (Development Version) 4f797f8

### DuckDB Client:

duckdb executable

### Hardware:

_No response_

### Full Name:

smartfuzz

### Affiliation:

smartfuzz

### Did you include all relevant configuration (e.g., CPU architecture, Linux distribution) to reproduce the issue?

- [x] Yes, I have

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### PR DESCRIPTION
**Pull request by Pranav2612000**
Fixes #20263 

```
memory D SELECT ( SELECT to_centuries ( v1 ) FROM v0 WHERE fmod ( fmod ( v1 , 3.100000 ) , 3.100000 ) OVER( ORDER BY v1 ) = 70000 ) AS century_result ;
Binder Error:
WINDOW expression is not supported here

LINE 1: SELECT ( SELECT to_centuries ( v1 ) FROM v0 WHERE fmod ( fmod ( v1 , 3.100000 ) , 3.100000 ) OVER( ORDER BY...
                                                          ^
memory D

```

### CODE REVIEW

**Comment by Pranav2612000** [comment]
@CR7-source can you take a look? The error was because some 'Expressions' were changed to a 'BoundedExpression' during the first binding. Trying to bind them again, during the error generation part resulted in the error.

The current approach seems to work, but I guess a better way could be to move the 'HasBoundedParts' function to the parent class, and add its support for other types as well ( like `FunctionExpression` ). Let me know what you think and how to proceed

**Comment by pdet** [comment]
Can you run the formatter?

**Comment by Pranav2612000** [comment]
Oops! Sorry! Forgot to run it. I've run it now and pushed

File: src/planner/expression_binder.cpp [hunk 1]
```diff
@@ -365,6 +365,16 @@ ErrorData ExpressionBinder::Bind(unique_ptr<ParsedExpression> &expr, idx_t depth
 		// already bound, don't bind it again
 		return ErrorData();
 	}
+	if (expression.GetExpressionClass() == ExpressionClass::WINDOW) {
+		auto &w = expression.Cast<WindowExpression>();
+		if (w.HasBoundedParts()) {
+			BindResult result =
+			    BindResult(BinderException::Unsupported(*expr, "WINDOW expression is not supported here"));
```
Comment (hawkfish) [inline src/planner/expression_binder.cpp]: Cab we make WINDOW camel case or use uppercase OVER here? Otherwise it might be confused for the [WINDOW clause](https://duckdb.org/docs/stable/sql/query_syntax/window).

**Review by hawkfish — CHANGES_REQUESTED** [review]
Just a small error message nit.

File: src/planner/expression_binder.cpp (hunk 1 above)
Comment (Pranav2612000) [reply src/planner/expression_binder.cpp]: Thanks for the review. I've updated the PR. Is this what you meant?

**Comment by Pranav2612000** [comment]
@lnkuiper all checks seem to be passing. @hawkfish's review comments are also resolved. Is this PR good to be merged in? Or are there any other changes I should do?

**Comment by lnkuiper** [comment]
Thanks!
