### PR TITLE
Change file exist check to is_pipe and do it in the bind

### LINKED ISSUE #7336: Potentially unintended exception in the CSV Reader when checking for parallel execution
### What happens?

While updating our code to run on master,  I stumbled upon an issue with the CSV reader introduce by [the wonderful change of supporting parallel reads](https://github.com/duckdb/duckdb/pull/6977). The problem is with this [line](https://github.com/duckdb/duckdb/blob/master/src/function/table/read_csv.cpp#L795) where the csv reader checks if a file exists to check if the file is on the local file system and thus can support a parallel scan. The issue is that we you run it on an http file (`read_csv_auto('https://github.com/duckdb/duckdb/raw/master/data/csv/customer.csv'`) , it calls the http extension which then [tries to get it's state from the file opener](https://github.com/duckdb/duckdb/blob/master/extension/httpfs/httpfs.cpp#L530), but it's not there because FileExists only gets a file name as a parameter.  

This ends up being masked by [how the httpfs handles exceptions in it's file exists implementation](https://github.com/duckdb/duckdb/blob/master/extension/httpfs/httpfs.cpp#L485) but it may have other side effects I don't oversee. 

I do have a couple of suggestions/questions:
1) Shouldn't this information be captured at bind time? (it already has a file_exists flag, so I got confused by the check at first).
2) Can't this information be derived from the file system? seems like over kill to open the file (over the internet :)).

 

### To Reproduce

Run `select * from read_csv_auto('https://github.com/duckdb/duckdb/raw/master/data/csv/customer.csv'`

### OS:

mac os

### DuckDB Version:

master

### DuckDB Client:

cpp

### Full Name:

Boaz Leskes

### Affiliation:

MotherDuck

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### LINKED ISSUE #7337: ASAN die while querying csv over http
### What happens?

Using master, running the following query causes an asan die:

```
~/src/md/duckdb (master) » ./build/debug/duckdb -unsigned                                                                                                                           boaz@boaz-air
v0.7.2-dev2820 fc797c18cf
Enter ".help" for usage hints.
D LOAD 'build/debug/extension/httpfs/httpfs.duckdb_extension';
D from read_csv_auto('https://github.com/duckdb/duckdb/raw/master/data/csv/customer.csv');
```
results in:
```
==29269==ERROR: AddressSanitizer: heap-use-after-free on address 0x00011bc10ff8 at pc 0x000109addd7c bp 0x00016d0d1720 sp 0x00016d0d1718
READ of size 8 at 0x00011bc10ff8 thread T0
    #0 0x109addd78 in std::__1::__bucket_list_deallocator<std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, duckdb::CachedFile>, void*>*>*>>::size[abi:v15006]() const __hash_table:768
    #1 0x109adce08 in std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, duckdb::CachedFile>, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, duckdb::CachedFile>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, duckdb::CachedFile>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, duckdb::CachedFile>>>::bucket_count[abi:v15006]() const __hash_table:1164
    #2 0x10c763a10 in std::__1::pair<std::__1::__hash_iterator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, duckdb::CachedFile>, void*>*>, bool> std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, duckdb::CachedFile>, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, duckdb::CachedFile>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, duckdb::CachedFile>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, duckdb::CachedFile>>>::__emplace_unique_key_args<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::piecewise_construct_t const&, std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&>, std::__1::tuple<>>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::piecewise_construct_t const&, std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&>&&, std::__1::tuple<>&&) __hash_table:1993
    #3 0x10c6e6018 in std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, duckdb::CachedFile, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, duckdb::CachedFile>>>::operator[](std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) unordered_map:1804
    #4 0x10c6e3a44 in duckdb::HTTPFileSystem::Read(duckdb::FileHandle&, void*, long long, unsigned long long) httpfs.cpp:380
    #5 0x10c6e6778 in duckdb::HTTPFileSystem::Read(duckdb::FileHandle&, void*, long long) httpfs.cpp:449
    #6 0x1080fccc8 in duckdb::FileHandle::Read(void*, unsigned long long) file_system.cpp:400
    #7 0x106e1e704 in duckdb::CSVFileHandle::Read(void*, unsigned long long) csv_file_handle.hpp:91

```

### To Reproduce

see description

### OS:

mac os

### DuckDB Version:

master

### DuckDB Client:

cli

### Full Name:

Boaz Leskes

### Affiliation:

MotherDuck

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by pdet**
Fix: #7336
Fix: #7337

### CODE REVIEW

File: src/function/table/read_csv.cpp [hunk 1]
```diff
@@ -234,6 +234,13 @@ static unique_ptr<FunctionData> ReadCSVBind(ClientContext &context, TableFunctio
 	} else {
 		result->reader_bind = MultiFileReader::BindOptions(options.file_options, result->files, return_types, names);
 	}
+	auto &fs = FileSystem::GetFileSystem(context);
+	for (auto &file : result->files) {
+		if (fs.IsPipe(file)) {
```
Comment (bleskes) [inline src/function/table/read_csv.cpp:239]: stupid question maybe - what's wrong with `FileSystem::OnDiskFile` ? seems to do exactly what we want based on the comment 

```
	//! Whether or not the FS handles plain files on disk. This is relevant for certain optimizations, as random reads
	//! in a file on-disk are much cheaper than e.g. random reads in a file over the network
```
?

also - nit - may add a dedicated field? the check later reads a bit off `bind_data.single_threaded = bind_data.single_threaded || !bind_data.file_exists;` (how can we run single threaded if the file doesn't exist?

Sorry if this doesn't make sense.. I'm happy you found a solution!

Comment (pdet) [reply src/function/table/read_csv.cpp:239]: Yeah, good point. The variable is actually misnamed. Will fix that.

I'm not exactly sure why I went for the `FileExists` function in the first place. The problem is not really if a file is on disk, but rather if it's a pipe. IIRC, the main issue is the combination of the CSV Auto with the Parallel CSV Reader. The parallel reader must start from fresh buffers to keep track of some internal counters, while the single-threaded CSV reader can directly use/continue from the auto buffers. But if it's piped, then the reset of the buffers gets borked.

**Comment by Mytherin** [comment]
Thanks!
