### PR TITLE
Fix #17266：the result of lad/lead when the offset is null

### LINKED ISSUE #17266: The result of LAG/LEAD is non-deterministic value when offset is null
### What happens?

The result of LAG，LEAD is random value when offset is null.

```sql
select c1, c3, c2, lag(c3, c2,BITSTRING'010101010') over (partition by c1 order by c3) from test1 order by c1;
```
┌───────┬──────┬────────┬─────────────────────────────────
  │  c1   │  c3  │   c2   │ lag(c3, c2, CAST('010101010' AS BIT)) OVER (PARTITION BY c1 ORDER BY c3) │
│ int32 │ bit  │ int16  │                                   bit                                    │
├───────┼──────┼────────┼─────────────────────────────────
│     **_0 │ NULL │   NULL │ 010101010_**                                                                │
│     1 │ 101  │  32767 │ 010101010                                                                │
│     2 │ 101  │ -32767 │ 010101010                                                                │
│     3 │ 000  │      0 │ 000                                                                      │
│     4 │ NULL │   NULL │ 010101010                                                                │
└───────┴──────┴────────┴─────────────────────────────────
```sql
select c1, c3, c2, lag(c3, c2,BITSTRING'010101010') over (partition by c1 order by c3) from test1 order by c1;
```
┌───────┬──────┬────────┬─────────────────────────────────
│  c1   │  c3  │   c2   │ lag(c3, c2, CAST('010101010' AS BIT)) OVER (PARTITION BY c1 ORDER BY c3) │
│ int32 │ bit  │ int16  │                                   bit                                    │
├───────┼──────┼────────┼─────────────────────────────────
│     **_0 │ NULL │   NULL │ NULL_**                                                                     │
│     1 │ 101  │  32767 │ 010101010                                                                │
│     2 │ 101  │ -32767 │ 010101010                                                                │
│     3 │ 000  │      0 │ 000                                                                      │
│     4 │ NULL │   NULL │ NULL                                                                     │
└───────┴──────┴────────┴─────────────────────────────────

### To Reproduce

```sql
create table test1(c1 int, c2 smallint, c3 BITSTRING);
insert into test1 values(0, null, null);
insert into test1 values(1, 32767, '101');
insert into test1 values(2, -32767, '101');
insert into test1 values(3, 0, '000');
insert into test1 values(4, null, null);
select c1, c3, c2, lag(c3, c2,BITSTRING'010101010') over (partition by c1 order by c3) from test1 order by c1;
```

### OS:

Ubuntu 24.04.1 LTS

### DuckDB Version:

0069af20abea2660d

### DuckDB Client:

DuckDB SHELL

### Hardware:

_No response_

### Full Name:

Guoji.Ma

### Affiliation:

Personal Project

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

make release  from 0069af20abea2660d

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [x] Yes, I have

### PR DESCRIPTION
**Pull request by ditdb**
fix the result of lad/lead when the offset is null
compatibility with PG

### CODE REVIEW

File: src/function/window/window_value_function.cpp [hunk 1]
```diff
@@ -300,6 +300,10 @@ void WindowLeadLagExecutor::EvaluateInternal(WindowExecutorGlobalState &gstate,
 			auto val_idx = NumericCast<int64_t>(own_row);
 			int64_t offset = 1;
 			if (wexpr.offset_expr) {
+				if (leadlag_offset.CellIsNull(i)) {
```
Comment (hawkfish) [inline src/function/window/window_value_function.cpp:303]: Can we move this check to the top of the loop? The `Rank` computation is potentially slow and we will throw it away.

**Review by hawkfish — CHANGES_REQUESTED** [review]
Also, can we have a test?

File: src/function/window/window_value_function.cpp (hunk 1 above)
Comment (ditdb) [reply src/function/window/window_value_function.cpp:298]: yes, it's an optimizing.

**Comment by ditdb** [comment]
> Also, can we have a test?

ok, I supplement it

File: test/sql/window/test_lead_lag.test [hunk 2]
```diff
@@ -105,3 +105,33 @@ ORDER BY 2, 1
 2024-01-01	7	1000	late	2024-03-01	dispatched
 2024-02-01	7	1000	dispatched	NULL	NULL
 2024-03-01	7	1000	dispatched	NULL	NULL
+
+# test lad and lead when offset is null
```
Comment (hawkfish) [inline test/sql/window/test_lead_lag.test:109]: "lag"!

**Review by hawkfish — CHANGES_REQUESTED** [review]
We also need a test for the secondary ordering. case (which is the one where I asked for the code to move.)  Have a look at test/sql/window/test_leadlag_orderby.test

File: test/sql/window/test_lead_lag.test (hunk 2 above)
Comment (ditdb) [reply test/sql/window/test_lead_lag.test:109]: I get it.

**Review by hawkfish — CHANGES_REQUESTED** [review]
Thanks - looks good!  Just fix those two comment typos (s/lad/lag/)
