### PR TITLE
Issue #14734: Wrap Parquet TIMETZ

### LINKED ISSUE #14734: DuckDB does not properly read TIMETZ types
### What happens?

The attached parquet file as a single TIMETZ column and DuckDB can not properly parse the timezone value. 
The parquet file viewed via https://dataconverter.io/view/parquet looks like this:
image

However, DuckDB returns the following:
```
D select * from 'timetz_column.parquet';
┌─────────────────────┐
│        col33        │
│ time with time zone │
├─────────────────────┤
│ at:33:32.627776+00  │
│ iv:26:11.627776+00  │
│ IL:29:15.627776+00  │
└─────────────────────┘
```
[timetz_column.parquet.zip](https://github.com/user-attachments/files/17651418/timetz_column.parquet.zip)

### To Reproduce

Download the attached parquet file. With DuckDB cli, run the following:
```
duckdb
D select * from 'timetz_column.parquet';
```

### OS:

MacOS M1 

### DuckDB Version:

1.1.3 (and older versions)

### DuckDB Client:

CLI

### Hardware:

_No response_

### Full Name:

Justin Tomlin

### Affiliation:

Alteryx

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by hawkfish**
Defensively wrap incoming out-of-range TIMETZ values from parquet. This seems to be what other tools do (e.g., Apache Drill).

fixes: duckdb/duckdb#14734
fixes: duckdblabs/duckdb-internal#3459

### CODE REVIEW

File: extension/parquet/parquet_timestamp.cpp [hunk 1]
```diff
@@ -105,6 +105,16 @@ date_t ParquetIntToDate(const int32_t &raw_date) {
 	return date_t(raw_date);
 }
 
+template <typename T>
+static T ParquetWrapTime(const T &raw, const T day) {
+	// Special case 24:00:00
+	if (raw == day) {
+		return raw;
+	}
+	const auto modulus = raw % day;
```
Comment (Mytherin) [inline extension/parquet/parquet_timestamp.cpp:114]: Instead of dong the modulo should we perhaps throw an error here? That is what pandas seems to do:

```py
pd.read_parquet('timetz_column.parquet')
# ValueError: hour must be in 0..23
```

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! LGTM - one comment/question:
