### PR TITLE
BUGFIX: do not perform unused columns optimization in presence of multiple grouping sets

### LINKED ISSUE #17175: DUPLICATE_GROUPS optimize causes incorrect result
### What happens?

DUPLICATE_GROUPS optimize causes incorrect result. Whether DUPLICATE_GROUPS optimization causes different query results.

### To Reproduce

Create table and insert data:
```
create table t1(col1 int, col2 int);
create table t2(col3 int);
insert into t1 values (1, 1);
insert into t2 values (1);
```

Execute sql:
```
select col1, col2, col3 from t1 join t2 on t1.col1 = t2.col3 group by rollup(col1, col2, col3) order by 1, 2 ,3;
```

If the DUPLICATE_GROUPS is enable, the result is:
```
┌───────┬───────┬───────┐
│ col1  │ col2  │ col3  │
│ int32 │ int32 │ int32 │
├───────┼───────┼───────┤
│     1 │     1 │     1 │
│     1 │     1 │     1 │
│     1 │  NULL │     1 │
│  NULL │  NULL │  NULL │
└───────┴───────┴───────┘
```

However, if the DUPLICATE_GROUPS is disable (I commented the code of apply DUPLICATE_GROUPS optimization), the result is:
```
┌───────┬───────┬───────┐
│ col1  │ col2  │ col3  │
│ int32 │ int32 │ int32 │
├───────┼───────┼───────┤
│     1 │     1 │     1 │
│     1 │     1 │  NULL │
│     1 │  NULL │  NULL │
│  NULL │  NULL │  NULL │
└───────┴───────┴───────┘
```

When DUPLICATE_GROUPS is disable, we can get the correct result.

### OS:

x86_64

### DuckDB Version:

1.2.2

### DuckDB Client:

1.2.2

### Hardware:

_No response_

### Full Name:

Jingqi Tian

### Affiliation:

Alibaba-inc

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [ ] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [ ] Yes, I have

### PR DESCRIPTION
**Pull request by Tmonster**
If we remove unused columns in the group by when there are multiple grouping sets (i.e more than 1), the duplicate groups optimizer will then optimize away possible groups created by functions like rollup and cube. 

Fixes https://github.com/duckdb/duckdb/issues/17175
Fixes https://github.com/duckdblabs/duckdb-internal/issues/4711

### CODE REVIEW

File: src/optimizer/remove_unused_columns.cpp [hunk 1]
```diff
@@ -56,9 +56,15 @@ void RemoveUnusedColumns::VisitOperator(LogicalOperator &op) {
 	switch (op.type) {
 	case LogicalOperatorType::LOGICAL_AGGREGATE_AND_GROUP_BY: {
 		// aggregate
+		auto &aggr = op.Cast<LogicalAggregate>();
+		// if there is more than one grouping set, the group by most likely has a rollup or cube
+		// If there is an equality join underneath the aggregate, this can change the groups to avoid unused columns
+		// This causes the duplicate eliminator to ignore functionality provided by grouping sets
+		if (aggr.grouping_sets.size() > 1) {
+			return;
```
Comment (lnkuiper) [inline src/optimizer/remove_unused_columns.cpp:64]: Is immediately returning not a bit too strict here? I think we could still recurse into children with `is_root` set to `true`.

**Review by lnkuiper — CHANGES_REQUESTED** [review]
Thanks for the PR! This makes a lot of sense, but I think the early-out is a bit too strict:

**Comment by Tmonster** [comment]
> Is immediately returning not a bit too strict here? I think we could still recurse into children with is_root set to true.

Ah yes of course. I thought that was already happening with the LogicalOperatorVisitor logic, but I see that it's not

**Review by lnkuiper — APPROVED** [review]
LGTM now, thanks! I think the failures are unrelated.

**Comment by Mytherin** [comment]
Thanks!
