### PR TITLE
[MetaTransaction] Add lock on modifying `all_transactions` and `transactions`

### LINKED ISSUE #10790: Importing large dataframes causes core dump
### What happens?

When writing large dataframes with a sequence for generating an autoincrement id, the following error occurs:

`libc++abi: terminating due to uncaught exception of type duckdb::InternalException: INTERNAL Error: Attempted to access index 1 within vector of size 1`

If you remove the sequence column, this issue goes away

### To Reproduce

```python
import duckdb
import pandas as pd
import numpy as np

num_rows = 2000000
num_columns = 10

con = duckdb.connect()
con.execute("CREATE SEQUENCE id_seq")
column_names = ',\n'.join([f'column_{i} FLOAT' for i in range(1, num_columns + 1)])
create_table_query = f"""
CREATE TABLE my_table (
    id INTEGER DEFAULT nextval('id_seq'),
    {column_names}
)
"""
con.execute(create_table_query)


for i in range(20):
    data = np.random.rand(num_rows, num_columns)
    columns = [f'Column_{i+1}' for i in range(num_columns)]
    df = pd.DataFrame(data, columns=columns)
    df_columns = ", ".join(df.columns)
    con.execute(f"INSERT INTO my_table ({df_columns}) SELECT * FROM df")
    print(f"inserted {i}")
    con.commit()
```

### OS:

macos sonoma 14.3

### DuckDB Version:

0.9.2, 0.10.1-dev240

### DuckDB Client:

Python

### Full Name:

Richmond Hollen

### Affiliation:

Ouster, Inc

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #10790

The issue was likely exposed by changes made in #10245 when ExecutePull was removed.
To explain the cause of the mentioned issue:

NextValFunction calls `MetaTransaction::Get` to look up or create the transaction, this is called from worker threads.
Because there was no lock on the meta transaction, this caused an issue where `all_transactions` contained the same db twice.

This only surfaced in Commit because there we loop through all the active transactions on the MetaTransaction, which was duplicated in this case, causing us to try to remove the transaction twice

### Coverage

I have added the test that previously caused the issue, sadly this is a python test.
I was not able to reproduce the issue with a sqllogictest, maybe it's worth creating a c++ test for it

### CODE REVIEW

**Comment by Tishj** [comment]
I really thought this would recreate the circumstances, triggering a parallel insert
```py
import duckdb

num_rows = 2000000
num_columns = 1

con = duckdb.connect()
con.execute("CREATE SEQUENCE id_seq")
create_table_query = f"""
CREATE TABLE my_table (
    id INTEGER DEFAULT nextval('id_seq'),
    a INTEGER
)
"""

con.execute(create_table_query)
con.execute("set preserve_insertion_order=false")
con.execute(f"""
    create table other as select * from range({num_rows}) tbl(i)
""")

for i in range(20):
    con.execute(f"INSERT INTO my_table (a) select i FROM other")
    con.table("my_table").show()
    print(f"inserted {i}")
```

File: src/transaction/meta_transaction.cpp [hunk 1]
```diff
@@ -24,13 +24,28 @@ Transaction &Transaction::Get(ClientContext &context, AttachedDatabase &db) {
...
+		if (RefersToSameObject(db, tx.get())) {
+			throw InternalException("Database is already present in all_transactions");
+		}
+	}
+}
+#endif
+
 Transaction &MetaTransaction::GetTransaction(AttachedDatabase &db) {
+	lock_guard<mutex> guard(lock);
 	auto entry = transactions.find(db);
```
Comment (Mytherin) [inline src/transaction/meta_transaction.cpp:39]: This lock is most likely only necessary in `MetaTransaction::GetTransaction` - Commit, Rollback and RemoveTransaction are all called in single-threaded mode under the transaction lock of the main transaction manager

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! That makes sense - although it is a bit odd that we are not starting a transaction during the (single-threaded) bind phase I think protecting this with a lock is a good idea in general. One comment:

File: src/transaction/meta_transaction.cpp (hunk 1 above)
Comment (Tishj) [reply src/transaction/meta_transaction.cpp:39]: Regarding the reproduction, do you have a suggestion what I could try still?
I thought the only requirement would be to get the source to scan in parallel, so we get multiple worker threads getting MetaTransaction::Get at the same time

Comment (Mytherin) [reply src/transaction/meta_transaction.cpp:39]: Is the reproduction from the issue not good enough?

Comment (Mytherin) [reply src/transaction/meta_transaction.cpp:39]: I'm still confused by how this goes wrong in the first place - in this instance the transaction should be started as part of `bind_insert.cpp` when it binds the base table, and binding always happens single-threaded. I'm not sure if the parallel ingestion is the issue. Looking at the query I would suspect the sequence default value to be the culprit here.

Comment (Tishj) [reply src/transaction/meta_transaction.cpp:39]: That's why I'm trying to create a better reproduction
all my hunches as to why this dies have been wrong so far

It seems to happen both with BatchedInsert and regular Insert

Comment (Tishj) [reply src/transaction/meta_transaction.cpp:39]: > Looking at the query I would suspect the sequence default value to be the culprit here.

Yea that is the problem, because that calls NextValFunction - which calls MetaTransaction::Get
But I still can't reproduce this outside of the pandas scan

Comment (Mytherin) [reply src/transaction/meta_transaction.cpp:39]: This one seems to work for me:
```sql
CREATE SEQUENCE id_seq;
CREATE TABLE my_table (
    id INTEGER DEFAULT nextval('id_seq'),
    a INTEGER
);
ATTACH ':memory:' AS s1;
CREATE TABLE s1.tbl AS FROM range(2000000);                            ^
INSERT INTO my_table (a) SELECT * FROM s1.tbl;
INSERT INTO my_table (a) SELECT * FROM s1.tbl;
INSERT INTO my_table (a) SELECT * FROM s1.tbl;
INSERT INTO my_table (a) SELECT * FROM s1.tbl;
INSERT INTO my_table (a) SELECT * FROM s1.tbl;
INSERT INTO my_table (a) SELECT * FROM s1.tbl;
INSERT INTO my_table (a) SELECT * FROM s1.tbl;

```

Comment (Mytherin) [reply src/transaction/meta_transaction.cpp:39]: Transactions are launched within a database, the second database ensures we don't open a transaction as part of the scan.

**Comment by Mytherin** [comment]
Could you still add the new test and remove the unneeded locks?

**Comment by Tishj** [comment]
> Could you still add the new test and remove the unneeded locks?

Will do, I couldn't seem to reproduce the error with the test you provided on `main` though:
```sql
statement ok
CREATE SEQUENCE id_seq;

statement ok
CREATE TABLE my_table (
	id INTEGER DEFAULT nextval('id_seq'),
	a INTEGER
);

statement ok
ATTACH ':memory:' AS s1;

# Create a bunch of data in a second database,
# as to not trigger opening a transaction on the original db
statement ok
CREATE TABLE s1.tbl AS FROM range(2000000);

loop i 1 100

statement ok
INSERT INTO my_table (a) SELECT * FROM s1.tbl;

endloop
```

**Comment by Mytherin** [comment]
Hm, that's weird - copy pasting this into the CLI instantly triggers the issue for me:

```sql
CREATE SEQUENCE id_seq;
CREATE TABLE my_table (
    id INTEGER DEFAULT nextval('id_seq'),
    a INTEGER
);
ATTACH ':memory:' AS s1;
CREATE TABLE s1.tbl AS FROM range(2000000);
INSERT INTO my_table (a) SELECT * FROM s1.tbl;
INSERT INTO my_table (a) SELECT * FROM s1.tbl;
INSERT INTO my_table (a) SELECT * FROM s1.tbl;
INSERT INTO my_table (a) SELECT * FROM s1.tbl;
INSERT INTO my_table (a) SELECT * FROM s1.tbl;
INSERT INTO my_table (a) SELECT * FROM s1.tbl;
INSERT INTO my_table (a) SELECT * FROM s1.tbl;
```

**Comment by Mytherin** [comment]
Might be related to thread count? Try adding `SET threads=10`

**Comment by Tishj** [comment]
> Might be related to thread count? Try adding `SET threads=10`

```sql
statement ok
pragma threads=10

statement ok
CREATE SEQUENCE id_seq;
CREATE TABLE my_table (
	id INTEGER DEFAULT nextval('id_seq'),
	a INTEGER
);
ATTACH ':memory:' AS s1;
CREATE TABLE s1.tbl AS FROM range(2000000);
INSERT INTO my_table (a) SELECT * FROM s1.tbl;
INSERT INTO my_table (a) SELECT * FROM s1.tbl;
INSERT INTO my_table (a) SELECT * FROM s1.tbl;
INSERT INTO my_table (a) SELECT * FROM s1.tbl;
INSERT INTO my_table (a) SELECT * FROM s1.tbl;
INSERT INTO my_table (a) SELECT * FROM s1.tbl;
INSERT INTO my_table (a) SELECT * FROM s1.tbl;
INSERT INTO my_table (a) SELECT * FROM s1.tbl;
INSERT INTO my_table (a) SELECT * FROM s1.tbl;
INSERT INTO my_table (a) SELECT * FROM s1.tbl;
```

Still no dice, I can also get it to crash instantly with the CLI
I tried making a c++ test, see if that could trigger it

```c++
TEST_CASE("Test MetaTransaction concurrency", "[api][.]") {
	duckdb::unique_ptr<DuckDB> db;
	duckdb::unique_ptr<Connection> con;

	REQUIRE_NOTHROW(db = make_uniq<DuckDB>());
	REQUIRE_NOTHROW(con = make_uniq<Connection>(*db));

	con->Query("CREATE SEQUENCE seq");
	con->Query(R"(
		CREATE TABLE my_table (
			id INTEGER DEFAULT nextval('seq'),
			a INTEGER
		)
	)");
	// Create some data outside of the main db
	con->Query("ATTACH ':memory:' AS s1;");
	con->Query("CREATE TABLE s1.tbl AS FROM range(2000000);");

	auto res = con->Query(R"(
		INSERT INTO my_table (a) SELECT * FROM s1.tbl;
		INSERT INTO my_table (a) SELECT * FROM s1.tbl;
		INSERT INTO my_table (a) SELECT * FROM s1.tbl;
		INSERT INTO my_table (a) SELECT * FROM s1.tbl;
		INSERT INTO my_table (a) SELECT * FROM s1.tbl;
		INSERT INTO my_table (a) SELECT * FROM s1.tbl;
		INSERT INTO my_table (a) SELECT * FROM s1.tbl;
		INSERT INTO my_table (a) SELECT * FROM s1.tbl;
		INSERT INTO my_table (a) SELECT * FROM s1.tbl;
		INSERT INTO my_table (a) SELECT * FROM s1.tbl;
		INSERT INTO my_table (a) SELECT * FROM s1.tbl;
		INSERT INTO my_table (a) SELECT * FROM s1.tbl;
	)");
	REQUIRE(!res->HasError());

	// clean up
	con.reset();
	db.reset();
}
```

Still nothing
I'm considering making a shell test, since we moved those over to pytest
But that almost defeats the point of adding another test, the one in the Python client is consistently failing on main already

**Comment by Mytherin** [comment]
What happens if you split up the `Query()` into multiple queries? I'm not sure how that interfaces with transactions (which is what this is all about).

**Comment by Tishj** [comment]
I'll check, in the mean time this did the trick:
```py
def test_temp_directory(shell):
    test = (
        ShellTest(shell)
		.statement("CREATE SEQUENCE id_seq;")
		.statement("""
            CREATE TABLE my_table (
			id INTEGER DEFAULT nextval('id_seq'),
			a INTEGER
		);""")
		.statement("ATTACH ':memory:' AS s1;")
		.statement("CREATE TABLE s1.tbl AS FROM range(2000000);")
		.statement("INSERT INTO my_table (a) SELECT * FROM s1.tbl;")
		.statement("INSERT INTO my_table (a) SELECT * FROM s1.tbl;")
		.statement("INSERT INTO my_table (a) SELECT * FROM s1.tbl;")
		.statement("INSERT INTO my_table (a) SELECT * FROM s1.tbl;")
		.statement("INSERT INTO my_table (a) SELECT * FROM s1.tbl;")
		.statement("INSERT INTO my_table (a) SELECT * FROM s1.tbl;")
		.statement("INSERT INTO my_table (a) SELECT * FROM s1.tbl;")
		.statement("INSERT INTO my_table (a) SELECT * FROM s1.tbl;")
		.statement("INSERT INTO my_table (a) SELECT * FROM s1.tbl;")
		.statement("INSERT INTO my_table (a) SELECT * FROM s1.tbl;")
    )
    result = test.run()
    result.check_stderr("terminating due to uncaught exception of type duckdb::InternalException")
```

**Comment by Tishj** [comment]
Also with this, no error:
```c++
	for (idx_t i = 0; i < 20; i++) {
		auto res = con->Query(R"(
			INSERT INTO my_table (a) SELECT * FROM s1.tbl;
		)");
		REQUIRE(!res->HasError());
	}
```

**Comment by Tishj** [comment]
Probably has to do with the error only showing up when we're committing a transaction
I assume the CLI handles this differently than the C++ API?
