### PR TITLE
fixes #6238

### LINKED ISSUE #6238: DuckDBJ: DuckDBDatabaseMetaData.supportsCatalogsIn%() methods should return true
### What happens?

Interface DatabaseMetaData provides these methods:

- supportsCatalogsInDataManipulation: "Retrieves whether a catalog name can be used in a data manipulation statement", see: https://docs.oracle.com/en/java/javase/11/docs/api/java.sql/java/sql/DatabaseMetaData.html#supportsCatalogsInDataManipulation()
- supportsCatalogsInIndexDefinitions: "Retrieves whether a catalog name can be used in an index definition statement."  https://docs.oracle.com/en/java/javase/11/docs/api/java.sql/java/sql/DatabaseMetaData.html#supportsCatalogsInIndexDefinitions()
- supportsCatalogsInTableDefinitions: "Retrieves whether a catalog name can be used in a table definition statement." https://docs.oracle.com/en/java/javase/11/docs/api/java.sql/java/sql/DatabaseMetaData.html#supportsCatalogsInTableDefinitions()

The respective implementations in DuckDBDatabaseMetaData always return false. 

I believe they should return true, as duckdb lets you use catalog qualified names to manipulate objects in attached databases. 

### To Reproduce

Test for https://docs.oracle.com/en/java/javase/11/docs/api/java.sql/java/sql/DatabaseMetaData.html#supportsCatalogsInTableDefinitions():

```
	public static void test_supports_catalogs_in_table_definitions() throws Exception {
		final Connection connection = DriverManager.getConnection("jdbc:duckdb:");
		final Statement statement = connection.createStatement();
		final DatabaseMetaData databaseMetaData = connection.getMetaData();
		final String CATALOG_NAME = "tmp";
		final String TABLE_NAME = "t1";
		final String qualifiedTableName = CATALOG_NAME + "." + TABLE_NAME;
		ResultSet resultSet = null;
		try {
			final File file = Files.createTempFile("duckdb-jdbc-test-", ".duckdb").toFile();
			file.delete();
			statement.execute("ATTACH '" + file.getAbsolutePath() + "' AS \"" + CATALOG_NAME + "\"");
			file.deleteOnExit();
			
			final boolean supportsCatalogsInTableDefinitions = databaseMetaData.supportsCatalogsInTableDefinitions();
			try {
				statement.execute("CREATE TABLE " + qualifiedTableName + "(id int)");
			}
			catch (SQLException ex) {
				if (supportsCatalogsInTableDefinitions) {
					fail("supportsCatalogsInTableDefinitions is true but CREATE TABLE in attached database is not allowed.");
				}
			}
			resultSet = statement.executeQuery(
				"SELECT * FROM information_schema.tables "+
				"WHERE table_catalog = '" + CATALOG_NAME + "' " +
				"AND table_name = '" + TABLE_NAME + "' "
			);
			assertTrue(resultSet.next(), "Expected exactly 1 row from information_schema.tables, got 0");
			assertFalse(resultSet.next());
			resultSet.close();

			try {
				statement.execute("DROP TABLE " + qualifiedTableName);
			}
			catch (SQLException ex) {
				if (supportsCatalogsInTableDefinitions) {
					fail("supportsCatalogsInTableDefinitions is true but DROP TABLE in attached database is not allowed.");
				}
			}
			resultSet = statement.executeQuery(
				"SELECT * FROM information_schema.tables "+
				"WHERE table_catalog = '" + CATALOG_NAME + "' " +
				"AND table_name = '" + TABLE_NAME + "' "
			);
			assertTrue(resultSet.next() == false, "Expected exactly 0 rows from information_schema.tables, got > 0");
			resultSet.close();

			assertTrue(supportsCatalogsInTableDefinitions, "supportsCatalogsInTableDefinitions should return true.");
		} 
		finally {
			if (resultSet != null) {
				resultSet.close();
			}
			statement.close();
			connection.close();
		}
	}
```

Test for https://docs.oracle.com/en/java/javase/11/docs/api/java.sql/java/sql/DatabaseMetaData.html#supportsCatalogsInDataManipulation()

```
	public static void test_supports_catalogs_in_data_manipulation() throws Exception {
		final File file = Files.createTempFile("duckdb-jdbc-test-", ".duckdb").toFile();
		final String filePath = file.getAbsolutePath();
		final String CATALOG_NAME = "tmp";
		final String TABLE_NAME = "t1";
		final String qualifiedTableName = CATALOG_NAME + "." + TABLE_NAME;
		file.delete();
		Connection connection = null;
		Statement statement = null;
		
		connection = DriverManager.getConnection("jdbc:duckdb:" + filePath);
		file.deleteOnExit();
		statement = connection.createStatement();
		statement.execute("CREATE TABLE " + TABLE_NAME + "(id int)");
		statement.close();
		connection.close();
		
		Thread.currentThread().sleep(1000);
		
		connection = DriverManager.getConnection("jdbc:duckdb:");
		final DatabaseMetaData databaseMetaData = connection.getMetaData();
		statement = connection.createStatement();
		ResultSet resultSet = null;
		try {
			statement.execute("ATTACH '" + filePath + "' AS \"" + CATALOG_NAME + "\"");
			
			final boolean supportsCatalogsInDataManipulation = databaseMetaData.supportsCatalogsInDataManipulation();
			try {
				statement.execute("INSERT INTO " + qualifiedTableName + " VALUES(1)");
				resultSet = statement.executeQuery("SELECT * FROM "+ qualifiedTableName);
				assertTrue(resultSet.next(), "Expected exactly 1 row from " + qualifiedTableName + ", got 0");
				assertTrue(resultSet.getInt("ID") == 1, "Value for ID should be 1");
				resultSet.close();
			}
			catch (SQLException ex) {
				if (supportsCatalogsInDataManipulation) {
					fail("supportsCatalogsInDataManipulation is true but INSERT in " + qualifiedTableName + " is not allowed.");
				}
			}
			
			try {
				statement.execute("UPDATE " + qualifiedTableName + " SET ID = 2 WHERE ID = 1");
				resultSet = statement.executeQuery("SELECT * FROM "+ qualifiedTableName);
				assertTrue(resultSet.next(), "Expected exactly 1 row from " + qualifiedTableName + ", got 0");
				assertTrue(resultSet.getInt("ID") == 2, "Value for ID should be 2");
				resultSet.close();
			}
			catch (SQLException ex) {
				if (supportsCatalogsInDataManipulation) {
					fail("supportsCatalogsInDataManipulation is true but UPDATE of " + qualifiedTableName + " is not allowed.");
				}
			}
			
			try {
				statement.execute("DELETE FROM " + qualifiedTableName + " WHERE ID = 2");
				resultSet = statement.executeQuery("SELECT * FROM "+ qualifiedTableName);
				assertTrue(resultSet.next() == false, "Expected 0 rows from " + qualifiedTableName + ", got > 0");
				resultSet.close();
			}
			catch (SQLException ex) {
				if (supportsCatalogsInDataManipulation) {
					fail("supportsCatalogsInDataManipulation is true but UPDATE of " + qualifiedTableName + " is not allowed.");
				}
			}
			
			assertTrue(supportsCatalogsInDataManipulation, "supportsCatalogsInDataManipulation should return true.");
		} 
		finally {
			if (resultSet != null) {
				resultSet.close();
			}
			statement.close();
			connection.close();
		}
	}
```

Test for https://docs.oracle.com/en/java/javase/11/docs/api/java.sql/java/sql/DatabaseMetaData.html#supportsCatalogsInIndexDefinitions()

```
	public static void test_supports_catalogs_in_index_definitions() throws Exception {
		final File file = Files.createTempFile("duckdb-jdbc-test-", ".duckdb").toFile();
		final String filePath = file.getAbsolutePath();
		final String CATALOG_NAME = "tmp";
		final String TABLE_NAME = "t1";
		final String INDEX_NAME = "idx1";
		final String qualifiedTableName = CATALOG_NAME + "." + TABLE_NAME;
		final String qualifiedIndexName = CATALOG_NAME + "." + INDEX_NAME;
		file.delete();
		Connection connection = null;
		Statement statement = null;
		
		connection = DriverManager.getConnection("jdbc:duckdb:" + filePath);
		file.deleteOnExit();
		statement = connection.createStatement();
		statement.execute("CREATE TABLE " + TABLE_NAME + "(id int)");
		statement.close();
		connection.close();
		
		Thread.currentThread().sleep(1000);
		
		connection = DriverManager.getConnection("jdbc:duckdb:");
		final DatabaseMetaData databaseMetaData = connection.getMetaData();
		statement = connection.createStatement();
		ResultSet resultSet = null;
		try {
			statement.execute("ATTACH '" + filePath + "' AS \"" + CATALOG_NAME + "\"");
			
			final boolean supportsCatalogsInIndexDefinitions = databaseMetaData.supportsCatalogsInIndexDefinitions();
			try {
				statement.execute("CREATE INDEX " + INDEX_NAME + " ON " + qualifiedTableName + "(ID)");
				resultSet = statement.executeQuery(
					"SELECT * FROM duckdb_indexes() " +
					"WHERE database_name = '" + CATALOG_NAME + "' " +
					"AND table_name = '" + TABLE_NAME + "' " +
					"WHERE index_name = '" + INDEX_NAME + "' "
				);
				assertTrue(resultSet.next(), "Expected exactly 1 row from duckdb_indexes(), got 0");
				resultSet.close();
			}
			catch (SQLException ex) {
				if (supportsCatalogsInIndexDefinitions) {
					fail(
						"supportsCatalogsInIndexDefinitions is true but " +
						"CREATE INDEX on " + qualifiedTableName + " is not allowed."
					);
				}
			}
			
			try {
				statement.execute("DROP index " + qualifiedIndexName);
				resultSet = statement.executeQuery(
					"SELECT * FROM duckdb_indexes() " +
					"WHERE database_name = '" + CATALOG_NAME + "' " +
					"AND table_name = '" + TABLE_NAME + "' " +
					"WHERE index_name = '" + INDEX_NAME + "' "
				);
				assertFalse(resultSet.next());
				resultSet.close();
			}
			catch (SQLException ex) {
				if (supportsCatalogsInIndexDefinitions) {
					fail("supportsCatalogsInIndexDefinitions is true but DROP of " + qualifiedIndexName + " is not allowed.");
				}
			}
			
			assertTrue(supportsCatalogsInIndexDefinitions, "supportsCatalogsInIndexDefinitions should return true.");
		} 
		finally {
			if (resultSet != null) {
				resultSet.close();
			}
			statement.close();
			connection.close();
		}
	}
```

### OS:

Windows 10 Pro

### DuckDB Version:

v0.6.2-dev2495 8dfa7815d0

### DuckDB Client:

DuckDBJ (jdbc)

### Full Name:

Roland Bouman

### Affiliation:

Just-Bi.nl (an EPAM company) 

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by rpbouman**
Adds tests for supportsCatalogsInDataManipulation, supportsCatalogsInTableDefinitions, supportsCatalogsInIndexDefinitions. Modify supportsCatalogsIn% methods in DuckDBDatabaseMetaData to return true.

### CODE REVIEW

File: tools/jdbc/src/test/java/org/duckdb/test/TestDuckDBJDBC.java [hunk 1]
```diff
@@ -2605,6 +2606,248 @@ public static void test_supportsLikeEscapeClause_shouldBe_true() throws Exceptio
...
+		Statement statement = null;
+		
+		connection = DriverManager.getConnection("jdbc:duckdb:" + filePath);
+		file.deleteOnExit();
+		statement = connection.createStatement();
+		statement.execute("CREATE TABLE " + TABLE_NAME + "(" + COLUMN_NAME + " int)");
+		statement.close();
+		connection.close();
+		
+		Thread.currentThread().sleep(1000);
```
Comment (Mytherin) [inline tools/jdbc/src/test/java/org/duckdb/test/TestDuckDBJDBC.java:2694]: Is it necessary for this test to attach an on-disk database (and hence create challenges around locks and such)? Perhaps we could just attach an in-memory database in the test?

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! The changes to the driver seem fine to me - but the tests seem a bit too involved/complex. Could we perhaps simplify the tests and use an in-memory database in `ATTACH`? That should test the same properties but avoid the need for sleeps and sidestep file creation/locking issues.

File: tools/jdbc/src/test/java/org/duckdb/test/TestDuckDBJDBC.java (hunk 1 above)
Comment (rpbouman) [reply tools/jdbc/src/test/java/org/duckdb/test/TestDuckDBJDBC.java]: > Thanks for the PR! The changes to the driver seem fine to me - but the tests seem a bit too involved/complex. Could we perhaps simplify the tests and use an in-memory database in `ATTACH`? That should test the same properties but avoid the need for sleeps and sidestep file creation/locking issues.

Yeah good call. Tests modified. 
https://github.com/duckdb/duckdb/pull/6239/commits/a0327f2a8f089073702a03f0d111edf793cb69f1

File: tools/jdbc/src/test/java/org/duckdb/test/TestDuckDBJDBC.java [hunk 2]
```diff
@@ -2605,6 +2606,219 @@ public static void test_supportsLikeEscapeClause_shouldBe_true() throws Exceptio
...
+			assertTrue(resultSet.next() == false, "Expected exactly 0 rows from information_schema.tables, got > 0");
+			resultSet.close();
+
+			assertTrue(supportsCatalogsInTableDefinitions, "supportsCatalogsInTableDefinitions should return true.");
+		} 
+		finally {
+			if (resultSet != null) {
+				resultSet.close();
+			}
+			statement.close();
```
Comment (Mause) [inline tools/jdbc/src/test/java/org/duckdb/test/TestDuckDBJDBC.java:2668]: Can you please use try with resources instead of all these explicit close calls?

File: tools/jdbc/src/test/java/org/duckdb/test/TestDuckDBJDBC.java [hunk 3]
```diff
@@ -2605,6 +2606,219 @@ public static void test_supportsLikeEscapeClause_shouldBe_true() throws Exceptio
...
+						"supportsCatalogsInDataManipulation is true but INSERT in " + qualifiedTableName + " is not allowed." + 
+						ex.getMessage()
+				  );
+					ex.printStackTrace();
+				}
+			}
+			
+			try {
+				statement.execute(
+					"UPDATE " + qualifiedTableName + " SET " + COLUMN_NAME + " = 2 " +
```
Comment (Mause) [inline tools/jdbc/src/test/java/org/duckdb/test/TestDuckDBJDBC.java:2707]: String.format would be a bit cleaner here I think

**Review by Mause — CHANGES_REQUESTED** [review]

File: tools/jdbc/src/test/java/org/duckdb/test/TestDuckDBJDBC.java (hunk 3 above)
Comment (rpbouman) [reply tools/jdbc/src/test/java/org/duckdb/test/TestDuckDBJDBC.java]: Hi @Mause , thanks for taking a look! Prior tests are also using this kind of style, I figured that was just good enough for tests, but I agree, it's nicer with try with resources and string formatter.

Let me know if something else needs changing.

**Comment by Mytherin** [comment]
Thanks!
