### PR TITLE
Fix tpcds extension to generate data matching tpcds tools 

### LINKED ISSUE #8584: TPCDS extension generates string columns that do not match the standard
### What happens?

Use the TPCDS extension to generate data. It doesn't match the data provided by the current version of the TPCDS standard.

The extension is based on version 2.10 of the standard's generation code, while the current version is 3.2. Unfortunately I do not have an old version of the TPCDS generation code to compare to.

But it could also have to do with the porting of the extension to C++.

### To Reproduce

Run the following SQL:
.open sf1
call dsdgen(sf=1);
-- TPCDS query 37
select  i_item_id
       ,i_item_desc
       ,i_current_price
 from item, inventory, date_dim, catalog_sales
 where i_current_price between 68 and 68 + 30
 and inv_item_sk = i_item_sk
 and d_date_sk=inv_date_sk
 and d_date between cast('2000-02-01' as date) and (cast('2000-02-01' as date) +  interval '60' day)
 and i_manufact_id in (677,940,694,808)
 and inv_quantity_on_hand between 100 and 500
 and cs_item_sk = i_item_sk
 group by i_item_id,i_item_desc,i_current_price
 order by i_item_id
 limit 100;

DuckDB returns:
AAAAAAAAHFMBAAAA
Workers used to send inside long star methods. Profound, natural ministers wo.
86.11

According to the answer file provided by TPCDS, the correct answer is:
AAAAAAAAHFMBAAAA
Jobs crack at all public countries. Possible, traditional initiatives will make british problems. Fiscal years call extremely just growing pupils. Soon dutch voices
86.11

The second columns are different.

### OS:

Windows amd64

### DuckDB Version:

0.8.2 main

### DuckDB Client:

CLI

### Full Name:

Dan Cory

### Affiliation:

self

### Have you tried this on the latest `master` branch?

I have tested with a master build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by DanCory**
Fix dsdgen to match the tpcds v4 release
Fixes #8584

### CODE REVIEW

**Comment by DanCory** [comment]
I'm seeing the benchmark tests somehow use query tpcds data. I don't know where that is to fix it.

**Comment by lnkuiper** [comment]
Our benchmark runner performs result validation for the TPC-DS queries. Changing the data generation means that the pre-computed results must also be updated. These can be found in `extension/tpcds/dsdgen/answers`

**Comment by DanCory** [comment]
Thanks @lnkuiper, I included updates for all of those in this PR https://github.com/duckdb/duckdb/pull/21746/changes/abeed66bfffa865aa9adf2e12d91ec7429a87646

**Comment by lnkuiper** [comment]
It doesn't seem like that commit was added to this PR

**Comment by DanCory** [comment]
It was already in this PR. Sorry for the confusion.

**Comment by lnkuiper** [comment]
I see. The TPC-DS regression test is still failing, however. We have precomputed answers for sf0.01, sf1, and sf100, and all of them must be recomputed, otherwise our result verification breaks with this PR.

**Comment by DanCory** [comment]
I regenerated all of those (using duckdb, not postgres), in the previously mentioned PR. As far as I can read the logs, the test is somehow still getting the old data in duckdb (either the database is cached or the extension?), and it is comparing them to the updated answers.

**Comment by Mytherin** [comment]
The regression test compares to a previous DuckDB version which generates the data in the old way - so I think that those failures make sense / are expected. We can merge in spite of those failures. The Linux Release test, however, still seems to contain failures that need to be fixed.

**Comment by DanCory** [comment]
Thanks so much for the feedback. I will have a look at the Linux test, but it will not be until next week.

I also just found three more TPCDS queries that aren't fully ordered by their order by clauses, so I may fix those as well.

**Comment by DanCory** [comment]
There's still one test in the Linux Release group that is failing, but it appears to be using an old version of the extension. I'm not quite sure how that happens.

**Comment by Mytherin** [comment]
The regression workflow compares against an older version of DuckDB, so I don't think that's going to be fixable. It's not an issue - I'll run CI here. Thanks for the updates.

**Comment by Mytherin** [comment]
There still seems to be failures in the slow tests (`make allunit`) - see the Linux Release Tests - could you have a look?

File: extension/tpcds/dsdgen/queries/18.sql [hunk 1]
```diff
@@ -45,5 +45,8 @@ GROUP BY ROLLUP (i_item_id,
 ORDER BY ca_country NULLS FIRST,
     ca_state NULLS FIRST,
     ca_county NULLS FIRST,
-    i_item_id NULLS FIRST
+    i_item_id NULLS FIRST,
+    grouping (ca_country) NULLS FIRST,
```
Comment (Mytherin) [inline extension/tpcds/dsdgen/queries/18.sql:49]: Could you expand on why all of these queries are changing? I haven't seen these queries elsewhere on the internet in this form.

Comment (DanCory) [reply extension/tpcds/dsdgen/queries/18.sql:49]: These queries aren't stable, in that different runs of the query could return results in different order. In the case of query 18, ca_country can be NULL in the raw data and it will also be NULL in the grouping row. The additional ORDER BY column ensures the output order is deterministic.

Comment (Mytherin) [reply extension/tpcds/dsdgen/queries/18.sql:49]: Many of the query changes are more than just ordering changes, though, e.g. turning a join into a subquery, removing `lower`, changing filters, etc. Did you get these queries from somewhere else?

Comment (DanCory) [reply extension/tpcds/dsdgen/queries/18.sql:49]: I checked the queries against the TPCDS version 4 standard which I downloaded from tpc.org and I included commit comments explaining them. The removal of lower was a change in TPCDS version 4, so many sources don't have it. The join vs. subquery was originally a subquery in TPCDS, but changed to a join for duckdb. I think this was to make sure early duckdb could process it, as several queries don't exactly match the TPCDS standard. This particular change affected the semantics of the query, so I changed it to match the standard. All queries have been checked that they return the same results as those downloaded from the TPCDS website at SF1, 10, 30, and 100, with some alterations for stable orderings.

**Comment by DanCory** [comment]
Checked in a few more updated test results. I _think_ the remaining failures all come from the change to query 99 to drop the lower function.

Thanks again for all your help reviewing this!

File: extension/tpcds/dsdgen/queries/18.sql (hunk 1 above)
Comment (Mytherin) [reply extension/tpcds/dsdgen/queries/18.sql:49]: Alright, sounds good, thanks for the clarification.

**Comment by Mytherin** [comment]
Thanks for all of the work - we do need all tests to pass before we can merge this, however. If you could fix up the last tests so that CI passes in full (minus the regression run using the old version) we can get this in.

**Comment by DanCory** [comment]
Sorry - just not sure what you want me to do with the last test failure I see. As far as I can tell, it is running the old query 99 (with lower) and comparing to the new answer file (without lower). Did you want me to include the old answer file?

Or is there another failure I am missing when reading the logs (certainly a possibility!)?

**Comment by Mytherin** [comment]
See [the CI run on your fork](https://github.com/DanCory/duckdb/actions/runs/24788578077/job/72544562644)

**Comment by Mytherin** [comment]
Ah I think what's missing is inlining of the queries for the `PRAGMA` functions. It's running the old query because, while the SQL file has been replaced, the extension still contains the old queries baked into it. You can run `python scripts/generate_csv_header.py` to inline the queries in the header.

**Comment by DanCory** [comment]
Thanks! I did not know about that. I will get that fixed.

**Comment by DanCory** [comment]
Linux release test is now passing!

**Comment by Mytherin** [comment]
Thanks!

**Comment by DanCory** [comment]
Thanks again for all your help @Mytherin and @lnkuiper

**Comment by lnkuiper** [comment]
Thanks for the contribution! Much appreciated
