### PR TITLE
Fix MacOS exception catching

### LINKED ISSUE #6521: Exceptions from MacOS extensions not caught properly
### What happens?

Thanks to @ywelsch for reporting this in detail. What's happening is as follows: when an extension that is built with EXTENSION_STATIC_BUILD=1 is loaded by duckdb, there's now basically two DuckDB's in the application. The reason for this is to avoid the need for RTLD_GLOBAL which is problematic in various clients.

Problems arise however when the extension c ode throws a duckdb::Exception (or one of its derived classes). To be able to catch these from the main DuckDB code the typeinfo of the exceptions is checked. On linux this is all fine, as explained here: [click](https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/libsupc%2B%2B/typeinfo#L52). tldr: strcmp will be used to catch exceptions by their symbol name.

However on MacOS no strcmp happens, but only pointer comparison is executed causing duckdb to not be able to catch the specific exception and will end up catching them as std::exceptions instead, losing the ability to do specific handling.

### To Reproduce

build json extension + duckdb binary without extensions:
```
EXTENSION_STATIC_BUILD=1 DISABLE_BUILTIN_EXTENSIONS=1 BUILD_JSON=1 make
```
then with a `test.json` that contains invalid json, run:
```
D LOAD 'build/release/extension/json/json.duckdb_extension';
D SELECT * FROM read_json_objects('test.json');
Error: Invalid Error: Invalid Input Error: Malformed JSON in file "test.json", at byte 1 in object 3: unexpected character.
```
Note the Invalid Error indicates that DuckDB was not able to catch the exception properly.

### OS:

MacOS

### DuckDB Version:

v0.7.1

### DuckDB Client:

CLI

### Full Name:

Sam Ansmink

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by carlopi**
To test this, add this as extension_config_local.cmake:
```
################# SPATIAL
duckdb_extension_load(spatial
        DONT_LINK LOAD_TESTS
        GIT_URL https://github.com/duckdblabs/duckdb_spatial.git
        GIT_TAG 36e5a126976ac3b66716893360ef7e6295707082
        INCLUDE_DIR spatial/include
        TEST_DIR test/sql
        )
```
on the `main` duckdb branch, then
```
GEN=ninja EXTENSION_STATIC_BUILD=1 make
./build/release/duckdb -unsigned -c "LOAD 'build/release/extension/spatial/spatial.duckdb_extension';CREATE TABLE zones AS SELECT zone, LocationId, borough, ST_GeomFromWKB(wkb_geometry) AS geom FROM ST_Read('taxi_zones.shx');"
```
Should error like: `Error: Invalid Error: IO Error: GDAL Error (4): taxi_zones.shx: No such file or directory`

while doing the same from this branch should give: `Error: IO Error: GDAL Error (4): taxi_zones.shx: No such file or directory`.

Fixes #6521

### CODE REVIEW

**Comment by carlopi** [comment]
Note that this do not guarantees same behaviour in all cases between duckdb::Exception and std::exceptions with the right message, but should solve a big share of them while adding infrastructure to solve the remaining ones.

Final part could be either done incrementally in the more relevant places or via adding appropriate testing where we toggle between throwing unwrapped std::exceptions or duckdb::Exception, and expect results to be the same.

File: src/include/duckdb/common/preserved_error.hpp [hunk 1]
```diff
@@ -21,6 +21,17 @@ class PreservedError {
 	PreservedError(const std::exception &ex)
 	    : initialized(true), type(ExceptionType::INVALID), raw_message(SanitizeErrorMessage(ex.what())),
 	      exception_instance(nullptr) {
+		// Given a message in the form: 	xxxxx Error: yyyyy
+		// Try to match xxxxxxx with known error so to potentially reconstruct the original error type
+		string err = raw_message.substr(0, raw_message.find(':'));
```
Comment (Tishj) [inline src/include/duckdb/common/preserved_error.hpp:26]: I think one problem with this is the assumption that this is always an error produced by duckdb, I think we can also catch regular c++ exceptions with this, so maybe we should first do a pass to check that this is one our exceptions

Comment (carlopi) [reply src/include/duckdb/common/preserved_error.hpp:26]: I think this is the role of line 28, where we are checking a few conditions that should be equivalent to "there is a substring ` Error:`, and the first semicolon is part of that substring.

Regular std::exceptions might also be wrongly catched iff they follow the pattern and also `err` matches one of the known errors, but that should be acceptable (here we are duck-typing exceptions 🦆, pun intended)

Comment (carlopi) [reply src/include/duckdb/common/preserved_error.hpp:26]: If you want to review line 26-28, it would be welcome, it's likely the weaker point of the PR.

Comment (Mytherin) [reply src/include/duckdb/common/preserved_error.hpp:26]: Agreed with Thijs that this looks like it can go wrong. Can we check if `raw_message.find(':')` returns `std::string::npos ` and bail-out if it does? Plus a check if there is a message afterwards (so an error like this `error:` does not trigger undefined behavior)?

Comment (carlopi) [reply src/include/duckdb/common/preserved_error.hpp:26]: Ouch, I just tested it plus read the spec, and you are both very right @Tishj and @Mytherin.

**Review by Tishj — APPROVED** [review]
Looks good now 👍

File: src/include/duckdb/common/preserved_error.hpp [hunk 2]
```diff
@@ -23,8 +23,17 @@ class PreservedError {
 	      exception_instance(nullptr) {
 		// Given a message in the form: 	xxxxx Error: yyyyy
 		// Try to match xxxxxxx with known error so to potentially reconstruct the original error type
-		string err = raw_message.substr(0, raw_message.find(':'));
-		string msg = raw_message.substr(raw_message.find(':') + 2);
+		auto position_semicolon = raw_message.find(':');
```
Comment (Mytherin) [inline src/include/duckdb/common/preserved_error.hpp:26]: Can we move this code to `PreservedError(const string &raw_message)` (in the .cpp file) and have this constructor only forward to that constructor (i.e. `PreservedError(ex.what())`)?

Comment (carlopi) [reply src/include/duckdb/common/preserved_error.hpp:26]: Sure, will do.

**Comment by Mytherin** [comment]
Thanks!
