### PR TITLE
[C-API] Add `duckdb_string_t` for use with the data chunk API

### LINKED ISSUE #7154: [C-API] `string_t` definition is missing from `duckdb.h`
### What happens?

When using the data chunk API, to access the data of the Vectors, we need to cast the data pointer into a type that has the same memory layout as `duckdb::string_t`, which is defined in the C++ API, and currently not exposed to the C-API

This should also be added to the docs once it's added, since it's not super obvious what the internal representation of our VARCHAR columns is.

### To Reproduce

-

### OS:

MacOS

### DuckDB Version:

master

### DuckDB Client:

C-API

### Full Name:

Thijs Bruineman

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #7154 

I've added the struct as part of `duckdb.h`, and accompanied it with a test showcasing how it can be used to retrieve data from a string column.

### CODE REVIEW

File: src/include/duckdb.h [hunk 1]
```diff
@@ -751,6 +770,13 @@ This is the amount of tuples that will fit into a data chunk created by `duckdb_
 */
 DUCKDB_API idx_t duckdb_vector_size();
 
+/*!
+Whether or not the duckdb_string_t value is inlined.
+This means that the data of the string does not have a separate allocation.
+
+*/
+DUCKDB_API bool duckdb_string_is_inlined(duckdb_string_t *string);
```
Comment (Mytherin) [inline src/include/duckdb.h:778]: Can we remove the pointer here and just pass in a `duckdb_string_t`?

**Review by Mytherin — COMMENTED** [review]
Thanks! LGTM - one minor comment
