### PR TITLE
[Bitstring] Add overload for `bitstring` to accept BIT as the type of the first argument

### LINKED ISSUE #14216: No function matches 'bitstring(BIT, INTEGER_LITERAL)'
### What happens?

The [bitstring function](https://duckdb.org/docs/sql/functions/bitstring.html#bitstringbitstring-length) doesn't work. The given example results in this error:

```
Binder Error: No function matches the given name and argument types 'bitstring(BIT, INTEGER_LITERAL)'. You might need to add explicit type casts.
	Candidate functions:
	bitstring(VARCHAR, INTEGER) -> BIT

LINE 1: SELECT bitstring('1010'::BITSTRING, 7);
```

### To Reproduce

```sql
SELECT bitstring('1010'::BITSTRING, 7);
```

### OS:

Linux

### DuckDB Version:

1.0.0

### DuckDB Client:

CLI

### Hardware:

_No response_

### Full Name:

Liam Diprose

### Affiliation:

Liam Diprose

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #14216

### CODE REVIEW

File: src/core_functions/scalar/bit/bitstring.cpp [hunk 1]
```diff
@@ -7,12 +7,18 @@ namespace duckdb {
...
+template <bool FROM_STRING>
 static void BitStringFunction(DataChunk &args, ExpressionState &state, Vector &result) {
 	BinaryExecutor::Execute<string_t, int32_t, string_t>(
 	    args.data[0], args.data[1], result, args.size(), [&](string_t input, int32_t n) {
 		    if (n < 0) {
 			    throw InvalidInputException("The bitstring length cannot be negative");
 		    }
+		    if (!FROM_STRING) {
+			    // FIXME: this could be optimized to not go through the VARCHAR -> BIT path
+			    auto converted = Bit::ToString(input);
```
Comment (Mytherin) [inline src/core_functions/scalar/bit/bitstring.cpp:19]: This looks like it will not work for bitstrings that are not inlined as the `std::string` object will be destroyed. Can we add a test for this?

**Comment by Mytherin** [comment]
Thanks for the PR! LGTM - one comment

File: src/core_functions/scalar/bit/bitstring.cpp (hunk 1 above)
Comment (Tishj) [reply src/core_functions/scalar/bit/bitstring.cpp:19]: Hmm that's a good point, I hadn't considered that

**Comment by Tishj** [comment]
I've added a `using` declaration to differentiate logically between a string_t and a bitstring_t so we know what the argument is supposed to represent

But in the future we should probably do this:
```c++
struct bitstring_t : public string_t { // NOLINT
};
```

(this is also what we do for the timestamp variants)
```c++
struct timestamp_tz_t : public timestamp_t { // NOLINT
};
struct timestamp_ns_t : public timestamp_t { // NOLINT
};
struct timestamp_ms_t : public timestamp_t { // NOLINT
};
struct timestamp_sec_t : public timestamp_t { // NOLINT
};
```

So this differentiation is explicit at the type system level, while still sharing the same underlying physical representation

File: src/core_functions/scalar/bit/bitstring.cpp (hunk 1 above)
Comment (Tishj) [reply src/core_functions/scalar/bit/bitstring.cpp]: I went ahead and implemented the optimization I suggested
It's mostly code stolen from `Bit::RightShift`
