### PR TITLE
[Python] Fix bug that caused a crash on conversion to arrow

### LINKED ISSUE #6438: [Python] Segfault on CREATE TABLE x AS SELECT * FROM polars_df
### What happens?

Segmentation fault when trying to import a polars dataframe as a table

Versions of related things
```
Polars 0.16.8
Python 3.10.9 (happens with 3.11 as well)
```

Running with lldb shows the following stack trace:
```
* thread #2, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x10)
  * frame #0: 0x00000001005147f8 Python`_PyUnicode_FromId + 36
    frame #1: 0x000000010058c570 Python`PyImport_Import + 56
    frame #2: 0x000000010058c4dc Python`PyImport_ImportModule + 60
    frame #3: 0x000000012bdc0bdc duckdb.cpython-310-darwin.so`duckdb::PythonImportCacheItem::LoadModule(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, duckdb::PythonImportCache&) + 64
    frame #4: 0x000000012bd48f14 duckdb.cpython-310-darwin.so`duckdb::VerifyArrowDatasetLoaded() + 96
    frame #5: 0x000000012bd4aa98 duckdb.cpython-310-darwin.so`duckdb::PythonTableArrowArrayStreamFactory::GetSchema(unsigned long, duckdb::ArrowSchemaWrapper&) + 48
    frame #6: 0x000000012ba24414 duckdb.cpython-310-darwin.so`duckdb::ArrowTableFunction::ArrowScanBind(duckdb::ClientContext&, duckdb::TableFunctionBindInput&, std::__1::vector<duckdb::LogicalType, std::__1::allocator<duckdb::LogicalType> >&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&) + 212
    frame #7: 0x000000012bc245e8 duckdb.cpython-310-darwin.so`duckdb::Binder::BindTableFunctionInternal(duckdb::TableFunction&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<duckdb::Value, std::__1::allocator<duckdb::Value> >, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, duckdb::Value, duckdb::CaseInsensitiveStringHashFunction, duckdb::CaseInsensitiveStringEquality, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, duckdb::Value> > >, std::__1::vector<duckdb::LogicalType, std::__1::allocator<duckdb::LogicalType> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::unique_ptr<duckdb::ExternalDependency, std::__1::default_delete<duckdb::ExternalDependency> >) + 160
    frame #8: 0x000000012bc25948 duckdb.cpython-310-darwin.so`duckdb::Binder::Bind(duckdb::TableFunctionRef&) + 1280
    frame #9: 0x000000012bbc9e8c duckdb.cpython-310-darwin.so`duckdb::Binder::Bind(duckdb::TableRef&) + 140
    frame #10: 0x000000012bc1f124 duckdb.cpython-310-darwin.so`duckdb::Binder::Bind(duckdb::BaseTableRef&) + 4280
    frame #11: 0x000000012bbc9e48 duckdb.cpython-310-darwin.so`duckdb::Binder::Bind(duckdb::TableRef&) + 72
    frame #12: 0x000000012bbef830 duckdb.cpython-310-darwin.so`duckdb::Binder::BindNode(duckdb::SelectNode&) + 280
    frame #13: 0x000000012bbc9ad4 duckdb.cpython-310-darwin.so`duckdb::Binder::BindNode(duckdb::QueryNode&) + 104
    frame #14: 0x000000012bbc9b58 duckdb.cpython-310-darwin.so`duckdb::Binder::Bind(duckdb::QueryNode&) + 40
    frame #15: 0x000000012bc07da8 duckdb.cpython-310-darwin.so`duckdb::Binder::BindCreateTableInfo(std::__1::unique_ptr<duckdb::CreateInfo, std::__1::default_delete<duckdb::CreateInfo> >, duckdb::SchemaCatalogEntry*) + 180
    frame #16: 0x000000012bc05058 duckdb.cpython-310-darwin.so`duckdb::Binder::Bind(duckdb::CreateStatement&) + 3928
    frame #17: 0x000000012bbd3c58 duckdb.cpython-310-darwin.so`duckdb::Planner::CreatePlan(duckdb::SQLStatement&) + 176
    frame #18: 0x000000012ba78e8c duckdb.cpython-310-darwin.so`duckdb::ClientContext::CreatePreparedStatement(duckdb::ClientContextLock&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::unique_ptr<duckdb::SQLStatement, std::__1::default_delete<duckdb::SQLStatement> >, std::__1::vector<duckdb::Value, std::__1::allocator<duckdb::Value> >*) + 904
    frame #19: 0x000000012baae894 duckdb.cpython-310-darwin.so`std::__1::__function::__func<duckdb::ClientContext::PrepareInternal(duckdb::ClientContextLock&, std::__1::unique_ptr<duckdb::SQLStatement, std::__1::default_delete<duckdb::SQLStatement> >)::$_1, std::__1::allocator<duckdb::ClientContext::PrepareInternal(duckdb::ClientContextLock&, std::__1::unique_ptr<duckdb::SQLStatement, std::__1::default_delete<duckdb::SQLStatement> >)::$_1>, void ()>::operator()() + 56
    frame #20: 0x000000012ba7b500 duckdb.cpython-310-darwin.so`duckdb::ClientContext::RunFunctionInTransactionInternal(duckdb::ClientContextLock&, std::__1::function<void ()> const&, bool) + 128
    frame #21: 0x000000012ba7b9d8 duckdb.cpython-310-darwin.so`duckdb::ClientContext::PrepareInternal(duckdb::ClientContextLock&, std::__1::unique_ptr<duckdb::SQLStatement, std::__1::default_delete<duckdb::SQLStatement> >) + 256
    frame #22: 0x000000012ba7bf14 duckdb.cpython-310-darwin.so`duckdb::ClientContext::Prepare(std::__1::unique_ptr<duckdb::SQLStatement, std::__1::default_delete<duckdb::SQLStatement> >) + 140
    frame #23: 0x000000012ba86cb4 duckdb.cpython-310-darwin.so`duckdb::Connection::Prepare(std::__1::unique_ptr<duckdb::SQLStatement, std::__1::default_delete<duckdb::SQLStatement> >) + 40
    frame #24: 0x000000012bd6d224 duckdb.cpython-310-darwin.so`duckdb::DuckDBPyConnection::ExecuteInternal(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, pybind11::object, bool) + 412
    frame #25: 0x000000012bd747cc duckdb.cpython-310-darwin.so`duckdb::DuckDBPyConnection::RunQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 276
    frame #26: 0x000000012bd91684 duckdb.cpython-310-darwin.so`duckdb::PyConnectionWrapper::RunQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<duckdb::DuckDBPyConnection>) + 184
    frame #27: 0x000000012bd274fc duckdb.cpython-310-darwin.so`void pybind11::cpp_function::initialize<std::__1::unique_ptr<duckdb::DuckDBPyRelation, std::__1::default_delete<duckdb::DuckDBPyRelation> > (*&)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<duckdb::DuckDBPyConnection>), std::__1::unique_ptr<duckdb::DuckDBPyRelation, std::__1::default_delete<duckdb::DuckDBPyRelation> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<duckdb::DuckDBPyConnection>, pybind11::name, pybind11::scope, pybind11::sibling, char [128], pybind11::arg, pybind11::arg_v, pybind11::arg_v>(std::__1::unique_ptr<duckdb::DuckDBPyRelation, std::__1::default_delete<duckdb::DuckDBPyRelation> > (*&)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<duckdb::DuckDBPyConnection>), std::__1::unique_ptr<duckdb::DuckDBPyRelation, std::__1::default_delete<duckdb::DuckDBPyRelation> > (*)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<duckdb::DuckDBPyConnection>), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&, char const (&) [128], pybind11::arg const&, pybind11::arg_v const&, pybind11::arg_v const&)::'lambda'(pybind11::detail::function_call&)::operator()(pybind11::detail::function_call&) const + 236
    frame #28: 0x000000012bd0c7cc duckdb.cpython-310-darwin.so`pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 3780
    frame #29: 0x00000001004be49c Python`cfunction_call + 60
    frame #30: 0x000000010046d238 Python`_PyObject_MakeTpCall + 136
    frame #31: 0x0000000100566d8c Python`call_function + 272
    frame #32: 0x0000000100564504 Python`_PyEval_EvalFrameDefault + 42676
    frame #33: 0x0000000100558bf0 Python`_PyEval_Vector + 376
    frame #34: 0x0000000100558a64 Python`PyEval_EvalCode + 104
    frame #35: 0x00000001005b3108 Python`run_eval_code_obj + 84
    frame #36: 0x00000001005b306c Python`run_mod + 112
    frame #37: 0x00000001005b2d00 Python`pyrun_file + 148
    frame #38: 0x00000001005b2634 Python`_PyRun_SimpleFileObject + 268
    frame #39: 0x00000001005b1c78 Python`_PyRun_AnyFileObject + 232
    frame #40: 0x00000001005d4d10 Python`pymain_run_file_obj + 220
    frame #41: 0x00000001005d4460 Python`pymain_run_file + 72
    frame #42: 0x00000001005d3cf0 Python`Py_RunMain + 872
    frame #43: 0x00000001005d50ec Python`Py_BytesMain + 40
    frame #44: 0x00000001ab887e50 dyld`start + 2544
```

### To Reproduce

Following script causes a segmentation fault
```python
import polars as pl
import duckdb

df = pl.DataFrame({"a": [1, 2, 3]})
duckdb.sql("CREATE TABLE x AS SELECT * FROM df")
```

### OS:

MacOS 13.1

### DuckDB Version:

0.7.0

### DuckDB Client:

Python

### Full Name:

Vesa Vilhonen

### Affiliation:

Personal

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #6438 

Until not too long ago, we loaded all imports at the start, while holding the GIL.
We recently moved to lazy-loading modules, and this was one of the places where the GIL was not held as the import took place - which caused the crash.

This PR adds some internal functions to verify proper management of the GIL:

`gil_check()`
\- returns a boolean indicating if the GIL is held
`gil_assert()`
\- asserts that gil_check returns True

### CODE REVIEW

File: tools/pythonpkg/src/python_import_cache.cpp [hunk 1]
```diff
@@ -36,6 +36,7 @@ PyObject *PythonImportCacheItem::AddCache(PythonImportCache &cache, py::object o
 void PythonImportCacheItem::LoadModule(const string &name, PythonImportCache &cache) {
 	load_attempted = true;
 	try {
+		py::gil_assert();
```
Comment (pdet) [inline tools/pythonpkg/src/python_import_cache.cpp:39]: If I understand this correctly, `gil_check()` returns if the thread is holding the GIL or not, right?
Wouldn't it be the case that if it's not we just acquire the GIL for the Load Module function?
As in replace this with an if ...

Comment (Tishj) [reply tools/pythonpkg/src/python_import_cache.cpp:39]: Yea I also thought of this, but Mark correctly pointed out that would cause us to silently degrade our GIL handling code, creating a lot of locks and unlocks instead of just one of each

Comment (Tishj) [reply tools/pythonpkg/src/python_import_cache.cpp:39]: But maybe in the case of LoadModule it might be fine?

Comment (Mytherin) [reply tools/pythonpkg/src/python_import_cache.cpp:39]: I would say we should just never call `LoadModule` outside of places where we hold the GIL. This is likely to hide other bugs as well. For example, we might do something like `arrow().attr("function")()`. Now the `arrow` load correctly grabs the GIL but the function call does not - hiding a bug.

I would say perhaps this should not only be an assertion but also be checked in release mode/throw an internal exception. I don't think our Python code runs with assertions in the CI, at least not for all tests.

Comment (pdet) [reply tools/pythonpkg/src/python_import_cache.cpp:39]: Fair enough, I think internal exception sounds excellent.

Comment (Tishj) [reply tools/pythonpkg/src/python_import_cache.cpp:39]: @Mytherin 
```c++
	if (!gil_check()) {
		throw duckdb::InternalException("The GIL should be held for this operation, but it's not!");
	}
```
