### PR TITLE
Fix union struct implict cast

### LINKED ISSUE #12843: Cannot insert into a UNION with two structs without using the `union_value` function
### What happens?

Cannot insert into a UNION with two structs without using the `union_value` function.  Both unnamed and named structs don't work.

### To Reproduce

```
create table t3 (id integer, u union(s1 struct(f1 string, f2 int), s2 struct(b1 string)));
```
```
D insert into t3 values (1, row('a'));
Mismatch Type Error: Type STRUCT(VARCHAR) does not match with STRUCT(f1 VARCHAR, f2 INTEGER). Cannot cast STRUCTs of different size
LINE 1: insert into t3 values (1, row('a'));
                                  ^
D insert into t3 values (1, row('a', 3));
Mismatch Type Error: Type STRUCT(VARCHAR, INTEGER) does not match with STRUCT(b1 VARCHAR). Cannot cast STRUCTs of different size
LINE 1: insert into t3 values (1, row('a', 3));
                                  ^
D insert into t3 values (1, {b1: 'a'});
Mismatch Type Error: Type STRUCT(b1 VARCHAR) does not match with STRUCT(f1 VARCHAR, f2 INTEGER). Cannot cast STRUCTs of different size
LINE 1: insert into t3 values (1, {b1: 'a'})
                                   ^
```

### OS:

MacOS

### DuckDB Version:

1.0

### DuckDB Client:

CLI

### Full Name:

Robert Yokota

### Affiliation:

Confluent

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by Maxxen**
Closes #12843 

With this PR, the implicit cast cost for union->union and struct->struct casts are properly calculated, instead of always returning 0.

The issue is that when casting a type into a union, we try to target the member with the lowest implicit cast cost, but we didn't actually compute the cast cost between two different structs, we just always return 0 and rely on the actual struct cast implementation to check that the cast is valid. This could then lead to the wrong union member being chosen If the union contains multiple struct members, as the "first" one would always be picked regardless if it was compatible or not.

Additionally, we also didnt compute the proper implicit cast cost between two unions. Even though we had logic to do it, it was effectively dead code as the `if(from.id() == to.id()` branch would always trigger before.

### CODE REVIEW

File: src/function/cast_rules.cpp [hunk 1]
```diff
@@ -437,19 +440,87 @@ int64_t CastRules::ImplicitCast(const LogicalType &from, const LogicalType &to)
...
+			for (idx_t source_idx = 0; source_idx < source_children.size(); source_idx++) {
+				auto &source_child = source_children[source_idx];
+				auto entry = target_members.find(source_child.first);
+				if (entry == target_members.end()) {
+					// element in source struct was not found in target struct
+					return -1;
+				}
+				auto target_idx = entry->second;
+				target_members.erase(entry);
+				auto child_cost = ImplicitCast(source_child.second, target_children[target_idx].second);
```
Comment (Mytherin) [inline src/function/cast_rules.cpp:484]: We should probably return `-1` if any of the children is not implicitly castable, no?

**Review by Mytherin — COMMENTED** [review]
Thanks! LGTM - one minor comment. Perhaps we can add some more tests that stress the new casting rules as well?

**Comment by Mytherin** [comment]
Thanks!
