### PR TITLE
 fix(adbc): return error when setting an empty sql query

### LINKED ISSUE #20050: duckdb 1.4 adbc segfault on empty sql
### What happens?

We get a segmentation fault when we have an empty sql or a sql with just commented out lines. We would expect an error.

The Address Sanitizer outputs:
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==33365==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000182972a44 bp 0x00016efea210 sp 0x00016efe99d0 T0)
==33365==The signal is caused by a READ memory access.
==33365==Hint: address points to the zero page.
    #0 0x000182972a44 in _platform_strlen+0x4 (libsystem_platform.dylib:arm64e+0xa44)
    #1 0x000320d3f810 in unsigned long std::__1::__constexpr_strlen[abi:ne190102]<char>(char const*) constexpr_c_functions.h:66
    #2 0x000320d3f690 in std::__1::char_traits<char>::length[abi:ne190102](char const*) char_traits.h:229
    #3 0x00032e0f5800 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::basic_string[abi:ne190102]<0>(char const*) string:1062
    #4 0x00032e0f55f8 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::basic_string[abi:ne190102]<0>(char const*) string:1060
    #5 0x0003249c6790 in duckdb_adbc::CheckResult(duckdb_state const&, AdbcError*, char const*) adbc.cpp:133
    #6 0x0003249c00c0 in duckdb_adbc::StatementSetSqlQuery(AdbcStatement*, char const*, AdbcError*) adbc.cpp:1015
    #7 0x0001010a6d68 in _cgo_225af673cf90_Cfunc_AdbcStatementSetSqlQuery+0x24 (test_crash:arm64+0x100292d68)
    #8 0x000100e8a108 in runtime.asmcgocall.abi0+0x78 (test_crash:arm64+0x100076108)

==33365==Register values:
 x[0] = 0x0000000000000000   x[1] = 0x0000000000000000   x[2] = 0x000000016efea290   x[3] = 0x000000016efea660
 x[4] = 0x0000000000000008   x[5] = 0x0000000000000008   x[6] = 0x000000016e7f0000   x[7] = 0x0000000000000001
 x[8] = 0x0000000000000001   x[9] = 0x000000702de1d450  x[10] = 0x000000702de1d452  x[11] = 0x000000016efea270
x[12] = 0x000000016efea268  x[13] = 0x000000016efea260  x[14] = 0x00007fffffffffff  x[15] = 0x000010700001ffff
x[16] = 0x0000000182972a40  x[17] = 0x0000000101e408a8  x[18] = 0x0000000000000000  x[19] = 0x000000016efea2a0
x[20] = 0x0000000000000001  x[21] = 0x0000000000000000  x[22] = 0x0000000101434bcc  x[23] = 0x00000001f0650018
x[24] = 0x00000001f0650150  x[25] = 0x0000000000000000  x[26] = 0x0000000000000000  x[27] = 0x0000000000000838
x[28] = 0x000000010140d480     fp = 0x000000016efea210     lr = 0x0000000101e16ab8     sp = 0x000000016efe99d0
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (libsystem_platform.dylib:arm64e+0xa44) in _platform_strlen+0x4
==33365==ABORTING
```

It points to the code here: https://github.com/duckdb/duckdb/blob/2692b94466b0244d8417591f7518efe3ffa04dbe/src/common/adbc/adbc.cpp#L133.

Which on my machine is linked to a function with following comment:
```
//! This method should only be called when the string is guaranteed to not be NULL
void SetError(struct AdbcError *error, const std::string &message);
```

So is it possible `error_msg` is null?

### To Reproduce

Run as follows:

```bash
go get github.com/apache/arrow-adbc/go/adbc

go mod init adbc_test/test_crash
go mod tidy

go build -o test_crash test_crash.go
DYLD_INSERT_LIBRARIES=/Library/Developer/CommandLineTools/usr/lib/clang/17/lib/darwin/libclang_rt.asan_osx_dynamic.dylib DYLD_LIBRARY_PATH=path/to/duckdb/build/debug/src ./test_crash
```

```go
package main

import (
	"context"
	"fmt"

	"github.com/apache/arrow-adbc/go/adbc"
	"github.com/apache/arrow-adbc/go/adbc/drivermgr"
)

type DuckDBSQLRunner struct {
	ctx  context.Context
	conn adbc.Connection
	db   adbc.Database
}

func NewDuckDBSQLRunner(ctx context.Context) (*DuckDBSQLRunner, error) {
	var drv drivermgr.Driver
	db, err := drv.NewDatabase(map[string]string{
		"driver":     "duckdb",
		"entrypoint": "duckdb_adbc_init",
		"path":       ":memory:",
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create new in-memory DuckDB database: %w", err)
	}
	conn, err := db.Open(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to open connection to new in-memory DuckDB database: %w", err)
	}
	return &DuckDBSQLRunner{ctx: ctx, conn: conn, db: db}, nil
}

func main() {
	ctx := context.Background()
	runner, _ := NewDuckDBSQLRunner(ctx)

	conn, _ := runner.db.Open(ctx)
	stmt, _ := conn.NewStatement()
	defer stmt.Close()

	stmt.SetSqlQuery("--");
}
```

### OS:

Mac arm

### DuckDB Version:

1.4, commit 2692b94466b0244d8417591f7518efe3ffa04dbe

### DuckDB Client:

go adbc

### Hardware:

_No response_

### Full Name:

Gishor Sivanrupan

### Affiliation:

Exaforce

### Did you include all relevant configuration (e.g., CPU architecture, Linux distribution) to reproduce the issue?

- [x] Yes, I have

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### PR DESCRIPTION
**Pull request by gishor**
Return an error instead of a segmentation fault.

This is also an issue in the main branch.

Fixes #20050

### CODE REVIEW

**Comment by pdet** [comment]
Hi @gishor, can you re-target to v1.4?

**Comment by gishor** [comment]
Hi @pdet, okay changed the target 👍

File: src/common/adbc/adbc.cpp [hunk 1]
```diff
@@ -1006,6 +1006,13 @@ AdbcStatusCode StatementSetSqlQuery(struct AdbcStatement *statement, const char
 		duckdb_destroy_extracted(&extracted_statements);
 		return ADBC_STATUS_INTERNAL;
 	}
+
+	if (extract_statements_size == 0) {
+		SetError(error, "No statements found");
+		duckdb_destroy_extracted(&extracted_statements);
+		return ADBC_STATUS_INVALID_ARGUMENT;
+	}
+
```
Comment (pdet) [inline src/common/adbc/adbc.cpp:1039]: I'm not sure if we should error or just return an empty set.

From what I can tell from ODBC, empty result sets are usually given, but it might also be engine dependent.
@maiadegraaf could you confirm what our ODBC behavior is?

@ianmcook, from the ADBC perspective, is there any preference?

Comment (ianmcook) [reply src/common/adbc/adbc.cpp:1039]: @lidavidm could you confirm what the standard/correct behavior should be in this case?

Comment (lidavidm) [reply src/common/adbc/adbc.cpp:1039]: Usually we error on a literal empty string, but I suppose `--` could produce an empty result set

Comment (maiadegraaf) [reply src/common/adbc/adbc.cpp:1039]: > From what I can tell from ODBC, empty result sets are usually given, but it might also be engine dependent.

Yeah exactly, both an empty string and a comment return an empty result set.

**Comment by pdet** [comment]
@gishor, considering @lidavidm's comment, could you change this PR to return an empty result set if `--`?

Then I think it's good to go.

Thanks for the work you put in for the PR!

**Comment by gishor** [comment]
@pdet 

I don't know how to make sure any subsequent code accessing `AdbcStatement` (like when we call `StatementExecuteQuery` afterwards) works as expected. I think we have to set `wrapper->statement` to something non-null, is that correct? I tried something like this, but got an error "Invalid Input Error: No statement to prepare!".

```cpp

	if (extract_statements_size == 0) {
		auto res = duckdb_prepare(wrapper->connection, query, &wrapper->statement);
		auto error_msg = duckdb_prepare_error(wrapper->statement);
		duckdb_destroy_extracted(&extracted_statements);
		return CheckResult(res, error, error_msg);
	}

```

Is there a better way?

**Comment by pdet** [comment]
> @pdet
> 
> I don't know how to make sure any subsequent code accessing `AdbcStatement` (like when we call `StatementExecuteQuery` afterwards) works as expected. I think we have to set `wrapper->statement` to something non-null, is that correct? I tried something like this, but got an error "Invalid Input Error: No statement to prepare!".
> 
> ```c++
> 	if (extract_statements_size == 0) {
> 		auto res = duckdb_prepare(wrapper->connection, query, &wrapper->statement);
> 		auto error_msg = duckdb_prepare_error(wrapper->statement);
> 		duckdb_destroy_extracted(&extracted_statements);
> 		return CheckResult(res, error, error_msg);
> 	}
> ```
> 
> Is there a better way?

I think you can just return an ok in `StatementSetSqlQuery` and in `StatementExecuteQuery` you can check if the statement is set? If not you return ok, `rows_affected = 0`, and the `out` attributes to null.

**Comment by gishor** [comment]
That sounds good, I was worried as I don't know if the output of `StatementSetSqlQuery` is used in other functions. What do you think about the last two commits?

Note that I still changed the function `ArrowTestHelper::RunArrowComparison` to handle ArrowArrayStream.

File: test/api/adbc/test_adbc.cpp [hunk 2]
```diff
@@ -140,6 +140,21 @@ TEST_CASE("ADBC - Select 42", "[adbc]") {
...
 }
 
+TEST_CASE("ADBC - non-empty query without actual statements", "[adbc]") {
+	if (!duckdb_lib) {
+		return;
+	}
+	ADBCTestDatabase db;
+
+	SECTION("Whitespace") {
+		REQUIRE(db.QueryAndCheck(" "));
```
Comment (pdet) [inline test/api/adbc/test_adbc.cpp]: This should behave the same as `""`

File: src/common/adbc/adbc.cpp [hunk 3]
```diff
@@ -862,6 +862,18 @@ AdbcStatusCode StatementExecuteQuery(struct AdbcStatement *statement, struct Arr
 	if (has_stream && to_table) {
 		return IngestToTableFromBoundStream(wrapper, error);
 	}
+
+	if (!wrapper->statement) {
```
Comment (pdet) [inline src/common/adbc/adbc.cpp:868]: We should probably set `rows_affected`

**Review by pdet — COMMENTED** [review]
Actually, I have two more requests!

File: src/common/adbc/adbc.cpp (hunk 3 above)
Comment (gishor) [reply src/common/adbc/adbc.cpp:868]: Like this? https://github.com/duckdb/duckdb/pull/20071/changes/230ba63a7509820aadedc60b2e1bb0f01e5bed94

**Comment by pdet** [comment]
Looks great! Thanks for all the work you put in @gishor!
