### PR TITLE
Properly send mapped function on RAPI

### LINKED ISSUE #3237: Python access violation exception
#### What happens?
Operation throws an Access Violation Exception

#### To Reproduce
```
import duckdb
import pandas as pd
from datetime import date, timedelta

def process(rel):
    def mapper(x):
        dates = x['date'].to_numpy("datetime64[us]")
        days = x['days_to_add'].to_numpy("int")
        x["result1"] = pd.Series([pd.to_datetime(y[0]).date() + timedelta(days=y[1].item()) for y in zip(dates,days)], dtype='datetime64[us]')
        x["result2"] = pd.Series([pd.to_datetime(y[0]).date() + timedelta(days=-y[1].item()) for y in zip(dates,days)], dtype='datetime64[us]')
        return x

    rel = rel.map(mapper)
    rel = rel.project("*, datediff('day', date, result1) as one")
    rel = rel.project("*, datediff('day', date, result2) as two")
    rel = rel.project("*, IF(ABS(one) > ABS(two), one, two) as three")
    #  rel = duckdb.from_df(rel.execute().fetchdf())  # <-- It works fine if uncommenting this line, i.e. if materializing the table here
    return rel

def main():
  df = pd.DataFrame({'date': pd.Series([date(2000,1,1), date(2000,1,2)], dtype="datetime64[us]"), 'days_to_add': [1,2]})
  rel = duckdb.from_df(df)
  rel = process(rel)
  x = rel.execute().fetchdf()
  return x

main()
```

#### Environment (please complete the following information):
 - OS: Windows 10
 - DuckDB Version: 0.3.2
 - DuckDB Client: Python

#### Crash dump

Just for reference, "!analyze -v" output from a crashdump. Please mind, this was NOT the dump from the example above, but from my "real world use case" where this happened - I assume the cause would be quite similar though

[crashdump_analysis.txt](https://github.com/duckdb/duckdb/files/8253644/crashdump_analysis.txt)

### PR DESCRIPTION
**Pull request by pdet**
Basically, when creating relations through the RAPI we must ensure a copy of the mapped function in that relation.
Ow, if the function goes out of the scope, it will cause a crash since the relation doesn't hold a proper hold of that (i.e., did not increment the ref_counter, although depends on that function).

fix: #3237

### CODE REVIEW

File: tools/pythonpkg/src/pyrelation.cpp [hunk 1]
```diff
@@ -198,23 +202,23 @@ unique_ptr<DuckDBPyRelation> DuckDBPyRelation::AliasDF(py::object df, const stri
 }
 
 unique_ptr<DuckDBPyRelation> DuckDBPyRelation::Filter(const string &expr) {
-	return make_unique<DuckDBPyRelation>(rel->Filter(expr));
+	return make_unique<DuckDBPyRelation>(rel->Filter(expr), map_function);
```
Comment (hannes) [inline tools/pythonpkg/src/pyrelation.cpp:205]: I think this should not be in every single constructor. Can't we keep a reference to the function in the map relation only?
