### PR TITLE
Issue #12412: AsOf Filter Push

### LINKED ISSUE #12412: BETWEEN incorrectly pushed into ASOF JOIN
### What happens?

a predicate from an outer query block gets pushed, even through a CTE, into an ASOF JOIN predicate.
This is a follow up to https://github.com/duckdb/duckdb/issues/12215
The exact example in that bug has been fixed, but a similar query produces incorrect results.

### To Reproduce

consider the query 
```
SELECT
    t1.col0 AS left_val,
    t2.col0 AS right_val,
FROM
    (VALUES (0), (5), (10), (15)) AS t1
    ASOF JOIN (VALUES (1), (6), (11), (16)) AS t2
    ON t2.col0 > t1.col0
```

This correctly returns
```
|    |   left_val |   right_val |
|---:|-----------:|------------:|
|  0 |         15 |          16 |
|  1 |         10 |          11 |
|  2 |          5 |           6 |
|  3 |          0 |           1 |
```
printed via a pandas dataframe, hence the implicit index as the first column.

placing the above query in a CTE (t) and filtering rows based on right_value:
```
WITH t as (
    SELECT
        t1.col0 AS left_val,
        t2.col0 AS right_val,
    FROM
        (VALUES (0), (5), (10), (15)) AS t1
        ASOF JOIN (VALUES (1), (6), (11), (16)) AS t2
        ON t2.col0 > t1.col0
)
SELECT *
FROM t
WHERE right_val BETWEEN 3 AND 12
;
```

returns
```
|    |   left_val |   right_val |
|---:|-----------:|------------:|
|  0 |         10 |          11 |
|  1 |          5 |           6 |
|  2 |          0 |           6 |
```

It should return
```
|    |   left_val |   right_val |
|---:|-----------:|------------:|
|  0 |         10 |          11 |
|  1 |          5 |           6 |
```

left_val 0 is joining to right_val 6, but it should have joined to right_val 1 and then get filtered out.  The filter is being pushed such that t2.col0 = 1 is filtered out prior to the join changing the _values_ of the join instead of _which rows_ are later filtered.

Note that the same predicate applied to left_value returns the correct result.

### OS:

M1 MacOS 14.4.1 (23E224) inside a docker container uname -a: Linux 4f7cfa19b600 6.6.22-linuxkit #1 SMP Fri Mar 29 12:21:27 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

### DuckDB Version:

1.0.0

### DuckDB Client:

Python

### Full Name:

Steven Pelley

### Affiliation:

None (retired/not currently employed)

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by hawkfish**
Don't push or pull filters through the right side of AsOf joins. AsOf is a table lookup, so we shouldn't mess with the table.

fixes: duckdb#12412
fixes: duckdblabs/duckdb-internal#2235

### CODE REVIEW

File: src/optimizer/filter_pullup.cpp [hunk 1]
```diff
@@ -38,7 +38,12 @@ unique_ptr<LogicalOperator> FilterPullup::PullupJoin(unique_ptr<LogicalOperator>
 
 	switch (join.join_type) {
 	case JoinType::INNER:
-		return PullupInnerJoin(std::move(op));
+		if (op->type == LogicalOperatorType::LOGICAL_ASOF_JOIN) {
+			//	We can only move filters through the left side of AsOf joins.
+			return PullupFromLeft(std::move(op));
+		} else {
+			return PullupInnerJoin(std::move(op));
```
Comment (Tmonster) [inline src/optimizer/filter_pullup.cpp:45]: nit: The else can be removed

**Review by Tmonster — APPROVED** [review]
looks good to me!

**Comment by Mytherin** [comment]
Thanks! LGTM
