### PR TITLE
Fix missing replacement scan code for CTEs

### LINKED ISSUE #19156: CTE lookup fails if CTE name conflicts with a filename used in a replacement scan
### What happens?

#19116 broke a [test in the DuckDB Python package](https://github.com/duckdb/duckdb-python/blob/af60d44dcc9992b77c15fe961542b33d4c2829b3/tests/fast/test_replacement_scan.py#L312) that checks you can create a CTE with the same name as a filename used for replacement scanning in the CTE.

Can you please have a look at his, @kryonix ?

### To Reproduce

This is an MRE (that should be a test in core, feel free to copy from [this PR](https://github.com/duckdb/duckdb/pull/19154)) in the CLI:
```
❯ duckdb
DuckDB v1.4.0 (Andium) b8a06e4a22
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D copy (select 42 as answer) to 'df.parquet';
D WITH 'df.parquet' AS (
      SELECT answer FROM 'df.parquet'
  )
  SELECT * FROM 'df.parquet';
┌────────┐
│ answer │
│ int32  │
├────────┤
│   42   │
└────────┘

❯ ./build/release/duckdb
DuckDB v1.5.0-dev370 (Development Version) 4bfb6e2f8c
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D WITH 'df.parquet' AS (
      SELECT answer FROM 'df.parquet'
  )
  SELECT * FROM 'df.parquet';
Binder Error:
Circular reference to CTE "df.parquet", There are two possible solutions.
1. use WITH RECURSIVE to use recursive CTEs.
2. If you want to use the TABLE name "df.parquet" the same as the CTE name, please explicitly add "SCHEMA" before table name. You can try "main.df.parquet" (main is the duckdb default schema)

LINE 2:     SELECT answer FROM 'df.parquet'
                               ^
```

### OS:

OSX, Linux, Windows

### DuckDB Version:

1.4.1.dev

### DuckDB Client:

core

### Hardware:

_No response_

### Full Name:

Evert

### Affiliation:

DuckDB Labs

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [x] Yes, I have

### PR DESCRIPTION
**Pull request by kryonix**
This reverts commit ad231d310ee29626faa7d4b7bbb5746bdb93b61b.

---

Fix: https://github.com/duckdb/duckdb/issues/19156

### CODE REVIEW

**Comment by szarnyasg** [comment]
cc @evertlammerts

**Comment by Mytherin** [comment]
Thanks for the PR!

Reverting this will break another test (`test/sql/attach/attach_default_table.test`).

In general the logic introduced here does not seem correct to me. Replacement scans should only be triggered if regular binding fails. The code introduced here performs a replacement scan before performing the regular binding.

I think this needs to be solved differently.

**Comment by kryonix** [comment]
I see. The test somehow did not fail for me while working on https://github.com/duckdb/duckdb/pull/19116. Now it does, however.

Anyways, given that information, I agree, this has to be solved differently.

**Comment by Mytherin** [comment]
Yes this was a hidden merge conflict between that PR and https://github.com/duckdb/duckdb/pull/19108 - which introduces replacement scans over `.ddb` files. The same error could occur prior to that PR with tables named `parquet` or similar but this did not exist in the test suite.

The changed behavior would also cause issues with the Python client as that would cause replacement scans over Python objects / DataFrames to be prioritized over existing tables (which is the opposite of the current behavior).

**Comment by kryonix** [comment]
Maybe we can do it like this. Essentially, the `bind_basetableref` code failed too early, when there was a problem with (circular) CTEs. Moving this error message (which really is just there to provide a better user facing hint)—at least locally—should solve the issues.

File: src/planner/binder/tableref/bind_basetableref.cpp [hunk 1]
```diff
@@ -244,8 +233,25 @@ unique_ptr<BoundTableRef> Binder::Bind(BaseTableRef &ref) {
 		// could not find an alternative: bind again to get the error
 		// note: this will always throw when using DuckDB as a catalog, but a second look-up might succeed
 		// in catalogs that do not have transactional DDL
-		table_or_view =
-		    entry_retriever.GetEntry(ref.catalog_name, ref.schema_name, table_lookup, OnEntryNotFound::THROW_EXCEPTION);
+		try {
+			table_or_view = entry_retriever.GetEntry(ref.catalog_name, ref.schema_name, table_lookup,
```
Comment (Mytherin) [inline src/planner/binder/tableref/bind_basetableref.cpp]: Running this just to catch the throw seems unnecessary - this function is called specifically to throw so it will always throw - can we move the `if` prior to running this instead?

**Comment by Mytherin** [comment]
> Maybe we can do it like this. Essentially, the `bind_basetableref` code failed too early, when there was a problem with (circular) CTEs. Moving this error message (which really is just there to provide a better user facing hint)—at least locally—should solve the issues.

Thanks! That looks good minus a small improvement

**Comment by Mytherin** [comment]
Maybe we can also add the test from https://github.com/duckdb/duckdb/pull/19154?

File: src/planner/binder/tableref/bind_basetableref.cpp (hunk 1 above)
Comment (kryonix) [reply src/planner/binder/tableref/bind_basetableref.cpp]: Oh, that actually makes a lot of sense 😁 I will change this.

**Comment by Mytherin** [comment]
Thanks!
