### PR TITLE
Maintain BlockHandle of meta blocks by BlockManager

### LINKED ISSUE #5698: MetaBlocks in buffer cannot be reused
### What happens?

For normal data blocks, their `BlockHandle`s are saved by `ColumnSegment`s, which never get freed. For metablocks, their `BlockHandle`s are saved by `MetaBlockReader`s. However, `MetaBlockReader`(as well as its `BlockHandle`) is freed as soon as it is finished being used. For example (`src/storage/table/row_group.cpp` line 37-43):
```
for (idx_t i = 0; i < pointer.data_pointers.size(); i++) {
	auto &block_pointer = pointer.data_pointers[i];
	MetaBlockReader column_data_reader(block_manager, block_pointer.block_id);
	column_data_reader.offset = block_pointer.offset;
	this->columns.push_back(
		ColumnData::Deserialize(block_manager, table_info, i, start, column_data_reader, types[i], nullptr));
}
```
Therefore, for a given MetaBlock `x`, there exists a situation that: 
for(0) -> create `MetaBlockReader` -> create `BlockHandle` -> Load `x` -> free `MetaBlockReader` and `BlockHandle` -> 
for(1) -> create `MetaBlockReader` -> create `BlockHandle` -> Load `x` -> free `MetaBlockReader` and `BlockHandle` -> 
for(2) -> ...
Even if this for loop is reading the same Block, it cannot be reused.

### To Reproduce

To load a TPC-H(SF=100) checkpoint, some meta blocks are continuously and repeatedly read into the buffer for 700+ times.

You can reproduce by adding a `printf` to `BlockHandle::Load` function (`src/storage/buffer_manager.cpp` line 126)
```
if (handle->block_id < MAXIMUM_BLOCK) {
	auto block = AllocateBlock(block_manager, move(reusable_buffer), handle->block_id);
	printf("%lu\n",handle->block_id); // Add this line
	block_manager.Read(*block);
	handle->buffer = move(block);
} else {
```

Then just `./build/release/duckdb [dbfile]`. It's observed that some blocks are continuously and repeatedly read into the buffer for 700+ times. For direct_io=true, this means there are 700+ times of 256KB read from SSD, which could have been avoided. For direct_io=false, there still exists undesired memory copies from OS file buffer to DuckDB buffer.

### OS:

Ubuntu

### DuckDB Version:

latest

### DuckDB Client:

Shell

### Full Name:

Zichun

### Affiliation:

ICT

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Hzc492**
This PR fix #5698 

A map from `block_id` to `shared_ptr<BlockHandle>` can be maintained by `BlockManager`, making the `BlockHandle` of meta blocks not freed even when `MetaBlockReader` is freed.

To recover a TPC-H(SF=100) checkpoint (27GB), the running time of function `SingleFileStorageManager::LoadDatabase`:
| latest master | this PR  |
|  ----  | ----  |
|  5.4s  | **0.47s** |

There is a speedup of more than 10x. (Note that this experiment is performed when direct_io=false. For direct_io=true, there will be a much greater improvement.)

### CODE REVIEW

File: src/storage/buffer_manager.cpp [hunk 1]
```diff
@@ -268,6 +268,12 @@ shared_ptr<BlockHandle> BlockManager::RegisterBlock(block_id_t block_id) {
 	return result;
 }
 
+shared_ptr<BlockHandle> BlockManager::RegisterMetaBlock(block_id_t block_id) {
+	auto handle = RegisterBlock(block_id);
+	meta_blocks[block_id] = handle;
```
Comment (Mytherin) [inline src/storage/buffer_manager.cpp:273]: This cache will always persist - perhaps we should clear it after the metadata is read (by calling `meta_blocks.clear()` after the initial load of a database is completed)?

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Looks great. Nice investigation.

One comment below - otherwise could you just have a look at the failing CI? It looks like a few of the tests run into internal errors after this change.

**Comment by Mytherin** [comment]
Thanks!
