### PR TITLE
[Export Database] Produce up-to-date query for ViewCatalogEntry

### LINKED ISSUE #9367: Export of VIEWs does not respect RENAME
### What happens?

Exporting a view seems to produce original SQL text it was defined with, which doesn't include ALTER VIEW RENAME changes. This is in particular a problem with dbt, since it first creates views with `__dbt_tmp` suffixes and renames as a kind of DDL transaction mechanism.

https://github.com/dbt-labs/dbt-core/blob/efa6339e1804e07f7f47aebccb46492fd897f7f5/core/dbt/include/global_project/macros/adapters/relation.sql#L1-L12

### To Reproduce

```
> duckdb-0.9.1 /tmp/view_name_repro.091.ddb
> duckdb-latest-main /tmp/view_name_repro_latest.ddb
v0.9.2-dev197 a00428dd4a
Enter ".help" for usage hints.
D create view X as (select 'x');
D alter view X rename to Y;
D .maxwidth 10000
D select view_name, sql from duckdb_views() where internal is false;
┌───────────┬───────────────────────────────────┐
│ view_name │                sql                │
│  varchar  │              varchar              │
├───────────┼───────────────────────────────────┤
│ Y         │ create view X as (select 'x');\n; │
└───────────┴───────────────────────────────────┘
  ^
D export database 'view_name_repro_latest_main';

> cat view_name_repro_latest_main/schema.sql
create view X as (select 'x');
            ^ (!!)

```

### OS:

aarch64

### DuckDB Version:

0.9.1

### DuckDB Client:

CLI

### Full Name:

Nicholas Ursa

### Affiliation:

MotherDuck

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #9367 

We regenerate the `sql` when ToSQL() is called, this is different from before in that *all* names are provided as explicit aliases.
This is done because name changes of the referenced table is not reflected in the view anyways, so it's fine to just record the names at the time of creation.

This behavior (not letting changes to the referenced query impact the names of the view) is copied from PostgreSQL

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR! Perhaps it makes sense to, instead of introducing an extra list of aliases (`explicit_aliases`), rework the way `aliases` work so that the generated aliases are only added when the view is actually used instead of stored in the `ViewCatalogEntry`?

File: src/function/table/system/duckdb_columns.cpp [hunk 1]
```diff
@@ -149,20 +150,36 @@ class TableColumnHelper : public ColumnHelper {
 
 class ViewColumnHelper : public ColumnHelper {
 public:
-	explicit ViewColumnHelper(ViewCatalogEntry &entry) : entry(entry) {
+	explicit ViewColumnHelper(ViewCatalogEntry &entry, ClientContext &context) : entry(entry) {
+		auto info = entry.GetInfo();
+		auto binder = Binder::CreateBinder(context);
+		auto &view_info = info->Cast<CreateViewInfo>();
+		binder->BindCreateViewInfo(view_info);
```
Comment (Mytherin) [inline src/function/table/system/duckdb_columns.cpp:157]: `BindCreateViewInfo` can be quite expensive - since it binds a query (which can involve I/O, e.g. if the view contains a reference to a CSV or Parquet file).

Is there any way we can avoid doing that here?

File: src/function/table/system/pragma_table_info.cpp [hunk 2]
```diff
@@ -19,10 +21,42 @@ namespace duckdb {
...
+};
+
+struct ViewEntryFunctionData : public PragmaTableFunctionData {
+	explicit ViewEntryFunctionData(CatalogEntry &entry_p, ClientContext &context) : PragmaTableFunctionData(entry_p) {
+		D_ASSERT(entry.type == CatalogType::VIEW_ENTRY);
+		auto &view_entry = entry.Cast<ViewCatalogEntry>();
+		auto info = view_entry.GetInfo();
+		auto &view_info = info->Cast<CreateViewInfo>();
+		auto binder = Binder::CreateBinder(context);
+		binder->BindCreateViewInfo(view_info);
```
Comment (Mytherin) [inline src/function/table/system/pragma_table_info.cpp:41]: Same here can we avoid the binding?

**Review by Mytherin — COMMENTED** [review]
Thanks for the changes! Looks good - two more comments:

File: src/function/table/system/duckdb_columns.cpp (hunk 1 above)
Comment (Tishj) [reply src/function/table/system/duckdb_columns.cpp:157]: If we only display the columns that were explicitly aliased that could work.
But otherwise there is no way to be sure that the view is up-to-date with the query it's referencing.

But maybe since this is a metadata function that might not matter?
I think in that case it might be better to just not output column data for views here then, instead of faking it

Comment (Mytherin) [reply src/function/table/system/duckdb_columns.cpp:157]: I don't quite follow why the behavior has changed in this PR - wasn't that always the case? Shouldn't returning the `BoundNames` give the same behavior as prior to this PR?

Comment (Tishj) [reply src/function/table/system/duckdb_columns.cpp:157]: What we did previously was save the bound names in the `aliases` vector. Which is also where we store the explicit aliases set by the user when creating the view.

For sql generating purposes we have to distinguish between explicitly set aliases and column names taken from the state of the query at the time of creation.

I added a separate vector for that purpose, but that would break behavior between existing and newly created views, so I've removed that and instead opted for rebinding in places where the full names/types of the view are required.

**Comment by Mytherin** [comment]
Thanks! LGTM
