### PR TITLE
Share null mask with constant null arg vector

### LINKED ISSUE #17217: Wrong inner Join result
### What happens?
Hi, DuckDB Developers!
Please see the below case.  I perform some equivalent join, but I meet some wrong results. 

### To Reproduce

```sql
CREATE TABLE t1(c0 INT);
CREATE TABLE t2(c0 INT);

INSERT INTO t1(c0) VALUES (-18), (NULL);
INSERT INTO t2(c0) VALUES (NULL);

SELECT * FROM t1 INNER JOIN t2 ON TRUE;
-- -18, NULL
-- NULL, NULL


SELECT * FROM t1 INNER JOIN t2 ON ((((t1.c0 NOT BETWEEN t2.c0 AND t2.c0)) IS NULL));
-- NULL, NULL
-- NULL, NULL
-- Wrong result, should be same with the first query
```

### OS:

MacOS

### DuckDB Version:

v1.3.0-dev2743 0069af20ab

### DuckDB Client:

CLI

### Hardware:

_No response_

### Full Name:

TheoristCoder

### Affiliation:

NUS

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [x] Yes, I have

### PR DESCRIPTION
**Pull request by iceTTTT**
Fixes https://github.com/duckdb/duckdb/issues/17217

When the constant_or_null function encounters a constant NULL input, it will set the null mask of result vector for row 0 to invalid.

If the null mask is shared with other function arg vector (due to a previous Combine() call), modifying the null mask for row 0 would incorrectly affect the arg vector. This leads to wrong query result.

Share the null mask with the constant NULL arg vector should fix the issue.

### CODE REVIEW

File: src/function/scalar/generic/constant_or_null.cpp [hunk 1]
```diff
@@ -43,6 +43,9 @@ static void ConstantOrNullFunction(DataChunk &args, ExpressionState &state, Vect
 			if (ConstantVector::IsNull(args.data[idx])) {
 				// input is constant null, return constant null
 				result.Reference(info.value);
+				auto &result_mask = ConstantVector::Validity(result);
```
Comment (Mytherin) [inline src/function/scalar/generic/constant_or_null.cpp:46]: Can we remove the reference altogether, and just set the result to a constant NULL? (i.e. `result.SetVectorType(VectorType::CONSTANT_VECTOR);`)

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Looks good - but perhaps it would be better to remove the reference altogether in this case:

File: src/function/scalar/generic/constant_or_null.cpp (hunk 1 above)
Comment (Mytherin) [reply src/function/scalar/generic/constant_or_null.cpp:46]: The `Initialize` should not also not be necessary anymore now, i.e. we just need the two lines (`SetVectorType` and `ConstantVector::SetNull`).

Comment (iceTTTT) [reply src/function/scalar/generic/constant_or_null.cpp:46]: The constant_or_null function may accept three or more inputs (e.g., **constant(true, c1, c2)**).
In cases where: **c1 is a flat vector**, and **c2 is a constant vector** :
we first access c1 and share its mask with the result through **result_mask.Combine(input_mask)**.

Later, when we access c2 and find it's a constant null.  If we simply call SetNull at this stage, it would corrupt c1's mask (since we're still sharing c1's mask state from the earlier Combine operation).

So we should call Initialize to switch the mask reference to c2's mask (the constant null vector) before calling SetNull.And c2 will not be affected because it's already null.

Comment (Mytherin) [reply src/function/scalar/generic/constant_or_null.cpp:46]: I see - makes sense. Thanks!

**Comment by Mytherin** [comment]
Thanks!
