### PR TITLE
Pushdown Tables Types to CSV Scanner 

### LINKED ISSUE #11740: read_csv ignore_errors does not work as expected
### What happens?

I get an error when reading a faulty csv file. 

### To Reproduce

```sql
CREATE TABLE users ( 
        id INTEGER NOT NULL,  /*primary key*/
        name VARCHAR(10) NOT NULL,  
        email VARCHAR
)  

INSERT INTO users SELECT * FROM read_csv('data.csv', rejects_table='rejects_table', ignore_errors=true, null_padding=true);  
```

data.csv: 

```csv
id,name,email 
1,alice,alice@email.com 
2,eve, 
3r,bob, 
```

error: 
`(duckdb.duckdb.ConversionException) Conversion Error: Could not convert string '3r' to INT32 `

### OS:

x64

### DuckDB Version:

0.10.2 

### DuckDB Client:

Python

### Full Name:

NA

### Affiliation:

NA

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by pdet**
In this PR, I add the capacity to pushdown table types for queries like:
```sql
CREATE TABLE users (
        id INTEGER NOT NULL,  /*primary key*/
        name VARCHAR(10) NOT NULL,
        email VARCHAR
);

INSERT INTO users FROM 'file.csv';
```

This is valuable since we can enforce direct type casting when reading the files, improve error messages (since we get the much nicer cast CSV error messages), and allow `ignore_errors` and `store_rejects` to properly work on cast errors between the CSV file and the table types.

This optimization only happens for direct insert -> projection -> csv_scanner operator chains. 

fix: #11740 and #11153

### CODE REVIEW

File: src/planner/binder/query_node/plan_setop.cpp [hunk 1]
```diff
@@ -23,14 +24,39 @@ unique_ptr<LogicalOperator> Binder::CastLogicalOperatorToTypes(vector<LogicalTyp
 	if (node->type == LogicalOperatorType::LOGICAL_PROJECTION) {
 		// "node" is a projection; we can just do the casts in there
 		D_ASSERT(node->expressions.size() == source_types.size());
+		if (node->children.size() == 1 && node->children[0]->type == LogicalOperatorType::LOGICAL_GET) {
+			// Is this a CSV Scan?
+			auto &logical_get = node->children[0]->Cast<LogicalGet>();
+			// yuck string matching, maybe there is a better way?
+			if (logical_get.function.name == "read_csv" || logical_get.function.name == "read_csv_auto") {
```
Comment (pdet) [inline src/planner/binder/query_node/plan_setop.cpp:31]: @Mytherin is this the best way to figure out which scanner is being used?

Comment (Tishj) [inline src/planner/binder/query_node/plan_setop.cpp:31]: We probably can, by adding something like an optional `table_function_type_pushdown_t` callback to the TableFunction struct, if it's set we can call it, moving most of this logic there

Does that sound reasonable?

File: src/planner/binder/query_node/plan_setop.cpp [hunk 2]
```diff
@@ -23,14 +24,39 @@ unique_ptr<LogicalOperator> Binder::CastLogicalOperatorToTypes(vector<LogicalTyp
...
+				// We loop in the expressions and bail out if there is anything weird (i.e., not a bound column ref)
+				bool can_pushdown_types = true;
+				for (auto &expr : op->expressions) {
+					can_pushdown_types = can_pushdown_types && expr->type == ExpressionType::BOUND_COLUMN_REF;
```
Comment (Mytherin) [inline src/planner/binder/query_node/plan_setop.cpp:35]: We should look at the `BoundColumnRefExpression` here to do the mapping instead of assuming `logical_get.column_ids` are in the same order (although that might even always be the case here for these straightforward queries)

File: src/planner/binder/query_node/plan_setop.cpp (hunk 1 above)
Comment (pdet) [reply src/planner/binder/query_node/plan_setop.cpp:31]: I would say it depends on whether other scanners face the same issues or not; I could see Parquet/Json having sth similar.

Comment (Mytherin) [reply src/planner/binder/query_node/plan_setop.cpp:31]: I agree adding a callback for this is reasonable - this is useful beyond the CSV scanner (JSON and Parquet might also want to implement this).

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! I think this makes sense - some minor comments:

**Comment by Tishj** [comment]
Awesome that you found such a non intrusive way to make this work, this is giving the csv reader another giant boost in user experience!

**Comment by darthf1** [comment]
Cool! Is this something that can work for the parquet reader as well (when I have a parquet file where all columns are varchar), or does that require rebuilding the `ignore_errors` part from the CSV reader into the parquet reader?

File: src/function/table/read_csv.cpp [hunk 3]
```diff
@@ -326,6 +326,25 @@ static unique_ptr<FunctionData> CSVReaderDeserialize(Deserializer &deserializer,
...
 
+bool PushdownTypeToCSVScanner(LogicalGet &logical_get, const vector<LogicalType> &target_types,
+                              const vector<unique_ptr<Expression>> &expressions) {
+	auto &csv_bind = logical_get.bind_data->Cast<ReadCSVData>();
+	// We loop in the expressions and bail out if there is anything weird (i.e., not a bound column ref)
+	vector<LogicalType> pushdown_types = csv_bind.csv_types;
+	for (idx_t i = 0; i < expressions.size(); i++) {
+		if (expressions[i]->type == ExpressionType::BOUND_COLUMN_REF) {
+			auto &col_ref = expressions[i]->Cast<BoundColumnRefExpression>();
+			pushdown_types[logical_get.column_ids[col_ref.binding.column_index]] = target_types[i];
```
Comment (Mytherin) [inline src/function/table/read_csv.cpp:337]: I think we should have this logic where we actually call the `pushdown_type` method - all that is relevant for the CSV reader is the bind data and the target types. I suggest the following signature here:

```cpp
typedef void (* table_function_type_pushdown_t)(ClientContext &context, optional_ptr<FunctionData> bind_data, const unordered_map<idx_t, LogicalType> &new_column_types);
```

Then the assumption is that if a `type_pushdown` method is defined, this method can always be applied to override column types in the bind (i.e. it always succeeds). Extraction of the new types per column can be done generically - this way we can also extend it in the future if required.

**Review by Mytherin — COMMENTED** [review]
Thanks! Looks good - one more comment:

File: src/function/table/read_csv.cpp (hunk 3 above)
Comment (pdet) [reply src/function/table/read_csv.cpp:337]: Why are we passing on the client context and not the LogicalGet?

Comment (Mytherin) [reply src/function/table/read_csv.cpp:337]: We should not be passing the `LogicalGet` as that's a higher level abstraction - table functions should keep their state in the bind data and we should manage the `LogicalGet` outside of these calls.

The `ClientContext` is more about future-proofing, since that allows us to access e.g. settings

Comment (pdet) [reply src/function/table/read_csv.cpp:337]: Alright, thanks for the clarification! :-)

Comment (pdet) [reply src/function/table/read_csv.cpp:337]: I guess the unordered_map instead of vector<LogicalType> is also future-proofing?

File: src/function/table/read_csv.cpp [hunk 4]
```diff
@@ -326,6 +326,25 @@ static unique_ptr<FunctionData> CSVReaderDeserialize(Deserializer &deserializer,
 	return std::move(result);
 }
 
+bool PushdownTypeToCSVScanner(LogicalGet &logical_get, const vector<LogicalType> &target_types,
+                              const vector<unique_ptr<Expression>> &expressions) {
+	auto &csv_bind = logical_get.bind_data->Cast<ReadCSVData>();
+	// We loop in the expressions and bail out if there is anything weird (i.e., not a bound column ref)
+	vector<LogicalType> pushdown_types = csv_bind.csv_types;
+	for (idx_t i = 0; i < expressions.size(); i++) {
+		if (expressions[i]->type == ExpressionType::BOUND_COLUMN_REF) {
```
Comment (Mytherin) [inline src/function/table/read_csv.cpp:335]: I think this doesn't handle the case where the same expression is referenced multiple times with different types, e.g.:

###### timestamp.csv
```
ts
2020-01-01 01:02:03
```

````sql
create table timestamps(ts timestamp, dt date);
insert into timestamps select ts,ts from read_csv('timestamp.csv');
from timestamps;
┌─────────────────────┬────────────┐
│         ts          │     dt     │
│      timestamp      │    date    │
├─────────────────────┼────────────┤
│ 2020-01-01 01:02:03 │ 2020-01-01 │
└─────────────────────┴────────────┘
```

Could we add this test?

**Comment by teucer** [comment]
When could we expect this to be merged and released please?

**Comment by pdet** [comment]
> When could we expect this to be merged and released please?

I think the merge is probably soon, the release is only with 0.10.3, currently [scheduled](https://duckdb.org/docs/dev/release_calendar.html) in ~3 weeks

File: src/function/table/read_csv.cpp [hunk 5]
```diff
@@ -326,6 +326,16 @@ static unique_ptr<FunctionData> CSVReaderDeserialize(Deserializer &deserializer,
 	return std::move(result);
 }
 
+vector<LogicalType> PushdownTypeToCSVScanner(ClientContext &context, optional_ptr<FunctionData> bind_data,
```
Comment (Mytherin) [inline src/function/table/read_csv.cpp:329]: Can we remove the return from this callback? There is only one correct return from this function that would not lead to other problems - the original types with the `new_column_types` applied over the columns. Having a return here indicates that the function has a choice in what to return which is not the case.

**Review by Mytherin — COMMENTED** [review]
Thanks for the changes! One more comment

File: src/function/table/read_csv.cpp (hunk 5 above)
Comment (pdet) [reply src/function/table/read_csv.cpp:329]: Fair enough!

**Comment by Mytherin** [comment]
Thanks!
