### PR TITLE
Fix #1690 -- Bug when exporting tables with symbols on its name

### LINKED ISSUE #1690: Import database fails when table's name have '.' or '-'
**What does happen?**
Fails to import a database created via the export command. This happens when the exported table has some symbols in its name (like . or -).

**What should happen?**
Given that DuckDB accepts creating these tables it also should be able to load tables with symbol when using EXPORT + IMPORT.

**To Reproduce**
Steps to reproduce the behavior. Bonus points if those are only SQL queries.
1. `duckdb original_db`
2. CREATE TABLE "a-1"(id int);
3. INSERT INTO "a-1" VALUES (1);
4. EXPORT DATABASE 'exported';
5. .quit
6. `duckdb imported`
7. IMPORT DATABASE 'exported';
```
Error: Parser Error: syntax error at or near "-"
LINE 7: COPY a-1...
```

**Environment (please complete the following information):**
 - OS: macOS Big Sur 11.2.3
 - DuckDB Version: master

**Before submitting**
- [X] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [X] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

### PR DESCRIPTION
**Pull request by Manerone**

### CODE REVIEW

File: src/execution/operator/persistent/physical_export.cpp [hunk 1]
```diff
@@ -46,7 +47,15 @@ static void WriteCopyStatement(FileSystem &fs, stringstream &ss, TableCatalogEnt
 	} else {
 		table_file_path = fs.JoinPath(info.file_path, StringUtil::Format("%s.%s", table->name, function.extension));
 	}
-	ss << table->name << " FROM '" << table_file_path << "' (";
+
+	if(KeywordHelper::RequiresQuotes(table->name)){
+		ss << '"'  << table->name << '"' ;
```
Comment (Mytherin) [inline src/execution/operator/persistent/physical_export.cpp:52]: Perhaps use `KeywordHelper::WriteOptionallyQuoted`? That would simplify this a bit.

File: test/sql/export/export_database.test [hunk 2]
```diff
@@ -19,9 +19,16 @@ INSERT INTO integers VALUES (1, 3), (4, 2), (NULL, 1)
...
+statement ok
+CREATE TABLE "table.with-symbols"(i INTEGER)
+
+statement ok
+INSERT INTO "table.with-symbols" VALUES (1), (4), (NULL)
+
 statement ok
 CREATE VIEW v1 AS SELECT * FROM integers WHERE i>3; --
 CREATE VIEW v2 AS SELECT * FROM integers WHERE i < 3;
+CREATE VIEW "view.with-symbols" AS SELECT * FROM "table.with-symbols" WHERE i < 3;
```
Comment (Mytherin) [inline test/sql/export/export_database.test:31]: Could you also test a table/view that has dots and quotes in it (see e.g. test/sql/catalog/test_quoted_column_name.test)?

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Looks great. Some comments:

Also might want to run `make format-fix` to fix the formatting :)

**Comment by Manerone** [comment]
I will look into the failing checks tomorrow :)

**Comment by Mytherin** [comment]
It looks like the Windows failure is related to the `table_file_path` that is being created for the COPY INTO files (apparently Windows does not like names with a `.` in them). Perhaps you could replace the `.` in the generated file name with `__dot__`?

**Comment by Manerone** [comment]
Indeed, from the MS page (https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file) there are a set of characters that are not allowed as file or folder name. I will just replace then by __{NAME}__. I guess this should only be done on the windows side.

**Comment by Mytherin** [comment]
Perhaps rather than dealing with that we should name the files `1.csv`, `2.csv`, etc. That way we avoid any potential problems and conflicts arising from that as well.

File: src/include/duckdb/execution/operator/persistent/physical_export.hpp [hunk 3]
```diff
@@ -19,15 +19,17 @@ namespace duckdb {
 class PhysicalExport : public PhysicalOperator {
 public:
 	PhysicalExport(vector<LogicalType> types, CopyFunction function, unique_ptr<CopyInfo> info,
-	               idx_t estimated_cardinality)
+	               idx_t estimated_cardinality, vector<CopyInfo> tables_info)
 	    : PhysicalOperator(PhysicalOperatorType::EXPORT, move(types), estimated_cardinality),
-	      function(std::move(function)), info(move(info)) {
+	      function(std::move(function)), info(move(info)), tables_info(tables_info) {
```
Comment (Mytherin) [inline src/include/duckdb/execution/operator/persistent/physical_export.hpp:24]: move(tables_info)

File: src/include/duckdb/planner/operator/logical_export.hpp [hunk 4]
```diff
@@ -16,11 +16,12 @@ namespace duckdb {
 
 class LogicalExport : public LogicalOperator {
 public:
-	LogicalExport(CopyFunction function, unique_ptr<CopyInfo> copy_info)
-	    : LogicalOperator(LogicalOperatorType::LOGICAL_EXPORT), function(function), copy_info(move(copy_info)) {
+	LogicalExport(CopyFunction function, unique_ptr<CopyInfo> copy_info, vector<CopyInfo> tables_info)
+	    : LogicalOperator(LogicalOperatorType::LOGICAL_EXPORT), function(function), copy_info(move(copy_info)), tables_info(tables_info) {
```
Comment (Mytherin) [inline src/include/duckdb/planner/operator/logical_export.hpp]: move(tables_info)

File: src/planner/binder/statement/bind_export.cpp [hunk 5]
```diff
@@ -13,6 +13,31 @@
 
 namespace duckdb {
 
+//! Sanitizes a string to have only low case chars and underscores
+string sanitize(const string& str){
```
Comment (Mytherin) [inline src/planner/binder/statement/bind_export.cpp]: SanitizeExportIdentifier

File: src/execution/operator/persistent/physical_export.cpp [hunk 6]
```diff
@@ -36,17 +37,12 @@ static void WriteValueAsSQL(stringstream &ss, Value &val) {
...
-	if (table->schema->name != DEFAULT_SCHEMA) {
-		table_file_path = fs.JoinPath(
-		    info.file_path, StringUtil::Format("%s.%s.%s", table->schema->name, table->name, function.extension));
-		ss << table->schema->name << ".";
-	} else {
-		table_file_path = fs.JoinPath(info.file_path, StringUtil::Format("%s.%s", table->name, function.extension));
-	}
-	ss << table->name << " FROM '" << table_file_path << "' (";
+
+	ss << KeywordHelper::WriteOptionallyQuoted(exported_table.table_name) << " FROM '" << exported_table.file_path
```
Comment (Mytherin) [inline src/execution/operator/persistent/physical_export.cpp:43]: I think the table will also need the schema here. Could you add a test case with export in which the table resides in a different schema?

File: src/planner/binder/statement/bind_export.cpp [hunk 7]
```diff
@@ -8,11 +8,36 @@
...
 
 namespace duckdb {
 
+//! Sanitizes a string to have only low case chars and underscores
+string SanitizeExportIdentifier(const string &str) {
+	// Copy the original string to result
+	string result(str);
+
+	for (idx_t i = 0; i < str.length(); ++i) {
+		auto c = str.at(i);
```
Comment (Mytherin) [inline src/planner/binder/statement/bind_export.cpp:23]: `str.at(i)` introduces bounds checks on every access, since we are only accessing until str.length() we know the bounds cannot be exceeded, so you can just use `str[i]`

File: src/planner/binder/statement/bind_export.cpp [hunk 8]
```diff
@@ -8,11 +8,36 @@
...
+		if (c >= 'a' && c <= 'z') {
+			// If it is lower case just continue
+			continue;
+		}
+
+		if (c >= 'A' && c <= 'Z') {
+			// To lowercase
+			result.at(i) = tolower(c);
```
Comment (Mytherin) [inline src/planner/binder/statement/bind_export.cpp:31]: Same here, you can use `result[i]`

File: src/execution/operator/persistent/physical_export.cpp [hunk 9]
```diff
@@ -118,8 +114,10 @@ void PhysicalExport::GetChunkInternal(ExecutionContext &context, DataChunk &chun
 	// write the load.sql file
 	// for every table, we write COPY INTO statement with the specified options
 	stringstream load_ss;
+	idx_t i = 0;
 	for (auto &table : tables) {
-		WriteCopyStatement(fs, load_ss, (TableCatalogEntry *)table, *info, function);
+		WriteCopyStatement(fs, load_ss, (TableCatalogEntry *)table, *info, exported_tables.at(i), function);
```
Comment (Mytherin) [inline src/execution/operator/persistent/physical_export.cpp:119]: The exported_tables seems to rely on the tables scan to output the tables in the same order every time. While that is true currently, that assumption might get violated in the future. What might be better is something along the lines of e.g.

```cpp
struct BoundExportData : public ParseInfo {
    unordered_map<TableCatalogEntry *, ExportedTableData> data;
};
```

Then you have a direct map of table entry -> export data, and you can check that all of the tables are present.

File: src/include/duckdb/parser/parsed_data/exported_table_data.hpp [hunk 10]
```diff
@@ -0,0 +1,35 @@
...
+//===----------------------------------------------------------------------===//
+
+#pragma once
+
+#include "duckdb/parser/parsed_data/parse_info.hpp"
+#include "duckdb/common/types/value.hpp"
+
+namespace duckdb {
+
+struct ExportedTableData : public ParseInfo {
```
Comment (Mytherin) [inline src/include/duckdb/parser/parsed_data/exported_table_data.hpp:16]: As stated above, I recommend having just a single node (`BoundExportData`) that holds the bind data for all the tables. The BoundExportTable can then inherit from ParseInfo, but the data for each of the individual tables does not need to (i.e. this can just be a regular struct with two string members).

**Review by Mytherin — COMMENTED** [review]
Thanks for the updates! Looks great. Some more minor comments, and then I think it's ready to be merged.

File: src/execution/operator/persistent/physical_export.cpp (hunk 9 above)
Comment (Manerone) [reply src/execution/operator/persistent/physical_export.cpp:119]: Just to be sure I understand, if we gather table info on the bind_export.cpp then we don't need to re-gather the same table info on the physical_export.cpp. Is that correct?

physical_export.cpp:90
```C++
schema->Scan(context.client, CatalogType::TABLE_ENTRY, [&](CatalogEntry *entry) {
	if (entry->type == CatalogType::TABLE_ENTRY) {
		tables.push_back(entry);
	} else {
		views.push_back(entry);
	}
})
```

Comment (Mytherin) [reply src/execution/operator/persistent/physical_export.cpp:119]: Yes, indeed. The export lives in a transaction, and a client can only run one query at a time, so necessarily the set of tables visible to a client cannot change in the middle of a query.

File: src/execution/operator/persistent/physical_export.cpp (hunk 6 above)
Comment (Manerone) [reply src/execution/operator/persistent/physical_export.cpp:43]: It should be taken care already on the bind_export.cpp line 82, this way we avoid having this same `if else` clause at the physical_export.cpp.
```C++
// set up the file name for the COPY TO
if (table->schema->name == DEFAULT_SCHEMA) {
	info->file_path =
			  fs.JoinPath(stmt.info->file_path,
			              StringUtil::Format("%s_%s.%s", to_string(id), SanitizeExportIdentifier(table->name),
			                                 copy_function->function.extension));
} else {
	info->file_path = fs.JoinPath(
			  stmt.info->file_path,
			  StringUtil::Format("%s_%s_%s.%s", SanitizeExportIdentifier(table->schema->name), to_string(id),
			                     SanitizeExportIdentifier(table->name), copy_function->function.extension));
}
```

In any case, I will add the tests because my reasoning might be wrong :)

Comment (Manerone) [reply src/execution/operator/persistent/physical_export.cpp:43]: My reasoning was wrong

**Comment by Mytherin** [comment]
Thanks! Looks great now. One final request, could you add two tables that have a different name but the same lowercase name (e.g. "table" and "TABLE") to the test?

**Comment by Mytherin** [comment]
Thanks! Looks great. Will merge after the tests pass.
