### PR TITLE
[Relation] Add support for creating an empty `ValueRelation`

### LINKED ISSUE #7700: [Python] `show tables` returns `None` type on empty result
### What happens?

In the R interface of DuckDB, if I issue `show tables` and do not have any tables, the result will be a `data.frame` object with zero rows:
```r
library(DBI)
library(duckdb)
conn = dbConnect(duckdb::duckdb(), dbdir=":memory:", read_only=FALSE)
dbGetQuery(conn, "show tables")
```
```
[1] name
<0 rows> (or 0-length row.names)
```

But in the Python interface, the same query return a python `None` when there aren't any tables, or a duckdb result object when there is at least one. Would be better if the result was still a table with zero rows when there aren't any tables returned by the query.

### To Reproduce

```python
import duckdb
out = duckdb.query("show tables")
out.__class__
```
```
NoneType
```

### OS:

Linux

### DuckDB Version:

0.8.1.dev96

### DuckDB Client:

Python

### Full Name:

David Cortes

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #7700

The query is not a select statement, so we use a ValueRelation to store the result of it.
But the query doesn't produce any tuples, and we didn't support creating an empty ValueRelation, so we returned None instead.

This PR adds support for creating an empty ValueRelation, so we can return that here instead of None.

### CODE REVIEW

File: src/main/connection.cpp [hunk 1]
```diff
@@ -218,6 +218,10 @@ shared_ptr<Relation> Connection::Values(const string &values, const vector<strin
 	return make_shared<ValueRelation>(context, values, column_names, alias);
 }
 
+shared_ptr<Relation> Connection::EmptyValues(vector<LogicalType> types, vector<string> names, const string &alias) {
+	return make_shared<ValueRelation>(context, types, names, alias);
```
Comment (Mytherin) [inline src/main/connection.cpp:222]: Is this helper method necessary? It seems to not be used outside of a C++ test.

Comment (Tishj) [reply src/main/connection.cpp]: I'm removing this entire approach, now it's just:
```c++
unique_ptr<DuckDBPyRelation> DuckDBPyRelation::EmptyResult(const std::shared_ptr<ClientContext> &context,
                                                           const vector<LogicalType> &types, vector<string> names) {
	vector<Value> dummy_values;
	D_ASSERT(types.size() == names.size());
	dummy_values.reserve(types.size());
	D_ASSERT(!types.empty());
	for (auto &type : types) {
		dummy_values.emplace_back(type);
	}
	vector<vector<Value>> single_row(1, std::move(dummy_values));
	auto values_relation =
	    make_uniq<DuckDBPyRelation>(make_shared<ValueRelation>(context, single_row, std::move(names)));
	// Add a filter on an impossible condition
	return values_relation->Filter("true = false");
}
```

**Comment by Mytherin** [comment]
Thanks! LGTM
