### PR TITLE
httpfs: Encode url path on request

### LINKED ISSUE #5502: AWS S3 keys containing special characters return 404 error
### What happens?

When trying to query parquet files in AWS S3 bucket with HTTPFS extension I get an error (404 Not Found) for files that contain special characters like `+`,`:`.

According to docs these characters are allowed but may need special handling: https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html

### To Reproduce

See example queries (files are in region eu-central-1):
doesn't work:
```sql
select * from parquet_scan('s3://tt-osm-changesets/replication/dag_run_date=2022-11-26/2022-11-26T13:51:14.934709+00:00.parquet');
```
glob resolves the names correctly it's just the request to file that fails:
```sql
select * from parquet_scan('s3://tt-osm-changesets/replication/*/*.parquet');
```
works:
```sql
select * from parquet_scan('s3://tt-osm-changesets/replication/dag_run_date=2022-11-26/20221126145858.parquet');
```

### OS:

Linux

### DuckDB Version:

v0.6.0 2213f9c946

### DuckDB Client:

CLI, DBeaver

### Full Name:

Tomasz Taraś

### Affiliation:

DXC

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by satotake**
Fix #5502

For S3, Some characters request params as well as path need to be encoded.
There is another option that cli users do it by themselves.
But, since python's `boto3` encodes url path before requesting, it will be good that duckdb cli does on behalf of the user.
(This means that `boto3` users cannot percent-encoding style path.)

### CODE REVIEW

**Comment by Mause** [comment]
Can you please add a test?

File: extension/httpfs/s3fs.cpp [hunk 1]
```diff
@@ -714,6 +714,16 @@ void S3FileSystem::Verify() {
 		throw std::runtime_error("test fail");
 	}
 
+	// bug #5502
```
Comment (satotake) [inline extension/httpfs/s3fs.cpp:717]: added to `S3FileSystem::Verify`. Is this what you expected?

**Comment by Mytherin** [comment]
@samansmink could you have a look at this when you have time?

**Comment by samansmink** [comment]
@Mytherin Looks good to me!
