### PR TITLE
Fix copy parquet from table with nullable columns

### LINKED ISSUE #22144: COPY to Parquet not preserving nullability
### What happens?

I believe there is a problem preserving the nullability of columns when writing to Parquet files. I've reproduced this with `1.5.2` on both macOS and windows. I'm aware that there have been problems in the past with COPY to Parquet not working when there were intervening SELECT statements, but as you can see from the example below, just a straight COPY to Parquet is failing.

### To Reproduce

```
λ duckdb
DuckDB v1.5.2 (Variegata)
Enter ".help" for usage hints.
memory D CREATE TABLE test_nullability (id INTEGER NOT NULL, name VARCHAR);
memory D INSERT INTO test_nullability VALUES (1, 'a'), (2, 'b');
```

After this, the schema looks correct:

```
memory D PRAGMA table_info('test_nullability');
┌───────┬─────────┬─────────┬─────────┬────────────┬─────────┐
│  cid  │  name   │  type   │ notnull │ dflt_value │   pk    │
│ int32 │ varchar │ varchar │ boolean │  varchar   │ boolean │
├───────┼─────────┼─────────┼─────────┼────────────┼─────────┤
│     0 │ id      │ INTEGER │ true    │ NULL       │ false   │
│     1 │ name    │ VARCHAR │ false   │ NULL       │ false   │
└───────┴─────────┴─────────┴─────────┴────────────┴─────────┘
```

Now copy to Parquet and check the *Parquet* schema:

```
memory D COPY test_nullability to 'test.parquet' (FORMAT PARQUET);
memory D  SELECT name, repetition_type FROM parquet_schema('test.parquet');
┌───────────────┬─────────────────┐
│     name      │ repetition_type │
│    varchar    │     varchar     │
├───────────────┼─────────────────┤
│ duckdb_schema │ REQUIRED        │
│ id            │ OPTIONAL        │
│ name          │ OPTIONAL        │
└───────────────┴─────────────────┘
```

My expectation would be that:
- id is REQUIRED
- name is OPTIONAL

### OS:

macOS, windows

### DuckDB Version:

1.5.2

### DuckDB Client:

duckdb

### Hardware:

_No response_

### Full Name:

Steve Rinn

### Affiliation:

Posting this from personal account, but working on behalf of Marsh McClennan

### Did you include all relevant configuration (e.g., CPU architecture, Linux distribution) to reproduce the issue?

- [x] Yes, I have

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant data sets for reproducing the issue?

Yes

### PR DESCRIPTION
**Pull request by dentiny**
Closes https://github.com/duckdb/duckdb/issues/22144

The issue is
- `CreateWriterRecursive` has `can_have_nulls=true` [as default](https://github.com/duckdb/duckdb/blob/2076dd79b5da1a11405fb2b5d2ed27471c791279/extension/parquet/include/column_writer.hpp#L183), meaning every column is written as OPTION in the parquet schema 
- The only caller `ParquetWriter` doesn't assign column nullability on column writer creation https://github.com/duckdb/duckdb/blob/2076dd79b5da1a11405fb2b5d2ed27471c791279/extension/parquet/parquet_writer.cpp#L497-L499

Now the problem becomes clear: when copying from table, column nullability is not passed down to copy function and parquet writer.

### CODE REVIEW

**Review by Mytherin — COMMENTED** [review]
Thanks - maybe a more generic solution is to determine this from the statistics instead? 

Let's also try to keep these specific settings out of generic structs (like `CopyFunctionBindInput`).

**Comment by dentiny** [comment]
> maybe a more generic solution is to determine this from the statistics instead?
Let's also try to keep these specific settings out of generic structs (like CopyFunctionBindInput).

These are two change requests:
- First, checking table stats might not work here, since stats only reflect table's current stats, but not table schema
- Second, I moved all table schema check logic from copy to parquet extension to limit the change scope of the PR

File: extension/parquet/parquet_extension.cpp [hunk 1]
```diff
@@ -343,6 +347,36 @@ static unique_ptr<FunctionData> ParquetWriteBind(ClientContext &context, CopyFun
 
 	bind_data->sql_types = sql_types;
 	bind_data->column_names = names;
+
+	// Determine non-nullable columns from table constraints (if copying from a table)
+	auto &copy_info = input.info;
+	if (!copy_info.table.empty()) {
+		auto entry =
```
Comment (Mytherin) [inline extension/parquet/parquet_extension.cpp]: This won't work in many cases, e.g. this works:

```sql
COPY tbl TO 'file.parquet';
```

But this does not:

```sql
COPY (FROM tbl) TO 'file.parquet';
```

I think it would be much nicer if we could inform this through pushing stats, e.g. in the `StatisticsPropagator` we could add a new overload for `LogicalCopyToFile` which could invoke a callback in the `CopyFunction`. The Parquet copy could then use this callback to look at the stats for each of the columns.

File: src/include/duckdb/function/copy_function.hpp [hunk 2]
```diff
@@ -167,6 +168,9 @@ typedef vector<unique_ptr<Expression>> (*copy_to_select_t)(CopyToSelectInput &in
 
 typedef void (*copy_to_initialize_operator_t)(GlobalFunctionData &gstate, const PhysicalOperator &op);
 
+typedef void (*copy_to_propagate_statistics_t)(ClientContext &context, FunctionData &bind_data,
+                                               const vector<BaseStatistics *> &column_stats);
```
Comment (Mytherin) [inline src/include/duckdb/function/copy_function.hpp]: Let's use a struct for the input arguments - `CopyFromPropagateStatsInput`  - similar to what we do elsewhere.

File: src/optimizer/statistics_propagator.cpp [hunk 3]
```diff
@@ -94,6 +98,24 @@ unique_ptr<NodeStatistics> StatisticsPropagator::PropagateStatistics(unique_ptr<
...
 }
 
+unique_ptr<NodeStatistics> StatisticsPropagator::PropagateStatistics(LogicalCopyToFile &op,
+                                                                     unique_ptr<LogicalOperator> &node_ptr) {
+	auto stats = PropagateChildren(op, node_ptr);
+	if (!op.function.copy_to_propagate_statistics || !op.bind_data || op.children.empty()) {
+		return stats;
+	}
+	auto bindings = op.children[0]->GetColumnBindings();
+	vector<BaseStatistics *> column_stats(bindings.size(), nullptr);
```
Comment (Mytherin) [inline src/optimizer/statistics_propagator.cpp]: Let's avoid using raw pointers - `vector<optional_ptr<BaseStatistics>>`

**Review by Mytherin — COMMENTED** [review]
Thanks for the update! Looks good - some minor comments then this is good to go

**Comment by dentiny** [comment]
```sh
Installing 41/41 roaring:wasm32-emscripten@4.5.0...
Building roaring:wasm32-emscripten@4.5.0...
...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed:
    ... cmake ...
```
doesn't seem to be my issue

**Comment by Mytherin** [comment]
Thanks - the changeset looks good to me now. Could you just rebase this to `main` given this is a feature?

**Comment by dentiny** [comment]
> Could you just rebase this to main given this is a feature?

Hmmm sure -- I thought it's a bug fix

**Comment by Mytherin** [comment]
We never wrote `REQUIRED` columns (and it's not required by the Parquet spec to do so either). This is a new feature that changes the behavior of our Parquet writer, which always carries risks with it (e.g. other systems might not be able to read this new format) so it's not appropriate for a bug fix release imo.

**Comment by dentiny** [comment]
> 1. /duckdb_build_dir/build/release/_deps/avro_extension_fc-src/test/sql/copy/invalid_option.test:3
================================================================================
Query failed, but error message did not match expected error message: Invalid Configuration Error: The following option(s) are not recognized: key: 'NOT_RECOGNIZED' (/duckdb_build_dir/build/release/_deps/avro_extension_fc-src/test/sql/copy/invalid_option.test:3)!
================================================================================
COPY (
	select 42 a
) TO 'duckdb_unittest_tempdir/7/test2.avro' (
	NOT_RECOGNIZED,
	ROOT_NAME 'test'
);
================================================================================
Actual result:
================================================================================
Invalid Configuration Error: The following option(s) are not recognized: key: 'not_recognized'
[12/485] (2%): /duckdb_build_dir/build/release/_deps/avro_extension_fc-src/test/sql/copy/invalid_option.test
unittest is a Catch v2.13.7 host application.
Run with -? for options

The failed CI test doesn't seem related to my change.

**Comment by Mytherin** [comment]
Agreed - thanks for the fixes!
