### PR TITLE
Fix #1785: correctly copy constraints in ADD COLUMN of alter table

### LINKED ISSUE #1785: Python | ALTER TABLE causes constraints lost in database file after exiting
**What does happen?**
In python, when I alter a table (I am adding columns to the table) the PRIMARY KEY constraint in the existing columns are lost, causing duplicated values when I insert new rows. The cli-tools, on the contrary, works correctly.

**What should happen?**
The constraints remains

**To Reproduce**
Steps to reproduce the behavior. Bonus points if those are only SQL queries.
1. Create a table ```db.execute('CREATE TABLE IF NOT EXISTS a(id INT PRIMARY KEY)')```
2. Insert a value ```db.execute('INSERT INTO a(id) VALUES (1)')```
    | id |
    | :-: |
    | 1  |
3. Add a new column ```db.execute('ALTER TABLE a ADD COLUMN c REAL')```
4. Insert the value above again ```db.execute('INSERT INTO a(id) VALUES (1)')```
5. Now there are two rows with id=1
    | id |  c   |
    | :-: |  :-:  |
    | 1  |   -  |
    | 1  |   -  |

**Environment (please complete the following information):**
 - OS: Windows 10 with Python 3.9.5
 - DuckDB Version 0.2.6

### PR DESCRIPTION
**Pull request by Mytherin**
Fixes #1785

### CODE REVIEW

**Review by hawkfish — APPROVED** [review]

File: src/catalog/catalog_entry/table_catalog_entry.cpp [hunk 1]
```diff
@@ -242,6 +242,10 @@ unique_ptr<CatalogEntry> TableCatalogEntry::AddColumn(ClientContext &context, Ad
 	for (idx_t i = 0; i < columns.size(); i++) {
 		create_info->columns.push_back(columns[i].Copy());
 	}
+	for (idx_t constr_idx = 0; constr_idx < constraints.size(); constr_idx++) {
+		auto &constraint = constraints[constr_idx];
+		create_info->constraints.push_back(constraint->Copy());
+	}
```
Comment (pdet) [inline src/catalog/catalog_entry/table_catalog_entry.cpp:248]: this can be a c++11 loop, no?

Comment (Mytherin) [reply src/catalog/catalog_entry/table_catalog_entry.cpp]: It can indeed

**Comment by Mytherin** [comment]
Test failures are unrelated to the PR
