### PR TITLE
[Arrow] Properly use the parent's `array.offset` in many places in the scan

### LINKED ISSUE #5547: Incorrect nested data converted in Arrow <-> DuckDB conversion when read through Arrow DataSet (Python)
### What happens?

I have a parquet file with a nested struct column. When querying this file and extracting the struct column, it appears to return the wrong data. It has done this when using a Arrow Dataset / Table as inputs.

I have uploaded the specific file in question down below. The nested aspect might be a coincidence - I have no idea what's going wrong.

### To Reproduce

Dataset (zipped parquet file - could not upload parquet alone):
[obfuscated.zip](https://github.com/duckdb/duckdb/files/10118562/obfuscated.zip)

## Environment
```
Package         Version
--------------- ------------
duckdb          0.6.1.dev191
numpy           1.24.0rc1
pandas          1.5.2
pip             22.3.1
pyarrow         10.0.1
python-dateutil 2.8.2
pytz            2022.6
setuptools      65.5.1
six             1.16.0
wheel           0.37.1
```

## Python code
```python
import pyarrow.dataset as ds
import duckdb

data = ds.dataset("~/obfuscated.parquet")

con = duckdb.connect()

display("Select then filter")
display(con.execute("""
SELECT
    col1,
    col2,
    col3,
    col4,
    col5,
    nested_col.*,
FROM data
ORDER BY ALL
""").df().loc[lambda df: (df.col1 == 749) & (df.col2 == 747) & (df.col3 == 5) & (df.col4 == 1)])

display("Filter then select")
display(con.execute("""
SELECT
    col1,
    col2,
    col3,
    col4,
    col5,
    nested_col.*,
FROM data
WHERE col1 = 749
    AND col2 = 747
    AND col3 = 5
    AND col4 = 1
ORDER BY ALL
""").df())

con.close()
```

## Output
image

The expected output is the second one above. This issue only shows with Arrow Dataset/Table inputs. The issue doesn't show when using a pandas DataFrame as inputs.

### OS:

Linux x64

### DuckDB Version:

duckdb-0.6.1.dev191

### DuckDB Client:

Python

### Full Name:

Edward Davis

### Affiliation:

Veitch Lister Consulting

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #5547 

It seems like the arrow arrays hit a certain chunk size limit, and are split up over multiple arrays while sharing the same buffer.
These offsets are put onto the struct array and should be forwarded to the child arrays, we did not do this previously.
(Or at least not consistently)

### CODE REVIEW

**Review by Mytherin — APPROVED** [review]
Thanks! Looks great. Could you just look at the failing CI?

**Comment by Tishj** [comment]
> Thanks! Looks great. Could you just look at the failing CI?

Weirdly that's one of the tests I added, seems I didn't run it - and it was broken
I've fixed the test and added tests for nulls

Discovered another bug concerning dictionaries, structs and nulls - will likely fix this in a separate PR

File: src/function/table/arrow_conversion.cpp [hunk 1]
```diff
@@ -18,24 +18,34 @@ static void ShiftRight(unsigned char *ar, int size, int shift) {
...
+		// The parent of this array is a list
+		// We just ignore the parent offset, it's already applied to the list
+		return array.offset + nested_offset;
+	}
+	// Parent offset is set in the case of a struct, it applies to all child arrays
+	// 'chunk_offset' is how much of the chunk we've already scanned, in case the chunk size exceeds
+	// STANDARD_VECTOR_SIZE
+	return array.offset + parent_offset + state.chunk_offset;
+}
+
```
Comment (pdet) [inline src/function/table/arrow_conversion.cpp:33]: Should we have an offset struct that holds all the offset information and have this method in?
Then we can localize this offset logic and not pass two values all over.

Comment (Tishj) [reply src/function/table/arrow_conversion.cpp:33]: We would still be populating this on the fly, the nested offset/parent offset is provided by the parent array.

I was thinking of writing this offset into the `ArrowArrayScanState` every time we scan a new chunk, so we don't repeat this logic everywhere, but the only thing we can get rid of that way is the parent_offset/nested offset if/else.

We would still need to keep the context of what type of offset this is though, because the `state.chunk_offset` would still need to be applied for every scanned Vector.

**Comment by Tishj** [comment]
Had this weird CI failure locally:
```
          for path in extension_paths_found:
              print(path)
              if path.endswith(extension_name + ".duckdb_extension"):
                  conn = duckdb.connect(db_name, config={'allow_unsigned_extensions': 'true'})
  >               conn.execute(f"LOAD '{path}'")
  E               duckdb.duckdb.InvalidInputException: Invalid Input Error: Extension "/project/httpfs/httpfs.duckdb_extension" version (v..1-dev) does not match DuckDB version (v0.0.0)
```

Probably caused by this being the version of the installed package:

```
      + pip install /tmp/cibuildwheel/repaired_wheel/duckdb-0.1.dev34218-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  Processing /tmp/cibuildwheel/repaired_wheel/duckdb-0.1.dev34218-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  Installing collected packages: duckdb
  Successfully installed duckdb-0.1.dev34218
```

**Comment by Mytherin** [comment]
Thanks!
