### PR TITLE
ODBC Small Issues fix  #7918 #7890 #7653

### LINKED ISSUE #7918: ODBC: Crash calling SQLSetStmtAttr(SQL_ATTR_ROW_BIND_TYPE)
### What happens?

We're seeing a SEGV trying to call SQLSetStmtAttr(SQL_ATTR_ROW_BIND_TYPE, <non-zero size>) in the DuckDB ODBC driver.
I've traced the issue to SQLSetStmtAttr in duckdb-master\tools\odbc\statement.cpp. This line:

`stmt->row_desc->ard->header.sql_desc_bind_type = *(SQLULEN *)value_ptr;`

is trying to dereference the passed-in value_ptr, but for this attribute the value in value_ptr is the actual SQLULEN value, NOT a pointer. This value should be stored as-is instead of being dereferenced.

### To Reproduce

rc = SQLSetStmtAttr(hstmt, SQL_ATTR_ROW_BIND_TYPE, 256, SQL_IS_UINTEGER);

### OS:

RHEL 8.4 x64

### DuckDB Version:

v0.8.0

### DuckDB Client:

ODBC 03.00.0000

### Full Name:

Chris DeHart

### Affiliation:

SAS

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by maiadegraaf**
This PR provides fixes and adds tests for the following issues:
- #7918 
- #7890 
- #7653

As well as some cosmetic changes for readability and some function signatures have been changed to prevent handles from being converted several times.

### CODE REVIEW

File: tools/jdbc/src/main/java/org/duckdb/DuckDBNative.java [hunk 1]
```diff
@@ -83,15 +83,15 @@ public class DuckDBNative {
 
 	protected static native String duckdb_jdbc_get_catalog(ByteBuffer conn_ref);
 
-	// returns stmt_ref result reference object
```
Comment (Mause) [inline tools/jdbc/src/main/java/org/duckdb/DuckDBNative.java:86]: Can you undo the changes to the JDBC source files? Adding the h prefix is just going to cause confusion

Comment (maiadegraaf) [reply tools/jdbc/src/main/java/org/duckdb/DuckDBNative.java:86]: Sure! Sorry, I did that by accident

**Comment by Mytherin** [comment]
Thanks! LGTM
