### PR TITLE
fix(nodejs): http state

### LINKED ISSUE #7748: nodejs: INTERNAL Error: State was not defined in this HTTP File Handle
### What happens?

In the nodejs bindings, when running an `exec` (*not* e.g., an `all`) that uses `parquet_scan('http://...')`, the following exception is raised:

```
undefined:0


[Error: Invalid Error: INTERNAL Error: State was not defined in this HTTP File Handle] {
  errno: -1,
  code: 'DUCKDB_NODEJS_ERROR',
  errorType: 'Invalid'
}

Node.js v20.2.0
```

### To Reproduce

Create a project with the following two files:

`package.json`:
```
{
  "name": "duck-http-bug",
  "version": "1.0.0",
  "main": "index.js",
  "author": "",
  "dependencies": {
    "duckdb": "^0.8.0"
  }
}
```

`index.js`:
```
var duckdb = require('duckdb');
var db = new duckdb.Database(':memory:');
db.exec(`SELECT * FROM parquet_scan('http://localhost:1234/whatever.parquet')`, function(err) {
  if (err) {
    throw err;
  }
  console.log('ok')
});
```

Then run `npm install`, and in a duckdb shell run `INSTALL 'httpfs'` (or run this in an environment with that plugin already installed). Then run `node index.js`. Note that you do *not* need an HTTP server listening on the given address—it is never accessed.

Full disclosure: I have not tested the latest `master` branch, even though I have checked that box below.

### OS:

Mac 13.3.1

### DuckDB Version:

0.8.0

### DuckDB Client:

nodejs

### Full Name:

Carl Jackson

### Affiliation:

Watershed

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Mause**
Fixes https://github.com/duckdb/duckdb/issues/7748

### CODE REVIEW

File: src/main/client_context.cpp [hunk 1]
```diff
@@ -319,6 +319,8 @@ shared_ptr<PreparedStatementData> ClientContext::CreatePreparedStatement(ClientC
 			planner.parameter_data.emplace_back(value);
 		}
 	}
+
+	client_data->http_state = make_uniq<HTTPState>();
```
Comment (carlopi) [inline src/main/client_context.cpp:323]: Looking elsewhere, it seems it should probably be `make_shared<HTTPState>`?

And also I am not sure whether either an assertion or a test on http_state being already NOT initialised would not make sense (but then it's missing also elsewhere, so not really tied to this PR).

**Comment by Mytherin** [comment]
Thanks! LGTM
