### PR TITLE
[Python] Add support for Pandas 2.0.0

### LINKED ISSUE #6954: [Python] Pandas 2.0.0 datetime with timezone consumption issue
### What happens?

Pandas 2.0.0 has changed the way they represent datetime objects with timezone info.
We try to read these as epoch, and that turns into bogus data.

The fix is very easy and I've already added it on a branch, so this issue is just for people that run into it.
We are aware of the issue and it should be fixed soon 👍 

### To Reproduce

```py
import pandas as pd
import duckdb

assert(pd.__version__ == 2.0.0)
pd_df = pd.DataFrame({'a': pd.Series([datetime.strptime('1990-01-01 00:00:00', '%Y-%m-%d %H:%M:%S')]).dt.tz_localize('UTC')})
res = duckdb.sql('select * from pd_df')
```

### OS:

MacOS

### DuckDB Version:

master

### DuckDB Client:

Python

### Full Name:

Thijs Bruineman

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #6954, #6695 

### Reorganizing python package source code
I've reorganized the files and folder structure within the `tools/pythonpkg/src` folder a bit.

### Pybind11 Wrapper
I've decided to no longer use `namespace py = pybind11` and instead create `namespace py` that uses `namespace pybind11`
It should have no effect on existing functionality, but allows us to add to the functionality and override/shadow some of the behavior that we've had to patch around before.
One such example is `py::isinstance`, our import cache keeps the `py::object` `ptr` as nullptr when it could not be imported and it's optional.
When these objects are used with `pybind11`'s `isinstance` method, this will segfault because it does no nullptr check.
In the past we've patched around this by adding a `IsInstance` method to our `PythonImportCacheItem`, but I've adapted `py::isinstance` to just return false if the type object is null, removing the need for this `IsInstance` method.

### Split Numpy logic from Pandas logic
Split some of the Numpy scanning code from Pandas, and introduced a `PandasColumn` class + `PandasColumnBackend` enum to take some steps into supporting multiple backends in the future.

### PyArrow Pandas DataFrames
PyArrow backed dataframes are transformed into `pyarrow.lib.Table` instead and dealt with earlier on.
For now mixed dataframes are converted into Tables too.

### Adapting python tests
I've reworked our python tests to use dependency injection for `pandas` instead of the base module.
I've created two proxies of the pandas module:

- `NumpyPandas`
Regular behavior of `pandas`
- `ArrowPandas`
`pandas.DataFrame` constructor produces a dataframe that has been converted to using pyarrow backed columns.
`pandas.testing.assert_frame_equal` has been intercepted to first convert any pyarrow backed column to numpy backed instead. This is done because we can't produce pyarrow backed dataframes from DuckDB yet, this support should be easier to add when we can produce pyarrow backed dataframes.

Verified that our entire test suite works on `pandas` versions: 2.0.0, 1.5.3, 1.3.3

### CODE REVIEW

File: tools/pythonpkg/src/numpy/numpy_scan.cpp [hunk 1]
```diff
@@ -57,7 +59,9 @@ void ScanPandasCategory(py::array &column, idx_t count, idx_t offset, Vector &ou
 
 template <class T>
 void ScanPandasMasked(PandasColumnBindData &bind_data, idx_t count, idx_t offset, Vector &out) {
```
Comment (Tishj) [inline tools/pythonpkg/src/numpy/numpy_scan.cpp:61]: This should be renamed

File: tools/pythonpkg/src/numpy/type.cpp [hunk 2]
```diff
@@ -10,93 +10,109 @@ static bool IsDateTime(const string &col_type_str) {
...
 		return true;
 	}
 	return false;
 }
 
-PandasType ConvertPandasType(const py::object &col_type) {
+NumpyNullableType ConvertNumpyType(const py::handle &col_type) {
 	auto col_type_str = string(py::str(col_type));
 
+	// pandas.core.dtypes.base.StorageExtensionDtype
```
Comment (Tishj) [inline tools/pythonpkg/src/numpy/type.cpp:31]: Ah, missed this, this should be deleted

File: tools/pythonpkg/src/numpy/type.cpp [hunk 3]
```diff
@@ -10,93 +10,109 @@ static bool IsDateTime(const string &col_type_str) {
...
+		return NumpyNullableType::INT_64;
 	} else if (col_type_str == "float16" || col_type_str == "Float16") {
-		return PandasType::FLOAT_16;
+		return NumpyNullableType::FLOAT_16;
 	} else if (col_type_str == "float32" || col_type_str == "Float32") {
-		return PandasType::FLOAT_32;
-	} else if (col_type_str == "float64" || col_type_str == "Float64") {
-		return PandasType::FLOAT_64;
+		return NumpyNullableType::FLOAT_32;
+	} else if (col_type_str == "float64" || col_type_str == "Float64" || col_type_str == "double") {
```
Comment (Tishj) [inline tools/pythonpkg/src/numpy/type.cpp:60]: This is a type added by `pyarrow` and doesn't exist if the dtype backend is `numpy_nullable`, should probably be deleted for now as well

File: tools/pythonpkg/src/numpy/numpy_scan.cpp [hunk 4]
```diff
@@ -411,92 +388,4 @@ void VectorConversion::NumpyToDuckDB(PandasColumnBindData &bind_data, py::array
 	}
 }
 
-void VectorConversion::BindPandas(const DBConfig &config, py::handle df, vector<PandasColumnBindData> &bind_columns,
```
Comment (Tishj) [inline tools/pythonpkg/src/numpy/numpy_scan.cpp:414]: Sadly git cant recognize this is moved to `src/pandas/bind.cpp`
Going to cause some merge conflicts, so this PR should not be merged before the current PRs that deal with this are merged (such as #6523 )

File: tools/pythonpkg/src/pandas/analyzer.cpp [hunk 5]
```diff
@@ -345,8 +345,9 @@ LogicalType PandasAnalyzer::InnerAnalyze(py::handle column, bool &can_convert, b
 	// Keys are not guaranteed to start at 0 for Series, use the internal __array__ instead
 	auto pandas_module = py::module::import("pandas");
 	auto pandas_series = pandas_module.attr("core").attr("series").attr("Series");
+
 	if (py::isinstance(column, pandas_series)) {
-		column = column.attr("__array__")();
```
Comment (Tishj) [inline tools/pythonpkg/src/pandas/analyzer.cpp:349]: Another change that was made in an attempt to unify the arrow/numpy codepaths here, should probably be removed just to avoid potential unforeseen problems caused by this change

File: tools/pythonpkg/src/pandas/bind.cpp [hunk 6]
```diff
@@ -0,0 +1,144 @@
...
+		auto pandas_array = column.attr("array");
+		bind_data.numpy_col = make_uniq<PandasNumpyColumn>(py::array(column.attr("to_numpy")("float32")));
+		bind_data.numpy_type = NumpyNullableType::FLOAT_32;
+		column_type = NumpyToLogicalType(bind_data.numpy_type);
+	} else {
+		auto pandas_array = column.attr("array");
+		if (py::hasattr(pandas_array, "_data")) {
+			// This means we can access the numpy array directly
+			bind_data.numpy_col = make_uniq<PandasNumpyColumn>(column.attr("array").attr("_data"));
+		} else if (py::hasattr(pandas_array, "asi8")) {
```
Comment (Tishj) [inline tools/pythonpkg/src/pandas/bind.cpp:100]: I believe this was the only change required to fix the timezone consumption issue

File: tools/pythonpkg/src/pyconnection.cpp [hunk 7]
```diff
@@ -88,6 +88,28 @@ bool DuckDBPyConnection::IsJupyter() {
...
+	D_ASSERT(py::isinstance(df, import_cache.pandas().DataFrame()));
+
+	py::list dtypes = df.attr("dtypes");
+	if (dtypes.empty()) {
+		return false;
+	}
+
+	auto arrow_dtype = import_cache.pandas().core.arrays.arrow.dtype.ArrowDtype();
+	for (auto &dtype : dtypes) {
+		if (!py::isinstance(dtype, arrow_dtype)) {
```
Comment (Tishj) [inline tools/pythonpkg/src/pyconnection.cpp:102]: This needs to be fixed, for now we want to treat any dataframe that contains at least a single pyarrow backed column as fully pyarrow backed, so we don't encounter any pyarrow dtypes in the pandas bind/scan code

**Review by Tishj — COMMENTED** [review]
Making some notes about changes (which might be hard to find otherwise through all the include changes)
And finding some changes that should be removed/undone

File: tools/pythonpkg/src/pyconnection.cpp (hunk 7 above)
Comment (Tishj) [reply tools/pythonpkg/src/pyconnection.cpp]: This did work, so I'm not sure if we just don't have tests that produce frankenstein dataframes, or we can consume them somehow.
But it's probably safer to disable this for now

**Comment by Tishj** [comment]
`map` directly converts to/from pandas DataFrames, we should add a check there to see if the dtypes of the columns are pyarrow and throw an explicit error there that we don't support this yet

**Comment by Tishj** [comment]
Also missing: need to unlock the pandas version, so we actually test pandas 2.0.0

**Comment by Tishj** [comment]
Euhm, pandas, are you okay?
```py
  =================================== ERRORS ====================================
  __________ ERROR collecting fast/pandas/test_implicit_pandas_scan.py __________
  D:\a\duckdb\duckdb\tools\pythonpkg\tests\fast\pandas\test_implicit_pandas_scan.py:11: in <module>
      pyarrow_df = numpy_nullable_df.convert_dtypes(dtype_backend="pyarrow")
  ..\venv-test\lib\site-packages\pandas\core\generic.py:6679: in convert_dtypes
      results = [
  ..\venv-test\lib\site-packages\pandas\core\generic.py:6680: in <listcomp>
      col._convert_dtypes(
  ..\venv-test\lib\site-packages\pandas\core\series.py:5524: in _convert_dtypes
      inferred_dtype = convert_dtypes(
  ..\venv-test\lib\site-packages\pandas\core\dtypes\cast.py:1136: in convert_dtypes
      pa_type = to_pyarrow_type(base_dtype)
  ..\venv-test\lib\site-packages\pandas\core\arrays\arrow\array.py:163: in to_pyarrow_type
      if isinstance(dtype, ArrowDtype):
  E   NameError: name 'ArrowDtype' is not defined
```
That's **your** internals, and I have a check if pandas version >= 2.0.0
it recognized `dtype_backend` being 'pyarrow' but then internally it fails because it doesn't have the ArrowDtype type 🙃

File: src/function/table/arrow_conversion.cpp [hunk 8]
```diff
@@ -5,9 +5,19 @@
 #include "duckdb/common/types/arrow_aux_data.hpp"
 #include "duckdb/function/scalar/nested_functions.hpp"
 
+namespace {
```
Comment (pdet) [inline src/function/table/arrow_conversion.cpp:8]: You can just wrap the whole shebang on the `namespace duckdb {` no?

Comment (Tishj) [reply src/function/table/arrow_conversion.cpp:8]: The reason I used an unnamed namespace is that we don't need to pollute the duckdb namespace with this struct, it's only relevant here.
This just makes it static essentially.

**Review by pdet — COMMENTED** [review]
Just have some small comments. In general, I think the logic there seems pretty solid. Excellent work!

I do have some suggestions for further testing. These may be already covered, so ignore them if that's the case.

Could we test Pandas with the Arrow representation on queries with filter and projection pushdown?
Is it possible to create an empty data frame, where only the columns are defined, and try to scan that?
Could we also add tests with Null values? Including completely null columns?
Do we have tests with mixed type columns (i.e., some columns are numpy, others py object (i.e., ints, strings, maps, going nuts on one column) , others arrow)?

File: tools/pythonpkg/src/pandas/scan.cpp [hunk 9]
```diff
@@ -141,6 +146,20 @@ double PandasScanFunction::PandasProgress(ClientContext &context, const Function
...
 }
 
+void PandasScanFunction::PandasBackendScanSwitch(PandasColumnBindData &bind_data, idx_t count, idx_t offset,
+                                                 Vector &out) {
+	auto backend = bind_data.numpy_col->Backend();
+	switch (backend) {
+	case PandasColumnBackend::NUMPY: {
+		NumpyScan::Scan(bind_data, count, offset, out);
+		break;
+	}
```
[the remark this answers is not in the document]
Comment (Tishj) [reply tools/pythonpkg/src/pandas/scan.cpp:156]: I think eventually we may want to do that, because currently we deal with mixed dataframes by converting them to pyarrow, then to duckdb.
We likely want to eventually get rid of the conversion to pyarrow first, as pyarrow -> duckdb isn't entirely zero-copy

**Review by Mytherin — COMMENTED** [review]
LGTM! @pdet can you have another look?

File: tools/pythonpkg/tests/fast/pandas/test_pandas_arrow.py [hunk 10]
```diff
@@ -0,0 +1,129 @@
...
+                [5,4,3],
+                'test',
+                None,
+                {'a': 42}
+            ]),
+            'integers': np.ndarray((4,), buffer=np.array([1,2,3,4,5]), offset=np.int_().itemsize, dtype=int)
+        })
+        pyarrow_df = df.convert_dtypes(dtype_backend='pyarrow')
+        con = duckdb.connect()
+        with pytest.raises(duckdb.InvalidInputException, match='Invalid Input Error: The dataframe could not be converted to a pyarrow.lib.Table, due to the following python exception:'):
```
Comment (pdet) [inline tools/pythonpkg/tests/fast/pandas/test_pandas_arrow.py:42]: Is this an internal error from Pandas? What's the exception?

File: tools/pythonpkg/tests/fast/pandas/test_pandas_arrow.py [hunk 11]
```diff
@@ -0,0 +1,129 @@
+import duckdb
+import pytest
+import datetime
+
+from conftest import pandas_supports_arrow_backend
+pd = pytest.importorskip("pandas", '2.0.0')
+import numpy as np
+
+@pytest.mark.skipif(not pandas_supports_arrow_backend(), reason="pandas does not support the 'pyarrow' backend")
+class TestPandasArrow(object):
```
Comment (pdet) [inline tools/pythonpkg/tests/fast/pandas/test_pandas_arrow.py:10]: Is it possible to create a pandas dataframe with arrow, numpy and object columns?

**Review by pdet — COMMENTED** [review]
Thijs, thanks for adjusting the tests, I think reusing the existing tests is an excellent idea. I've just added two small comments!

File: src/function/table/arrow.cpp [hunk 12]
```diff
@@ -16,9 +16,10 @@ namespace duckdb {
 LogicalType ArrowTableFunction::GetArrowLogicalType(
     ArrowSchema &schema, std::unordered_map<idx_t, unique_ptr<ArrowConvertData>> &arrow_convert_data, idx_t col_idx) {
 	auto format = string(schema.format);
-	if (arrow_convert_data.find(col_idx) == arrow_convert_data.end()) {
+	if (!arrow_convert_data.count(col_idx)) {
```
[the remark this answers is not in the document]
Comment (Tishj) [reply src/function/table/arrow.cpp:19]: Hmm I think that's subjective, in my mind `count` on a map just aliases to `contains`
It's shorter and to me it expresses the intent better, but I'll change it

File: tools/pythonpkg/tests/fast/pandas/test_pandas_arrow.py (hunk 10 above)
Comment (Tishj) [reply tools/pythonpkg/tests/fast/pandas/test_pandas_arrow.py:42]: It's an error from pyarrow, I'll change it to match the full exception

File: tools/pythonpkg/tests/fast/pandas/test_pandas_arrow.py (hunk 11 above)
Comment (Tishj) [reply tools/pythonpkg/tests/fast/pandas/test_pandas_arrow.py:10]: That's done in `test_mixed_columns`
But I've added another test to it that should make this more explicit 👍

File: src/function/table/arrow.cpp (hunk 12 above)
[the remark this answers is not in the document]
Comment (Tishj) [reply src/function/table/arrow.cpp]: Changed it back 👍

**Comment by Mytherin** [comment]
@pdet can you do another pass over this?
