### PR TITLE
[Python] Add support for strided `float32` and `float64` data

### LINKED ISSUE #5253: Creating table from pandas dataframe produces incorrect results
### What happens?

I create a table from a pandas DataFrame. When I select the data back out, the data is different from the input.

### To Reproduce

I've attached the `example.pkl` file inside a zip. 

[example.pkl.zip](https://github.com/duckdb/duckdb/files/9962969/example.pkl.zip)

```
import duckdb
import pyarrow as pa
import pandas as pd
import pickle

con = duckdb.connect()
with open('example.pkl', 'rb') as f:
    in_df = pickle.load(f)
# Replacing the load from pandas with a load from pyarrow produces correct results.
# in_tbl = pa.Table.from_pandas(in_df)
# con.execute('create table tiles as select * from in_tbl')
con.execute('create table tiles as select * from in_df')
out = con.execute('select * from tiles limit 10000').fetch_df()
print(in_df['alpha0'])
print(out['alpha0'])
```

Output:
```
0    0.011102
1    0.011101
2    0.011111
3    0.011123
4    0.011102
5    0.011101
6    0.011111
7    0.011123
8    0.011139
9    0.011137
Name: alpha0, dtype: float32
0    0.011102
1    0.102584
2    0.114941
3    0.104812
4    0.099318
5    0.104231
6    0.099771
7    0.106665
8    0.103630
9    0.100998
Name: alpha0, dtype: float32
```

Also note that saving the dataframe to CSV and then reloading it also fixes the issue. So, I'm guessing this is an edge case where the pandas data is stored 

Thank you!!

### OS:

Mac OS Ventura, M1

### DuckDB Version:

0.5.1

### DuckDB Client:

Python

### Full Name:

Ben Thompson

### Affiliation:

Confirm Solutions

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #5253 

The functionality was already mostly there, as other POD column dtypes already supported strided memory layouts, but somehow floating points got left behind.

### CODE REVIEW

File: tools/pythonpkg/src/vector_conversion.cpp [hunk 1]
```diff
@@ -86,13 +86,24 @@ bool ValueIsNull(double value) {
...
-void ScanPandasFpColumn(T *src_ptr, idx_t count, idx_t offset, Vector &out) {
-	FlatVector::SetData(out, (data_ptr_t)(src_ptr + offset));
-	auto tgt_ptr = FlatVector::GetData<T>(out);
+void ScanPandasFpColumn(T *src_ptr, idx_t stride, idx_t count, idx_t offset, Vector &out) {
 	auto &mask = FlatVector::Validity(out);
-	for (idx_t i = 0; i < count; i++) {
-		if (Value::IsNan<T>(tgt_ptr[i])) {
-			mask.SetInvalid(i);
+	if (stride == sizeof(T)) {
+		FlatVector::SetData(out, (data_ptr_t)(src_ptr + offset));
```
Comment (Tishj) [inline tools/pythonpkg/src/vector_conversion.cpp:92]: Might not be worth it to separate these two cases, as we need to loop over the data regardless to check for NaN

**Comment by Mytherin** [comment]
Thanks for the PR! LGTM
