### PR TITLE
Using Arrow Scanner to scan Arrow Objects

### LINKED ISSUE #1835: Arrow dataset + aggregation + multithreading
**What does happen?**
I'm testing out the new abilities to query an Arrow source from DuckDB. Things work well for Tables and record batches, however I've found that with datasets, when using aggregations, with multithreading I get hangs.

The following will (almost always) hang on the last line:
```
ds <- arrow::open_dataset("userdata1.parquet")
duckdb::duckdb_register_arrow(con, "mydatasetreader", ds)
dbExecute(con, "PRAGMA threads=4")
dbGetQuery(con, "SELECT count(*) FROM mydatasetreader")
```

I've noticed that this will _sometimes_ succeed (with a correct result), though when it hangs it hangs forever. I've tried smaller numbers of threads (2, 3) and those seem to work slightly more frequently — 1 thread always works. Higher numbers of threads (e.g. 8) always hang. 

I'm happy to dig more / debug on my end if there are obvious places I should look.

**What should happen?**
Return the result of the query without hanging.

**To Reproduce**
This code (in the style of / could be inserted into duckdb/tools/rpkg/tests/testthat/test_register_arrow.R)
```
test_that("duckdb_register_arrow() works with datasets", {
    skip_on_os("windows")
    skip_if_not_installed("arrow", "4.0.1")
    con <- dbConnect(duckdb::duckdb())

    # Registering a dataset + aggregation
    ds <- arrow::open_dataset("userdata1.parquet")
    duckdb::duckdb_register_arrow(con, "mydatasetreader", ds)
    res1 <- dbGetQuery(con, "SELECT count(*) FROM mydatasetreader")
    res2 <- dbGetQuery(con, "SELECT count(*) FROM parquet_scan('userdata1.parquet')")
    expect_true(identical(res1, res2))
    # we can read with > 3 cores
    dbExecute(con, "PRAGMA threads=4")
    res3 <- dbGetQuery(con, "SELECT count(*) FROM mydatasetreader")
    expect_true(identical(res2, res3))
    duckdb::duckdb_unregister_arrow(con, "mydatasetreader")

    dbDisconnect(con, shutdown = T)
})
```

**Environment (please complete the following information):**
 - OS: macOS 11.3.1 on a Mac Pro 6-core Xeon E5
 - DuckDB Version: the `master` branch from today

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [x] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

### PR DESCRIPTION
**Pull request by pdet**
In this PR I change the python layer to use the arrow scanner to scan arrow objects. Similar to what is done from the R side.

Since the get_next() function in the arrow scan is not thread-safe, I also added a lock when acquiring new batches in parallel (Which fixes #1835)

There are 2 main things to note:
1) The Python and R side are now consistent in the way they scan the data, but they depend on an unreleased version of Arrow.

2) The arrow scanner has some difficulties when reading null values, which forced me to momentarily comment out some of our tests.

### CODE REVIEW

File: src/function/table/arrow.cpp [hunk 1]
```diff
@@ -16,6 +16,7 @@
 #include "utf8proc_wrapper.hpp"
 
 #include "duckdb/common/operator/multiply.hpp"
+#include <mutex>
```
Comment (Mytherin) [inline src/function/table/arrow.cpp:19]: `#include "duckdb/common/mutex.hpp"`

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! One minor comment, otherwise I think it looks good:

**Comment by Mytherin** [comment]
Could you merge this branch with master so the tests can run again?
