### PR TITLE
Issue #4388: DATE_TRUNC Low Precision

### LINKED ISSUE #4388: date_trunc on timestamp_ms leads to incorrect values.
### What happens?

With a timestamp_ms type date_trunc produces dates that seem to not be valid (or perhaps the metadata is incorrect). 

Most simple repro: `select date_trunc('day', CAST(now() AS TIMESTAMP_MS));` 

It also reproduces with `year`, `month`, `week` and `quarter`, but not `second` or `hour` so I'm assuming that it is caused by any any timestamp -> date coercion with the date_trunc. 

I had been using `current_timestamp()` instead of `now()` but on the master build (downloaded from a very recent master build) on the CLI that didn't work and I used now() instead).

Originally I ran into this issue on 0.4.0 (wasm build) while loading in arrow data in a timestampmillis vector, but found it was reproducible with a direct cast too. 

It does NOT reproduce on 3.4.0 so I'm guessing it may be related to https://github.com/duckdb/duckdb/issues/3880 (and a few other related changes / fixes). 

### To Reproduce

```
select date_trunc('day', CAST(now() AS TIMESTAMP_MS));
select date_trunc('month', CAST(now() AS TIMESTAMP_MS));
select date_trunc('quarter', CAST(now() AS TIMESTAMP_MS));
select date_trunc('year', CAST(now() AS TIMESTAMP_MS));
```
expectation (for today 8/14/22)
```
day => 2022-08-14
week => 2022-08-14
month => 2022-08-01
quarter => 2022-07-01
year => 2022-01-01
```

actual: 
```
day => 3681773-02-02  
week => 3681773-02-02 
month => 3749428-10-02 (BC) 
quarter => 794384-03-31 
year => 366696-08-11 (BC)  
```

### OS:

mac 

### DuckDB Version:

0.4.0, master

### DuckDB Client:

cli, wasm, java

### Full Name:

Jonathan Swenson

### Affiliation:

Omni

### Have you tried this on the latest `master` branch?

- [X] I agree (tried on artifacts from https://github.com/duckdb/duckdb/actions/runs/2855563716 -  33d78e2)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by hawkfish**
* Add missing cases for TIMESTAMP_MS and friends.
* Add exception for unhandled types.
* Add tests.

### CODE REVIEW

File: src/function/scalar/date/date_trunc.cpp [hunk 1]
```diff
@@ -692,6 +692,9 @@ static unique_ptr<FunctionData> DateTruncBind(ClientContext &context, ScalarFunc
 	case DatePartSpecifier::DOY:
 		switch (arguments[1]->return_type.id()) {
```
Comment (Mytherin) [inline src/function/scalar/date/date_trunc.cpp:693]: I think the problem here is actually that you are looking at the argument types to begin with - date trunc does not accept `timestamp` parameters (besides `timestamp`), so a cast will be automatically added. The cast will only be performed **after** the bind, however. This function should either be templated, or look at the `arguments` inside the `bound_function`.

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! One comment about the fix:

File: src/function/scalar/date/date_trunc.cpp (hunk 1 above)
Comment (hawkfish) [reply src/function/scalar/date/date_trunc.cpp:693]: Ah so you are saying that instead of "knowing" all the types that could be cast to `TIMESTAMP` it should discover what that argument will be by looking at the original binding types?

Comment (Mytherin) [reply src/function/scalar/date/date_trunc.cpp:693]: Exactly

**Comment by Mytherin** [comment]
Thanks!
