### PR TITLE
parquet: avoid corrupting define buffers during skips

### LINKED ISSUE #21166: INTERNAL Error: "Attempted to access index 1 within vector of size 1" when COPYing PLAIN_DICTIONARY STRUCT(LIST<STRUCT>) column with predicate pushdown
## Summary

DuckDB 1.2.1 (latest nightly may also be affected; confirmed on 1.2.1 ARM64) raises an `InternalException` when using `COPY ... TO` on a query that:

1. Reads a `STRUCT(result LIST<STRUCT<...>>, ...)` column encoded with **PLAIN_DICTIONARY**
2. Applies a **predicate pushdown** (`WHERE id = X`) that selects the **first non-null row immediately after a large contiguous null block** (≥53,000 nulls) within a row group

## Minimal Reproduction

```python
"""
Minimal reproduction for DuckDB bug:
  INTERNAL Error: Attempted to access index 1 within vector of size 1
"""

import duckdb
import pyarrow.parquet as pq

REPRO_FILE = "repro_input.parquet"
OUTPUT_FILE = "repro_output.parquet"

# Step 1: Create trigger file
# Key conditions:
#   - Row group size >= ~120,000 rows
#   - Large contiguous null block (>=53,000 rows) in a STRUCT(LIST<STRUCT>) column, mid-row-group
#   - Target row is the FIRST non-null row immediately after the null block
#   - Enough distinct non-null values to trigger PLAIN_DICTIONARY encoding
setup_conn = duckdb.connect()
setup_conn.execute(f"""
COPY (
    SELECT
        i AS id,
        CASE WHEN i >= 59392 AND i < 112640 THEN NULL
        ELSE {{
            result: [
                {{label: 'illustration', confidence: 0.96}},
                {{label: '3d',           confidence: 0.02}},
                {{label: 'comic',        confidence: 0.01}},
                {{label: 'not_painting', confidence: 0.005}},
                {{label: 'bangumi',      confidence: 0.005}}
            ],
            label: 'illustration',
            confidence: 0.96
        }}
        END::STRUCT(result STRUCT(label VARCHAR, confidence DOUBLE)[], label VARCHAR, confidence DOUBLE) AS col
    FROM range(122880) t(i)
) TO '{REPRO_FILE}' (FORMAT PARQUET, CODEC SNAPPY, ROW_GROUP_SIZE 122880)
""")

pf = pq.ParquetFile(REPRO_FILE)
print(f"Encoding: {pf.metadata.row_group(0).column(1).encodings}")
# Verify: col encoding includes PLAIN_DICTIONARY

# Step 2: Show the misread (predicate pushdown silently returns wrong NULL)
conn1 = duckdb.connect()
v_wrong = conn1.execute(
    f"SELECT col IS NULL FROM '{REPRO_FILE}' WHERE id = 112640"
).fetchone()[0]

conn2 = duckdb.connect()
conn2.execute("PRAGMA disable_optimizer")
v_correct = conn2.execute(
    f"SELECT col IS NULL FROM '{REPRO_FILE}' WHERE id = 112640"
).fetchone()[0]

print(f"With optimizer (predicate pushdown): col IS NULL = {v_wrong}   ← wrong!")
print(f"Without optimizer (full scan):       col IS NULL = {v_correct}  ← correct")

# Step 3: Trigger the crash
conn3 = duckdb.connect()
try:
    conn3.execute(
        f"COPY (SELECT col FROM '{REPRO_FILE}' WHERE id = 112640) TO '{OUTPUT_FILE}'"
    )
    print("No crash (bug not triggered)")
except Exception as e:
    print(f"CRASH: {e}")
```

**Output:**

```
Encoding: ('PLAIN_DICTIONARY', 'RLE_DICTIONARY', 'RLE')
With optimizer (predicate pushdown): col IS NULL = True   ← wrong!
Without optimizer (full scan):       col IS NULL = False  ← correct
CRASH: InternalException: INTERNAL Error: Attempted to access index 1 within vector of size 1
```

### Bug 1 — Reader: Predicate Pushdown × PLAIN_DICTIONARY Dremel Decoder Misread

When DuckDB applies predicate pushdown to target a row immediately after a large contiguous null block in a `PLAIN_DICTIONARY`-encoded `STRUCT(LIST<STRUCT>)` column, the Dremel decoder **misreads the definition level at the null→non-null page boundary**, incorrectly marking the row as `NULL` at the outer struct level.

Evidence:

```sql
-- Returns NULL  (wrong — predicate pushdown active)
SELECT col IS NULL FROM 'repro_input.parquet' WHERE id = 112640;

-- Returns false  (correct — full scan, no pushdown)
PRAGMA disable_optimizer;
SELECT col IS NULL FROM 'repro_input.parquet' WHERE id = 112640;
```

Conditions that must all be met:
| Condition | Value |
|-----------|-------|
| Column encoding | PLAIN_DICTIONARY (legacy dict encoding) |
| Null block size | ≥53,000 contiguous nulls |
| Null block position | Mid-row-group (not starting at row 0) |
| Target row | **First** non-null row immediately after the null block |
| Row group size | ≥~120,000 rows |

### Bug 2 — Writer: `ListColumnWriter` Doesn't Guard Against Outer-NULL + Non-Empty Child Vector

After the misread above, the in-memory vector state becomes inconsistent:

```
outer_struct_vector[0].valid = false     ← misread as NULL by the reader
result_list_vector[0] = {offset, length=5}  ← child list still has 5 entries
child_vector.size = 1                    ← only 1 row allocated
```

`ListColumnWriter::Write` sums up `list_entry.length` for all rows (getting 5) and calls the child writer for 5 elements — but the child vector only has 1 row. `PrimitiveColumnWriter` then asserts `index < size` → crash.

The writer should skip child-field writes when the outer struct validity is `false`.

## Workaround

Use DuckDB to read, Polars to write — Polars' parquet writer handles this edge case correctly:

```python
result = conn.execute("SELECT * FROM read_parquet(...) WHERE ...").pl()
result.write_parquet("output.parquet")
```

Alternatively, `PRAGMA disable_optimizer` before the query avoids the misread but disables all optimizations.

## Environment

- DuckDB version: 1.2.1 (confirmed, ARM64; also reported on 1.4.3)
- Python: 3.13
- OS: Linux ARM64
- Install: `pip install duckdb`

### PR DESCRIPTION
**Pull request by Mikubill**
## Summary

Fixes #21166.

`ColumnReader::ApplyPendingSkips` currently reuses the caller-provided define_out and repeat_out buffers as scratch space. That is unsafe because `PrepareRead` behaves asymmetrically:

  - the fast path (`GetRepeatedBatch`) advances the decoder but does not write into the caller buffer
  - the normal path (`GetBatch`) does write definition levels into the caller buffer

When a skipped range contains both NULL and non-NULL rows, stale definition levels written by earlier NULL iterations can survive into later fast-path iterations. For optional STRUCT<scalar, scalar, ...> columns, that can cause `StructColumnReader` to treat a non-NULL parent row as NULL after predicate pushdown.

This change allocates local scratch buffers inside `ApplyPendingSkips` and passes those to `PrepareRead`, so the skip phase never corrupts the caller's buffers.

### CODE REVIEW

File: extension/parquet/column_reader.cpp [hunk 1]
```diff
@@ -774,6 +774,10 @@ void ColumnReader::ApplyPendingSkips(data_ptr_t define_out, data_ptr_t repeat_ou
 	pending_skips = 0;
 
 	auto to_skip = num_values;
+	data_t skip_defines[STANDARD_VECTOR_SIZE];
```
Comment (Mytherin) [inline extension/parquet/column_reader.cpp]: Given that we are also reading the defines, we should also zero-out `skip_defines`. I think we might potentially read uninitialized memory otherwise.

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Looks good - one comment. Could you also retarget to `v1.5-variegata` so we can include this in the bug-fix release?

**Comment by KumoSiunaus** [comment]
@Mytherin Just wanted to voice support for this PR — we've been hitting #21166 in production. It would be great if this could be merged and included in the v1.5.1 release on March 23rd. Thanks!

**Comment by Mytherin** [comment]
It has been merged :)
