### PR TITLE
Map extract now allows composite (nested) types as `key`

### LINKED ISSUE #6541: Unexpected error when extracting entries from a map with nested keys
### What happens?

Building a map value with nested keys (lists or structs) works fine as indicated by the DuckDB documentation at  https://duckdb.org/docs/sql/data_types/map.

Extracting a value from such maps yields an unexpected error, however:

~~~
Error: Invalid type Error: Invalid Type [LIST]: Invalid type for List Vector Search
Error: Invalid type Error: Invalid Type [STRUCT]: Invalid type for List Vector Search
~~~

### To Reproduce

Map with list-typed keys:

~~~
SELECT map_extract(map([[0,1]], ['X']), [0,1]);
-- Error: Invalid type Error: Invalid Type [LIST]: Invalid type for List Vector Search
~~~

Map with struct-typed keys:
~~~
SELECT map_extract(map([(0,1)], ['X']), (0,1));
-- Error: Invalid type Error: Invalid Type [STRUCT]: Invalid type for List Vector Search
~~~

### OS:

macOS Ventura 13.2.1

### DuckDB Version:

v0.7.2-dev14 c817201fa8

### DuckDB Client:

CLI

### Full Name:

Torsten Grust

### Affiliation:

U Tübingen, Germany

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #6541 

We now use the ListPositionFunction (`list_position` in the catalog) to do the search in the MAP, which allows us to reuse the existing logic - and because of that also support nested types

### CODE REVIEW

**Comment by Tishj** [comment]
I think ListPositionFunction is missing support for INTERVAL physical type
Should be an easy fix, will push a fix when I'm in front of my laptop again

File: src/function/scalar/map/map_extract.cpp [hunk 1]
```diff
@@ -5,34 +5,76 @@
...
+		idx_t current_offset = ListVector::GetListSize(result);
+
+		// Get the 'values' list entry corresponding to the offset
+		idx_t value_index = map_data.sel->get_index(row);
+		auto &value_list_entry = ((list_entry_t *)map_data.data)[value_index];
+
+		// Add the values to the result
+		idx_t list_offset = value_list_entry.offset + (offset - 1);
+		// All keys are unique, only one will ever match
+		idx_t length = 1;
```
Comment (Tishj) [inline src/function/scalar/map/map_extract.cpp:52]: Looking back on this, this seems a wrong assumption
but it works?

This passes:
```sql
query I
select map([[[3]]], [[[4],[4]]])[[[3]]]
----
[[[4], [4]]]
```

Comment (Tishj) [reply src/function/scalar/map/map_extract.cpp:48]: Ah nvm, the input is a LIST, so it realizes that we're copying 1 entry from a list - thereby copying also the contents of that entry

File: test/sql/types/nested/map/test_map_subscript_composite.test [hunk 2]
```diff
@@ -0,0 +1,154 @@
...
+[2]
+[2]
+[2]
+[2]
+
+#Test dictionary vectors
+query III
+select grp, m, case when grp>1 then m[[0]] else list_value(null) end
+from (select grp, MAP(lsta,lstb) as m
+from (SELECT a%4 as grp, list([a]) as lsta, list(a) as lstb FROM range(7) tbl(a) group by grp) as lst_tbl) as T;
```
Comment (Mytherin) [inline test/sql/types/nested/map/test_map_subscript_composite.test:129]: Perhaps it makes sense to use `test_all_types` as map keys in a test?

For example, this should be a nop:

```sql
SELECT map([columns(*)], [columns(*)])[columns(*)]
FROM test_all_types()
WHERE bool IS NOT NULL;
```

i.e. it should be identical to:

```sql
SELECT *
FROM test_all_types()
WHERE bool IS NOT NULL;
```

File: test/sql/types/nested/map/test_map_subscript_composite.test [hunk 3]
```diff
@@ -0,0 +1,154 @@
...
+----
```
Comment (Mytherin) [inline test/sql/types/nested/map/test_map_subscript_composite.test:130]: Also perhaps add some tests with `test_vector_types`:

```sql
SELECT map([c], [c])[c]
FROM test_vector_types(NULL::INT[], false) t(c)
WHERE c IS NOT NULL;
```

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! LGTM. Some comments:

File: test/sql/types/nested/map/test_map_subscript_composite.test (hunk 2 above)
Comment (Tishj) [reply test/sql/types/nested/map/test_map_subscript_composite.test:129]: Added a slow test for it 👍

File: test/sql/types/nested/map/test_map_subscript_composite.test (hunk 3 above)
Comment (Tishj) [reply test/sql/types/nested/map/test_map_subscript_composite.test:130]: This feels like cheating, I had no idea that function existed, that's such a helpful tool
Found and fixed a couple bugs in existing code because of this :pray:

File: src/function/scalar/map/map_extract.cpp [hunk 4]
```diff
@@ -41,26 +79,30 @@ static void MapExtractFunction(DataChunk &args, ExpressionState &state, Vector &
...
 
-	for (idx_t row = 0; row < args.size(); row++) {
-		idx_t row_index = map_data.sel->get_index(row);
-		auto key_value = key.GetValue(row);
+	Vector position_vector(LogicalType::LIST(LogicalType::INTEGER), tuple_count);
+	// We can pass around state as it's not used by ListPositionFunction anyways
+	ListContainsOrPosition<int32_t, PositionFunctor, MapKeyArgFunctor>(list_position_chunk, position_vector);
 
-		list_entry_t entry = ListVector::GetData(map)[row_index];
-		auto offsets = MapVector::Search(map_keys, args.size(), key_value, entry);
```
Comment (Mytherin) [inline src/function/scalar/map/map_extract.cpp:54]: Is `MapVector::Search` unused after this PR?

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Looks good. One comment:

File: src/function/scalar/map/map_extract.cpp (hunk 4 above)
Comment (Tishj) [reply src/function/scalar/map/map_extract.cpp:54]: Ah yea now that you mention it, probably is
I'll clean up the dead code :+1:

**Comment by Mytherin** [comment]
Thanks!
