### PR TITLE
Pop up ICU errors to the csv sniffer

### LINKED ISSUE #17705: DuckDB v1.3 introduced a new error in read_csv related to date parsing.
### What happens?

A CSV file that was previously parseable under v1.2 is no longer parseable under v1.3 because of an error trying to parse timezones. In addition, the `ignore_errors = true` flag appears to be ignored. 

### To Reproduce

Consider the following CSV taken from a much larger file: 

```csv
day_night,operation_no,flight_date_time
Night,38615452,2022/01/27 11:04:57 PM
Night,38615452,2022/01/27 11:04:57 PM
Night,38615475,2022/01/27 11:09:20 PM
```

Using the CLI with the following command: 

`select * from read_csv('sample.csv');`

Produces the following error: 

```
Not implemented Error:
Unknown TimeZone 'PM'!

Candidate time zones: "Pacific/Marquesas", "PLT", "PNT", "PRC", "GMT"
```

Attempting to ignore errors using the command below results in the same error as above being generated: 

`select * from read_csv('sample.csv', ignore_errors = true);`

In DuckDB v1.2, this column was parsed as a VARCHAR and no error was reported. If DuckDB v1.3 is now "correct" it should still honour the `ignore_errors` options.

_This may be related to [Sniff Timestamp_TZ from CSV FIles #15730](https://github.com/duckdb/duckdb/pull/15730)_

### OS:

macOS

### DuckDB Version:

DuckDB v1.3.0 (Ossivalis) 71c5c07cdd clang-17.0.0

### DuckDB Client:

CLI

### Hardware:

MacBook Pro

### Full Name:

Kenny Carruthers

### Affiliation:

None

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [x] Yes, I have

### PR DESCRIPTION
**Pull request by pdet**
Fix: https://github.com/duckdb/duckdb/issues/17705

### CODE REVIEW

File: extension/icu/icu-strptime.cpp [hunk 1]
```diff
@@ -293,7 +293,7 @@ struct ICUStrptime : public ICUDateFunc {
 
 				    // Change TZ if one was provided.
 				    if (tz.GetSize()) {
-					    SetTimeZone(calendar, tz);
+					    SetTimeZone(calendar, tz, parameters.error_message);
```
Comment (Mytherin) [inline extension/icu/icu-strptime.cpp]: In case of an error we should call `HandleCastError` similar to the code above, instead of (still) returning a timestamp. Could you add a test that triggers this with an explicit `TRY_CAST` and an invalid timezone?

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Looks good - one comment:

**Comment by Mytherin** [comment]
Thanks!
