### PR TITLE
Fix arrow conversion, map doesn't support large offset

### LINKED ISSUE #10795: Bug in map to Arrow conversion.
### What happens?

When `arrow_large_buffer_size` is enabled, conversion of map data type to Arrow results in incorrect data. It looks like DuckDB uses 64-bit offsets when generating Arrow MapArray, but MapArray only supports 32-bit offsets. There is no LargeMapArray type in Arrow.

### To Reproduce

```
import duckdb

# correct
arrow = duckdb.sql("select map(['non-inlined string', 'test', 'duckdb'], [42, 1337, 123])").to_arrow_table()
print(arrow)

# incorrect
duckdb.sql("set arrow_large_buffer_size=true")
arrow = duckdb.sql("select map(['non-inlined string', 'test', 'duckdb'], [42, 1337, 123])").to_arrow_table()
print(arrow)
```

```
pyarrow.Table
map(main.list_value('non-inlined string', 'test', 'duckdb'), main.list_value(42, 1337, 123)): map<string, int32>
  child 0, entries: struct<key: string not null, value: int32> not null
      child 0, key: string not null
      child 1, value: int32
----
map(main.list_value('non-inlined string', 'test', 'duckdb'), main.list_value(42, 1337, 123)): [[keys:["non-inlined string","test","duckdb"]values:[42,1337,123]]
```
```
pyarrow.Table
map(main.list_value('non-inlined string', 'test', 'duckdb'), main.list_value(42, 1337, 123)): map<large_string, int32>
  child 0, entries: struct<key: large_string not null, value: int32> not null
      child 0, key: large_string not null
      child 1, value: int32
----
map(main.list_value('non-inlined string', 'test', 'duckdb'), main.list_value(42, 1337, 123)): [[keys:[]values:[]]]
```

### OS:

ubuntu 20.04

### DuckDB Version:

main

### DuckDB Client:

python

### Full Name:

Yiyuan Liu

### Affiliation:

High-Flyer AI

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by yiyuanliu**
Fix #10795

### CODE REVIEW

File: src/common/arrow/arrow_appender.cpp [hunk 1]
```diff
@@ -236,11 +236,7 @@ static void InitializeFunctionPointers(ArrowAppendData &append_data, const Logic
 		break;
 	}
 	case LogicalTypeId::MAP:
-		if (append_data.options.arrow_offset_size == ArrowOffsetSize::LARGE) {
-			InitializeAppenderForType<ArrowMapData<int64_t>>(append_data);
-		} else {
-			InitializeAppenderForType<ArrowMapData<int32_t>>(append_data);
-		}
+		InitializeAppenderForType<ArrowMapData<int32_t>>(append_data);
```
Comment (Tishj) [inline src/common/arrow/arrow_appender.cpp:239]: Please add a comment describing that there is no LargeMapArray, currently this can easily be mistaken for an oversight

File: tools/pythonpkg/tests/fast/udf/test_scalar.py [hunk 2]
```diff
@@ -127,9 +127,11 @@ def no_op(x):
         con = duckdb.connect()
         map_type = con.map_type('VARCHAR', 'BIGINT')
         con.create_function('test_map', no_op, [map_type], map_type, type=udf_type)
-        rel = con.sql("select test_map(map(['non-inlined string', 'test', 'duckdb'], [42, 1337, 123]))")
-        res = rel.fetchall()
-        assert res == [({'key': ['non-inlined string', 'test', 'duckdb'], 'value': [42, 1337, 123]},)]
+        for arrow_large_buffer_size in [False, True]:
```
Comment (Tishj) [inline tools/pythonpkg/tests/fast/udf/test_scalar.py:130]: Im confused, this is not testing the Arrow export?
Can you revert this change and add/change a dedicated test for outputting maps with `.arrow()`

Likely found in tests/fast/arrow

Comment (yiyuanliu) [reply tools/pythonpkg/tests/fast/udf/test_scalar.py]: Added a new test `tests/fast/arrow/test_10795.py`

**Review by Tishj — APPROVED** [review]
Thanks for the changes, looks good to me!
Also, active PRs get marked as draft automatically when new changes are pushed, feel free to just undraft the PR so CI can run 👍

**Comment by Mytherin** [comment]
Thanks!
