### PR TITLE
Fix #7023

### LINKED ISSUE #7023: Index appears like a table
### What happens?

When we create an index on a table, it appears like a table with the

```sql
show tables;
```

### To Reproduce

Create table and index : 

```sql
CREATE TABLE mobitag_audit(date TIMESTAMP NOT NULL,
    message_length INTEGER NOT NULL,
    day_name VARCHAR);

create index mobitag_date on mobitag_audit(date);
```

get tables : 

```sql
show tables;
```

image

### OS:

Linux Mint 21.1 Vera

### DuckDB Version:

v0.7.1 b00b93f0b1

### DuckDB Client:

duckdb

### Full Name:

Adrien SALES

### Affiliation:

adriens

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #7023 

Indexes aren't tables, so they shouldn't show up in `SHOW TABLES`

### CODE REVIEW

File: src/function/pragma/pragma_queries.cpp [hunk 1]
```diff
@@ -22,21 +22,27 @@ string PragmaShowTables(ClientContext &context, const FunctionParameters &parame
 	auto schema = ClientData::Get(context).catalog_search_path->GetDefault().schema;
 	schema = (schema == INVALID_SCHEMA) ? DEFAULT_SCHEMA : schema; // NOLINT
 
-	auto where_clause =
-	    StringUtil::Join({"where database_name = '", catalog, "' and schema_name = '", schema, "'"}, "");
+	auto where_clause = StringUtil::Format("where ((database_name = '%s') and (schema_name = '%s'))", catalog, schema);
+	// clang-format off
+	auto pragma_query = StringUtil::Format("\
+	with \"tables\" as						\
```
Comment (Mytherin) [inline src/function/pragma/pragma_queries.cpp:28]: Can we use a multi-line string literal here? e.g.:

```cpp
auto pragma_query = R"(
      ...
    )";
```

Comment (Tishj) [reply src/function/pragma/pragma_queries.cpp]: Learned something new today, that's really cool! No need to escape the newlines, and also no need to escape the `"` 🤯

**Comment by Mytherin** [comment]
Thanks!
