### PR TITLE
[NodeJS] Support multi-statement prepare

### LINKED ISSUE #6198: Nodejs client: Import fails with "Cannot prepare multiple statements"
### What happens?

Using the node client, exporting a database with multiple tables works fine. Importing it fails with:

>  Invalid Error: Cannot prepare multiple statements at once!

```javascript
{
  errno: -1,
  code: 'DUCKDB_NODEJS_ERROR'
}
```

### To Reproduce

**Current OS and Node Version**

OS: MacOS Ventura 13.2 (22D49)
Device: M1 Max
Node: v18.13.0

**Steps**

```javascript
import duckdb from 'duckdb';

async function getConnection(file) {
    console.log(`creating new connection for: ${ file }`);
    return new Promise((resolve, reject) => {
        const db = new duckdb.Database(file, duckdb.OPEN_READWRITE, () => {
            resolve(db);
        });
    });
}

async function timeAsync(block) {
    const start = process.hrtime();
    await block();
    const end = process.hrtime(start);
    const elapsedMs = (end[0] * 1000000000 + end[1]) / 1000000;
    return elapsedMs;
}

async function runQuery(connection, func, sql, args) {
    args ||= [];
    func = func.bind(connection);
    return new Promise((resolve, reject) => {
        func(sql, ...args, (err, res) => {
            if (err) {
                reject(err);
                return;
            }
            resolve(res);
        });
    });
}

async function executeQuery(con, query) {
    let data = null;
    let error = null;
    const time = await timeAsync(async () => {
        try {
            data = await runQuery(con, con.all, query);
        } catch (err) {
            error = err;
        }
    });
    if (error) {
        console.log(`query failed with error`, error);
        console.log(`query executed was: ${ query }\n`);
        return;
    }
    console.log(`query executed was: ${ query }\n`);
    console.log(`query executed in ${time}ms`, data);
}

const bugCon = await getConnection("bug.db");
await executeQuery(
    bugCon,
    'create table test (id int);'
);
await executeQuery(
    bugCon,
    'create table test2 (id int);'
);
await executeQuery(
    bugCon,
    "export database './tmp' (format csv, compression zstd)"
);
console.log("creating new database to import from");
const bug2Con = await getConnection("bug2.db");

// ---------------------------------
// 🐞🐞🐞🐞THIS SHOULD WORK BUT DOESN'T
// --------------------------------

await executeQuery(
    bug2Con,
    "import database './tmp'"
);
```

### OS:

MacOS

### DuckDB Version:

0.6.1

### DuckDB Client:

Node (18.13.0)

### Full Name:

Rohland de Charmoy

### Affiliation:

Codeo

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #6198 

Things like `IMPORT` are pragmas that resolve to a query with multiple statements.
When this is passed to `Prepare` directly this throws an error.

Instead of providing this directly to Prepare we now first use ExtractStatements to get the statements, if there are more than one we directly execute everything but the last one.

### CODE REVIEW

**Review by Mytherin — APPROVED** [review]
LGTM. Perhaps @Mause wants to have a look as well?

File: tools/nodejs/src/statement.cpp [hunk 1]
```diff
@@ -34,7 +34,37 @@ struct PrepareTask : public Task {
...
+		}
+
+		// if there are multiple statements, we directly execute the statements besides the last one
+		// we only return the result of the last statement to the user, unless one of the previous statements fails
+		for (idx_t i = 0; i + 1 < statements.size(); i++) {
+			auto pending_query = connection->PendingQuery(std::move(statements[i]));
+			auto res = pending_query->Execute();
+
+			if (res->HasError()) {
+				res->ThrowError();
```
Comment (Mytherin) [inline tools/nodejs/src/statement.cpp:63]: Should we throw an error here? Could you perhaps try triggering this (e.g. `SELECT * FROM non_existent_table; SELECT 42`)

Comment (Tishj) [reply tools/nodejs/src/statement.cpp:63]: Yea you are right, we should probably do something different than throw a c++ exception here.
I tried to throw a Napi::Error through the Env instead, and also tried just only setting `statement.statement` to a ParsedStatement containing the PreservedError, but in either case it segfaults, instead of resolving properly
```ts
        it('should fail executing the first statement', function(done) {
            db.prepare("select * from non_existent_table; select 42")
                .all(function(err: null | Error, rows: TableData) {
                    if (err) {
						done();
					}
                })
                .finalize(done);
        });
```

Comment (Tishj) [reply tools/nodejs/src/statement.cpp:63]: I looked into it a little more, `.all` runs the `RunPreparedTask` Task, but the `PrepareTask` Task is failing, so likely I need to change this test, `db.prepare()` fails, before `.all()` even runs

Comment (Tishj) [reply tools/nodejs/src/statement.cpp]: Should be fixed now

File: tools/nodejs/src/statement.cpp [hunk 2]
```diff
@@ -34,7 +34,45 @@ struct PrepareTask : public Task {
...
+			return;
+		} catch (std::exception &ex) {
+			statement.statement = duckdb::make_unique<duckdb::PreparedStatement>(duckdb::PreservedError(ex));
+			return;
+		}
+
+		// if there are multiple statements, we directly execute the statements besides the last one
+		// we only return the result of the last statement to the user, unless one of the previous statements fails
+		for (idx_t i = 0; i + 1 < statements.size(); i++) {
+			auto pending_query = connection->PendingQuery(std::move(statements[i]));
```
Comment (Mytherin) [inline tools/nodejs/src/statement.cpp:59]: Can we wrap the entire function into one big try/catch block? `PendingQuery` is not covered by the try/catch and there's a bunch of duplicate exception handling logic.

**Review by Mytherin — COMMENTED** [review]
Thanks! Looks good - one more request for a minor clean-up then this can be merged.

**Comment by Mytherin** [comment]
Thanks!
