### PR TITLE
[Attach] Fix bug causing sequences to break attaching databases.

### LINKED ISSUE #10263: Sequence missing from catalog with ATTACH
### What happens?

I'm not sure this is an issue or expected behavior, but I found the following suprising.

Attaching to database with `ATTACH` for a database with a sequence raises a Catalog Error (for a missing sequence).

### To Reproduce

**Create DB**

```sh
duckdb db.duckdb
```

```sql
CREATE SEQUENCE 'id_seq';
CREATE TABLE person (id INT DEFAULT nextval('id_seq'), age INT NOT NULL);
INSERT INTO person (age) VALUES (10);
```

**Attach in a new session**

```sh
duckdb
```

```sql
ATTACH 'db.duckdb';
# Error: Catalog Error: Sequence with name id_seq does not exist!
```

Everything works fine connecting to existing db when starting cli:

```
duckdb db.duckdb
```

### OS:

macOS 14.2 

### DuckDB Version:

v0.9.2 3c695d7ba9

### DuckDB Client:

CLI

### Full Name:

Trevor Manz

### Affiliation:

Harvard Medical School

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #10263 

Essentially, this issue stems from code being shared between database loading and attaching a new database.
This function is `SingleFileCheckpointReader::LoadFromStorage`

It was originally made to handle loading the initial database from disk, meaning no existing transaction manager was present.
Because of this, it always created a new connection to the database and manually started a transaction, to meet the requirement imposed by the binder - which is that there has to be an active transaction attached to these actions.

Since we are coming from PhysicalAttach, we already have an existing database, and connection with transaction running, in which we are creating this AttachedDatabase.
Because of the behavior of LoadFromStorage, we create a new transaction in which we are loading the contents of the database.

Because there are now two transactions active, one that has created the AttachedDatabase and another that is populating the database, neither transaction can see the changes made by the other.
That causes the lookup for `db1.seq` to fail, because it can't *see* `db1`.

We fix this by providing proper context to LoadFromStorage to let it know there is an existing transaction it can use, instead of starting a new one.

### CODE REVIEW

File: src/include/duckdb/storage/storage_manager.hpp [hunk 1]
```diff
@@ -46,7 +46,7 @@ class StorageManager {
 	static StorageManager &Get(Catalog &catalog);
 
 	//! Initialize a database or load an existing database from the given path
-	void Initialize();
+	void Initialize(optional_ptr<ClientContext> context);
```
Comment (douenergy) [inline src/include/duckdb/storage/storage_manager.hpp:49]: Should we also set 'nullptr' as the default value for StorageManager.Initialize?

**Review by douenergy — COMMENTED** [review]
Thanks, @Tishj, I have learned more about CheckpointManager from your PR.

**Comment by Mytherin** [comment]
Thanks! LGTM
