### PR TITLE
Remove dependency of arrow import with dataset module

### LINKED ISSUE #6584: Reading from pyarrow is not thread-safe
### What happens?

Reading in multiple pyarrow datasets from different threads causes the error:
```
duckdb.InvalidInputException: Invalid Input Error: Optional module 'pyarrow.dataset' is required to perform this action
```

Manually importing `pyarrow.dataset` within each thread is the current workaround.

### To Reproduce

```python
from concurrent.futures import ThreadPoolExecutor
import duckdb
pool = ThreadPoolExecutor(max_workers=2)

c = duckdb.connect()

def f(cur, i):
    import pyarrow
    # import pyarrow.dataset # (uncomment to fix)
    data = pyarrow.Table.from_pydict({"a": [1,2,3]})
    cur.execute(f"create table t_{i} as select * from data")

futures = []
for i in range(2):
    fut = pool.submit(f, c.cursor(), i)
    futures.append(fut)

for fut in futures:
    fut.result()
```

### OS:

MacOS Arm

### DuckDB Version:

0.7.2-dev225 and 0.7.1

### DuckDB Client:

Python

### Full Name:

Alexander Vandenberg-Rodes

### Affiliation:

Obsidian Security

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by pdet**
The way the import cache for arrow was previously implemented caused an unnecessary dependency on `pyarrow.Dataset` when operating on non-dataset-related Arrow objects.

Fixes #6584

### CODE REVIEW

**Comment by Tishj** [comment]
If I recall correctly, 3.9 doesn't have dataset module, that's why it's marked optional
Might need a pytest.mark.skipif(sys.version_info < (3,10))

**Comment by Mause** [comment]
> If I recall correctly, 3.9 doesn't have dataset module, that's why it's marked optional
> Might need a pytest.mark.skipif(sys.version_info < (3,10))

I don't think it's a Python version thing, it's just an optional part of pyarrow that you can choose to compile in or not

**Comment by Mause** [comment]
> If I recall correctly, 3.9 doesn't have dataset module, that's why it's marked optional
> Might need a pytest.mark.skipif(sys.version_info < (3,10))

I don't think it's a Python version thing, it's just an optional part of pyarrow that you can choose to compile in or not

File: tools/pythonpkg/src/python_import_cache.cpp [hunk 1]
```diff
@@ -34,10 +34,10 @@ PyObject *PythonImportCacheItem::AddCache(PythonImportCache &cache, py::object o
 }
 
 void PythonImportCacheItem::LoadModule(const string &name, PythonImportCache &cache) {
-	load_attempted = true;
```
Comment (Tishj) [inline tools/pythonpkg/src/python_import_cache.cpp:37]: I don't agree with this change, since these are modules, if they're not installed at the start of a session, that will not change during the session.
This way we will still attempt to load modules unnecessarily even when we already know they're missing.

I guess monkeypatch might mess with this assumption though..

File: tools/pythonpkg/src/pyconnection.cpp [hunk 2]
```diff
@@ -1382,7 +1382,7 @@ bool DuckDBPyConnection::IsAcceptedArrowObject(const py::object &object) {
 	    py_import_cache.arrow_lib().RecordBatchReader.IsInstance(object)) {
 		return true;
 	}
-	if (!py_import_cache.arrow_dataset().IsLoaded()) {
+	if (!ModuleIsLoaded<ArrowDatasetCacheItem>()) {
```
Comment (Tishj) [inline tools/pythonpkg/src/pyconnection.cpp:1385]: While this is a good change, as we don't unnecessarily load a module we don't need this way, it shouldn't be required to fix the issue.

Recently I pushed a fix for missing attributes in a module, by checking if the module has the attribute in question (hasattr).
IsInstance will still work if the object isn't loaded and just return false

**Review by Tishj — COMMENTED** [review]
Looks good, just one or two things I'm not sure about

File: tools/pythonpkg/src/python_import_cache.cpp (hunk 1 above)
Comment (Tishj) [reply tools/pythonpkg/src/python_import_cache.cpp:37]: Actually, it's probably fine to leave it as is, because as discussed, the monkeypatch messes with this assumption

**Comment by Mytherin** [comment]
Could you have a look at fixing the merge conflicts?

**Comment by Tishj** [comment]
`DuckDBPyConnection::IsPolarsDataFrame` symbol is missing apparently

**Comment by Mytherin** [comment]
Thanks!
