### PR TITLE
[Adaptive Sniffer] In case files have only one row, be more permissive to detect headers and types.

### LINKED ISSUE #14166: csv/csv.gz Files With Empty Rows Auto-Inferred As VARCHAR
### What happens?

When reading multiple `csv` or `csv.gz` files say with a glob pattern, and one of those has no rows, all the columns in that file is casted as a VARCHAR. This causes a schema mismatch between that file and all other files when they have a defined type.

### To Reproduce

Run this in the DuckDB CLI (or run in an in-memory database in Python)

```sql
CREATE OR REPLACE TABLE
    cte AS
SELECT
    generate_series::DATE as date_col,
    (random()*100)::INTEGER AS int_col,
    (random()*123.45)::DOUBLE AS double_col
FROM
    GENERATE_SERIES(TIMESTAMP '2000-01-01 00:00:00', TIMESTAMP '2000-12-31 00:00:00', INTERVAL 1 DAY);

COPY (
    FROM
        cte
    WHERE
        EXTRACT(YEAR FROM date_col) == 2000
) TO '__2000.csv.gz';

COPY (
    FROM
        cte
    WHERE
        EXTRACT(YEAR FROM date_col) == 2001
) TO '__2001.csv.gz';

FROM
    '__200*.csv.gz';
```

Error:
```
Invalid Input Error: Schema mismatch between globbed files.
Main file schema: __2000.csv.gz
Current file: __2001.csv.gz
Column with name: "date_col" is expected to have type: DATE But has type: VARCHAR
Column with name: "int_col" is expected to have type: BIGINT But has type: VARCHAR
Column with name: "double_col" is expected to have type: DOUBLE But has type: VARCHAR
Potential Fix: Since your schema has a mismatch, consider setting union_by_name=true.
```

Note that this also occurs when the format for the output file to be read again is `csv`, but does not occur when the output format is a parquet file.

### OS:

macOS aarch64 / RHEL 7.6 Linux x86_64

### DuckDB Version:

1.1.1

### DuckDB Client:

CLI

### Hardware:

_No response_

### Full Name:

Kian Francis Gedaria Laredo

### Affiliation:

Phitopolis International Corporation

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by pdet**
When globbing multiple CSV files, if a file that would be ran with the adaptive sniffer only has one row,  the adaptive sniffer could misidentify if the one row would be a header or a data row. 

This PR extends the checks to identify this case, and adds tests for it.

Fix: #14166

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR!

I wonder if we should be sniffing over multiple files when the files are small, similar to what we do in the JSON reader? That would perhaps more robustly fix the issue.

File: src/execution/operator/csv_scanner/scanner/csv_schema.cpp [hunk 1]
```diff
@@ -60,14 +60,53 @@ bool CSVSchema::Empty() const {
 	return columns.empty();
 }
 
-bool CSVSchema::SchemasMatch(string &error_message, vector<string> &names, vector<LogicalType> &types,
-                             const string &cur_file_path) {
-	D_ASSERT(names.size() == types.size());
+bool CSVSchema::SchemasMatch(string &error_message, SnifferResult *sniffer_result, const string &cur_file_path,
```
Comment (Mytherin) [inline src/execution/operator/csv_scanner/scanner/csv_schema.cpp:63]: nit: can we avoid using raw pointers here?

File: src/execution/operator/csv_scanner/scanner/csv_schema.cpp [hunk 2]
```diff
@@ -60,8 +60,10 @@ bool CSVSchema::Empty() const {
 	return columns.empty();
 }
 
-bool CSVSchema::SchemasMatch(string &error_message, SnifferResult *sniffer_result, const string &cur_file_path,
-                             bool is_minimal_sniffer) const {
+bool CSVSchema::SchemasMatch(string &error_message, weak_ptr<SnifferResult> sniffer_result_ptr,
```
Comment (Mytherin) [inline src/execution/operator/csv_scanner/scanner/csv_schema.cpp]: Is there a reason for this to be a weak pointer instead of a reference?

**Comment by Mytherin** [comment]
Thanks - one more comment, otherwise LGTM

**Comment by Mytherin** [comment]
Thanks!
