### PR TITLE
prevent physical nested loop join with multiple conditions on semi an…

### LINKED ISSUE #10046: ANTI JOIN with range not giving results
### What happens?

When using the ANTI JOIN sql syntax, not getting the expected results.

### To Reproduce

```
import duckdb
import pandas as pd

data = {
    "user_id": ["1", "2", "3", "4", "5", "6", "7", "8"],
    "timestamp": [
        "2023-03-14T00:00:00Z",
        "2023-03-15T00:00:00Z",
        "2023-03-16T00:00:00Z",
        "2023-03-17T00:00:00Z",
        "2023-03-18T00:00:00Z",
        "2023-03-19T23:59:59Z",
        "2023-03-20T00:00:00Z",
        "2023-03-21T00:00:00Z",
    ],
    "value": [2, 4, 7, 3, 2, 4, 7, 3],
}
input_table = pd.DataFrame.from_dict(data)

data = {
    "timestamp": [
        "2023-03-15T00:00:00Z",
        "2023-03-20T00:00:00Z",
    ]
}
time_limit_table = pd.DataFrame.from_dict(data)

duckdb.sql("""
    WITH flattened AS (
        SELECT MIN("timestamp") AS start, MAX("timestamp") AS end
        FROM time_limit_table
    )
    SELECT * FROM input_table
    ANTI JOIN flattened
    ON input_table."timestamp" >= flattened.start AND input_table."timestamp" <  flattened.end
""")
# returns 0 rows -- expecting 3 rows
```

Using the `left join` approach gives the expected result (3 rows):
```
duckdb.sql("""
    WITH flattened AS (
        SELECT MIN("timestamp") AS start, MAX("timestamp") AS end
        FROM time_limit_table
    )
    SELECT * FROM input_table
    LEFT JOIN flattened
    ON input_table."timestamp" >= flattened.start AND input_table."timestamp" <  flattened.end
    WHERE flattened.start is null
""")
```

### OS:

macOS 13.6.3, arm64

### DuckDB Version:

0.9.2

### DuckDB Client:

Python

### Full Name:

Vitaly Sergeyev

### Affiliation:

Tecton

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by Tmonster**
Fixes https://github.com/duckdb/duckdb/issues/10046

The query in the issue is currently planned as PhysicalNestedLoopJoins. If a semi or anti join is planned as a physical nested loop join, then `ResolveSimpleJoin` is used to create the output chunk. The `ResolveSimpleJoin` calls `NestedLoopJoinMark::Perform`. This function implicitly assumes a OR conjunction among all conditions, setting the `found_match` index to true once the condition is satisfied, then keeping the true value during all future comparisons. 

One potential fix is to fix the `NestedLoopJoinMark` logic so that it has better awareness of the conditions, if they have `conjunction_and` or `conjunction_or` etc. However, this is a very rare instance, to satisfy it and plan a nested loop join mark with multiple conditions,

- there need to be *no* equality conditions. Otherwise a hash join with a filter is used. 
- The conditions must all be connected by `AND` statements. If `OR` statements are used then a `PhysicalBlockwiseNLJoin` is used, and the expressions are properly evaluated. 
- It needs to use the explicit `ANTI` or `SEMI` syntax.

The solution I have come up with here is just to check the number of conditions in the SEMI or ANTI join and see if we can plan a `NestedLoopJoin`. If `conditions.size() > 1`, we plan a `PhysicalBlockwiseNLJoin` which will properly evaluate the conditions.

### CODE REVIEW

File: src/execution/operator/join/physical_nested_loop_join.cpp [hunk 1]
```diff
@@ -309,7 +315,10 @@ void PhysicalNestedLoopJoin::ResolveSimpleJoin(ExecutionContext &context, DataCh
 	state.left_condition.Reset();
 	state.lhs_executor.Execute(input, state.left_condition);
 
-	bool found_match[STANDARD_VECTOR_SIZE] = {false};
+	bool found_match[STANDARD_VECTOR_SIZE] = {true};
```
Comment (Mytherin) [inline src/execution/operator/join/physical_nested_loop_join.cpp:318]: This change seems off to me - is this made intentionally?

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Looks good - one comment below. I wonder if the mark join code is actually correct given your description? Join conditions should always be a conjunctive `AND`. Perhaps the mark join was previously only triggered with a single condition?

File: src/execution/operator/join/physical_nested_loop_join.cpp (hunk 1 above)
Comment (Tmonster) [reply src/execution/operator/join/physical_nested_loop_join.cpp:318]: No not made intentionally. Belonged to a previous solution which I ended up abandoning because I didn't really want to change this logic like this
