### PR TITLE
[Python] Fix conversion of deeply nested dictionaries

### LINKED ISSUE #7734: "duckdb.TypeMismatchException: Mismatch Type Error" using dicts with different set of keys in python
### What happens?

In python duckdb module raises exception if  different sets of keys are using on 3rd level of dict.

The error exists on pip duckdb versions: 0.6.0, 0.7.0, 0.8.0
Version 0.5.0 raises Segmentation fault
Version 0.4.0 works fine 

### To Reproduce

This code 
```python
import duckdb
import pandas as pd
con = duckdb.connect(database=':memory:')

d = [
    {'a': 
       {'b': {
          'x': 'A', 
          'y': 'B'}}},
    {'a': 
       {'b': {
          'x': 'A'}}}
]

con.register('tbl', pd.DataFrame(d))
con.execute("SELECT * FROM tbl").fetchdf()
```
raises exception: 
`duckdb.TypeMismatchException: Mismatch Type Error: Type STRUCT(x VARCHAR) does not match with STRUCT(x VARCHAR, y VARCHAR). Cannot cast STRUCTs of different size`

### OS:

Ubuntu 22.04

### DuckDB Version:

0.8.0

### DuckDB Client:

python

### Full Name:

Andrey Elkin

### Affiliation:

Mindsdb

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #7734

When converting dictionary we need to either output a STRUCT or a MAP, depending on the compatibility of the analyzed objects.

This wasn't done properly for nested structures, this PR fixes this for `list` and `dict` and adds tests for them.

### CODE REVIEW

File: src/include/duckdb/common/types.hpp [hunk 1]
```diff
@@ -434,7 +437,9 @@ struct EnumType{
 
 struct StructType {
 	DUCKDB_API static const child_list_t<LogicalType> &GetChildTypes(const LogicalType &type);
+	DUCKDB_API static child_list_t<LogicalType> &GetChildTypes(LogicalType &type);
 	DUCKDB_API static const LogicalType &GetChildType(const LogicalType &type, idx_t index);
+	DUCKDB_API static LogicalType &GetChildType(LogicalType &type, idx_t index);
```
Comment (Mytherin) [inline src/include/duckdb/common/types.hpp:442]: We try to keep types immutable - could we not create a new struct instead of modifying an existing struct in-place?

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! LGTM - one comment:

**Comment by Mytherin** [comment]
Thanks!
