### PR TITLE
Throw when trying to consume over 128 byte decimals

### LINKED ISSUE #9201: pyarrow decimal256 values are being lost
### What happens?

When using duckdb to query pyarrow tables, pyarrow decimal256 type values are lost and zero value is returned instead. But the same values inside pyarrow decimal128 type are not affected.

### To Reproduce

```python
from decimal import Decimal

import duckdb
import pyarrow as pa

print(duckdb.__version__)
print(pa.__version__)

# DECIMAL256 VALUES ARE BEING LOST

pa_decimal256 = pa.Table.from_pylist(
    [{"data": Decimal("100.00")} for _ in range(4)],
    pa.schema([("data", pa.decimal256(12, 4))]),
)
print(pa_decimal256.to_pylist())
with duckdb.connect() as conn:
    print(conn.execute("select * from pa_decimal256;").arrow().to_pylist())

# DECIMAL128 VALUES ARE CORRECT

pa_decimal128 = pa.Table.from_pylist(
    [{"data": Decimal("100.00")} for _ in range(4)],
    pa.schema([("data", pa.decimal128(12, 4))]),
)
print(pa_decimal128.to_pylist())
with duckdb.connect() as conn:
    print(conn.execute("select * from pa_decimal128;").arrow().to_pylist())
```

Output, for me:

```text
0.9.0
13.0.0
[{'data': Decimal('100.0000')}, {'data': Decimal('100.0000')}, {'data': Decimal('100.0000')}, {'data': Decimal('100.0000')}]
[{'data': Decimal('100.0000')}, {'data': Decimal('0.0000')}, {'data': Decimal('100.0000')}, {'data': Decimal('0.0000')}]
[{'data': Decimal('100.0000')}, {'data': Decimal('100.0000')}, {'data': Decimal('100.0000')}, {'data': Decimal('100.0000')}]
[{'data': Decimal('100.0000')}, {'data': Decimal('100.0000')}, {'data': Decimal('100.0000')}, {'data': Decimal('100.0000')}]
```

### OS:

x86_64 GNU/Linux

### DuckDB Version:

0.9.0

### DuckDB Client:

Python

### Full Name:

Jeet Parekh

### Affiliation:

self

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by pdet**
Fix: #9201

### CODE REVIEW

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! LGTM - minor comments:

File: src/function/table/arrow.cpp [hunk 1]
```diff
@@ -42,8 +42,25 @@ static unique_ptr<ArrowType> GetArrowLogicalTypeNoDictionary(ArrowSchema &schema
 		return make_uniq<ArrowType>(LogicalType::DOUBLE);
 	} else if (format[0] == 'd') { //! this can be either decimal128 or decimal 256 (e.g., d:38,0)
 		std::string parameters = format.substr(format.find(':'));
-		uint8_t width = std::stoi(parameters.substr(1, parameters.find(',')));
-		uint8_t scale = std::stoi(parameters.substr(parameters.find(',') + 1));
+		// Find the positions of the commas
+		size_t pos1 = parameters.find(',');           // Position of the first comma
+		size_t pos2 = parameters.find(',', pos1 + 1); // Position of the second comma
+
```
Comment (Tishj) [inline src/function/table/arrow.cpp:48]: `D_ASSERT(pos1 != std::string::npos)`
`D_ASSERT(pos2 != std::string::npos)`

**Review by Tishj — APPROVED** [review]
Looks good!

File: src/function/table/arrow.cpp [hunk 2]
```diff
@@ -42,8 +42,25 @@ static unique_ptr<ArrowType> GetArrowLogicalTypeNoDictionary(ArrowSchema &schema
 		return make_uniq<ArrowType>(LogicalType::DOUBLE);
 	} else if (format[0] == 'd') { //! this can be either decimal128 or decimal 256 (e.g., d:38,0)
 		std::string parameters = format.substr(format.find(':'));
```
Comment (Mytherin) [inline src/function/table/arrow.cpp:44]: These format strings come to us from an external source, so I think it would make sense to be defensive here. We never know if some library could produce just `d` as a schema. Could we check that `format.find(':')` and `parameters.find(',')` return valid positions and throw if they do not?

Comment (Mytherin) [reply src/function/table/arrow.cpp:44]: Perhaps using `StringUtil::Split` is easier to use in a defensive way since then you don't need to do all this arithmetic on string positions which is somewhat error prone

**Comment by Mytherin** [comment]
> @Mytherin I think the errors are related to secrets, maybe we can restart the CI?

Restarting won't fix the CI since these issues are present in the `main` branch at the time when this PR was opened

File: src/function/table/arrow.cpp (hunk 2 above)
Comment (pdet) [reply src/function/table/arrow.cpp:44]: Excellent idea

**Comment by Mytherin** [comment]
Thanks!
