### PR TITLE
Fix #9456 and improve Deliminator

### LINKED ISSUE #9456: EXISTS operator returns NULL when multiple predicates are present
### What happens?

EXISTS operator returns NULL. The documentation says it should only return `true` or `false`.

### To Reproduce

create table u(u0 int, u1 int);
create table t(t0 int, t1 int);
insert into u values(1, 10);
insert into t values(1, 11);
insert into u values(null, 20);
insert into t values(null, 21);
SELECT t0, t1, EXISTS (SELECT * FROM u WHERE u0 = t0 AND u1 < t1) FROM t;

### OS:

arm64

### DuckDB Version:

0.9.1

### DuckDB Client:

CLI

### Full Name:

Deepak Majeti

### Affiliation:

IBM

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by lnkuiper**
Fixes the Deliminator bug found in #9456 and adds functionality to switch from `JoinType::SINGLE` to `JoinType::LEFT` if we can determine that the RHS is de-duplicated already by an aggregate, allowing us to flip the build and probe sides.

This removes `JoinType::SINGLE` from TPC-H Q17 and Q20.

### CODE REVIEW

File: src/optimizer/deliminator.cpp [hunk 1]
```diff
@@ -294,4 +365,55 @@ bool Deliminator::RemoveInequalityJoinWithDelimGet(LogicalComparisonJoin &delim_
...
+void Deliminator::TrySwitchSingleToLeft(LogicalComparisonJoin &delim_join) {
+	D_ASSERT(delim_join.join_type == JoinType::SINGLE);
+
+	// Collect RHS bindings
+	vector<ColumnBinding> join_bindings;
+	for (const auto &cond : delim_join.conditions) {
+		if (!IsEqualityJoinCondition(cond)) {
+			return;
+		}
+		if (cond.right->type != ExpressionType::BOUND_COLUMN_REF) {
```
Comment (Tmonster) [inline src/optimizer/deliminator.cpp:377]: why do we only get the right conditions? Isn't it possible that we have a left delim join here and we should get the bindings from the left side?

Edit: It's because single joins inherently join right delim joins

File: src/optimizer/deliminator.cpp [hunk 2]
```diff
@@ -294,4 +365,55 @@ bool Deliminator::RemoveInequalityJoinWithDelimGet(LogicalComparisonJoin &delim_
...
+			return;
+		}
+		auto &colref = cond.right->Cast<BoundColumnRefExpression>();
+		join_bindings.emplace_back(colref.binding);
+	}
+
+	// Now try to find an aggr in the RHS such that the join_column_bindings is a superset of the groups
+	reference<LogicalOperator> current_op = *delim_join.children[1];
+	while (current_op.get().type != LogicalOperatorType::LOGICAL_AGGREGATE_AND_GROUP_BY) {
```
Comment (Tmonster) [inline src/optimizer/deliminator.cpp:386]: this probably would never come up, but is it possible that there are multiple aggregates? If so, it's possible that we just check the first aggregate, but not the second.

File: test/issues/general/test_9456.test [hunk 3]
```diff
@@ -0,0 +1,54 @@
+# name: test/issues/general/test_9456.test
+# description: Issue 9456: EXISTS operator returns NULL when multiple predicates are present
```
Comment (Tmonster) [inline test/issues/general/test_9456.test:2]: Do you mean "exists operator **does not** return NULL when multiple predicates are present?"

**Review by Tmonster — COMMENTED** [review]
Nice! Just some comments. Still need to spend more time understanding everything about duplicate elimination though, so I couldn't give this a very thorough review

File: src/common/enums/join_type.cpp [hunk 4]
```diff
@@ -16,6 +17,34 @@ bool PropagatesBuildSide(JoinType type) {
...
+	case JoinType::SEMI:
+		return JoinType::RIGHT_SEMI;
+	case JoinType::ANTI:
+		return JoinType::RIGHT_ANTI;
+	case JoinType::RIGHT_SEMI:
+		return JoinType::SEMI;
+	case JoinType::RIGHT_ANTI:
+		return JoinType::ANTI;
+	default:
+		throw NotImplementedException("InverseJoinType for JoinType::%s", EnumUtil::ToString(type));
```
[the remark this answers is not in the document]
Comment (lnkuiper) [reply src/common/enums/join_type.cpp:44]: The thrown error will be "Not Implemented Error: InverseJoinType for JoinType::%s", so there's already a "no" in there!

Also, Inner is in the list!

File: src/include/duckdb/execution/operator/join/physical_delim_join.hpp [hunk 5]
```diff
@@ -12,16 +12,14 @@
 #include "duckdb/execution/physical_operator.hpp"
 
 namespace duckdb {
+
 class PhysicalHashAggregate;
 
-//! PhysicalDelimJoin represents a join where the LHS will be duplicate eliminated and pushed into a
-//! PhysicalColumnDataScan in the RHS.
+//! PhysicalRightDelimJoin represents a join where the RHS will be duplicate eliminated and pushed into a
```
[the remark this answers is not in the document]
Comment (lnkuiper) [reply src/include/duckdb/execution/operator/join/physical_delim_join.hpp:18]: It is, thanks!

File: src/optimizer/deliminator.cpp (hunk 1 above)
Comment (lnkuiper) [reply src/optimizer/deliminator.cpp:377]: To be able to flip the join from SINGLE to LEFT, we need to know whether the RHS has, for some reason, been de-duplicated, e.g., by a random aggregate, that's all.

The semantics of the SINGLE join are to not join LHS values with more than one RHS value, but if the RHS is de-duplicated, this is guaranteed even with the LEFT join.

File: test/issues/general/test_9456.test (hunk 3 above)
Comment (lnkuiper) [reply test/issues/general/test_9456.test:2]: I've copied this from the original issue, as we did for other issue test cases

File: src/execution/operator/join/physical_left_delim_join.cpp [hunk 6]
```diff
@@ -0,0 +1,138 @@
...
+// Pipeline Construction
+//===--------------------------------------------------------------------===//
+void PhysicalLeftDelimJoin::BuildPipelines(Pipeline &current, MetaPipeline &meta_pipeline) {
+	op_state.reset();
+	sink_state.reset();
+
+	auto &child_meta_pipeline = meta_pipeline.CreateChildMetaPipeline(current, *this);
+	child_meta_pipeline.Build(*children[0]);
+
+	if (type == PhysicalOperatorType::LEFT_DELIM_JOIN) {
```
[the remark this answers is not in the document]
Comment (lnkuiper) [reply src/execution/operator/join/physical_left_delim_join.cpp:124]: Good point, this was already there, but can actually be changed to an assert

File: src/optimizer/deliminator.cpp (hunk 2 above)
Comment (lnkuiper) [reply src/optimizer/deliminator.cpp:386]: Well-spotted, only one of the (possibly chained) aggregates would need to have a subset of the join columns as groups

**Comment by lnkuiper** [comment]
Thanks for the feedback @Tmonster !

I hadn't explained this in the PR message, as I decided to implement `PhysicalRightDelimJoin` after opening it, but the general idea is as follows:

Our original `PhysicalDelimJoin` (now `PhysicalLeftDelimJoin`) de-duplicated LHS values and pushed that into delim scans in the RHS. It also fully materialized the LHS (with duplicates) in a `ColumnDataCollection`.

The `PhysicalRightDelimJoin` flips the children, and de-duplicates the RHS, and pushes that into the delim scans in the LHS. This is the same but flipped, so far. The difference is that instead of materializing the RHS (with duplicates) in a `ColumnDataCollection`, we immediately build the HT (which we can do since this is now the right side, our build side). This saves one copy of the data and reduces memory pressure.

I also added a rule to the `Deliminator` optimizer that checks if there is a filter on the de-duplicated side, and if so, it will not try to remove all of the joins with delim scans on the other side. Usually, removing joins with delim scans is good, if we can, because they add no information. However, if there is a filter applied to the de-duplicated side, this means that joining with the delim scan also applies that filter, removing tuples from the other side early. This saves significant time on a few TPC-H queries.

**Review by Tmonster — APPROVED** [review]
looks good to me!

File: test/optimizer/deliminator_optimizer.test [hunk 7]
```diff
@@ -1,235 +0,0 @@
...
-PRAGMA explain_output = OPTIMIZED_ONLY
-
-# correlated any/all
-query II
-EXPLAIN SELECT i=ANY(SELECT i FROM integers WHERE i=i1.i) FROM integers i1 ORDER BY i
-----
-logical_opt	<!REGEX>:.*DELIM_JOIN.*
-
-query II
-EXPLAIN SELECT i=ALL(SELECT i FROM integers WHERE i=i1.i) FROM integers i1 ORDER BY i
```
[the remark this answers is not in the document]
Comment (lnkuiper) [reply test/optimizer/deliminator_optimizer.test:25]: We had `deliminator_optimizer.test` and `test_deliminator.test`, I've deleted the former and moved them to the latter.

File: test/optimizer/deliminator.test [hunk 8]
```diff
@@ -13,28 +13,66 @@ CALL dbgen(sf=0.0001);
...
-# Q 20
+# Q 17: if we remove the filters """ p_brand = 'Brand#23' AND p_container = 'MED BOX' """ we can remove the whole DELIM join
 query II
-explain SELECT s_name, s_address FROM supplier, nation WHERE s_suppkey IN ( SELECT ps_suppkey FROM partsupp WHERE ps_partkey IN ( SELECT p_partkey FROM part WHERE p_name LIKE 'forest%') AND ps_availqty > ( SELECT 0.5 * sum(l_quantity) FROM lineitem WHERE l_partkey = ps_partkey AND l_suppkey = ps_suppkey AND l_shipdate >= CAST('1994-01-01' AS date) AND l_shipdate < CAST('1995-01-01' AS date))) AND s_nationkey = n_nationkey AND n_name = 'CANADA' ORDER BY s_name;
+explain SELECT sum(l_extendedprice) / 7.0 AS avg_yearly FROM lineitem, part WHERE p_partkey = l_partkey AND l_quantity < (SELECT 0.2 * avg(l_quantity) FROM lineitem WHERE l_partkey = p_partkey);
 ----
-logical_opt	<!REGEX>:.*DELIM_JOIN.*
+logical_opt	<!REGEX>:.*LEFT_DELIM_JOIN.*
 
+# Q 20 shouldn't find SINGLE join, converted to LEFT
```
[the remark this answers is not in the document]
Comment (lnkuiper) [reply test/optimizer/deliminator.test]: Thanks, I've clarified the comment (and also fixed some tests while I was at it)

We're now keeping more DELIM joins than before, so that's why I've deleted some

File: src/execution/operator/join/physical_right_delim_join.cpp [hunk 9]
```diff
@@ -0,0 +1,141 @@
...
+	// we add an entry to the mapping of (PhysicalOperator*) -> (Pipeline*)
+	auto &state = meta_pipeline.GetState();
+	for (auto &delim_scan : delim_scans) {
+		state.delim_join_dependencies.insert(
+		    make_pair(delim_scan, reference<Pipeline>(*child_meta_pipeline.GetBasePipeline())));
+	}
+
+	// The rest of this function replicates the PhysicalJoin::BuildJoinPipelines,
+	// without building the RHS because we already build that in the Sink phase of this operator
+	state.AddPipelineOperator(current, *join);
```
Comment (Mytherin) [inline src/execution/operator/join/physical_right_delim_join.cpp:119]: Can we re-use the code from `PhysicalJoin::BuildJoinPipelines` and skip the build of the RHS with a boolean or so?

File: src/execution/physical_plan/plan_delim_join.cpp [hunk 10]
```diff
@@ -40,7 +50,40 @@ unique_ptr<PhysicalOperator> PhysicalPlanGenerator::PlanDelimJoin(LogicalCompari
...
+	    make_uniq<PhysicalLeftDelimJoin>(op.types, std::move(plan), delim_scans, op.estimated_cardinality);
+	// we still have to create the DISTINCT clause that is used to generate the duplicate eliminated chunk
+	delim_join->distinct = make_uniq<PhysicalHashAggregate>(context, delim_types, std::move(distinct_expressions),
+	                                                        std::move(distinct_groups), op.estimated_cardinality);
+	return std::move(delim_join);
+}
+
+unique_ptr<PhysicalOperator> PhysicalPlanGenerator::PlanRightDelimJoin(LogicalComparisonJoin &op) {
+	// first create the underlying join
+	auto plan = PlanComparisonJoin(op);
```
Comment (Mytherin) [inline src/execution/physical_plan/plan_delim_join.cpp:63]: Maybe this can be unified further as this looks like a lot of the same code between left/right with only the index differing?

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Looks good - some minor comments below:

**Comment by Mytherin** [comment]
Thanks!
