### PR TITLE
Properly deal with Star (*) expressions in `COPY ... (FORMAT JSON)`

### LINKED ISSUE #6305: Segmentation error with json extension and values clause
### What happens?

The python client crashes out with a segmentation fault when combining the `values` clause and the json extension.

### To Reproduce

/// python

```python
import duckdb

con = duckdb.connect()

con.execute("install json")
con.execute("load json")

con.execute("""
    copy (
        select * from values
        (uuid(), 10),
        (uuid(), 10),
        (uuid(), 15),
        (uuid(), 5)
        v (order_id, revenue)
    ) to 'query.json' (format json)
""")
```

In the above query, swapping the format to CSV / parquet yields a query that executes without a problem.

I'm not able to validate this on the prerelease (master branch) version because the `json` extension.

I also ran into a buffer error a while ago related to this that I was unable to find again.

### OS:

Mac OS

### DuckDB Version:

0.7.0

### DuckDB Client:

Python (3.11)

### Full Name:

James McNeill

### Affiliation:

Conjura

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by lnkuiper**
Fixes #6305

### CODE REVIEW

**Comment by jpmmcneill** [comment]
Cheers @lnkuiper. After looking at this, I dug into other behaviour with `*`, for example, what happens if there is something like

```sql
copy ( select col1 as dupe_col1, * from example_table) to 'out.json' (format json)
```

As my reading of this change is that such situations might not be handled.

A few observations:
1. When the json exists, the above works as usual expected (interestingly, new json blobs are appended in rather than the overwritten)!
2. When the json does not exist, the above seg faults.

**Comment by lnkuiper** [comment]
@jpmmcneill Thanks for the investigation! I discussed this with Mark, and my fix definitely does not cover all cases. The `*` expression also supports `EXCLUDE` and `REPLACE`, so I will try to come up with a more generic solution in this PR.

The data definitely should not be appended to an existing file, but if this happens it is an issue with the CSV writer, because we actually just convert the input to JSON then write using the CSV writer.

**Comment by jpmmcneill** [comment]
That makes sense @lnkuiper. It is possible that I hallucinated the appending, maybe I need more coffee in my duckdb mug 😄. Thank you very much

**Comment by lnkuiper** [comment]
After dealing with star expressions in a proper way, I've slightly changed the parameters to `read_json` to deal with different kinds of JSON formats. We now have
```
lines = ['true', 'false', 'auto']
json_format = ['records', 'array_of_records', 'values', 'array_of_values', 'auto']
```
This allows us to deal with more JSON found in the wild.

I've also fixed an issue where `BufferedJSONReader` did not properly read data from pipes.

File: extension/json/buffered_json_reader.cpp [hunk 1]
```diff
@@ -135,9 +138,23 @@ idx_t JSONFileHandle::ReadFromCache(const char *&pointer, idx_t &size, idx_t &po
...
 	}
+
 	return read_size;
 }
 
+idx_t JSONFileHandle::ReadInternal(const char *pointer, const idx_t requested_size) {
+	// Deal with reading from pipes
+	idx_t total_read_size = 0;
+	while (total_read_size < requested_size) {
+		auto read_size = file_handle->Read((void *)(pointer + total_read_size), requested_size - total_read_size);
```
Comment (Mytherin) [inline extension/json/buffered_json_reader.cpp:149]: This feels like something that should likely be handled in the `LocalFileSystem::Read` implementation. I imagine this might be causing silent issues in other readers as well?

**Review by Mytherin — APPROVED** [review]
Thanks for the fixes! LGTM. One comment:

**Comment by Mytherin** [comment]
Merging as-is, perhaps the read improvement can be generalized in a different PR
