### PR TITLE
Fix #20410: fix for RIGHT SEMI/ANTI - cannot fully label chain as found if there are non-equality predicates present in the join condition

### LINKED ISSUE #20410: ANTI JOIN produces wrong results in some cases
### What happens?

I think the ANTI JOIN is not working correctly in following example. I noticed the issue only happens when we materialize cte1. It seems the anti join is performed in a different way with the materialized CTE (RIGHT_ANTI), which leads to wrong results.

### To Reproduce

I ran this using your unittest framework on latest v1.4 and main.
With MATERIALIZED, we get empty result (which I think is wrong):
```sql
query II
WITH cte1 AS MATERIALIZED (
    SELECT
        'col1' AS col1,
        UNNEST(
            [TIMESTAMPTZ '2025-01-01 00:00:11+00', TIMESTAMPTZ '2025-01-01 00:00:41+00']
        ) AS col2
),
cte2 AS (
    SELECT
        'col1' AS col1,
        TIMESTAMPTZ '2025-01-01 00:00:40+00' AS col2,
        'col3' AS col3,
)
SELECT
    *
FROM
    cte1 ANTI
    JOIN cte2 ON cte1.col1 = cte2.col1
    AND cte1.col2 > cte2.col2;
----
```

Without MATERIALIZED, duckdb returns one row, as expected:
```sql
query II
WITH cte1 AS (
    SELECT
        'col1' AS col1,
        UNNEST(
            [TIMESTAMPTZ '2025-01-01 00:00:11+00', TIMESTAMPTZ '2025-01-01 00:00:41+00']
        ) AS col2
),
cte2 AS (
    SELECT
        'col1' AS col1,
        TIMESTAMPTZ '2025-01-01 00:00:40+00' AS col2,
        'col3' AS col3,
)
SELECT
    *
FROM
    cte1 ANTI
    JOIN cte2 ON cte1.col1 = cte2.col1
    AND cte1.col2 > cte2.col2;
----
col1	2025-01-01 00:00:11+00
```

### OS:

mac arm

### DuckDB Version:

latest 1.4 and main branches

### DuckDB Client:

cli

### Hardware:

_No response_

### Full Name:

Gishor Sivanrupan

### Affiliation:

Exaforce

### Did you include all relevant configuration (e.g., CPU architecture, Linux distribution) to reproduce the issue?

- [x] Yes, I have

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### PR DESCRIPTION
**Pull request by Mytherin**
Fixes https://github.com/duckdb/duckdb/issues/20410

This fixes an issue in the hash join implementation for `RIGHT_SEMI / RIGHT_ANTI`. In the previous implementation, upon finding a match, we would label the entire chain as having found that match. That is only correct when there are only equality predicates. If there are a mix of equality / inequality predicates, we need to call `ResolvePredicates` for every row in the hash table.

### CODE REVIEW

File: src/execution/join_hashtable.cpp [hunk 1]
```diff
@@ -1130,26 +1130,10 @@ void ScanStructure::NextRightSemiOrAntiJoin(DataChunk &keys) {
...
-				// Technically it is, but it does not matter, since the only value that can be written is "true"
-				Store<bool>(true, ptr + ht.tuple_size);
-				auto next_ptr = LoadPointer(ptr + ht.pointer_offset);
-				if (!next_ptr) {
-					break;
-				}
-				ptr = next_ptr;
-			}
+			auto idx = chain_match_sel_vector.get_index(i);
+			Store<bool>(true, ptrs[idx] + ht.tuple_size);
```
Comment (lnkuiper) [inline src/execution/join_hashtable.cpp]: Seems like the optimization is fully removed now. I added this optimization because RIGHT SEMI/ANTI became really slow if we have a build side with many duplicates (the original issue was a build side with 500k exact duplicates). Can we re-add the optimization for cases when there are only equality predicates?

Comment (Mytherin) [reply src/execution/join_hashtable.cpp]: Makes sense - I'll re-add it

Comment (lnkuiper) [reply src/execution/join_hashtable.cpp]: Thanks!
