### PR TITLE
Fixes issue #4123

### LINKED ISSUE #4123: Vector::SetValue not always casting when it should
#### What happens?
When determining whether or not to cast, SetValue only considers PhysicalType.
This can be problematic in case there is additional type_info present on the LogicalType.
(For a comprehensive list of the possible TypeInfo see PR #1851)

An example I came across is DECIMAL ignoring the width/scale, producing wrong results by not casting if the width/scale differ.
I have attempted to fix the issue by always comparing the LogicalTypes using the equality operator but this caused enough issues to demand a separate PR.  
So for now there is only a simple band aid fix targeting DECIMAL.

#### To Reproduce
There's not really a reproducible example to this issue, it's more a potential problem that should be addressed.
Since this has caused issues with DECIMAL, there's a high probability other issues could arise from this.

#### Notes
When attempting to patch this potential issue I have observed two (semi) big hurdles.
1. Value::CastAs(LogicalType& target_type) is not inheriting collation when target_type is VARCHAR, which caused this to infinite recurse:
```c++
	if (val.type() != GetType()) {
		SetValue(index, val.CastAs(GetType()));
		return;
	}
```
2. When not just comparing using `PhysicalType` but instead comparing using `LogicalTypeId` a lot of tests break that relied on there never needing to be an actual Cast performed if the PhysicalType was the same, such as:
```
Invalid Input Error: Failed to cast value: Unimplemented type for cast (BIGINT -> TIMESTAMP)
```

The second issue is only relevant if there is a difference in the way that data should be represented between two LogicalType's that share the same PhysicalType. To which I unfortunately don't know the answer yet.

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #4123 

## Problem

SetValue was only using PhysicalType, causing types that carry ExtraTypeInfo that might be relevant in casting to not convert properly, because the cast is not performed.
After changing this to comparing the entire LogicalType, I found that there are casts missing for types that share the same physical type, which makes sense because those should never need to be cast, so I don't compare LogicalTypeId anymore.

Then I discovered that GetValue does not properly inherit `alias` ExtraTypeInfo, and I figured that's probably irrelevant to casting, so I stopped comparing alias to determine if a cast should happen.
Which resulted in this:

```sql
SQL Query
SELECT add_point(({'x': 2, 'y': 3})::POINT, ({'x': 3, 'y': 4})::POINT)
================================================================================
Actual result:
Binder Error: No function matches the given name and argument types 'add_point(STRUCT(x INTEGER, y INTEGER), STRUCT(x INTEGER, y INTEGER))'. You might need to add explicit type casts.
        Candidate functions:
        add_point(POINT, POINT) -> POINT
```

It seems `alias` *is* relevant when casting.
This previously succeeded because no cast was performed, since POINT and STRUCT share a PhysicalType (not entirely sure still why this did not work anymore when I stopped comparing the alias)

## Changes

I eventually landed on adding the type_info of the Vector to all Values that come out of Vector::GetValue.
If there are other places this becomes relevant (Value inheriting a LogicalType) it might be better to handle this by adding an optional `const LogicalType &type` parameter to all Value constructors.

### CODE REVIEW

File: src/common/types/vector.cpp [hunk 1]
```diff
@@ -291,17 +291,10 @@ void Vector::Resize(idx_t cur_size, idx_t new_size) {
...
-	}
-	if (incoming.id() == LogicalTypeId::DECIMAL && incoming.id() == target.id()) {
-		//! Compare the type_info
-		return incoming != target;
-	}
-	return false;
+static bool ShouldCastValue(const LogicalType &left, const LogicalType &right) {
+	//! If two types share the same physical type and there is no extra type info
+	//  or the type info is the same, we can avoid casting
+	return (left.InternalType() != right.InternalType() || !left.EqualTypeInfo(right));
```
Comment (Mytherin) [inline src/common/types/vector.cpp:297]: Can't we just compare logical types here? Then we also don't need to export the `EqualTypeInfo` function.

File: src/common/types/vector.cpp [hunk 2]
```diff
@@ -403,7 +396,15 @@ void Vector::SetValue(idx_t index, const Value &val) {
...
-Value Vector::GetValueInternal(const Vector &v_p, idx_t index_p) {
+Value Vector::AttachTypeInfo(const Vector &v, Value &&val) {
+	if (!v.GetType().HasAlias()) {
+		return val;
+	}
+	val.type().CopyAuxInfo(v.GetType());
+	return val;
+}
+
+Value Vector::GetValue(const Vector &v_p, idx_t index_p) {
```
Comment (Mytherin) [inline src/common/types/vector.cpp:407]: Are these changes to `GetValue` necessary? It seems to do the same as the previous function but (in my opinion) in a less readable manner.

File: src/common/types/vector.cpp [hunk 3]
```diff
@@ -554,22 +555,13 @@ Value Vector::GetValueInternal(const Vector &v_p, idx_t index_p) {
...
 	}
 	default:
 		throw InternalException("Unimplemented type for value access");
 	}
 }
 
-Value Vector::GetValue(const Vector &v_p, idx_t index_p) {
-	auto value = GetValueInternal(v_p, index_p);
-	// set the alias of the type to the correct value, if there is a type alias
-	if (v_p.GetType().HasAlias()) {
```
Comment (Mytherin) [inline src/common/types/vector.cpp:567]: The alias inheriting already happens here, no?

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR!

> It seems alias is relevant when casting.

Alias is relevant to casting and function overloading because for user-defined types we want to be able to create multiple overloads of the same function signature, but with different types. e.g. we might want to support a `multiply(point, int)` and `multiply(vec2, int)`, even though both `point` and `vec2` are `struct(x int, y int)` internally. 

In the PR I am not sure why the changes to `GetValue` are necessary - the alias should already be inherited in the current code set, no? Am I missing something perhaps?

File: src/common/types/vector.cpp (hunk 2 above)
Comment (Tishj) [reply src/common/types/vector.cpp:407]: Yes I agree, the other solution was cleaner. I still need to clean this up from just being functional to also being a less intrusive change

File: src/common/types/vector.cpp (hunk 1 above)
Comment (Tishj) [reply src/common/types/vector.cpp:297]: If we compare LogicalTypes then we will be casting in a lot of cases where this isn't necessary, because of the LogicalTypeIds.
This probably wouldn't matter too much because I believe SetValue isn't used where performance is crucial, but a lot of those casts are not implemented.

File: src/common/types/vector.cpp (hunk 3 above)
Comment (Tishj) [reply src/common/types/vector.cpp:567]: It does and it doesn't.

Since we can also have nested vectors (dictionary for example), the TypeInfo might not be part of the DictionaryVector right?

File: src/common/types/vector.cpp (hunk 1 above)
Comment (Mytherin) [reply src/common/types/vector.cpp]: I think casting by physical type is likely hiding bugs. We shouldn't be able to use `SetValue` to set an `INT32` value in a `DATE` vector, for example.

File: src/common/types/vector.cpp (hunk 3 above)
Comment (Mytherin) [reply src/common/types/vector.cpp]: The `GetValue` itself should generally do this - I think an assertion here would be very appropriate, however (asserting that the type is equal to the type of the vector).

Comment (Tishj) [reply src/common/types/vector.cpp:567]: I've added the assertion and tested that it doesn't break (it did break when the typeid was AggregateState, hence the weird if statement). And I changed it to use CopyAuxInfo instead of altering/creating a new TypeInfo object

File: src/common/types/vector.cpp (hunk 1 above)
Comment (Tishj) [reply src/common/types/vector.cpp]: Except we also do this intentionally in some places, like the HistogramFinalizeFunction, we store the values internally as their physical types, and then create a Value from them, and set that into the result vector.

I'm not really sure how to go about this, other than maybe a boolean flag on SetValue `no_cast` to show intent.
