### PR TITLE
httpfs: Avoid corruptions with servers sending more data than asked for

### LINKED ISSUE #8908: Segmentation fault
### What happens?

```
select * from read_csv_auto('https://www.ebi.ac.uk/gwas/api/search/downloads/alternative');
```
results in:
```
zsh: segmentation fault  duckdb
```

### To Reproduce

```
❯ echo "select * from read_csv_auto('https://www.ebi.ac.uk/gwas/api/search/downloads/alternative');" | duckdb
zsh: done                echo  | 
zsh: segmentation fault  duckdb
❯ duckdb --version
-- Loading resources from /Users/seandavis/.duckdbrc
v0.8.2-dev3458 3d880e1053
```

### OS:

MacOS (M1)

### DuckDB Version:

v0.8.2-dev3458 3d880e1053

### DuckDB Client:

CLI

### Full Name:

Sean Davis

### Affiliation:

University of Colorado

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by carlopi**
Fixes #8930 and fixes #8908 (avoiding the fatal crash).

HTTP server are allowed to send back more data than asked for, and be somehow unreliably. In this case a GET request with a range headers gets more data than asked for, and with very big files we ended up overriding the current buffer.

This is an uncommon but legal behaviour, to properly handle this situation so we will have to improve logic elsewhere to properly handle this case.

### CODE REVIEW

**Comment by carlopi** [comment]
This is an improvement on current behaviour, so should be OK, but maybe we can do better either returning a more informative IOException.

Proper handling for this cases still to be done, since currently query will fail with:
```
Error: IO Error: Canceled error for HTTP GET Range to 'https://www.ebi.ac.uk/gwas/api/search/downloads/alternative'
```

Note that we can't just reallocate to a newer buffer in general, or at least that will require some deeper changes.

**Comment by pdet** [comment]
Ideally, we allocate buffers there, but that would require a significant code rewrite. 

As a workaround, I think the best solution would be to store the excess buffer in a cache at the `HTTPState` and properly manage it when calling the `GetRangeRequest`.

**Comment by Mause** [comment]
Do we need to make a similar fix in the fsspec wrapper as well? I think I used memcpy there too

File: extension/httpfs/httpfs.cpp [hunk 1]
```diff
@@ -329,6 +329,14 @@ unique_ptr<ResponseWrapper> HTTPFileSystem::GetRangeRequest(FileHandle &handle,
...
 			    if (buffer_out != nullptr) {
+				    if (data_length + out_offset > buffer_out_len) {
+					    // As of v0.8.2-dev4424 we might end up here when very big files are served from servers
+					    // that returns more data than requested via range header. This is an uncommon but legal
+					    // behaviour, so we have to improve logic elsewhere to properly handle this case.
+
+					    // To avoid corruption of memory, we bail out.
+					    return false;
+				    }
 				    memcpy(buffer_out + out_offset, data, data_length);
```
Comment (Mytherin) [inline extension/httpfs/httpfs.cpp:340]: What if instead of bailing out we just constrain the amount of data buffered to the buffer length, i.e. do something like:

```cpp
data_length = MinValue<idx_t>(data_length, buffer_out_len - data_length - out_offset);
```

That way we would just silently discard any data that is sent past the end of the buffer.

**Comment by carlopi** [comment]
Thanks @pdet for the suggestions and for taking a deep dive on this.

I will change this to throw a relevant error, pointing to the `SET force_download=true;` option

**Comment by Mytherin** [comment]
Thanks!
