### PR TITLE
[Python] Add support for +/- infinity `datetime` objects

### LINKED ISSUE #8143: TIMESTAMP field with infinity value breaks DuckDBPyRelation fetchall() method.
### What happens?

When trying to extract the Relation content via fetchall, I get the following error:
```
>>> flist.fetchall()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
duckdb.ConversionException: Conversion Error: Date out of range in timestamp conversion

```

### To Reproduce

Run the following Python code on console
```
import duckdb
con = duckdb.connect(':default:')
con.execute("""CREATE TABLE fset(
    filename VARCHAR,
    path VARCHAR[],
    origin VARCHAR,
    tags VARCHAR[],
    created TIMESTAMP,
    removed TIMESTAMP,
    hidden BOOLEAN,
    processed BOOLEAN,
    owner VARCHAR,
    changed_by VARCHAR,
    read_user VARCHAR[],
    read_group VARCHAR[],
    change_user VARCHAR[],
    change_group VARCHAR[])"""
)
con.execute("INSERT INTO fset SELECT * FROM read_json('file01.json', auto_detect=true, union_by_name=true)")
flist = con.sql("select * from fset")
con.sql("select removed from flist")
flist.fetchall()
```

file01.json
```
[
	{
		"filename" : "file0001.json",
		"path" : ["json"],
		"origin" : ["json"],
		"tags" : [ "tag01", "tag02" ],
		"created" : "2023-06-28 15:26:53.51-03",
		"removed" : "infinity",
		"hidden" : false,
		"processed" : true,
		"owner" : "user0001",
		"changed_by" : "user0001",
		"read_user" : ["user0001"],
		"read_group" : ["group0001"],
		"change_user" : ["user0001"],
		"change_group" : ["group0001"]
	}
]
```

### OS:

osx

### DuckDB Version:

duckdb==0.8.1

### DuckDB Client:

Python

### Full Name:

Caio Klein

### Affiliation:

SkyOne

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #8143 and #8214 

To fix 8214, we now add double quotes around the identifier when performing the internal lookup

To fix 8143 we now produce `datetime.datetime.max` and `datetime.date.max` values for `INFINITY` timestamps and dates respectively.
For `-INFINITY`  we produce the `.min` variant of the datetime object.

This also adds support for reading those values as `INFINITY` and `-INFINITY`

### CODE REVIEW

**Review by hawkfish — APPROVED** [review]

File: tools/pythonpkg/src/native/python_objects.cpp [hunk 1]
```diff
@@ -405,12 +448,31 @@ py::object PythonObject::FromValue(const Value &val, const LogicalType &type) {
 	case LogicalTypeId::TIMESTAMP_TZ: {
 		D_ASSERT(type.InternalType() == PhysicalType::INT64);
 		auto timestamp = val.GetValueUnsafe<timestamp_t>();
+
+		InfinityType infinity = InfinityType::NONE;
```
[the remark this answers is not in the document]
Comment (Tishj) [reply tools/pythonpkg/src/native/python_objects.cpp:452]: I don't think we do anything to prevent that no

File: tools/pythonpkg/tests/fast/api/test_attribute_getter.py [hunk 2]
```diff
@@ -51,4 +51,8 @@ def test_getitem_struct(self):
     def test_getattr_struct(self):
         rel = duckdb.sql("select {'a':5, 'b':6} as a, 5 as b")
         assert rel.a.a.fetchall()[0][0] == 5
-        assert rel.a.b.fetchall()[0][0] == 6
\ No newline at end of file
+        assert rel.a.b.fetchall()[0][0] == 6
+    
+    def test_getattr_spaces(self):
+        rel = duckdb.sql('select 42 as "hello world"')
+        assert rel['hello world'].fetchall()[0][0] == 42
```
[the remark this answers is not in the document]
Comment (Mytherin) [reply tools/pythonpkg/tests/fast/api/test_attribute_getter.py:58]: We should probably run a formatter/linter on Python code in the repo at this point, @Mause any thoughts on that?

[the remark this answers is not in the document]
Comment (Tishj) [reply tools/pythonpkg/tests/fast/api/test_attribute_getter.py:58]: I think Elliana suggested we should use black to format the python code

**Review by Mytherin — APPROVED** [review]
Thanks for the PR! LGTM. Perhaps @Mause wants to have a look as well?

File: tools/pythonpkg/tests/fast/api/test_attribute_getter.py (hunk 2 above)
[the remark this answers is not in the document]
Comment (Mause) [reply tools/pythonpkg/tests/fast/api/test_attribute_getter.py:58]: I actually have a pr with that I was looking to submit once the big python PR's had been merged (because otherwise we'll end up a bunch of conflicts)

File: tools/pythonpkg/src/native/python_objects.cpp [hunk 3]
```diff
@@ -434,6 +496,12 @@ py::object PythonObject::FromValue(const Value &val, const LogicalType &type) {
 
 		auto date = val.GetValueUnsafe<date_t>();
 		int32_t year, month, day;
+		if (!duckdb::Date::IsFinite(date)) {
+			if (date == date_t::infinity()) {
+				return py::module::import("datetime").attr("date").attr("max");
```
Comment (Mause) [inline tools/pythonpkg/src/native/python_objects.cpp:501]: Not caching the min/max values?

File: tools/pythonpkg/tests/fast/types/test_datetime_datetime.py [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+        ]:
+            # This query is not supported in core duckdb
+            with pytest.raises(duckdb.ConversionException):
+                con.execute(query).fetchall()
+        elif not positive and type in [
+                'TIMESTAMP_NS',
+                'TIMESTAMP_MS',
+                'TIMESTAMP_S'
+        ]:
+            # This query is not supported in core duckdb but doesn't deterministically produce an error
```
Comment (Mause) [inline tools/pythonpkg/tests/fast/types/test_datetime_datetime.py:40]: Any idea why it doesn't deterministically error?

**Review by Mause — COMMENTED** [review]
Looks good! Just a couple of minor comments

File: tools/pythonpkg/tests/fast/types/test_datetime_datetime.py (hunk 4 above)
Comment (Tishj) [reply tools/pythonpkg/tests/fast/types/test_datetime_datetime.py:40]: No clue, I think it has to do with an earlier under/overflow from an unchecked expression.
I noticed INFINITY and -INFINITY are not really implemented for TIMESTAMP_S/MS/NS, as I am having to check for the truncated versions of the `timestamp_t::infinity` value.
```c++
struct timestamp_ms_t : public timestamp_t { // NOLINT
	static constexpr timestamp_t infinity() {
		return timestamp_t(int64_t(NumericLimits<int64_t>::Maximum() / 1000) * 1000);
	}
	static constexpr timestamp_t ninfinity() {
		return timestamp_t(int64_t(-NumericLimits<int64_t>::Maximum() / 1000) * 1000);
	}
};
```

So it might be a result of that

File: tools/pythonpkg/src/native/python_objects.cpp (hunk 3 above)
Comment (Tishj) [reply tools/pythonpkg/src/native/python_objects.cpp:501]: I don't think our import cache does anything other than remove a few extra string comparisons.
We haven't measured this, but from working with the code for a while I am confident pybind caches the imports itself

File: src/include/duckdb/common/types/timestamp.hpp [hunk 5]
```diff
@@ -67,21 +67,49 @@ struct timestamp_t { // NOLINT
...
+	static constexpr timestamp_t infinity() {
+		return timestamp_t::infinity();
+	}
+	static constexpr timestamp_t ninfinity() {
+		return timestamp_t::ninfinity();
+	}
+};
+struct timestamp_ms_t : public timestamp_t { // NOLINT
+	static constexpr timestamp_t infinity() {
+		return timestamp_t(int64_t(NumericLimits<int64_t>::Maximum() / 1000) * 1000);
```
Comment (Mytherin) [inline src/include/duckdb/common/types/timestamp.hpp:99]: Let's always use `timestamp_t::infinity`.

@hawkfish could you perhaps have a look at this, it looks like there is an issue when casting infinity to non-microsecond timestamp types, e.g.:

```sql
D select 'infinity'::timestamp_ms as ts;
┌───────────────────────────┐
│            ts             │
│       timestamp_ms        │
├───────────────────────────┤
│ 294247-01-10 04:00:54.775 │
└───────────────────────────┘
```

**Comment by Mytherin** [comment]
Thanks!
