### PR TITLE
Attempt to fix column data update data race

### LINKED ISSUE #19688: Database is being invalidated with an error
### What happens?

I'm doing some concurrent updates on a table which has a JSON column. The database engine becomes invalidated with the following error after running it for a while.

`
time=2025-11-06T20:04:59.110-05:00 level=ERROR msg="[worker %d] update failed: %v" worker=7 err="FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.\nOriginal error: \"Unaligned fetch in validity and main column data for update\"\n\nStack Trace:\n\n/tmp/go-build1761955493/b001/exe/main(duckdb::Exception::ToJSON(duckdb::ExceptionType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x56) [0x1872a46]\n/tmp/go-build1761955493/b001/exe/main(duckdb::Exception::Exception(duckdb::ExceptionType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x14) [0x1872b04]\n/tmp/go-build1761955493/b001/exe/main(duckdb::FatalException::FatalException(duckdb::ExceptionType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x9) [0x18778d9]\n/tmp/go-build1761955493/b001/exe/main(duckdb::ErrorManager::InvalidatedDatabase(duckdb::ClientContext&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x1ba) [0xf548fa]\n/tmp/go-build1761955493/b001/exe/main() [0x9e25d6]\n/tmp/go-build1761955493/b001/exe/main(duckdb::ClientContext::PendingStatementOrPreparedStatement(duckdb::ClientContextLock&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, duckdb::unique_ptr<duckdb::SQLStatement, std::default_delete<duckdb::SQLStatement>, true>, duckdb::shared_ptr<duckdb::PreparedStatementData, true>&, duckdb::PendingQueryParameters const&)+0x65) [0xf716e5]\n/tmp/go-build1761955493/b001/exe/main(duckdb::ClientContext::PendingStatementOrPreparedStatementInternal(duckdb::ClientContextLock&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, duckdb::unique_ptr<duckdb::SQLStatement, std::default_delete<duckdb::SQLStatement>, true>, duckdb::shared_ptr<duckdb::PreparedStatementData, true>&, duckdb::PendingQueryParameters const&)+0x7f) [0xf7193f]\n/tmp/go-build1761955493/b001/exe/main(duckdb::ClientContext::PendingQueryPreparedInternal(duckdb::ClientContextLock&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, duckdb::shared_ptr<duckdb::PreparedStatementData, true>&, duckdb::PendingQueryParameters const&)+0x68) [0xf71ce8]\n/tmp/go-build1761955493/b001/exe/main(duckdb::ClientContext::PendingQuery(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, duckdb::shared_ptr<duckdb::PreparedStatementData, true>&, duckdb::PendingQueryParameters const&)+0x4c) [0xf71d7c]\n/tmp/go-build1761955493/b001/exe/main(duckdb::PreparedStatement::PendingQuery(std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, duckdb::BoundParameterData, duckdb::CaseInsensitiveStringHashFunction, duckdb::CaseInsensitiveStringEquality, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, duckdb::BoundParameterData> > >&, bool)+0xf4) [0xf71eb4]\n/tmp/go-build1761955493/b001/exe/main(duckdb_pending_prepared_internal(_duckdb_prepared_statement*, _duckdb_pending_result**, bool)+0x68) [0xf15678]\n/tmp/go-build1761955493/b001/exe/main(_cgo_74b48e76bd64_Cfunc_duckdb_pending_prepared+0x1b) [0xf06e7b]\n/tmp/go-build1761955493/b001/exe/main() [0xe1a464]\n"
`

### To Reproduce

Here is a Go program which can be used to recreate the issue.

[program.zip](https://github.com/user-attachments/files/23409853/program.zip)

### OS:

Linux

### DuckDB Version:

v1.4.1

### DuckDB Client:

Go

### Hardware:

_No response_

### Full Name:

Srimal Nishantha

### Affiliation:

Randoli Inc

### Did you include all relevant configuration (e.g., CPU architecture, Linux distribution) to reproduce the issue?

- [x] Yes, I have

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant data sets for reproducing the issue?

Yes

### PR DESCRIPTION
**Pull request by dentiny**
Closes https://github.com/duckdb/duckdb/issues/19688

I could reproduce the "invalidate database" exception almost 100% before the fix, which indicates there's race condition for column data update. 
This PR fixes by grabbing locks on fetch and update, so data and validity column could be fetched and updated atomically (currently the lock is grabbed inside of each update function).
I confirm previous failure doesn't reproduce by running it 100 times.

CC @taniabogatsch

### CODE REVIEW

**Comment by taniabogatsch** [comment]
Thanks @dentiny for looking into fixing this and opening the PR! Is that test you're mentioning something we could include in the PR?

**Comment by dentiny** [comment]
> Is that test you're mentioning something we could include in the PR?

Nope, the original issue contains golang program to reproduce (in the "To Reproduce" section)
I could check with multi-threaded C++ unit test though

Another thing I'm thinking is whether we need to introduce a [scoped_lock](https://en.cppreference.com/w/cpp/thread/scoped_lock.html), if the fix makes sense to you.

**Comment by taniabogatsch** [comment]
Ah, I was wondering if you had extracted a C++ test from the Go code. Maybe the multi-threaded unit test is a good idea or even better a test that uses our concurrent functionality in the SQLLogic tests (`concurrentloop`, etc.)? So that we can include a test to ensure we're not regressing here in the future.

**Comment by taniabogatsch** [comment]
The fix makes sense to me for fixing a race condition in the column data update code, yes, but I tagged Mark as I am not sure how fine-grained we want to be with the lock or whether we should lock in a different place.

**Comment by dentiny** [comment]
> Ah, I was wondering if you had extracted a C++ test from the Go code. 

I wrote a script to build duckdb from source, copy the static lib and link against golang program via `CGO_CFLAGS` & `CGO_LDFLAGS`.

> Maybe the multi-threaded unit test is a good idea

I add a C++ unit test, mostly because it's easy (for me) to control thread-level concurrency.

File: test/api/test_stress_update_issue_19688.cpp [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+
+constexpr int STRESS_TEST_NUM_WORKERS = 8;
+constexpr int STRESS_TEST_NUM_ROWS = 1000;
+
+void WorkerTask(DuckDB *db, int worker_id, std::atomic<int> *success_count, std::atomic<bool> *fatal_error_occurred) {
+	Connection con(*db);
+	std::mt19937 generator(worker_id); // Different seed per worker
+	std::uniform_int_distribution<int> val_distribution(0, 99999);
+
+	for (int id = 0; id < STRESS_TEST_NUM_ROWS; id++) {
```
Comment (Mytherin) [inline test/api/test_stress_update_issue_19688.cpp]: Could we turn these into sqllogictest tests using `concurentloop`?

**Review by Mytherin — COMMENTED** [review]
Thanks! LGTM. Should this target v1.4-andium instead of main?

Also, one more comment

**Comment by dentiny** [comment]
> Should this target v1.4-andium instead of main?

Just want to double check before I make changes.
The changeset in this PR seems to conflict with [the rework PR](https://github.com/duckdb/duckdb/pull/19761)

Part of your rework PR
image

Part of my fix PR
image

Not sure what's the general policy here?
I'm ok with preparing two PRs, one for main, one for v1.4, but we need to be careful when merging v1.4 to main.

**Comment by Mytherin** [comment]
We can prepare two separate PRs yes, I think that might be best

File: test/api/test_stress_update_issue_19688.cpp (hunk 1 above)
Comment (dentiny) [reply test/api/test_stress_update_issue_19688.cpp]: sure, updated

File: test/sql/update/test_stress_update_issue_19688.test [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+----
+1000
+
+# Launch 8 concurrent workers to perform UPDATE/DELETE/INSERT operations on the same rows
+concurrentloop threadid 0 8
+
+# Each worker operates on all 1000 rows
+loop i 0 1000
+
+statement maybe
```
Comment (dentiny) [inline test/sql/update/test_stress_update_issue_19688.test:30]: I hope the allowed exception is self-explanatory, basically I want to make sure if there's any error happening, it's not FATAL.

File: src/storage/table/standard_column_data.cpp [hunk 3]
```diff
@@ -133,6 +133,9 @@ void StandardColumnData::InitializeAppend(ColumnAppendState &state) {
 
 void StandardColumnData::AppendData(BaseStatistics &stats, ColumnAppendState &state, UnifiedVectorFormat &vdata,
                                     idx_t count) {
+	const lock_guard<mutex> standard_guard(update_lock);
+	const lock_guard<mutex> validity_guard(validity->update_lock);
```
Comment (Mytherin) [inline src/storage/table/standard_column_data.cpp:128]: Could you expand on why we need to grab the update lock as part of `AppendData`?

**Comment by taniabogatsch** [comment]
@dentiny - we should target this one against `v1.5`.

File: src/storage/table/standard_column_data.cpp (hunk 3 above)
Comment (dentiny) [reply src/storage/table/standard_column_data.cpp:128]: sorry for the delay! So the issue is
- We have two `ColumnData` to update together: `StandardColumnData` and `ValidityColumnData`
- The two updates should be grouped in an atomic operation

**Comment by dentiny** [comment]
> @dentiny - we should target this one against `v1.5`.

Sorry for the delay and thanks for the comment!
Due to the merge conflict, I plan to make a new PR on v1.5 branch if Mark think it's fine ([thread](https://github.com/duckdb/duckdb/pull/20334#issuecomment-3713597529))

File: src/storage/table/standard_column_data.cpp (hunk 3 above)
Comment (Mytherin) [reply src/storage/table/standard_column_data.cpp:128]: I understand that part in `Update` - but this function is `AppendData`. Why do we need to grab the update lock while appending here?

**Comment by Mytherin** [comment]
Yes, please make a new PR on the v1.5 branch

File: src/storage/table/standard_column_data.cpp (hunk 3 above)
Comment (dentiny) [reply src/storage/table/standard_column_data.cpp:128]: Thanks for the quick reply!

Here's my reasoning (sorry for the repeatition): we could have multiple threads making updates to column data and validity column data, for all possible write operations (whether it's update or append -- append operation also updates both items), we should grab a lock to make sure it's atomic.

As for why `update_lock`:
- I consider both `UpdateData` and `AppendData` as an "update" operation
- For the existing mutex inside of `ColumnData`, I only see `update_lock` to protect against write operation
- If you prefer to add another `append_lock`, or rename it as `write_lock`, I'm totally happy to make the change (if that's what you mean?)

And I just checked with the broken golang script in the original github issue with `AppendData` change reverted, I confirm the reported crash still persists.

**Comment by dentiny** [comment]
> Yes, please make a new PR on the v1.5 branch

Sure I will make a new PR if you think the change here makes sense :)

**Comment by Mytherin** [comment]
Yes, I think this is fine to go into v1.5.

**Comment by ftKnox** [comment]
I wanted to chime in here since I hit this issue in production with v1.4.3 using the duckdb-rs library performing queries of the below form.

```
INSERT INTO test
    (i,n,p,v,s,c,d)
VALUES
    ($1,$2,$3,$4,$5,$6,$7)
ON CONFLICT
    (i,c)
DO UPDATE SET
    d = json_merge_patch(test.d, EXCLUDED.d)
```

I ended up building and testing @dentiny's branch [hjiang/fix-column-update-data-race](https://github.com/duckdb/duckdb/pull/20334/commits/9560dd0ecccce4e0c533c663d9b9861bedc4d01b) and that does indeed seem to fix the database invalidation issue. At the same time, I was also seeing `TransactionContext Error: Failed to commit: PRIMARY KEY or UNIQUE constraint violation: duplicate key` that I thought may be related and or caused by this issue. However this primary key constraint failure still exists. Does this need a new issue or do you think this is related?

Thanks!

**Comment by dentiny** [comment]
> At the same time, I was also seeing TransactionContext Error: Failed to commit: PRIMARY KEY or UNIQUE constraint violation: duplicate key

Not quite sure about your query and schema: since without more information, it's possible that the broken PK/constraint come from other columns other than (i,c) (the one you handled).

**Comment by dentiny** [comment]
And FYI: I personally think for these types of data race we could do much better with compiler support, so I'm trying to add clang annotation into mutex and lock, still WIP https://github.com/dentiny/duckdb/pull/33

**Comment by ftKnox** [comment]
Yes sorry I didn't provide enough context. The schema looks like:

```
CREATE TABLE IF NOT EXISTS
test (
    i TEXT NOT NULL,
    n TEXT NOT NULL,
    p BIGINT NOT NULL,
    v NUMERIC NOT NULL,
    s TEXT NOT NULL,
    c TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    d JSON NOT NULL,
    PRIMARY KEY (i, c)
);
```

Here is some test log output. This happens immediately and then the errors are random at higher iterations. So it looks like some race condition, and I thought it was related to this particular race condition. For further context, the code actually uses both a local duckdb instance and simultaneously writes to postgres using the same schema and query. The postgres side works as expected.

```
running 1 test
thread:  7 -> upsert row failed -> insert count 0 -> ayjo6gw19vwzlq6wkfkkc8fv -> 2026-01-22 16:04:01 UTC -> TransactionContext Error: Failed to commit: PRIMARY KEY or UNIQUE constraint violation: duplicate key "ayjo6gw19vwzlq6wkfkkc8fv, 2026-01-22 16:04:01+00"
thread:  4 -> upsert row failed -> insert count 0 -> ayjo6gw19vwzlq6wkfkkc8fv -> 2026-01-22 16:04:01 UTC -> Constraint Error: Duplicate key "i: ayjo6gw19vwzlq6wkfkkc8fv, c: 2026-01-22 16:04:01+00" violates primary key constraint.
thread:  1 -> upsert row failed -> insert count 0 -> ayjo6gw19vwzlq6wkfkkc8fv -> 2026-01-22 16:04:01 UTC -> Constraint Error: Duplicate key "i: ayjo6gw19vwzlq6wkfkkc8fv, c: 2026-01-22 16:04:01+00" violates primary key constraint.
thread:  2 -> upsert row failed -> insert count 0 -> ayjo6gw19vwzlq6wkfkkc8fv -> 2026-01-22 16:04:01 UTC -> Constraint Error: Duplicate key "i: ayjo6gw19vwzlq6wkfkkc8fv, c: 2026-01-22 16:04:01+00" violates primary key constraint.
thread:  3 -> upsert row failed -> insert count 0 -> ayjo6gw19vwzlq6wkfkkc8fv -> 2026-01-22 16:04:01 UTC -> TransactionContext Error: Failed to commit: PRIMARY KEY or UNIQUE constraint violation: duplicate key "ayjo6gw19vwzlq6wkfkkc8fv, 2026-01-22 16:04:01+00"
thread:  9 -> upsert row failed -> insert count 0 -> ayjo6gw19vwzlq6wkfkkc8fv -> 2026-01-22 16:04:01 UTC -> Constraint Error: Duplicate key "i: ayjo6gw19vwzlq6wkfkkc8fv, c: 2026-01-22 16:04:01+00" violates primary key constraint.
thread:  5 -> upsert row failed -> insert count 0 -> ayjo6gw19vwzlq6wkfkkc8fv -> 2026-01-22 16:04:01 UTC -> TransactionContext Error: Failed to commit: PRIMARY KEY or UNIQUE constraint violation: duplicate key "ayjo6gw19vwzlq6wkfkkc8fv, 2026-01-22 16:04:01+00"
thread: 10 -> upsert row failed -> insert count 0 -> ayjo6gw19vwzlq6wkfkkc8fv -> 2026-01-22 16:04:01 UTC -> Constraint Error: Duplicate key "i: ayjo6gw19vwzlq6wkfkkc8fv, c: 2026-01-22 16:04:01+00" violates primary key constraint.
thread:  8 -> upsert row failed -> insert count 0 -> ayjo6gw19vwzlq6wkfkkc8fv -> 2026-01-22 16:04:01 UTC -> TransactionContext Error: Failed to commit: PRIMARY KEY or UNIQUE constraint violation: duplicate key "ayjo6gw19vwzlq6wkfkkc8fv, 2026-01-22 16:04:01+00"
```

**Comment by dentiny** [comment]
Hi @Mytherin I have rebased the PR against v1.5

**Comment by Mytherin** [comment]
Thanks!
