### PR TITLE
Parser Keyword Category Search

### LINKED ISSUE #13794: normalize_names does not work properly with `/dev/stdin`
### What happens?

Hi,
if I apply `normalize_names` to `/dev/stdin` duckdb normalizes the field `text` to `_text`.

It should remain `text`.

### To Reproduce

To reproduce

```
printf "name,text\nJohn,ipsum\n" | duckdb -line -c "select * from read_csv_auto('/dev/stdin',normalize_names=true);"
```

It gives in output

```
_name = John
_text = ipsum
```

### OS:

Debian 12

### DuckDB Version:

v1.0.0 1f98600c2c

### DuckDB Client:

cli

### Hardware:

_No response_

### Full Name:

Andrea Borruso

### Affiliation:

onData

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by pdet**
This PR extends the keyword search from the parser to take an optional parameter with matching categories.

Is currently used to  normalize CSV column names names that match either reserved or type func keywords.

Fix: #13794

### CODE REVIEW

File: third_party/libpg_query/include/parser/parser.hpp [hunk 1]
```diff
@@ -29,7 +29,7 @@ typedef enum PGBackslashQuoteType {
 /* Primary entry point for the raw parsing functions */
 PGList *raw_parser(const char *str);
 
-bool is_keyword(const char *str);
+bool is_keyword(const char *str, const std::vector<duckdb_libpgquery::PGKeywordCategory> &type_filter = {});
```
Comment (Mytherin) [inline third_party/libpg_query/include/parser/parser.hpp:32]: Can we replace this with returning the keyword category instead, and adding a `PG_KEYWORD_NONE` category? Then we don't need to pass in this vector and do the comparisons here

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Looks good - one comment

File: src/include/duckdb/parser/keyword_helper.hpp [hunk 2]
```diff
@@ -9,13 +9,14 @@
...
 #include "duckdb/common/common.hpp"
+#include "duckdb/parser/simplified_token.hpp"
 
 namespace duckdb {
 
 class KeywordHelper {
 public:
 	//! Returns true if the given text matches a keyword of the parser
-	static bool IsKeyword(const string &text);
+	static bool IsKeyword(const string &text, const vector<KeywordCategory> &filter_type = {});
```
Comment (Mytherin) [inline src/include/duckdb/parser/keyword_helper.hpp:19]: Can we bubble the keyword type up all the way, so that we have `KeywordHelper::KeywordCategory(const string &text)` - and `KeywordHelper::IsKeyword()` is essentially `KeywordHelper::KeywordCategory(text) != KeywordCategory::NONE`

Comment (pdet) [reply src/include/duckdb/parser/keyword_helper.hpp:19]: Ah, I had understood that you just wanted it out of the third-party

**Comment by Mytherin** [comment]
Thanks!

**Comment by aborruso** [comment]
Thank you very much
