### PR TITLE
Do not exit shell on Ctrl+C

### LINKED ISSUE #14906: Keyboard interrupt (ctrl-c) immediately kills DuckDB on Windows (PowerShell).
### What happens?

When I press ctrl-c, DuckDB immediately exits. However, I would prefer it to _never_ exit when I press ctrl-c. In other shells and REPLs, I use ctrl-c to clear the current line, etc. For example, bash, zsh, python, ipython. I've noticed that in Linux (WSL), pressing ctrl-c _twice_ causes DuckDB to exit. This is preferable, but still not ideal. (Normally one would use ctrl-d to exit a shell or REPL.)

### To Reproduce

Run `duckdb`, then press `ctrl-c` in Windows PowerShell.

### OS:

Windows 11

### DuckDB Version:

v1.1.3 19864453f7

### DuckDB Client:

CLI

### Hardware:

_No response_

### Full Name:

David Wales

### Affiliation:

South Western Sydney Primary Health Network

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by staticlibs**
This PR changes the Ctlr+C handling in the DuckDB shell. Currently typing Ctrl+C twice makes the whole process to exit. This is changed to print the message instead:

```
Interrupted, use Ctrl+D to exit
```

This behaviour follows what Python shell is doing (it prints `KeyboardInterrupt` on Ctrl+C).

The exit logic was used from the terminal input handler and also from the signal handler. ~~It is supposed that signal handler code path is not triggered after the terminal is initialized. Still, for consistency, the handling is changed on both code paths.~~ edit: the exit logic from the signal handler is restored, it is supposed to be triggered only if the running query cannot be interrupted.

Testing: tested manually on Linux and Windows.

Fixes: #14906

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks!

I think it makes sense to have `Ctrl+C` not kill the process - but I think the main reason this exists is that `Ctrl+C` gets sent as a signal, whereas `Ctrl+D` does not. As such, when doing an operation that hangs without an internal interrupt, we can still leave/kill the CLI. 

Maybe we can remove the kill in the main loop (i.e. in `ShellState::ProcessInput`) but leave the kill in the interrupt handler?

Alternatively - what would be nice is if we could move the execution to the background in some capacity, but that's a more involved rework. For example, we could then have Ctrl+C return control instantly always - but then if another query is run it would say `waiting for background query...` or so. That's much more of a redesign, though.

**Comment by staticlibs** [comment]
Thanks for the review!

Restored the process exit in the signal handler.

About the background execution, as I understand we need to run the query in a background thread for that. And this makes signal handling more involved, as we won't have control over which thread is receiving the `SIGINT`. So need to have a dedicated signal dispatcher thread. I'll file an issue for this for future.

File: tools/shell/shell.cpp [hunk 1]
```diff
@@ -784,6 +784,24 @@ string ShellState::EscapeCString(const string &str) {
 	return result;
 }
 
+/**
+ ** Uses non-buffered output calls (that are also signal-safe) to print the message.
+ */
+static void PrintCtrlDHint() {
+	string msg = "Interrupted, use Ctrl+D to exit\n";
+#if (defined(_WIN32) || defined(WIN32)) && !defined(_WIN32_WCE)
```
Comment (Mytherin) [inline tools/shell/shell.cpp]: Now that this is no longer happening during a signal we can just use `Print()`

Comment (staticlibs) [reply tools/shell/shell.cpp]: M, changing `PrintCtrlDHint()` to `Print("Interrupted, use Ctrl+D to exit\n")` in `ShellState::ProcessInput` does not work properly after the query is interrupted.

So the message is printed on Ctrl+C correctly before query is run. Then the query is run, interrupted by Ctrl+C, shell is given back to user. Subsequent Ctrl+C won't exit this shell (so it does not get to the signal hanlder), but it does not print the "Interrupted, use Ctrl+D to exit" message either, just prints empty line, until I run any query successfully.

This behaviour is the same on Linux and Windows. The problem does not happen with `PrintCtrlDHint()`. Something is wrong with buffered output after the query interrupt (from signal handler). I will do some more debugging on this.

Comment (Mytherin) [reply tools/shell/shell.cpp]: I think that's this line:

```
void ShellState::Print(PrintOutput output, const char *str, idx_t len) {
	if (seenInterrupt) {
		// no more printing after seeing an interrupt
		return;
	}
```

The `seenInterrupt` flag should be cleared

Comment (staticlibs) [reply tools/shell/shell.cpp]: Ah, that explains it. I updated the PR moving existing interrupt clearing logic to before the Ctrl+C handling.

**Comment by Mytherin** [comment]
Thanks!
