### PR TITLE
c-api: support decimal and prevent invalid type throws

### LINKED ISSUE #2853: C API : duckdb_value_date pass on exception instead of returning error state
#### What happens?
The C API function duckdb_value_date triggers an unhandled exception instead of returning an error state when passed an index to a column which is not a DATE type:
```
DB.Prepare('SELECT 1,2,3,?,DATE ''1992-09-20'',TIMESTAMP ''1992-09-20 11:30:00'';');
DB.BindString(1, 'True');
DB.ExecPrepared;
writeln('Date :  ' + DateToStr(DB.ValueAsDate(1,0)));
```
Triggers an unhandled exception:
```
An unhandled exception occurred at $00007FFEF5964F69:
EExternalException: External exception E06D7363
  $00007FFEF5964F69
  $00007FFEED756480
  $00007FFE91FE45B2
  $00007FFE922EA174
  $00007FFE922E8907
  $00007FFE922EB487
  $000000010001D90E  VALUEASDATE,  line 383 of duckdb.pas
  $0000000100001CAB  main,  line 25 of duckdtest.lpr
  $0000000100001E66
  $000000010000FF60
  $0000000100001710
  $00007FFEF7207034
  $00007FFEF8062651
```

#### To Reproduce
Source is FreePascal code.

#### Environment (please complete the following information):
 - OS: Windows 10
 - DuckDB Version: 0.3.1
 - DuckDB Client: Custom FreePascal code using the C-API

I has not been successful in building the Trunk and therefore have not tested this.

### PR DESCRIPTION
**Pull request by wangfenjin**
Use a trick to store the decimal data in order to save some memory, will allocate an extra row to store the decimal scale and width info so we don't need to have duplication in each row. Not sure if we have a better way to do this.

fix #2853 #2858

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR!

> Use a trick to store the decimal data in order to save some memory, will allocate an extra row to store the decimal scale and width info so we don't need to have duplication in each row. Not sure if we have a better way to do this.

I'm not such a big fan of this trick. It does not seem very clean to put what is essentially metadata (the width and the scale of the decimal) into the data itself. I think what needs to happen instead is that we create a new opaque object (e.g. `duckdb_logical_type`) that is the C equivalent of the LogicalType class in DuckDB.

This is in general required, since as we extend the C API to support all types that DuckDB supports we will need to be able to model more complex types such as lists, structs, maps, etc. A simple enum is not enough to model these complex types.

The `duckdb_type` enum can continue existing as only the enum (i.e. the equivalent of `LogicalTypeId`). We will simply need to add a new methods to be able to obtain the `duckdb_logical_type` as well, e.g.:

```c
duckdb_logical_type duckdb_column_logical_type(duckdb_result *result, idx_t col);
```

Together with functions that operate on the logical type, e.g.:

```c
int8_t duckdb_decimal_get_width(duckdb_logical_type type);
int8_t duckdb_decimal_get_scale(duckdb_logical_type type);
```

Then the decimal functions could require these as parameters:

```c
double duckdb_decimal_to_double(duckdb_hugeint value, int8_t width, int8_t scale);
```

**Comment by wangfenjin** [comment]
@Mytherin Please help review the code when you got time

File: src/include/duckdb.h [hunk 1]
```diff
@@ -162,6 +171,7 @@ typedef struct {
 	char *__deprecated_name;
 #endif
 	void *internal_data;
+	void *duckdb_logical_type;
```
Comment (Mytherin) [inline src/include/duckdb.h:174]: The current idea with the deprecated flags is that we migrate to storing all of the data for the `duckdb_column` class inside the `internal_data` object. This is cleaner since it means we don't need to alter a struct in the header to add new fields. Altering a struct in the header is problematic since it breaks backwards compatibility during linking, as the sizes of objects on e.g. the stack changes which can cause nasty crashes. 

The `internal_data` object can be a C++ class that holds C++ objects, and should be defined in `src/include/duckdb/main/capi_internal.hpp`. For example, similarly to the `DatabaseData` and `AppenderWrapper` objects, there should be a `DuckDBColumnData` object.

This object can then hold the LogicalType as-is, and adding new fields to this will be easy as well.

Could you perhaps have a look at creating the `internal_data` object like this and using it to store the LogicalType?

File: src/main/capi/result-c.cpp [hunk 2]
```diff
@@ -53,6 +55,11 @@ duckdb_state duckdb_translate_result(MaterializedQueryResult *result, duckdb_res
 	// zero initialize the columns (so we can cleanly delete it in case a malloc fails)
 	memset(out->__deprecated_columns, 0, sizeof(duckdb_column) * out->__deprecated_column_count);
 	for (idx_t i = 0; i < out->__deprecated_column_count; i++) {
+		BufferedSerializer serializer;
+		result->types[i].Serialize(serializer);
+		BufferedDeserializer deserializer(serializer);
+		auto cloned_type = new LogicalType(LogicalType::Deserialize(deserializer));
```
Comment (Mytherin) [inline src/main/capi/result-c.cpp:61]: Is there a reason for requiring a deep-copy? Wouldn't a normal copy suffice? Note that logical types are immutable, so having shared references to them should in never cause problems.

**Review by Mytherin — COMMENTED** [review]
Thanks for the updates! Apologies for the delay in reviewing. Looks a lot better now. Comments:

File: src/include/duckdb.h (hunk 1 above)
Comment (wangfenjin) [reply src/include/duckdb.h:174]: OK

File: src/main/capi/result-c.cpp (hunk 2 above)
Comment (wangfenjin) [reply src/main/capi/result-c.cpp:61]: because if I don’t deep copy it will double free

Comment (Mytherin) [reply src/main/capi/result-c.cpp:61]: That should not happen, logical types are copied using the regular copy constructor all over the place. Are you sure this is not masking a different problem?

File: src/include/duckdb.h (hunk 1 above)
Comment (wangfenjin) [reply src/include/duckdb.h]: I had move LogicalType into internal_data.

What's our plan to the __deprecated* fields? Should I also define them in the internal_data?

File: src/main/capi/result-c.cpp (hunk 2 above)
Comment (wangfenjin) [reply src/main/capi/result-c.cpp]: Delete the deep code logic, previously I think I miss use the column-data and result

File: src/include/duckdb.h (hunk 1 above)
Comment (Mytherin) [reply src/include/duckdb.h]: For now the deprecated fields can remain in the header. I am planning on doing some restructuring of the C API in the future which includes removing the deprecated fields and moving them into the internal_data amongst others, which is why they are deprecated.

**Comment by wangfenjin** [comment]
All tests should be fine, the failed CI not related to this change

**Comment by Mytherin** [comment]
Thanks!
