### PR TITLE
[Python] Keep referenced Python objects alive

### LINKED ISSUE #11387: Incorrect/inconsistent replacement scans behavior
### What happens?

The replacement scans do not work properly once the relation object is passed to function. 

```python
def build_rel_upon_rel(conn: duckdb.DuckDBPyConnection, rel: duckdb.DuckDBPyRelation):
    return conn.sql("select * from rel")

db = duckdb.connect()
rel_fetch_schema = db.sql("select * from information_schema.schemata")
new_rel = build_rel_upon_rel(rel_fetch_schema)
```

This won't work unless the `rel` variable is explicitly defined **OUTSIDE** the function call. That is:

```python

rel_fetch_schema = db.sql("select * from information_schema.schemata")
rel = rel_fetch_schema
new_rel = build_rel_upon_rel(rel_fetch_schema) 
# You didn't see wrong, not even rel itself, now passing the rel_fetch_schema also works!
```

### To Reproduce

```python
import duckdb


def build_rel_on_rel_unamed(conn: duckdb.DuckDBPyConnection, rel: duckdb.DuckDBPyRelation):
    return conn.sql("select * from rel")


def build_rel_on_rel_named(conn: duckdb.DuckDBPyConnection, rel: duckdb.DuckDBPyRelation = None):
    return conn.sql("select * from rel")


def invocation_1(db: duckdb.DuckDBPyConnection, ):
    schemas = db.sql("select * from information_schema.schemata")
    try:
        result = build_rel_on_rel_unamed(db, schemas).fetchall()
    except Exception as e:
        print(f"\n\nError occurred with invocation_1: {e}")
        return None

    print(f"Succeeded with invocation_1")
    return result


def invocation_2(db: duckdb.DuckDBPyConnection, ):
    schemas = db.sql("select * from information_schema.schemata")
    other_name = schemas
    try:
        result = build_rel_on_rel_unamed(db, other_name).fetchall()
    except Exception as e:
        print(f"\n\nError occurred with invocation_2: {e}")
        return None

    print(f"Succeeded with invocation_2")
    return result


def invocation_3(db: duckdb.DuckDBPyConnection, ):
    schemas = db.sql("select * from information_schema.schemata")
    rel = schemas
    try:
        result = build_rel_on_rel_unamed(db, schemas).fetchall()
    except Exception as e:
        print(f"\n\nError occurred with invocation_3: {e}")
        return None

    print(f"Succeeded with invocation_3")
    return result


def test_1_2_3():
    db = duckdb.connect()
    assert invocation_1(db) is None
    assert invocation_2(db) is None
    assert invocation_3(db) is not None
    db.close()


def test_2_1_3():
    db = duckdb.connect()
    assert invocation_2(db) is None
    assert invocation_1(db) is None
    assert invocation_3(db) is not None
    db.close()


def test_3_2_1():
    db = duckdb.connect()
    assert invocation_3(db) is not None
    assert invocation_2(db) is None
    assert invocation_1(db) is None
    db.close()


def test_3_1_2():
    db = duckdb.connect()
    assert invocation_3(db) is not None
    assert invocation_1(db) is None
    assert invocation_2(db) is None
    db.close()


def invocation_4(db: duckdb.DuckDBPyConnection, ):
    schemas = db.sql("select * from information_schema.schemata")
    try:
        result = build_rel_on_rel_named(db, rel=schemas).fetchall()
    except Exception as e:
        print(f"\n\nError occurred with invocation_4: {e}")
        return None

    print(f"Succeeded with invocation_4")
    return result


def invocation_5(db: duckdb.DuckDBPyConnection, ):
    schemas = db.sql("select * from information_schema.schemata")
    other_name = schemas
    try:
        result = build_rel_on_rel_unamed(db, rel=other_name).fetchall()
    except Exception as e:
        print(f"\n\nError occurred with invocation_5: {e}")
        return None

    print(f"Succeeded with invocation_5")
    return result


def invocation_6(db: duckdb.DuckDBPyConnection, ):
    schemas = db.sql("select * from information_schema.schemata")
    rel = schemas
    try:
        result = build_rel_on_rel_unamed(db, rel=schemas).fetchall()
    except Exception as e:
        print(f"\n\nError occurred with invocation_6: {e}")
        return None

    print(f"Succeeded with invocation_6")
    return result


def test_4_5_6():
    db = duckdb.connect()
    assert invocation_4(db) is None
    assert invocation_5(db) is None
    assert invocation_6(db) is not None
    db.close()


def test_6_5_4():
    db = duckdb.connect()
    assert invocation_6(db) is not None
    assert invocation_5(db) is None
    assert invocation_4(db) is None
    db.close()


def test_5_4_6():
    db = duckdb.connect()
    assert invocation_5(db) is None
    assert invocation_4(db) is None
    assert invocation_6(db) is not None
    db.close()


if __name__ == "__main__":
    test_1_2_3()
    test_3_2_1()
    test_2_1_3()
    test_3_1_2()

    test_4_5_6()
    test_6_5_4()
    test_5_4_6()
```

### OS:

macOS 13.5.2 (22G91)

### DuckDB Version:

0.10.1

### DuckDB Client:

Python

### Full Name:

Hank Zhong

### Affiliation:

www.shanshu.ai

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #11387, #11224

ExternalDependency objects are created in the ReplacementScan, which runs as part of the bind phase.
When the DuckDBPyRelation is created, it first creates a Relation, this gets bound to verify the correctness and also to collect the names+types that are returned from the query.

The ExternalDependency objects were not being forwarded anywhere and they died together with the rest of the bind data that was not used.

As a result, the objects that the query has discovered during Bind were not being kept alive by us, and would thus get deleted if no longer referenced (as evidenced by the referenced issue, where the DataFrame has gone out of scope)

## Internal details

ExternalDependency is now a collection of DependencyItems, which is a pure virtual class that can hold anything.
We implement the PythonDependencyItem to hold the RegisteredObject.

When the QueryRelation is created we add an ExternalDependency into the TableRef, when we bind it, we create a Copy() which also gets the ExternalDependency.
During the ReplacementScan this gets populated with the objects we depend on (and also the ones we have created)

This now means that the objects are guaranteed to stay alive as long as the DuckDBPyRelation is alive, and because it's the TableRef that is responsible for this, this extends to VIEWs created from the Relation.

### ReplacementScanInput

```c++
struct ReplacementScanInput {
public:
	ReplacementScanInput(TableRef &ref, const string &table_name) : ref(ref), table_name(table_name) {
	}

public:
	TableRef &ref;
	const string &table_name;
};
```

The `TableRef` is provided to the ReplacementScan function, in the Python client we use this as a cache for the replacement scan. When the object exists in the cache (ExternalDependency) it gets used, otherwise we perform the scan, for a successful scan we populate the cache.

### TableFunctionBindInput

The `TableFunctionRef` is provided to the TableFunction's bind function, this gives it the chance to take a reference on the DependencyItem(s) created during replacement scan, making sure it stays alive during execution.

This is used for the `arrow_scan`, in the replacement scan we create a `PythonTableArrowArrayStreamFactory` that needs to stay alive during execution.

### CODE REVIEW

**Comment by Tishj** [comment]
I am just now realizing that this will not work:
```py
def test_lifetime():
	def create_join(conn):
		df1 = pd.DataFrame({'a': ['a', 'b', 'c'], 'b': [1,2,3]})
		df2 = pd.DataFrame({'a': ['a', 'b', 'c'], 'b': [4,5,6]})

		return conn.sql("select * from df1 JOIN df2 USING (a, a)")

	con = duckdb.connect()
	rel = create_join(con)
	rel.show()
```

We are expecting the query_node to be a SelectNode, which is not always the case

**Comment by Tishj** [comment]
Realization I just had..

This makes it so that we keep the objects alive, so we can find them .. but we will only look for them when a replacement scan is triggered.

```py
import duckdb
import pandas as pd

def return_rel(conn):
	df = pd.DataFrame({'a': [1,2,3]})
	rel = conn.sql("select * from df")
	return rel

conn = duckdb.connect()
rel = return_rel(conn)
#conn.execute("create table df as select * from unnest([4,5,6])")
res = rel.fetchall()
print(res)
```
```
[(1,), (2,), (3,)]
```

Uncommented `conn.execute("create table df as select * from unnest([4,5,6])")`:
```
[(4,), (5,), (6,)]
```

File: src/planner/binder/tableref/bind_basetableref.cpp [hunk 1]
```diff
@@ -46,30 +46,35 @@ static bool TryLoadExtensionForReplacementScan(ClientContext &context, const str
...
+		if (replacement_function->type == TableReferenceType::TABLE_FUNCTION) {
+			auto &table_function = replacement_function->Cast<TableFunctionRef>();
+			table_function.column_name_alias = ref.column_name_alias;
+		} else if (replacement_function->type == TableReferenceType::SUBQUERY) {
+			auto &subquery = replacement_function->Cast<SubqueryRef>();
+			subquery.column_name_alias = ref.column_name_alias;
+		} else {
+			throw InternalException("Replacement scan should return either a table function or a subquery");
 		}
+		auto copied_replacement = replacement_function->Copy();
```
Comment (Tishj) [inline src/planner/binder/tableref/bind_basetableref.cpp:74]: Github proves once again how bad it is at resolving diffs, this is just using early return
The only difference is here, where we make a copy of the replacement scan result to bind, and then move the original into the BoundTableRef after (perhaps we want to check that the Bind succeeds though..)

**Comment by Tishj** [comment]
@Mytherin I undid "slightly hacky solution", I think we should try to merge this as-is and push the fix for this:
```py
    def test_replacement_scan_caching(self, duckdb_cursor):
        def return_rel(conn):
            df = pd.DataFrame({'a': [1, 2, 3]})
            rel = conn.sql("select * from df")
            return rel

        rel = return_rel(duckdb_cursor)
        # FIXME: this test should fail in the future
        # The correct answer here is [1,2,3], as that is the 'df' that was visible during creation of the Relation
        duckdb_cursor.execute("create table df as select * from unnest([4,5,6])")
        res = rel.fetchall()
        assert res == [(4,), (5,), (6,)]
```

separately

File: src/function/table/read_csv.cpp [hunk 2]
```diff
@@ -352,7 +352,9 @@ void ReadCSVTableFunction::RegisterFunction(BuiltinFunctions &set) {
 	set.AddFunction(MultiFileReader::CreateFunctionSet(ReadCSVTableFunction::GetAutoFunction()));
 }
 
-unique_ptr<TableRef> ReadCSVReplacement(ClientContext &context, const string &table_name, ReplacementScanData *data) {
+unique_ptr<TableRef> ReadCSVReplacement(ClientContext &context, ReplacementScanInput &input,
+                                        ReplacementScanData *data) {
```
Comment (Mytherin) [inline src/function/table/read_csv.cpp:356]: While we're at it can we turn this into an `optional_ptr`?

File: src/main/relation/query_relation.cpp [hunk 3]
```diff
@@ -2,14 +2,31 @@
...
+		ref.external_dependency = make_shared_ptr<ExternalDependency>();
+	}
+}
+
 QueryRelation::QueryRelation(const shared_ptr<ClientContext> &context, unique_ptr<SelectStatement> select_stmt_p,
                              string alias_p)
     : Relation(context, RelationType::QUERY_RELATION), select_stmt(std::move(select_stmt_p)),
       alias(std::move(alias_p)) {
+	auto &ref = *select_stmt->node->Cast<SelectNode>().from_table;
+	InitializeTableRefDependency(ref);
```
Comment (Mytherin) [inline src/main/relation/query_relation.cpp:29]: Note: this can be removed later on after the follow-up PR is merged (currently this is also not really working in all cases since this is not doing a full traversal of the query node)

File: src/include/duckdb/main/external_dependencies.hpp [hunk 4]
```diff
@@ -6,17 +6,73 @@
...
 
+#include "duckdb/common/case_insensitive_map.hpp"
+#include <functional>
+
 #pragma once
 
 namespace duckdb {
 
-enum class ExternalDependenciesType : uint8_t { PYTHON_DEPENDENCY };
+enum class ExternalDependencyItemType : uint8_t { PYTHON_DEPENDENCY };
```
Comment (Mytherin) [inline src/include/duckdb/main/external_dependencies.hpp:16]: Can we remove the `ExternalDependencyItemType` and use dynamic casts instead like the `FunctionData`? This is used exclusively in extensions/clients/etc that the core cannot know about so having an enum in the core can never be exhaustive anyway

File: tools/pythonpkg/src/python_replacement_scan.cpp [hunk 5]
```diff
@@ -0,0 +1,203 @@
...
+		}
+	}
+
+	unique_ptr<TableRef> result;
+	result = ReplaceInternal(context, table_name);
+	if (!result) {
+		return nullptr;
+	}
+	if (table_ref.external_dependency) {
+		D_ASSERT(result->external_dependency);
```
Comment (Mytherin) [inline tools/pythonpkg/src/python_replacement_scan.cpp:192]: Note: this can also be removed when the CTE solution is in-place most likely

**Review by Mytherin — COMMENTED** [review]
Thanks! Looks great - some minor comments:

**Comment by Tishj** [comment]
<https://github.com/duckdb/duckdb/actions/runs/8953338506/job/24591737145?pr=11761> needs to be restarted, unrelated failure fixed by https://github.com/duckdblabs/duckdb-internal/issues/1971
