### PR TITLE
fix(#8441): some filter expressions can not be pushed down

### LINKED ISSUE #8441: filtering on predictate involving RANDOM() yields unexpected results
### What happens?

Filtering on a predicate derived from the RANDOM() function occasionally yields results where the value is == false.

I'm seeing this behaviour in python library and OS X CLI.  I was implementing weighted random sampling, so am not using the built in SAMPLE functionality.

### To Reproduce

Reproducing on the terminal.

It involves the RANDOM() function, so you may need to run it a couple of times, but for me in most cases this yields results where the column `random_sampled` == false
```
echo "
WITH samples AS (
        SELECT
                n,
                CAST(FLOOR(RANDOM()*n) AS INT) AS n_sample
        FROM (
                VALUES (1), (2), (2), (2), (2), (2), (2), (2), (2), (2), (2), (2), (2), (2), (2), (2), (20), (100)) AS t(n)
),

test AS (
        SELECT
                n,
                n_sample,
                n_sample >= 1 AS random_sampled
        FROM samples
)

SELECT
        *
FROM test
WHERE random_sampled
" | ./duckdb
┌───────┬──────────┬────────────────┐
│   n   │ n_sample │ random_sampled │
│ int32 │  int32   │    boolean     │
├───────┼──────────┼────────────────┤
│     2 │        1 │ true           │
│     2 │        0 │ false          │
│     2 │        1 │ true           │
│     2 │        0 │ false          │
│     2 │        0 │ false          │
│     2 │        0 │ false          │
│     2 │        1 │ true           │
│     2 │        1 │ true           │
│     2 │        1 │ true           │
│     2 │        0 │ false          │
│    20 │       15 │ true           │
│   100 │       62 │ true           │
├───────┴──────────┴────────────────┤
│ 12 rows                 3 columns │
└───────────────────────────────────┘

### OS:

os x arm64

### DuckDB Version:

0.8.1

### DuckDB Client:

python, CLI

### Full Name:

Robert Kyle

### Affiliation:

Personal - no affiliation

### Have you tried this on the latest `master` branch?

I have tested with a master build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by Reminiscent**
fix https://github.com/duckdb/duckdb/issues/8441

Before this PR
```
D explain select rnd, rnd < 0.5 from (select random()) as t(rnd) where rnd < 0.5;

┌─────────────────────────────┐
│┌───────────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│            rnd            │
│        (rnd < 0.5)        │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          random()         │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│           FILTER          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│      (random() < 0.5)     │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 0           │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│         DUMMY_SCAN        │
└───────────────────────────┘
```

We can find there are two `random` function in the plan. The reason is that when we try to push down the expression below the `projection`, we just replace the expression. But if the column in `projection` is generated by the function which has side effects. We shouldn't push down the related expressions. In this case, when we try to push down the filter conditions `rnd < 0.5`, we should check the whether the column `rnd` in the `projection` lists have side effect or not. If it has side effects, we should keep the filter expressions and add an extra filter above the `projection` operator.

After this PR
```
D explain select rnd, rnd < 0.5 from (select random()) as t(rnd) where rnd < 0.5;

┌─────────────────────────────┐
│┌───────────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│            rnd            │
│        (rnd < 0.5)        │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│           FILTER          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│        (rnd < 0.5)        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 0           │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          random()         │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│         DUMMY_SCAN        │
└───────────────────────────┘  
```

### CODE REVIEW

File: src/optimizer/pushdown/pushdown_projection.cpp [hunk 1]
```diff
@@ -6,6 +6,23 @@
...
+		D_ASSERT(colref.binding.table_index == proj.table_index);
+		D_ASSERT(colref.binding.column_index < proj.expressions.size());
+		D_ASSERT(colref.depth == 0);
+		if (proj.expressions[colref.binding.column_index]->HasSideEffects()) {
+			return true;
+		}
+		return false;
+	}
+	bool has_side_effects = false;
+	ExpressionIterator::EnumerateChildren(
```
Comment (Tishj) [inline src/optimizer/pushdown/pushdown_projection.cpp:21]: I'm not sure if this is necessary as `HasSideEffects` is already recursive for expressions that have children

File: src/optimizer/pushdown/pushdown_projection.cpp [hunk 2]
```diff
@@ -6,6 +6,23 @@
 
 namespace duckdb {
 
+static bool HasSideEffects(LogicalProjection &proj, const unique_ptr<Expression> &expr) {
+	if (expr->type == ExpressionType::BOUND_COLUMN_REF) {
+		auto &colref = expr->Cast<BoundColumnRefExpression>();
+		D_ASSERT(colref.binding.table_index == proj.table_index);
+		D_ASSERT(colref.binding.column_index < proj.expressions.size());
+		D_ASSERT(colref.depth == 0);
```
Comment (Tishj) [inline src/optimizer/pushdown/pushdown_projection.cpp:14]: Can you add a test where all of this plays out within a subquery? essentially nesting it:
```sql
select * from (select rnd from (select random()) as t(rnd) where rnd < 0.5);
```

File: src/optimizer/pushdown/pushdown_projection.cpp (hunk 1 above)
Comment (Reminiscent) [reply src/optimizer/pushdown/pushdown_projection.cpp:21]: Yes, you are right. I'll fix it later. thanks!

File: src/optimizer/pushdown/pushdown_projection.cpp (hunk 2 above)
Comment (Reminiscent) [reply src/optimizer/pushdown/pushdown_projection.cpp:14]: Add it. Thanks!

File: src/optimizer/pushdown/pushdown_projection.cpp (hunk 1 above)
Comment (Tishj) [reply src/optimizer/pushdown/pushdown_projection.cpp:21]: Ah right, that makes sense, there is a layer of indirection that I was missing.

That checks out, thanks for clarifying 👍

File: test/optimizer/pushdown/filter_cannot_pushdown.test [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+----
+logical_opt	<REGEX>:.*rnd < 0.3.*
+
+query II
+explain select * from (select rnd, a from (select random() as rnd, a from t) where rnd < 0.3 and a > 1)
+----
+logical_opt	<REGEX>:.*rnd < 0.3.*
+
+query II
+explain select rnd, a from (select random() as rnd, a from t) where rnd < 0.3 and a > 1;
```
Comment (Tmonster) [inline test/optimizer/pushdown/filter_cannot_pushdown.test:36]: might also add a test case like 

`explain select rnd, a from (select random(), 2 as 'a') as t(rnd, a) where rnd < 1 and a > 0;`

I wrote the following case as well 
```
create table t1 as select range as a, random() as b from range(10);
explain select a, b from (select random(), a, b from t1) as t(rnd, a, b) where rnd < 1 and a > 0;
```

And it seems to have a different plan than master duckdb. 
Master 
```
┌─────────────────────────────┐
│┌───────────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐
│           FILTER          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│      (random() < 1.0)     │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 0           │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         SEQ_SCAN          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             t1            │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             a             │
│             b             │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│ Filters: a>0 AND a IS NOT │
│            NULL           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 0           │
└───────────────────────────┘
D
```

your branch 
```
┌─────────────────────────────┐
│┌───────────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             #1            │
│             #2            │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│           FILTER          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│        (rnd < 1.0)        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 10          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          random()         │
│             a             │
│             b             │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         SEQ_SCAN          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             t1            │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             a             │
│             b             │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│ Filters: a>0 AND a IS NOT │
│            NULL           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 0           │
└───────────────────────────┘
```

Why is there now an extra projection for the random?

Comment (Reminiscent) [reply test/optimizer/pushdown/filter_cannot_pushdown.test:36]: I think this case is a little bit special. You can see my plan, you will find that if the filter not be pushed down below the projection, it will reference the column `rnd` and the top projection needs to eliminate the column `rnd`.


But you can see the master plan, if the filter can be pushed down below the projection. The origin logical plan will be `SQL_SCAN -> Filter(random()) -> PROJECTION(a, b)`. And the optimizer will analyze the plan, it will find the column `rnd` are not been used. So in the `SEQ_SCAN`, we don't need to extract the column `rnd`. We only needs the column `a` and column `b`. So the projection in the top is same, it also needs the column `a` and column `b`. So the projection can be removed. That's why the final plan in the master branch has no projection.

**Comment by hannes** [comment]
@Reminiscent thanks for the PR, please make sure to address the comments by Thijs and Tom.

**Comment by Reminiscent** [comment]
> @Reminiscent thanks for the PR, please make sure to address the comments by Thijs and Tom.

Thanks for your comment. I'll address the comments by Thijs and Tom.

File: test/optimizer/pushdown/filter_cannot_pushdown.test (hunk 3 above)
Comment (Reminiscent) [reply test/optimizer/pushdown/filter_cannot_pushdown.test:36]: @Tmonster Thanks for your comments. So, do you think the new plan is acceptable? And I'll add these test cases later.

File: test/optimizer/pushdown/filter_cannot_pushdown.test [hunk 4]
```diff
@@ -0,0 +1,51 @@
+# name: test/optimizer/pushdown/filter_cannot_pushdown.test
+# description: Test Filter Can Not Push Down
+# group: [pushdown]
+
+require skip_reload
```
Comment (Tmonster) [inline test/optimizer/pushdown/filter_cannot_pushdown.test:5]: why do you need skip reload?

File: test/optimizer/pushdown/filter_cannot_pushdown.test (hunk 3 above)
Comment (Tmonster) [reply test/optimizer/pushdown/filter_cannot_pushdown.test:36]: new plan is good

**Review by Tmonster — APPROVED** [review]
Might also be good to have a test like 
```
loop i 1 100

query II
select rnd > 0.5 from (select random()) as t(rnd) where rnd < 0.5;
----
False

endloop
```

currently in master this test will fail. Eventually the second random call will produce a random over 0.5, which will then result in true, when it should be false

File: test/optimizer/pushdown/filter_cannot_pushdown.test (hunk 4 above)
Comment (Reminiscent) [reply test/optimizer/pushdown/filter_cannot_pushdown.test:5]: Sry, that's my mistake. I'll remove it.

**Comment by Reminiscent** [comment]
> Might also be good to have a test like
> 
> ```
> loop i 1 100
> 
> query II
> select rnd > 0.5 from (select random()) as t(rnd) where rnd < 0.5;
> ----
> False
> 
> endloop
> ```
> 
> currently in master this test will fail. Eventually the second random call will produce a random over 0.5, which will then result in true, when it should be false

I change this test case a little bit different. Because sometimes the origin test case will generate the empty result. If the `rnd > 0.5`, it can not be passed through the filter. So I just union all the result with the single false. So the answer will be two false or one false. After use the group by, we can check whether the final result is single false or not.

**Comment by Reminiscent** [comment]
@Tmonster  @Tishj  Thanks for your comments. All comments have been addressed. PTAL

**Comment by Tishj** [comment]
> > Might also be good to have a test like
> > 
> > ```
> > loop i 1 100
> > 
> > query II
> > select rnd > 0.5 from (select random()) as t(rnd) where rnd < 0.5;
> > ----
> > False
> > 
> > endloop
> > ```
> > 
> > currently in master this test will fail. Eventually the second random call will produce a random over 0.5, which will then result in true, when it should be false
> 
> I change this test case a little bit different. Because sometimes the origin test case will generate the empty result.

Hmm that makes sense, maybe create a table(impossible boolean) and insert into it in the loop, then finally select the results where `impossible = true`, should have no results

**Comment by Reminiscent** [comment]
> > > Might also be good to have a test like
> > > ```
> > > loop i 1 100
> > > 
> > > query II
> > > select rnd > 0.5 from (select random()) as t(rnd) where rnd < 0.5;
> > > ----
> > > False
> > > 
> > > endloop
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > currently in master this test will fail. Eventually the second random call will produce a random over 0.5, which will then result in true, when it should be false
> > 
> > 
> > I change this test case a little bit different. Because sometimes the origin test case will generate the empty result.
> 
> Hmm that makes sense, maybe create a table(impossible boolean) and insert into it in the loop, then finally select the results where `impossible = true`, should have no results

@Tishj Yes, you are right. Do you think it's necessary to add an extra test case like you said or now is OK?

**Comment by Reminiscent** [comment]
> Nah your test serves the same purpose, looks good 👍
> 
> EDIT: UNION ALL doesn't do duplicate elimination right? So the result could be two rows of False this way, no?

Yes. The result will be two false or one false. We only need to guarentee there are no true value have been generated.

**Comment by Reminiscent** [comment]
@Tishj @Tmonster Hi, All comments are addressed. Can you help me to take a look again. Thanks!

**Comment by Tmonster** [comment]
looks good to me, thank you for finding this issue and fixing it!

**Review by Tmonster — APPROVED** [review]

**Comment by hannes** [comment]
No need to @ me or anyone else. We see all PR's and comments on them.
