### PR TITLE
Issue #8937: Window Order Collation

### LINKED ISSUE #8937: COLLATE order not working in window functions
### What happens?

When applying a COLLATE to a window function the order uses the default behavior.

### To Reproduce

This shows that the order in the array agg does not change when using a window funciton
```
select
    *,
    array_agg(col) over(partition by id order by col) as lead_col,
    array_agg(col) over(partition by id order by col collate nocase) as lead_col_nocase
from (select unnest(array[1, 1, 1, 1]) as id, unnest(array['A', 'a', 'b', 'B']) as col)
```
This shows that the collate does change the order outside of the window function
```
select
    *
from (select unnest(array[1, 1, 1, 1]) as id, unnest(array['A', 'a', 'b', 'B']) as col) order by col collate nocase
```

### OS:

macos 

### DuckDB Version:

0.8.1

### DuckDB Client:

Datagrip JBDC

### Full Name:

Thomas Boles

### Affiliation:

SaaSWorks Inc.

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by hawkfish**
Restore any collation expression so that the sort will be executed correctly.

fixes: #8937
fixes: duckdblabs/duckdb-internal#308

### CODE REVIEW

File: src/planner/binder/expression/bind_window_expression.cpp [hunk 1]
```diff
@@ -139,6 +139,12 @@ BindResult BaseSelectBinder::BindWindow(WindowExpression &window, idx_t depth) {
 	}
 	for (auto &order : window.orders) {
 		BindChild(order.expression, depth, error);
+		if (error.empty()) {
+			//	Restore any collation expressions
+			auto &order_expr = order.expression;
+			auto &bound_order = BoundExpression::GetExpression(*order_expr);
+			ExpressionBinder::PushCollation(context, bound_order, bound_order->return_type, false);
```
Comment (Mytherin) [inline src/planner/binder/expression/bind_window_expression.cpp:146]: Can this be done instead after the `if (!error.empty())` on line 156?

I'm not sure if this matters but in the current state this code can be executed multiple times in case of correlated subqueries where we have stacked binders.

**Comment by Mytherin** [comment]
Thanks!
