### PR TITLE
[Python Dev] Make `pandas` not required in a couple places, check if it's installed in others

### LINKED ISSUE #16339: Python API: .to_df() segfaults when NumPy is installed but Pandas is missing
### What happens?

Calling `.to_df()` in the Python API causes a segmentation fault if NumPy is installed but Pandas is not. Ideally, the function should raise a clear error indicating that Pandas is required.

### To Reproduce

```
% uv venv venv
Using CPython 3.13.2 interpreter at: /usr/bin/python3
Creating virtual environment at: venv
Activate with: source venv/bin/activate
% . venv/bin/activate
% uv pip install duckdb numpy
Using Python 3.13.2 environment at: venv
Resolved 2 packages in 24ms
Installed 2 packages in 16ms
 + duckdb==1.2.0
 + numpy==2.2.3
% python3
Python 3.13.2 (main, Feb  5 2025, 01:23:35) [GCC 14.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import duckdb
>>> r = duckdb.read_csv('/etc/hostname')
>>> r.to_df()
zsh: segmentation fault  python3
```

```
% python3
Python 3.12.8 (main, Dec  3 2024, 18:42:41) [Clang 16.0.0 (clang-1600.0.26.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import duckdb
>>> r = duckdb.read_csv('/etc/xtab')
>>> r.to_df()
zsh: segmentation fault  python3
```

### OS:

Debian Linux testing aarch64, macOS Sonama 14.6.1 M3 Pro

### DuckDB Version:

1.2.0

### DuckDB Client:

Python

### Hardware:

_No response_

### Full Name:

NODA Kai

### Affiliation:

Independent

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [x] Yes, I have

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #16339

### CODE REVIEW

File: tools/pythonpkg/src/pandas/analyzer.cpp [hunk 1]
```diff
@@ -467,12 +467,11 @@ LogicalType PandasAnalyzer::InnerAnalyze(py::object column, bool &can_convert, i
 	if (rows == 0) {
 		return LogicalType::SQLNULL;
 	}
+	auto &import_cache = *DuckDBPyConnection::ImportCache();
+	auto pandas_series = import_cache.pandas.Series(false);
```
Comment (Tishj) [inline tools/pythonpkg/src/pandas/analyzer.cpp:471]: Hmm this is now not even attempting to import pandas, which I thought would be correct..

Since this is pandas analyze, if pandas wasn't imported by the user - there is nothing to analyze.

But I think that's incorrect, a bit of a misnomer kinda

**Comment by Mytherin** [comment]
Thanks for the PR! LGTM - should we backport some of these to `v1.2.1`?

**Comment by Mytherin** [comment]
Thanks!
