### PR TITLE
Don't create config folder on extension listing

### LINKED ISSUE #15471: listing extensions creates $HOME/.duckdb/
### What happens?

Listing installed extensions, even against an in-memory database creates a `.duckdb/`  directory in the user's home directory.

### To Reproduce

Merely running 
```
$ duckdb
```

```
SELECT extension_name, installed, description
FROM duckdb_extensions();
```

will create a `$HOME/.duckdb`  directory if none exists

### OS:

x86_64 ubuntu 24.04

### DuckDB Version:

1.1.3

### DuckDB Client:

CLI

### Hardware:

_No response_

### Full Name:

Pete Fein

### Affiliation:

Snakedev

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by lcostantino**
Not sure if this is needed, but whenever extensions are listed if .duckdb folder is not existent it won't be created by default.

Closes: #15471

### CODE REVIEW

File: src/main/extension/extension_install.cpp [hunk 1]
```diff
@@ -88,6 +88,9 @@ string ExtensionHelper::ExtensionDirectory(DatabaseInstance &db, FileSystem &fs)
 		// expand ~ in extension directory
 		extension_directory = fs.ExpandPath(extension_directory);
 		if (!fs.DirectoryExists(extension_directory)) {
+			if (!create) {
+				return extension_directory;
+			}
```
Comment (carlopi) [inline src/main/extension/extension_install.cpp:93]: There is a corner case where `extension_directory` exists, and the subdirectories are still created.

Possibly create should wrap all calls of `CreateDirectory` (2 locations).

File: src/include/duckdb/main/extension_helper.hpp [hunk 2]
```diff
@@ -120,8 +120,8 @@ class ExtensionHelper {
 	static ExtensionUpdateResult UpdateExtension(ClientContext &context, const string &extension_name);
 
 	//! Get the extension directory base on the current config
-	static string ExtensionDirectory(ClientContext &context);
-	static string ExtensionDirectory(DatabaseInstance &db, FileSystem &fs);
+	static string ExtensionDirectory(ClientContext &context, bool create = true);
```
Comment (Mytherin) [inline src/include/duckdb/main/extension_helper.hpp:123]: For clarity can we add this functionality as a separate method - `GetExtensionDirectoryPath` - which only returns the path (i.e. runs the first part of the current `ExtensionDirectory` function)? Then `ExtensionDirectory` can call that method and do the creation.

Comment (lcostantino) [reply src/include/duckdb/main/extension_helper.hpp:123]: Sure

**Comment by Mytherin** [comment]
Thanks!
