### PR TITLE
[Map] Fix map_extract from multiple rows

### LINKED ISSUE #4590: map[entry] used in multi-row case, but return Incorrect results
### What happens?

map[entry] used in multi-row case, but return Incorrect results, some map[entry] no results.

### To Reproduce

```
create table t1 (id int, k float8[], v numeric[]);

insert into t1 
select 
generate_series, 
[(random()*100)::float8, (random()*100)::float8, (random()*100)::float8, (random()*100)::float8], 
[(random()*100)::numeric, (random()*100)::numeric, (random()*100)::numeric, (random()*100)::numeric]
from generate_series(1,1000);


select * from t1 limit 10;
┌────┬─────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────┐
│ id │                                        k                                        │                v                 │
├────┼─────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────┤
│ 1  │ [11.16937385200741, 95.8525169631123, 14.96787912095149, 91.43671728471217]     │ [92.021, 35.289, 39.456, 87.582] │
│ 2  │ [17.423948183987278, 84.25555633945753, 4.3259101929901895, 16.98639854252953]  │ [93.521, 72.287, 35.128, 90.006] │
│ 3  │ [92.2745976346253, 95.69644112971064, 62.07402224235098, 73.28854870826204]     │ [78.309, 66.085, 4.861, 91.508]  │
│ 4  │ [86.89964604258995, 98.16639474550412, 91.14385554360781, 34.335507041387146]   │ [49.390, 15.129, 50.420, 40.268] │
│ 5  │ [19.39417378031513, 79.37516113262977, 11.292100746951089, 38.22825377300108]   │ [84.122, 82.529, 13.576, 58.504] │
│ 6  │ [90.70183636869812, 40.517623149910385, 26.8095445183128, 7.944494697252404]    │ [26.349, 29.863, 84.530, 43.415] │
│ 7  │ [54.61782919117665, 65.90019005022482, 61.10493819255031, 49.45131010595972]    │ [64.396, 74.232, 14.787, 32.315] │
│ 8  │ [2.3417069814963516, 88.03378650639992, 12.379745303741597, 18.882166458964853] │ [79.234, 43.398, 54.175, 47.952] │
│ 9  │ [22.776224842010116, 18.045670007831806, 74.94138262116849, 35.122861558367234] │ [7.719, 69.285, 85.415, 11.131]  │
│ 10 │ [56.16691286120725, 2.420740877841772, 77.54608254822578, 95.03478701110808]    │ [68.135, 62.069, 89.292, 21.453] │
└────┴─────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────┘

create table t2 (id int, v_map map(float8, numeric), k float8[]); 
insert into t2 select id, map(k,v), k from t1;


select * from t2 limit 10;
┌────┬────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────┐
│ id │                                       v_map                                        │                                        k                                        │
├────┼────────────────────────────────────────────────────────────────────────────────────┼─────────────────────────────────────────────────────────────────────────────────┤
│ 1  │ {11.16937385200741=92.021, 95.8525169631123=35.289, 14.96787912095149=39.456, 9... │ [11.16937385200741, 95.8525169631123, 14.96787912095149, 91.43671728471217]     │
│ 2  │ {17.423948183987278=93.521, 84.25555633945753=72.287, 4.3259101929901895=35.128... │ [17.423948183987278, 84.25555633945753, 4.3259101929901895, 16.98639854252953]  │
│ 3  │ {92.2745976346253=78.309, 95.69644112971064=66.085, 62.07402224235098=4.861, 73... │ [92.2745976346253, 95.69644112971064, 62.07402224235098, 73.28854870826204]     │
│ 4  │ {86.89964604258995=49.390, 98.16639474550412=15.129, 91.14385554360781=50.420, ... │ [86.89964604258995, 98.16639474550412, 91.14385554360781, 34.335507041387146]   │
│ 5  │ {19.39417378031513=84.122, 79.37516113262977=82.529, 11.292100746951089=13.576,... │ [19.39417378031513, 79.37516113262977, 11.292100746951089, 38.22825377300108]   │
│ 6  │ {90.70183636869812=26.349, 40.517623149910385=29.863, 26.8095445183128=84.530, ... │ [90.70183636869812, 40.517623149910385, 26.8095445183128, 7.944494697252404]    │
│ 7  │ {54.61782919117665=64.396, 65.90019005022482=74.232, 61.10493819255031=14.787, ... │ [54.61782919117665, 65.90019005022482, 61.10493819255031, 49.45131010595972]    │
│ 8  │ {2.3417069814963516=79.234, 88.03378650639992=43.398, 12.379745303741597=54.175... │ [2.3417069814963516, 88.03378650639992, 12.379745303741597, 18.882166458964853] │
│ 9  │ {22.776224842010116=7.719, 18.045670007831806=69.285, 74.94138262116849=85.415,... │ [22.776224842010116, 18.045670007831806, 74.94138262116849, 35.122861558367234] │
│ 10 │ {56.16691286120725=68.135, 2.420740877841772=62.069, 77.54608254822578=89.292, ... │ [56.16691286120725, 2.420740877841772, 77.54608254822578, 95.03478701110808]    │
└────┴────────────────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────────┘



select v_map[array_sort(k, 'DESC', 'NULLS LAST')[1]] from t2 limit 10;
┌───────────────────────────────────────────────┐
│ v_map[array_sort(k, 'DESC', 'NULLS LAST')[1]] │
├───────────────────────────────────────────────┤
│ [35.289]                                      │
│ []                                            │
│ []                                            │
│ []                                            │
│ []                                            │
│ []                                            │
│ []                                            │
│ []                                            │
│ []                                            │
│ []                                            │
└───────────────────────────────────────────────┘

```

### OS:

MacOS

### DuckDB Version:

4.0.1-dev commit: 0d2d7930d2789405a0d07a15e37485fe70faee3e

### DuckDB Client:

CLI

### Full Name:

Digoal Zhou

### Affiliation:

Alibaba

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Tishj**
This PR closes #4590 

`map_extract(map, key)`
What was happening is that map_extract did not use the `key` of the row it's searching, instead it was always using index 0.

### CODE REVIEW

File: src/function/scalar/map/map_extract.cpp [hunk 1]
```diff
@@ -15,11 +15,23 @@ void FillResult(Value &values, Vector &result, idx_t row) {
...
 }
 
+static bool ShouldCastKey(const LogicalType &map_key_type, const LogicalType &indexing_type) {
+	return map_key_type != LogicalTypeId::SQLNULL && map_key_type != indexing_type;
+}
+
+static Value GetKeyToLookFor(Vector &index_vector, idx_t row, const LogicalType &cast_to) {
+	auto key_value = index_vector.GetValue(row);
+	if (cast_to.id() != LogicalTypeId::SQLNULL) {
+		key_value = key_value.CastAs(cast_to);
```
Comment (Mytherin) [inline src/function/scalar/map/map_extract.cpp:30]: Rather than casting here in the function itself, we can set the required target type in the bind (`bound_function.arguments[1] = MapType::KeyType(arguments[0]->return_type)`). That way the system will insert a (more efficient and vectorized) cast and the code here can be simplified.

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Looks good. One comment:

**Comment by Tishj** [comment]
Hmm it seems to be failing on NULL -> TYPE cast
But we don't accept NULL as key anymore, so we can optimize this case to just return an empty list
