### PR TITLE
Qualify macros only when called, and throw error on recursive macros

### LINKED ISSUE #8141: Error when attaching a remote db with FTS
### What happens?

When trying to attach a db that has a fts index, it fails to fetch data using match_bm25 macro.
Error:

```
 line 22, in <module>
    result = con.execute(
duckdb.BinderException: Binder Error: Catalog "index" does not exist!

```

### To Reproduce

```
import duckdb

con = duckdb.connect()

INSTALL_EXTENSION_COMMAND = "INSTALL '{extension}';"
LOAD_EXTENSION_COMMAND = "LOAD '{extension}';"

con.execute(INSTALL_EXTENSION_COMMAND.format(extension="httpfs"))
con.execute(LOAD_EXTENSION_COMMAND.format(extension="httpfs"))
con.execute(INSTALL_EXTENSION_COMMAND.format(extension="fts"))
con.execute(LOAD_EXTENSION_COMMAND.format(extension="fts"))

INDEX_URL = "https://huggingface.co/datasets/asoria/copy_e_glue/resolve/refs%2Fconvert%2Fparquet/default/test/index.duckdb"
ATTACH_COMMAND = f"ATTACH '{INDEX_URL}' as db;"

con.execute(ATTACH_COMMAND)
con.execute("use db;")

query = "denominator"
result = con.execute(
    "SELECT * FROM data WHERE fts_main_data.match_bm25(__hf_index_id, ?) IS NOT NULL;",
    [query],
)

rows = result.df()
print(f"{rows=}")
con.close()
```

### OS:

Ubuntu 22.04.2 LTS x86_64

### DuckDB Version:

0.8.2.dev161

### DuckDB Client:

Python 0.8.2.dev161

### Full Name:

Andrea Soria

### Affiliation:

Hugging Face

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by lnkuiper**
Fixes #8141

### CODE REVIEW

File: src/planner/binder/expression/bind_macro_expression.cpp [hunk 1]
```diff
@@ -79,8 +122,15 @@ BindResult ExpressionBinder::BindMacro(FunctionExpression &function, ScalarMacro
 	new_macro_binding->arguments = &positionals;
 	macro_binding = new_macro_binding.get();
 
-	// replace current expression with stored macro expression, and replace params
+	// replace current expression with stored macro expression
 	expr = macro_def.expression->Copy();
+
+	// detect infinite recursion
+	unordered_set<CatalogEntry *> expanded_macros;
```
Comment (Mytherin) [inline src/planner/binder/expression/bind_macro_expression.cpp:129]: Can this be a `reference_set_t`?

Comment (lnkuiper) [reply src/planner/binder/expression/bind_macro_expression.cpp:129]: Of course!

File: src/planner/binder/expression/bind_macro_expression.cpp [hunk 2]
```diff
@@ -44,6 +44,50 @@ void ExpressionBinder::ReplaceMacroParametersRecursive(unique_ptr<ParsedExpressi
...
+			} else {
+				recursive_macro = &function->Cast<ScalarMacroCatalogEntry>();
+			}
+		}
+		break;
+	}
+	case ExpressionClass::SUBQUERY: {
+		// replacing parameters within a subquery is slightly different
+		auto &sq = (expr->Cast<SubqueryExpression>()).subquery;
+		ParsedExpressionIterator::EnumerateQueryNodeChildren(*sq->node, [&](unique_ptr<ParsedExpression> &child) {
```
Comment (Mytherin) [inline src/planner/binder/expression/bind_macro_expression.cpp:67]: I think that this will not work with `TABLE` macros, correct? i.e. this will still fail:

```sql
create macro m1(a) as a+1;
create macro m2(a) as table select m1(a);
create or replace macro m1(a) as (from m2(42));
select m1(42);
```

I think it might make sense to have an expression recursion limit in the binder similar to what we have in the transformer (look for `StackCheck`). Macros can also be used to circumvent the expression depth limit otherwise which can lead to a stack overflow.

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Looks good - one more comment:

**Comment by lnkuiper** [comment]
I've implemented `StackCheck` in `ExpressionBinder`, seems to work well. I've set the maximum depth to 128. With higher depths, we get stack overflows instead. I hope 128 is OK.

Also, I found a bug unrelated (I think) to this PR:
```
$ duckdb
-- Loading resources from /Users/laurens/.duckdbrc
v0.8.1-dev1402 aada97ec5f
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D drop macro sum;
ABORT THROWN BY INTERNAL EXCEPTION: Database "system" not found
^C[1]    53269 abort (core dumped)  duckdb
```

**Comment by Alex-Monahan** [comment]
I think Python has a 10,000 level default on the stack and it can be edited with a parameter, in case that is helpful!

**Comment by Mytherin** [comment]
> I've implemented `StackCheck` in `ExpressionBinder`, seems to work well. I've set the maximum depth to 128. With higher depths, we get stack overflows instead. I hope 128 is OK.
> 
> Also, I found a bug unrelated (I think) to this PR:
> 
> ```
> $ duckdb
> -- Loading resources from /Users/laurens/.duckdbrc
> v0.8.1-dev1402 aada97ec5f
> Enter ".help" for usage hints.
> Connected to a transient in-memory database.
> Use ".open FILENAME" to reopen on a persistent database.
> D drop macro sum;
> ABORT THROWN BY INTERNAL EXCEPTION: Database "system" not found
> ^C[1]    53269 abort (core dumped)  duckdb
> ```

Could you open an issue with that bug?

**Comment by lnkuiper** [comment]
> Could you open an issue with that bug?

Done #8287

I've also investigated why I could only set the limit to 128, and it's because there's a lot of recursive calls in the Binder, especially when binding table macro's. This is one recursive binding iteration:
```
ExpressionBinder::BindExpression
BaseSelectBinder::BindExpression
ExpressionBinder::BindMacro
ExpressionBinder::BindExpression
ExpressionBinder::BindExpression
BaseSelectBinder::BindExpression
ExpressionBinder::Bind
ExpressionBinder::Bind
Binder::BindSelectNode
Binder::BindNode
Binder::BindNode
Binder::Bind
Binder::Bind
Binder::BindNode
Binder::BindNode
ExpressionBinder::BindExpression
```
In this cycle, the stack counter of `StackCheck` is incremented once (in the main switch in `expression_binder.cpp`), despite there being 16 function calls.

**Comment by Mytherin** [comment]
I wonder if there is any place where a large amount of data is placed onto the stack (e.g. a large array)? 128 does seem very low for a limit. As Alex mentioned Python defaults to 10K, SQLite defaults to 1K.

We might also want to add more recursion checking in e.g. `Binder::BindSelectNode` as well.

**Comment by lnkuiper** [comment]
I don't think any large stack allocations are being done. For every pass through the main switch in `ExpressionBinder`, we have 16 function calls until we increment `StackCheck` again, but only for this specific test case with the recursive table macro. Small stack allocations are being done in some of the 16 function calls.

I've tried again and increased the limit to 425 (that's as far as I went with my binary search). Considering we have 16 function calls per increment, that's a stack depth 425 * 16 = 6800. If we want, we could consider increasing the stack size at compile-time. I could also add a special case to `bind_macro_expression.cpp` to increment the stack counter by more?

**Comment by Mytherin** [comment]
I think perhaps we need to add more instances of the StackChecker along the path then. Shouldn't the stack depth be incremented multiple times as `ExpressionBinder::BindExpression` is called several times in the path?

We should likely also add a stack increment to `Binder::BindNode`.
