### PR TITLE
Fix list_sort segmentation fault regression

### LINKED ISSUE #5694: "segmentation fault" regression since 0.6.0
### What happens?

`INSERT` fails with "segmentation fault" error. The issue exists on 0.6.0 and 0.6.1 and is not reproducible on 0.5.1.

### To Reproduce
Extract the attached 
[jvm_crush5_cp.csv.zip](https://github.com/duckdb/duckdb/files/10225864/jvm_crush5_cp.csv.zip)
to the work directory

`./duckdb`

```
CREATE TABLE t_raw as
  SELECT
    h1, 
    h2, 
    h3,
    CAST(c1 as TIMESTAMP) as c1,
    n1,
    LOWER(TRIM(s)) as s,
    n2
  FROM read_csv_auto('jvm_crush5_cp.csv', ALL_VARCHAR=1);

    CREATE TABLE t_healthy (
        h1 VARCHAR,
        h2 VARCHAR,
        h3 VARCHAR,
        c1 TIMESTAMP,
        n1 INT,
        a VARCHAR[],
        n2 INT,
        PRIMARY KEY(h1, n1)
   );

  INSERT INTO t_healthy
     SELECT
         h1,
         h2,
         h3,
         c1,
         CAST(n1 as INT) as n1,
         list_sort(string_to_array(s, ',')) as a,
         CAST(n2 as INT) as n2
      FROM t_raw
      WHERE (
(n1 = '1' AND s IN ('1822','1823','1824','1825','1826','1827','1828','1829','1830','1831','1832','1833','1834','1835','1836','1837','1838','1839','1840','1841','1842','1843','1844','1845','1846','1847','1848','1849','1850','1851','1852','1853','1854','1855','1856','1857','1858','1859','1860','1861','1862','1863','1864','1865','1866','1867','1868','1869','1870','1871','1872','1873','1874','1875','1876','1877','1878','1879','1880','1881','1882','1883','1884','1885','1886','1887','1888','1889','1890','1891','1892','1893','1894','1895','1896','1897','1898','1899','1900','1901','1902','1903','1904','1905','1906','1907','1908','1909','1910','1911','1912','1913','1914','1915','1916','1917','1918','1919','1920','1921','1922','1923','1924','1925','1926','1927','1928','1929','1930','1931','1932','1933','1934','1935','1936','1937','1938','1939','1940','1941','1942','1943','1944','1945','1946','1947','1948','1949','1950','1951','1952','1953','1954','1955','1956','1957','1958','1959','1960','1961','1962','1963','1964','1965','1966','1967','1968','1969','1970','1971','1972','1973','1974','1975','1976','1977','1978','1979','1980','1981','1982','1983','1984','1985','1986','1987','1988','1989','1990','1991','1992','1993','1994','1995','1996','1997','1998','1999','2000','2001','2002','2003','2004','na'))
);
```
`Segmentation fault`

### OS:

mac os, centos 7

### DuckDB Version:

0.6.0, 0.6.1

### DuckDB Client:

CLI, JDBC

### Full Name:

Andrii Karaivanskyi

### Affiliation:

Indeed

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by taniabogatsch**
This PR fixes #5694. Two issues were causing the bug: (1) the global state was overwritten by different threads (use-after-free), (2) we did not flatten the key_chunk, causing incorrect indexes into the sorted chunk.

### CODE REVIEW

File: src/function/scalar/list/list_sort.cpp [hunk 1]
```diff
@@ -116,10 +116,10 @@ static void ListSortFunction(DataChunk &args, ExpressionState &state, Vector &re
 
 	// initialize the global and local sorting state
 	auto &buffer_manager = BufferManager::GetBufferManager(info.context);
-	info.global_sort_state = make_unique<GlobalSortState>(buffer_manager, info.orders, info.payload_layout);
-	auto &global_sort_state = *info.global_sort_state;
+	unique_ptr<GlobalSortState> global_sort_state;
```
Comment (Mytherin) [inline src/function/scalar/list/list_sort.cpp:119]: Does this still need to be a unique ptr?

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! LGTM. One minor comment:

**Comment by Mytherin** [comment]
Thanks!
