### PR TITLE
[File System] Slightly more flexibility when detecting file compression type

### LINKED ISSUE #10617: sniff_csv fails to detect compression when reading from a url that has a query string
### What happens?

`sniff_csv` fails to  detect compression when reading from a url that has a query string.

For example this statement
```sql
from sniff_csv('https://github.com/duckdb/duckdb/raw/main/data/csv/who.csv.gz?v=1');
```
Fails withs this error
```text
Error: Invalid Input Error: Invalid unicode (byte sequence mismatch) detected in value construction
```

but this statement succeeds
```sql
from sniff_csv('https://github.com/duckdb/duckdb/raw/main/data/csv/who.csv.gz');
```

The root cause of this is in the file at line src/common/virtual_file_system.cpp at line 15 https://github.com/duckdb/duckdb/blob/4d24f5c660a205bf22a7fd99e36efece798452c4/src/common/virtual_file_system.cpp#L15 and could be fixed with a check for url and remove the query string path.

I will open a PR for this.

### To Reproduce

Run this statement
```sql
from sniff_csv('https://github.com/duckdb/duckdb/raw/main/data/csv/who.csv.gz?v=1');
```

### OS:

all

### DuckDB Version:

0.9.3

### DuckDB Client:

all

### Full Name:

Gabriel Hodoroaga

### Affiliation:

Bobsled

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by pdet**
Fix #10617

### CODE REVIEW

File: src/common/virtual_file_system.cpp [hunk 1]
```diff
@@ -14,19 +14,25 @@ unique_ptr<FileHandle> VirtualFileSystem::OpenFile(const string &path, FileOpenF
 	auto compression = flags.Compression();
 	if (compression == FileCompressionType::AUTO_DETECT) {
 		// auto detect compression settings based on file name
+		compression = FileCompressionType::UNCOMPRESSED;
 		auto lower_path = StringUtil::Lower(path);
 		if (StringUtil::EndsWith(lower_path, ".tmp")) {
 			// strip .tmp
 			lower_path = lower_path.substr(0, lower_path.length() - 4);
 		}
-		if (StringUtil::EndsWith(lower_path, ".gz")) {
```
Comment (Mytherin) [inline src/common/virtual_file_system.cpp:22]: When adding the `.wal` suffix we explicitly [consider GET parameters by looking for a question mark](https://github.com/duckdb/duckdb/blob/bd2b98175392833aca33a613d682bb36fc4b6d0e/src/storage/storage_manager.cpp#L92). I think that's a bit cleaner than looking through the entire string for `.gz`. Perhaps we can do something similar here?

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Looks good - one comment:

**Comment by Mytherin** [comment]
Thanks for the changes! Code looks good to me - CI failure seems to be a missing header.

**Comment by Mytherin** [comment]
Thanks!
