### PR TITLE
General ART improvements and memory pressure reduction

### LINKED ISSUE #7406: Avoid excessively calling vacuum during concurrent index operations
### What happens?

Currently, we disable two tests focusing on concurrent index operations, `"Concurrent writes during index creation"` and `"Concurrent appends during index join"` (`test/sql/parallelism/interquery/test_concurrent_index.cpp`). #7372 fixes them; however, they take excessive time to finish.

When profiling the tests, it becomes apparent that most time is spent in the `vacuum` operation of the ART while flushing the changes to storage. This should not be the case, i.e., we first check if a vacuum is necessary and only perform it when passing a threshold. I suspect that the local state in the separate threads either triggers the vacuum for each thread independently (isolation) or that there's a bug in the threshold check.

Screenshot 2023-05-08 at 14 04 42

### To Reproduce

By enabling and running any of the two tests: `"Concurrent writes during index creation"` or `"Concurrent appends during index join"`.

### OS:

iOS

### DuckDB Version:

newest

### DuckDB Client:

CLI / test runner

### Full Name:

Tania Bogatsch

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### LINKED ISSUE #7760: CREATE INDEX ends in out of memory error
### What happens?

I've updated to the 0.8 version: Now I cannot create an index without an error:
CREATE INDEX i ON table (column)
Error: rapi_execute: Failed to run query
Error: Out of Memory Error: failed to allocate data of size 262KB (13.4GB/13.4GB used)

I am working within R, but the error also occurs when I use the console. In the 0.7.1 verison everything works.

I have tried PRAGMA memory_limit='32GB', but that results in the same error:
Error: rapi_execute: Failed to run query
Error: Out of Memory Error: failed to allocate data of size 262KB (31.9GB/32.0GB used)

### To Reproduce

CREATE INDEX i ON table (column)

### OS:

WIN 11

### DuckDB Version:

0.8

### DuckDB Client:

R / Console

### Full Name:

Erdmann

### Affiliation:

viadee

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### LINKED ISSUE #8066: create index causes SIGBUS (Misaligned address error) on MacARM
### What happens?

Crash when creating an index. Couldn't reproduce on Linux, but happens reliably on an m2.

Doesn't happen when in-memory. Doesn't happen if the column is an integer (does happen if its a timestamp or a date). Seems to only happen reliably with a row count > 215 000..but this seems inconsistent and might only be random

### To Reproduce

```
duckdb test.db
v0.8.1 6536a77232
Enter ".help" for usage hints.
D create table t as select now() as d from generate_series(1, 218165);
D create index i on t(d);
Job 1, 'duckdb test.db' terminated by signal SIGBUS (Misaligned address error)
```

### OS:

aarch64

### DuckDB Version:

0.8.1

### DuckDB Client:

-

### Full Name:

Karl Seguin

### Affiliation:

none

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by taniabogatsch**
This PR combines several changes to the ART and mainly focuses on reducing its memory pressure during index creation (`CREATE INDEX`). Combining these changes significantly improves ART creation performance and its memory footprint.

### Disable sorting for `VARCHAR` and compound keys

Before this PR, we always add a sorting operator to the pipeline preceding the index creation operator. Especially for `VARCHAR` keys and compound keys, this sorting operation significantly blew up the memory. 

Now, we check the key types during plan creation. If we detect a `VARCHAR` or compound key type, we adjust the pipeline accordingly, i.e., we do not add that sorting operator.

This change has implications for the execution of the create index operator, which previously expected its incoming data to be sorted. We now have to distinguish between the sorted and not sorted cases and only execute the old (faster) `Sink` implementation on sorted data. This is still desirable since the regression in performance is negligible, and the memory pressure decreases significantly. For not sorted data, we now insert the keys key-at-a-time into the thread-local ART of a sink.

### ARTs can now share their memory

Each thread has its local ART. We build a chunk-sized ART with an efficient construction strategy that does not require iterating all keys for every incoming chunk of sorted data. We then merge that chunk-sized ART into the thread-local ART. This merging step is very efficient since all operations are on sorted data.

Before this PR, the chunk-sized ART would allocate its own memory, which would then get appended to the thread-local ART's memory. This significantly blows up the memory, as we preallocate blocks of 256KB.

This PR allows ARTs to share their memory. Consequently, the thread-local ART can now share its memory with the chunk-sized ART, decreasing memory pressure. 

## Performance improvements

Tree structures such as the ART make it tempting to use recursion for simplicity. For specific scenarios, such as many duplicate keys, or very long prefixes, using recursion for some functions can become problematic. The recursion depth incurs significant overhead in function calls.

Therefore, this PR changes some function implementations from recursive to iterative ones (for `Leaf` and `Prefix`).
- Changed functions: `Free`, `Vacuum`, `Deserialize`, `Serialize`

## Benchmarks

I also want to show some benchmark numbers, to highlight the positive effect of the reduction in memory pressure on performance. All the benchmarks can be found in `benchmark/micro/index/create/`.

| Benchmark      | info | master branch | PR |
| ----------- | ----------- | ----------- | ----------- |
| create_art_varchar.benchmark | 28.8M `VARCHAR`, 7.2M distinct, 8GB memory limit | time-out, oom | 11.39 |
| create_art.benchmark | 10M `INT64`, 2.5M distinct | 0.56 | 0.22 |
| create_art_varchar_long.benchmark | 10M long `VARCHAR` | 0.23 | 0.19 |
| create_art_varchar_short.benchmark | 10M short `VARCHAR` | 0.15 | 0.13 |
| create_art_random.benchmark | 10M `INT`, approx. 1M distinct | 0.51 | 0.18 |
| create_art_duplicates.benchmark | 10M `INT`, approx. 100 distinct | bus error | 0.20 |

## Other improvements

- added a benchmark on `VARCHAR` index creation with a memory limit to detect regression on the memory consumption
- fixed ART benchmarks for `DELETE` and `INSERT` operations
- move `Vacuum` to the `Finalize` step of the index creation operation. This is now possible because the thread-local ARTs share their memory.

This PR also closes the following issues.
- Close #8066
- Close #7760
- Close #7406

### CODE REVIEW

File: src/execution/physical_plan/plan_create_index.cpp [hunk 1]
```diff
@@ -68,27 +68,44 @@ unique_ptr<PhysicalOperator> PhysicalPlanGenerator::CreatePlan(LogicalCreateInde
...
-		auto col_expr = make_uniq_base<Expression, BoundReferenceExpression>(new_column_types[i], i);
-		orders.emplace_back(OrderType::ASCENDING, OrderByNullType::NULLS_FIRST, std::move(col_expr));
-		projections.emplace_back(i);
+	// determine if we sort the data prior to index creation
+	// we don't sort, if either VARCHAR or compound key
+	auto perform_sorting = true;
+	if (op.unbound_expressions.size() > 1) {
+		perform_sorting = false;
+	} else if (op.unbound_expressions[0]->return_type.InternalType() == PhysicalType::VARCHAR) {
+		perform_sorting = false;
```
Comment (Mytherin) [inline src/execution/physical_plan/plan_create_index.cpp:77]: Maybe this should also be disabled for lists/structs (although not sure if we support indexes on those in the first place?)

Comment (pdet) [reply src/execution/physical_plan/plan_create_index.cpp:77]: We don't support it in nested types.
(https://github.com/duckdb/duckdb/blob/525b948821318b9b7701256b199fd0f0a84c40ef/src/execution/index/art/art.cpp#L63)

File: test/sql/index/art/memory/test_art_varchar.test_slow [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+statement ok
+CREATE TABLE strings AS
+    SELECT ((i * 95823983533) % 86000000)::VARCHAR AS s1
+        FROM range(7200000) tbl(i);
+
+statement ok
+CREATE TABLE art AS SELECT rpad(s1, 10, '-') AS id FROM strings;
+
+statement ok
+DROP TABLE strings;
```
Comment (pdet) [inline test/sql/index/art/memory/test_art_varchar.test_slow:32]: can't this be done in one query?

File: test/sql/index/art/memory/test_art_varchar.test_slow [hunk 3]
```diff
@@ -0,0 +1,80 @@
...
+
+statement ok
+CREATE INDEX idx ON art USING ART(id);
+
+query I
+SELECT mem_to_bytes(current.memory_usage) > base.usage AND
+       	mem_to_bytes(current.memory_usage) < 4 * base.usage
+FROM base, pragma_database_size() current;
+----
+1
```
Comment (pdet) [inline test/sql/index/art/memory/test_art_varchar.test_slow:80]: If I read this correctly:
This test only checks memory usage after index creation, and it can be anywhere from 1 to 4x the memory usage of just having the table, right?
Does the range need to be that wide? I would assume that for a memory representation when compared to uncompressed varchar columns it wouldn't blow up that much.

The other thing I'm thinking is if we can somehow test memory consumption during one operation, as in, when running the create index you don't get a sneaky memory usage spike
But wasn't the issue 
the index can increase the memory usage

**Review by pdet — CHANGES_REQUESTED** [review]
Tania, great PR! Thanks for it!

I just had some small code nips, and a couple questions about one of the tests!

File: test/sql/index/art/memory/test_art_varchar.test_slow (hunk 3 above)
Comment (taniabogatsch) [reply test/sql/index/art/memory/test_art_varchar.test_slow:80]: > This test only checks memory usage after index creation, and it can be anywhere from 1 to 4x the memory usage of just having the table, right?

Yes.

> Does the range need to be that wide? I would assume that for a memory representation when compared to uncompressed varchar columns it wouldn't blow up that much.

Nice catch, this is probably a relic. I will double-check and see if I can decrease the range.

> The other thing I'm thinking is if we can somehow test memory consumption during one operation, as in, when running the create index you don't get a sneaky memory usage spike

I added a benchmark with a fixed (low) memory limit. If we start spiking the memory usage again, that benchmark will hopefully be very slow due to offloading/ or even time-out. But now I'm thinking that it might be worth adding a few more of these benchmarks...

> But wasn't the issue
the index can increase the memory usage

How do you mean this?

Comment (taniabogatsch) [reply test/sql/index/art/memory/test_art_varchar.test_slow:74]: It does blow up quite a bit, from ~1 GB to ~3 GB. This benchmark has duplicates, so we cannot inline the leaves. Storing the column twice already gives us 2GB (10-byte strings vs 8-byte row IDs). Whatever we gain here from the prefix compression is probably countered by the memory of the nodes... And then we have another GB for the leaves or so. I can look more closely at where the memory goes, exactly (how many of each node and such). Should I? :)

**Comment by Mytherin** [comment]
Thanks! LGTM
