### PR TITLE
[Python] Fix issue with `native` UDFs returning STRUCT items

### LINKED ISSUE #13135: Python UDF with struct return type has incorrect result
### What happens?

The results of a Python UDF returning a struct seem to sometimes have the struct fields and values shuffled.

### To Reproduce

```python
import duckdb


con = duckdb.connect()


def example():
    return {
        "country": "country",
        "postal_code": "postal_code",
        "state": "state",
        "city": "city",
        "street2": "street2",
        "street1": "street1",
    }


return_type = """
STRUCT(
    "street1" STRING,
    "street2" STRING,
    "city" STRING,
    "state" STRING,
    "postal_code" STRING,
    "country" STRING
)
"""

con.create_function("example", example, return_type=return_type)


sol = example()
(res,) = con.sql("SELECT example()").fetchone()

assert res == sol
```

### OS:

Linux x86

### DuckDB Version:

1.0.0

### DuckDB Client:

Python

### Full Name:

Jim Crist-Harif

### Affiliation:

Voltron Data

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #13135

Similar to the behavior enabled by <https://github.com/duckdb/duckdb/pull/10537> this PR allows the keys in the provided dictionary to differ from that in the given target.

As shown by the issue this was previously ignored and assumed to always match.

### CODE REVIEW

File: tools/pythonpkg/src/native/python_conversion.cpp [hunk 1]
```diff
@@ -606,7 +633,7 @@ Value TransformPythonValue(py::handle ele, const LogicalType &target_type, bool
 		PyDictionary dict = PyDictionary(py::reinterpret_borrow<py::object>(ele));
 		switch (target_type.id()) {
 		case LogicalTypeId::STRUCT:
-			return TransformDictionaryToStruct(dict, target_type);
+			return TransformDictionaryToStruct(dict, target_type).DefaultCastAs(target_type);
```
Comment (Mytherin) [inline tools/pythonpkg/src/native/python_conversion.cpp:636]: As we are already doing the re-ordering in the dictionary conversion, do we need to do the cast here as well? Can we perhaps construct the struct in the correct order directly in `TransformDictionaryToStruct`?

**Review by Mytherin — COMMENTED** [review]
Thanks! LGTM - one comment

File: tools/pythonpkg/src/native/python_conversion.cpp (hunk 1 above)
Comment (Tishj) [reply tools/pythonpkg/src/native/python_conversion.cpp:636]: We're not doing the reordering yet, we're only matching the key to the right target type.
I left reordering as a FIXME and let DefaultCastAs deal with it for now

Comment (Mytherin) [reply tools/pythonpkg/src/native/python_conversion.cpp:636]: The re-ordering seems relatively simple no? You already get the target index from `key_mapping[struct_keys[i]]`, all that would be required is resizing the `struct_values` array to `dict.len`, and then assigning to the target index instead of emplacing.

It's probably not performance sensitive code but casting is adding extra cost as we will be binding the cast for every value, in addition to doing the key look-ups multiple times.

Comment (Tishj) [reply tools/pythonpkg/src/native/python_conversion.cpp:636]: Yea you're right, I think it will be trivial I just wanted to put it off for later, but I'll address the FIXME 👍

Comment (Tishj) [reply tools/pythonpkg/src/native/python_conversion.cpp]: Fixed it

**Comment by Mytherin** [comment]
Thanks!
