### PR TITLE
Optimize Limited Distinct

### LINKED ISSUE #21002: Out Of Memory Error for "select distinct .. limit"
### What happens?

When using select distinct .. **limit** there is an Out Of Memory Error if the number of distinct values is high, despite the use of limit. I would expect the query to stop once the number of values specified in limit is reached but according to the plan all the distinct values are determined first, and then the limit is applied.

At the moment we have to guard against the OOM by calling "select approx_count_distinct(n) from abc" first

### To Reproduce

```sql
PRAGMA memory_limit='1Gb';
create table abc as select md5(random()::VARCHAR) AS n FROM range(100_000_000);
select distinct n from abc limit 10;
```

### OS:

iOS arm64

### DuckDB Version:

1.4.4

### DuckDB Client:

command line

### Hardware:

_No response_

### Full Name:

Thomas Rynne

### Affiliation:

Topaz Technology

### Did you include all relevant configuration (e.g., CPU architecture, Linux distribution) to reproduce the issue?

- [x] Yes, I have

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### PR DESCRIPTION
**Pull request by peterxcli**
fixes: #21002

Introduces a new physical operator, `PhysicalLimitedDistinct`, to optimize queries using `DISTINCT ... LIMIT N` or `GROUP BY ... LIMIT N` by allowing early termination once enough distinct groups are found. 

- Added the `PhysicalLimitedDistinct` operator, which uses a hash table to efficiently stop processing once the required number of distinct groups is found. This operator is implemented in `physical_limited_distinct.cpp` and exposed via a new header. 
- Modified the physical plan generator to select `PhysicalLimitedDistinct` for DISTINCT or GROUP BY queries with a LIMIT, when there are no aggregates or complex grouping sets. - Implemented logic in the LIMIT planner to push down LIMIT hints into child DISTINCT or GROUP BY nodes, enabling early termination for qualifying queries.
- Added an optional `limit` field to both `LogicalAggregate` and `LogicalDistinct` operators to carry the early termination hint through planning.
- Updated parameter reporting for these logical operators to include the limit when present.

Reference from datafusion:
- [`LimitedDistinctAggregation`](https://github.com/apache/datafusion/blob/ffcc7e3af8cfccb0c0705de2112d8277b28114fd/datafusion/physical-optimizer/src/limited_distinct_aggregation.rs)
- [`is_unordered_unfiltered_group_by_distinct`](https://github.com/apache/datafusion/blob/ffcc7e3af8cfccb0c0705de2112d8277b28114fd/datafusion/physical-plan/src/aggregates/mod.rs#L926-L963)
- [`GroupedHashAggregateStream` hit the soft limit then terminate](https://github.com/apache/datafusion/blob/ffcc7e3af8cfccb0c0705de2112d8277b28114fd/datafusion/physical-plan/src/aggregates/row_hash.rs#L738-L745)

### CODE REVIEW

File: src/execution/radix_partitioned_hashtable.cpp [hunk 1]
```diff
@@ -693,6 +693,14 @@ void RadixPartitionedHashTable::SetMultiScan(GlobalSinkState &sink_p) {
 	sink.scan_pin_properties = TupleDataPinProperties::UNPIN_AFTER_DONE;
 }
 
+idx_t RadixPartitionedHashTable::GetLocalGroupCount(LocalSinkState &lstate) {
+	auto &local_state = lstate.Cast<RadixHTLocalSinkState>();
+	if (!local_state.ht) {
+		return 0;
+	}
+	return local_state.ht->GetMaterializedCount();
```
Comment (lnkuiper) [inline src/execution/radix_partitioned_hashtable.cpp]: GetMaterializedCount can return values greater than the total number of groups. RadixPartitionedHashTable has a small fixed-size hash table that is abandoned when it is full. The same group can appear multiple times. I can see this working for small limits, but not limits larger than the fixed HT size. Maybe this optimization should only apply to small limits anyway.

File: src/execution/physical_plan/plan_distinct.cpp [hunk 2]
```diff
@@ -88,6 +88,9 @@ PhysicalOperator &PhysicalPlanGenerator::CreatePlan(LogicalDistinct &op) {
 	auto &group_by = Make<PhysicalHashAggregate>(context, aggregate_types, std::move(aggregates), std::move(groups),
 	                                             child.get().estimated_cardinality);
 	group_by.children.push_back(child);
+	if (op.limit.IsValid()) {
```
Comment (lnkuiper) [inline src/execution/physical_plan/plan_distinct.cpp]: What if it's a `DISTINCT ... ORDER BY ... LIMIT ...`?

This should be resolved as if the `ORDER BY` happens before the `DISTINCT` (which is Postgres semantics). Do we still get correct results then?

File: src/include/duckdb/optimizer/limited_distinct_aggregation.hpp [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+
+#pragma once
+
+#include "duckdb/common/unique_ptr.hpp"
+
+namespace duckdb {
+class LogicalOperator;
+class LimitedDistinctAggregation {
+public:
+	//! Push a LIMIT hint into a DISTINCT operator as its soft limit for early termination.
```
Comment (lnkuiper) [inline src/include/duckdb/optimizer/limited_distinct_aggregation.hpp]: This should also be applicable to `GROUP BY` that do not compute aggregate functions, not just `DISTINCT`

**Review by lnkuiper — CHANGES_REQUESTED** [review]
Thanks for the PR! I think this needs some more testing with larger limits (I think this PR will return incorrect results), and I think that instead of doing this in the optimizer and using the `PhysicalHashAggregate`, we should separate the logic into a different operator that just aggregates in a `GroupedAggregateHashTable`, and then select this operator during physical planning. Since this optimization only applies to very specific queries, I don't think we want to use `PhysicalHashAggregate`/`RadixPartitionedHashTable`, it's not a good fit (these can do partitioning/sorting/distinct aggregation functions), which this optimization does not need.

This removes the need for an optimizer, modifying the hash agg/radix table, and puts all the logic in the physical planner/the new physical operator, which is a lot cleaner (and more correct).

**Comment by peterxcli** [comment]
> This removes the need for an optimizer, modifying the hash agg/radix table, and puts all the logic in the physical planner/the new physical operator, which is a lot cleaner (and more correct).

@lnkuiper Thanks for the suggestion, I refactor this PR to introduce new physical operator, please take another look, thanks!

File: src/include/duckdb/planner/operator/logical_distinct.hpp [hunk 4]
```diff
@@ -28,6 +28,8 @@ class LogicalDistinct : public LogicalOperator {
 	vector<unique_ptr<Expression>> distinct_targets;
 	//! The order by modifier (optional, only for distinct on)
 	unique_ptr<BoundOrderModifier> order_by;
+	//! Optional soft limit for early termination
+	optional_idx limit;
```
Comment (lnkuiper) [inline src/include/duckdb/planner/operator/logical_distinct.hpp]: This should be removed

File: src/planner/operator/logical_aggregate.cpp [hunk 5]
```diff
@@ -78,6 +78,9 @@ InsertionOrderPreservingMap<string> LogicalAggregate::ParamsToString() const {
 		expressions_info += expressions[i]->GetName();
 	}
 	result["Expressions"] = expressions_info;
+	if (limit.IsValid()) {
+		result["Limit"] = to_string(limit.GetIndex());
+	}
```
Comment (lnkuiper) [inline src/planner/operator/logical_aggregate.cpp]: This should be removed

File: src/planner/operator/logical_distinct.cpp [hunk 6]
```diff
@@ -18,6 +18,9 @@ InsertionOrderPreservingMap<string> LogicalDistinct::ParamsToString() const {
 		    StringUtil::Join(distinct_targets, distinct_targets.size(), "\n",
 		                     [](const unique_ptr<Expression> &child) { return child->GetName(); });
 	}
+	if (limit.IsValid()) {
+		result["Limit"] = to_string(limit.GetIndex());
+	}
```
Comment (lnkuiper) [inline src/planner/operator/logical_distinct.cpp]: This should be removed

File: src/include/duckdb/planner/operator/logical_aggregate.hpp [hunk 7]
```diff
@@ -41,6 +41,8 @@ class LogicalAggregate : public LogicalOperator {
 	vector<unique_ptr<BaseStatistics>> group_stats;
 	//! Whether the inputs to all expression are non-NULL
 	TupleDataValidityType distinct_validity;
+	//! Optional soft limit for early termination (GROUP BY without aggregates)
+	optional_idx limit;
```
Comment (lnkuiper) [inline src/include/duckdb/planner/operator/logical_aggregate.hpp]: This should be removed

File: src/execution/physical_plan/plan_aggregate.cpp [hunk 8]
```diff
@@ -296,6 +297,17 @@ PhysicalOperator &PhysicalPlanGenerator::CreatePlan(LogicalAggregate &op) {
...
+	// If we have a limit hint and no aggregate expressions, use PhysicalLimitedDistinct
+	// for plain GROUP BY only. GROUPING SETS / ROLLUP / CUBE need the regular aggregate path.
+	if (op.limit.IsValid() && op.expressions.empty() && op.grouping_sets.size() <= 1 && op.grouping_functions.empty()) {
+		idx_t limit_val = op.limit.GetIndex();
+		vector<unique_ptr<Expression>> empty_aggregates;
+		auto &limited = Make<PhysicalLimitedDistinct>(op.types, std::move(op.groups), std::move(empty_aggregates),
+		                                              limit_val, op.estimated_cardinality);
+		limited.children.push_back(plan);
+		return limited;
+	}
```
Comment (lnkuiper) [inline src/execution/physical_plan/plan_aggregate.cpp]: This should be removed

File: src/execution/physical_plan/plan_distinct.cpp [hunk 9]
```diff
@@ -84,6 +85,19 @@ PhysicalOperator &PhysicalPlanGenerator::CreatePlan(LogicalDistinct &op) {
...
+		auto &limited = Make<PhysicalLimitedDistinct>(aggregate_types, std::move(groups), std::move(aggregates),
+		                                              limit_val, child.get().estimated_cardinality);
+		limited.children.push_back(child);
+		if (!requires_projection) {
+			return limited;
+		}
+		auto &proj = Make<PhysicalProjection>(types, std::move(projections), limited.estimated_cardinality);
+		proj.children.push_back(limited);
+		return proj;
+	}
```
Comment (lnkuiper) [inline src/execution/physical_plan/plan_distinct.cpp]: This should be removed

File: test/sql/aggregate/distinct/distinct_limit.test [hunk 10]
```diff
@@ -0,0 +1,112 @@
+# name: test/sql/aggregate/distinct/distinct_limit.test
+# description: Test DISTINCT with LIMIT early termination using PhysicalLimitedDistinct
+# group: [distinct]
+
+statement ok
+PRAGMA enable_verification
```
Comment (lnkuiper) [inline test/sql/aggregate/distinct/distinct_limit.test]: We have a dedicated CI run where verification is enabled - no need to add this to tests anymore

File: src/execution/physical_plan/plan_limit.cpp [hunk 11]
```diff
@@ -46,8 +48,50 @@ bool UseBatchLimit(PhysicalOperator &child_node, BoundLimitNode &limit_val, Boun
...
+	return false;
+}
+
 PhysicalOperator &PhysicalPlanGenerator::CreatePlan(LogicalLimit &op) {
 	D_ASSERT(op.children.size() == 1);
+
+	// Try to push limit hint into DISTINCT or GROUP BY for early termination
+	// The hint tells the child to stop collecting groups once it has enough.
+	// We still create a physical LIMIT node on top to enforce the actual limit/offset.
+	TryPushLimitIntoChild(op);
```
Comment (lnkuiper) [inline src/execution/physical_plan/plan_limit.cpp]: I think this should be the only place where we deal with limit + distinct. All other places and modifications to operators are unnecessary. We can catch the case here and create the operator.

Maybe you can plan the child first, regardless of whether it's a distinct/groupby, and then the result will be a physical hash aggregate. Then you inspect that and convert it into a limited distinct.

**Review by lnkuiper — COMMENTED** [review]
Thanks for the changes! I've left some more comments. I think it's looking a lot better, but I think it can be minimized to touch less files - a lot of changes are unnecessary.

I would also like to ask for more testing, especially with `distinct on (...) ... from ... order by ...`, which has the semantics of evaluating the order by before the distinct, which we do by pushing an ordered first aggregate. I don't think the optimization should trigger in that case, and this needs to be tested.

**Review by lnkuiper — APPROVED** [review]
Thanks for all the changes! Looks correct and with minimal code footprint now
